oneOS: servers/window_server/Compositor.cpp File Reference
Compositor.cpp File Reference
#include "Compositor.h"
#include "CursorManager.h"
#include "ResourceManager.h"
#include "Screen.h"
#include "Window.h"
#include "WindowManager.h"
#include <libfoundation/EventLoop.h>
#include <libg/Context.h>
#include <std/Memory.h>
Functions
__attribute__ ((flatten)) void Compositor
Variables
static Compositor * s_the
Function Documentation
__attribute__()
__attribute__ ((flatten))
Definition at line 53 of file Compositor.cpp.
 {
     if (m_invalidated_areas.size() == 0) {
         return;
     }
     auto& screen = Screen::the();
     auto& wm = WindowManager::the();
     auto invalidated_areas = move(m_invalidated_areas);
     LG::Context ctx(screen.write_bitmap());
     auto is_window_area_invalidated = [&](const Vector<LG::Rect>& areas, const LG::Rect& area) -> bool {
         for (int i = 0; i < areas.size(); i++) {
             if (area.intersects(areas[i])) {
                 return true;
             }
         }
         return false;
     };
     auto draw_wallpaper_for_area = [&](const LG::Rect& area) {
         ctx.add_clip(area);
         ctx.draw({ 0, 0 }, m_resource_manager.background());
         ctx.reset_clip();
     };
     auto draw_window = [&](Window& window, const LG::Rect& area) {
         ctx.add_clip(area);
         ctx.add_clip(window.bounds());
         window.frame().draw(ctx);
         ctx.draw(window.content_bounds().origin(), window.content_bitmap());
         ctx.reset_clip();
     };
     for (int i = 0; i < invalidated_areas.size(); i++) {
         draw_wallpaper_for_area(invalidated_areas[i]);
     }
     auto* window_ptr = wm.windows().tail();
     while (window_ptr) {
         auto& window = *window_ptr;
         if (is_window_area_invalidated(invalidated_areas, window.bounds())) {
             for (int i = 0; i < invalidated_areas.size(); i++) {
                 draw_window(window, invalidated_areas[i]);
             }
         }
         window_ptr = window_ptr->prev();
     }
     auto mouse_draw_position = m_cursor_manager.draw_position(wm.mouse_x(), wm.mouse_y());
     auto& current_mouse_bitmap = m_cursor_manager.current_cursor();
     for (int i = 0; i < invalidated_areas.size(); i++) {
         ctx.add_clip(invalidated_areas[i]);
         ctx.draw(mouse_draw_position, current_mouse_bitmap);
         ctx.reset_clip();
     }
     screen.swap_buffers();
     copy_changes_to_second_buffer(invalidated_areas);
 }
References LG::Context::add_clip(), ResourceManager::background(), Window::bounds(), Window::content_bitmap(), Window::content_bounds(), Compositor::copy_changes_to_second_buffer(), CursorManager::current_cursor(), LG::Context::draw(), WindowFrame::draw(), CursorManager::draw_position(), Window::frame(), Compositor::m_cursor_manager, Compositor::m_invalidated_areas, Compositor::m_resource_manager, move(), LG::Rect::origin(), LG::Context::reset_clip(), Algo::Vector< T >::size(), Screen::the(), and WindowManager::the().
Variable Documentation
s_the
Compositor* s_the static
Definition at line 19 of file Compositor.cpp.
Referenced by Compositor::Compositor(), and Compositor::the().