oneOS: libs/libcxx/std/Utility.h File Reference
Utility.h File Reference
Functions
template<typename T >
constexpr T min (const T &a, const T &b)
template<typename T >
constexpr T max (const T &a, const T &b)
template<typename T >
T && move (T &arg)
template<typename T , typename U >
void swap (T &a, U &b)
constexpr int abs (int i)
Function Documentation
abs()
constexpr int abs (int i) inline constexpr
Definition at line 29 of file Utility.h.
 {
     return i < 0 ? -i : i;
 }
Referenced by LG::PNG::PNGLoader::paeth_predictor().
max()
template<typename T > constexpr T max (const T & a, const T & b) inline constexpr
Definition at line 10 of file Utility.h.
 {
     return a < b ? b : a;
 }
Referenced by LG::Rect::intersect(), LG::Rect::intersection(), LG::Rect::intersects(), Button::recalc_dims(), LG::Rect::union_of(), and LG::Rect::unite().
min()
template<typename T > constexpr T min (const T & a, const T & b) inline constexpr
Definition at line 4 of file Utility.h.
 {
     return a < b ? a : b;
 }
Referenced by parser.Parser::get_token_at(), LG::Rect::intersect(), LG::Rect::intersection(), LG::Rect::intersects(), LG::Rect::union_of(), and LG::Rect::unite().
move()
template<typename T > T&& move (T & arg) inline
Definition at line 16 of file Utility.h.
 {
     return static_cast<T&&>(arg);
 }
Referenced by __attribute__(), LG::PNG::ScanlineKeeper::add(), LFoundation::EventLoop::add(), Algo::Vector< T >::grow(), DockView::new_fast_launch_entity(), LFoundation::QueuedEvent::operator=(), SendEvent::operator=(), LFoundation::EventLoop::pump(), ClientConnection< ServerDecoder, ClientDecoder >::pump_messages(), Algo::Vector< T >::push_back(), ClientConnection< ServerDecoder, ClientDecoder >::receive_event(), Connection::receive_event(), WindowManager::receive_event(), DockWindow::receive_event(), DockEntity::set_icon(), FastLaunchEntity::set_icon(), Window::set_icon(), FastLaunchEntity::set_path_to_exec(), UI::Label::set_text(), UI::Button::set_title(), Button::set_title(), and swap().
swap()
template<typename T , typename U > void swap (T & a, U & b) inline
Definition at line 22 of file Utility.h.
 {
     U tmp = move((U&)a);
     a = (T &&) move(b);
     b = move(tmp);
 }
References move().