oneOS: src/kernel/drivers/x86/bga.c File Reference
bga.c File Reference
#include <drivers/x86/bga.h>
#include <drivers/driver_manager.h>
#include <errno.h>
#include <fs/devfs/devfs.h>
#include <fs/vfs.h>
#include <log.h>
#include <tasking/proc.h>
#include <tasking/tasking.h>
#include <utils/kassert.h>
#include <drivers/x86/pci.h>
Macros
#define VBE_DISPI_IOPORT_INDEX 0x01CE
#define VBE_DISPI_IOPORT_DATA 0x01CF
#define VBE_DISPI_INDEX_ID 0x0
#define VBE_DISPI_INDEX_XRES 0x1
#define VBE_DISPI_INDEX_YRES 0x2
#define VBE_DISPI_INDEX_BPP 0x3
#define VBE_DISPI_INDEX_ENABLE 0x4
#define VBE_DISPI_INDEX_BANK 0x5
#define VBE_DISPI_INDEX_VIRT_WIDTH 0x6
#define VBE_DISPI_INDEX_VIRT_HEIGHT 0x7
#define VBE_DISPI_INDEX_X_OFFSET 0x8
#define VBE_DISPI_INDEX_Y_OFFSET 0x9
#define VBE_DISPI_DISABLED 0x00
#define VBE_DISPI_ENABLED 0x01
#define VBE_DISPI_LFB_ENABLED 0x40
Functions
static void _bga_write_reg (uint16_t cmd, uint16_t data)
static uint16_t _bga_read_reg (uint16_t cmd)
static void _bga_set_resolution (uint16_t width, uint16_t height)
static int _bga_ioctl (dentry_t *dentry, uint32_t cmd, uint32_t arg)
static proc_zone_t * _bga_mmap (dentry_t *dentry, mmap_params_t *params)
static void bga_recieve_notification (uint32_t msg, uint32_t param)
static driver_desc_t _bga_driver_info ()
void bga_install ()
void bga_init (device_t *dev)
void bga_set_resolution (uint16_t width, uint16_t height)
Variables
static uint16_t bga_screen_width
static uint16_t bga_screen_height
static uint32_t bga_screen_line_size
static uint32_t bga_screen_buffer_size
static uint32_t bga_buf_paddr
Macro Definition Documentation
VBE_DISPI_DISABLED
#define VBE_DISPI_DISABLED 0x00
Definition at line 26 of file bga.c.
VBE_DISPI_ENABLED
#define VBE_DISPI_ENABLED 0x01
Definition at line 27 of file bga.c.
VBE_DISPI_INDEX_BANK
#define VBE_DISPI_INDEX_BANK 0x5
Definition at line 20 of file bga.c.
VBE_DISPI_INDEX_BPP
#define VBE_DISPI_INDEX_BPP 0x3
Definition at line 18 of file bga.c.
VBE_DISPI_INDEX_ENABLE
#define VBE_DISPI_INDEX_ENABLE 0x4
Definition at line 19 of file bga.c.
VBE_DISPI_INDEX_ID
#define VBE_DISPI_INDEX_ID 0x0
Definition at line 15 of file bga.c.
VBE_DISPI_INDEX_VIRT_HEIGHT
#define VBE_DISPI_INDEX_VIRT_HEIGHT 0x7
Definition at line 22 of file bga.c.
VBE_DISPI_INDEX_VIRT_WIDTH
#define VBE_DISPI_INDEX_VIRT_WIDTH 0x6
Definition at line 21 of file bga.c.
VBE_DISPI_INDEX_X_OFFSET
#define VBE_DISPI_INDEX_X_OFFSET 0x8
Definition at line 23 of file bga.c.
VBE_DISPI_INDEX_XRES
#define VBE_DISPI_INDEX_XRES 0x1
Definition at line 16 of file bga.c.
VBE_DISPI_INDEX_Y_OFFSET
#define VBE_DISPI_INDEX_Y_OFFSET 0x9
Definition at line 24 of file bga.c.
VBE_DISPI_INDEX_YRES
#define VBE_DISPI_INDEX_YRES 0x2
Definition at line 17 of file bga.c.
VBE_DISPI_IOPORT_DATA
#define VBE_DISPI_IOPORT_DATA 0x01CF
Definition at line 13 of file bga.c.
VBE_DISPI_IOPORT_INDEX
#define VBE_DISPI_IOPORT_INDEX 0x01CE
Definition at line 12 of file bga.c.
VBE_DISPI_LFB_ENABLED
#define VBE_DISPI_LFB_ENABLED 0x40
Definition at line 28 of file bga.c.
Function Documentation
_bga_driver_info()
static driver_desc_t _bga_driver_info () inline static
Definition at line 122 of file bga.c.
 {
     driver_desc_t bga_desc;
     bga_desc.type = DRIVER_VIDEO_DEVICE;
     bga_desc.auto_start = false;
     bga_desc.is_device_driver = true;
     bga_desc.is_device_needed = false;
     bga_desc.is_driver_needed = false;
     bga_desc.functions[DRIVER_NOTIFICATION] = bga_recieve_notification;
     bga_desc.functions[DRIVER_VIDEO_INIT] = bga_init;
     bga_desc.functions[DRIVER_VIDEO_SET_RESOLUTION] = bga_set_resolution;
     bga_desc.pci_serve_class = 0x03;
     bga_desc.pci_serve_subclass = 0x00;
     bga_desc.pci_serve_vendor_id = 0x1234;
     bga_desc.pci_serve_device_id = 0x1111;
     return bga_desc;
 }
References driver_desc_t::auto_start, bga_init(), bga_recieve_notification(), bga_set_resolution(), DRIVER_NOTIFICATION, DRIVER_VIDEO_DEVICE, DRIVER_VIDEO_INIT, DRIVER_VIDEO_SET_RESOLUTION, driver_desc_t::functions, driver_desc_t::is_device_driver, driver_desc_t::is_device_needed, driver_desc_t::is_driver_needed, driver_desc_t::pci_serve_class, driver_desc_t::pci_serve_device_id, driver_desc_t::pci_serve_subclass, driver_desc_t::pci_serve_vendor_id, and driver_desc_t::type.
Referenced by bga_install().
_bga_ioctl()
static int _bga_ioctl (dentry_t * dentry, uint32_t cmd, uint32_t arg) static
Definition at line 63 of file bga.c.
 {
     uint32_t y_offset = 0;
     switch (cmd) {
     case 0x1:
         log("%x", arg);
         return 0;
     case BGA_SWAP_BUFFERS:
         y_offset = bga_screen_height * (arg & 1);
         _bga_write_reg(VBE_DISPI_INDEX_Y_OFFSET, (uint16_t)y_offset);
         return 0;
     default:
         return -EINVAL;
     }
 }
References _bga_write_reg(), bga_screen_height, BGA_SWAP_BUFFERS, cmd, EINVAL, log(), and VBE_DISPI_INDEX_Y_OFFSET.
Referenced by bga_recieve_notification().
_bga_mmap()
static proc_zone_t* _bga_mmap (dentry_t * dentry, mmap_params_t * params) static
Definition at line 79 of file bga.c.
 {
     bool map_shared = ((params->flags & MAP_SHARED) > 0);
     if (!map_shared) {
         return 0;
     }
     proc_zone_t* zone = proc_new_random_zone(RUNNIG_THREAD->process, bga_screen_buffer_size);
     if (!zone) {
         return 0;
     }
     zone->flags |= ZONE_WRITABLE | ZONE_READABLE;
     for (int offset = 0; offset < bga_screen_buffer_size; offset += VMM_PAGE_SIZE) {
         vmm_map_page(zone->start + offset, bga_buf_paddr + offset, zone->flags);
     }
     return zone;
 }
References bga_buf_paddr, bga_screen_buffer_size, mmap_params::flags, proc_zone::flags, MAP_SHARED, proc_new_random_zone(), RUNNIG_THREAD, proc_zone::start, vmm_map_page(), VMM_PAGE_SIZE, ZONE_READABLE, and ZONE_WRITABLE.
Referenced by bga_recieve_notification().
_bga_read_reg()
static uint16_t _bga_read_reg (uint16_t cmd) inline static
Definition at line 40 of file bga.c.
 {
     port_16bit_out(VBE_DISPI_IOPORT_INDEX, cmd);
     return port_16bit_in(VBE_DISPI_IOPORT_DATA);
 }
References cmd, port_16bit_in(), port_16bit_out(), VBE_DISPI_IOPORT_DATA, and VBE_DISPI_IOPORT_INDEX.
_bga_set_resolution()
static void _bga_set_resolution (uint16_t width, uint16_t height) static
Definition at line 46 of file bga.c.
 {
     _bga_write_reg(VBE_DISPI_INDEX_ENABLE, VBE_DISPI_DISABLED);
     _bga_write_reg(VBE_DISPI_INDEX_XRES, width);
     _bga_write_reg(VBE_DISPI_INDEX_YRES, height);
     _bga_write_reg(VBE_DISPI_INDEX_VIRT_WIDTH, width);
     _bga_write_reg(VBE_DISPI_INDEX_VIRT_HEIGHT, (uint16_t)height * 2);
     _bga_write_reg(VBE_DISPI_INDEX_BPP, 32);
     _bga_write_reg(VBE_DISPI_INDEX_X_OFFSET, 0);
     _bga_write_reg(VBE_DISPI_INDEX_Y_OFFSET, 0);
     _bga_write_reg(VBE_DISPI_INDEX_ENABLE, VBE_DISPI_ENABLED | VBE_DISPI_LFB_ENABLED);
     _bga_write_reg(VBE_DISPI_INDEX_BANK, 0);
     bga_screen_line_size = (uint32_t)width * 4;
 }
References _bga_write_reg(), bga_screen_line_size, VBE_DISPI_DISABLED, VBE_DISPI_ENABLED, VBE_DISPI_INDEX_BANK, VBE_DISPI_INDEX_BPP, VBE_DISPI_INDEX_ENABLE, VBE_DISPI_INDEX_VIRT_HEIGHT, VBE_DISPI_INDEX_VIRT_WIDTH, VBE_DISPI_INDEX_X_OFFSET, VBE_DISPI_INDEX_XRES, VBE_DISPI_INDEX_Y_OFFSET, VBE_DISPI_INDEX_YRES, and VBE_DISPI_LFB_ENABLED.
Referenced by bga_set_resolution().
_bga_write_reg()
static void _bga_write_reg (uint16_t cmd, uint16_t data) inline static
Definition at line 34 of file bga.c.
 {
     port_16bit_out(VBE_DISPI_IOPORT_INDEX, cmd);
     port_16bit_out(VBE_DISPI_IOPORT_DATA, data);
 }
References cmd, port_16bit_out(), VBE_DISPI_IOPORT_DATA, and VBE_DISPI_IOPORT_INDEX.
Referenced by _bga_ioctl(), and _bga_set_resolution().
bga_init()
void bga_init (device_t * dev)
Definition at line 145 of file bga.c.
 {
     bga_buf_paddr = pci_read_bar(dev, 0) & 0xfffffff0;
     bga_set_resolution(1024, 768);
 }
References bga_buf_paddr, bga_set_resolution(), and pci_read_bar().
Referenced by _bga_driver_info().
bga_install()
void bga_install ()
Definition at line 140 of file bga.c.
 {
     driver_install(_bga_driver_info());
 }
References _bga_driver_info(), and driver_install().
Referenced by stage3().
bga_recieve_notification()
static void bga_recieve_notification (uint32_t msg, uint32_t param) static
Definition at line 101 of file bga.c.
 {
     if (msg == DM_NOTIFICATION_DEVFS_READY) {
         dentry_t* mp;
         if (vfs_resolve_path("/dev", &mp) < 0) {
             kpanic("Can't init bga in /dev");
         }
         file_ops_t fops;
         fops.can_read = 0;
         fops.can_write = 0;
         fops.read = 0;
         fops.write = 0;
         fops.ioctl = _bga_ioctl;
         fops.mmap = _bga_mmap;
         devfs_inode_t* res = devfs_register(mp, "bga", 3, 0, &fops);
         dentry_put(mp);
     }
 }
References _bga_ioctl(), _bga_mmap(), file_ops::can_read, file_ops::can_write, dentry_put(), devfs_register(), DM_NOTIFICATION_DEVFS_READY, file_ops::ioctl, kpanic(), file_ops::mmap, file_ops::read, vfs_resolve_path(), and file_ops::write.
Referenced by _bga_driver_info().
bga_set_resolution()
void bga_set_resolution (uint16_t width, uint16_t height)
Definition at line 151 of file bga.c.
 {
     _bga_set_resolution(width, height);
     bga_screen_width = width;
     bga_screen_height = height;
     bga_screen_buffer_size = bga_screen_line_size * (uint32_t)height * 2;
 }
References _bga_set_resolution(), bga_screen_buffer_size, bga_screen_height, bga_screen_line_size, and bga_screen_width.
Referenced by _bga_driver_info(), and bga_init().
Variable Documentation
bga_buf_paddr
uint32_t bga_buf_paddr static
Definition at line 32 of file bga.c.
Referenced by _bga_mmap(), and bga_init().
bga_screen_buffer_size
uint32_t bga_screen_buffer_size static
Definition at line 31 of file bga.c.
Referenced by _bga_mmap(), and bga_set_resolution().
bga_screen_height
uint16_t bga_screen_height static
Definition at line 30 of file bga.c.
Referenced by _bga_ioctl(), and bga_set_resolution().
bga_screen_line_size
uint32_t bga_screen_line_size static
Definition at line 31 of file bga.c.
Referenced by _bga_set_resolution(), and bga_set_resolution().
bga_screen_width
uint16_t bga_screen_width static
Definition at line 30 of file bga.c.
Referenced by bga_set_resolution().