oneOS: include/drivers/x86/bga.h File Reference
bga.h File Reference
#include <types.h>
#include <platform/x86/port.h>
#include <drivers/x86/display.h>
#include <mem/kmalloc.h>
#include <drivers/driver_manager.h>
Functions
void bga_install ()
void bga_init ()
void bga_set_resolution (uint16_t width, uint16_t height)
Function Documentation
bga_init()
void bga_init ()
bga_install()
void bga_install ()
Definition at line 140 of file bga.c.
 {
     driver_install(_bga_driver_info());
 }
References _bga_driver_info(), and driver_install().
Referenced by stage3().
bga_set_resolution()
void bga_set_resolution (uint16_t width, uint16_t height)
Definition at line 151 of file bga.c.
 {
     _bga_set_resolution(width, height);
     bga_screen_width = width;
     bga_screen_height = height;
     bga_screen_buffer_size = bga_screen_line_size * (uint32_t)height * 2;
 }
References _bga_set_resolution(), bga_screen_buffer_size, bga_screen_height, bga_screen_line_size, and bga_screen_width.
Referenced by _bga_driver_info(), and bga_init().