oneOS: include/algo/bitmap.h File Reference
bitmap.h File Reference
#include <types.h>
Data Structures
struct bitmap
Typedefs
typedef struct bitmap bitmap_t
Functions
bitmap_t bitmap_wrap (uint8_t *data, uint32_t len)
bitmap_t bitmap_allocate (uint32_t len)
int bitmap_find_space (bitmap_t bitmap, int req)
int bitmap_set (bitmap_t bitmap, int where)
int bitmap_unset (bitmap_t bitmap, int where)
int bitmap_set_range (bitmap_t bitmap, int start, int len)
int bitmap_unset_range (bitmap_t bitmap, int start, int len)
Typedef Documentation
bitmap_t
typedef struct bitmap bitmap_t
Definition at line 1 of file bitmap.h.
Function Documentation
bitmap_allocate()
bitmap_t bitmap_allocate (uint32_t len)
Definition at line 22 of file bitmap.c.
 {
     uint32_t alloc_len = len / 8;
     if (len % 8) {
         alloc_len++;
     }
     uint8_t* data = kmalloc(alloc_len);
     return bitmap_wrap(data, len);
 }
References bitmap_wrap(), and kmalloc().
bitmap_find_space()
int bitmap_find_space (bitmap_t bitmap, int req)
Definition at line 33 of file bitmap.c.
 {
     int taken = 0;
     int start = 0;
     for (int i = 0; i < bitmap.len; i++) {
         if (bitmap.data[i] == 0xff) {
             continue;
         }
         for (int j = 0; j < 8; j++) {
             if ((bitmap.data[i] >> j) & 1) {
                 taken = 0;
             } else {
                 if (taken == 0) {
                     start = i * 8 + j;
                 }
                 taken++;
                 if (taken == req) {
                     return start;
                 }
             }
         }
     }
     return -ENODATA;
 }
References bitmap::data, ENODATA, and bitmap::len.
Referenced by kmalloc(), shared_buffer_create(), and zoner_new_zone().
bitmap_set()
int bitmap_set (bitmap_t bitmap, int where)
Definition at line 58 of file bitmap.c.
 {
     if (where >= bitmap.len * 8) {
         return -EFAULT;
     }
     int block = where / 8;
     int offset = where % 8;
     bitmap.data[block] |= (1 << offset);
     return 0;
 }
References bitmap::data, EFAULT, and bitmap::len.
Referenced by bitmap_set_range().
bitmap_set_range()
int bitmap_set_range (bitmap_t bitmap, int start, int len)
Definition at line 84 of file bitmap.c.
 {
     for (int i = start; i < start + len; i++) {
         if (bitmap_set(bitmap, i) != 0) {
             return -EPERM;
         }
     }
     return 0;
 }
References bitmap_set(), and EPERM.
Referenced by _kmalloc_init_bitmap(), _shared_buffer_init_bitmap(), kmalloc(), shared_buffer_create(), zoner_new_zone(), and zoner_place_bitmap().
bitmap_unset()
int bitmap_unset (bitmap_t bitmap, int where)
Definition at line 71 of file bitmap.c.
 {
     if (where >= bitmap.len * 8) {
         return -EFAULT;
     }
     int block = where / 8;
     int offset = where % 8;
     bitmap.data[block] &= ~((1 << offset));
     return 0;
 }
References bitmap::data, EFAULT, and bitmap::len.
Referenced by bitmap_unset_range().
bitmap_unset_range()
int bitmap_unset_range (bitmap_t bitmap, int start, int len)
Definition at line 94 of file bitmap.c.
 {
     for (int i = start; i < start + len; i++) {
         if (bitmap_unset(bitmap, i) != 0) {
             return -EPERM;
         }
     }
     return 0;
 }
References bitmap_unset(), and EPERM.
Referenced by kfree(), shared_buffer_free(), and zoner_free_zone().
bitmap_wrap()
bitmap_t bitmap_wrap (uint8_t * data, uint32_t len)
Definition at line 13 of file bitmap.c.
 {
     bitmap_t bitmap;
     bitmap.data = data;
     bitmap.len = len;
     return bitmap;
 }
References bitmap, bitmap::data, and bitmap::len.
Referenced by _kmalloc_init_bitmap(), _shared_buffer_init_bitmap(), bitmap_allocate(), and zoner_place_bitmap().