oneOS: src/kernel/tasking/blocker.c File Reference
blocker.c File Reference
#include <tasking/sched.h>
#include <tasking/thread.h>
#include <time/time_manager.h>
#include <log.h>
Functions
int should_unblock_join_block (thread_t *thread)
int init_join_blocker (thread_t *thread)
int should_unblock_read_block (thread_t *thread)
int init_read_blocker (thread_t *thread, file_descriptor_t *bfd)
int should_unblock_write_block (thread_t *thread)
int init_write_blocker (thread_t *thread, file_descriptor_t *bfd)
int should_unblock_sleep_block (thread_t *thread)
int init_sleep_blocker (thread_t *thread, uint32_t time)
int should_unblock_select_block (thread_t *thread)
int init_select_blocker (thread_t *thread, int nfds, fd_set_t *readfds, fd_set_t *writefds, fd_set_t *exceptfds, timeval_t *timeout)
Function Documentation
init_join_blocker()
int init_join_blocker (thread_t * p)
BLOCKER FUNCTIONS
Definition at line 23 of file blocker.c.
 {
     thread->status = THREAD_BLOCKED;
     thread->blocker.reason = BLOCKER_JOIN;
     thread->blocker.should_unblock = should_unblock_join_block;
     thread->blocker.should_unblock_for_signal = true;
     sched_dequeue(thread);
     resched();
     return 0;
 }
References thread::blocker, BLOCKER_JOIN, blocker::reason, resched(), sched_dequeue(), blocker::should_unblock, blocker::should_unblock_for_signal, should_unblock_join_block(), thread::status, and THREAD_BLOCKED.
Referenced by tasking_waitpid().
init_read_blocker()
int init_read_blocker (thread_t * thread, file_descriptor_t * bfd)
Definition at line 39 of file blocker.c.
 {
     thread->blocker_fd = bfd;
     if (should_unblock_read_block(thread)) {
         return 0;
     }
     thread->status = THREAD_BLOCKED;
     thread->blocker.reason = BLOCKER_READ;
     thread->blocker.should_unblock = should_unblock_read_block;
     thread->blocker.should_unblock_for_signal = true;
     sched_dequeue(thread);
     resched();
     return 0;
 }
References thread::blocker, thread::blocker_fd, BLOCKER_READ, blocker::reason, resched(), sched_dequeue(), blocker::should_unblock, blocker::should_unblock_for_signal, should_unblock_read_block(), thread::status, and THREAD_BLOCKED.
Referenced by sys_read().
init_select_blocker()
int init_select_blocker (thread_t * thread, int nfds, fd_set_t * readfds, fd_set_t * writefds, fd_set_t * exceptfds, timeval_t * timeout)
Definition at line 127 of file blocker.c.
 {
     FD_ZERO(&(thread->readfds));
     FD_ZERO(&(thread->writefds));
     FD_ZERO(&(thread->exceptfds));
     thread->unblock_time = 0;
     if (readfds) {
         thread->readfds = *readfds;
     }
     if (writefds) {
         thread->writefds = *writefds;
     }
     if (exceptfds) {
         thread->exceptfds = *exceptfds;
     }
     if (timeout) {
         thread->unblock_time = timeman_now() + timeout->tv_sec;
     }
     thread->nfds = nfds;
     if (should_unblock_select_block(thread)) {
         return 0;
     }
     thread->status = THREAD_BLOCKED;
     thread->blocker.reason = BLOCKER_SELECT;
     thread->blocker.should_unblock = should_unblock_select_block;
     thread->blocker.should_unblock_for_signal = true;
     sched_dequeue(thread);
     resched();
     return 0;
 }
References thread::blocker, BLOCKER_SELECT, thread::exceptfds, FD_ZERO, thread::nfds, thread::readfds, blocker::reason, resched(), sched_dequeue(), blocker::should_unblock, blocker::should_unblock_for_signal, should_unblock_select_block(), thread::status, THREAD_BLOCKED, timeman_now(), timeval::tv_sec, thread::unblock_time, and thread::writefds.
Referenced by sys_select().
init_sleep_blocker()
int init_sleep_blocker (thread_t * thread, uint32_t time)
Definition at line 83 of file blocker.c.
 {
     thread->unblock_time = timeman_now() + time;
     if (should_unblock_sleep_block(thread)) {
         return 0;
     }
     thread->status = THREAD_BLOCKED;
     thread->blocker.reason = BLOCKER_SLEEP;
     thread->blocker.should_unblock = should_unblock_sleep_block;
     thread->blocker.should_unblock_for_signal = true;
     sched_dequeue(thread);
     resched();
     return 0;
 }
References thread::blocker, BLOCKER_SLEEP, blocker::reason, resched(), sched_dequeue(), blocker::should_unblock, blocker::should_unblock_for_signal, should_unblock_sleep_block(), thread::status, THREAD_BLOCKED, timeman_now(), and thread::unblock_time.
Referenced by sys_sleep().
init_write_blocker()
int init_write_blocker (thread_t * thread, file_descriptor_t * bfd)
Definition at line 61 of file blocker.c.
 {
     thread->blocker_fd = bfd;
     if (should_unblock_write_block(thread)) {
         return 0;
     }
     thread->status = THREAD_BLOCKED;
     thread->blocker.reason = BLOCKER_WRITE;
     thread->blocker.should_unblock = should_unblock_write_block;
     thread->blocker.should_unblock_for_signal = true;
     sched_dequeue(thread);
     resched();
     return 0;
 }
References thread::blocker, thread::blocker_fd, BLOCKER_WRITE, blocker::reason, resched(), sched_dequeue(), blocker::should_unblock, blocker::should_unblock_for_signal, should_unblock_write_block(), thread::status, and THREAD_BLOCKED.
Referenced by sys_write().
should_unblock_join_block()
int should_unblock_join_block (thread_t * thread)
Definition at line 14 of file blocker.c.
 {
     // TODO: Add more checks here.
     if (thread->joinee->status == THREAD_DYING || thread->joinee->status == THREAD_DEAD) {
         return 1;
     }
     return 0;
 }
References thread::joinee, thread::status, THREAD_DEAD, and THREAD_DYING.
Referenced by init_join_blocker().
should_unblock_read_block()
int should_unblock_read_block (thread_t * thread)
Definition at line 34 of file blocker.c.
 {
     return thread->blocker_fd->ops->can_read(thread->blocker_fd->dentry, thread->blocker_fd->offset);
 }
References thread::blocker_fd, file_ops::can_read, file_descriptor::dentry, file_descriptor::offset, and file_descriptor::ops.
Referenced by init_read_blocker().
should_unblock_select_block()
int should_unblock_select_block (thread_t * thread)
Definition at line 100 of file blocker.c.
 {
     if (thread->unblock_time != 0 && thread->unblock_time <= timeman_now()) {
         return true;
     }
     file_descriptor_t* fd;
     for (int i = 0; i < thread->nfds; i++) {
         if (FD_ISSET(i, &thread->readfds)) {
             fd = proc_get_fd(thread->process, i);
             if (fd->ops->can_read(fd->dentry, fd->offset)) {
                 return true;
             }
         }
     }
     for (int i = 0; i < thread->nfds; i++) {
         if (FD_ISSET(i, &thread->writefds)) {
             fd = proc_get_fd(thread->process, i);
             if (fd->ops->can_write(fd->dentry, fd->offset)) {
                 return true;
             }
         }
     }
     return false;
 }
References file_ops::can_read, file_ops::can_write, file_descriptor::dentry, FD_ISSET, thread::nfds, file_descriptor::offset, file_descriptor::ops, proc_get_fd(), thread::process, thread::readfds, timeman_now(), thread::unblock_time, and thread::writefds.
Referenced by init_select_blocker().
should_unblock_sleep_block()
int should_unblock_sleep_block (thread_t * thread)
Definition at line 78 of file blocker.c.
 {
     return thread->unblock_time <= timeman_now();
 }
References timeman_now(), and thread::unblock_time.
Referenced by init_sleep_blocker().
should_unblock_write_block()
int should_unblock_write_block (thread_t * thread)
Definition at line 56 of file blocker.c.
 {
     return thread->blocker_fd->ops->can_write(thread->blocker_fd->dentry, thread->blocker_fd->offset);
 }
References thread::blocker_fd, file_ops::can_write, file_descriptor::dentry, file_descriptor::offset, and file_descriptor::ops.
Referenced by init_write_blocker().