oneOS: src/boot/x86/stage2/drivers/display.c File Reference
display.c File Reference
#include "display.h"
Functions
void print_char (char symbol, unsigned char color, int col, int row)
void print_string (const char *string, unsigned char color, int col, int row)
void print_hex (uint32_t hex, unsigned char color, int col, int row)
void print_dec (uint32_t dec, unsigned char color, int col, int row)
void printf (const char *string)
void printh (uint32_t hex)
void printd (uint32_t dec)
void clean_screen ()
void scroll (unsigned char lines)
void set_cursor_offset (unsigned short offset)
int get_cursor_offet ()
int get_offset (int col, int row)
char col_in_field (int col)
char row_in_field (int row)
Function Documentation
clean_screen()
void clean_screen ()
Definition at line 82 of file display.c.
                     {
     char* mem = VIDEO_MEMORY;
     for (int i = 0; i < 2 * MAX_COLS * MAX_ROWS; i+=2) {
         mem[i] = ' ';
         mem[i+1] = WHITE_ON_BLACK;
     }
     set_cursor_offset(0);
 }
col_in_field()
char col_in_field (int col)
Definition at line 131 of file display.c.
 { return (0 <= col && col <= MAX_COLS); }
Referenced by delete_char(), ext_print_char(), and print_char().
get_cursor_offet()
int get_cursor_offet ()
Definition at line 119 of file display.c.
{
     port_byte_out(REG_SCREEN_CTRL, 14);
     unsigned short offset = port_byte_in(REG_SCREEN_DATA);
     offset <<= 8;
     port_byte_out(REG_SCREEN_CTRL, 15);
     offset += port_byte_in(REG_SCREEN_DATA);
     return offset;
 }
Referenced by delete_char(), ext_print_char(), and print_char().
get_offset()
int get_offset (int col, int row)
Definition at line 130 of file display.c.
 { return row * MAX_COLS + col; }
Referenced by delete_char(), ext_print_char(), and print_char().
print_char()
void print_char (char symbol, unsigned char color, int col, int row)
Definition at line 3 of file display.c.
{
     char* mem = VIDEO_MEMORY;
     unsigned short offset_types[2] = {get_cursor_offet(), get_offset(col, row)};
     unsigned short offset = offset_types[(col_in_field(col) && row_in_field(row))];
     if (symbol == '\n') {
         offset += MAX_COLS - (offset % MAX_COLS) - 1; // -1 to make it works (offset + 1 further)
     } else {
         mem[offset * 2] = symbol;
         mem[offset * 2 + 1] = color;
     }
     if (offset + 1 >= MAX_COLS * MAX_ROWS) {
         scroll(1); // scroll for 1 line
     } else {
         set_cursor_offset(offset+1);
     }
 }
Referenced by kprintf(), print_dec(), print_hex(), and print_string().
print_dec()
void print_dec (uint32_t dec, unsigned char color, int col, int row)
Definition at line 51 of file display.c.
{
     uint32_t pk = 1000000000;
     bool was_not_zero = 0;
     while (pk > 0) {
         uint32_t pp = dec / pk;
         if (was_not_zero || pp > 0) {
             print_char(pp + '0', color, col, row);
             was_not_zero = 1;
         }
         dec -= pp * pk;
         pk /= 10;
     }
     if (!was_not_zero) {
         print_char('0', color, col, row);
     }
 }
Referenced by kprintd(), and printd().
print_hex()
void print_hex (uint32_t hex, unsigned char color, int col, int row)
Definition at line 28 of file display.c.
{
     uint32_t pk = (uint32_t)0x10000000;
     bool was_not_zero = 0;
     while (pk > 0) {
         uint32_t pp = hex / pk;
         if (was_not_zero || pp > 0) {
             if (pp >= 10) {
                 print_char(pp - 10 + 'A', color, col, row);
             } else {
                 print_char(pp + '0', color, col, row);
             }
             was_not_zero = 1;
         }
         hex -= pp * pk;
         pk /= 16;
     }
     if (was_not_zero) {
         print_char('h', color, col, row);
     } else {
         print_char('0', color, col, row);
     }
 }
Referenced by kprinth(), and printh().
print_string()
void print_string (const char * string, unsigned char color, int col, int row)
Definition at line 20 of file display.c.
{
     int i = 0;
     while (string[i] != 0) {
         print_char(string[i++], color, col, row);
         col = row = -1;
     }
 }
Referenced by kprintf(), and printf().
printd()
void printd (uint32_t dec)
Definition at line 76 of file display.c.
{
     print_dec(dec, WHITE_ON_BLACK, -1, -1);
 }
References print_dec(), and WHITE_ON_BLACK.
Referenced by ext2_lite_init(), and stage2().
printf()
void printf (const char * string)
Definition at line 68 of file display.c.
{
     print_string(string, WHITE_ON_BLACK, -1, -1);
 }
References print_string(), and WHITE_ON_BLACK.
Referenced by ext2_lite_has_in_dir(), ext2_lite_init(), and stage2().
printh()
void printh (uint32_t hex)
Definition at line 72 of file display.c.
{
     print_hex(hex, WHITE_ON_BLACK, -1, -1);
 }
References print_hex(), and WHITE_ON_BLACK.
Referenced by get_load_disk(), and indentify_ata_device().
row_in_field()
char row_in_field (int row)
Definition at line 132 of file display.c.
 { return (0 <= row && row <= MAX_ROWS); }
Referenced by delete_char(), ext_print_char(), and print_char().
scroll()
void scroll (unsigned char lines)
Definition at line 93 of file display.c.
{
     char* mem = VIDEO_MEMORY;
     unsigned int mem_offset = lines * MAX_COLS;
     unsigned int bytes_2_del = 2*(MAX_COLS*MAX_ROWS-mem_offset);
     char* src = (mem + mem_offset*2);
     for (int i = 0; i < bytes_2_del; ++i) {
         *(mem + i) = *(src + i);
     }
     for (int i = bytes_2_del; i < 2 * MAX_COLS * MAX_ROWS; i+=2) {
         mem[i] = ' ';
         mem[i + 1] = WHITE_ON_BLACK;
     }
     set_cursor_offset(bytes_2_del/2);
 }
Referenced by ext_print_char(), and print_char().
set_cursor_offset()
void set_cursor_offset (unsigned short offset)
Definition at line 112 of file display.c.
{
     port_byte_out(REG_SCREEN_CTRL, 14);
     port_byte_out(REG_SCREEN_DATA, (unsigned char)(offset >> 8));
     port_byte_out(REG_SCREEN_CTRL, 15);
     port_byte_out(REG_SCREEN_DATA, (unsigned char)(offset & 0xff));
 }
Referenced by clean_screen(), delete_char(), ext_print_char(), print_char(), and scroll().