oneOS: LG::Context Class Reference
LG::Context Class Reference
#include <Context.h>
Public Member Functions
Context (PixelBitmap &)
~Context ()
void add_clip (const Rect &rect)
void reset_clip ()
void set (const Point< int > &start, const PixelBitmap &bitmap)
void draw (const Point< int > &start, const PixelBitmap &bitmap)
void draw (const Point< int > &start, const GlyphBitmap &bitmap)
void fill (const Rect &rect)
void add_ellipse (const Rect &rect)
void set_draw_offset (const Point< int > &offset)
void set_fill_color (const Color &clr)
const Color & fill_color () const
Private Attributes
PixelBitmap & m_bitmap
Rect m_clip
const Rect m_origin_clip
Point< int > m_draw_offset {0, 0}
Color m_color {}
Detailed Description
Definition at line 21 of file Context.h.
Constructor & Destructor Documentation
Context()
LG::Context::Context (PixelBitmap & bitmap)
Definition at line 14 of file Context.cpp.
     : m_bitmap(bitmap)
     , m_origin_clip(0, 0, bitmap.width(), bitmap.height())
     , m_clip(0, 0, bitmap.width(), bitmap.height())
     , m_color()
 {
 }
~Context()
LG::Context::~Context () inline
Definition at line 24 of file Context.h.
 { }
Member Function Documentation
add_clip()
void LG::Context::add_clip (const Rect & rect)
Definition at line 22 of file Context.cpp.
 {
     m_clip.intersect(rect);
 }
References LG::Rect::intersect(), and m_clip.
Referenced by __attribute__(), UI::Context::Context(), DockView::display(), and TerminalView::display().
add_ellipse()
void LG::Context::add_ellipse (const Rect & rect)
Definition at line 135 of file Context.cpp.
 {
     int rx = rect.width() / 2;
     int ry = rect.height() / 2;
     int xc = rect.mid_x();
     int yc = rect.mid_y();
     double dx, dy, d1, d2, x, y;
     double tmp_d1, tmp_d2;
     x = 0;
     y = ry;
     d1 = (ry * ry) - (rx * rx * ry) + (0.25 * rx * rx);
     dx = 2 * ry * ry * x;
     dy = 2 * rx * rx * y;
     while (dx < dy) {
         m_bitmap[y + yc][(int)x + xc] = fill_color();
         m_bitmap[y + yc][(int)-x + xc] = fill_color();
         m_bitmap[-y + yc][(int)x + xc] = fill_color();
         m_bitmap[-y + yc][(int)-x + xc] = fill_color();
         x++;
         dx += 2 * ry * ry;
         tmp_d1 = d1;
         d1 += ry * ry + dx;
         if (tmp_d1 >= 0) {
             y--;
             dy -= 2 * rx * rx;
             d1 -= dy;
         }
     }
     d2 = ((ry * ry) * ((x + 0.5) * (x + 0.5))) + ((rx * rx) * ((y - 1) * (y - 1))) - (rx * rx * ry * ry);
     while (y >= 0) {
         m_bitmap[y + yc][(int)x + xc] = fill_color();
         m_bitmap[y + yc][(int)-x + xc] = fill_color();
         m_bitmap[-y + yc][(int)x + xc] = fill_color();
         m_bitmap[-y + yc][(int)-x + xc] = fill_color();
         y--;
         dy -= 2 * rx * rx;
         tmp_d2 = d2;
         d2 += rx * rx - dy;
         if (tmp_d2 <= 0) {
             x++;
             dx += 2 * ry * ry;
             d2 += dx;
         }
     }
 }
References fill_color(), LG::Rect::height(), m_bitmap, LG::Rect::mid_x(), LG::Rect::mid_y(), and LG::Rect::width().
draw() [1/2]
void LG::Context::draw (const Point< int > & start, const GlyphBitmap & bitmap)
Definition at line 88 of file Context.cpp.
 {
     Rect draw_bounds(start.x() + m_draw_offset.x(), start.y() + m_draw_offset.y(), bitmap.width(), bitmap.height());
     draw_bounds.intersect(m_clip);
     if (draw_bounds.empty()) {
         return;
     }
     auto& color = fill_color();
     int min_x = draw_bounds.min_x();
     int min_y = draw_bounds.min_y();
     int max_x = draw_bounds.max_x();
     int max_y = draw_bounds.max_y();
     int offset_x = -start.x() - m_draw_offset.x();
     int offset_y = -start.y() - m_draw_offset.y();
     int bitmap_y = min_y + offset_y;
     for (int y = min_y; y <= max_y; y++, bitmap_y++) {
         int bitmap_x = min_x + offset_x;
         for (int x = min_x; x <= max_x; x++, bitmap_x++) {
             if (bitmap.bit_at(bitmap_x, bitmap_y)) {
                 m_bitmap[y][x] = color;
             }
         }
     }
 }
References LG::Rect::empty(), fill_color(), LG::Rect::intersect(), m_bitmap, m_clip, m_draw_offset, LG::Rect::max_x(), LG::Rect::max_y(), LG::Rect::min_x(), LG::Rect::min_y(), LG::Point< T >::x(), and LG::Point< T >::y().
draw() [2/2]
void LG::Context::draw (const Point< int > & start, const PixelBitmap & bitmap)
Definition at line 54 of file Context.cpp.
 {
     if (!bitmap.has_alpha_channel()) {
         set(start, bitmap);
         return;
     }
     Rect draw_bounds(start.x() + m_draw_offset.x(), start.y() + m_draw_offset.y(), bitmap.width(), bitmap.height());
     draw_bounds.intersect(m_clip);
     if (draw_bounds.empty()) {
         return;
     }
     int min_x = draw_bounds.min_x();
     int min_y = draw_bounds.min_y();
     int max_x = draw_bounds.max_x();
     int max_y = draw_bounds.max_y();
     int offset_x = -start.x() - m_draw_offset.x();
     int offset_y = -start.y() - m_draw_offset.y();
     int bitmap_y = min_y + offset_y;
     for (int y = min_y; y <= max_y; y++, bitmap_y++) {
         int bitmap_x = min_x + offset_x;
         for (int x = min_x; x <= max_x; x++, bitmap_x++) {
             if (bitmap[bitmap_y][bitmap_x].alpha() == 0xff) {
                 m_bitmap[y][x] = bitmap[bitmap_y][bitmap_x];
             } else if (!bitmap[bitmap_y][bitmap_x].alpha()) {
                 continue;
             } else {
                 m_bitmap[y][x].mix_with(bitmap[bitmap_y][bitmap_x]);
             }
         }
     }
 }
References LG::Rect::empty(), LG::Rect::intersect(), m_bitmap, m_clip, m_draw_offset, LG::Rect::max_x(), LG::Rect::max_y(), LG::Rect::min_x(), LG::Rect::min_y(), set(), LG::Point< T >::x(), and LG::Point< T >::y().
Referenced by __attribute__(), UI::Button::display(), UI::Label::display(), DockView::display(), TerminalView::display(), Button::display(), and WindowFrame::draw().
fill()
void LG::Context::fill (const Rect & rect)
Definition at line 114 of file Context.cpp.
 {
     auto draw_bounds = rect;
     draw_bounds.offset_by(m_draw_offset);
     draw_bounds.intersect(m_clip);
     if (draw_bounds.empty()) {
         return;
     }
     auto color = fill_color().u32();
     int min_x = draw_bounds.min_x();
     int min_y = draw_bounds.min_y();
     int max_x = draw_bounds.max_x();
     int max_y = draw_bounds.max_y();
     int len_x = max_x - min_x + 1;
     for (int y = min_y; y <= max_y; y++) {
         fast_set((uint32_t*)&m_bitmap[y][min_x], color, len_x);
     }
 }
References fast_set(), fill_color(), m_bitmap, m_clip, m_draw_offset, LG::Rect::offset_by(), and LG::Color::u32().
Referenced by UI::View::display(), UI::Button::display(), DockView::display(), TerminalView::display(), and WindowFrame::draw().
fill_color()
const Color& LG::Context::fill_color () const inline
Definition at line 38 of file Context.h.
 { return m_color; }
References m_color.
Referenced by add_ellipse(), draw(), and fill().
reset_clip()
void LG::Context::reset_clip ()
Definition at line 27 of file Context.cpp.
 {
     m_clip = m_origin_clip;
 }
References m_clip, and m_origin_clip.
Referenced by __attribute__().
set()
void LG::Context::set (const Point< int > & start, const PixelBitmap & bitmap)
Definition at line 32 of file Context.cpp.
 {
     Rect draw_bounds(start.x() + m_draw_offset.x(), start.y() + m_draw_offset.y(), bitmap.width(), bitmap.height());
     draw_bounds.intersect(m_clip);
     if (draw_bounds.empty()) {
         return;
     }
     int min_x = draw_bounds.min_x();
     int min_y = draw_bounds.min_y();
     int max_x = draw_bounds.max_x();
     int max_y = draw_bounds.max_y();
     int offset_x = -start.x() - m_draw_offset.x();
     int offset_y = -start.y() - m_draw_offset.y();
     int bitmap_x = min_x + offset_x;
     int bitmap_y = min_y + offset_y;
     int len_x = max_x - min_x + 1;
     for (int y = min_y; y <= max_y; y++, bitmap_y++) {
         fast_copy((uint32_t*)&m_bitmap[y][min_x], (uint32_t*)&bitmap[bitmap_y][bitmap_x], len_x);
     }
 }
References LG::Rect::empty(), fast_copy(), LG::Rect::intersect(), m_bitmap, m_clip, m_draw_offset, LG::Rect::max_x(), LG::Rect::max_y(), LG::Rect::min_x(), LG::Rect::min_y(), LG::Point< T >::x(), and LG::Point< T >::y().
Referenced by draw().
set_draw_offset()
void LG::Context::set_draw_offset (const Point< int > & offset) inline
Definition at line 35 of file Context.h.
 { m_draw_offset = offset; }
References m_draw_offset.
Referenced by UI::Context::Context().
set_fill_color()
void LG::Context::set_fill_color (const Color & clr) inline
Definition at line 36 of file Context.h.
 { m_color = clr; }
References m_color.
Referenced by UI::View::display(), UI::Button::display(), UI::Label::display(), DockView::display(), TerminalView::display(), and WindowFrame::draw().
Field Documentation
m_bitmap
PixelBitmap& LG::Context::m_bitmap private
Definition at line 41 of file Context.h.
Referenced by add_ellipse(), draw(), fill(), and set().
m_clip
Rect LG::Context::m_clip private
Definition at line 42 of file Context.h.
Referenced by add_clip(), draw(), fill(), reset_clip(), and set().
m_color
Color LG::Context::m_color {} private
Definition at line 45 of file Context.h.
Referenced by fill_color(), and set_fill_color().
m_draw_offset
Point<int> LG::Context::m_draw_offset {0, 0} private
Definition at line 44 of file Context.h.
Referenced by draw(), fill(), set(), and set_draw_offset().
m_origin_clip
const Rect LG::Context::m_origin_clip private
Definition at line 43 of file Context.h.
Referenced by reset_clip().
The documentation for this class was generated from the following files:
libs/libg/Context.h
libs/libg/Context.cpp