oneOS: UI::Button Class Reference
UI::Button Class Reference
#include <Button.h>
Public Member Functions
Button (const LG::Rect &)
const String & title () const
void set_title (const String &title)
void set_title (String &&title)
void set_title_color (const LG::Color &color)
const LG::Color & title_color () const
void set_content_edge_insets (const EdgeInsect &ei)
const EdgeInsect & content_edge_insets () const
const LG::Font & font () const
virtual void display (const LG::Rect &rect) override
virtual void hover_begin (const LG::Point< int > &location) override
virtual void hover_end () override
Public Member Functions inherited from UI::View
View (const LG::Rect &)
View (const LG::Rect &, const LG::Color &)
template<class T , class... Args>
T & add_subview (Args &&... args)
void remove_from_superview ()
template<typename Callback >
void foreach_subview (Callback callback) const
View * subview_at (const LG::Point< int > &point) const
View * hit_test (const LG::Point< int > &point)
const LG::Rect & frame () const
const LG::Rect & bounds () const
void set_width (size_t x)
void set_height (size_t x)
LG::Rect frame_in_window ()
Window * window ()
bool has_superview ()
View * superview ()
Vector< View * > & subviews ()
const Vector< View * > & subviews () const
void set_needs_display (const LG::Rect &)
void set_needs_display ()
bool is_hovered () const
void set_focusable (bool val)
bool is_focusable () const
virtual void did_display (const LG::Rect &rect)
virtual void click_began (const LG::Point< int > &location)
virtual void click_ended ()
virtual void receive_mouse_move_event (MouseEvent &) override
virtual void receive_mouse_action_event (MouseActionEvent &) override
virtual void receive_mouse_leave_event (MouseLeaveEvent &) override
virtual void receive_keyup_event (KeyUpEvent &) override
virtual void receive_keydown_event (KeyDownEvent &) override
virtual void receive_display_event (DisplayEvent &) override
LG::Color & background_color ()
const LG::Color & background_color () const
virtual void set_background_color (const LG::Color &background_color)
Public Member Functions inherited from UI::Responder
bool send_invalidate_message_to_server (const LG::Rect &rect) const
void send_display_message_to_self (Window &win, const LG::Rect &display_rect)
void receive_event (UniquePtr< LFoundation::Event > event) override
Public Member Functions inherited from LFoundation::EventReceiver
EventReceiver ()
~EventReceiver ()
Private Member Functions
void recalc_bounds ()
size_t text_height ()
size_t text_width ()
Static Private Member Functions
static constexpr uint32_t std_background_color ()
static constexpr uint32_t std_hovered_background_color ()
Private Attributes
String m_title {}
LG::Color m_title_color { LG::Color::White }
LG::Font m_font { LG::Font::system_font() }
EdgeInsect m_content_edge_insets { 12, 12, 12, 12 }
Additional Inherited Members
Protected Member Functions inherited from UI::Responder
Responder ()
Protected Attributes inherited from UI::Responder
bool m_display_message_sent { false }
LG::Rect m_prev_display_message {}
Detailed Description
Definition at line 17 of file Button.h.
Constructor & Destructor Documentation
Button()
Button::Button (const LG::Rect & frame)
Definition at line 17 of file Button.cpp.
     : View(frame, std_background_color())
 {
 }
Member Function Documentation
content_edge_insets()
const EdgeInsect& UI::Button::content_edge_insets () const inline
Definition at line 29 of file Button.h.
 { return m_content_edge_insets; }
References m_content_edge_insets.
Referenced by display(), and recalc_bounds().
display()
void Button::display (const LG::Rect & rect) override virtual
Draws the receiver’s image within the passed-in rectangle.
Parameters
rect The portion of the view’s bounds that needs to be updated. The first time your view is drawn, this rectangle is typically the entire visible bounds of your view. However, during subsequent drawing operations, the rectangle may specify only part of your view.
Reimplemented from UI::View.
Definition at line 22 of file Button.cpp.
 {
     Context ctx(*this);
     ctx.set_fill_color(background_color());
     ctx.fill(bounds());
     LG::Point<int> text_start { content_edge_insets().left(), content_edge_insets().top() };
     auto& f = font();
     ctx.set_fill_color(title_color());
     for (int i = 0; i < m_title.size(); i++) {
         ctx.draw(text_start, f.glyph_bitmap(m_title[i]));
         text_start.offset_by(f.glyph_width(m_title[i]) + 2, 0);
     }
 }
References UI::View::background_color(), UI::View::bounds(), content_edge_insets(), LG::Context::draw(), LG::Context::fill(), font(), UI::EdgeInsect::left(), m_title, LG::Context::set_fill_color(), Algo::String::size(), title_color(), and UI::EdgeInsect::top().
font()
const LG::Font& UI::Button::font () const inline
Definition at line 31 of file Button.h.
 { return m_font; }
References m_font.
Referenced by display(), text_height(), and text_width().
hover_begin()
void Button::hover_begin (const LG::Point< int > & location) override virtual
Reimplemented from UI::View.
Definition at line 39 of file Button.cpp.
 {
     set_background_color(std_hovered_background_color());
 }
References UI::View::set_background_color(), and std_hovered_background_color().
hover_end()
void Button::hover_end () override virtual
Reimplemented from UI::View.
Definition at line 44 of file Button.cpp.
 {
     set_background_color(std_background_color());
 }
References UI::View::set_background_color(), and std_background_color().
recalc_bounds()
void Button::recalc_bounds () private
Definition at line 49 of file Button.cpp.
 {
     size_t new_width = text_width() + content_edge_insets().left() + content_edge_insets().right();
     size_t new_height = text_height() + content_edge_insets().top() + content_edge_insets().bottom();
     set_width(new_width);
     set_height(new_height);
 }
References UI::EdgeInsect::bottom(), content_edge_insets(), UI::EdgeInsect::left(), UI::EdgeInsect::right(), UI::View::set_height(), UI::View::set_width(), text_height(), text_width(), and UI::EdgeInsect::top().
Referenced by set_title().
set_content_edge_insets()
void UI::Button::set_content_edge_insets (const EdgeInsect & ei) inline
Definition at line 28 of file Button.h.
 { m_content_edge_insets = ei; }
References m_content_edge_insets.
set_title() [1/2]
void UI::Button::set_title (const String & title) inline
Definition at line 22 of file Button.h.
 { m_title = title, recalc_bounds(), set_needs_display(); }
References m_title, recalc_bounds(), UI::View::set_needs_display(), and title().
set_title() [2/2]
void UI::Button::set_title (String && title) inline
Definition at line 23 of file Button.h.
 { m_title = move(title), recalc_bounds(), set_needs_display(); }
References m_title, move(), recalc_bounds(), UI::View::set_needs_display(), and title().
set_title_color()
void UI::Button::set_title_color (const LG::Color & color) inline
Definition at line 25 of file Button.h.
 { m_title_color = color; }
References m_title_color.
std_background_color()
static constexpr uint32_t UI::Button::std_background_color () inline static constexpr private
Definition at line 42 of file Button.h.
 { return 0x00eda024; }
Referenced by hover_end().
std_hovered_background_color()
static constexpr uint32_t UI::Button::std_hovered_background_color () inline static constexpr private
Definition at line 43 of file Button.h.
 { return 0x00ca8311; }
Referenced by hover_begin().
text_height()
size_t Button::text_height () private
Definition at line 67 of file Button.cpp.
 {
     return font().glyph_height();
 }
References font(), and LG::Font::glyph_height().
Referenced by recalc_bounds().
text_width()
size_t Button::text_width () private
Definition at line 57 of file Button.cpp.
 {
     size_t width = 0;
     auto& f = font();
     for (int i = 0; i < m_title.size(); i++) {
         width += f.glyph_width(m_title[i]) + 2; // FIXME
     }
     return width;
 }
References font(), m_title, and Algo::String::size().
Referenced by recalc_bounds().
title()
const String& UI::Button::title () const inline
Definition at line 21 of file Button.h.
 { return m_title; }
References m_title.
Referenced by set_title().
title_color()
const LG::Color& UI::Button::title_color () const inline
Definition at line 26 of file Button.h.
 { return m_title_color; }
References m_title_color.
Referenced by display().
Field Documentation
m_content_edge_insets
EdgeInsect UI::Button::m_content_edge_insets { 12, 12, 12, 12 } private
Definition at line 49 of file Button.h.
Referenced by content_edge_insets(), and set_content_edge_insets().
m_font
LG::Font UI::Button::m_font { LG::Font::system_font() } private
Definition at line 47 of file Button.h.
Referenced by font().
m_title
String UI::Button::m_title {} private
Definition at line 45 of file Button.h.
Referenced by display(), set_title(), text_width(), and title().
m_title_color
LG::Color UI::Button::m_title_color { LG::Color::White } private
Definition at line 46 of file Button.h.
Referenced by set_title_color(), and title_color().
The documentation for this class was generated from the following files:
libs/libui/Button.h
libs/libui/Button.cpp