oneOS: AskBringToFrontMessage Class Reference
AskBringToFrontMessage Class Reference
#include <WSConnection.h>
Public Member Functions
AskBringToFrontMessage (message_key_t key, uint32_t window_id, uint32_t target_window_id)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
uint32_t window_id () const
uint32_t target_window_id () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
uint32_t m_window_id
uint32_t m_target_window_id
Detailed Description
Definition at line 308 of file WSConnection.h.
Constructor & Destructor Documentation
AskBringToFrontMessage()
AskBringToFrontMessage::AskBringToFrontMessage (message_key_t key, uint32_t window_id, uint32_t target_window_id) inline
Definition at line 310 of file WSConnection.h.
         : m_key(key)
         , m_window_id(window_id)
         , m_target_window_id(target_window_id)
     {
     }
Member Function Documentation
decoder_magic()
int AskBringToFrontMessage::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 319 of file WSConnection.h.
 { return 320; }
Referenced by encode().
encode()
EncodedMessage AskBringToFrontMessage::encode () const inline override virtual
Reimplemented from Message.
Definition at line 322 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_window_id);
         Encoder::append(buffer, m_target_window_id);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), m_target_window_id, and m_window_id.
id()
int AskBringToFrontMessage::id () const inline override virtual
Reimplemented from Message.
Definition at line 316 of file WSConnection.h.
 { return 11; }
key()
int AskBringToFrontMessage::key () const inline override virtual
Reimplemented from Message.
Definition at line 318 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode().
reply_id()
int AskBringToFrontMessage::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 317 of file WSConnection.h.
 { return -1; }
target_window_id()
uint32_t AskBringToFrontMessage::target_window_id () const inline
Definition at line 321 of file WSConnection.h.
 { return m_target_window_id; }
References m_target_window_id.
Referenced by WServerDecoder::handle().
window_id()
uint32_t AskBringToFrontMessage::window_id () const inline
Definition at line 320 of file WSConnection.h.
 { return m_window_id; }
References m_window_id.
Referenced by WServerDecoder::handle().
Field Documentation
m_key
message_key_t AskBringToFrontMessage::m_key private
Definition at line 333 of file WSConnection.h.
Referenced by key().
m_target_window_id
uint32_t AskBringToFrontMessage::m_target_window_id private
Definition at line 335 of file WSConnection.h.
Referenced by encode(), and target_window_id().
m_window_id
uint32_t AskBringToFrontMessage::m_window_id private
Definition at line 334 of file WSConnection.h.
Referenced by encode(), and window_id().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h