oneOS: DestroyWindowMessage Class Reference
DestroyWindowMessage Class Reference
#include <WSConnection.h>
Public Member Functions
DestroyWindowMessage (message_key_t key, uint32_t window_id)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
uint32_t window_id () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
uint32_t m_window_id
Detailed Description
Definition at line 128 of file WSConnection.h.
Constructor & Destructor Documentation
DestroyWindowMessage()
DestroyWindowMessage::DestroyWindowMessage (message_key_t key, uint32_t window_id) inline
Definition at line 130 of file WSConnection.h.
         : m_key(key)
         , m_window_id(window_id)
     {
     }
Member Function Documentation
decoder_magic()
int DestroyWindowMessage::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 138 of file WSConnection.h.
 { return 320; }
Referenced by encode().
encode()
EncodedMessage DestroyWindowMessage::encode () const inline override virtual
Reimplemented from Message.
Definition at line 140 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_window_id);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), and m_window_id.
id()
int DestroyWindowMessage::id () const inline override virtual
Reimplemented from Message.
Definition at line 135 of file WSConnection.h.
 { return 5; }
key()
int DestroyWindowMessage::key () const inline override virtual
Reimplemented from Message.
Definition at line 137 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode(), and WServerDecoder::handle().
reply_id()
int DestroyWindowMessage::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 136 of file WSConnection.h.
 { return 6; }
window_id()
uint32_t DestroyWindowMessage::window_id () const inline
Definition at line 139 of file WSConnection.h.
 { return m_window_id; }
References m_window_id.
Referenced by WServerDecoder::handle().
Field Documentation
m_key
message_key_t DestroyWindowMessage::m_key private
Definition at line 150 of file WSConnection.h.
Referenced by key().
m_window_id
uint32_t DestroyWindowMessage::m_window_id private
Definition at line 151 of file WSConnection.h.
Referenced by encode(), and window_id().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h