oneOS: Encoder Class Reference
Encoder Class Reference
#include <Encoder.h>
Public Member Functions
~Encoder ()
Static Public Member Functions
static void append (EncodedMessage &buf, int val)
static void append (EncodedMessage &buf, uint32_t val)
static void append (EncodedMessage &buf, size_t val)
static void decode (const char *buf, size_t &offset, size_t &val)
static void decode (const char *buf, size_t &offset, uint32_t &val)
static void decode (const char *buf, size_t &offset, int &val)
template<typename T >
static void append (EncodedMessage &buf, T &value)
template<typename T >
static void decode (const char *buf, size_t &offset, T &value)
Private Member Functions
Encoder ()
Detailed Description
Definition at line 6 of file Encoder.h.
Constructor & Destructor Documentation
~Encoder()
Encoder::~Encoder () inline
Definition at line 8 of file Encoder.h.
 { }
Encoder()
Encoder::Encoder () inline private
Definition at line 89 of file Encoder.h.
 { }
Member Function Documentation
append() [1/4]
static void Encoder::append (EncodedMessage & buf, int val) inline static
Definition at line 10 of file Encoder.h.
     {
         buf.push_back((uint8_t)val);
         buf.push_back((uint8_t)(val >> 8));
         buf.push_back((uint8_t)(val >> 16));
         buf.push_back((uint8_t)(val >> 24));
     }
References buf.
Referenced by GreetMessage::encode(), GreetMessageReply::encode(), CreateWindowMessage::encode(), CreateWindowMessageReply::encode(), DestroyWindowMessage::encode(), DestroyWindowMessageReply::encode(), SetBufferMessage::encode(), SetBarStyleMessage::encode(), SetTitleMessage::encode(), InvalidateMessage::encode(), AskBringToFrontMessage::encode(), MouseMoveMessage::encode(), MouseActionMessage::encode(), MouseLeaveMessage::encode(), KeyboardMessage::encode(), DisplayMessage::encode(), WindowCloseRequestMessage::encode(), DisconnectMessage::encode(), NotifyWindowStatusChangedMessage::encode(), NotifyWindowIconChangedMessage::encode(), LG::Point< T >::encode(), and LG::Rect::encode().
append() [2/4]
static void Encoder::append (EncodedMessage & buf, size_t val) inline static
Definition at line 26 of file Encoder.h.
     {
         buf.push_back((uint8_t)val);
         buf.push_back((uint8_t)(val >> 8));
         buf.push_back((uint8_t)(val >> 16));
         buf.push_back((uint8_t)(val >> 24));
     }
References buf.
append() [3/4]
template<typename T > static void Encoder::append (EncodedMessage & buf, T & value) inline static
Definition at line 77 of file Encoder.h.
     {
         value.encode(buf);
     }
References buf.
append() [4/4]
static void Encoder::append (EncodedMessage & buf, uint32_t val) inline static
Definition at line 18 of file Encoder.h.
     {
         buf.push_back((uint8_t)val);
         buf.push_back((uint8_t)(val >> 8));
         buf.push_back((uint8_t)(val >> 16));
         buf.push_back((uint8_t)(val >> 24));
     }
References buf.
decode() [1/4]
static void Encoder::decode (const char * buf, size_t & offset, int & val) inline static
Definition at line 62 of file Encoder.h.
     {
         uint8_t b0 = buf[offset++];
         uint8_t b1 = buf[offset++];
         uint8_t b2 = buf[offset++];
         uint8_t b3 = buf[offset++];
         val = 0;
         val |= (uint8_t(b3) << 24);
         val |= (uint8_t(b2) << 16);
         val |= (uint8_t(b1) << 8);
         val |= (uint8_t(b0));
     }
References buf.
decode() [2/4]
static void Encoder::decode (const char * buf, size_t & offset, size_t & val) inline static
Definition at line 34 of file Encoder.h.
     {
         uint8_t b0 = buf[offset++];
         uint8_t b1 = buf[offset++];
         uint8_t b2 = buf[offset++];
         uint8_t b3 = buf[offset++];
         val = 0;
         val |= (uint8_t(b3) << 24);
         val |= (uint8_t(b2) << 16);
         val |= (uint8_t(b1) << 8);
         val |= (uint8_t(b0));
     }
References buf.
Referenced by LG::Point< T >::decode(), LG::Rect::decode(), WindowServerDecoder::decode(), and WindowClientDecoder::decode().
decode() [3/4]
template<typename T > static void Encoder::decode (const char * buf, size_t & offset, T & value) inline static
Definition at line 83 of file Encoder.h.
     {
         value.decode(buf, offset);
     }
References buf.
decode() [4/4]
static void Encoder::decode (const char * buf, size_t & offset, uint32_t & val) inline static
Definition at line 48 of file Encoder.h.
     {
         uint8_t b0 = buf[offset++];
         uint8_t b1 = buf[offset++];
         uint8_t b2 = buf[offset++];
         uint8_t b3 = buf[offset++];
         val = 0;
         val |= (uint8_t(b3) << 24);
         val |= (uint8_t(b2) << 16);
         val |= (uint8_t(b1) << 8);
         val |= (uint8_t(b0));
     }
References buf.
The documentation for this class was generated from the following file:
libs/libipc/Encoder.h