oneOS: GreetMessage Class Reference
GreetMessage Class Reference
#include <WSConnection.h>
Public Member Functions
GreetMessage (message_key_t key)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
Detailed Description
Definition at line 12 of file WSConnection.h.
Constructor & Destructor Documentation
GreetMessage()
GreetMessage::GreetMessage (message_key_t key) inline
Definition at line 14 of file WSConnection.h.
         : m_key(key)
     {
     }
Member Function Documentation
decoder_magic()
int GreetMessage::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 21 of file WSConnection.h.
 { return 320; }
Referenced by encode().
encode()
EncodedMessage GreetMessage::encode () const inline override virtual
Reimplemented from Message.
Definition at line 22 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         return buffer;
     }
References Encoder::append(), decoder_magic(), and key().
id()
int GreetMessage::id () const inline override virtual
Reimplemented from Message.
Definition at line 18 of file WSConnection.h.
 { return 1; }
key()
int GreetMessage::key () const inline override virtual
Reimplemented from Message.
Definition at line 20 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode(), and WServerDecoder::handle().
reply_id()
int GreetMessage::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 19 of file WSConnection.h.
 { return 2; }
Field Documentation
m_key
message_key_t GreetMessage::m_key private
Definition at line 31 of file WSConnection.h.
Referenced by key().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h