oneOS: WindowCloseRequestMessage Class Reference
WindowCloseRequestMessage Class Reference
#include <WSConnection.h>
Public Member Functions
WindowCloseRequestMessage (message_key_t key, int win_id)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
int win_id () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
int m_win_id
Detailed Description
Definition at line 620 of file WSConnection.h.
Constructor & Destructor Documentation
WindowCloseRequestMessage()
WindowCloseRequestMessage::WindowCloseRequestMessage (message_key_t key, int win_id) inline
Definition at line 622 of file WSConnection.h.
         : m_key(key)
         , m_win_id(win_id)
     {
     }
Member Function Documentation
decoder_magic()
int WindowCloseRequestMessage::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 630 of file WSConnection.h.
 { return 737; }
Referenced by encode().
encode()
EncodedMessage WindowCloseRequestMessage::encode () const inline override virtual
Reimplemented from Message.
Definition at line 632 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_win_id);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), and m_win_id.
id()
int WindowCloseRequestMessage::id () const inline override virtual
Reimplemented from Message.
Definition at line 627 of file WSConnection.h.
 { return 6; }
key()
int WindowCloseRequestMessage::key () const inline override virtual
Reimplemented from Message.
Definition at line 629 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode().
reply_id()
int WindowCloseRequestMessage::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 628 of file WSConnection.h.
 { return -1; }
win_id()
int WindowCloseRequestMessage::win_id () const inline
Definition at line 631 of file WSConnection.h.
 { return m_win_id; }
References m_win_id.
Referenced by UI::ClientDecoder::handle().
Field Documentation
m_key
message_key_t WindowCloseRequestMessage::m_key private
Definition at line 642 of file WSConnection.h.
Referenced by key().
m_win_id
int WindowCloseRequestMessage::m_win_id private
Definition at line 643 of file WSConnection.h.
Referenced by encode(), and win_id().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h