oneOS: UI::App Class Reference
UI::App Class Reference
#include <App.h>
Public Member Functions
App ()
int run ()
void set_window (Window *window)
Window & window ()
const Window & window () const
const Connection & connection () const
void receive_event (UniquePtr< LFoundation::Event > event) override
Public Member Functions inherited from LFoundation::EventReceiver
EventReceiver ()
~EventReceiver ()
Static Public Member Functions
static App & the ()
Private Attributes
LFoundation::EventLoop m_event_loop
Connection m_server_connection
Window * m_window
Detailed Description
Definition at line 20 of file App.h.
Constructor & Destructor Documentation
App()
UI::App::App ()
Definition at line 21 of file App.cpp.
     : m_event_loop()
     , m_server_connection(socket(PF_LOCAL, 0, 0))
 {
     s_the = this;
 }
References UI::s_the.
Member Function Documentation
connection()
const Connection& UI::App::connection () const inline
Definition at line 30 of file App.h.
 { return m_server_connection; }
References m_server_connection.
Referenced by UI::Window::did_format_change(), UI::Window::set_frame_style(), and UI::Window::set_title().
receive_event()
void UI::App::receive_event (UniquePtr< LFoundation::Event > event) override virtual
Reimplemented from LFoundation::EventReceiver.
Definition at line 28 of file App.cpp.
 {
     if (event->type() == Event::Type::WindowCloseRequestEvent) {
         // TODO: Only 1 window is supported for now
         WindowCloseRequestEvent& own_event = *(WindowCloseRequestEvent*)event.get();
         auto message = DestroyWindowMessage(m_server_connection.key(), own_event.window_id());
         auto reply = m_server_connection.send_sync_message<DestroyWindowMessageReply>(message);
         m_event_loop.stop(reply->status());
     }
 }
References UniquePtr< T >::get(), UI::Connection::key(), m_event_loop, m_server_connection, UI::Connection::send_sync_message(), LFoundation::EventLoop::stop(), LFoundation::Event::type(), and UI::WindowCloseRequestEvent::window_id().
run()
int UI::App::run () inline
Definition at line 25 of file App.h.
 { return m_event_loop.run(); }
References m_event_loop, and LFoundation::EventLoop::run().
set_window()
void UI::App::set_window (Window * window) inline
Definition at line 26 of file App.h.
 { m_window = window; }
References m_window, and window().
Referenced by UI::Window::Window().
the()
App & UI::App::the () static
Definition at line 16 of file App.cpp.
 {
     return *s_the;
 }
References UI::s_the.
Referenced by DockView::click_began(), UI::Window::did_format_change(), UI::ClientDecoder::handle(), UI::Responder::send_invalidate_message_to_server(), UI::Window::set_frame_style(), UI::Window::set_title(), and UI::Window::Window().
window() [1/2]
Window& UI::App::window () inline
Definition at line 27 of file App.h.
 { return *m_window; }
References m_window.
Referenced by set_window().
window() [2/2]
const Window& UI::App::window () const inline
Definition at line 28 of file App.h.
 { return *m_window; }
References m_window.
Field Documentation
m_event_loop
LFoundation::EventLoop UI::App::m_event_loop private
Definition at line 34 of file App.h.
Referenced by receive_event(), and run().
m_server_connection
Connection UI::App::m_server_connection private
Definition at line 35 of file App.h.
Referenced by connection(), and receive_event().
m_window
Window* UI::App::m_window private
Definition at line 36 of file App.h.
Referenced by set_window(), and window().
The documentation for this class was generated from the following files:
libs/libui/App.h
libs/libui/App.cpp