oneOS: Weakable< T > Class Template Reference
Weakable< T > Class Template Reference
#include <WeakPtr.h>
Public Member Functions
WeakPtr< T > weak_ptr ()
Protected Member Functions
Weakable ()
~Weakable ()
Private Attributes
WeakLink< T > * m_data { nullptr }
Detailed Description
template<typename T>
class Weakable< T >
Definition at line 67 of file WeakPtr.h.
Constructor & Destructor Documentation
Weakable()
template<typename T > Weakable< T >::Weakable () inline protected
Definition at line 78 of file WeakPtr.h.
 { }
~Weakable()
template<typename T > Weakable< T >::~Weakable () inline protected
Definition at line 80 of file WeakPtr.h.
     {
         if (m_data) {
             m_data->m_ptr = nullptr;
         }
     }
References Weakable< T >::m_data.
Member Function Documentation
weak_ptr()
template<typename T > WeakPtr<T> Weakable< T >::weak_ptr () inline
Definition at line 69 of file WeakPtr.h.
     {
         if (!m_data) {
             m_data = new WeakLink<T>(static_cast<T&>(*this));
         }
         return WeakPtr<T>(m_data);
     }
References Weakable< T >::m_data.
Referenced by WindowManager::receive_mouse_event(), WindowManager::setup_dock(), and WindowManager::start_window_move().
Field Documentation
m_data
template<typename T > WeakLink<T>* Weakable< T >::m_data { nullptr } private
Definition at line 88 of file WeakPtr.h.
Referenced by Weakable< T >::weak_ptr(), and Weakable< T >::~Weakable().
The documentation for this class was generated from the following file:
libs/libcxx/std/WeakPtr.h