oneOS: DisplayMessage Class Reference
DisplayMessage Class Reference
#include <WSConnection.h>
Public Member Functions
DisplayMessage (message_key_t key, LG::Rect rect)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
LG::Rect rect () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
LG::Rect m_rect
Detailed Description
Definition at line 594 of file WSConnection.h.
Constructor & Destructor Documentation
DisplayMessage()
DisplayMessage::DisplayMessage (message_key_t key, LG::Rect rect) inline
Definition at line 596 of file WSConnection.h.
         : m_key(key)
         , m_rect(rect)
     {
     }
Member Function Documentation
decoder_magic()
int DisplayMessage::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 604 of file WSConnection.h.
 { return 737; }
Referenced by encode().
encode()
EncodedMessage DisplayMessage::encode () const inline override virtual
Reimplemented from Message.
Definition at line 606 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_rect);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), and m_rect.
id()
int DisplayMessage::id () const inline override virtual
Reimplemented from Message.
Definition at line 601 of file WSConnection.h.
 { return 5; }
key()
int DisplayMessage::key () const inline override virtual
Reimplemented from Message.
Definition at line 603 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode().
rect()
LG::Rect DisplayMessage::rect () const inline
Definition at line 605 of file WSConnection.h.
 { return m_rect; }
References m_rect.
Referenced by UI::ClientDecoder::handle().
reply_id()
int DisplayMessage::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 602 of file WSConnection.h.
 { return -1; }
Field Documentation
m_key
message_key_t DisplayMessage::m_key private
Definition at line 616 of file WSConnection.h.
Referenced by key().
m_rect
LG::Rect DisplayMessage::m_rect private
Definition at line 617 of file WSConnection.h.
Referenced by encode(), and rect().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h