oneOS: Message Class Reference
Message Class Reference
#include <Message.h>
Public Member Functions
Message ()
virtual ~Message ()=default
virtual int decoder_magic () const
virtual int id () const
virtual message_key_t key () const
virtual int reply_id () const
virtual EncodedMessage encode () const
Detailed Description
Definition at line 8 of file Message.h.
Constructor & Destructor Documentation
Message()
Message::Message () inline
Definition at line 10 of file Message.h.
 { }
~Message()
virtual Message::~Message () virtual default
Member Function Documentation
decoder_magic()
virtual int Message::decoder_magic () const inline virtual
Reimplemented in NotifyWindowIconChangedMessage, NotifyWindowStatusChangedMessage, DisconnectMessage, WindowCloseRequestMessage, DisplayMessage, KeyboardMessage, MouseLeaveMessage, MouseActionMessage, MouseMoveMessage, AskBringToFrontMessage, InvalidateMessage, SetTitleMessage, SetBarStyleMessage, SetBufferMessage, DestroyWindowMessageReply, DestroyWindowMessage, CreateWindowMessageReply, CreateWindowMessage, GreetMessageReply, and GreetMessage.
Definition at line 13 of file Message.h.
 { return 0; }
Referenced by WindowServerDecoder::handle(), and WindowClientDecoder::handle().
encode()
virtual EncodedMessage Message::encode () const inline virtual
Reimplemented in NotifyWindowIconChangedMessage, NotifyWindowStatusChangedMessage, DisconnectMessage, WindowCloseRequestMessage, DisplayMessage, KeyboardMessage, MouseLeaveMessage, MouseActionMessage, MouseMoveMessage, AskBringToFrontMessage, InvalidateMessage, SetTitleMessage, SetBarStyleMessage, SetBufferMessage, DestroyWindowMessageReply, DestroyWindowMessage, CreateWindowMessageReply, CreateWindowMessage, GreetMessageReply, and GreetMessage.
Definition at line 17 of file Message.h.
 { return Vector<uint8_t>(); }
Referenced by ClientConnection< ServerDecoder, ClientDecoder >::send_message(), and ServerConnection< ServerDecoder, ClientDecoder >::send_message().
id()
virtual int Message::id () const inline virtual
Reimplemented in NotifyWindowIconChangedMessage, NotifyWindowStatusChangedMessage, DisconnectMessage, WindowCloseRequestMessage, DisplayMessage, KeyboardMessage, MouseLeaveMessage, MouseActionMessage, MouseMoveMessage, AskBringToFrontMessage, InvalidateMessage, SetTitleMessage, SetBarStyleMessage, SetBufferMessage, DestroyWindowMessageReply, DestroyWindowMessage, CreateWindowMessageReply, CreateWindowMessage, GreetMessageReply, and GreetMessage.
Definition at line 14 of file Message.h.
 { return 0; }
Referenced by WindowServerDecoder::handle(), and WindowClientDecoder::handle().
key()
virtual message_key_t Message::key () const inline virtual
Reimplemented in NotifyWindowIconChangedMessage, NotifyWindowStatusChangedMessage, DisconnectMessage, WindowCloseRequestMessage, DisplayMessage, KeyboardMessage, MouseLeaveMessage, MouseActionMessage, MouseMoveMessage, AskBringToFrontMessage, InvalidateMessage, SetTitleMessage, SetBarStyleMessage, SetBufferMessage, DestroyWindowMessageReply, DestroyWindowMessage, CreateWindowMessageReply, CreateWindowMessage, GreetMessageReply, and GreetMessage.
Definition at line 15 of file Message.h.
 { return -1; }
Referenced by ClientConnection< ServerDecoder, ClientDecoder >::wait_for_answer().
reply_id()
virtual int Message::reply_id () const inline virtual
Reimplemented in NotifyWindowIconChangedMessage, NotifyWindowStatusChangedMessage, DisconnectMessage, WindowCloseRequestMessage, DisplayMessage, KeyboardMessage, MouseLeaveMessage, MouseActionMessage, MouseMoveMessage, AskBringToFrontMessage, InvalidateMessage, SetTitleMessage, SetBarStyleMessage, SetBufferMessage, DestroyWindowMessageReply, DestroyWindowMessage, CreateWindowMessageReply, CreateWindowMessage, GreetMessageReply, and GreetMessage.
Definition at line 16 of file Message.h.
 { return -1; } // -1 means that there is no reply.
Referenced by ClientConnection< ServerDecoder, ClientDecoder >::wait_for_answer().
The documentation for this class was generated from the following file:
libs/libipc/Message.h