oneOS: UniquePtr< T > Class Template Reference
UniquePtr< T > Class Template Reference
#include <memory.h>
Public Member Functions
UniquePtr ()
UniquePtr (T *data)
UniquePtr (nullptr_t)
UniquePtr & operator= (nullptr_t)
UniquePtr (UniquePtr &&moving) noexcept
UniquePtr & operator= (UniquePtr &&moving) noexcept
template<typename U >
UniquePtr (UniquePtr< U > &&moving)
template<typename U >
UniquePtr & operator= (UniquePtr< U > &&moving)
T * release () noexcept
void swap (UniquePtr &src) noexcept
void reset ()
~UniquePtr ()
UniquePtr (UniquePtr const &)=delete
UniquePtr & operator= (UniquePtr const &)=delete
T * operator-> () const
T & operator* () const
T * get () const
operator bool () const
Private Attributes
T * m_data { nullptr }
Detailed Description
template<typename T>
class UniquePtr< T >
Definition at line 7 of file memory.h.
Constructor & Destructor Documentation
UniquePtr() [1/6]
template<typename T > UniquePtr< T >::UniquePtr () inline
Definition at line 9 of file memory.h.
         : m_data(nullptr)
     {
     }
UniquePtr() [2/6]
template<typename T > UniquePtr< T >::UniquePtr (T * data) inline
Definition at line 14 of file memory.h.
         : m_data(data)
     {
     }
UniquePtr() [3/6]
template<typename T > UniquePtr< T >::UniquePtr (nullptr_t) inline
Definition at line 19 of file memory.h.
         : m_data(nullptr)
     {
     }
UniquePtr() [4/6]
template<typename T > UniquePtr< T >::UniquePtr (UniquePtr< T > && moving) inline noexcept
Definition at line 29 of file memory.h.
         : m_data(nullptr)
     {
         moving.swap(*this);
     }
UniquePtr() [5/6]
template<typename T > template<typename U > UniquePtr< T >::UniquePtr (UniquePtr< U > && moving) inline
Definition at line 41 of file memory.h.
     {
         UniquePtr<T> tmp((T*)moving.release());
         tmp.swap(*this);
     }
References UniquePtr< T >::swap().
~UniquePtr()
template<typename T > UniquePtr< T >::~UniquePtr () inline
Definition at line 74 of file memory.h.
     {
         delete m_data;
     }
References UniquePtr< T >::m_data.
UniquePtr() [6/6]
template<typename T > UniquePtr< T >::UniquePtr (UniquePtr< T > const &) delete
Member Function Documentation
get()
template<typename T > T* UniquePtr< T >::get () const inline
Definition at line 85 of file memory.h.
 { return m_data; }
References UniquePtr< T >::m_data.
Referenced by UI::App::receive_event(), UI::Responder::receive_event(), UI::Window::receive_event(), and DockWindow::receive_event().
operator bool()
template<typename T > UniquePtr< T >::operator bool () const inline explicit
Definition at line 86 of file memory.h.
 { return m_data; }
References UniquePtr< T >::m_data.
operator*()
template<typename T > T& UniquePtr< T >::operator* () const inline
Definition at line 83 of file memory.h.
 { return *m_data; }
References UniquePtr< T >::m_data.
operator->()
template<typename T > T* UniquePtr< T >::operator-> () const inline
Definition at line 82 of file memory.h.
 { return m_data; }
References UniquePtr< T >::m_data.
operator=() [1/4]
template<typename T > UniquePtr& UniquePtr< T >::operator= (nullptr_t) inline
Definition at line 23 of file memory.h.
     {
         reset();
         return *this;
     }
References UniquePtr< T >::reset().
operator=() [2/4]
template<typename T > UniquePtr& UniquePtr< T >::operator= (UniquePtr< T > && moving) inline noexcept
Definition at line 34 of file memory.h.
     {
         moving.swap(*this);
         return *this;
     }
References UniquePtr< T >::swap().
operator=() [3/4]
template<typename T > UniquePtr& UniquePtr< T >::operator= (UniquePtr< T > const &) delete
operator=() [4/4]
template<typename T > template<typename U > UniquePtr& UniquePtr< T >::operator= (UniquePtr< U > && moving) inline
Definition at line 47 of file memory.h.
     {
         UniquePtr<T> tmp((T*)moving.release());
         tmp.swap(*this);
         return *this;
     }
References UniquePtr< T >::swap().
release()
template<typename T > T* UniquePtr< T >::release () inline noexcept
Definition at line 54 of file memory.h.
     {
         T* result = m_data;
         m_data = nullptr;
         return result;
     }
References UniquePtr< T >::m_data.
Referenced by WindowManager::receive_keyboard_event(), WindowManager::receive_mouse_event(), and UniquePtr< T >::reset().
reset()
template<typename T > void UniquePtr< T >::reset () inline
Definition at line 68 of file memory.h.
     {
         T* tmp = release();
         delete tmp;
     }
References UniquePtr< T >::release().
Referenced by UniquePtr< T >::operator=().
swap()
template<typename T > void UniquePtr< T >::swap (UniquePtr< T > & src) inline noexcept
Definition at line 61 of file memory.h.
     {
         T* tmp_data = m_data;
         m_data = src.m_data;
         src.m_data = tmp_data;
     }
References UniquePtr< T >::m_data.
Referenced by UniquePtr< T >::operator=(), Screen::swap_buffers(), and UniquePtr< T >::UniquePtr().
Field Documentation
m_data
template<typename T > T* UniquePtr< T >::m_data { nullptr } private
Definition at line 89 of file memory.h.
Referenced by UniquePtr< T >::get(), UniquePtr< T >::operator bool(), UniquePtr< T >::operator*(), UniquePtr< T >::operator->(), UniquePtr< T >::release(), UniquePtr< T >::swap(), and UniquePtr< T >::~UniquePtr().
The documentation for this class was generated from the following file:
libs/libcxx/memory.h