oneOS: LFoundation::FDWaiter Class Reference
LFoundation::FDWaiter Class Reference
#include <Receivers.h>
Public Member Functions
FDWaiter (int fd, void(*on_read)(), void(*on_write)())
FDWaiter (FDWaiter &&fdw)
FDWaiter & operator= (const FDWaiter &fdw)
FDWaiter & operator= (FDWaiter &&fdw)
void receive_event (UniquePtr< Event > event) override
int fd ()
Public Member Functions inherited from LFoundation::EventReceiver
EventReceiver ()
~EventReceiver ()
Private Attributes
int m_fd
void(* m_on_read)()
void(* m_on_write)()
Friends
class EventLoop
Detailed Description
Definition at line 37 of file Receivers.h.
Constructor & Destructor Documentation
FDWaiter() [1/2]
LFoundation::FDWaiter::FDWaiter (int fd, void(*)() on_read, void(*)() on_write) inline
Definition at line 41 of file Receivers.h.
         : EventReceiver()
         , m_fd(fd)
         , m_on_read(on_read)
         , m_on_write(on_write)
     {
     }
FDWaiter() [2/2]
LFoundation::FDWaiter::FDWaiter (FDWaiter && fdw) inline
Definition at line 49 of file Receivers.h.
         : EventReceiver()
         , m_fd(fdw.m_fd)
         , m_on_read(fdw.m_on_read)
         , m_on_write(fdw.m_on_write)
     {
     }
Member Function Documentation
fd()
int LFoundation::FDWaiter::fd () inline
Definition at line 82 of file Receivers.h.
 { return m_fd; }
References m_fd.
operator=() [1/2]
FDWaiter& LFoundation::FDWaiter::operator= (const FDWaiter & fdw) inline
Definition at line 57 of file Receivers.h.
     {
         m_fd = fdw.m_fd;
         m_on_read = fdw.m_on_read;
         m_on_write = fdw.m_on_write;
         return *this;
     }
References m_fd, m_on_read, and m_on_write.
operator=() [2/2]
FDWaiter& LFoundation::FDWaiter::operator= (FDWaiter && fdw) inline
Definition at line 65 of file Receivers.h.
     {
         m_fd = fdw.m_fd;
         m_on_read = fdw.m_on_read;
         m_on_write = fdw.m_on_write;
         return *this;
     }
References m_fd, m_on_read, and m_on_write.
receive_event()
void LFoundation::FDWaiter::receive_event (UniquePtr< Event > event) inline override virtual
Reimplemented from LFoundation::EventReceiver.
Definition at line 73 of file Receivers.h.
     {
         if (event->type() == Event::Type::FdWaiterRead) {
             m_on_read();
         } else if (event->type() == Event::Type::FdWaiterWrite) {
             m_on_write();
         }
     }
References m_on_read, and m_on_write.
Friends And Related Function Documentation
EventLoop
friend class EventLoop friend
Definition at line 39 of file Receivers.h.
Field Documentation
m_fd
int LFoundation::FDWaiter::m_fd private
Definition at line 85 of file Receivers.h.
Referenced by fd(), and operator=().
m_on_read
void(* LFoundation::FDWaiter::m_on_read) () private
Definition at line 86 of file Receivers.h.
Referenced by operator=(), and receive_event().
m_on_write
void(* LFoundation::FDWaiter::m_on_write) () private
Definition at line 87 of file Receivers.h.
Referenced by operator=(), and receive_event().
The documentation for this class was generated from the following file:
libs/libfoundation/Receivers.h