oneOS: Algo::LinkedListIterator< T > Class Template Reference
Algo::LinkedListIterator< T > Class Template Reference
#include <LinkedList.h>
Public Member Functions
bool operator!= (const LinkedListIterator &other) const
bool operator== (const LinkedListIterator &other) const
LinkedListIterator & operator++ ()
T & operator* ()
T * operator-> ()
bool is_end () const
Static Public Member Functions
static LinkedListIterator null ()
Private Member Functions
LinkedListIterator (T *node)
Private Attributes
friend LinkedList< T >
T * m_node
Detailed Description
template<class T>
class Algo::LinkedListIterator< T >
Definition at line 12 of file LinkedList.h.
Constructor & Destructor Documentation
LinkedListIterator()
template<class T > Algo::LinkedListIterator< T >::LinkedListIterator (T * node) inline explicit private
Definition at line 28 of file LinkedList.h.
         : m_node(node)
     {
     }
Referenced by Algo::LinkedListIterator< T >::null().
Member Function Documentation
is_end()
template<class T > bool Algo::LinkedListIterator< T >::is_end () const inline
Definition at line 23 of file LinkedList.h.
 { return !m_node; }
References Algo::LinkedListIterator< T >::m_node.
null()
template<class T > static LinkedListIterator Algo::LinkedListIterator< T >::null () inline static
Definition at line 24 of file LinkedList.h.
 { return LinkedListIterator(nullptr); }
References Algo::LinkedListIterator< T >::LinkedListIterator().
Referenced by Algo::LinkedList< T >::end().
operator!=()
template<class T > bool Algo::LinkedListIterator< T >::operator!= (const LinkedListIterator< T > & other) const inline
Definition at line 14 of file LinkedList.h.
 { return m_node != other.m_node; }
References Algo::LinkedListIterator< T >::m_node.
operator*()
template<class T > T& Algo::LinkedListIterator< T >::operator* () inline
Definition at line 21 of file LinkedList.h.
 { return *m_node; }
References Algo::LinkedListIterator< T >::m_node.
operator++()
template<class T > LinkedListIterator& Algo::LinkedListIterator< T >::operator++ () inline
Definition at line 16 of file LinkedList.h.
     {
         m_node = m_node->next();
         return *this;
     }
References Algo::LinkedListIterator< T >::m_node.
operator->()
template<class T > T* Algo::LinkedListIterator< T >::operator-> () inline
Definition at line 22 of file LinkedList.h.
 { return m_node; }
References Algo::LinkedListIterator< T >::m_node.
operator==()
template<class T > bool Algo::LinkedListIterator< T >::operator== (const LinkedListIterator< T > & other) const inline
Definition at line 15 of file LinkedList.h.
 { return m_node == other.m_node; }
References Algo::LinkedListIterator< T >::m_node.
Field Documentation
LinkedList< T >
template<class T > friend Algo::LinkedListIterator< T >::LinkedList< T > private
Definition at line 27 of file LinkedList.h.
m_node
template<class T > T* Algo::LinkedListIterator< T >::m_node private
Definition at line 32 of file LinkedList.h.
Referenced by Algo::LinkedListIterator< T >::is_end(), Algo::LinkedListIterator< T >::operator!=(), Algo::LinkedListIterator< T >::operator*(), Algo::LinkedListIterator< T >::operator++(), Algo::LinkedListIterator< T >::operator->(), and Algo::LinkedListIterator< T >::operator==().
The documentation for this class was generated from the following file:
libs/libcxx/std/LinkedList.h