oneOS: LG::GlyphBitmap Class Reference
LG::GlyphBitmap Class Reference
#include <Font.h>
Public Member Functions
GlyphBitmap ()=default
GlyphBitmap (const uint32_t *rows, uint8_t width, uint8_t height)
~GlyphBitmap ()
bool bit_at (int x, int y) const
size_t width () const
size_t height () const
const uint32_t * rows () const
uint32_t row (uint32_t index) const
bool empty ()
Private Attributes
const uint32_t * m_rows { nullptr }
uint8_t m_width { 0 }
uint8_t m_height { 0 }
Friends
class Font
Detailed Description
Definition at line 24 of file Font.h.
Constructor & Destructor Documentation
GlyphBitmap() [1/2]
LG::GlyphBitmap::GlyphBitmap () default
GlyphBitmap() [2/2]
LG::GlyphBitmap::GlyphBitmap (const uint32_t * rows, uint8_t width, uint8_t height) inline
Definition at line 28 of file Font.h.
         : m_rows(rows)
         , m_width(width)
         , m_height(height)
     {
     }
~GlyphBitmap()
LG::GlyphBitmap::~GlyphBitmap () inline
Definition at line 35 of file Font.h.
 { }
Member Function Documentation
bit_at()
bool LG::GlyphBitmap::bit_at (int x, int y) const inline
Definition at line 37 of file Font.h.
 { return row(y) & (1 << x); }
References row().
empty()
bool LG::GlyphBitmap::empty () inline
Definition at line 43 of file Font.h.
 { return !m_rows || !m_width || !m_height; }
References m_height, m_rows, and m_width.
height()
size_t LG::GlyphBitmap::height () const inline
Definition at line 39 of file Font.h.
 { return m_height; }
References m_height.
Referenced by Button::recalc_dims().
row()
uint32_t LG::GlyphBitmap::row (uint32_t index) const inline
Definition at line 42 of file Font.h.
 { return m_rows[index]; }
References m_rows.
Referenced by bit_at().
rows()
const uint32_t* LG::GlyphBitmap::rows () const inline
Definition at line 41 of file Font.h.
 { return m_rows; }
References m_rows.
width()
size_t LG::GlyphBitmap::width () const inline
Definition at line 38 of file Font.h.
 { return m_width; }
References m_width.
Referenced by Button::display(), and Button::recalc_dims().
Friends And Related Function Documentation
Font
friend class Font friend
Definition at line 26 of file Font.h.
Field Documentation
m_height
uint8_t LG::GlyphBitmap::m_height { 0 } private
Definition at line 48 of file Font.h.
Referenced by empty(), and height().
m_rows
const uint32_t* LG::GlyphBitmap::m_rows { nullptr } private
Definition at line 46 of file Font.h.
Referenced by empty(), row(), and rows().
m_width
uint8_t LG::GlyphBitmap::m_width { 0 } private
Definition at line 47 of file Font.h.
Referenced by empty(), and width().
The documentation for this class was generated from the following file:
libs/libg/Font.h