oneOS: WindowClientDecoder Class Reference
WindowClientDecoder Class Reference
#include <WSConnection.h>
Public Member Functions
WindowClientDecoder ()
int magic () const
UniquePtr< Message > decode (const char *buf, size_t size, size_t &decoded_msg_len) override
UniquePtr< Message > handle (const Message &msg) override
virtual UniquePtr< Message > handle (const MouseMoveMessage &msg)
virtual UniquePtr< Message > handle (const MouseActionMessage &msg)
virtual UniquePtr< Message > handle (const MouseLeaveMessage &msg)
virtual UniquePtr< Message > handle (const KeyboardMessage &msg)
virtual UniquePtr< Message > handle (const DisplayMessage &msg)
virtual UniquePtr< Message > handle (const WindowCloseRequestMessage &msg)
virtual UniquePtr< Message > handle (const DisconnectMessage &msg)
virtual UniquePtr< Message > handle (const NotifyWindowStatusChangedMessage &msg)
virtual UniquePtr< Message > handle (const NotifyWindowIconChangedMessage &msg)
Public Member Functions inherited from MessageDecoder
MessageDecoder ()
virtual ~MessageDecoder ()
virtual int magic ()
Detailed Description
Definition at line 740 of file WSConnection.h.
Constructor & Destructor Documentation
WindowClientDecoder()
WindowClientDecoder::WindowClientDecoder () inline
Definition at line 742 of file WSConnection.h.
 {}
Member Function Documentation
decode()
UniquePtr<Message> WindowClientDecoder::decode (const char * buf, size_t size, size_t & decoded_msg_len) inline override virtual
Reimplemented from MessageDecoder.
Definition at line 744 of file WSConnection.h.
     {
         int msg_id, decoder_magic;
         size_t saved_dml = decoded_msg_len;
         Encoder::decode(buf, decoded_msg_len, decoder_magic);
         Encoder::decode(buf, decoded_msg_len, msg_id);
         if (magic() != decoder_magic) {
             decoded_msg_len = saved_dml;
             return nullptr;
         }
         message_key_t secret_key;
         Encoder::decode(buf, decoded_msg_len, secret_key);
         int var_win_id;
         uint32_t var_x;
         uint32_t var_y;
         int var_type;
         uint32_t var_kbd_key;
         LG::Rect var_rect;
         int var_reason;
         int var_changed_window_id;
         LG::String var_icon_path;
         switch(msg_id) {
         case 1:
             Encoder::decode(buf, decoded_msg_len, var_win_id);
             Encoder::decode(buf, decoded_msg_len, var_x);
             Encoder::decode(buf, decoded_msg_len, var_y);
             return new MouseMoveMessage(secret_key, var_win_id, var_x, var_y);
         case 2:
             Encoder::decode(buf, decoded_msg_len, var_win_id);
             Encoder::decode(buf, decoded_msg_len, var_type);
             Encoder::decode(buf, decoded_msg_len, var_x);
             Encoder::decode(buf, decoded_msg_len, var_y);
             return new MouseActionMessage(secret_key, var_win_id, var_type, var_x, var_y);
         case 3:
             Encoder::decode(buf, decoded_msg_len, var_win_id);
             Encoder::decode(buf, decoded_msg_len, var_x);
             Encoder::decode(buf, decoded_msg_len, var_y);
             return new MouseLeaveMessage(secret_key, var_win_id, var_x, var_y);
         case 4:
             Encoder::decode(buf, decoded_msg_len, var_win_id);
             Encoder::decode(buf, decoded_msg_len, var_kbd_key);
             return new KeyboardMessage(secret_key, var_win_id, var_kbd_key);
         case 5:
             Encoder::decode(buf, decoded_msg_len, var_rect);
             return new DisplayMessage(secret_key, var_rect);
         case 6:
             Encoder::decode(buf, decoded_msg_len, var_win_id);
             return new WindowCloseRequestMessage(secret_key, var_win_id);
         case 7:
             Encoder::decode(buf, decoded_msg_len, var_reason);
             return new DisconnectMessage(secret_key, var_reason);
         case 8:
             Encoder::decode(buf, decoded_msg_len, var_win_id);
             Encoder::decode(buf, decoded_msg_len, var_changed_window_id);
             Encoder::decode(buf, decoded_msg_len, var_type);
             return new NotifyWindowStatusChangedMessage(secret_key, var_win_id, var_changed_window_id, var_type);
         case 9:
             Encoder::decode(buf, decoded_msg_len, var_win_id);
             Encoder::decode(buf, decoded_msg_len, var_changed_window_id);
             Encoder::decode(buf, decoded_msg_len, var_icon_path);
             return new NotifyWindowIconChangedMessage(secret_key, var_win_id, var_changed_window_id, var_icon_path);
         default:
             decoded_msg_len = saved_dml;
             return nullptr;
         }
     }
References buf, Encoder::decode(), and magic().
handle() [1/10]
virtual UniquePtr<Message> WindowClientDecoder::handle (const DisconnectMessage & msg) inline virtual
Definition at line 849 of file WSConnection.h.
 { return nullptr; }
handle() [2/10]
virtual UniquePtr<Message> WindowClientDecoder::handle (const DisplayMessage & msg) inline virtual
Reimplemented in UI::ClientDecoder.
Definition at line 847 of file WSConnection.h.
 { return nullptr; }
handle() [3/10]
virtual UniquePtr<Message> WindowClientDecoder::handle (const KeyboardMessage & msg) inline virtual
Reimplemented in UI::ClientDecoder.
Definition at line 846 of file WSConnection.h.
 { return nullptr; }
handle() [4/10]
UniquePtr<Message> WindowClientDecoder::handle (const Message & msg) inline override virtual
Reimplemented from MessageDecoder.
Definition at line 813 of file WSConnection.h.
     {
         if (magic() != msg.decoder_magic()) {
             return nullptr;
         }
         switch(msg.id()) {
         case 1:
             return handle(static_cast<const MouseMoveMessage&>(msg));
         case 2:
             return handle(static_cast<const MouseActionMessage&>(msg));
         case 3:
             return handle(static_cast<const MouseLeaveMessage&>(msg));
         case 4:
             return handle(static_cast<const KeyboardMessage&>(msg));
         case 5:
             return handle(static_cast<const DisplayMessage&>(msg));
         case 6:
             return handle(static_cast<const WindowCloseRequestMessage&>(msg));
         case 7:
             return handle(static_cast<const DisconnectMessage&>(msg));
         case 8:
             return handle(static_cast<const NotifyWindowStatusChangedMessage&>(msg));
         case 9:
             return handle(static_cast<const NotifyWindowIconChangedMessage&>(msg));
         default:
             return nullptr;
         }
     }
References Message::decoder_magic(), Message::id(), and magic().
handle() [5/10]
virtual UniquePtr<Message> WindowClientDecoder::handle (const MouseActionMessage & msg) inline virtual
Reimplemented in UI::ClientDecoder.
Definition at line 844 of file WSConnection.h.
 { return nullptr; }
handle() [6/10]
virtual UniquePtr<Message> WindowClientDecoder::handle (const MouseLeaveMessage & msg) inline virtual
Reimplemented in UI::ClientDecoder.
Definition at line 845 of file WSConnection.h.
 { return nullptr; }
handle() [7/10]
virtual UniquePtr<Message> WindowClientDecoder::handle (const MouseMoveMessage & msg) inline virtual
Reimplemented in UI::ClientDecoder.
Definition at line 843 of file WSConnection.h.
 { return nullptr; }
handle() [8/10]
virtual UniquePtr<Message> WindowClientDecoder::handle (const NotifyWindowIconChangedMessage & msg) inline virtual
Reimplemented in UI::ClientDecoder.
Definition at line 851 of file WSConnection.h.
 { return nullptr; }
handle() [9/10]
virtual UniquePtr<Message> WindowClientDecoder::handle (const NotifyWindowStatusChangedMessage & msg) inline virtual
Reimplemented in UI::ClientDecoder.
Definition at line 850 of file WSConnection.h.
 { return nullptr; }
handle() [10/10]
virtual UniquePtr<Message> WindowClientDecoder::handle (const WindowCloseRequestMessage & msg) inline virtual
Reimplemented in UI::ClientDecoder.
Definition at line 848 of file WSConnection.h.
 { return nullptr; }
magic()
int WindowClientDecoder::magic () const inline
Definition at line 743 of file WSConnection.h.
 { return 737; }
Referenced by decode(), and handle().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h