oneOS: WServerDecoder Class Reference
WServerDecoder Class Reference
#include <WSServerDecoder.h>
Public Member Functions
WServerDecoder ()
~WServerDecoder ()
virtual UniquePtr< Message > handle (const GreetMessage &msg) override
virtual UniquePtr< Message > handle (const CreateWindowMessage &msg) override
virtual UniquePtr< Message > handle (const DestroyWindowMessage &msg) override
virtual UniquePtr< Message > handle (const SetBarStyleMessage &msg) override
virtual UniquePtr< Message > handle (const SetTitleMessage &msg) override
virtual UniquePtr< Message > handle (const SetBufferMessage &msg) override
virtual UniquePtr< Message > handle (const InvalidateMessage &msg) override
virtual UniquePtr< Message > handle (const AskBringToFrontMessage &msg) override
UniquePtr< Message > handle (const Message &msg) override
virtual UniquePtr< Message > handle (const GreetMessage &msg)
virtual UniquePtr< Message > handle (const CreateWindowMessage &msg)
virtual UniquePtr< Message > handle (const DestroyWindowMessage &msg)
virtual UniquePtr< Message > handle (const SetBufferMessage &msg)
virtual UniquePtr< Message > handle (const SetBarStyleMessage &msg)
virtual UniquePtr< Message > handle (const SetTitleMessage &msg)
virtual UniquePtr< Message > handle (const InvalidateMessage &msg)
virtual UniquePtr< Message > handle (const AskBringToFrontMessage &msg)
Public Member Functions inherited from WindowServerDecoder
WindowServerDecoder ()
int magic () const
UniquePtr< Message > decode (const char *buf, size_t size, size_t &decoded_msg_len) override
UniquePtr< Message > handle (const Message &msg) override
Public Member Functions inherited from MessageDecoder
MessageDecoder ()
virtual ~MessageDecoder ()
virtual int magic ()
Detailed Description
Definition at line 12 of file WSServerDecoder.h.
Constructor & Destructor Documentation
WServerDecoder()
WServerDecoder::WServerDecoder () inline
Definition at line 14 of file WSServerDecoder.h.
 { }
~WServerDecoder()
WServerDecoder::~WServerDecoder () inline
Definition at line 15 of file WSServerDecoder.h.
 { }
Member Function Documentation
handle() [1/17]
virtual UniquePtr<Message> WindowServerDecoder::handle inline
Definition at line 455 of file WSConnection.h.
 { return nullptr; }
handle() [2/17]
UniquePtr< Message > WServerDecoder::handle (const AskBringToFrontMessage & msg) override virtual
Reimplemented from WindowServerDecoder.
Definition at line 88 of file WSServerDecoder.cpp.
 {
     auto& wm = WindowManager::the();
     auto* window = wm.window(msg.window_id());
     auto* target_window = wm.window(msg.target_window_id());
     if (!window || !target_window) {
         return nullptr;
     }
     if (window->type() == WindowType::Dock) {
         // Only dock can ask for that now.
         wm.bring_to_front(*target_window);
     }
     return nullptr;
 }
References Dock, AskBringToFrontMessage::target_window_id(), WindowManager::the(), and AskBringToFrontMessage::window_id().
handle() [3/17]
virtual UniquePtr<Message> WindowServerDecoder::handle inline
Definition at line 449 of file WSConnection.h.
 { return nullptr; }
handle() [4/17]
UniquePtr< Message > WServerDecoder::handle (const CreateWindowMessage & msg) override virtual
Reimplemented from WindowServerDecoder.
Definition at line 18 of file WSServerDecoder.cpp.
 {
     auto& wm = WindowManager::the();
     int win_id = wm.next_win_id();
     auto* window = new Window(msg.key(), win_id, msg);
     window->frame().set_app_name("Unknown app");
     window->set_icon(msg.icon_path());
     wm.add_window(window);
     wm.notify_window_icon_changed(window->id());
     return new CreateWindowMessageReply(msg.key(), win_id);
 }
References CreateWindowMessage::icon_path(), CreateWindowMessage::key(), and WindowManager::the().
handle() [5/17]
virtual UniquePtr<Message> WindowServerDecoder::handle inline
Definition at line 450 of file WSConnection.h.
 { return nullptr; }
handle() [6/17]
UniquePtr< Message > WServerDecoder::handle (const DestroyWindowMessage & msg) override virtual
Reimplemented from WindowServerDecoder.
Definition at line 41 of file WSServerDecoder.cpp.
 {
     auto& wm = WindowManager::the();
     auto* window = wm.window(msg.window_id());
     if (window->connection_id() != msg.key()) {
         // TODO: security violation
     }
     wm.remove_window(window);
     return new DestroyWindowMessageReply(msg.key(), 0);
 }
References DestroyWindowMessage::key(), WindowManager::the(), and DestroyWindowMessage::window_id().
handle() [7/17]
virtual UniquePtr<Message> WindowServerDecoder::handle inline
Definition at line 448 of file WSConnection.h.
 { return nullptr; }
handle() [8/17]
UniquePtr< Message > WServerDecoder::handle (const GreetMessage & msg) override virtual
Reimplemented from WindowServerDecoder.
Definition at line 13 of file WSServerDecoder.cpp.
 {
     return new GreetMessageReply(msg.key(), Connection::the().alloc_connection());
 }
References Connection::alloc_connection(), GreetMessage::key(), and Connection::the().
handle() [9/17]
virtual UniquePtr<Message> WindowServerDecoder::handle inline
Definition at line 454 of file WSConnection.h.
 { return nullptr; }
handle() [10/17]
UniquePtr< Message > WServerDecoder::handle (const InvalidateMessage & msg) override virtual
Reimplemented from WindowServerDecoder.
Definition at line 52 of file WSServerDecoder.cpp.
 {
     auto& wm = WindowManager::the();
     auto* window = wm.window(msg.window_id());
     if (!window) {
         return nullptr;
     }
     auto rect = msg.rect();
     rect.offset_by(window->content_bounds().origin());
     rect.intersect(window->content_bounds());
     Compositor::the().invalidate(rect);
     return nullptr;
 }
References Compositor::invalidate(), LG::Rect::offset_by(), InvalidateMessage::rect(), Compositor::the(), WindowManager::the(), and InvalidateMessage::window_id().
handle() [11/17]
UniquePtr<Message> WindowServerDecoder::handle inline override
Definition at line 420 of file WSConnection.h.
     {
         if (magic() != msg.decoder_magic()) {
             return nullptr;
         }
         switch(msg.id()) {
         case 1:
             return handle(static_cast<const GreetMessage&>(msg));
         case 3:
             return handle(static_cast<const CreateWindowMessage&>(msg));
         case 5:
             return handle(static_cast<const DestroyWindowMessage&>(msg));
         case 7:
             return handle(static_cast<const SetBufferMessage&>(msg));
         case 8:
             return handle(static_cast<const SetBarStyleMessage&>(msg));
         case 9:
             return handle(static_cast<const SetTitleMessage&>(msg));
         case 10:
             return handle(static_cast<const InvalidateMessage&>(msg));
         case 11:
             return handle(static_cast<const AskBringToFrontMessage&>(msg));
         default:
             return nullptr;
         }
     }
handle() [12/17]
virtual UniquePtr<Message> WindowServerDecoder::handle inline
Definition at line 452 of file WSConnection.h.
 { return nullptr; }
handle() [13/17]
UniquePtr< Message > WServerDecoder::handle (const SetBarStyleMessage & msg) override virtual
Reimplemented from WindowServerDecoder.
Definition at line 77 of file WSServerDecoder.cpp.
 {
     auto& wm = WindowManager::the();
     auto* window = wm.window(msg.window_id());
     if (!window) {
         return nullptr;
     }
     window->frame().set_color(LG::Color(msg.color()));
     return nullptr;
 }
References SetBarStyleMessage::color(), WindowManager::the(), and SetBarStyleMessage::window_id().
handle() [14/17]
virtual UniquePtr<Message> WindowServerDecoder::handle inline
Definition at line 451 of file WSConnection.h.
 { return nullptr; }
handle() [15/17]
UniquePtr< Message > WServerDecoder::handle (const SetBufferMessage & msg) override virtual
Reimplemented from WindowServerDecoder.
Definition at line 30 of file WSServerDecoder.cpp.
 {
     auto* window = WindowManager::the().window(msg.window_id());
     if (!window) {
         return nullptr;
     }
     window->set_buffer(msg.buffer_id());
     window->content_bitmap().set_format(LG::PixelBitmapFormat(msg.format()));
     return nullptr;
 }
References SetBufferMessage::buffer_id(), SetBufferMessage::format(), Window::set_buffer(), WindowManager::the(), WindowManager::window(), and SetBufferMessage::window_id().
handle() [16/17]
virtual UniquePtr<Message> WindowServerDecoder::handle inline
Definition at line 453 of file WSConnection.h.
 { return nullptr; }
handle() [17/17]
UniquePtr< Message > WServerDecoder::handle (const SetTitleMessage & msg) override virtual
Reimplemented from WindowServerDecoder.
Definition at line 66 of file WSServerDecoder.cpp.
 {
     auto& wm = WindowManager::the();
     auto* window = wm.window(msg.window_id());
     if (!window) {
         return nullptr;
     }
     window->frame().set_app_name(msg.title());
     return nullptr;
 }
References WindowManager::the(), SetTitleMessage::title(), and SetTitleMessage::window_id().
The documentation for this class was generated from the following files:
servers/window_server/WSServerDecoder.h
servers/window_server/WSServerDecoder.cpp