oneOS: LG::Color Class Reference
LG::Color Class Reference
#include <Color.h>
Public Types
enum Colors {
Red , Blue , Green , White ,
Black
}
Public Member Functions
Color ()=default
Color (Colors)
Color (const Color &c)
Color (uint32_t color)
Color (uint8_t r, uint8_t g, uint8_t b, uint8_t alpha=255)
~Color ()
Color & operator= (const Color &c)
Color & operator= (Color &&c)
uint8_t alpha () const
bool is_opaque () const
uint8_t red () const
uint8_t green () const
uint8_t blue () const
uint32_t u32 () const
void mix_with (const Color &clr)
Private Attributes
uint8_t m_b { 0 }
uint8_t m_g { 0 }
uint8_t m_r { 0 }
uint8_t m_opacity { 0 }
Detailed Description
Definition at line 18 of file Color.h.
Member Enumeration Documentation
Colors
enum LG::Color::Colors
Enumerator
Red
Blue
Green
White
Black
Definition at line 20 of file Color.h.
                 {
         Red,
         Blue,
         Green,
         White,
         Black,
     };
Constructor & Destructor Documentation
Color() [1/5]
LG::Color::Color () default
Color() [2/5]
LG::Color::Color (Colors clr)
Definition at line 13 of file Color.cpp.
 {
     struct rgb {
         uint8_t r;
         uint8_t g;
         uint8_t b;
     } rgb_color;
     switch (clr) {
     case Red:
         rgb_color = { 255, 0, 0 };
         break;
     case Blue:
         rgb_color = { 0, 0, 255 };
         break;
     case Green:
         rgb_color = { 0, 255, 0 };
         break;
     case White:
         rgb_color = { 255, 255, 255 };
         break;
     case Black:
         rgb_color = { 0, 0, 0 };
         break;
     default:
         break;
     }
     m_r = rgb_color.r;
     m_g = rgb_color.g;
     m_b = rgb_color.b;
     m_opacity = 0;
 }
References Black, Blue, g, Green, m_b, m_g, m_opacity, m_r, Red, and White.
Color() [3/5]
LG::Color::Color (const Color & c) inline
Definition at line 30 of file Color.h.
         : m_opacity(c.m_opacity)
         , m_r(c.m_r)
         , m_g(c.m_g)
         , m_b(c.m_b)
     {
     }
Color() [4/5]
LG::Color::Color (uint32_t color) inline
Definition at line 38 of file Color.h.
         : m_opacity((color & 0xFF000000) >> 24)
         , m_r((color & 0x00FF0000) >> 16)
         , m_g((color & 0x0000FF00) >> 8)
         , m_b((color & 0x000000FF) >> 0)
     {
     }
Color() [5/5]
LG::Color::Color (uint8_t r, uint8_t g, uint8_t b, uint8_t alpha = 255) inline
Definition at line 46 of file Color.h.
         : m_opacity(255 - alpha)
         , m_b(b)
         , m_g(g)
         , m_r(r)
     {
     }
~Color()
LG::Color::~Color () inline
Definition at line 54 of file Color.h.
 { }
Member Function Documentation
alpha()
uint8_t LG::Color::alpha () const inline
Definition at line 74 of file Color.h.
 { return 255 - m_opacity; }
References m_opacity.
Referenced by mix_with().
blue()
uint8_t LG::Color::blue () const inline
Definition at line 79 of file Color.h.
 { return m_b; }
References m_b.
Referenced by mix_with().
green()
uint8_t LG::Color::green () const inline
Definition at line 78 of file Color.h.
 { return m_g; }
References m_g.
Referenced by mix_with().
is_opaque()
bool LG::Color::is_opaque () const inline
Definition at line 75 of file Color.h.
 { return m_opacity == 255; }
References m_opacity.
Referenced by mix_with().
mix_with()
void LG::Color::mix_with (const Color & clr) inline
Definition at line 90 of file Color.h.
     {
         if (clr.is_opaque() || !alpha()) {
             return;
         }
         int alpha_c = 256 * (alpha() + clr.alpha()) - alpha() * clr.alpha();
         int alpha_of_me = alpha() * (255 - clr.alpha());
         int alpha_of_it = 256 * clr.alpha();
         m_r = (red() * alpha_of_me + clr.red() * alpha_of_it) / alpha_c;
         m_g = (green() * alpha_of_me + clr.green() * alpha_of_it) / alpha_c;
         m_b = (blue() * alpha_of_me + clr.blue() * alpha_of_it) / alpha_c;
         m_opacity = 255 - (alpha_c / 256);
     }
References alpha(), blue(), green(), is_opaque(), m_b, m_g, m_opacity, m_r, and red().
operator=() [1/2]
Color& LG::Color::operator= (Color && c) inline
Definition at line 65 of file Color.h.
     {
         m_opacity = c.m_opacity;
         m_r = c.m_r;
         m_g = c.m_g;
         m_b = c.m_b;
         return *this;
     }
References m_b, m_g, m_opacity, and m_r.
operator=() [2/2]
Color& LG::Color::operator= (const Color & c) inline
Definition at line 56 of file Color.h.
     {
         m_opacity = c.m_opacity;
         m_r = c.m_r;
         m_g = c.m_g;
         m_b = c.m_b;
         return *this;
     }
References m_b, m_g, m_opacity, and m_r.
red()
uint8_t LG::Color::red () const inline
Definition at line 77 of file Color.h.
 { return m_r; }
References m_r.
Referenced by mix_with().
u32()
uint32_t LG::Color::u32 () const inline
Definition at line 81 of file Color.h.
     {
         uint32_t clr = (m_opacity << 24)
             | (m_b << 0)
             | (m_g << 8)
             | (m_r << 16);
         return clr;
     }
References m_b, m_g, m_opacity, and m_r.
Referenced by LG::Context::fill(), and UI::Window::set_frame_style().
Field Documentation
m_b
uint8_t LG::Color::m_b { 0 } private
Definition at line 107 of file Color.h.
Referenced by blue(), Color(), mix_with(), operator=(), and u32().
m_g
uint8_t LG::Color::m_g { 0 } private
Definition at line 108 of file Color.h.
Referenced by Color(), green(), mix_with(), operator=(), and u32().
m_opacity
uint8_t LG::Color::m_opacity { 0 } private
Definition at line 110 of file Color.h.
Referenced by alpha(), Color(), is_opaque(), mix_with(), operator=(), and u32().
m_r
uint8_t LG::Color::m_r { 0 } private
Definition at line 109 of file Color.h.
Referenced by Color(), mix_with(), operator=(), red(), and u32().
The documentation for this class was generated from the following files:
libs/libg/Color.h
libs/libg/Color.cpp