oneOS: UI::Window Class Reference
UI::Window Class Reference
#include <Window.h>
Public Member Functions
Window ()
Window (uint32_t width, uint32_t height, WindowType type=WindowType::Standard)
Window (uint32_t width, uint32_t height, const LG::String &path)
int id () const
WindowType type () const
SharedBuffer< LG::Color > & buffer ()
const SharedBuffer< LG::Color > & buffer () const
LG::PixelBitmap & bitmap ()
const LG::PixelBitmap & bitmap () const
void receive_event (UniquePtr< LFoundation::Event > event) override
template<class T , class... Args>
T & create_superview (Args &&... args)
void set_bitmap_format (LG::PixelBitmapFormat format)
View * superview () const
void set_focused_view (View &view)
View * focused_view ()
const LG::Rect & bounds () const
bool set_title (const LG::String &title)
bool set_frame_style (const LG::Color &color)
bool did_format_change ()
const LG::String & icon_path () const
Public Member Functions inherited from LFoundation::EventReceiver
EventReceiver ()
~EventReceiver ()
Private Attributes
uint32_t m_id
WindowType m_type { WindowType::Standard }
LG::Rect m_bounds
LG::PixelBitmap m_bitmap
SharedBuffer< LG::Color > m_buffer
View * m_superview { nullptr }
View * m_focused_view { nullptr }
LG::String m_icon_path { "/res/icons/apps/missing.icon" }
Detailed Description
Definition at line 27 of file Window.h.
Constructor & Destructor Documentation
Window() [1/3]
Window::Window ()
Definition at line 16 of file Window.cpp.
     : Window(400, 300)
 {
 }
Window() [2/3]
Window::Window (uint32_t width, uint32_t height, WindowType type = WindowType::Standard)
Definition at line 21 of file Window.cpp.
     : m_bounds(0, 0, width, height)
     , m_buffer(size_t(width * height * 4))
     , m_bitmap()
     , m_type(type)
 {
     m_id = Connection::the().new_window(*this);
     m_bitmap = LG::PixelBitmap(m_buffer.data(), bounds().width(), bounds().height());
     App::the().set_window(this);
 }
References bounds(), Sys::SharedBuffer< T >::data(), m_bitmap, m_buffer, m_id, UI::Connection::new_window(), UI::App::set_window(), UI::App::the(), and UI::Connection::the().
Window() [3/3]
Window::Window (uint32_t width, uint32_t height, const LG::String & path)
Definition at line 32 of file Window.cpp.
     : m_bounds(0, 0, width, height)
     , m_buffer(size_t(width * height * 4))
     , m_bitmap()
     , m_icon_path(icon_path)
 {
     m_id = Connection::the().new_window(*this);
     m_bitmap = LG::PixelBitmap(m_buffer.data(), bounds().width(), bounds().height());
     App::the().set_window(this);
 }
References bounds(), Sys::SharedBuffer< T >::data(), m_bitmap, m_buffer, m_id, UI::Connection::new_window(), UI::App::set_window(), UI::App::the(), and UI::Connection::the().
Member Function Documentation
bitmap() [1/2]
LG::PixelBitmap& UI::Window::bitmap () inline
Definition at line 39 of file Window.h.
 { return m_bitmap; }
References m_bitmap.
Referenced by did_format_change().
bitmap() [2/2]
const LG::PixelBitmap& UI::Window::bitmap () const inline
Definition at line 40 of file Window.h.
 { return m_bitmap; }
References m_bitmap.
bounds()
const LG::Rect& UI::Window::bounds () const inline
Definition at line 61 of file Window.h.
 { return m_bounds; }
References m_bounds.
Referenced by create_superview(), UI::Connection::new_window(), and Window().
buffer() [1/2]
SharedBuffer<LG::Color>& UI::Window::buffer () inline
Definition at line 36 of file Window.h.
 { return m_buffer; }
References m_buffer.
Referenced by did_format_change(), and UI::Connection::new_window().
buffer() [2/2]
const SharedBuffer<LG::Color>& UI::Window::buffer () const inline
Definition at line 37 of file Window.h.
 { return m_buffer; }
References m_buffer.
create_superview()
template<class T , class... Args> T& UI::Window::create_superview (Args &&... args) inline
Definition at line 45 of file Window.h.
     {
         T* new_view = new T(bounds(), args...);
         new_view->set_window(this);
         m_superview = new_view;
         m_superview->set_needs_display();
         return *new_view;
     }
References __main__::args, bounds(), m_superview, and UI::View::set_needs_display().
did_format_change()
bool Window::did_format_change ()
Notifies the window server that the bitmap format of the window was changed.
Returns
The status of operation.
Definition at line 72 of file Window.cpp.
 {
     SetBufferMessage msg(Connection::the().key(), id(), buffer().id(), bitmap().format());
     return App::the().connection().send_async_message(msg);
 }
References bitmap(), buffer(), UI::App::connection(), UI::Connection::send_async_message(), UI::App::the(), and UI::Connection::the().
Referenced by set_bitmap_format().
focused_view()
View* UI::Window::focused_view () inline
Definition at line 59 of file Window.h.
 { return m_focused_view; }
References m_focused_view.
icon_path()
const LG::String& UI::Window::icon_path () const inline
Definition at line 67 of file Window.h.
 { return m_icon_path; }
References m_icon_path.
Referenced by UI::Connection::new_window().
id()
int UI::Window::id () const inline
Definition at line 33 of file Window.h.
 { return m_id; }
References m_id.
receive_event()
void Window::receive_event (UniquePtr< LFoundation::Event > event) override virtual
Reimplemented from LFoundation::EventReceiver.
Reimplemented in DockWindow.
Definition at line 78 of file Window.cpp.
 {
     if (event->type() == Event::Type::MouseEvent) {
         if (m_superview) {
             MouseEvent& own_event = *(MouseEvent*)event.get();
             m_superview->receive_mouse_move_event(own_event);
         }
     }
     if (event->type() == Event::Type::MouseActionEvent) {
         if (m_superview) {
             MouseActionEvent& own_event = *(MouseActionEvent*)event.get();
             auto* view = m_superview->hit_test({(int)own_event.x(), (int)own_event.y()});
             view->receive_mouse_action_event(own_event);
         }
     }
     if (event->type() == Event::Type::MouseLeaveEvent) {
         if (m_superview) {
             MouseLeaveEvent& own_event = *(MouseLeaveEvent*)event.get();
             m_superview->receive_mouse_leave_event(own_event);
         }
     }
     if (event->type() == Event::Type::KeyUpEvent) {
         if (m_focused_view) {
             KeyUpEvent& own_event = *(KeyUpEvent*)event.get();
             m_focused_view->receive_keyup_event(own_event);
         }
     }
     if (event->type() == Event::Type::KeyDownEvent) {
         if (m_focused_view) {
             KeyDownEvent& own_event = *(KeyDownEvent*)event.get();
             m_focused_view->receive_keydown_event(own_event);
         }
     }
     if (event->type() == Event::Type::DisplayEvent) {
         if (m_superview) {
             DisplayEvent& own_event = *(DisplayEvent*)event.get();
             m_superview->receive_display_event(own_event);
         }
     }
 }
References UniquePtr< T >::get(), UI::View::hit_test(), m_focused_view, m_superview, UI::View::receive_display_event(), UI::View::receive_keydown_event(), UI::View::receive_keyup_event(), UI::View::receive_mouse_action_event(), UI::View::receive_mouse_leave_event(), UI::View::receive_mouse_move_event(), LFoundation::Event::type(), UI::MouseActionEvent::x(), and UI::MouseActionEvent::y().
set_bitmap_format()
void UI::Window::set_bitmap_format (LG::PixelBitmapFormat format) inline
Definition at line 54 of file Window.h.
 { m_bitmap.set_format(format), did_format_change(); }
References did_format_change(), m_bitmap, and LG::PixelBitmap::set_format().
set_focused_view()
void UI::Window::set_focused_view (View & view) inline
Definition at line 58 of file Window.h.
 { m_focused_view = &view; }
References m_focused_view.
set_frame_style()
bool Window::set_frame_style (const LG::Color & color)
Sets frame style for the window.
Parameters
color A color to be set.
Returns
The status of operation.
Definition at line 61 of file Window.cpp.
 {
     SetBarStyleMessage msg(Connection::the().key(), id(), color.u32(), 0);
     return App::the().connection().send_async_message(msg);
 }
References UI::App::connection(), UI::Connection::send_async_message(), UI::App::the(), UI::Connection::the(), and LG::Color::u32().
set_title()
bool Window::set_title (const LG::String & title)
Sets title for the window.
Parameters
title A title to be set.
Returns
The status of operation.
Definition at line 49 of file Window.cpp.
 {
     SetTitleMessage msg(Connection::the().key(), id(), title);
     return App::the().connection().send_async_message(msg);
 }
References UI::App::connection(), UI::Connection::send_async_message(), UI::App::the(), and UI::Connection::the().
superview()
View* UI::Window::superview () const inline
Definition at line 56 of file Window.h.
 { return m_superview; }
References m_superview.
Referenced by DockWindow::receive_event().
type()
WindowType UI::Window::type () const inline
Definition at line 34 of file Window.h.
 { return m_type; }
References m_type.
Referenced by token.Token::__str__(), and UI::Connection::new_window().
Field Documentation
m_bitmap
LG::PixelBitmap UI::Window::m_bitmap private
Definition at line 73 of file Window.h.
Referenced by bitmap(), set_bitmap_format(), and Window().
m_bounds
LG::Rect UI::Window::m_bounds private
Definition at line 72 of file Window.h.
Referenced by bounds().
m_buffer
SharedBuffer<LG::Color> UI::Window::m_buffer private
Definition at line 74 of file Window.h.
Referenced by buffer(), and Window().
m_focused_view
View* UI::Window::m_focused_view { nullptr } private
Definition at line 76 of file Window.h.
Referenced by focused_view(), receive_event(), and set_focused_view().
m_icon_path
LG::String UI::Window::m_icon_path { "/res/icons/apps/missing.icon" } private
Definition at line 77 of file Window.h.
Referenced by icon_path().
m_id
uint32_t UI::Window::m_id private
Definition at line 70 of file Window.h.
Referenced by id(), and Window().
m_superview
View* UI::Window::m_superview { nullptr } private
Definition at line 75 of file Window.h.
Referenced by create_superview(), receive_event(), and superview().
m_type
WindowType UI::Window::m_type { WindowType::Standard } private
Definition at line 71 of file Window.h.
Referenced by type().
The documentation for this class was generated from the following files:
libs/libui/Window.h
libs/libui/Window.cpp