oneOS: DockWindow Class Reference
DockWindow Class Reference
#include <DockWindow.h>
Public Member Functions
DockWindow ()
void receive_event (UniquePtr< LFoundation::Event > event) override
Public Member Functions inherited from UI::Window
Window ()
Window (uint32_t width, uint32_t height, WindowType type=WindowType::Standard)
Window (uint32_t width, uint32_t height, const LG::String &path)
int id () const
WindowType type () const
SharedBuffer< LG::Color > & buffer ()
const SharedBuffer< LG::Color > & buffer () const
LG::PixelBitmap & bitmap ()
const LG::PixelBitmap & bitmap () const
template<class T , class... Args>
T & create_superview (Args &&... args)
void set_bitmap_format (LG::PixelBitmapFormat format)
View * superview () const
void set_focused_view (View &view)
View * focused_view ()
const LG::Rect & bounds () const
bool set_title (const LG::String &title)
bool set_frame_style (const LG::Color &color)
bool did_format_change ()
const LG::String & icon_path () const
Public Member Functions inherited from LFoundation::EventReceiver
EventReceiver ()
~EventReceiver ()
Detailed Description
Definition at line 5 of file DockWindow.h.
Constructor & Destructor Documentation
DockWindow()
DockWindow::DockWindow () inline
Definition at line 7 of file DockWindow.h.
         : UI::Window(1024, 36, UI::WindowType::Dock)
     {
     }
Member Function Documentation
receive_event()
void DockWindow::receive_event (UniquePtr< LFoundation::Event > event) override virtual
Reimplemented from UI::Window.
Definition at line 5 of file DockWindow.cpp.
 {
     if (event->type() == UI::Event::Type::NotifyWindowStatusChangedEvent) {
         UI::NotifyWindowStatusChangedEvent& own_event = *(UI::NotifyWindowStatusChangedEvent*)event.get();
         DockView* it = (DockView*)superview();
         if (own_event.type() == 0) {
             it->new_entity(own_event.changed_window_id());
         }
         if (own_event.type() == 2) {
             it->remove_entity(own_event.changed_window_id());
         }
     }
     if (event->type() == UI::Event::Type::NotifyWindowIconChangedEvent) {
         UI::NotifyWindowIconChangedEvent& own_event = *(UI::NotifyWindowIconChangedEvent*)event.get();
         DockView* it = (DockView*)superview();
         it->set_icon(own_event.changed_window_id(), own_event.icon_path());
     }
     Window::receive_event(move(event));
 }
References UI::NotifyWindowStatusChangedEvent::changed_window_id(), UI::NotifyWindowIconChangedEvent::changed_window_id(), UniquePtr< T >::get(), UI::NotifyWindowIconChangedEvent::icon_path(), move(), DockView::new_entity(), DockView::remove_entity(), DockView::set_icon(), UI::Window::superview(), LFoundation::Event::type(), and UI::NotifyWindowStatusChangedEvent::type().
The documentation for this class was generated from the following files:
userland/dock/DockWindow.h
userland/dock/DockWindow.cpp