oneOS: Connection Class Reference
Connection Class Reference
#include <Connection.h>
Public Member Functions
Connection (int connection_fd)
void listen ()
bool send_async_message (const Message &msg) const
int alloc_connection ()
void receive_event (UniquePtr< LFoundation::Event > event) override
Public Member Functions inherited from LFoundation::EventReceiver
EventReceiver ()
~EventReceiver ()
Static Public Member Functions
static Connection & the ()
Private Attributes
int m_connection_fd
int m_connections_number { 0 }
ServerConnection< WServerDecoder, WindowClientDecoder > m_connection_with_clients
WServerDecoder m_server_decoder
WindowClientDecoder m_client_decoder
Detailed Description
Definition at line 16 of file Connection.h.
Constructor & Destructor Documentation
Connection()
Connection::Connection (int connection_fd)
Definition at line 20 of file Connection.cpp.
     : m_connection_fd(connection_fd)
     , m_server_decoder()
     , m_client_decoder()
     , m_connection_with_clients(m_connection_fd, m_server_decoder, m_client_decoder)
 {
     s_the = this;
     bind(m_connection_fd, "/win.sock", 9);
     LFoundation::EventLoop::the().add(
         m_connection_fd, [] {
             Connection::the().listen();
         },
         nullptr);
 }
References LFoundation::EventLoop::add(), bind(), listen(), m_connection_fd, s_the, LFoundation::EventLoop::the(), and the().
Member Function Documentation
alloc_connection()
int Connection::alloc_connection () inline
Definition at line 27 of file Connection.h.
 { return ++m_connections_number; }
References m_connections_number.
Referenced by WServerDecoder::handle().
listen()
void Connection::listen () inline
Definition at line 21 of file Connection.h.
     {
         m_connection_with_clients.pump_messages();
     }
References m_connection_with_clients, and ServerConnection< ServerDecoder, ClientDecoder >::pump_messages().
Referenced by Connection().
receive_event()
void Connection::receive_event (UniquePtr< LFoundation::Event > event) override virtual
Reimplemented from LFoundation::EventReceiver.
Definition at line 35 of file Connection.cpp.
 {
     if (event->type() == WSEvent::Type::SendEvent) {
         UniquePtr<SendEvent> send_event = move(event);
         m_connection_with_clients.send_message(*send_event->message());
     }
 }
References m_connection_with_clients, move(), ServerConnection< ServerDecoder, ClientDecoder >::send_message(), and LFoundation::Event::type().
send_async_message()
bool Connection::send_async_message (const Message & msg) const inline
Definition at line 26 of file Connection.h.
 { return m_connection_with_clients.send_message(msg); }
References m_connection_with_clients, and ServerConnection< ServerDecoder, ClientDecoder >::send_message().
Referenced by Window::set_needs_display().
the()
Connection & Connection::the () static
Definition at line 15 of file Connection.cpp.
 {
     return *s_the;
 }
References s_the.
Referenced by Connection(), WServerDecoder::handle(), and Window::set_needs_display().
Field Documentation
m_client_decoder
WindowClientDecoder Connection::m_client_decoder private
Definition at line 35 of file Connection.h.
m_connection_fd
int Connection::m_connection_fd private
Definition at line 31 of file Connection.h.
Referenced by Connection().
m_connection_with_clients
ServerConnection<WServerDecoder, WindowClientDecoder> Connection::m_connection_with_clients private
Definition at line 33 of file Connection.h.
Referenced by listen(), receive_event(), and send_async_message().
m_connections_number
int Connection::m_connections_number { 0 } private
Definition at line 32 of file Connection.h.
Referenced by alloc_connection().
m_server_decoder
WServerDecoder Connection::m_server_decoder private
Definition at line 34 of file Connection.h.
The documentation for this class was generated from the following files:
servers/window_server/Connection.h
servers/window_server/Connection.cpp