oneOS: SetBufferMessage Class Reference
SetBufferMessage Class Reference
#include <WSConnection.h>
Public Member Functions
SetBufferMessage (message_key_t key, uint32_t window_id, int buffer_id, int format)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
uint32_t window_id () const
int buffer_id () const
int format () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
uint32_t m_window_id
int m_buffer_id
int m_format
Detailed Description
Definition at line 180 of file WSConnection.h.
Constructor & Destructor Documentation
SetBufferMessage()
SetBufferMessage::SetBufferMessage (message_key_t key, uint32_t window_id, int buffer_id, int format) inline
Definition at line 182 of file WSConnection.h.
         : m_key(key)
         , m_window_id(window_id)
         , m_buffer_id(buffer_id)
         , m_format(format)
     {
     }
Member Function Documentation
buffer_id()
int SetBufferMessage::buffer_id () const inline
Definition at line 194 of file WSConnection.h.
 { return m_buffer_id; }
References m_buffer_id.
Referenced by WServerDecoder::handle().
decoder_magic()
int SetBufferMessage::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 192 of file WSConnection.h.
 { return 320; }
Referenced by encode().
encode()
EncodedMessage SetBufferMessage::encode () const inline override virtual
Reimplemented from Message.
Definition at line 196 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_window_id);
         Encoder::append(buffer, m_buffer_id);
         Encoder::append(buffer, m_format);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), m_buffer_id, m_format, and m_window_id.
format()
int SetBufferMessage::format () const inline
Definition at line 195 of file WSConnection.h.
 { return m_format; }
References m_format.
Referenced by WServerDecoder::handle().
id()
int SetBufferMessage::id () const inline override virtual
Reimplemented from Message.
Definition at line 189 of file WSConnection.h.
 { return 7; }
key()
int SetBufferMessage::key () const inline override virtual
Reimplemented from Message.
Definition at line 191 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode().
reply_id()
int SetBufferMessage::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 190 of file WSConnection.h.
 { return -1; }
window_id()
uint32_t SetBufferMessage::window_id () const inline
Definition at line 193 of file WSConnection.h.
 { return m_window_id; }
References m_window_id.
Referenced by WServerDecoder::handle().
Field Documentation
m_buffer_id
int SetBufferMessage::m_buffer_id private
Definition at line 210 of file WSConnection.h.
Referenced by buffer_id(), and encode().
m_format
int SetBufferMessage::m_format private
Definition at line 211 of file WSConnection.h.
Referenced by encode(), and format().
m_key
message_key_t SetBufferMessage::m_key private
Definition at line 208 of file WSConnection.h.
Referenced by key().
m_window_id
uint32_t SetBufferMessage::m_window_id private
Definition at line 209 of file WSConnection.h.
Referenced by encode(), and window_id().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h