oneOS: MouseActionMessage Class Reference
MouseActionMessage Class Reference
#include <WSConnection.h>
Public Member Functions
MouseActionMessage (message_key_t key, int win_id, int type, uint32_t x, uint32_t y)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
int win_id () const
int type () const
uint32_t x () const
uint32_t y () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
int m_win_id
int m_type
uint32_t m_x
uint32_t m_y
Detailed Description
Definition at line 492 of file WSConnection.h.
Constructor & Destructor Documentation
MouseActionMessage()
MouseActionMessage::MouseActionMessage (message_key_t key, int win_id, int type, uint32_t x, uint32_t y) inline
Definition at line 494 of file WSConnection.h.
         : m_key(key)
         , m_win_id(win_id)
         , m_type(type)
         , m_x(x)
         , m_y(y)
     {
     }
Member Function Documentation
decoder_magic()
int MouseActionMessage::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 505 of file WSConnection.h.
 { return 737; }
Referenced by encode().
encode()
EncodedMessage MouseActionMessage::encode () const inline override virtual
Reimplemented from Message.
Definition at line 510 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_win_id);
         Encoder::append(buffer, m_type);
         Encoder::append(buffer, m_x);
         Encoder::append(buffer, m_y);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), m_type, m_win_id, m_x, and m_y.
id()
int MouseActionMessage::id () const inline override virtual
Reimplemented from Message.
Definition at line 502 of file WSConnection.h.
 { return 2; }
key()
int MouseActionMessage::key () const inline override virtual
Reimplemented from Message.
Definition at line 504 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode().
reply_id()
int MouseActionMessage::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 503 of file WSConnection.h.
 { return -1; }
type()
int MouseActionMessage::type () const inline
Definition at line 507 of file WSConnection.h.
 { return m_type; }
References m_type.
Referenced by token.Token::__str__(), and UI::ClientDecoder::handle().
win_id()
int MouseActionMessage::win_id () const inline
Definition at line 506 of file WSConnection.h.
 { return m_win_id; }
References m_win_id.
Referenced by UI::ClientDecoder::handle().
x()
uint32_t MouseActionMessage::x () const inline
Definition at line 508 of file WSConnection.h.
 { return m_x; }
References m_x.
Referenced by UI::ClientDecoder::handle().
y()
uint32_t MouseActionMessage::y () const inline
Definition at line 509 of file WSConnection.h.
 { return m_y; }
References m_y.
Referenced by UI::ClientDecoder::handle().
Field Documentation
m_key
message_key_t MouseActionMessage::m_key private
Definition at line 523 of file WSConnection.h.
Referenced by key().
m_type
int MouseActionMessage::m_type private
Definition at line 525 of file WSConnection.h.
Referenced by encode(), and type().
m_win_id
int MouseActionMessage::m_win_id private
Definition at line 524 of file WSConnection.h.
Referenced by encode(), and win_id().
m_x
uint32_t MouseActionMessage::m_x private
Definition at line 526 of file WSConnection.h.
Referenced by encode(), and x().
m_y
uint32_t MouseActionMessage::m_y private
Definition at line 527 of file WSConnection.h.
Referenced by encode(), and y().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h