oneOS: WindowManager Class Reference
WindowManager Class Reference
#include <WindowManager.h>
Public Member Functions
WindowManager ()
void add_window (Window *window)
void remove_window (Window *window)
void close_window (Window &window)
Window * window (int id)
void do_bring_to_front (Window &window)
void bring_to_front (Window &window)
LinkedList< Window > & windows ()
const LinkedList< Window > & windows () const
int next_win_id ()
void receive_event (UniquePtr< LFoundation::Event > event) override
int mouse_x () const
int mouse_y () const
bool is_mouse_left_button_pressed () const
constexpr int cursor_size () const
void setup_dock (Window *window)
bool notify_listner_about_window_status (const Window &window, int changed_window_id, WindowStatusUpdateType type)
bool notify_listner_about_changed_icon (const Window &, int changed_window_id)
void notify_window_status_changed (int changed_window_id, WindowStatusUpdateType type)
void notify_window_icon_changed (int changed_window_id)
Public Member Functions inherited from LFoundation::EventReceiver
EventReceiver ()
~EventReceiver ()
Static Public Member Functions
static WindowManager & the ()
Private Member Functions
void start_window_move (Window &window)
bool continue_window_move (MouseEvent *mouse_event)
void update_mouse_position (MouseEvent *mouse_event)
void receive_mouse_event (UniquePtr< LFoundation::Event > event)
void receive_keyboard_event (UniquePtr< LFoundation::Event > event)
WeakPtr< Window > & movable_window ()
const WeakPtr< Window > & movable_window () const
WeakPtr< Window > & hovered_window ()
const WeakPtr< Window > & hovered_window () const
WeakPtr< Window > & active_window ()
const WeakPtr< Window > & active_window () const
Private Attributes
LinkedList< Window > m_windows
Screen & m_screen
Connection & m_connection
Compositor & m_compositor
LFoundation::EventLoop & m_event_loop
WeakPtr< Window > m_dock_window {}
WeakPtr< Window > m_movable_window {}
WeakPtr< Window > m_active_window {}
WeakPtr< Window > m_hovered_window {}
int m_next_win_id { 0 }
int m_mouse_x { 0 }
int m_mouse_y { 0 }
bool m_mouse_left_button_pressed { false }
bool m_mouse_changed_button_status { false }
Detailed Description
Definition at line 24 of file WindowManager.h.
Constructor & Destructor Documentation
WindowManager()
WindowManager::WindowManager ()
Definition at line 23 of file WindowManager.cpp.
     : m_screen(Screen::the())
     , m_connection(Connection::the())
     , m_compositor(Compositor::the())
     , m_event_loop(LFoundation::EventLoop::the())
 {
     s_the = this;
 }
References s_the.
Member Function Documentation
active_window() [1/2]
WeakPtr<Window>& WindowManager::active_window () inline private
Definition at line 119 of file WindowManager.h.
 { return m_active_window; }
References m_active_window.
Referenced by receive_keyboard_event(), and remove_window().
active_window() [2/2]
const WeakPtr<Window>& WindowManager::active_window () const inline private
Definition at line 120 of file WindowManager.h.
 { return m_active_window; }
References m_active_window.
add_window()
void WindowManager::add_window (Window * window) inline
Definition at line 29 of file WindowManager.h.
     {
         if (window->type() == WindowType::Dock) {
            setup_dock(window);
         }
         m_windows.push_back(window);
         bring_to_front(*window);
         notify_window_status_changed(window->id(), WindowStatusUpdateType::Created);
     }
References bring_to_front(), Created, Dock, Window::id(), m_windows, notify_window_status_changed(), Algo::LinkedList< T >::push_back(), setup_dock(), Window::type(), and window().
bring_to_front()
void WindowManager::bring_to_front (Window & window) inline
Definition at line 78 of file WindowManager.h.
     {
         do_bring_to_front(window);
         if (m_dock_window) {
             do_bring_to_front(*m_dock_window);
         }
         m_compositor.invalidate(window.bounds());
     }
References Window::bounds(), do_bring_to_front(), Compositor::invalidate(), m_compositor, m_dock_window, and window().
Referenced by add_window(), and receive_mouse_event().
close_window()
void WindowManager::close_window (Window & window) inline
Definition at line 56 of file WindowManager.h.
     {
         m_event_loop.add(m_connection, new SendEvent(new WindowCloseRequestMessage(window.connection_id(), window.id())));
     }
References LFoundation::EventLoop::add(), Window::connection_id(), Window::id(), m_connection, m_event_loop, and window().
continue_window_move()
bool WindowManager::continue_window_move (MouseEvent * mouse_event) private
Definition at line 46 of file WindowManager.cpp.
 {
     if (!movable_window()) {
         return false;
     }
     update_mouse_position(mouse_event);
     if (!is_mouse_left_button_pressed()) {
         m_movable_window = nullptr;
         return true;
     }
     auto bounds = movable_window()->bounds();
     m_compositor.invalidate(movable_window()->bounds());
     movable_window()->bounds().offset_by(mouse_event->packet().x_offset, -mouse_event->packet().y_offset);
     movable_window()->content_bounds().offset_by(mouse_event->packet().x_offset, -mouse_event->packet().y_offset);
     bounds.unite(movable_window()->bounds());
     m_compositor.invalidate(bounds);
     return true;
 }
References Window::bounds(), Window::content_bounds(), Compositor::invalidate(), is_mouse_left_button_pressed(), m_compositor, m_movable_window, movable_window(), LG::Rect::offset_by(), MouseEvent::packet(), update_mouse_position(), MousePacket::x_offset, and MousePacket::y_offset.
Referenced by receive_mouse_event().
cursor_size()
constexpr int WindowManager::cursor_size () const inline constexpr
Definition at line 96 of file WindowManager.h.
 { return 14; }
do_bring_to_front()
void WindowManager::do_bring_to_front (Window & window) inline
Definition at line 71 of file WindowManager.h.
     {
         auto* window_ptr = &window;
         m_windows.remove(window_ptr);
         m_windows.push_front(window_ptr);
     }
References m_windows, Algo::LinkedList< T >::push_front(), Algo::LinkedList< T >::remove(), and window().
Referenced by bring_to_front().
hovered_window() [1/2]
WeakPtr<Window>& WindowManager::hovered_window () inline private
Definition at line 117 of file WindowManager.h.
 { return m_hovered_window; }
References m_hovered_window.
Referenced by receive_mouse_event(), and remove_window().
hovered_window() [2/2]
const WeakPtr<Window>& WindowManager::hovered_window () const inline private
Definition at line 118 of file WindowManager.h.
 { return m_hovered_window; }
References m_hovered_window.
is_mouse_left_button_pressed()
bool WindowManager::is_mouse_left_button_pressed () const inline
Definition at line 95 of file WindowManager.h.
 { return m_mouse_left_button_pressed; }
References m_mouse_left_button_pressed.
Referenced by continue_window_move(), and receive_mouse_event().
mouse_x()
int WindowManager::mouse_x () const inline
Definition at line 93 of file WindowManager.h.
 { return m_mouse_x; }
References m_mouse_x.
mouse_y()
int WindowManager::mouse_y () const inline
Definition at line 94 of file WindowManager.h.
 { return m_mouse_y; }
References m_mouse_y.
movable_window() [1/2]
WeakPtr<Window>& WindowManager::movable_window () inline private
Definition at line 115 of file WindowManager.h.
 { return m_movable_window; }
References m_movable_window.
Referenced by continue_window_move(), and remove_window().
movable_window() [2/2]
const WeakPtr<Window>& WindowManager::movable_window () const inline private
Definition at line 116 of file WindowManager.h.
 { return m_movable_window; }
References m_movable_window.
next_win_id()
int WindowManager::next_win_id () inline
Definition at line 89 of file WindowManager.h.
 { return ++m_next_win_id; }
References m_next_win_id.
notify_listner_about_changed_icon()
bool WindowManager::notify_listner_about_changed_icon (const Window & win, int changed_window_id)
Definition at line 184 of file WindowManager.cpp.
 {
 #ifdef WM_DEBUG
     Dbg() << "notify_listner_about_changed_icon " << win.id() << " that " << changed_window_id << "\n";
 #endif
     auto* changed_window_ptr = window(changed_window_id);
     if (!changed_window_ptr) {
         return false;
     }
     m_event_loop.add(m_connection, new SendEvent(new NotifyWindowIconChangedMessage(win.connection_id(), win.id(), changed_window_id, changed_window_ptr->icon_path())));
     return true;
 }
References LFoundation::EventLoop::add(), Window::connection_id(), Window::id(), m_connection, m_event_loop, and window().
Referenced by notify_window_icon_changed().
notify_listner_about_window_status()
bool WindowManager::notify_listner_about_window_status (const Window & window, int changed_window_id, WindowStatusUpdateType type)
Definition at line 175 of file WindowManager.cpp.
 {
 #ifdef WM_DEBUG
     Dbg() << "notify_listner_about_window_status " << win.id() << " that " << changed_window_id << " " << type << "\n";
 #endif
     m_event_loop.add(m_connection, new SendEvent(new NotifyWindowStatusChangedMessage(win.connection_id(), win.id(), changed_window_id, (int)type)));
     return true;
 }
References LFoundation::EventLoop::add(), Window::connection_id(), Window::id(), m_connection, m_event_loop, and type.
Referenced by notify_window_status_changed().
notify_window_icon_changed()
void WindowManager::notify_window_icon_changed (int changed_window_id)
Definition at line 206 of file WindowManager.cpp.
 {
     for (auto& window : m_windows) {
         if (window.event_mask() & WindowEvent::IconChange) {
             notify_listner_about_changed_icon(window, changed_window_id);
         }
     }
 }
References Window::event_mask(), IconChange, m_windows, notify_listner_about_changed_icon(), and window().
notify_window_status_changed()
void WindowManager::notify_window_status_changed (int changed_window_id, WindowStatusUpdateType type)
Definition at line 197 of file WindowManager.cpp.
 {
     for (auto& window : m_windows) {
         if (window.event_mask() & WindowEvent::WindowStatus) {
             notify_listner_about_window_status(window, changed_window_id, type);
         }
     }
 }
References Window::event_mask(), m_windows, notify_listner_about_window_status(), type, window(), and WindowStatus.
Referenced by add_window(), and remove_window().
receive_event()
void WindowManager::receive_event (UniquePtr< LFoundation::Event > event) override virtual
Reimplemented from LFoundation::EventReceiver.
Definition at line 163 of file WindowManager.cpp.
 {
     if (event->type() == WSEvent::Type::MouseEvent) {
         receive_mouse_event(move(event));
     }
     if (event->type() == WSEvent::Type::KeyboardEvent) {
         receive_keyboard_event(move(event));
     }
 }
References move(), receive_keyboard_event(), receive_mouse_event(), and LFoundation::Event::type().
receive_keyboard_event()
void WindowManager::receive_keyboard_event (UniquePtr< LFoundation::Event > event) private
Definition at line 153 of file WindowManager.cpp.
 {
     KeyboardEvent* keyboard_event = (KeyboardEvent*)event.release();
     if (active_window()) {
         auto window = active_window();
         m_event_loop.add(m_connection, new SendEvent(new KeyboardMessage(window->connection_id(), window->id(), keyboard_event->packet().key)));
     }
     delete keyboard_event;
 }
References active_window(), LFoundation::EventLoop::add(), Window::connection_id(), Window::id(), KeyboardPacket::key, m_connection, m_event_loop, KeyboardEvent::packet(), UniquePtr< T >::release(), and window().
Referenced by receive_event().
receive_mouse_event()
void WindowManager::receive_mouse_event (UniquePtr< LFoundation::Event > event) private
Definition at line 100 of file WindowManager.cpp.
 {
     MouseEvent* mouse_event = (MouseEvent*)event.release();
     auto new_hovered_window = WeakPtr<Window>();
     if (continue_window_move(mouse_event)) {
         goto end;
     }
     update_mouse_position(mouse_event);
     for (auto& window : m_windows) {
         if (window.bounds().contains(m_mouse_x, m_mouse_y)) {
             if (window.frame().bounds().contains(m_mouse_x, m_mouse_y)) {
                 if (is_mouse_left_button_pressed()) {
                     auto tap_point = LG::Point<int>(m_mouse_x - window.frame().bounds().min_x(), m_mouse_y - window.frame().bounds().min_y());
                     window.frame().receive_tap_event(tap_point);
                     start_window_move(window);
                 }
             } else if (window.content_bounds().contains(m_mouse_x, m_mouse_y)) {
                 LG::Point<int> point(m_mouse_x, m_mouse_y);
                 point.offset_by(-window.content_bounds().origin());
                 m_event_loop.add(m_connection, new SendEvent(new MouseMoveMessage(window.connection_id(), window.id(), point.x(), point.y())));
                 new_hovered_window = window.weak_ptr();
                 if (m_mouse_changed_button_status) {
                     // FIXME: only left button for now!
                     m_event_loop.add(m_connection, new SendEvent(new MouseActionMessage(window.connection_id(), window.id(), !is_mouse_left_button_pressed(), point.x(), point.y())));
                 }
             }
             if (is_mouse_left_button_pressed() && m_active_window.ptr() != &window) {
                 bring_to_front(window);
                 m_active_window = window.weak_ptr();
             }
             break;
         }
     }
     if (hovered_window()) {
         auto window = hovered_window();
         if (window->id() != new_hovered_window->id()) {
             m_event_loop.add(m_connection, new SendEvent(new MouseLeaveMessage(window->connection_id(), window->id(), 0, 0)));
         }
     }
     m_hovered_window = new_hovered_window;
 end:
     delete mouse_event;
 }
References LFoundation::EventLoop::add(), Window::bounds(), WindowFrame::bounds(), bring_to_front(), Window::connection_id(), LG::Rect::contains(), Window::content_bounds(), continue_window_move(), Window::frame(), hovered_window(), Window::id(), is_mouse_left_button_pressed(), m_active_window, m_connection, m_event_loop, m_hovered_window, m_mouse_changed_button_status, m_mouse_x, m_mouse_y, m_windows, LG::Rect::min_x(), LG::Rect::min_y(), LG::Point< T >::offset_by(), LG::Rect::origin(), WeakPtr< T >::ptr(), WindowFrame::receive_tap_event(), UniquePtr< T >::release(), start_window_move(), update_mouse_position(), Weakable< T >::weak_ptr(), window(), LG::Point< T >::x(), and LG::Point< T >::y().
Referenced by receive_event().
remove_window()
void WindowManager::remove_window (Window * window) inline
Definition at line 39 of file WindowManager.h.
     {
         if (movable_window().ptr() == window) {
             m_movable_window = nullptr;
         }
         if (active_window().ptr() == window) {
             m_active_window = nullptr;
         }
         if (hovered_window().ptr() == window) {
             m_hovered_window = nullptr;
         }
         m_windows.remove(window);
         m_compositor.invalidate(window->bounds());
         notify_window_status_changed(window->id(), WindowStatusUpdateType::Removed);
         delete window;
     }
References active_window(), Window::bounds(), hovered_window(), Window::id(), Compositor::invalidate(), m_active_window, m_compositor, m_hovered_window, m_movable_window, m_windows, movable_window(), notify_window_status_changed(), Algo::LinkedList< T >::remove(), Removed, and window().
setup_dock()
void WindowManager::setup_dock (Window * window)
Definition at line 37 of file WindowManager.cpp.
 {
     window->make_frameless();
     window->bounds().set_y(m_screen.bounds().max_y() - window->bounds().height() + 1);
     window->content_bounds().set_y(m_screen.bounds().max_y() - window->bounds().height() + 1);
     window->set_event_mask(WindowEvent::IconChange | WindowEvent::WindowStatus);
     m_dock_window = window->weak_ptr();
 }
References Screen::bounds(), Window::bounds(), Window::content_bounds(), LG::Rect::height(), IconChange, m_dock_window, m_screen, Window::make_frameless(), LG::Rect::max_y(), Window::set_event_mask(), LG::Rect::set_y(), Weakable< T >::weak_ptr(), window(), and WindowStatus.
Referenced by add_window().
start_window_move()
void WindowManager::start_window_move (Window & window) private
Definition at line 32 of file WindowManager.cpp.
 {
     m_movable_window = window.weak_ptr();
 }
References m_movable_window, Weakable< T >::weak_ptr(), and window().
Referenced by receive_mouse_event().
the()
WindowManager & WindowManager::the () static
Definition at line 18 of file WindowManager.cpp.
 {
     return *s_the;
 }
References s_the.
Referenced by __attribute__(), WServerDecoder::handle(), WindowFrame::handle_control_panel_tap(), Devices::pump_keyboard(), and Devices::pump_mouse().
update_mouse_position()
void WindowManager::update_mouse_position (MouseEvent * mouse_event) private
Definition at line 68 of file WindowManager.cpp.
 {
     auto invalidate_bounds = m_compositor.cursor_manager().current_cursor().bounds();
     invalidate_bounds.origin().set(m_compositor.cursor_manager().draw_position(m_mouse_x, m_mouse_y));
     m_compositor.invalidate(invalidate_bounds);
     m_mouse_x += mouse_event->packet().x_offset;
     m_mouse_y -= mouse_event->packet().y_offset;
     if (m_mouse_x < 0) {
         m_mouse_x = 0;
     }
     if (m_mouse_y < 0) {
         m_mouse_y = 0;
     }
     if (m_mouse_x >= m_screen.width() - 1) {
         m_mouse_x = m_screen.width() - 1;
     }
     if (m_mouse_y >= m_screen.height() - 1) {
         m_mouse_y = m_screen.height() - 1;
     }
     invalidate_bounds.origin().set(m_compositor.cursor_manager().draw_position(m_mouse_x, m_mouse_y));
     m_compositor.invalidate(invalidate_bounds);
     m_mouse_changed_button_status = false;
     if (m_mouse_left_button_pressed != (mouse_event->packet().button_states & 1)) {
         m_mouse_changed_button_status = true;
     }
     m_mouse_left_button_pressed = (mouse_event->packet().button_states & 1);
 }
References LG::PixelBitmap::bounds(), MousePacket::button_states, CursorManager::current_cursor(), Compositor::cursor_manager(), CursorManager::draw_position(), Screen::height(), Compositor::invalidate(), m_compositor, m_mouse_changed_button_status, m_mouse_left_button_pressed, m_mouse_x, m_mouse_y, m_screen, LG::Rect::origin(), MouseEvent::packet(), LG::Point< T >::set(), Screen::width(), MousePacket::x_offset, and MousePacket::y_offset.
Referenced by continue_window_move(), and receive_mouse_event().
window()
Window* WindowManager::window (int id) inline
Definition at line 61 of file WindowManager.h.
     {
         for (auto& window : m_windows) {
             if (window.id() == id) {
                 return &window;
             }
         }
         return nullptr;
     }
References Window::id(), and m_windows.
Referenced by add_window(), bring_to_front(), close_window(), do_bring_to_front(), WServerDecoder::handle(), notify_listner_about_changed_icon(), notify_window_icon_changed(), notify_window_status_changed(), receive_keyboard_event(), receive_mouse_event(), remove_window(), setup_dock(), and start_window_move().
windows() [1/2]
LinkedList<Window>& WindowManager::windows () inline
Definition at line 87 of file WindowManager.h.
 { return m_windows; }
References m_windows.
windows() [2/2]
const LinkedList<Window>& WindowManager::windows () const inline
Definition at line 88 of file WindowManager.h.
 { return m_windows; }
References m_windows.
Field Documentation
m_active_window
WeakPtr<Window> WindowManager::m_active_window {} private
Definition at line 131 of file WindowManager.h.
Referenced by active_window(), receive_mouse_event(), and remove_window().
m_compositor
Compositor& WindowManager::m_compositor private
Definition at line 126 of file WindowManager.h.
Referenced by bring_to_front(), continue_window_move(), remove_window(), and update_mouse_position().
m_connection
Connection& WindowManager::m_connection private
Definition at line 125 of file WindowManager.h.
Referenced by close_window(), notify_listner_about_changed_icon(), notify_listner_about_window_status(), receive_keyboard_event(), and receive_mouse_event().
m_dock_window
WeakPtr<Window> WindowManager::m_dock_window {} private
Definition at line 129 of file WindowManager.h.
Referenced by bring_to_front(), and setup_dock().
m_event_loop
LFoundation::EventLoop& WindowManager::m_event_loop private
Definition at line 127 of file WindowManager.h.
Referenced by close_window(), notify_listner_about_changed_icon(), notify_listner_about_window_status(), receive_keyboard_event(), and receive_mouse_event().
m_hovered_window
WeakPtr<Window> WindowManager::m_hovered_window {} private
Definition at line 132 of file WindowManager.h.
Referenced by hovered_window(), receive_mouse_event(), and remove_window().
m_mouse_changed_button_status
bool WindowManager::m_mouse_changed_button_status { false } private
Definition at line 138 of file WindowManager.h.
Referenced by receive_mouse_event(), and update_mouse_position().
m_mouse_left_button_pressed
bool WindowManager::m_mouse_left_button_pressed { false } private
Definition at line 137 of file WindowManager.h.
Referenced by is_mouse_left_button_pressed(), and update_mouse_position().
m_mouse_x
int WindowManager::m_mouse_x { 0 } private
Definition at line 135 of file WindowManager.h.
Referenced by mouse_x(), receive_mouse_event(), and update_mouse_position().
m_mouse_y
int WindowManager::m_mouse_y { 0 } private
Definition at line 136 of file WindowManager.h.
Referenced by mouse_y(), receive_mouse_event(), and update_mouse_position().
m_movable_window
WeakPtr<Window> WindowManager::m_movable_window {} private
Definition at line 130 of file WindowManager.h.
Referenced by continue_window_move(), movable_window(), remove_window(), and start_window_move().
m_next_win_id
int WindowManager::m_next_win_id { 0 } private
Definition at line 133 of file WindowManager.h.
Referenced by next_win_id().
m_screen
Screen& WindowManager::m_screen private
Definition at line 124 of file WindowManager.h.
Referenced by setup_dock(), and update_mouse_position().
m_windows
LinkedList<Window> WindowManager::m_windows private
Definition at line 122 of file WindowManager.h.
Referenced by add_window(), do_bring_to_front(), notify_window_icon_changed(), notify_window_status_changed(), receive_mouse_event(), remove_window(), window(), and windows().
The documentation for this class was generated from the following files:
servers/window_server/WindowManager.h
servers/window_server/WindowManager.cpp