oneOS: DockView Class Reference
DockView Class Reference
#include <DockView.h>
Public Member Functions
DockView (const LG::Rect &)
void display (const LG::Rect &rect) override
void click_began (const LG::Point< int > &location) override
DockEntity * find_entity (int window_id)
void new_entity (int window_id)
void remove_entity (int window_id)
void set_icon (int window_id, const LG::String &path)
void new_fast_launch_entity (const LG::String &icon_path, LG::String &&exec_path)
Public Member Functions inherited from UI::View
View (const LG::Rect &)
View (const LG::Rect &, const LG::Color &)
template<class T , class... Args>
T & add_subview (Args &&... args)
void remove_from_superview ()
template<typename Callback >
void foreach_subview (Callback callback) const
View * subview_at (const LG::Point< int > &point) const
View * hit_test (const LG::Point< int > &point)
const LG::Rect & frame () const
const LG::Rect & bounds () const
void set_width (size_t x)
void set_height (size_t x)
LG::Rect frame_in_window ()
Window * window ()
bool has_superview ()
View * superview ()
Vector< View * > & subviews ()
const Vector< View * > & subviews () const
void set_needs_display (const LG::Rect &)
void set_needs_display ()
bool is_hovered () const
void set_focusable (bool val)
bool is_focusable () const
virtual void did_display (const LG::Rect &rect)
virtual void hover_begin (const LG::Point< int > &location)
virtual void hover_end ()
virtual void click_ended ()
virtual void receive_mouse_move_event (MouseEvent &) override
virtual void receive_mouse_action_event (MouseActionEvent &) override
virtual void receive_mouse_leave_event (MouseLeaveEvent &) override
virtual void receive_keyup_event (KeyUpEvent &) override
virtual void receive_keydown_event (KeyDownEvent &) override
virtual void receive_display_event (DisplayEvent &) override
LG::Color & background_color ()
const LG::Color & background_color () const
virtual void set_background_color (const LG::Color &background_color)
Public Member Functions inherited from UI::Responder
bool send_invalidate_message_to_server (const LG::Rect &rect) const
void send_display_message_to_self (Window &win, const LG::Rect &display_rect)
void receive_event (UniquePtr< LFoundation::Event > event) override
Public Member Functions inherited from LFoundation::EventReceiver
EventReceiver ()
~EventReceiver ()
Private Member Functions
void launch (const FastLaunchEntity &ent)
Private Attributes
int m_fast_launch_entites_count { 0 }
LinkedList< FastLaunchEntity > m_fast_launch_entites {}
LinkedList< DockEntity > m_dock_entites {}
Additional Inherited Members
Protected Member Functions inherited from UI::Responder
Responder ()
Protected Attributes inherited from UI::Responder
bool m_display_message_sent { false }
LG::Rect m_prev_display_message {}
Detailed Description
Definition at line 9 of file DockView.h.
Constructor & Destructor Documentation
DockView()
DockView::DockView (const LG::Rect & frame)
Definition at line 12 of file DockView.cpp.
     : View(frame)
 {
 }
Member Function Documentation
click_began()
void DockView::click_began (const LG::Point< int > & location) override virtual
Reimplemented from UI::View.
Definition at line 106 of file DockView.cpp.
 {
     // Check if it is a tap on fast-launch icons
     int offsetx = 8;
     for (auto& entity : m_fast_launch_entites) {
         auto it = LG::Rect(offsetx, 2, 32, 32);
         if (it.contains(location)) {
             launch(entity);
         }
         offsetx += entity.icon().bounds().width() + 8;
     }
     offsetx += 8;
     for (auto& entity : m_dock_entites) {
         auto it = LG::Rect(offsetx, 2, 32, 32);
         if (it.contains(location)) {
             auto& app = UI::App::the();
             AskBringToFrontMessage msg(app.connection().key(), window()->id(), entity.window_id());
             app.connection().send_async_message(msg);
             return;
         }
         offsetx += entity.icon().bounds().width() + 8;
     }
 }
References launch(), m_dock_entites, m_fast_launch_entites, UI::App::the(), and UI::View::window().
display()
void DockView::display (const LG::Rect & rect) override virtual
Draws the receiver’s image within the passed-in rectangle.
Parameters
rect The portion of the view’s bounds that needs to be updated. The first time your view is drawn, this rectangle is typically the entire visible bounds of your view. However, during subsequent drawing operations, the rectangle may specify only part of your view.
Reimplemented from UI::View.
Definition at line 17 of file DockView.cpp.
 {
     // FIXME: Rendering is a bit studip now, will rewrite it
     //        completely when stackview is available.
     UI::Context ctx(*this);
     ctx.add_clip(rect);
     // Drawing fast-launch icons
     ctx.set_fill_color(background_color());
     ctx.fill(bounds());
     ctx.set_fill_color(LG::Color(222, 222, 222, 255));
     ctx.fill(LG::Rect(0, 0, 8 + 40 * m_fast_launch_entites_count, bounds().height()));
     // Drawing launched icons
     int offsetx = 8;
     for (auto& entity : m_fast_launch_entites) {
         ctx.draw({ offsetx, 2 }, entity.icon());
         offsetx += entity.icon().bounds().width() + 8;
     }
     offsetx += 8;
     for (auto& entity : m_dock_entites) {
         ctx.draw({ offsetx, 2 }, entity.icon());
         ctx.fill(LG::Rect(offsetx, 34, 32, 2));
         offsetx += entity.icon().bounds().width() + 8;
     }
 }
References LG::Context::add_clip(), UI::View::background_color(), UI::View::bounds(), LG::Context::draw(), LG::Context::fill(), m_dock_entites, m_fast_launch_entites, m_fast_launch_entites_count, and LG::Context::set_fill_color().
find_entity()
DockEntity * DockView::find_entity (int window_id)
Definition at line 57 of file DockView.cpp.
 {
     for (auto& ent : m_dock_entites) {
         if (ent.window_id() == window_id) {
             return &ent;
         }
     }
     return nullptr;
 }
References m_dock_entites.
Referenced by remove_entity(), and set_icon().
launch()
void DockView::launch (const FastLaunchEntity & ent) private
Definition at line 98 of file DockView.cpp.
 {
     if (fork() == 0) {
         execve(ent.path_to_exec().c_str(), 0, 0);
         ASSERT_NOT_REACHED();
     }
 }
References ASSERT_NOT_REACHED, Algo::String::c_str(), execve(), fork(), and FastLaunchEntity::path_to_exec().
Referenced by click_began().
new_entity()
void DockView::new_entity (int window_id)
Definition at line 67 of file DockView.cpp.
 {
     // Don't add an icon of dock (self).
     if (window()->id() != window_id) {
         auto* entity = new DockEntity(window_id);
         m_dock_entites.push_back(entity);
     }
 }
References m_dock_entites, Algo::LinkedList< T >::push_back(), and UI::View::window().
Referenced by DockWindow::receive_event().
new_fast_launch_entity()
void DockView::new_fast_launch_entity (const LG::String & icon_path, LG::String && exec_path)
Definition at line 46 of file DockView.cpp.
 {
     auto* entity = new FastLaunchEntity();
     LG::PNG::PNGLoader loader;
     entity->set_icon(loader.load_from_file(icon_path + "/32x32.png"));
     entity->set_path_to_exec(move(exec_path));
     m_fast_launch_entites.push_back(entity);
     m_fast_launch_entites_count++;
     set_needs_display();
 }
References LG::PNG::PNGLoader::load_from_file(), m_fast_launch_entites, m_fast_launch_entites_count, move(), Algo::LinkedList< T >::push_back(), and UI::View::set_needs_display().
remove_entity()
void DockView::remove_entity (int window_id)
Definition at line 76 of file DockView.cpp.
 {
     auto* ent = find_entity(window_id);
     if (!ent) {
         return;
     }
     m_dock_entites.remove(ent);
     delete ent;
     set_needs_display();
 }
References find_entity(), m_dock_entites, Algo::LinkedList< T >::remove(), and UI::View::set_needs_display().
Referenced by DockWindow::receive_event().
set_icon()
void DockView::set_icon (int window_id, const LG::String & path)
Definition at line 87 of file DockView.cpp.
 {
     auto* ent = find_entity(window_id);
     if (!ent) {
         return;
     }
     LG::PNG::PNGLoader loader;
     ent->set_icon(loader.load_from_file(path + "/32x32.png"));
     set_needs_display();
 }
References find_entity(), LG::PNG::PNGLoader::load_from_file(), and UI::View::set_needs_display().
Referenced by DockWindow::receive_event().
Field Documentation
m_dock_entites
LinkedList<DockEntity> DockView::m_dock_entites {} private
Definition at line 28 of file DockView.h.
Referenced by click_began(), display(), find_entity(), new_entity(), and remove_entity().
m_fast_launch_entites
LinkedList<FastLaunchEntity> DockView::m_fast_launch_entites {} private
Definition at line 27 of file DockView.h.
Referenced by click_began(), display(), and new_fast_launch_entity().
m_fast_launch_entites_count
int DockView::m_fast_launch_entites_count { 0 } private
Definition at line 26 of file DockView.h.
Referenced by display(), and new_fast_launch_entity().
The documentation for this class was generated from the following files:
userland/dock/DockView.h
userland/dock/DockView.cpp