oneOS: CreateWindowMessage Class Reference
CreateWindowMessage Class Reference
#include <WSConnection.h>
Public Member Functions
CreateWindowMessage (message_key_t key, int type, uint32_t width, uint32_t height, int buffer_id, LG::String icon_path)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
int type () const
uint32_t width () const
uint32_t height () const
int buffer_id () const
LG::String icon_path () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
int m_type
uint32_t m_width
uint32_t m_height
int m_buffer_id
LG::String m_icon_path
Detailed Description
Definition at line 60 of file WSConnection.h.
Constructor & Destructor Documentation
CreateWindowMessage()
CreateWindowMessage::CreateWindowMessage (message_key_t key, int type, uint32_t width, uint32_t height, int buffer_id, LG::String icon_path) inline
Definition at line 62 of file WSConnection.h.
         : m_key(key)
         , m_type(type)
         , m_width(width)
         , m_height(height)
         , m_buffer_id(buffer_id)
         , m_icon_path(icon_path)
     {
     }
Member Function Documentation
buffer_id()
int CreateWindowMessage::buffer_id () const inline
Definition at line 78 of file WSConnection.h.
 { return m_buffer_id; }
References m_buffer_id.
decoder_magic()
int CreateWindowMessage::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 74 of file WSConnection.h.
 { return 320; }
Referenced by encode().
encode()
EncodedMessage CreateWindowMessage::encode () const inline override virtual
Reimplemented from Message.
Definition at line 80 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_type);
         Encoder::append(buffer, m_width);
         Encoder::append(buffer, m_height);
         Encoder::append(buffer, m_buffer_id);
         Encoder::append(buffer, m_icon_path);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), m_buffer_id, m_height, m_icon_path, m_type, and m_width.
height()
uint32_t CreateWindowMessage::height () const inline
Definition at line 77 of file WSConnection.h.
 { return m_height; }
References m_height.
Referenced by Window::Window().
icon_path()
LG::String CreateWindowMessage::icon_path () const inline
Definition at line 79 of file WSConnection.h.
 { return m_icon_path; }
References m_icon_path.
Referenced by WServerDecoder::handle().
id()
int CreateWindowMessage::id () const inline override virtual
Reimplemented from Message.
Definition at line 71 of file WSConnection.h.
 { return 3; }
key()
int CreateWindowMessage::key () const inline override virtual
Reimplemented from Message.
Definition at line 73 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode(), and WServerDecoder::handle().
reply_id()
int CreateWindowMessage::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 72 of file WSConnection.h.
 { return 4; }
type()
int CreateWindowMessage::type () const inline
Definition at line 75 of file WSConnection.h.
 { return m_type; }
References m_type.
Referenced by token.Token::__str__().
width()
uint32_t CreateWindowMessage::width () const inline
Definition at line 76 of file WSConnection.h.
 { return m_width; }
References m_width.
Referenced by Window::Window().
Field Documentation
m_buffer_id
int CreateWindowMessage::m_buffer_id private
Definition at line 98 of file WSConnection.h.
Referenced by buffer_id(), and encode().
m_height
uint32_t CreateWindowMessage::m_height private
Definition at line 97 of file WSConnection.h.
Referenced by encode(), and height().
m_icon_path
LG::String CreateWindowMessage::m_icon_path private
Definition at line 99 of file WSConnection.h.
Referenced by encode(), and icon_path().
m_key
message_key_t CreateWindowMessage::m_key private
Definition at line 94 of file WSConnection.h.
Referenced by key().
m_type
int CreateWindowMessage::m_type private
Definition at line 95 of file WSConnection.h.
Referenced by encode(), and type().
m_width
uint32_t CreateWindowMessage::m_width private
Definition at line 96 of file WSConnection.h.
Referenced by encode(), and width().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h