oneOS: UI::ClientDecoder Class Reference
UI::ClientDecoder Class Reference
#include <ClientDecoder.h>
Public Member Functions
ClientDecoder ()
~ClientDecoder ()
virtual UniquePtr< Message > handle (const MouseMoveMessage &msg) override
virtual UniquePtr< Message > handle (const MouseActionMessage &msg) override
virtual UniquePtr< Message > handle (const MouseLeaveMessage &msg) override
virtual UniquePtr< Message > handle (const KeyboardMessage &msg) override
virtual UniquePtr< Message > handle (const DisplayMessage &msg) override
virtual UniquePtr< Message > handle (const WindowCloseRequestMessage &msg) override
virtual UniquePtr< Message > handle (const NotifyWindowStatusChangedMessage &msg) override
virtual UniquePtr< Message > handle (const NotifyWindowIconChangedMessage &msg) override
UniquePtr< Message > handle (const Message &msg) override
virtual UniquePtr< Message > handle (const MouseMoveMessage &msg)
virtual UniquePtr< Message > handle (const MouseActionMessage &msg)
virtual UniquePtr< Message > handle (const MouseLeaveMessage &msg)
virtual UniquePtr< Message > handle (const KeyboardMessage &msg)
virtual UniquePtr< Message > handle (const DisplayMessage &msg)
virtual UniquePtr< Message > handle (const WindowCloseRequestMessage &msg)
virtual UniquePtr< Message > handle (const DisconnectMessage &msg)
virtual UniquePtr< Message > handle (const NotifyWindowStatusChangedMessage &msg)
virtual UniquePtr< Message > handle (const NotifyWindowIconChangedMessage &msg)
Public Member Functions inherited from WindowClientDecoder
WindowClientDecoder ()
int magic () const
UniquePtr< Message > decode (const char *buf, size_t size, size_t &decoded_msg_len) override
UniquePtr< Message > handle (const Message &msg) override
virtual UniquePtr< Message > handle (const DisconnectMessage &msg)
Public Member Functions inherited from MessageDecoder
MessageDecoder ()
virtual ~MessageDecoder ()
virtual int magic ()
Private Attributes
LFoundation::EventLoop & m_event_loop
Detailed Description
Definition at line 17 of file ClientDecoder.h.
Constructor & Destructor Documentation
ClientDecoder()
UI::ClientDecoder::ClientDecoder ()
Definition at line 16 of file ClientDecoder.cpp.
     : m_event_loop(LFoundation::EventLoop::the())
 {
 }
~ClientDecoder()
UI::ClientDecoder::~ClientDecoder () inline
Definition at line 20 of file ClientDecoder.h.
 { }
Member Function Documentation
handle() [1/18]
virtual UniquePtr<Message> WindowClientDecoder::handle inline
Definition at line 849 of file WSConnection.h.
 { return nullptr; }
handle() [2/18]
virtual UniquePtr<Message> WindowClientDecoder::handle inline
Definition at line 847 of file WSConnection.h.
 { return nullptr; }
handle() [3/18]
UniquePtr< Message > UI::ClientDecoder::handle (const DisplayMessage & msg) override virtual
Reimplemented from WindowClientDecoder.
Definition at line 60 of file ClientDecoder.cpp.
 {
     m_event_loop.add(App::the().window(), new DisplayEvent(msg.rect()));
     return nullptr;
 }
References LFoundation::EventLoop::add(), m_event_loop, DisplayMessage::rect(), and UI::App::the().
handle() [4/18]
virtual UniquePtr<Message> WindowClientDecoder::handle inline
Definition at line 846 of file WSConnection.h.
 { return nullptr; }
handle() [5/18]
UniquePtr< Message > UI::ClientDecoder::handle (const KeyboardMessage & msg) override virtual
Reimplemented from WindowClientDecoder.
Definition at line 45 of file ClientDecoder.cpp.
 {
     if (App::the().window().id() == msg.win_id()) {
         // Checking if the key is down or up
         if (msg.kbd_key() >> 31) {
             uint32_t key = msg.kbd_key();
             key &= 0xEFFFFFFF;
             m_event_loop.add(App::the().window(), new KeyUpEvent(key));
         } else {
             m_event_loop.add(App::the().window(), new KeyDownEvent(msg.kbd_key()));
         }
     }
     return nullptr;
 }
References LFoundation::EventLoop::add(), KeyboardMessage::kbd_key(), m_event_loop, UI::App::the(), and KeyboardMessage::win_id().
handle() [6/18]
UniquePtr<Message> WindowClientDecoder::handle inline override
Definition at line 813 of file WSConnection.h.
     {
         if (magic() != msg.decoder_magic()) {
             return nullptr;
         }
         switch(msg.id()) {
         case 1:
             return handle(static_cast<const MouseMoveMessage&>(msg));
         case 2:
             return handle(static_cast<const MouseActionMessage&>(msg));
         case 3:
             return handle(static_cast<const MouseLeaveMessage&>(msg));
         case 4:
             return handle(static_cast<const KeyboardMessage&>(msg));
         case 5:
             return handle(static_cast<const DisplayMessage&>(msg));
         case 6:
             return handle(static_cast<const WindowCloseRequestMessage&>(msg));
         case 7:
             return handle(static_cast<const DisconnectMessage&>(msg));
         case 8:
             return handle(static_cast<const NotifyWindowStatusChangedMessage&>(msg));
         case 9:
             return handle(static_cast<const NotifyWindowIconChangedMessage&>(msg));
         default:
             return nullptr;
         }
     }
handle() [7/18]
virtual UniquePtr<Message> WindowClientDecoder::handle inline
Definition at line 844 of file WSConnection.h.
 { return nullptr; }
handle() [8/18]
UniquePtr< Message > UI::ClientDecoder::handle (const MouseActionMessage & msg) override virtual
Reimplemented from WindowClientDecoder.
Definition at line 29 of file ClientDecoder.cpp.
 {
     if (App::the().window().id() == msg.win_id()) {
         m_event_loop.add(App::the().window(), new MouseActionEvent((MouseActionType)msg.type(), msg.x(), msg.y()));
     }
     return nullptr;
 }
References LFoundation::EventLoop::add(), m_event_loop, UI::App::the(), MouseActionMessage::type(), MouseActionMessage::win_id(), MouseActionMessage::x(), and MouseActionMessage::y().
handle() [9/18]
virtual UniquePtr<Message> WindowClientDecoder::handle inline
Definition at line 845 of file WSConnection.h.
 { return nullptr; }
handle() [10/18]
UniquePtr< Message > UI::ClientDecoder::handle (const MouseLeaveMessage & msg) override virtual
Reimplemented from WindowClientDecoder.
Definition at line 37 of file ClientDecoder.cpp.
 {
     if (App::the().window().id() == msg.win_id()) {
         m_event_loop.add(App::the().window(), new MouseLeaveEvent(msg.x(), msg.y()));
     }
     return nullptr;
 }
References LFoundation::EventLoop::add(), m_event_loop, UI::App::the(), MouseLeaveMessage::win_id(), MouseLeaveMessage::x(), and MouseLeaveMessage::y().
handle() [11/18]
virtual UniquePtr<Message> WindowClientDecoder::handle inline
Definition at line 843 of file WSConnection.h.
 { return nullptr; }
handle() [12/18]
UniquePtr< Message > UI::ClientDecoder::handle (const MouseMoveMessage & msg) override virtual
Reimplemented from WindowClientDecoder.
Definition at line 21 of file ClientDecoder.cpp.
 {
     if (App::the().window().id() == msg.win_id()) {
         m_event_loop.add(App::the().window(), new MouseEvent(msg.x(), msg.y()));
     }
     return nullptr;
 }
References LFoundation::EventLoop::add(), m_event_loop, UI::App::the(), MouseMoveMessage::win_id(), MouseMoveMessage::x(), and MouseMoveMessage::y().
handle() [13/18]
virtual UniquePtr<Message> WindowClientDecoder::handle inline
Definition at line 851 of file WSConnection.h.
 { return nullptr; }
handle() [14/18]
UniquePtr< Message > UI::ClientDecoder::handle (const NotifyWindowIconChangedMessage & msg) override virtual
Reimplemented from WindowClientDecoder.
Definition at line 84 of file ClientDecoder.cpp.
 {
     if (App::the().window().id() == msg.win_id()) {
         m_event_loop.add(App::the().window(), new NotifyWindowIconChangedEvent(msg.changed_window_id(), msg.icon_path()));
     }
     return nullptr;
 }
References LFoundation::EventLoop::add(), NotifyWindowIconChangedMessage::changed_window_id(), NotifyWindowIconChangedMessage::icon_path(), m_event_loop, UI::App::the(), and NotifyWindowIconChangedMessage::win_id().
handle() [15/18]
virtual UniquePtr<Message> WindowClientDecoder::handle inline
Definition at line 850 of file WSConnection.h.
 { return nullptr; }
handle() [16/18]
UniquePtr< Message > UI::ClientDecoder::handle (const NotifyWindowStatusChangedMessage & msg) override virtual
Reimplemented from WindowClientDecoder.
Definition at line 76 of file ClientDecoder.cpp.
 {
     if (App::the().window().id() == msg.win_id()) {
         m_event_loop.add(App::the().window(), new NotifyWindowStatusChangedEvent(msg.changed_window_id(), msg.type()));
     }
     return nullptr;
 }
References LFoundation::EventLoop::add(), NotifyWindowStatusChangedMessage::changed_window_id(), m_event_loop, UI::App::the(), NotifyWindowStatusChangedMessage::type(), and NotifyWindowStatusChangedMessage::win_id().
handle() [17/18]
virtual UniquePtr<Message> WindowClientDecoder::handle inline
Definition at line 848 of file WSConnection.h.
 { return nullptr; }
handle() [18/18]
UniquePtr< Message > UI::ClientDecoder::handle (const WindowCloseRequestMessage & msg) override virtual
Reimplemented from WindowClientDecoder.
Definition at line 66 of file ClientDecoder.cpp.
 {
     // TODO: Currently we support only 1 window per app.
     if (App::the().window().id() == msg.win_id()) {
         m_event_loop.add(App::the(), new WindowCloseRequestEvent(msg.win_id()));
     }
     return nullptr;
 }
References LFoundation::EventLoop::add(), m_event_loop, UI::App::the(), and WindowCloseRequestMessage::win_id().
Field Documentation
m_event_loop
LFoundation::EventLoop& UI::ClientDecoder::m_event_loop private
Definition at line 35 of file ClientDecoder.h.
Referenced by handle().
The documentation for this class was generated from the following files:
libs/libui/ClientDecoder.h
libs/libui/ClientDecoder.cpp