oneOS: Compositor Class Reference
Compositor Class Reference
#include <Compositor.h>
Public Member Functions
Compositor ()
void refresh ()
void optimized_invalidate_insert (Vector< LG::Rect > &data, const LG::Rect &area)
void invalidate (const LG::Rect &area)
CursorManager & cursor_manager ()
const CursorManager & cursor_manager () const
ResourceManager & resource_manager ()
const ResourceManager & resource_manager () const
Static Public Member Functions
static Compositor & the ()
Private Member Functions
void copy_changes_to_second_buffer (const Vector< LG::Rect > &areas)
Private Attributes
CursorManager & m_cursor_manager
ResourceManager & m_resource_manager
Vector< LG::Rect > m_invalidated_areas
Detailed Description
Definition at line 19 of file Compositor.h.
Constructor & Destructor Documentation
Compositor()
Compositor::Compositor ()
Definition at line 26 of file Compositor.cpp.
     : m_cursor_manager(CursorManager::the())
     , m_resource_manager(ResourceManager::the())
 {
     s_the = this;
     invalidate(Screen::the().bounds());
     LFoundation::EventLoop::the().add(LFoundation::Timer([] {
         Compositor::the().refresh();
     }));
 }
References LFoundation::EventLoop::add(), invalidate(), refresh(), s_the, LFoundation::EventLoop::the(), the(), and Screen::the().
Member Function Documentation
copy_changes_to_second_buffer()
void Compositor::copy_changes_to_second_buffer (const Vector< LG::Rect > & areas) private
Definition at line 37 of file Compositor.cpp.
 {
     auto& screen = Screen::the();
     for (int i = 0; i < areas.size(); i++) {
         auto bounds = areas[i].intersection(screen.bounds());
         uint32_t* buf1_ptr = (uint32_t*)&screen.display_bitmap()[bounds.min_y()][bounds.min_x()];
         uint32_t* buf2_ptr = (uint32_t*)&screen.write_bitmap()[bounds.min_y()][bounds.min_x()];
         for (int j = 0; j < bounds.height(); j++) {
             fast_copy(buf2_ptr, buf1_ptr, bounds.width());
             buf1_ptr += screen.width();
             buf2_ptr += screen.width();
         }
     }
 }
References fast_copy(), Algo::Vector< T >::size(), and Screen::the().
Referenced by __attribute__().
cursor_manager() [1/2]
CursorManager& Compositor::cursor_manager () inline
Definition at line 45 of file Compositor.h.
 { return m_cursor_manager; }
References m_cursor_manager.
Referenced by WindowManager::update_mouse_position().
cursor_manager() [2/2]
const CursorManager& Compositor::cursor_manager () const inline
Definition at line 46 of file Compositor.h.
 { return m_cursor_manager; }
References m_cursor_manager.
invalidate()
void Compositor::invalidate (const LG::Rect & area) inline
Definition at line 44 of file Compositor.h.
 { optimized_invalidate_insert(m_invalidated_areas, area); }
References m_invalidated_areas, and optimized_invalidate_insert().
Referenced by WindowFrame::add_control(), WindowManager::bring_to_front(), Compositor(), WindowManager::continue_window_move(), WServerDecoder::handle(), WindowManager::remove_window(), WindowFrame::set_app_name(), and WindowManager::update_mouse_position().
optimized_invalidate_insert()
void Compositor::optimized_invalidate_insert (Vector< LG::Rect > & data, const LG::Rect & area) inline
Definition at line 26 of file Compositor.h.
     {
         LG::Rect area_union;
         size_t area_square = area.square();
         size_t inv_area_square = 0;
         for (int i = 0; i < data.size(); i++) {
             inv_area_square = data[i].square();
             area_union = area.union_of(data[i]);
             if (area_square + inv_area_square > area_union.square()) {
                 data[i].unite(area);
                 return;
             }
         }
         data.push_back(area);
     }
References Algo::Vector< T >::push_back(), Algo::Vector< T >::size(), LG::Rect::square(), and LG::Rect::union_of().
Referenced by invalidate().
refresh()
void Compositor::refresh ()
Referenced by Compositor().
resource_manager() [1/2]
ResourceManager& Compositor::resource_manager () inline
Definition at line 47 of file Compositor.h.
 { return m_resource_manager; }
References m_resource_manager.
resource_manager() [2/2]
const ResourceManager& Compositor::resource_manager () const inline
Definition at line 48 of file Compositor.h.
 { return m_resource_manager; }
References m_resource_manager.
the()
Compositor & Compositor::the () static
Definition at line 21 of file Compositor.cpp.
 {
     return *s_the;
 }
References s_the.
Referenced by WindowFrame::add_control(), Compositor(), WServerDecoder::handle(), and WindowFrame::set_app_name().
Field Documentation
m_cursor_manager
CursorManager& Compositor::m_cursor_manager private
Definition at line 53 of file Compositor.h.
Referenced by __attribute__(), and cursor_manager().
m_invalidated_areas
Vector<LG::Rect> Compositor::m_invalidated_areas private
Definition at line 55 of file Compositor.h.
Referenced by __attribute__(), and invalidate().
m_resource_manager
ResourceManager& Compositor::m_resource_manager private
Definition at line 54 of file Compositor.h.
Referenced by __attribute__(), and resource_manager().
The documentation for this class was generated from the following files:
servers/window_server/Compositor.h
servers/window_server/Compositor.cpp