oneOS: SetTitleMessage Class Reference
SetTitleMessage Class Reference
#include <WSConnection.h>
Public Member Functions
SetTitleMessage (message_key_t key, uint32_t window_id, LG::String title)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
uint32_t window_id () const
LG::String title () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
uint32_t m_window_id
LG::String m_title
Detailed Description
Definition at line 248 of file WSConnection.h.
Constructor & Destructor Documentation
SetTitleMessage()
SetTitleMessage::SetTitleMessage (message_key_t key, uint32_t window_id, LG::String title) inline
Definition at line 250 of file WSConnection.h.
         : m_key(key)
         , m_window_id(window_id)
         , m_title(title)
     {
     }
Member Function Documentation
decoder_magic()
int SetTitleMessage::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 259 of file WSConnection.h.
 { return 320; }
Referenced by encode().
encode()
EncodedMessage SetTitleMessage::encode () const inline override virtual
Reimplemented from Message.
Definition at line 262 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_window_id);
         Encoder::append(buffer, m_title);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), m_title, and m_window_id.
id()
int SetTitleMessage::id () const inline override virtual
Reimplemented from Message.
Definition at line 256 of file WSConnection.h.
 { return 9; }
key()
int SetTitleMessage::key () const inline override virtual
Reimplemented from Message.
Definition at line 258 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode().
reply_id()
int SetTitleMessage::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 257 of file WSConnection.h.
 { return -1; }
title()
LG::String SetTitleMessage::title () const inline
Definition at line 261 of file WSConnection.h.
 { return m_title; }
References m_title.
Referenced by WServerDecoder::handle().
window_id()
uint32_t SetTitleMessage::window_id () const inline
Definition at line 260 of file WSConnection.h.
 { return m_window_id; }
References m_window_id.
Referenced by WServerDecoder::handle().
Field Documentation
m_key
message_key_t SetTitleMessage::m_key private
Definition at line 273 of file WSConnection.h.
Referenced by key().
m_title
LG::String SetTitleMessage::m_title private
Definition at line 275 of file WSConnection.h.
Referenced by encode(), and title().
m_window_id
uint32_t SetTitleMessage::m_window_id private
Definition at line 274 of file WSConnection.h.
Referenced by encode(), and window_id().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h