oneOS: NotifyWindowStatusChangedMessage Class Reference
NotifyWindowStatusChangedMessage Class Reference
#include <WSConnection.h>
Public Member Functions
NotifyWindowStatusChangedMessage (message_key_t key, int win_id, int changed_window_id, int type)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
int win_id () const
int changed_window_id () const
int type () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
int m_win_id
int m_changed_window_id
int m_type
Detailed Description
Definition at line 672 of file WSConnection.h.
Constructor & Destructor Documentation
NotifyWindowStatusChangedMessage()
NotifyWindowStatusChangedMessage::NotifyWindowStatusChangedMessage (message_key_t key, int win_id, int changed_window_id, int type) inline
Definition at line 674 of file WSConnection.h.
         : m_key(key)
         , m_win_id(win_id)
         , m_changed_window_id(changed_window_id)
         , m_type(type)
     {
     }
Member Function Documentation
changed_window_id()
int NotifyWindowStatusChangedMessage::changed_window_id () const inline
Definition at line 686 of file WSConnection.h.
 { return m_changed_window_id; }
References m_changed_window_id.
Referenced by UI::ClientDecoder::handle().
decoder_magic()
int NotifyWindowStatusChangedMessage::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 684 of file WSConnection.h.
 { return 737; }
Referenced by encode().
encode()
EncodedMessage NotifyWindowStatusChangedMessage::encode () const inline override virtual
Reimplemented from Message.
Definition at line 688 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_win_id);
         Encoder::append(buffer, m_changed_window_id);
         Encoder::append(buffer, m_type);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), m_changed_window_id, m_type, and m_win_id.
id()
int NotifyWindowStatusChangedMessage::id () const inline override virtual
Reimplemented from Message.
Definition at line 681 of file WSConnection.h.
 { return 8; }
key()
int NotifyWindowStatusChangedMessage::key () const inline override virtual
Reimplemented from Message.
Definition at line 683 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode().
reply_id()
int NotifyWindowStatusChangedMessage::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 682 of file WSConnection.h.
 { return -1; }
type()
int NotifyWindowStatusChangedMessage::type () const inline
Definition at line 687 of file WSConnection.h.
 { return m_type; }
References m_type.
Referenced by token.Token::__str__(), and UI::ClientDecoder::handle().
win_id()
int NotifyWindowStatusChangedMessage::win_id () const inline
Definition at line 685 of file WSConnection.h.
 { return m_win_id; }
References m_win_id.
Referenced by UI::ClientDecoder::handle().
Field Documentation
m_changed_window_id
int NotifyWindowStatusChangedMessage::m_changed_window_id private
Definition at line 702 of file WSConnection.h.
Referenced by changed_window_id(), and encode().
m_key
message_key_t NotifyWindowStatusChangedMessage::m_key private
Definition at line 700 of file WSConnection.h.
Referenced by key().
m_type
int NotifyWindowStatusChangedMessage::m_type private
Definition at line 703 of file WSConnection.h.
Referenced by encode(), and type().
m_win_id
int NotifyWindowStatusChangedMessage::m_win_id private
Definition at line 701 of file WSConnection.h.
Referenced by encode(), and win_id().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h