oneOS: LFoundation::EventLoop Class Reference
LFoundation::EventLoop Class Reference
#include <EventLoop.h>
Public Member Functions
EventLoop ()
void add (int fd, void(*on_read)(), void(*on_write)())
void add (const Timer &timer)
void add (Timer &&timer)
void add (EventReceiver &rec, Event *ptr)
void stop (int exit_code)
void check_fds ()
void check_timers ()
void pump ()
int run ()
Static Public Member Functions
static EventLoop & the ()
Private Attributes
bool m_stop_flag { false }
int m_exit_code { 0 }
Vector< FDWaiter > m_waiting_fds
Vector< Timer > m_timers
Vector< QueuedEvent > m_event_queue
Detailed Description
Definition at line 47 of file EventLoop.h.
Constructor & Destructor Documentation
EventLoop()
LFoundation::EventLoop::EventLoop ()
Definition at line 24 of file EventLoop.cpp.
 {
     s_the = this;
 }
References LFoundation::s_the.
Member Function Documentation
add() [1/4]
void LFoundation::EventLoop::add (const Timer & timer) inline
Definition at line 57 of file EventLoop.h.
     {
         m_timers.push_back(timer);
     }
References m_timers.
add() [2/4]
void LFoundation::EventLoop::add (EventReceiver & rec, Event * ptr) inline
Definition at line 67 of file EventLoop.h.
     {
         m_event_queue.push_back(QueuedEvent(rec, ptr));
     }
References m_event_queue.
add() [3/4]
void LFoundation::EventLoop::add (int fd, void(*)() on_read, void(*)() on_write) inline
Definition at line 52 of file EventLoop.h.
     {
         m_waiting_fds.push_back(FDWaiter(fd, on_read, on_write));
     }
References m_waiting_fds.
Referenced by WindowManager::close_window(), Compositor::Compositor(), UI::Connection::Connection(), Connection::Connection(), Devices::Devices(), UI::ClientDecoder::handle(), WindowManager::notify_listner_about_changed_icon(), WindowManager::notify_listner_about_window_status(), Devices::pump_keyboard(), ClientConnection< ServerDecoder, ClientDecoder >::pump_messages(), Devices::pump_mouse(), WindowManager::receive_keyboard_event(), WindowManager::receive_mouse_event(), UI::Responder::send_display_message_to_self(), and TerminalView::TerminalView().
add() [4/4]
void LFoundation::EventLoop::add (Timer && timer) inline
Definition at line 62 of file EventLoop.h.
     {
         m_timers.push_back(move(timer));
     }
References m_timers, and move().
check_fds()
void LFoundation::EventLoop::check_fds ()
Definition at line 29 of file EventLoop.cpp.
 {
     fd_set_t readfds;
     fd_set_t writefds;
     FD_ZERO(&readfds);
     FD_ZERO(&writefds);
     int nfds = -1;
     for (int i = 0; i < m_waiting_fds.size(); i++) {
         if (m_waiting_fds[i].m_on_read) {
             FD_SET(m_waiting_fds[i].m_fd, &readfds);
         }
         if (m_waiting_fds[i].m_on_write) {
             FD_SET(m_waiting_fds[i].m_fd, &writefds);
         }
         if (nfds < m_waiting_fds[i].m_fd) {
             nfds = m_waiting_fds[i].m_fd;
         }
     }
     // For now, that means, that we don't wait for fds.
     timeval_t timeout;
     timeout.tv_sec = 0;
     timeout.tv_usec = 0;
     int res = select(nfds + 1, &readfds, &writefds, nullptr, &timeout);
     for (int i = 0; i < m_waiting_fds.size(); i++) {
         if (m_waiting_fds[i].m_on_read) {
             if (FD_ISSET(m_waiting_fds[i].m_fd, &readfds)) {
                 m_event_queue.push_back(QueuedEvent(m_waiting_fds[i], new FDWaiterReadEvent()));
             }
         }
         if (m_waiting_fds[i].m_on_write) {
             if (FD_ISSET(m_waiting_fds[i].m_fd, &writefds)) {
                 m_event_queue.push_back(QueuedEvent(m_waiting_fds[i], new FDWaiterWriteEvent()));
             }
         }
     }
 }
References FD_ISSET, FD_SET, FD_ZERO, m_event_queue, m_waiting_fds, select(), timeval::tv_sec, and timeval::tv_usec.
Referenced by pump().
check_timers()
void LFoundation::EventLoop::check_timers ()
Definition at line 69 of file EventLoop.cpp.
 {
     for (int i = 0; i < m_timers.size(); i++) {
         if (m_timers[i].expired()) {
             m_event_queue.push_back(QueuedEvent(m_timers[i], new TimerEvent()));
         }
     }
 }
References m_event_queue, and m_timers.
Referenced by pump().
pump()
void LFoundation::EventLoop::pump ()
Definition at line 78 of file EventLoop.cpp.
 {
     check_fds();
     check_timers();
     Vector<QueuedEvent> events_to_dispatch(move(m_event_queue));
     for (int i = 0; i < events_to_dispatch.size(); i++) {
         events_to_dispatch[i].receiver.receive_event(move(events_to_dispatch[i].event));
     }
     if (!events_to_dispatch.size()) {
         sched_yield();
     }
 }
References check_fds(), check_timers(), m_event_queue, move(), sched_yield(), and Algo::Vector< T >::size().
Referenced by run().
run()
int LFoundation::EventLoop::run ()
Definition at line 91 of file EventLoop.cpp.
 {
     while (!m_stop_flag) {
         pump();
     }
     return m_exit_code;
 }
References m_exit_code, m_stop_flag, and pump().
Referenced by UI::App::run().
stop()
void LFoundation::EventLoop::stop (int exit_code) inline
Definition at line 72 of file EventLoop.h.
 { m_exit_code = exit_code, m_stop_flag = true; }
References m_exit_code, and m_stop_flag.
Referenced by UI::App::receive_event().
the()
EventLoop & LFoundation::EventLoop::the () static
Definition at line 19 of file EventLoop.cpp.
 {
     return *s_the;
 }
References LFoundation::s_the.
Referenced by Compositor::Compositor(), UI::Connection::Connection(), Connection::Connection(), Devices::Devices(), Devices::pump_keyboard(), ClientConnection< ServerDecoder, ClientDecoder >::pump_messages(), Devices::pump_mouse(), UI::Responder::send_display_message_to_self(), and TerminalView::TerminalView().
Field Documentation
m_event_queue
Vector<QueuedEvent> LFoundation::EventLoop::m_event_queue private
Definition at line 83 of file EventLoop.h.
Referenced by add(), check_fds(), check_timers(), and pump().
m_exit_code
int LFoundation::EventLoop::m_exit_code { 0 } private
Definition at line 80 of file EventLoop.h.
Referenced by run(), and stop().
m_stop_flag
bool LFoundation::EventLoop::m_stop_flag { false } private
Definition at line 79 of file EventLoop.h.
Referenced by run(), and stop().
m_timers
Vector<Timer> LFoundation::EventLoop::m_timers private
Definition at line 82 of file EventLoop.h.
Referenced by add(), and check_timers().
m_waiting_fds
Vector<FDWaiter> LFoundation::EventLoop::m_waiting_fds private
Definition at line 81 of file EventLoop.h.
Referenced by add(), and check_fds().
The documentation for this class was generated from the following files:
libs/libfoundation/EventLoop.h
libs/libfoundation/EventLoop.cpp