oneOS: LG::PNG::PNGLoader Class Reference
LG::PNG::PNGLoader Class Reference
#include <PNGLoader.h>
Public Member Functions
PNGLoader ()=default
~PNGLoader ()
PixelBitmap load_from_file (const Algo::String &path)
PixelBitmap load_from_mem (const uint8_t *ptr)
DataStreamer & streamer ()
Private Member Functions
bool check_header (const uint8_t *ptr) const
void proccess_stream (PixelBitmap &bitmap)
bool read_chunk (PixelBitmap &bitmap)
void read_IHDR (ChunkHeader &header, PixelBitmap &bitmap)
void read_TEXT (ChunkHeader &header, PixelBitmap &bitmap)
void read_PHYS (ChunkHeader &header, PixelBitmap &bitmap)
void read_IDAT (ChunkHeader &header, PixelBitmap &bitmap)
uint8_t paeth_predictor (int a, int b, int c)
void unfilter_scanlines ()
void copy_scanlines_to_bitmap (PixelBitmap &bitmap)
Private Attributes
DataStreamer m_streamer
IHDRChunk m_ihdr_chunk
ScanlineKeeper m_scanline_keeper
Detailed Description
Definition at line 127 of file PNGLoader.h.
Constructor & Destructor Documentation
PNGLoader()
LG::PNG::PNGLoader::PNGLoader () default
~PNGLoader()
LG::PNG::PNGLoader::~PNGLoader () inline
Definition at line 130 of file PNGLoader.h.
 { }
Member Function Documentation
check_header()
bool LG::PNG::PNGLoader::check_header (const uint8_t * ptr) const private
Definition at line 46 of file PNGLoader.cpp.
 {
     return memcmp(ptr, (uint8_t*)png_header, png_header_size) == 0;
 }
References memcmp(), LG::PNG::png_header, and LG::PNG::png_header_size.
Referenced by load_from_mem().
copy_scanlines_to_bitmap()
void LG::PNG::PNGLoader::copy_scanlines_to_bitmap (PixelBitmap & bitmap) private
Definition at line 198 of file PNGLoader.cpp.
 {
     if (m_ihdr_chunk.color_type == 2) {
         bitmap.set_format(PixelBitmapFormat::RGB);
         for (int i = 0; i < m_ihdr_chunk.height; i++) {
             auto& scanline = m_scanline_keeper.scanlines()[i];
             for (int j = 0, bit = 0; j < m_ihdr_chunk.width; j++) {
                 int r = scanline.data()[bit++];
                 int g = scanline.data()[bit++];
                 int b = scanline.data()[bit++];
                 int alpha = 255;
                 bitmap[i][j] = Color(r, g, b, alpha);
             }
         }
     }
     if (m_ihdr_chunk.color_type == 6) {
         bitmap.set_format(PixelBitmapFormat::RGBA);
         for (int i = 0; i < m_ihdr_chunk.height; i++) {
             auto& scanline = m_scanline_keeper.scanlines()[i];
             for (int j = 0, bit = 0; j < m_ihdr_chunk.width; j++) {
                 int r = scanline.data()[bit++];
                 int g = scanline.data()[bit++];
                 int b = scanline.data()[bit++];
                 int alpha = scanline.data()[bit++];
                 bitmap[i][j] = Color(r, g, b, alpha);
             }
         }
     }
 }
References LG::PNG::IHDRChunk::color_type, g, LG::PNG::IHDRChunk::height, m_ihdr_chunk, m_scanline_keeper, LG::RGB, LG::RGBA, LG::PNG::ScanlineKeeper::scanlines(), and LG::PNG::IHDRChunk::width.
Referenced by read_IDAT().
load_from_file()
PixelBitmap LG::PNG::PNGLoader::load_from_file (const Algo::String & path)
Definition at line 22 of file PNGLoader.cpp.
 {
     int fd = open(path.c_str(), O_RDONLY);
     if (fd < 0) {
         Dbg() << "PNGLoader: cant open\n";
         return PixelBitmap();
     }
     fstat_t stat;
     fstat(fd, &stat);
     mmap_params_t mmap_params;
     mmap_params.prot = PROT_READ;
     mmap_params.flags = MAP_PRIVATE;
     mmap_params.fd = fd;
     mmap_params.size = stat.size;
     uint8_t* ptr = (uint8_t*)mmap(&mmap_params);
     PixelBitmap bitmap = load_from_mem(ptr);
     // munmap(ptr);
     return bitmap;
 }
References bitmap, Algo::String::c_str(), mmap_params::fd, mmap_params::flags, fstat(), load_from_mem(), MAP_PRIVATE, mmap(), O_RDONLY, open(), mmap_params::prot, PROT_READ, mmap_params::size, and fstat::size.
Referenced by CursorManager::CursorManager(), DockView::new_fast_launch_entity(), WindowFrame::reload_icon(), ResourceManager::ResourceManager(), and DockView::set_icon().
load_from_mem()
PixelBitmap LG::PNG::PNGLoader::load_from_mem (const uint8_t * ptr)
Definition at line 263 of file PNGLoader.cpp.
 {
     auto bitmap = PixelBitmap();
     if (!ptr) {
         Dbg() << "PNGLoader: nullptr\n";
         return bitmap;
     }
     if (!check_header(ptr)) {
         Dbg() << "PNGLoader: not png\n";
         return bitmap;
     }
     streamer().set(ptr + png_header_size);
     proccess_stream(bitmap);
     return bitmap;
 }
References bitmap, check_header(), LG::PNG::png_header_size, proccess_stream(), LG::PNG::DataStreamer::set(), and streamer().
Referenced by load_from_file().
paeth_predictor()
uint8_t LG::PNG::PNGLoader::paeth_predictor (int a, int b, int c) private
Definition at line 130 of file PNGLoader.cpp.
 {
     int p = a + b - c;
     int pa = abs(p - a);
     int pb = abs(p - b);
     int pc = abs(p - c);
     if (pa <= pb && pa <= pc)
         return a;
     if (pb <= pc)
         return b;
     return c;
 }
References abs(), and p.
Referenced by unfilter_scanlines().
proccess_stream()
void LG::PNG::PNGLoader::proccess_stream (PixelBitmap & bitmap) private
Definition at line 257 of file PNGLoader.cpp.
 {
     int len = 0;
     while (read_chunk(bitmap)) { }
 }
References read_chunk().
Referenced by load_from_mem().
read_chunk()
bool LG::PNG::PNGLoader::read_chunk (PixelBitmap & bitmap) private
Definition at line 228 of file PNGLoader.cpp.
 {
     ChunkHeader header;
     streamer().read(header.len);
     streamer().read(header.type, 4);
     if (memcmp(header.type, (uint8_t*)"IHDR", 4) == 0) {
         read_IHDR(header, bitmap);
     } else if (memcmp(header.type, (uint8_t*)"tEXt", 4) == 0) {
         read_TEXT(header, bitmap);
     } else if (memcmp(header.type, (uint8_t*)"zTXt", 4) == 0) {
         read_TEXT(header, bitmap);
     } else if (memcmp(header.type, (uint8_t*)"pHYs", 4) == 0) {
         read_PHYS(header, bitmap);
     } else if (memcmp(header.type, (uint8_t*)"IDAT", 4) == 0) {
         read_IDAT(header, bitmap);
     } else if (memcmp(header.type, (uint8_t*)"IEND", 4) == 0) {
         return false;
     } else {
         Dbg() << "PNGLoader: Unexpected header type: " << (char*)header.type << "\n";
         return false;
     }
     int crc;
     streamer().read(crc);
     return true;
 }
References fat16_formatter::header(), memcmp(), LG::PNG::DataStreamer::read(), read_IDAT(), read_IHDR(), read_PHYS(), read_TEXT(), and streamer().
Referenced by proccess_stream().
read_IDAT()
void LG::PNG::PNGLoader::read_IDAT (ChunkHeader & header, PixelBitmap & bitmap) private
Definition at line 79 of file PNGLoader.cpp.
 {
     size_t destlen = 0;
     int ret = puff(0, &destlen, streamer().ptr() + 2, &header.len);
     uint8_t* unzipped_data = (uint8_t*)malloc(destlen);
     puff(unzipped_data, &destlen, streamer().ptr() + 2, &header.len);
     DataStreamer local_streamer(unzipped_data);
     m_scanline_keeper.init(unzipped_data);
     if (m_ihdr_chunk.color_type == 2) {
         m_scanline_keeper.set_color_length(3);
         if (m_ihdr_chunk.depth == 8) {
             for (int i = 0; i < m_ihdr_chunk.height; i++) {
                 uint8_t scanline_filter;
                 local_streamer.read(scanline_filter);
                 if (scanline_filter > 4) {
                     Dbg() << "Invalid PNG filter: " << scanline_filter;
                     continue;
                 }
                 size_t len_of_scanline = (m_scanline_keeper.color_length() * m_ihdr_chunk.width * m_ihdr_chunk.depth + 7) / 8;
                 m_scanline_keeper.add(Scanline(scanline_filter, local_streamer.ptr()));
                 local_streamer.skip(len_of_scanline);
             }
         }
     } else if (m_ihdr_chunk.color_type == 6) {
         m_scanline_keeper.set_color_length(4);
         if (m_ihdr_chunk.depth == 8) {
             for (int i = 0; i < m_ihdr_chunk.height; i++) {
                 uint8_t scanline_filter;
                 local_streamer.read(scanline_filter);
                 if (scanline_filter > 4) {
                     Dbg() << "Invalid PNG filter: " << scanline_filter;
                     continue;
                 }
                 size_t len_of_scanline = (m_scanline_keeper.color_length() * m_ihdr_chunk.width * m_ihdr_chunk.depth + 7) / 8;
                 m_scanline_keeper.add(Scanline(scanline_filter, local_streamer.ptr()));
                 local_streamer.skip(len_of_scanline);
             }
         }
     }
     unfilter_scanlines();
     copy_scanlines_to_bitmap(bitmap);
     m_scanline_keeper.invalidate();
     streamer().skip(header.len + 6);
 }
References LG::PNG::ScanlineKeeper::add(), LG::PNG::ScanlineKeeper::color_length(), LG::PNG::IHDRChunk::color_type, copy_scanlines_to_bitmap(), LG::PNG::IHDRChunk::depth, fat16_formatter::header(), LG::PNG::IHDRChunk::height, LG::PNG::ScanlineKeeper::init(), LG::PNG::ScanlineKeeper::invalidate(), m_ihdr_chunk, m_scanline_keeper, malloc(), LG::PNG::DataStreamer::ptr(), puff(), LG::PNG::DataStreamer::read(), LG::PNG::ScanlineKeeper::set_color_length(), LG::PNG::DataStreamer::skip(), streamer(), unfilter_scanlines(), and LG::PNG::IHDRChunk::width.
Referenced by read_chunk().
read_IHDR()
void LG::PNG::PNGLoader::read_IHDR (ChunkHeader & header, PixelBitmap & bitmap) private
Definition at line 51 of file PNGLoader.cpp.
 {
     streamer().read(m_ihdr_chunk.width);
     streamer().read(m_ihdr_chunk.height);
     streamer().read(m_ihdr_chunk.depth);
     streamer().read(m_ihdr_chunk.color_type);
     streamer().read(m_ihdr_chunk.compression_method);
     streamer().read(m_ihdr_chunk.filter_method);
     streamer().read(m_ihdr_chunk.interlace_method);
     bitmap.resize(m_ihdr_chunk.width, m_ihdr_chunk.height);
 #ifdef PNGLOADER_DEGUG
     Dbg() << "IHDR: " << m_ihdr_chunk.width << " " << m_ihdr_chunk.depth << " " << m_ihdr_chunk.compression_method << " " << m_ihdr_chunk.filter_method << " " << m_ihdr_chunk.color_type << "\n";
 #endif
 }
References LG::PNG::IHDRChunk::color_type, LG::PNG::IHDRChunk::compression_method, LG::PNG::IHDRChunk::depth, LG::PNG::IHDRChunk::filter_method, LG::PNG::IHDRChunk::height, LG::PNG::IHDRChunk::interlace_method, m_ihdr_chunk, LG::PNG::DataStreamer::read(), streamer(), and LG::PNG::IHDRChunk::width.
Referenced by read_chunk().
read_PHYS()
void LG::PNG::PNGLoader::read_PHYS (ChunkHeader & header, PixelBitmap & bitmap) private
Definition at line 73 of file PNGLoader.cpp.
 {
     streamer().skip(header.len);
 }
References fat16_formatter::header(), LG::PNG::DataStreamer::skip(), and streamer().
Referenced by read_chunk().
read_TEXT()
void LG::PNG::PNGLoader::read_TEXT (ChunkHeader & header, PixelBitmap & bitmap) private
Definition at line 68 of file PNGLoader.cpp.
 {
     streamer().skip(header.len);
 }
References fat16_formatter::header(), LG::PNG::DataStreamer::skip(), and streamer().
Referenced by read_chunk().
streamer()
DataStreamer& LG::PNG::PNGLoader::streamer () inline
Definition at line 135 of file PNGLoader.h.
 { return m_streamer; }
References m_streamer.
Referenced by load_from_mem(), read_chunk(), read_IDAT(), read_IHDR(), read_PHYS(), and read_TEXT().
unfilter_scanlines()
void LG::PNG::PNGLoader::unfilter_scanlines () private
Definition at line 143 of file PNGLoader.cpp.
 {
     for (int i = 0; i < m_ihdr_chunk.height; i++) {
         if (m_scanline_keeper.scanlines()[i].filter_type() == 1) { // Sub
             int width = m_ihdr_chunk.width * m_scanline_keeper.color_length();
             for (int j = 0; j < width; j++) {
                 int prev = 0;
                 if (j >= m_scanline_keeper.color_length()) {
                     prev = m_scanline_keeper.scanlines()[i].data()[j - m_scanline_keeper.color_length()];
                 }
                 m_scanline_keeper.scanlines()[i].data()[j] += prev;
             }
         } else if (m_scanline_keeper.scanlines()[i].filter_type() == 2) { // Up
             int width = m_ihdr_chunk.width * m_scanline_keeper.color_length();
             for (int j = 0; j < width; j++) {
                 int prev = 0;
                 if (i > 0) {
                     prev = m_scanline_keeper.scanlines()[i - 1].data()[j];
                 }
                 m_scanline_keeper.scanlines()[i].data()[j] += prev;
             }
         } else if (m_scanline_keeper.scanlines()[i].filter_type() == 3) { // Average
             int width = m_ihdr_chunk.width * m_scanline_keeper.color_length();
             for (int j = 0; j < width; j++) {
                 int prev = 0;
                 int prior = 0;
                 if (i > 0) {
                     prior = m_scanline_keeper.scanlines()[i - 1].data()[j];
                 }
                 if (j >= m_scanline_keeper.color_length()) {
                     prev = m_scanline_keeper.scanlines()[i].data()[j - m_scanline_keeper.color_length()];
                 }
                 m_scanline_keeper.scanlines()[i].data()[j] += (prev + prior) / 2;
             }
         } else if (m_scanline_keeper.scanlines()[i].filter_type() == 4) { // Paeth
             int width = m_ihdr_chunk.width * m_scanline_keeper.color_length();
             for (int j = 0; j < width; j++) {
                 int a = 0;
                 int b = 0;
                 int c = 0;
                 if (i > 0) {
                     b = m_scanline_keeper.scanlines()[i - 1].data()[j];
                 }
                 if (j >= m_scanline_keeper.color_length()) {
                     a = m_scanline_keeper.scanlines()[i].data()[j - m_scanline_keeper.color_length()];
                     if (i > 0) {
                         c = m_scanline_keeper.scanlines()[i - 1].data()[j - m_scanline_keeper.color_length()];
                     }
                 }
                 m_scanline_keeper.scanlines()[i].data()[j] += paeth_predictor(a, b, c);
             }
         }
     }
 }
References LG::PNG::ScanlineKeeper::color_length(), LG::PNG::IHDRChunk::height, m_ihdr_chunk, m_scanline_keeper, paeth_predictor(), LG::PNG::ScanlineKeeper::scanlines(), and LG::PNG::IHDRChunk::width.
Referenced by read_IDAT().
Field Documentation
m_ihdr_chunk
IHDRChunk LG::PNG::PNGLoader::m_ihdr_chunk private
Definition at line 152 of file PNGLoader.h.
Referenced by copy_scanlines_to_bitmap(), read_IDAT(), read_IHDR(), and unfilter_scanlines().
m_scanline_keeper
ScanlineKeeper LG::PNG::PNGLoader::m_scanline_keeper private
Definition at line 153 of file PNGLoader.h.
Referenced by copy_scanlines_to_bitmap(), read_IDAT(), and unfilter_scanlines().
m_streamer
DataStreamer LG::PNG::PNGLoader::m_streamer private
Definition at line 151 of file PNGLoader.h.
Referenced by streamer().
The documentation for this class was generated from the following files:
libs/libg/ImageLoaders/PNGLoader.h
libs/libg/ImageLoaders/PNGLoader.cpp