oneOS: UI::View Class Reference
UI::View Class Reference
#include <View.h>
Public Member Functions
View (const LG::Rect &)
View (const LG::Rect &, const LG::Color &)
template<class T , class... Args>
T & add_subview (Args &&... args)
void remove_from_superview ()
template<typename Callback >
void foreach_subview (Callback callback) const
View * subview_at (const LG::Point< int > &point) const
View * hit_test (const LG::Point< int > &point)
const LG::Rect & frame () const
const LG::Rect & bounds () const
void set_width (size_t x)
void set_height (size_t x)
LG::Rect frame_in_window ()
Window * window ()
bool has_superview ()
View * superview ()
Vector< View * > & subviews ()
const Vector< View * > & subviews () const
void set_needs_display (const LG::Rect &)
void set_needs_display ()
bool is_hovered () const
void set_focusable (bool val)
bool is_focusable () const
virtual void display (const LG::Rect &rect)
virtual void did_display (const LG::Rect &rect)
virtual void hover_begin (const LG::Point< int > &location)
virtual void hover_end ()
virtual void click_began (const LG::Point< int > &location)
virtual void click_ended ()
virtual void receive_mouse_move_event (MouseEvent &) override
virtual void receive_mouse_action_event (MouseActionEvent &) override
virtual void receive_mouse_leave_event (MouseLeaveEvent &) override
virtual void receive_keyup_event (KeyUpEvent &) override
virtual void receive_keydown_event (KeyDownEvent &) override
virtual void receive_display_event (DisplayEvent &) override
LG::Color & background_color ()
const LG::Color & background_color () const
virtual void set_background_color (const LG::Color &background_color)
Public Member Functions inherited from UI::Responder
bool send_invalidate_message_to_server (const LG::Rect &rect) const
void send_display_message_to_self (Window &win, const LG::Rect &display_rect)
void receive_event (UniquePtr< LFoundation::Event > event) override
Public Member Functions inherited from LFoundation::EventReceiver
EventReceiver ()
~EventReceiver ()
Private Member Functions
void set_window (Window *window)
void set_superview (View *superview)
Private Attributes
View * m_superview { nullptr }
Window * m_window { nullptr }
Vector< View * > m_subviews
LG::Rect m_frame
LG::Rect m_bounds
bool m_active { false }
bool m_hovered { false }
bool m_focusable { false }
LG::Color m_background_color { LG::Color::White }
Friends
class Window
Additional Inherited Members
Protected Member Functions inherited from UI::Responder
Responder ()
Protected Attributes inherited from UI::Responder
bool m_display_message_sent { false }
LG::Rect m_prev_display_message {}
Detailed Description
Definition at line 21 of file View.h.
Constructor & Destructor Documentation
View() [1/2]
UI::View::View (const LG::Rect & frame)
Definition at line 17 of file View.cpp.
     : m_frame(frame)
     , m_bounds(0, 0, frame.width(), frame.height())
 {
 }
View() [2/2]
UI::View::View (const LG::Rect & frame, const LG::Color & bc)
Definition at line 23 of file View.cpp.
     : m_frame(frame)
     , m_bounds(0, 0, frame.width(), frame.height())
     , m_background_color(bc)
 {
 }
Member Function Documentation
add_subview()
template<class T , class... Args> T& UI::View::add_subview (Args &&... args) inline
Definition at line 29 of file View.h.
     {
         T* subview = new T(args...);
         subview->set_window(window());
         subview->set_superview(this);
         m_subviews.push_back(subview);
         return *subview;
     }
References __main__::args, m_subviews, and window().
background_color() [1/2]
LG::Color& UI::View::background_color () inline
Definition at line 99 of file View.h.
 { return m_background_color; }
References m_background_color.
Referenced by display(), UI::Button::display(), DockView::display(), and set_background_color().
background_color() [2/2]
const LG::Color& UI::View::background_color () const inline
Definition at line 100 of file View.h.
 { return m_background_color; }
References m_background_color.
bounds()
const LG::Rect& UI::View::bounds () const inline
Definition at line 63 of file View.h.
 { return m_bounds; }
References m_bounds.
Referenced by UI::Button::display(), UI::Label::display(), DockView::display(), TerminalView::display(), receive_display_event(), and set_needs_display().
click_began()
void UI::View::click_began (const LG::Point< int > & location) virtual
Reimplemented in DockView.
Definition at line 100 of file View.cpp.
 {
     m_active = true;
     set_needs_display();
 }
References m_active, and set_needs_display().
Referenced by receive_mouse_action_event().
click_ended()
void UI::View::click_ended () virtual
Definition at line 106 of file View.cpp.
 {
     m_active = true;
     set_needs_display();
 }
References m_active, and set_needs_display().
Referenced by receive_mouse_action_event().
did_display()
void UI::View::did_display (const LG::Rect & rect) virtual
Definition at line 88 of file View.cpp.
 {
 }
Referenced by receive_display_event().
display()
void UI::View::display (const LG::Rect & rect) virtual
Draws the receivers image within the passed-in rectangle.
Parameters
rect The portion of the views bounds that needs to be updated. The first time your view is drawn, this rectangle is typically the entire visible bounds of your view. However, during subsequent drawing operations, the rectangle may specify only part of your view.
Reimplemented in TerminalView, DockView, UI::Label, and UI::Button.
Definition at line 81 of file View.cpp.
 {
     Context ctx(*this);
     ctx.set_fill_color(background_color());
     ctx.fill(rect);
 }
References background_color(), LG::Context::fill(), and LG::Context::set_fill_color().
Referenced by receive_display_event().
foreach_subview()
template<typename Callback > void UI::View::foreach_subview (Callback callback) const inline
Definition at line 41 of file View.h.
     {
         for (int i = 0; i < m_subviews.size(); i++) {
             if (!callback(*m_subviews[i])) {
                 return;
             }
         }
     }
References m_subviews.
Referenced by receive_display_event(), receive_mouse_leave_event(), and receive_mouse_move_event().
frame()
const LG::Rect& UI::View::frame () const inline
Definition at line 62 of file View.h.
 { return m_frame; }
References m_frame.
Referenced by frame_in_window(), TerminalView::recalc_dimensions(), receive_display_event(), receive_mouse_move_event(), set_needs_display(), subview_at(), and TerminalView::TerminalView().
frame_in_window()
LG::Rect UI::View::frame_in_window ()
Definition at line 48 of file View.cpp.
 {
     View* view = this;
     auto rect = frame();
     while (view->has_superview()) {
         view = view->superview();
         rect.offset_by(view->frame().origin());
     }
     return rect;
 }
References frame(), has_superview(), LG::Rect::origin(), and superview().
Referenced by UI::Context::Context().
has_superview()
bool UI::View::has_superview () inline
Definition at line 70 of file View.h.
 { return m_superview; }
References m_superview.
Referenced by frame_in_window(), receive_display_event(), and set_needs_display().
hit_test()
View * UI::View::hit_test (const LG::Point< int > & point)
Returns the farthest descendant of the receiver in the view hierarchy (including itself) that contains a specified point.
Parameters
point A point specified in the receivers local coordinate system (bounds).
Returns
The view object that is the farthest descendent of the current view and contains point. Returns nil if the point lies completely outside the receivers view hierarchy.
Definition at line 40 of file View.cpp.
 {
     if (auto* subview = subview_at(point)) {
         return subview->hit_test(point - subview->frame().origin());
     }
     return this;
 }
References hit_test(), and subview_at().
Referenced by hit_test(), and UI::Window::receive_event().
hover_begin()
void UI::View::hover_begin (const LG::Point< int > & location) virtual
Reimplemented in UI::Label, and UI::Button.
Definition at line 92 of file View.cpp.
 {
 }
Referenced by receive_mouse_move_event().
hover_end()
void UI::View::hover_end () virtual
Reimplemented in UI::Label, and UI::Button.
Definition at line 96 of file View.cpp.
 {
 }
Referenced by receive_mouse_leave_event().
is_focusable()
bool UI::View::is_focusable () const inline
Definition at line 81 of file View.h.
 { return m_focusable; }
References m_focusable.
is_hovered()
bool UI::View::is_hovered () const inline
Definition at line 78 of file View.h.
 { return m_hovered; }
References m_hovered.
Referenced by receive_mouse_leave_event(), and receive_mouse_move_event().
receive_display_event()
void UI::View::receive_display_event (DisplayEvent & event) override virtual
Reimplemented from UI::Responder.
Definition at line 179 of file View.cpp.
 {
     event.bounds().intersect(bounds());
     display(event.bounds());
     foreach_subview([&](View& subview) -> bool {
         auto bounds = event.bounds();
         if (bounds.intersects(subview.frame())) {
             bounds.offset_by(-subview.frame().origin());
             DisplayEvent own_event(bounds);
             subview.receive_display_event(own_event);
         }
         return true;
     });
     did_display(event.bounds());
     if (!has_superview()) {
         bool success = send_invalidate_message_to_server(event.bounds());
     }
     Responder::receive_display_event(event);
 }
References UI::DisplayEvent::bounds(), bounds(), did_display(), display(), foreach_subview(), frame(), has_superview(), LG::Rect::intersects(), UI::Responder::receive_display_event(), and UI::Responder::send_invalidate_message_to_server().
Referenced by UI::Window::receive_event().
receive_keydown_event()
void UI::View::receive_keydown_event (KeyDownEvent &) override virtual
Reimplemented from UI::Responder.
Reimplemented in TerminalView.
Definition at line 175 of file View.cpp.
 {
 }
Referenced by UI::Window::receive_event().
receive_keyup_event()
void UI::View::receive_keyup_event (KeyUpEvent &) override virtual
Reimplemented from UI::Responder.
Reimplemented in TerminalView.
Definition at line 171 of file View.cpp.
 {
 }
Referenced by UI::Window::receive_event().
receive_mouse_action_event()
void UI::View::receive_mouse_action_event (MouseActionEvent & event) override virtual
Reimplemented from UI::Responder.
Definition at line 137 of file View.cpp.
 {
     if (event.type() == MouseActionType::ClickBegan) {
         click_began(LG::Point<int>(event.x(), event.y()));
     } else if (event.type() == MouseActionType::ClickEnded) {
         click_ended();
     }
     Responder::receive_mouse_action_event(event);
 }
References click_began(), click_ended(), UI::ClickBegan, UI::ClickEnded, UI::Responder::receive_mouse_action_event(), UI::MouseActionEvent::type(), UI::MouseActionEvent::x(), and UI::MouseActionEvent::y().
Referenced by UI::Window::receive_event().
receive_mouse_leave_event()
void UI::View::receive_mouse_leave_event (MouseLeaveEvent & event) override virtual
Reimplemented from UI::Responder.
Definition at line 148 of file View.cpp.
 {
     if (!is_hovered()) {
         return;
     }
     foreach_subview([&](View& subview) -> bool {
         if (subview.is_hovered()) {
             LG::Point<int> point(event.x(), event.y());
             point.offset_by(-subview.frame().origin());
             MouseLeaveEvent mle(point.x(), point.y());
             subview.receive_mouse_leave_event(mle);
         }
         return true;
     });
     m_hovered = false;
     m_active = false;
     hover_end();
     Responder::receive_mouse_leave_event(event);
 }
References foreach_subview(), hover_end(), is_hovered(), m_active, m_hovered, and UI::Responder::receive_mouse_leave_event().
Referenced by UI::Window::receive_event().
receive_mouse_move_event()
void UI::View::receive_mouse_move_event (MouseEvent & event) override virtual
Reimplemented from UI::Responder.
Definition at line 112 of file View.cpp.
 {
     if (!is_hovered()) {
         m_hovered = true;
         hover_begin(LG::Point<int>(event.x(), event.y()));
     }
     foreach_subview([&](View& subview) -> bool {
         if (subview.is_hovered() && !subview.frame().contains(event.x(), event.y())) {
             LG::Point<int> point(event.x(), event.y());
             point.offset_by(-subview.frame().origin());
             MouseLeaveEvent mle(point.x(), point.y());
             subview.receive_mouse_leave_event(mle);
         } else if (!subview.is_hovered() && subview.frame().contains(event.x(), event.y())) {
             LG::Point<int> point(event.x(), event.y());
             point.offset_by(-subview.frame().origin());
             MouseEvent me(point.x(), point.y());
             subview.receive_mouse_move_event(me);
         }
         return true;
     });
     Responder::receive_mouse_move_event(event);
 }
References LG::Rect::contains(), foreach_subview(), frame(), hover_begin(), is_hovered(), m_hovered, UI::Responder::receive_mouse_move_event(), UI::MouseEvent::x(), and UI::MouseEvent::y().
Referenced by UI::Window::receive_event().
remove_from_superview()
void UI::View::remove_from_superview ()
Definition at line 30 of file View.cpp.
 {
 }
set_background_color()
virtual void UI::View::set_background_color (const LG::Color & background_color) inline virtual
Definition at line 101 of file View.h.
     {
         m_background_color = background_color;
         set_needs_display();
     }
References background_color(), m_background_color, and set_needs_display().
Referenced by UI::Button::hover_begin(), UI::Button::hover_end(), and main().
set_focusable()
void UI::View::set_focusable (bool val) inline
Definition at line 80 of file View.h.
 { m_focusable = val; }
References m_focusable.
set_height()
void UI::View::set_height (size_t x) inline
Definition at line 65 of file View.h.
 { m_frame.set_height(x), m_bounds.set_height(x), set_needs_display(); }
References m_bounds, m_frame, LG::Rect::set_height(), and set_needs_display().
Referenced by UI::Button::recalc_bounds(), and UI::Label::recalc_bounds().
set_needs_display() [1/2]
void UI::View::set_needs_display () inline
Definition at line 76 of file View.h.
 { set_needs_display(bounds()); }
References bounds(), and set_needs_display().
Referenced by click_began(), click_ended(), TerminalView::did_move_cursor(), DockView::new_fast_launch_entity(), TerminalView::put_char(), DockView::remove_entity(), TerminalView::scroll_line(), set_background_color(), set_height(), DockView::set_icon(), set_needs_display(), UI::Button::set_title(), set_width(), and TerminalView::will_move_cursor().
set_needs_display() [2/2]
void UI::View::set_needs_display (const LG::Rect & rect)
Marks the receivers bounds rectangle as needing to be redrawn.
Parameters
rect A rect specified in the receivers local coordinate system.
Definition at line 64 of file View.cpp.
 {
     auto display_rect = rect;
     display_rect.intersect(bounds());
     if (has_superview()) {
         display_rect.offset_by(frame().origin());
         superview()->set_needs_display(display_rect);
     } else {
         send_display_message_to_self(*window(), display_rect);
     }
 }
References bounds(), frame(), has_superview(), LG::Rect::intersect(), UI::Responder::send_display_message_to_self(), set_needs_display(), superview(), and window().
Referenced by UI::Window::create_superview(), and set_needs_display().
set_superview()
void UI::View::set_superview (View * superview) inline private
Definition at line 109 of file View.h.
 { m_superview = superview; }
References m_superview, and superview().
set_width()
void UI::View::set_width (size_t x) inline
Definition at line 64 of file View.h.
 { m_frame.set_width(x), m_bounds.set_width(x), set_needs_display(); }
References m_bounds, m_frame, set_needs_display(), and LG::Rect::set_width().
Referenced by UI::Button::recalc_bounds(), and UI::Label::recalc_bounds().
set_window()
void UI::View::set_window (Window * window) inline private
Definition at line 108 of file View.h.
 { m_window = window; }
References m_window, and window().
subview_at()
View* UI::View::subview_at (const LG::Point< int > & point) const inline
Definition at line 50 of file View.h.
     {
         for (int i = subviews().size() - 1; i >= 0; --i) {
             if (subviews()[i]->frame().contains(point)) {
                 return subviews()[i];
             }
         }
         return nullptr;
     }
References frame(), and subviews().
Referenced by hit_test().
subviews() [1/2]
Vector<View*>& UI::View::subviews () inline
Definition at line 72 of file View.h.
 { return m_subviews; }
References m_subviews.
Referenced by subview_at().
subviews() [2/2]
const Vector<View*>& UI::View::subviews () const inline
Definition at line 73 of file View.h.
 { return m_subviews; }
References m_subviews.
superview()
View* UI::View::superview () inline
Definition at line 71 of file View.h.
 { return m_superview; }
References m_superview.
Referenced by frame_in_window(), set_needs_display(), and set_superview().
window()
Window* UI::View::window () inline
Definition at line 69 of file View.h.
 { return m_window; }
References m_window.
Referenced by add_subview(), DockView::click_began(), DockView::new_entity(), set_needs_display(), and set_window().
Friends And Related Function Documentation
Window
friend class Window friend
Definition at line 23 of file View.h.
Field Documentation
m_active
bool UI::View::m_active { false } private
Definition at line 117 of file View.h.
Referenced by click_began(), click_ended(), and receive_mouse_leave_event().
m_background_color
LG::Color UI::View::m_background_color { LG::Color::White } private
Definition at line 121 of file View.h.
Referenced by background_color(), and set_background_color().
m_bounds
LG::Rect UI::View::m_bounds private
Definition at line 115 of file View.h.
Referenced by bounds(), set_height(), and set_width().
m_focusable
bool UI::View::m_focusable { false } private
Definition at line 119 of file View.h.
Referenced by is_focusable(), and set_focusable().
m_frame
LG::Rect UI::View::m_frame private
Definition at line 114 of file View.h.
Referenced by frame(), set_height(), and set_width().
m_hovered
bool UI::View::m_hovered { false } private
Definition at line 118 of file View.h.
Referenced by is_hovered(), receive_mouse_leave_event(), and receive_mouse_move_event().
m_subviews
Vector<View*> UI::View::m_subviews private
Definition at line 113 of file View.h.
Referenced by add_subview(), foreach_subview(), and subviews().
m_superview
View* UI::View::m_superview { nullptr } private
Definition at line 111 of file View.h.
Referenced by has_superview(), set_superview(), and superview().
m_window
Window* UI::View::m_window { nullptr } private
Definition at line 112 of file View.h.
Referenced by set_window(), and window().
The documentation for this class was generated from the following files:
libs/libui/View.h
libs/libui/View.cpp