oneOS: DisconnectMessage Class Reference
DisconnectMessage Class Reference
#include <WSConnection.h>
Public Member Functions
DisconnectMessage (message_key_t key, int reason)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
int reason () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
int m_reason
Detailed Description
Definition at line 646 of file WSConnection.h.
Constructor & Destructor Documentation
DisconnectMessage()
DisconnectMessage::DisconnectMessage (message_key_t key, int reason) inline
Definition at line 648 of file WSConnection.h.
         : m_key(key)
         , m_reason(reason)
     {
     }
Member Function Documentation
decoder_magic()
int DisconnectMessage::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 656 of file WSConnection.h.
 { return 737; }
Referenced by encode().
encode()
EncodedMessage DisconnectMessage::encode () const inline override virtual
Reimplemented from Message.
Definition at line 658 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_reason);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), and m_reason.
id()
int DisconnectMessage::id () const inline override virtual
Reimplemented from Message.
Definition at line 653 of file WSConnection.h.
 { return 7; }
key()
int DisconnectMessage::key () const inline override virtual
Reimplemented from Message.
Definition at line 655 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode().
reason()
int DisconnectMessage::reason () const inline
Definition at line 657 of file WSConnection.h.
 { return m_reason; }
References m_reason.
reply_id()
int DisconnectMessage::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 654 of file WSConnection.h.
 { return -1; }
Field Documentation
m_key
message_key_t DisconnectMessage::m_key private
Definition at line 668 of file WSConnection.h.
Referenced by key().
m_reason
int DisconnectMessage::m_reason private
Definition at line 669 of file WSConnection.h.
Referenced by encode(), and reason().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h