oneOS: UI::Responder Class Reference
UI::Responder Class Reference
#include <Responder.h>
Public Member Functions
bool send_invalidate_message_to_server (const LG::Rect &rect) const
void send_display_message_to_self (Window &win, const LG::Rect &display_rect)
void receive_event (UniquePtr< LFoundation::Event > event) override
virtual void receive_mouse_move_event (MouseEvent &)
virtual void receive_mouse_action_event (MouseActionEvent &)
virtual void receive_mouse_leave_event (MouseLeaveEvent &)
virtual void receive_keyup_event (KeyUpEvent &)
virtual void receive_keydown_event (KeyDownEvent &)
virtual void receive_display_event (DisplayEvent &)
Public Member Functions inherited from LFoundation::EventReceiver
EventReceiver ()
~EventReceiver ()
Protected Member Functions
Responder ()
Protected Attributes
bool m_display_message_sent { false }
LG::Rect m_prev_display_message {}
Detailed Description
Definition at line 18 of file Responder.h.
Constructor & Destructor Documentation
Responder()
UI::Responder::Responder () inline protected
Definition at line 34 of file Responder.h.
 { }
Member Function Documentation
receive_display_event()
virtual void UI::Responder::receive_display_event (DisplayEvent &) inline virtual
Reimplemented in UI::View.
Definition at line 29 of file Responder.h.
 { m_display_message_sent = false; }
References m_display_message_sent.
Referenced by UI::View::receive_display_event(), and receive_event().
receive_event()
void UI::Responder::receive_event (UniquePtr< LFoundation::Event > event) override virtual
Reimplemented from LFoundation::EventReceiver.
Definition at line 33 of file Responder.cpp.
 {
     if (event->type() == Event::Type::MouseEvent) {
         MouseEvent& own_event = *(MouseEvent*)event.get();
         receive_mouse_move_event(own_event);
     }
     if (event->type() == Event::Type::DisplayEvent) {
         DisplayEvent& own_event = *(DisplayEvent*)event.get();
         receive_display_event(own_event);
     }
 }
References UniquePtr< T >::get(), receive_display_event(), receive_mouse_move_event(), and LFoundation::Event::type().
receive_keydown_event()
virtual void UI::Responder::receive_keydown_event (KeyDownEvent &) inline virtual
Reimplemented in TerminalView, and UI::View.
Definition at line 28 of file Responder.h.
 { }
receive_keyup_event()
virtual void UI::Responder::receive_keyup_event (KeyUpEvent &) inline virtual
Reimplemented in TerminalView, and UI::View.
Definition at line 27 of file Responder.h.
 { }
receive_mouse_action_event()
virtual void UI::Responder::receive_mouse_action_event (MouseActionEvent &) inline virtual
Reimplemented in UI::View.
Definition at line 25 of file Responder.h.
 { }
Referenced by UI::View::receive_mouse_action_event().
receive_mouse_leave_event()
virtual void UI::Responder::receive_mouse_leave_event (MouseLeaveEvent &) inline virtual
Reimplemented in UI::View.
Definition at line 26 of file Responder.h.
 { }
Referenced by UI::View::receive_mouse_leave_event().
receive_mouse_move_event()
virtual void UI::Responder::receive_mouse_move_event (MouseEvent &) inline virtual
Reimplemented in UI::View.
Definition at line 24 of file Responder.h.
 { }
Referenced by receive_event(), and UI::View::receive_mouse_move_event().
send_display_message_to_self()
void UI::Responder::send_display_message_to_self (Window & win, const LG::Rect & display_rect)
Definition at line 24 of file Responder.cpp.
 {
     if (!m_display_message_sent || m_prev_display_message != display_rect) {
         LFoundation::EventLoop::the().add(win, new DisplayEvent(display_rect));
         m_display_message_sent = true;
         m_prev_display_message = display_rect;
     }
 }
References LFoundation::EventLoop::add(), m_display_message_sent, m_prev_display_message, and LFoundation::EventLoop::the().
Referenced by UI::View::set_needs_display().
send_invalidate_message_to_server()
bool UI::Responder::send_invalidate_message_to_server (const LG::Rect & rect) const
Definition at line 17 of file Responder.cpp.
 {
     auto& app = App::the();
     InvalidateMessage msg(Connection::the().key(), app.window().id(), rect);
     return app.connection().send_async_message(msg);
 }
References UI::App::the(), and UI::Connection::the().
Referenced by UI::View::receive_display_event().
Field Documentation
m_display_message_sent
bool UI::Responder::m_display_message_sent { false } protected
Definition at line 32 of file Responder.h.
Referenced by receive_display_event(), and send_display_message_to_self().
m_prev_display_message
LG::Rect UI::Responder::m_prev_display_message {} protected
Definition at line 33 of file Responder.h.
Referenced by send_display_message_to_self().
The documentation for this class was generated from the following files:
libs/libui/Responder.h
libs/libui/Responder.cpp