oneOS: LG::String Class Reference
LG::String Class Reference
#include <String.h>
Public Member Functions
void encode (EncodedMessage &buf) const override
void decode (const char *buf, size_t &offset) override
Public Member Functions inherited from Algo::String
String ()=default
String (const char *str)
String (const String &s)
String (String &&s)
~String ()
String & operator= (const String &s)
String & operator= (String &&s)
String & operator+= (const String &s)
String operator+ (const String &s) const
String operator+ (const char *s) const
void push_back (char c)
void pop_back ()
const char & at (size_t i) const
char & at (size_t i)
void clear ()
size_t size () const
const char & operator[] (size_t i) const
char & operator[] (size_t i)
const char & back () const
char & back ()
const char * c_str () const
const char * data () const
Detailed Description
Definition at line 21 of file String.h.
Member Function Documentation
decode()
void LG::String::decode (const char * buf, size_t & offset) inline override virtual
Reimplemented from Decodable< String >.
Definition at line 33 of file String.h.
     {
         while (buf[offset] != '\0') {
             push_back(buf[offset]);
             offset++;
         }
         offset++;
     }
References buf, and Algo::String::push_back().
encode()
void LG::String::encode (EncodedMessage & buf) const inline override virtual
Reimplemented from Encodable< String >.
Definition at line 25 of file String.h.
     {
         for (int i = 0; i < size(); i++) {
             buf.push_back(at(i));
         }
         buf.push_back('\0');
     }
References Algo::String::at(), buf, and Algo::String::size().
The documentation for this class was generated from the following file:
libs/libg/String.h