oneOS: ClientConnection< ServerDecoder, ClientDecoder > Class Template Reference
ClientConnection< ServerDecoder, ClientDecoder > Class Template Reference
#include <ClientConnection.h>
Public Member Functions
ClientConnection (int sock_fd, ServerDecoder &server_decoder, ClientDecoder &client_decoder)
void set_accepted_key (int key)
bool send_message (const Message &msg) const
UniquePtr< Message > send_sync (const Message &msg)
UniquePtr< Message > wait_for_answer (const Message &msg)
void pump_messages ()
void receive_event (UniquePtr< LFoundation::Event > event) override
Public Member Functions inherited from LFoundation::EventReceiver
EventReceiver ()
~EventReceiver ()
Private Attributes
int m_accepted_key { -1 }
int m_connection_fd
Vector< UniquePtr< Message > > m_messages
ServerDecoder & m_server_decoder
ClientDecoder & m_client_decoder
Detailed Description
template<typename ServerDecoder, typename ClientDecoder>
class ClientConnection< ServerDecoder, ClientDecoder >
Definition at line 12 of file ClientConnection.h.
Constructor & Destructor Documentation
ClientConnection()
template<typename ServerDecoder , typename ClientDecoder > ClientConnection< ServerDecoder, ClientDecoder >::ClientConnection (int sock_fd, ServerDecoder & server_decoder, ClientDecoder & client_decoder) inline
Definition at line 14 of file ClientConnection.h.
         : m_connection_fd(sock_fd)
         , m_server_decoder(server_decoder)
         , m_client_decoder(client_decoder)
         , m_messages()
     {
     }
Member Function Documentation
pump_messages()
template<typename ServerDecoder , typename ClientDecoder > void ClientConnection< ServerDecoder, ClientDecoder >::pump_messages () inline
Definition at line 49 of file ClientConnection.h.
     {
         Vector<char> buf;
         char tmpbuf[1024];
         int read_cnt;
         while (read_cnt = read(m_connection_fd, tmpbuf, sizeof(tmpbuf))) {
             if (read_cnt <= 0) {
                 Dbg() << getpid() << " :: ClientConnection read error\n";
                 return;
             }
             size_t buf_size = buf.size();
             buf.resize(buf_size + read_cnt);
             memcpy((uint8_t*)&buf.data()[buf_size], (uint8_t*)tmpbuf, read_cnt);
             if (read_cnt < sizeof(tmpbuf)) {
                 break;
             }
         }
         size_t msg_len = 0;
         size_t buf_size = buf.size();
         for (size_t i = 0; i < buf_size; i += msg_len) {
             msg_len = 0;
             if (auto response = m_client_decoder.decode((buf.data() + i), read_cnt - i, msg_len)) {
                 m_messages.push_back(move(response));
             } else if (auto response = m_server_decoder.decode((buf.data() + i), read_cnt - i, msg_len)) {
                 m_messages.push_back(move(response));
             } else {
                 Dbg() << getpid() << " :: ClientConnection read error\n";
                 ASSERT_NOT_REACHED();
             }
         }
         if (m_messages.size() > 0) {
             // Note: We send an event to ourselves and use CallEvent to recognize the
             // event as sign to start processing of messages.
             LFoundation::EventLoop::the().add(*this, new LFoundation::CallEvent(0));
         }
     }
References LFoundation::EventLoop::add(), ASSERT_NOT_REACHED, buf, getpid(), ClientConnection< ServerDecoder, ClientDecoder >::m_client_decoder, ClientConnection< ServerDecoder, ClientDecoder >::m_connection_fd, ClientConnection< ServerDecoder, ClientDecoder >::m_messages, ClientConnection< ServerDecoder, ClientDecoder >::m_server_decoder, memcpy(), move(), Algo::Vector< T >::push_back(), read(), Algo::Vector< T >::size(), and LFoundation::EventLoop::the().
Referenced by ClientConnection< ServerDecoder, ClientDecoder >::wait_for_answer().
receive_event()
template<typename ServerDecoder , typename ClientDecoder > void ClientConnection< ServerDecoder, ClientDecoder >::receive_event (UniquePtr< LFoundation::Event > event) inline override virtual
Reimplemented from LFoundation::EventReceiver.
Definition at line 90 of file ClientConnection.h.
     {
         if (event->type() == LFoundation::Event::Type::DeferredInvoke) {
             // Note: The event was sent from pump_messages() and callback of CallEvent is 0!
             // Do NOT call callback here!
             auto msg = move(m_messages);
             for (int i = 0; i < msg.size(); i++) {
                 if (msg[i] && msg[i]->decoder_magic() == m_client_decoder.magic() && msg[i]->key() == m_accepted_key) {
                     m_client_decoder.handle(*msg[i]);
                 }
             }
         }
     }
References ClientConnection< ServerDecoder, ClientDecoder >::m_accepted_key, ClientConnection< ServerDecoder, ClientDecoder >::m_client_decoder, ClientConnection< ServerDecoder, ClientDecoder >::m_messages, move(), and LFoundation::Event::type().
send_message()
template<typename ServerDecoder , typename ClientDecoder > bool ClientConnection< ServerDecoder, ClientDecoder >::send_message (const Message & msg) const inline
Definition at line 24 of file ClientConnection.h.
     {
         auto encoded_msg = msg.encode();
         int wrote = write(m_connection_fd, encoded_msg.data(), encoded_msg.size());
         return wrote == encoded_msg.size();
     }
References Message::encode(), ClientConnection< ServerDecoder, ClientDecoder >::m_connection_fd, and write().
Referenced by ClientConnection< ServerDecoder, ClientDecoder >::send_sync().
send_sync()
template<typename ServerDecoder , typename ClientDecoder > UniquePtr<Message> ClientConnection< ServerDecoder, ClientDecoder >::send_sync (const Message & msg) inline
Definition at line 31 of file ClientConnection.h.
     {
         bool status = send_message(msg);
         return wait_for_answer(msg);
     }
References ClientConnection< ServerDecoder, ClientDecoder >::send_message(), and ClientConnection< ServerDecoder, ClientDecoder >::wait_for_answer().
set_accepted_key()
template<typename ServerDecoder , typename ClientDecoder > void ClientConnection< ServerDecoder, ClientDecoder >::set_accepted_key (int key) inline
Definition at line 22 of file ClientConnection.h.
 { m_accepted_key = key; }
References ClientConnection< ServerDecoder, ClientDecoder >::m_accepted_key.
wait_for_answer()
template<typename ServerDecoder , typename ClientDecoder > UniquePtr<Message> ClientConnection< ServerDecoder, ClientDecoder >::wait_for_answer (const Message & msg) inline
Definition at line 37 of file ClientConnection.h.
     {
         for (;;) {
             for (int i = 0; i < m_messages.size(); i++) {
                 if (m_messages[i] && m_messages[i]->key() == msg.key() && m_messages[i]->id() == msg.reply_id()) {
                     return m_messages[i].release();
                 }
             }
             pump_messages();
         }
     }
References Message::key(), ClientConnection< ServerDecoder, ClientDecoder >::m_messages, ClientConnection< ServerDecoder, ClientDecoder >::pump_messages(), Message::reply_id(), and Algo::Vector< T >::size().
Referenced by ClientConnection< ServerDecoder, ClientDecoder >::send_sync().
Field Documentation
m_accepted_key
template<typename ServerDecoder , typename ClientDecoder > int ClientConnection< ServerDecoder, ClientDecoder >::m_accepted_key { -1 } private
Definition at line 105 of file ClientConnection.h.
Referenced by ClientConnection< ServerDecoder, ClientDecoder >::receive_event(), and ClientConnection< ServerDecoder, ClientDecoder >::set_accepted_key().
m_client_decoder
template<typename ServerDecoder , typename ClientDecoder > ClientDecoder& ClientConnection< ServerDecoder, ClientDecoder >::m_client_decoder private
Definition at line 109 of file ClientConnection.h.
Referenced by ClientConnection< ServerDecoder, ClientDecoder >::pump_messages(), and ClientConnection< ServerDecoder, ClientDecoder >::receive_event().
m_connection_fd
template<typename ServerDecoder , typename ClientDecoder > int ClientConnection< ServerDecoder, ClientDecoder >::m_connection_fd private
Definition at line 106 of file ClientConnection.h.
Referenced by ClientConnection< ServerDecoder, ClientDecoder >::pump_messages(), and ClientConnection< ServerDecoder, ClientDecoder >::send_message().
m_messages
template<typename ServerDecoder , typename ClientDecoder > Vector<UniquePtr<Message> > ClientConnection< ServerDecoder, ClientDecoder >::m_messages private
Definition at line 107 of file ClientConnection.h.
Referenced by ClientConnection< ServerDecoder, ClientDecoder >::pump_messages(), ClientConnection< ServerDecoder, ClientDecoder >::receive_event(), and ClientConnection< ServerDecoder, ClientDecoder >::wait_for_answer().
m_server_decoder
template<typename ServerDecoder , typename ClientDecoder > ServerDecoder& ClientConnection< ServerDecoder, ClientDecoder >::m_server_decoder private
Definition at line 108 of file ClientConnection.h.
Referenced by ClientConnection< ServerDecoder, ClientDecoder >::pump_messages().
The documentation for this class was generated from the following file:
libs/libipc/ClientConnection.h