oneOS: SetBarStyleMessage Class Reference
SetBarStyleMessage Class Reference
#include <WSConnection.h>
Public Member Functions
SetBarStyleMessage (message_key_t key, uint32_t window_id, uint32_t color, int text_style)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
uint32_t window_id () const
uint32_t color () const
int text_style () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
uint32_t m_window_id
uint32_t m_color
int m_text_style
Detailed Description
Definition at line 214 of file WSConnection.h.
Constructor & Destructor Documentation
SetBarStyleMessage()
SetBarStyleMessage::SetBarStyleMessage (message_key_t key, uint32_t window_id, uint32_t color, int text_style) inline
Definition at line 216 of file WSConnection.h.
         : m_key(key)
         , m_window_id(window_id)
         , m_color(color)
         , m_text_style(text_style)
     {
     }
Member Function Documentation
color()
uint32_t SetBarStyleMessage::color () const inline
Definition at line 228 of file WSConnection.h.
 { return m_color; }
References m_color.
Referenced by WServerDecoder::handle().
decoder_magic()
int SetBarStyleMessage::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 226 of file WSConnection.h.
 { return 320; }
Referenced by encode().
encode()
EncodedMessage SetBarStyleMessage::encode () const inline override virtual
Reimplemented from Message.
Definition at line 230 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_window_id);
         Encoder::append(buffer, m_color);
         Encoder::append(buffer, m_text_style);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), m_color, m_text_style, and m_window_id.
id()
int SetBarStyleMessage::id () const inline override virtual
Reimplemented from Message.
Definition at line 223 of file WSConnection.h.
 { return 8; }
key()
int SetBarStyleMessage::key () const inline override virtual
Reimplemented from Message.
Definition at line 225 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode().
reply_id()
int SetBarStyleMessage::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 224 of file WSConnection.h.
 { return -1; }
text_style()
int SetBarStyleMessage::text_style () const inline
Definition at line 229 of file WSConnection.h.
 { return m_text_style; }
References m_text_style.
window_id()
uint32_t SetBarStyleMessage::window_id () const inline
Definition at line 227 of file WSConnection.h.
 { return m_window_id; }
References m_window_id.
Referenced by WServerDecoder::handle().
Field Documentation
m_color
uint32_t SetBarStyleMessage::m_color private
Definition at line 244 of file WSConnection.h.
Referenced by color(), and encode().
m_key
message_key_t SetBarStyleMessage::m_key private
Definition at line 242 of file WSConnection.h.
Referenced by key().
m_text_style
int SetBarStyleMessage::m_text_style private
Definition at line 245 of file WSConnection.h.
Referenced by encode(), and text_style().
m_window_id
uint32_t SetBarStyleMessage::m_window_id private
Definition at line 243 of file WSConnection.h.
Referenced by encode(), and window_id().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h