oneOS: UI::EdgeInsect Class Reference
UI::EdgeInsect Class Reference
#include <EdgeInsets.h>
Public Member Functions
EdgeInsect ()=default
EdgeInsect (int top, int left, int bottom, int right)
int top () const
int left () const
int bottom () const
int right () const
Private Attributes
int m_top { 0 }
int m_bottom { 0 }
int m_left { 0 }
int m_right { 0 }
Detailed Description
Definition at line 13 of file EdgeInsets.h.
Constructor & Destructor Documentation
EdgeInsect() [1/2]
UI::EdgeInsect::EdgeInsect () default
EdgeInsect() [2/2]
UI::EdgeInsect::EdgeInsect (int top, int left, int bottom, int right) inline
Definition at line 16 of file EdgeInsets.h.
         : m_top(top)
         , m_left(left)
         , m_bottom(bottom)
         , m_right(right)
     {
     }
Member Function Documentation
bottom()
int UI::EdgeInsect::bottom () const inline
Definition at line 26 of file EdgeInsets.h.
 { return m_bottom; }
References m_bottom.
Referenced by UI::Button::recalc_bounds(), and UI::Label::recalc_bounds().
left()
int UI::EdgeInsect::left () const inline
Definition at line 25 of file EdgeInsets.h.
 { return m_left; }
References m_left.
Referenced by UI::Button::display(), UI::Label::display(), UI::Label::preferred_width(), UI::Button::recalc_bounds(), and UI::Label::recalc_bounds().
right()
int UI::EdgeInsect::right () const inline
Definition at line 27 of file EdgeInsets.h.
 { return m_right; }
References m_right.
Referenced by UI::Label::display(), UI::Label::preferred_width(), UI::Button::recalc_bounds(), and UI::Label::recalc_bounds().
top()
int UI::EdgeInsect::top () const inline
Definition at line 24 of file EdgeInsets.h.
 { return m_top; }
References m_top.
Referenced by UI::Button::display(), UI::Label::display(), UI::Button::recalc_bounds(), and UI::Label::recalc_bounds().
Field Documentation
m_bottom
int UI::EdgeInsect::m_bottom { 0 } private
Definition at line 31 of file EdgeInsets.h.
Referenced by bottom().
m_left
int UI::EdgeInsect::m_left { 0 } private
Definition at line 32 of file EdgeInsets.h.
Referenced by left().
m_right
int UI::EdgeInsect::m_right { 0 } private
Definition at line 33 of file EdgeInsets.h.
Referenced by right().
m_top
int UI::EdgeInsect::m_top { 0 } private
Definition at line 30 of file EdgeInsets.h.
Referenced by top().
The documentation for this class was generated from the following file:
libs/libui/EdgeInsets.h