oneOS: CreateWindowMessageReply Class Reference
CreateWindowMessageReply Class Reference
#include <WSConnection.h>
Public Member Functions
CreateWindowMessageReply (message_key_t key, uint32_t window_id)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
uint32_t window_id () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
uint32_t m_window_id
Detailed Description
Definition at line 102 of file WSConnection.h.
Constructor & Destructor Documentation
CreateWindowMessageReply()
CreateWindowMessageReply::CreateWindowMessageReply (message_key_t key, uint32_t window_id) inline
Definition at line 104 of file WSConnection.h.
         : m_key(key)
         , m_window_id(window_id)
     {
     }
Member Function Documentation
decoder_magic()
int CreateWindowMessageReply::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 112 of file WSConnection.h.
 { return 320; }
Referenced by encode().
encode()
EncodedMessage CreateWindowMessageReply::encode () const inline override virtual
Reimplemented from Message.
Definition at line 114 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_window_id);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), and m_window_id.
id()
int CreateWindowMessageReply::id () const inline override virtual
Reimplemented from Message.
Definition at line 109 of file WSConnection.h.
 { return 4; }
key()
int CreateWindowMessageReply::key () const inline override virtual
Reimplemented from Message.
Definition at line 111 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode().
reply_id()
int CreateWindowMessageReply::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 110 of file WSConnection.h.
 { return -1; }
window_id()
uint32_t CreateWindowMessageReply::window_id () const inline
Definition at line 113 of file WSConnection.h.
 { return m_window_id; }
References m_window_id.
Field Documentation
m_key
message_key_t CreateWindowMessageReply::m_key private
Definition at line 124 of file WSConnection.h.
Referenced by key().
m_window_id
uint32_t CreateWindowMessageReply::m_window_id private
Definition at line 125 of file WSConnection.h.
Referenced by encode(), and window_id().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h