oneOS: Window Class Reference
Window Class Reference
#include <Window.h>
Public Member Functions
Window (int connection_id, int id, const CreateWindowMessage &msg)
Window (Window &&win)
void set_buffer (int buffer_id)
int id () const
int connection_id () const
WindowType type () const
WindowEventMask event_mask () const
void set_event_mask (WindowEventMask mask)
SharedBuffer< LG::Color > & buffer ()
LG::PixelBitmap & content_bitmap ()
const LG::PixelBitmap & content_bitmap () const
LG::Rect & content_bounds ()
const LG::Rect & content_bounds () const
LG::Rect & bounds ()
const LG::Rect & bounds () const
WindowFrame & frame ()
const WindowFrame & frame () const
void set_needs_display (const LG::Rect &rect) const
void make_frame ()
void make_frameless ()
void set_icon (LG::String &&name)
void set_icon (const LG::String &name)
const LG::String & icon_path () const
void will_be_closed ()
void will_be_minimized ()
void was_minimized ()
void will_be_maximized ()
void was_maximized ()
Public Member Functions inherited from Weakable< Window >
WeakPtr< Window > weak_ptr ()
Public Member Functions inherited from Algo::LinkedListNode< Window >
LinkedListNode ()=default
Window * next () const
Window * prev () const
void set_prev (Window *prev)
void set_next (Window *next)
Private Attributes
int m_id { -1 }
int m_connection_id { -1 }
WindowType m_type { WindowType::Standard }
WindowEventMask m_event_mask { 0 }
LG::Rect m_bounds
LG::Rect m_content_bounds
LG::PixelBitmap m_content_bitmap
SharedBuffer< LG::Color > m_buffer
WindowFrame m_frame
LG::String m_icon_path {}
Additional Inherited Members
Protected Member Functions inherited from Weakable< Window >
Weakable ()
~Weakable ()
Detailed Description
Definition at line 37 of file Window.h.
Constructor & Destructor Documentation
Window() [1/2]
Window::Window (int connection_id, int id, const CreateWindowMessage & msg)
Definition at line 13 of file Window.cpp.
     : m_id(id)
     , m_connection_id(connection_id)
     , m_type((WindowType)msg.type())
     , m_buffer(msg.buffer_id())
     , m_frame(*this)
     , m_content_bitmap()
     , m_bounds(0, 0, 0, 0)
     , m_content_bounds(0, 0, 0, 0)
 {
     m_bounds = LG::Rect(0, 0, msg.width() + frame().left_border_size() + frame().right_border_size(), msg.height() + frame().top_border_size() + frame().bottom_border_size());
     m_content_bounds = LG::Rect(m_frame.left_border_size(), m_frame.top_border_size(), msg.width(), msg.height());
     m_content_bitmap = LG::PixelBitmap(m_buffer.data(), content_bounds().width(), content_bounds().height());
 }
References content_bounds(), Sys::SharedBuffer< T >::data(), frame(), CreateWindowMessage::height(), WindowFrame::left_border_size(), m_bounds, m_buffer, m_content_bitmap, m_content_bounds, m_frame, WindowFrame::top_border_size(), and CreateWindowMessage::width().
Window() [2/2]
Window::Window (Window && win)
Definition at line 28 of file Window.cpp.
     : m_id(win.m_id)
     , m_connection_id(win.m_connection_id)
     , m_buffer(win.m_buffer)
     , m_frame(*this, move(win.m_frame.control_panel_buttons()), move(win.m_frame.window_control_buttons()))
     , m_content_bitmap(move(win.m_content_bitmap))
     , m_bounds(win.m_bounds)
     , m_content_bounds(win.m_content_bounds)
 {
 }
Member Function Documentation
bounds() [1/2]
LG::Rect& Window::bounds () inline
Definition at line 57 of file Window.h.
 { return m_bounds; }
References m_bounds.
Referenced by __attribute__(), WindowFrame::bounds(), WindowManager::bring_to_front(), WindowManager::continue_window_move(), WindowFrame::draw(), WindowManager::receive_mouse_event(), WindowFrame::receive_tap_event(), WindowManager::remove_window(), and WindowManager::setup_dock().
bounds() [2/2]
const LG::Rect& Window::bounds () const inline
Definition at line 58 of file Window.h.
 { return m_bounds; }
References m_bounds.
buffer()
SharedBuffer<LG::Color>& Window::buffer () inline
Definition at line 50 of file Window.h.
 { return m_buffer; }
References m_buffer.
connection_id()
int Window::connection_id () const inline
Definition at line 45 of file Window.h.
 { return m_connection_id; }
References m_connection_id.
Referenced by WindowManager::close_window(), WindowManager::notify_listner_about_changed_icon(), WindowManager::notify_listner_about_window_status(), WindowManager::receive_keyboard_event(), WindowManager::receive_mouse_event(), and set_needs_display().
content_bitmap() [1/2]
LG::PixelBitmap& Window::content_bitmap () inline
Definition at line 51 of file Window.h.
 { return m_content_bitmap; }
References m_content_bitmap.
Referenced by __attribute__().
content_bitmap() [2/2]
const LG::PixelBitmap& Window::content_bitmap () const inline
Definition at line 52 of file Window.h.
 { return m_content_bitmap; }
References m_content_bitmap.
content_bounds() [1/2]
LG::Rect& Window::content_bounds () inline
Definition at line 54 of file Window.h.
 { return m_content_bounds; }
References m_content_bounds.
Referenced by __attribute__(), WindowManager::continue_window_move(), WindowManager::receive_mouse_event(), WindowManager::setup_dock(), and Window().
content_bounds() [2/2]
const LG::Rect& Window::content_bounds () const inline
Definition at line 55 of file Window.h.
 { return m_content_bounds; }
References m_content_bounds.
event_mask()
WindowEventMask Window::event_mask () const inline
Definition at line 47 of file Window.h.
 { return m_event_mask; }
References m_event_mask.
Referenced by WindowManager::notify_window_icon_changed(), and WindowManager::notify_window_status_changed().
frame() [1/2]
WindowFrame& Window::frame () inline
Definition at line 60 of file Window.h.
 { return m_frame; }
References m_frame.
Referenced by __attribute__(), make_frame(), WindowManager::receive_mouse_event(), and Window().
frame() [2/2]
const WindowFrame& Window::frame () const inline
Definition at line 61 of file Window.h.
 { return m_frame; }
References m_frame.
icon_path()
const LG::String& Window::icon_path () const inline
Definition at line 84 of file Window.h.
 { return m_icon_path; }
References m_icon_path.
Referenced by WindowFrame::reload_icon().
id()
int Window::id () const inline
Definition at line 44 of file Window.h.
 { return m_id; }
References m_id.
Referenced by WindowManager::add_window(), WindowManager::close_window(), WindowManager::notify_listner_about_changed_icon(), WindowManager::notify_listner_about_window_status(), WindowManager::receive_keyboard_event(), WindowManager::receive_mouse_event(), WindowManager::remove_window(), and WindowManager::window().
make_frame()
void Window::make_frame ()
Definition at line 46 of file Window.cpp.
 {
     uint32_t x = m_bounds.min_x();
     uint32_t y = m_bounds.min_y();
     uint32_t content_width = m_content_bounds.width();
     uint32_t content_height = m_content_bounds.height();
     m_bounds = LG::Rect(x, y, content_width + frame().left_border_size() + frame().right_border_size(), content_height + frame().top_border_size() + frame().bottom_border_size());
     m_content_bounds = LG::Rect(x + m_frame.left_border_size(), y + m_frame.top_border_size(), content_width, content_height);
     m_frame.set_visible(true);
 }
References frame(), LG::Rect::height(), WindowFrame::left_border_size(), m_bounds, m_content_bounds, m_frame, LG::Rect::min_x(), LG::Rect::min_y(), WindowFrame::set_visible(), WindowFrame::top_border_size(), and LG::Rect::width().
make_frameless()
void Window::make_frameless ()
Definition at line 57 of file Window.cpp.
 {
     uint32_t x = m_bounds.min_x();
     uint32_t y = m_bounds.min_y();
     uint32_t content_width = m_content_bounds.width();
     uint32_t content_height = m_content_bounds.height();
     m_bounds = LG::Rect(x, y, content_width, content_height);
     m_content_bounds = LG::Rect(x, y, content_width, content_height);
     m_frame.set_visible(false);
 }
References LG::Rect::height(), m_bounds, m_content_bounds, m_frame, LG::Rect::min_x(), LG::Rect::min_y(), WindowFrame::set_visible(), and LG::Rect::width().
Referenced by WindowManager::setup_dock().
set_buffer()
void Window::set_buffer (int buffer_id)
Definition at line 39 of file Window.cpp.
 {
     if (m_buffer.id() != buffer_id) {
         m_buffer.open(buffer_id);
     }
 }
References Sys::SharedBuffer< T >::id(), m_buffer, and Sys::SharedBuffer< T >::open().
Referenced by WServerDecoder::handle().
set_event_mask()
void Window::set_event_mask (WindowEventMask mask) inline
Definition at line 48 of file Window.h.
 { m_event_mask = mask; }
References m_event_mask.
Referenced by WindowManager::setup_dock().
set_icon() [1/2]
void Window::set_icon (const LG::String & name) inline
Definition at line 78 of file Window.h.
     {
         m_icon_path = name;
         m_frame.reload_icon();
     }
References m_frame, m_icon_path, copy_bin::name, and WindowFrame::reload_icon().
set_icon() [2/2]
void Window::set_icon (LG::String && name) inline
Definition at line 72 of file Window.h.
     {
         m_icon_path = move(name);
         m_frame.reload_icon();
     }
References m_frame, m_icon_path, move(), copy_bin::name, and WindowFrame::reload_icon().
set_needs_display()
void Window::set_needs_display (const LG::Rect & rect) const inline
Definition at line 63 of file Window.h.
     {
         DisplayMessage msg(connection_id(), rect);
         Connection::the().send_async_message(msg);
     }
References connection_id(), Connection::send_async_message(), and Connection::the().
type()
WindowType Window::type () const inline
Definition at line 46 of file Window.h.
 { return m_type; }
References m_type.
Referenced by token.Token::__str__(), and WindowManager::add_window().
was_maximized()
void Window::was_maximized ()
was_minimized()
void Window::was_minimized ()
will_be_closed()
void Window::will_be_closed ()
will_be_maximized()
void Window::will_be_maximized ()
will_be_minimized()
void Window::will_be_minimized ()
Field Documentation
m_bounds
LG::Rect Window::m_bounds private
Definition at line 97 of file Window.h.
Referenced by bounds(), make_frame(), make_frameless(), and Window().
m_buffer
SharedBuffer<LG::Color> Window::m_buffer private
Definition at line 100 of file Window.h.
Referenced by buffer(), set_buffer(), and Window().
m_connection_id
int Window::m_connection_id { -1 } private
Definition at line 94 of file Window.h.
Referenced by connection_id().
m_content_bitmap
LG::PixelBitmap Window::m_content_bitmap private
Definition at line 99 of file Window.h.
Referenced by content_bitmap(), and Window().
m_content_bounds
LG::Rect Window::m_content_bounds private
Definition at line 98 of file Window.h.
Referenced by content_bounds(), make_frame(), make_frameless(), and Window().
m_event_mask
WindowEventMask Window::m_event_mask { 0 } private
Definition at line 96 of file Window.h.
Referenced by event_mask(), and set_event_mask().
m_frame
WindowFrame Window::m_frame private
Definition at line 101 of file Window.h.
Referenced by frame(), make_frame(), make_frameless(), set_icon(), and Window().
m_icon_path
LG::String Window::m_icon_path {} private
Definition at line 102 of file Window.h.
Referenced by icon_path(), and set_icon().
m_id
int Window::m_id { -1 } private
Definition at line 93 of file Window.h.
Referenced by id().
m_type
WindowType Window::m_type { WindowType::Standard } private
Definition at line 95 of file Window.h.
Referenced by type().
The documentation for this class was generated from the following files:
servers/window_server/Window.h
servers/window_server/Window.cpp