oneOS: Sys::SharedBuffer< T > Class Template Reference
Sys::SharedBuffer< T > Class Template Reference
#include <SharedBuffer.h>
Public Member Functions
SharedBuffer ()=default
SharedBuffer (size_t size)
SharedBuffer (int id)
~SharedBuffer ()
void create (size_t size)
void open (int id)
void free ()
bool alive () const
const T & at (size_t i) const
T & at (size_t i)
size_t size () const
const T & operator[] (size_t i) const
T & operator[] (size_t i)
int id () const
T * data ()
Private Attributes
int m_id { -1 }
size_t m_size { 0 }
T * m_data { nullptr }
Detailed Description
template<typename T>
class Sys::SharedBuffer< T >
Definition at line 7 of file SharedBuffer.h.
Constructor & Destructor Documentation
SharedBuffer() [1/3]
template<typename T > Sys::SharedBuffer< T >::SharedBuffer () default
SharedBuffer() [2/3]
template<typename T > Sys::SharedBuffer< T >::SharedBuffer (size_t size) inline
Definition at line 10 of file SharedBuffer.h.
         : m_size(size)
     {
         m_id = shared_buffer_create((uint8_t**)&m_data, m_size);
     }
References Sys::SharedBuffer< T >::m_data, Sys::SharedBuffer< T >::m_id, Sys::SharedBuffer< T >::m_size, and shared_buffer_create().
SharedBuffer() [3/3]
template<typename T > Sys::SharedBuffer< T >::SharedBuffer (int id) inline
Definition at line 16 of file SharedBuffer.h.
         : m_id(id)
     {
         if (shared_buffer_get(m_id, (uint8_t**)&m_data) != 0) {
             m_id = -1;
         }
     }
References Sys::SharedBuffer< T >::m_data, Sys::SharedBuffer< T >::m_id, and shared_buffer_get().
~SharedBuffer()
template<typename T > Sys::SharedBuffer< T >::~SharedBuffer () inline
Definition at line 24 of file SharedBuffer.h.
     {
     }
Member Function Documentation
alive()
template<typename T > bool Sys::SharedBuffer< T >::alive () const inline
Definition at line 50 of file SharedBuffer.h.
 { return m_id >= 0; }
References Sys::SharedBuffer< T >::m_id.
Referenced by Sys::SharedBuffer< T >::free().
at() [1/2]
template<typename T > T& Sys::SharedBuffer< T >::at (size_t i) inline
Definition at line 57 of file SharedBuffer.h.
     {
         return data()[i];
     }
References Sys::SharedBuffer< T >::data().
at() [2/2]
template<typename T > const T& Sys::SharedBuffer< T >::at (size_t i) const inline
Definition at line 52 of file SharedBuffer.h.
     {
         return data()[i];
     }
References Sys::SharedBuffer< T >::data().
Referenced by Sys::SharedBuffer< T >::operator[]().
create()
template<typename T > void Sys::SharedBuffer< T >::create (size_t size) inline
Definition at line 28 of file SharedBuffer.h.
     {
         m_size = size;
         m_id = shared_buffer_create((uint8_t**)&m_data, m_size);
     }
References Sys::SharedBuffer< T >::m_data, Sys::SharedBuffer< T >::m_id, Sys::SharedBuffer< T >::m_size, shared_buffer_create(), and Sys::SharedBuffer< T >::size().
data()
template<typename T > T* Sys::SharedBuffer< T >::data () inline
Definition at line 68 of file SharedBuffer.h.
 { return m_data; }
References Sys::SharedBuffer< T >::m_data.
Referenced by Sys::SharedBuffer< T >::at(), Window::Window(), and UI::Window::Window().
free()
template<typename T > void Sys::SharedBuffer< T >::free () inline
Definition at line 42 of file SharedBuffer.h.
     {
         if (alive()) {
             shared_buffer_free(id());
             m_id = -1;
         }
     }
References Sys::SharedBuffer< T >::alive(), Sys::SharedBuffer< T >::m_id, and shared_buffer_free().
id()
template<typename T > int Sys::SharedBuffer< T >::id () const inline
Definition at line 67 of file SharedBuffer.h.
 { return m_id; }
References Sys::SharedBuffer< T >::m_id.
Referenced by UI::Connection::new_window(), Sys::SharedBuffer< T >::open(), and Window::set_buffer().
open()
template<typename T > void Sys::SharedBuffer< T >::open (int id) inline
Definition at line 34 of file SharedBuffer.h.
     {
         m_id = id;
         if (shared_buffer_get(m_id, (uint8_t**)&m_data) != 0) {
             m_id = -1;
         }
     }
References Sys::SharedBuffer< T >::id(), Sys::SharedBuffer< T >::m_data, Sys::SharedBuffer< T >::m_id, and shared_buffer_get().
Referenced by Window::set_buffer().
operator[]() [1/2]
template<typename T > T& Sys::SharedBuffer< T >::operator[] (size_t i) inline
Definition at line 65 of file SharedBuffer.h.
 { return at(i); }
References Sys::SharedBuffer< T >::at().
operator[]() [2/2]
template<typename T > const T& Sys::SharedBuffer< T >::operator[] (size_t i) const inline
Definition at line 64 of file SharedBuffer.h.
 { return at(i); }
References Sys::SharedBuffer< T >::at().
size()
template<typename T > size_t Sys::SharedBuffer< T >::size () const inline
Definition at line 62 of file SharedBuffer.h.
 { return m_size; }
References Sys::SharedBuffer< T >::m_size.
Referenced by Sys::SharedBuffer< T >::create().
Field Documentation
m_data
template<typename T > T* Sys::SharedBuffer< T >::m_data { nullptr } private
Definition at line 73 of file SharedBuffer.h.
Referenced by Sys::SharedBuffer< T >::create(), Sys::SharedBuffer< T >::data(), Sys::SharedBuffer< T >::open(), and Sys::SharedBuffer< T >::SharedBuffer().
m_id
template<typename T > int Sys::SharedBuffer< T >::m_id { -1 } private
Definition at line 71 of file SharedBuffer.h.
Referenced by Sys::SharedBuffer< T >::alive(), Sys::SharedBuffer< T >::create(), Sys::SharedBuffer< T >::free(), Sys::SharedBuffer< T >::id(), Sys::SharedBuffer< T >::open(), and Sys::SharedBuffer< T >::SharedBuffer().
m_size
template<typename T > size_t Sys::SharedBuffer< T >::m_size { 0 } private
Definition at line 72 of file SharedBuffer.h.
Referenced by Sys::SharedBuffer< T >::create(), Sys::SharedBuffer< T >::SharedBuffer(), and Sys::SharedBuffer< T >::size().
The documentation for this class was generated from the following file:
libs/libcxx/sys/SharedBuffer.h