oneOS: WeakPtr< T > Class Template Reference
WeakPtr< T > Class Template Reference
#include <WeakPtr.h>
Public Member Functions
WeakPtr ()
WeakPtr & operator= (nullptr_t)
operator bool () const
T * ptr ()
const T * ptr () const
T * operator-> ()
const T * operator-> () const
T & operator* ()
const T & operator* () const
void clear ()
Private Member Functions
WeakPtr (WeakLink< T > *data)
Private Attributes
WeakLink< T > * m_data { nullptr }
Friends
class Weakable< T >
Detailed Description
template<typename T>
class WeakPtr< T >
Definition at line 29 of file WeakPtr.h.
Constructor & Destructor Documentation
WeakPtr() [1/2]
template<typename T > WeakPtr< T >::WeakPtr () inline
Definition at line 33 of file WeakPtr.h.
         : m_data(nullptr)
     {
     }
WeakPtr() [2/2]
template<typename T > WeakPtr< T >::WeakPtr (WeakLink< T > * data) inline private
Definition at line 58 of file WeakPtr.h.
         : m_data(data)
     {
     }
Member Function Documentation
clear()
template<typename T > void WeakPtr< T >::clear () inline
Definition at line 55 of file WeakPtr.h.
 { m_data = nullptr; }
References WeakPtr< T >::m_data.
operator bool()
template<typename T > WeakPtr< T >::operator bool () const inline
Definition at line 44 of file WeakPtr.h.
 { return ptr(); }
References WeakPtr< T >::ptr().
operator*() [1/2]
template<typename T > T& WeakPtr< T >::operator* () inline
Definition at line 52 of file WeakPtr.h.
 { return *ptr(); }
References WeakPtr< T >::ptr().
operator*() [2/2]
template<typename T > const T& WeakPtr< T >::operator* () const inline
Definition at line 53 of file WeakPtr.h.
 { return *ptr(); }
References WeakPtr< T >::ptr().
operator->() [1/2]
template<typename T > T* WeakPtr< T >::operator-> () inline
Definition at line 49 of file WeakPtr.h.
 { return ptr(); }
References WeakPtr< T >::ptr().
operator->() [2/2]
template<typename T > const T* WeakPtr< T >::operator-> () const inline
Definition at line 50 of file WeakPtr.h.
 { return ptr(); }
References WeakPtr< T >::ptr().
operator=()
template<typename T > WeakPtr& WeakPtr< T >::operator= (nullptr_t) inline
Definition at line 38 of file WeakPtr.h.
     {
         m_data = nullptr;
         return *this;
     }
References WeakPtr< T >::m_data.
ptr() [1/2]
template<typename T > T* WeakPtr< T >::ptr () inline
Definition at line 46 of file WeakPtr.h.
 { return m_data ? m_data->ptr() : nullptr; }
References WeakPtr< T >::m_data.
Referenced by WeakPtr< T >::operator bool(), WeakPtr< T >::operator*(), WeakPtr< T >::operator->(), and WindowManager::receive_mouse_event().
ptr() [2/2]
template<typename T > const T* WeakPtr< T >::ptr () const inline
Definition at line 47 of file WeakPtr.h.
 { return m_data ? m_data->ptr() : nullptr; }
References WeakPtr< T >::m_data.
Friends And Related Function Documentation
Weakable< T >
template<typename T > friend class Weakable< T > friend
Definition at line 25 of file WeakPtr.h.
Field Documentation
m_data
template<typename T > WeakLink<T>* WeakPtr< T >::m_data { nullptr } private
Definition at line 63 of file WeakPtr.h.
Referenced by WeakPtr< T >::clear(), WeakPtr< T >::operator=(), and WeakPtr< T >::ptr().
The documentation for this class was generated from the following file:
libs/libcxx/std/WeakPtr.h