oneOS: Algo::LinkedListNode< T > Class Template Reference
Algo::LinkedListNode< T > Class Template Reference
#include <LinkedList.h>
Public Member Functions
LinkedListNode ()=default
T * next () const
T * prev () const
void set_prev (T *prev)
void set_next (T *next)
Private Attributes
T * m_prev { nullptr }
T * m_next { nullptr }
Detailed Description
template<class T>
class Algo::LinkedListNode< T >
Definition at line 36 of file LinkedList.h.
Constructor & Destructor Documentation
LinkedListNode()
template<class T > Algo::LinkedListNode< T >::LinkedListNode () default
Member Function Documentation
next()
template<class T > T* Algo::LinkedListNode< T >::next () const inline
Definition at line 40 of file LinkedList.h.
 { return m_next; }
References Algo::LinkedListNode< T >::m_next.
Referenced by Algo::LinkedListNode< T >::set_next().
prev()
template<class T > T* Algo::LinkedListNode< T >::prev () const inline
Definition at line 41 of file LinkedList.h.
 { return m_prev; }
References Algo::LinkedListNode< T >::m_prev.
Referenced by Algo::LinkedListNode< T >::set_prev().
set_next()
template<class T > void Algo::LinkedListNode< T >::set_next (T * next) inline
Definition at line 43 of file LinkedList.h.
 { m_next = next; };
References Algo::LinkedListNode< T >::m_next, and Algo::LinkedListNode< T >::next().
set_prev()
template<class T > void Algo::LinkedListNode< T >::set_prev (T * prev) inline
Definition at line 42 of file LinkedList.h.
 { m_prev = prev; };
References Algo::LinkedListNode< T >::m_prev, and Algo::LinkedListNode< T >::prev().
Field Documentation
m_next
template<class T > T* Algo::LinkedListNode< T >::m_next { nullptr } private
Definition at line 47 of file LinkedList.h.
Referenced by Algo::LinkedListNode< T >::next(), and Algo::LinkedListNode< T >::set_next().
m_prev
template<class T > T* Algo::LinkedListNode< T >::m_prev { nullptr } private
Definition at line 46 of file LinkedList.h.
Referenced by Algo::LinkedListNode< T >::prev(), and Algo::LinkedListNode< T >::set_prev().
The documentation for this class was generated from the following file:
libs/libcxx/std/LinkedList.h