oneOS: KeyboardMessage Class Reference
KeyboardMessage Class Reference
#include <WSConnection.h>
Public Member Functions
KeyboardMessage (message_key_t key, int win_id, uint32_t kbd_key)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
int win_id () const
uint32_t kbd_key () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
int m_win_id
uint32_t m_kbd_key
Detailed Description
Definition at line 564 of file WSConnection.h.
Constructor & Destructor Documentation
KeyboardMessage()
KeyboardMessage::KeyboardMessage (message_key_t key, int win_id, uint32_t kbd_key) inline
Definition at line 566 of file WSConnection.h.
         : m_key(key)
         , m_win_id(win_id)
         , m_kbd_key(kbd_key)
     {
     }
Member Function Documentation
decoder_magic()
int KeyboardMessage::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 575 of file WSConnection.h.
 { return 737; }
Referenced by encode().
encode()
EncodedMessage KeyboardMessage::encode () const inline override virtual
Reimplemented from Message.
Definition at line 578 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_win_id);
         Encoder::append(buffer, m_kbd_key);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), m_kbd_key, and m_win_id.
id()
int KeyboardMessage::id () const inline override virtual
Reimplemented from Message.
Definition at line 572 of file WSConnection.h.
 { return 4; }
kbd_key()
uint32_t KeyboardMessage::kbd_key () const inline
Definition at line 577 of file WSConnection.h.
 { return m_kbd_key; }
References m_kbd_key.
Referenced by UI::ClientDecoder::handle().
key()
int KeyboardMessage::key () const inline override virtual
Reimplemented from Message.
Definition at line 574 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode().
reply_id()
int KeyboardMessage::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 573 of file WSConnection.h.
 { return -1; }
win_id()
int KeyboardMessage::win_id () const inline
Definition at line 576 of file WSConnection.h.
 { return m_win_id; }
References m_win_id.
Referenced by UI::ClientDecoder::handle().
Field Documentation
m_kbd_key
uint32_t KeyboardMessage::m_kbd_key private
Definition at line 591 of file WSConnection.h.
Referenced by encode(), and kbd_key().
m_key
message_key_t KeyboardMessage::m_key private
Definition at line 589 of file WSConnection.h.
Referenced by key().
m_win_id
int KeyboardMessage::m_win_id private
Definition at line 590 of file WSConnection.h.
Referenced by encode(), and win_id().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h