oneOS: LFoundation::Event Class Reference
LFoundation::Event Class Reference
#include <Event.h>
Public Types
enum Type {
Invalid = 0 , FdWaiterRead , FdWaiterWrite , DeferredInvoke ,
Other
}
Public Member Functions
Event (int type)
~Event ()
int type ()
Private Attributes
int m_type
Detailed Description
Definition at line 13 of file Event.h.
Member Enumeration Documentation
Type
enum LFoundation::Event::Type
Enumerator
Invalid
FdWaiterRead
FdWaiterWrite
DeferredInvoke
Other
Definition at line 15 of file Event.h.
               {
         Invalid = 0,
         FdWaiterRead,
         FdWaiterWrite,
         DeferredInvoke,
         Other,
     };
Constructor & Destructor Documentation
Event()
LFoundation::Event::Event (int type) inline
Definition at line 23 of file Event.h.
         : m_type(type)
     {
     }
~Event()
LFoundation::Event::~Event () inline
Definition at line 28 of file Event.h.
 { }
Member Function Documentation
type()
int LFoundation::Event::type () inline
Definition at line 30 of file Event.h.
 { return m_type; }
References m_type.
Referenced by token.Token::__str__(), ClientConnection< ServerDecoder, ClientDecoder >::receive_event(), UI::App::receive_event(), UI::Responder::receive_event(), UI::Window::receive_event(), Connection::receive_event(), WindowManager::receive_event(), and DockWindow::receive_event().
Field Documentation
m_type
int LFoundation::Event::m_type private
Definition at line 33 of file Event.h.
Referenced by type().
The documentation for this class was generated from the following file:
libs/libfoundation/Event.h