oneOS: Devices Class Reference
Devices Class Reference
#include <Devices.h>
Public Member Functions
Devices ()
~Devices ()
void pump_mouse ()
void pump_keyboard ()
Static Public Member Functions
static Devices & the ()
Private Attributes
int m_mouse_fd
int m_keyboard_fd
Detailed Description
Definition at line 16 of file Devices.h.
Constructor & Destructor Documentation
Devices()
Devices::Devices ()
Definition at line 14 of file Devices.cpp.
 {
     s_the = this;
     m_mouse_fd = open("/dev/mouse", O_RDONLY);
     if (!m_mouse_fd) {
         Dbg() << "Can't open mouse\n";
     }
     m_keyboard_fd = open("/dev/kbd", O_RDONLY);
     if (!m_keyboard_fd) {
         Dbg() << "Can't open keyboard\n";
     }
     LFoundation::EventLoop::the().add(
         m_mouse_fd, [] {
             Devices::the().pump_mouse();
         },
         nullptr);
     LFoundation::EventLoop::the().add(
         m_keyboard_fd, [] {
             Devices::the().pump_keyboard();
         },
         nullptr);
 }
References LFoundation::EventLoop::add(), m_keyboard_fd, m_mouse_fd, O_RDONLY, open(), pump_keyboard(), pump_mouse(), s_the, LFoundation::EventLoop::the(), and the().
~Devices()
Devices::~Devices () inline
Definition at line 20 of file Devices.h.
 {}
Member Function Documentation
pump_keyboard()
void Devices::pump_keyboard () inline
Definition at line 39 of file Devices.h.
     {
         LFoundation::EventLoop& el = LFoundation::EventLoop::the();
         WindowManager& wm = WindowManager::the();
         char buf[512];
         int read_cnt = read(m_keyboard_fd, buf, sizeof(buf));
         if (read_cnt <= 0) {
             return;
         }
         KeyboardPacket* packet_buf = (KeyboardPacket*)buf;
         for (int offset = 0, cnt = 0; offset < read_cnt; offset += sizeof(KeyboardPacket), cnt++) {
             el.add(wm, new KeyboardEvent(packet_buf[cnt]));
         }
     }
References LFoundation::EventLoop::add(), buf, m_keyboard_fd, read(), LFoundation::EventLoop::the(), and WindowManager::the().
Referenced by Devices().
pump_mouse()
void Devices::pump_mouse () inline
Definition at line 22 of file Devices.h.
     {
         LFoundation::EventLoop& el = LFoundation::EventLoop::the();
         WindowManager& wm = WindowManager::the();
         char buf[512];
         int read_cnt = read(m_mouse_fd, buf, sizeof(buf));
         if (read_cnt <= 0) {
             return;
         }
         MousePacket* packet_buf = (MousePacket*)buf;
         for (int offset = 0, cnt = 0; offset < read_cnt; offset += sizeof(MousePacket), cnt++) {
             el.add(wm, new MouseEvent(packet_buf[cnt]));
         }
     }
References LFoundation::EventLoop::add(), buf, m_mouse_fd, read(), LFoundation::EventLoop::the(), and WindowManager::the().
Referenced by Devices().
the()
Devices & Devices::the () static
Definition at line 40 of file Devices.cpp.
 {
     return *s_the;
 }
References s_the.
Referenced by Devices().
Field Documentation
m_keyboard_fd
int Devices::m_keyboard_fd private
Definition at line 58 of file Devices.h.
Referenced by Devices(), and pump_keyboard().
m_mouse_fd
int Devices::m_mouse_fd private
Definition at line 57 of file Devices.h.
Referenced by Devices(), and pump_mouse().
The documentation for this class was generated from the following files:
servers/window_server/Devices.h
servers/window_server/Devices.cpp