oneOS: LG::PNG::ScanlineKeeper Class Reference
LG::PNG::ScanlineKeeper Class Reference
#include <PNGLoader.h>
Public Member Functions
ScanlineKeeper ()=default
~ScanlineKeeper ()
void init (void *ptr)
void init (void *ptr, uint8_t color_length)
void invalidate ()
void add (Scanline &&el)
void set_color_length (uint8_t color_length)
uint8_t color_length () const
Vector< Scanline > & scanlines ()
const Vector< Scanline > & scanlines () const
Private Attributes
uint8_t m_color_length { 0 }
void * m_ptr { nullptr }
Vector< Scanline > m_data
Detailed Description
Definition at line 97 of file PNGLoader.h.
Constructor & Destructor Documentation
ScanlineKeeper()
LG::PNG::ScanlineKeeper::ScanlineKeeper () default
~ScanlineKeeper()
LG::PNG::ScanlineKeeper::~ScanlineKeeper () inline
Definition at line 100 of file PNGLoader.h.
 { invalidate(); }
References invalidate().
Member Function Documentation
add()
void LG::PNG::ScanlineKeeper::add (Scanline && el) inline
Definition at line 114 of file PNGLoader.h.
 { m_data.push_back(move(el)); }
References m_data, and move().
Referenced by LG::PNG::PNGLoader::read_IDAT().
color_length()
uint8_t LG::PNG::ScanlineKeeper::color_length () const inline
Definition at line 116 of file PNGLoader.h.
 { return m_color_length; }
References m_color_length.
Referenced by init(), LG::PNG::PNGLoader::read_IDAT(), set_color_length(), and LG::PNG::PNGLoader::unfilter_scanlines().
init() [1/2]
void LG::PNG::ScanlineKeeper::init (void * ptr) inline
Definition at line 102 of file PNGLoader.h.
 { m_ptr = ptr; }
References m_ptr.
Referenced by LG::PNG::PNGLoader::read_IDAT().
init() [2/2]
void LG::PNG::ScanlineKeeper::init (void * ptr, uint8_t color_length) inline
Definition at line 103 of file PNGLoader.h.
 { m_ptr = ptr, m_color_length = color_length; }
References color_length(), m_color_length, and m_ptr.
invalidate()
void LG::PNG::ScanlineKeeper::invalidate () inline
Definition at line 105 of file PNGLoader.h.
     {
         if (m_ptr) {
             free(m_ptr);
             m_data.clear();
             m_ptr = nullptr;
         }
     }
References free(), m_data, and m_ptr.
Referenced by LG::PNG::PNGLoader::read_IDAT(), and ~ScanlineKeeper().
scanlines() [1/2]
Vector<Scanline>& LG::PNG::ScanlineKeeper::scanlines () inline
Definition at line 118 of file PNGLoader.h.
 { return m_data; }
References m_data.
Referenced by LG::PNG::PNGLoader::copy_scanlines_to_bitmap(), and LG::PNG::PNGLoader::unfilter_scanlines().
scanlines() [2/2]
const Vector<Scanline>& LG::PNG::ScanlineKeeper::scanlines () const inline
Definition at line 119 of file PNGLoader.h.
 { return m_data; }
References m_data.
set_color_length()
void LG::PNG::ScanlineKeeper::set_color_length (uint8_t color_length) inline
Definition at line 115 of file PNGLoader.h.
 { m_color_length = color_length; }
References color_length(), and m_color_length.
Referenced by LG::PNG::PNGLoader::read_IDAT().
Field Documentation
m_color_length
uint8_t LG::PNG::ScanlineKeeper::m_color_length { 0 } private
Definition at line 122 of file PNGLoader.h.
Referenced by color_length(), init(), and set_color_length().
m_data
Vector<Scanline> LG::PNG::ScanlineKeeper::m_data private
Definition at line 124 of file PNGLoader.h.
Referenced by add(), invalidate(), and scanlines().
m_ptr
void* LG::PNG::ScanlineKeeper::m_ptr { nullptr } private
Definition at line 123 of file PNGLoader.h.
Referenced by init(), and invalidate().
The documentation for this class was generated from the following file:
libs/libg/ImageLoaders/PNGLoader.h