oneOS: LG::Point< T > Class Template Reference
LG::Point< T > Class Template Reference
#include <Point.h>
Public Member Functions
Point ()=default
Point (T x, T y)
~Point ()
void set (const Point &p)
void set_x (int x)
void set_y (int y)
T x () const
T y () const
void offset_by (int x, int y)
void offset_by (const Point &p)
Point operator- () const
Point operator- (const Point &p) const
Point & operator-= (const Point &p)
Point & operator+= (const Point &p)
Point operator+ (const Point &p) const
bool operator== (const Point &p) const
bool operator!= (const Point &p) const
void encode (EncodedMessage &buf) const override
void decode (const char *buf, size_t &offset) override
Private Attributes
T m_x {}
T m_y {}
Detailed Description
template<typename T>
class LG::Point< T >
Definition at line 19 of file Point.h.
Constructor & Destructor Documentation
Point() [1/2]
template<typename T > LG::Point< T >::Point () default
Point() [2/2]
template<typename T > LG::Point< T >::Point (T x, T y) inline
Definition at line 23 of file Point.h.
         : m_x(x)
         , m_y(y)
     {
     }
~Point()
template<typename T > LG::Point< T >::~Point () inline
Definition at line 28 of file Point.h.
 { }
Member Function Documentation
decode()
template<typename T > void LG::Point< T >::decode (const char * buf, size_t & offset) inline override virtual
Reimplemented from Decodable< Point< T > >.
Definition at line 73 of file Point.h.
     {
         Encoder::decode(buf, offset, m_x);
         Encoder::decode(buf, offset, m_y);
     }
References buf, Encoder::decode(), LG::Point< T >::m_x, and LG::Point< T >::m_y.
encode()
template<typename T > void LG::Point< T >::encode (EncodedMessage & buf) const inline override virtual
Reimplemented from Encodable< Point< T > >.
Definition at line 67 of file Point.h.
     {
         Encoder::append(buf, m_x);
         Encoder::append(buf, m_y);
     }
References Encoder::append(), buf, LG::Point< T >::m_x, and LG::Point< T >::m_y.
offset_by() [1/2]
template<typename T > void LG::Point< T >::offset_by (const Point< T > & p) inline
Definition at line 38 of file Point.h.
 { offset_by(p.x(), p.y()); }
References LG::Point< T >::offset_by(), and p.
Referenced by LG::Point< T >::offset_by().
offset_by() [2/2]
template<typename T > void LG::Point< T >::offset_by (int x, int y) inline
Definition at line 37 of file Point.h.
 { m_x += x, m_y += y; }
References LG::Point< T >::m_x, LG::Point< T >::m_y, LG::Point< T >::x(), and LG::Point< T >::y().
Referenced by Button::display(), LG::Rect::offset_by(), and WindowManager::receive_mouse_event().
operator!=()
template<typename T > bool LG::Point< T >::operator!= (const Point< T > & p) const inline
Definition at line 62 of file Point.h.
     {
         return !(*this == p);
     }
References p.
operator+()
template<typename T > Point LG::Point< T >::operator+ (const Point< T > & p) const inline
Definition at line 55 of file Point.h.
 { return { m_x + p.m_x, m_y + p.m_y }; }
References LG::Point< T >::m_x, LG::Point< T >::m_y, and p.
operator+=()
template<typename T > Point& LG::Point< T >::operator+= (const Point< T > & p) inline
Definition at line 49 of file Point.h.
     {
         m_x += p.m_x;
         m_y += p.m_y;
         return *this;
     }
References LG::Point< T >::m_x, LG::Point< T >::m_y, and p.
operator-() [1/2]
template<typename T > Point LG::Point< T >::operator- () const inline
Definition at line 40 of file Point.h.
 { return { -m_x, -m_y }; }
References LG::Point< T >::m_x, and LG::Point< T >::m_y.
operator-() [2/2]
template<typename T > Point LG::Point< T >::operator- (const Point< T > & p) const inline
Definition at line 41 of file Point.h.
 { return { m_x - p.m_x, m_y - p.m_y }; }
References LG::Point< T >::m_x, LG::Point< T >::m_y, and p.
operator-=()
template<typename T > Point& LG::Point< T >::operator-= (const Point< T > & p) inline
Definition at line 42 of file Point.h.
     {
         m_x -= p.m_x;
         m_y -= p.m_y;
         return *this;
     }
References LG::Point< T >::m_x, LG::Point< T >::m_y, and p.
operator==()
template<typename T > bool LG::Point< T >::operator== (const Point< T > & p) const inline
Definition at line 57 of file Point.h.
     {
         return m_x == p.m_x && m_y == p.m_y;
     }
References LG::Point< T >::m_x, LG::Point< T >::m_y, and p.
set()
template<typename T > void LG::Point< T >::set (const Point< T > & p) inline
Definition at line 30 of file Point.h.
 { m_x = p.x(), m_y = p.y(); }
References LG::Point< T >::m_x, LG::Point< T >::m_y, and p.
Referenced by WindowManager::update_mouse_position().
set_x()
template<typename T > void LG::Point< T >::set_x (int x) inline
Definition at line 31 of file Point.h.
 { m_x = x; }
References LG::Point< T >::m_x, and LG::Point< T >::x().
Referenced by LG::Rect::set_x().
set_y()
template<typename T > void LG::Point< T >::set_y (int y) inline
Definition at line 32 of file Point.h.
 { m_y = y; }
References LG::Point< T >::m_y, and LG::Point< T >::y().
Referenced by LG::Rect::set_y().
x()
template<typename T > T LG::Point< T >::x () const inline
Definition at line 34 of file Point.h.
 { return m_x; }
References LG::Point< T >::m_x.
Referenced by LG::Context::draw(), LG::Rect::max_x(), LG::Rect::mid_x(), LG::Rect::min_x(), LG::Point< T >::offset_by(), WindowManager::receive_mouse_event(), LG::Context::set(), and LG::Point< T >::set_x().
y()
template<typename T > T LG::Point< T >::y () const inline
Definition at line 35 of file Point.h.
 { return m_y; }
References LG::Point< T >::m_y.
Referenced by LG::Context::draw(), LG::Rect::max_y(), LG::Rect::mid_y(), LG::Rect::min_y(), LG::Point< T >::offset_by(), WindowManager::receive_mouse_event(), LG::Context::set(), and LG::Point< T >::set_y().
Field Documentation
m_x
template<typename T > T LG::Point< T >::m_x {} private
Definition at line 80 of file Point.h.
Referenced by LG::Point< T >::decode(), LG::Point< T >::encode(), LG::Point< T >::offset_by(), LG::Point< T >::operator+(), LG::Point< T >::operator+=(), LG::Point< T >::operator-(), LG::Point< T >::operator-=(), LG::Point< T >::operator==(), LG::Point< T >::set(), LG::Point< T >::set_x(), and LG::Point< T >::x().
m_y
template<typename T > T LG::Point< T >::m_y {} private
Definition at line 81 of file Point.h.
Referenced by LG::Point< T >::decode(), LG::Point< T >::encode(), LG::Point< T >::offset_by(), LG::Point< T >::operator+(), LG::Point< T >::operator+=(), LG::Point< T >::operator-(), LG::Point< T >::operator-=(), LG::Point< T >::operator==(), LG::Point< T >::set(), LG::Point< T >::set_y(), and LG::Point< T >::y().
The documentation for this class was generated from the following file:
libs/libg/Point.h