oneOS: Algo::String Class Reference
Algo::String Class Reference
#include <String.h>
Public Member Functions
String ()=default
String (const char *str)
String (const String &s)
String (String &&s)
~String ()
String & operator= (const String &s)
String & operator= (String &&s)
String & operator+= (const String &s)
String operator+ (const String &s) const
String operator+ (const char *s) const
void push_back (char c)
void pop_back ()
const char & at (size_t i) const
char & at (size_t i)
void clear ()
size_t size () const
const char & operator[] (size_t i) const
char & operator[] (size_t i)
const char & back () const
char & back ()
const char * c_str () const
const char * data () const
Private Member Functions
void ensure_capacity (size_t new_size)
void grow (size_t capacity)
char * end ()
Private Attributes
size_t m_size { 0 }
size_t m_capacity { 0 }
char * m_str { nullptr }
Detailed Description
Definition at line 8 of file String.h.
Constructor & Destructor Documentation
String() [1/4]
Algo::String::String () default
Referenced by operator+().
String() [2/4]
Algo::String::String (const char * str) inline
Definition at line 12 of file String.h.
     {
         m_size = strlen(str);
         ensure_capacity(m_size + 1);
         memcpy((uint8_t*)m_str, (uint8_t*)str, m_size);
         m_str[m_size] = '\0';
     }
References ensure_capacity(), m_size, m_str, memcpy(), __main__::str, and strlen().
String() [3/4]
Algo::String::String (const String & s) inline
Definition at line 20 of file String.h.
     {
         grow(s.m_capacity);
         m_size = s.m_size;
         memcpy((uint8_t*)m_str, (uint8_t*)s.m_str, m_size);
         m_str[m_size] = '\0';
     }
References grow(), m_capacity, m_size, m_str, and memcpy().
String() [4/4]
Algo::String::String (String && s) inline
Definition at line 28 of file String.h.
     {
         m_size = s.m_size;
         m_capacity = s.m_capacity;
         m_str = s.m_str;
         s.m_size = s.m_capacity = 0;
         s.m_str = nullptr;
     }
References m_capacity, m_size, and m_str.
~String()
Algo::String::~String () inline
Definition at line 37 of file String.h.
     {
         clear();
     }
References clear().
Member Function Documentation
at() [1/2]
char& Algo::String::at (size_t i) inline
Definition at line 104 of file String.h.
     {
         return m_str[i];
     }
References m_str.
at() [2/2]
const char& Algo::String::at (size_t i) const inline
Definition at line 99 of file String.h.
     {
         return m_str[i];
     }
References m_str.
Referenced by back(), LG::String::encode(), and operator[]().
back() [1/2]
char& Algo::String::back () inline
Definition at line 125 of file String.h.
 { return at(size() - 1); }
References at(), and size().
back() [2/2]
const char& Algo::String::back () const inline
Definition at line 124 of file String.h.
 { return at(size() - 1); }
References at(), and size().
c_str()
const char* Algo::String::c_str () const inline
Definition at line 127 of file String.h.
 { return m_str; }
References m_str.
Referenced by DockView::launch(), LG::PNG::PNGLoader::load_from_file(), and TerminalView::send_input().
clear()
void Algo::String::clear () inline
Definition at line 109 of file String.h.
     {
         m_size = 0;
         m_capacity = 0;
         if (m_str) {
             free(m_str);
             m_str = nullptr;
         }
     }
References free(), m_capacity, m_size, and m_str.
Referenced by operator=(), TerminalView::send_input(), and ~String().
data()
const char* Algo::String::data () const inline
Definition at line 128 of file String.h.
 { return m_str; }
References m_str.
end()
char* Algo::String::end () inline private
Definition at line 152 of file String.h.
 { return m_str + m_size; }
References m_size, and m_str.
Referenced by operator+=().
ensure_capacity()
void Algo::String::ensure_capacity (size_t new_size) inline private
Definition at line 131 of file String.h.
     {
         if (new_size > m_capacity) {
             grow(new_size + 16);
         }
     }
References grow(), and m_capacity.
Referenced by operator+=(), push_back(), and String().
grow()
void Algo::String::grow (size_t capacity) inline private
Definition at line 138 of file String.h.
     {
         if (capacity < m_capacity) {
             return;
         }
         if (!m_str) {
             m_str = (char*)malloc(capacity);
         } else {
             m_str = (char*)realloc(m_str, capacity);
         }
         m_capacity = capacity;
     }
References m_capacity, m_str, malloc(), and realloc().
Referenced by ensure_capacity(), operator=(), and String().
operator+() [1/2]
String Algo::String::operator+ (const char * s) const inline
Definition at line 80 of file String.h.
     {
         String res(*this);
         res += String(s);
         return res;
     }
References String().
operator+() [2/2]
String Algo::String::operator+ (const String & s) const inline
Definition at line 73 of file String.h.
     {
         String res(*this);
         res += s;
         return res;
     }
operator+=()
String& Algo::String::operator+= (const String & s) inline
Definition at line 64 of file String.h.
     {
         ensure_capacity(size() + s.size() + 1);
         memcpy((uint8_t*)end(), (uint8_t*)s.m_str, s.size());
         m_size += s.size();
         m_str[m_size] = '\0';
         return *this;
     }
References end(), ensure_capacity(), m_size, m_str, memcpy(), and size().
operator=() [1/2]
String& Algo::String::operator= (const String & s) inline
Definition at line 42 of file String.h.
     {
         grow(s.m_capacity);
         m_size = s.m_size;
         memcpy((uint8_t*)m_str, (uint8_t*)s.m_str, m_size);
         m_str[m_size] = '\0';
         return *this;
     }
References grow(), m_capacity, m_size, m_str, and memcpy().
operator=() [2/2]
String& Algo::String::operator= (String && s) inline
Definition at line 51 of file String.h.
     {
         if (this != &s) {
             clear();
             m_size = s.m_size;
             m_capacity = s.m_capacity;
             m_str = s.m_str;
             s.m_size = s.m_capacity = 0;
             s.m_str = nullptr;
         }
         return *this;
     }
References clear(), m_capacity, m_size, and m_str.
operator[]() [1/2]
char& Algo::String::operator[] (size_t i) inline
Definition at line 122 of file String.h.
 { return at(i); }
References at().
operator[]() [2/2]
const char& Algo::String::operator[] (size_t i) const inline
Definition at line 121 of file String.h.
 { return at(i); }
References at().
pop_back()
void Algo::String::pop_back () inline
Definition at line 94 of file String.h.
     {
         m_str[--m_size] = '\0';
     }
References m_size, and m_str.
Referenced by TerminalView::receive_keydown_event().
push_back()
void Algo::String::push_back (char c) inline
Definition at line 87 of file String.h.
     {
         ensure_capacity(size() + 2);
         m_str[m_size++] = c;
         m_str[m_size] = '\0';
     }
References ensure_capacity(), m_size, m_str, and size().
Referenced by LG::String::decode(), and TerminalView::receive_keydown_event().
size()
size_t Algo::String::size () const inline
Definition at line 119 of file String.h.
 { return m_size; }
References m_size.
Referenced by back(), UI::Button::display(), UI::Label::display(), Button::display(), LG::String::encode(), operator+=(), push_back(), Button::recalc_dims(), TerminalView::receive_keydown_event(), TerminalView::send_input(), UI::Button::text_width(), Button::text_width(), and UI::Label::text_width().
Field Documentation
m_capacity
size_t Algo::String::m_capacity { 0 } private
Definition at line 155 of file String.h.
Referenced by clear(), ensure_capacity(), grow(), operator=(), and String().
m_size
size_t Algo::String::m_size { 0 } private
Definition at line 154 of file String.h.
Referenced by clear(), end(), operator+=(), operator=(), pop_back(), push_back(), size(), and String().
m_str
char* Algo::String::m_str { nullptr } private
Definition at line 156 of file String.h.
Referenced by at(), c_str(), clear(), data(), end(), grow(), operator+=(), operator=(), pop_back(), push_back(), and String().
The documentation for this class was generated from the following file:
libs/libcxx/std/String.h