oneOS: LG::Font Class Reference
LG::Font Class Reference
#include <Font.h>
Public Member Functions
Font (uint32_t *raw_data, uint8_t *m_width_data, uint8_t width, uint8_t height, size_t count, bool dynamic_width)
~Font ()
uint8_t glyph_width (size_t ch) const
uint8_t glyph_height () const
GlyphBitmap glyph_bitmap (size_t ch) const
Static Public Member Functions
static Font & system_font ()
static Font & system_bold_font ()
static Font * load_from_file (const char *path)
static Font * load_from_mem (uint8_t *path)
Private Attributes
uint32_t * m_raw_data
uint8_t * m_width_data
uint8_t m_width
uint8_t m_height
size_t m_count
bool m_dynamic_width
Detailed Description
Definition at line 51 of file Font.h.
Constructor & Destructor Documentation
Font()
LG::Font::Font (uint32_t * raw_data, uint8_t * m_width_data, uint8_t width, uint8_t height, size_t count, bool dynamic_width)
Definition at line 49 of file Font.cpp.
     : m_raw_data(raw_data)
     , m_width_data(width_data)
     , m_width(width)
     , m_height(height)
     , m_count(count)
     , m_dynamic_width(dynamic_width)
 {
 }
Referenced by load_from_mem().
~Font()
LG::Font::~Font () inline
Definition at line 54 of file Font.h.
 { }
Member Function Documentation
glyph_bitmap()
GlyphBitmap LG::Font::glyph_bitmap (size_t ch) const
Definition at line 114 of file Font.cpp.
 {
     return GlyphBitmap(&m_raw_data[ch * m_height], glyph_width(ch), m_height);
 }
References glyph_width(), m_height, and m_raw_data.
glyph_height()
uint8_t LG::Font::glyph_height () const inline
Definition at line 62 of file Font.h.
 { return m_height; }
References m_height.
Referenced by TerminalView::glyph_height(), UI::Button::text_height(), Button::text_height(), and UI::Label::text_height().
glyph_width()
uint8_t LG::Font::glyph_width (size_t ch) const inline
Definition at line 61 of file Font.h.
 { return m_dynamic_width ? m_width_data[ch] : m_width; }
References m_dynamic_width, m_width, and m_width_data.
Referenced by UI::Label::display(), glyph_bitmap(), and TerminalView::glyph_width().
load_from_file()
Font * LG::Font::load_from_file (const char * path) static
Definition at line 59 of file Font.cpp.
 {
     int fd = open(path, O_RDONLY);
     if (fd < 0) {
         return nullptr;
     }
     fstat_t stat;
     fstat(fd, &stat);
     mmap_params_t mmap_params;
     mmap_params.prot = PROT_READ;
     mmap_params.flags = MAP_PRIVATE;
     mmap_params.fd = fd;
     mmap_params.size = stat.size;
     uint8_t* res = (uint8_t*)mmap(&mmap_params);
     return Font::load_from_mem(res);
 }
References mmap_params::fd, mmap_params::flags, fstat(), load_from_mem(), MAP_PRIVATE, mmap(), O_RDONLY, open(), mmap_params::prot, PROT_READ, mmap_params::size, and fstat::size.
Referenced by system_bold_font(), and system_font().
load_from_mem()
Font * LG::Font::load_from_mem (uint8_t * path) static
Definition at line 79 of file Font.cpp.
 {
     if (!font_data) {
         return nullptr;
     }
     FontFileHeader& header = *(FontFileHeader*)font_data;
     if (memcmp((uint8_t*)header.magic, (const uint8_t*)"!Fnt", 4)) {
         write(1, "Font unsupported\n", 17);
         return nullptr;
     }
     size_t count = 0;
     if (header.type == 0) {
         count = 256;
     } else if (header.type == 1) {
         count = 384;
     } else {
         write(1, "Type unsupported\n", 17);
         return nullptr;
     }
     size_t bytes_per_glyph = sizeof(uint32_t) * header.glyph_height;
     uint32_t* raw_data = (uint32_t*)(font_data + sizeof(FontFileHeader));
     uint8_t* width_data = nullptr;
     if (header.is_variable_width) {
         width_data = (uint8_t*)((uint8_t*)(raw_data) + count * bytes_per_glyph);
     }
     return new Font(raw_data, width_data, header.glyph_width, header.glyph_height, count, header.is_variable_width);
 }
References Font(), fat16_formatter::header(), memcmp(), and write().
Referenced by load_from_file().
system_bold_font()
Font & LG::Font::system_bold_font () static
Definition at line 39 of file Font.cpp.
 {
     static Font* s_system_bold_font_ptr;
     const static char* s_system_bold_font_path = "/res/systembold.font";
     if (!s_system_bold_font_ptr) {
         s_system_bold_font_ptr = Font::load_from_file(s_system_bold_font_path);
     }
     return *s_system_bold_font_ptr;
 }
References load_from_file().
system_font()
Font & LG::Font::system_font () static
Definition at line 29 of file Font.cpp.
 {
     static Font* s_system_font_ptr;
     const static char* s_system_font_path = "/res/system.font";
     if (!s_system_font_ptr) {
         s_system_font_ptr = Font::load_from_file(s_system_font_path);
     }
     return *s_system_font_ptr;
 }
References load_from_file().
Field Documentation
m_count
size_t LG::Font::m_count private
Definition at line 70 of file Font.h.
m_dynamic_width
bool LG::Font::m_dynamic_width private
Definition at line 71 of file Font.h.
Referenced by glyph_width().
m_height
uint8_t LG::Font::m_height private
Definition at line 69 of file Font.h.
Referenced by glyph_bitmap(), and glyph_height().
m_raw_data
uint32_t* LG::Font::m_raw_data private
Definition at line 66 of file Font.h.
Referenced by glyph_bitmap().
m_width
uint8_t LG::Font::m_width private
Definition at line 68 of file Font.h.
Referenced by glyph_width().
m_width_data
uint8_t* LG::Font::m_width_data private
Definition at line 67 of file Font.h.
Referenced by glyph_width().
The documentation for this class was generated from the following files:
libs/libg/Font.h
libs/libg/Font.cpp