oneOS: NotifyWindowIconChangedMessage Class Reference
NotifyWindowIconChangedMessage Class Reference
#include <WSConnection.h>
Public Member Functions
NotifyWindowIconChangedMessage (message_key_t key, int win_id, int changed_window_id, LG::String icon_path)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
int win_id () const
int changed_window_id () const
LG::String icon_path () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
int m_win_id
int m_changed_window_id
LG::String m_icon_path
Detailed Description
Definition at line 706 of file WSConnection.h.
Constructor & Destructor Documentation
NotifyWindowIconChangedMessage()
NotifyWindowIconChangedMessage::NotifyWindowIconChangedMessage (message_key_t key, int win_id, int changed_window_id, LG::String icon_path) inline
Definition at line 708 of file WSConnection.h.
         : m_key(key)
         , m_win_id(win_id)
         , m_changed_window_id(changed_window_id)
         , m_icon_path(icon_path)
     {
     }
Member Function Documentation
changed_window_id()
int NotifyWindowIconChangedMessage::changed_window_id () const inline
Definition at line 720 of file WSConnection.h.
 { return m_changed_window_id; }
References m_changed_window_id.
Referenced by UI::ClientDecoder::handle().
decoder_magic()
int NotifyWindowIconChangedMessage::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 718 of file WSConnection.h.
 { return 737; }
Referenced by encode().
encode()
EncodedMessage NotifyWindowIconChangedMessage::encode () const inline override virtual
Reimplemented from Message.
Definition at line 722 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_win_id);
         Encoder::append(buffer, m_changed_window_id);
         Encoder::append(buffer, m_icon_path);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), m_changed_window_id, m_icon_path, and m_win_id.
icon_path()
LG::String NotifyWindowIconChangedMessage::icon_path () const inline
Definition at line 721 of file WSConnection.h.
 { return m_icon_path; }
References m_icon_path.
Referenced by UI::ClientDecoder::handle().
id()
int NotifyWindowIconChangedMessage::id () const inline override virtual
Reimplemented from Message.
Definition at line 715 of file WSConnection.h.
 { return 9; }
key()
int NotifyWindowIconChangedMessage::key () const inline override virtual
Reimplemented from Message.
Definition at line 717 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode().
reply_id()
int NotifyWindowIconChangedMessage::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 716 of file WSConnection.h.
 { return -1; }
win_id()
int NotifyWindowIconChangedMessage::win_id () const inline
Definition at line 719 of file WSConnection.h.
 { return m_win_id; }
References m_win_id.
Referenced by UI::ClientDecoder::handle().
Field Documentation
m_changed_window_id
int NotifyWindowIconChangedMessage::m_changed_window_id private
Definition at line 736 of file WSConnection.h.
Referenced by changed_window_id(), and encode().
m_icon_path
LG::String NotifyWindowIconChangedMessage::m_icon_path private
Definition at line 737 of file WSConnection.h.
Referenced by encode(), and icon_path().
m_key
message_key_t NotifyWindowIconChangedMessage::m_key private
Definition at line 734 of file WSConnection.h.
Referenced by key().
m_win_id
int NotifyWindowIconChangedMessage::m_win_id private
Definition at line 735 of file WSConnection.h.
Referenced by encode(), and win_id().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h