oneOS: Algo::LinkedList< T > Class Template Reference
Algo::LinkedList< T > Class Template Reference
#include <LinkedList.h>
Public Types
using Iterator = LinkedListIterator< T >
Public Member Functions
LinkedList ()
bool is_empty () const
T * head () const
T * tail () const
void push_front (T *node)
void push_back (T *node)
void remove (T *node)
Iterator begin ()
Iterator end ()
Data Fields
friend Iterator
Private Attributes
T * m_head { nullptr }
T * m_tail { nullptr }
Detailed Description
template<class T>
class Algo::LinkedList< T >
Definition at line 51 of file LinkedList.h.
Member Typedef Documentation
Iterator
template<class T > using Algo::LinkedList< T >::Iterator = LinkedListIterator<T>
Definition at line 64 of file LinkedList.h.
Constructor & Destructor Documentation
LinkedList()
template<class T > Algo::LinkedList< T >::LinkedList () inline
Definition at line 53 of file LinkedList.h.
 { }
Member Function Documentation
begin()
template<class T > Iterator Algo::LinkedList< T >::begin () inline
Definition at line 66 of file LinkedList.h.
 { return Iterator(m_head); }
References Algo::LinkedList< T >::m_head.
end()
template<class T > Iterator Algo::LinkedList< T >::end () inline
Definition at line 67 of file LinkedList.h.
 { return Iterator::null(); }
References Algo::LinkedListIterator< T >::null().
head()
template<class T > T* Algo::LinkedList< T >::head () const inline
Definition at line 57 of file LinkedList.h.
 { return m_head; }
References Algo::LinkedList< T >::m_head.
is_empty()
template<class T > bool Algo::LinkedList< T >::is_empty () const inline
Definition at line 55 of file LinkedList.h.
 { return !m_head; }
References Algo::LinkedList< T >::m_head.
push_back()
template<typename T > void Algo::LinkedList< T >::push_back (T * node)
Definition at line 94 of file LinkedList.h.
 {
     if (!m_tail) {
         ASSERT(!m_head);
         m_head = node;
         m_tail = node;
         node->set_prev(nullptr);
         node->set_next(nullptr);
         return;
     }
     ASSERT(m_head);
     m_tail->set_next(node);
     node->set_prev(m_tail);
     node->set_next(nullptr);
     m_tail = node;
 }
References ASSERT.
Referenced by WindowManager::add_window(), DockView::new_entity(), and DockView::new_fast_launch_entity().
push_front()
template<typename T > void Algo::LinkedList< T >::push_front (T * node)
Definition at line 75 of file LinkedList.h.
 {
     if (!m_head) {
         ASSERT(!m_tail);
         m_head = node;
         m_tail = node;
         node->set_prev(0);
         node->set_next(0);
         return;
     }
     ASSERT(m_tail);
     m_head->set_prev(node);
     node->set_next(m_head);
     node->set_prev(0);
     m_head = node;
 }
References ASSERT.
Referenced by WindowManager::do_bring_to_front().
remove()
template<typename T > void Algo::LinkedList< T >::remove (T * node) inline
Definition at line 113 of file LinkedList.h.
 {
     if (node->prev()) {
         ASSERT(node != m_head);
         node->prev()->set_next(node->next());
     } else {
         ASSERT(node == m_head);
         m_head = node->next();
     }
     if (node->next()) {
         ASSERT(node != m_tail);
         node->next()->set_prev(node->prev());
     } else {
         ASSERT(node == m_tail);
         m_tail = node->prev();
     }
 }
References ASSERT.
Referenced by WindowManager::do_bring_to_front(), DockView::remove_entity(), and WindowManager::remove_window().
tail()
template<class T > T* Algo::LinkedList< T >::tail () const inline
Definition at line 58 of file LinkedList.h.
 { return m_tail; }
References Algo::LinkedList< T >::m_tail.
Field Documentation
Iterator
template<class T > friend Algo::LinkedList< T >::Iterator
Definition at line 65 of file LinkedList.h.
m_head
template<class T > T* Algo::LinkedList< T >::m_head { nullptr } private
Definition at line 70 of file LinkedList.h.
Referenced by Algo::LinkedList< T >::begin(), Algo::LinkedList< T >::head(), and Algo::LinkedList< T >::is_empty().
m_tail
template<class T > T* Algo::LinkedList< T >::m_tail { nullptr } private
Definition at line 71 of file LinkedList.h.
Referenced by Algo::LinkedList< T >::tail().
The documentation for this class was generated from the following file:
libs/libcxx/std/LinkedList.h