oneOS: UI::NotifyWindowStatusChangedEvent Class Reference
UI::NotifyWindowStatusChangedEvent Class Reference
#include <Event.h>
Public Member Functions
NotifyWindowStatusChangedEvent (uint32_t changed_window_id, int type)
~NotifyWindowStatusChangedEvent ()
uint32_t changed_window_id () const
int type () const
Public Member Functions inherited from UI::Event
Event (int type)
~Event ()
Public Member Functions inherited from LFoundation::Event
Event (int type)
~Event ()
int type ()
Private Attributes
uint32_t m_changed_window_id
int m_type
Additional Inherited Members
Public Types inherited from UI::Event
enum Type {
Invalid = 0x2000 , MouseEvent , MouseActionEvent , MouseLeaveEvent ,
KeyUpEvent , KeyDownEvent , DisplayEvent , WindowCloseRequestEvent ,
NotifyWindowStatusChangedEvent , NotifyWindowIconChangedEvent , Other
}
Public Types inherited from LFoundation::Event
enum Type {
Invalid = 0 , FdWaiterRead , FdWaiterWrite , DeferredInvoke ,
Other
}
Detailed Description
Definition at line 174 of file Event.h.
Constructor & Destructor Documentation
NotifyWindowStatusChangedEvent()
UI::NotifyWindowStatusChangedEvent::NotifyWindowStatusChangedEvent (uint32_t changed_window_id, int type) inline
Definition at line 176 of file Event.h.
         : Event(Event::Type::NotifyWindowStatusChangedEvent)
         , m_changed_window_id(changed_window_id)
         , m_type(type)
     {
     }
~NotifyWindowStatusChangedEvent()
UI::NotifyWindowStatusChangedEvent::~NotifyWindowStatusChangedEvent () inline
Definition at line 183 of file Event.h.
 { }
Member Function Documentation
changed_window_id()
uint32_t UI::NotifyWindowStatusChangedEvent::changed_window_id () const inline
Definition at line 184 of file Event.h.
 { return m_changed_window_id; }
References m_changed_window_id.
Referenced by DockWindow::receive_event().
type()
int UI::NotifyWindowStatusChangedEvent::type () const inline
Definition at line 185 of file Event.h.
 { return m_type; }
References m_type.
Referenced by token.Token::__str__(), and DockWindow::receive_event().
Field Documentation
m_changed_window_id
uint32_t UI::NotifyWindowStatusChangedEvent::m_changed_window_id private
Definition at line 188 of file Event.h.
Referenced by changed_window_id().
m_type
int UI::NotifyWindowStatusChangedEvent::m_type private
Definition at line 189 of file Event.h.
Referenced by type().
The documentation for this class was generated from the following file:
libs/libui/Event.h