oneOS: Screen Class Reference
Screen Class Reference
#include <Screen.h>
Public Member Functions
Screen ()
void swap_buffers ()
size_t width ()
size_t height () const
LG::Rect & bounds ()
const LG::Rect & bounds () const
uint32_t depth () const
LG::PixelBitmap & write_bitmap ()
const LG::PixelBitmap & write_bitmap () const
LG::PixelBitmap & display_bitmap ()
const LG::PixelBitmap & display_bitmap () const
Static Public Member Functions
static Screen & the ()
Private Attributes
int m_screen_fd
LG::Rect m_bounds
uint32_t m_depth
int m_active_buffer
LG::PixelBitmap m_write_bitmap
LG::PixelBitmap m_display_bitmap
UniquePtr< LG::PixelBitmap > m_write_bitmap_ptr { nullptr }
UniquePtr< LG::PixelBitmap > m_display_bitmap_ptr { nullptr }
Detailed Description
Definition at line 15 of file Screen.h.
Constructor & Destructor Documentation
Screen()
Screen::Screen ()
Definition at line 21 of file Screen.cpp.
     : m_bounds(0, 0, 1024, 768)
     , m_depth(4)
     , m_write_bitmap()
     , m_display_bitmap()
 {
     s_the = this;
     m_screen_fd = open("/dev/bga", 0);
     mmap_params_t mp;
     mp.flags = MAP_SHARED;
     mp.fd = m_screen_fd;
     mp.size = 1; // Ignored in kernel mapping bga file
     mp.prot = PROT_READ | PROT_WRITE; // Ignored in kernel mapping bga file
     size_t screen_buffer_size = width() * height() * depth();
     LG::Color* first_buffer = (LG::Color*)mmap(&mp);
     LG::Color* second_buffer = (LG::Color*)((uint8_t*)first_buffer + screen_buffer_size);
     m_display_bitmap = LG::PixelBitmap(first_buffer, width(), height());
     m_write_bitmap = LG::PixelBitmap(second_buffer, width(), height());
     m_display_bitmap_ptr = &m_display_bitmap;
     m_write_bitmap_ptr = &m_write_bitmap;
     m_active_buffer = 0;
 }
References depth(), mmap_params::fd, mmap_params::flags, height(), m_active_buffer, m_display_bitmap, m_display_bitmap_ptr, m_screen_fd, m_write_bitmap, m_write_bitmap_ptr, MAP_SHARED, mmap(), open(), mmap_params::prot, PROT_READ, PROT_WRITE, s_the, mmap_params::size, and width().
Member Function Documentation
bounds() [1/2]
LG::Rect& Screen::bounds () inline
Definition at line 24 of file Screen.h.
 { return m_bounds; }
References m_bounds.
Referenced by WindowManager::setup_dock().
bounds() [2/2]
const LG::Rect& Screen::bounds () const inline
Definition at line 25 of file Screen.h.
 { return m_bounds; }
References m_bounds.
depth()
uint32_t Screen::depth () const inline
Definition at line 26 of file Screen.h.
 { return m_depth; }
References m_depth.
Referenced by Screen().
display_bitmap() [1/2]
LG::PixelBitmap& Screen::display_bitmap () inline
Definition at line 30 of file Screen.h.
 { return *m_display_bitmap_ptr; }
References m_display_bitmap_ptr.
display_bitmap() [2/2]
const LG::PixelBitmap& Screen::display_bitmap () const inline
Definition at line 31 of file Screen.h.
 { return *m_display_bitmap_ptr; }
References m_display_bitmap_ptr.
height()
size_t Screen::height () const inline
Definition at line 23 of file Screen.h.
 { return m_bounds.height(); }
References LG::Rect::height(), and m_bounds.
Referenced by Screen(), and WindowManager::update_mouse_position().
swap_buffers()
void Screen::swap_buffers ()
Definition at line 48 of file Screen.cpp.
 {
     m_write_bitmap_ptr.swap(m_display_bitmap_ptr);
     m_active_buffer ^= 1;
     ioctl(m_screen_fd, BGA_SWAP_BUFFERS, m_active_buffer);
 }
References BGA_SWAP_BUFFERS, ioctl(), m_active_buffer, m_display_bitmap_ptr, m_screen_fd, m_write_bitmap_ptr, and UniquePtr< T >::swap().
the()
Screen & Screen::the () static
Definition at line 16 of file Screen.cpp.
 {
     return *s_the;
 }
References s_the.
Referenced by __attribute__(), Compositor::Compositor(), and Compositor::copy_changes_to_second_buffer().
width()
size_t Screen::width () inline
Definition at line 22 of file Screen.h.
 { return m_bounds.width(); }
References m_bounds, and LG::Rect::width().
Referenced by Screen(), and WindowManager::update_mouse_position().
write_bitmap() [1/2]
LG::PixelBitmap& Screen::write_bitmap () inline
Definition at line 28 of file Screen.h.
 { return *m_write_bitmap_ptr; }
References m_write_bitmap_ptr.
write_bitmap() [2/2]
const LG::PixelBitmap& Screen::write_bitmap () const inline
Definition at line 29 of file Screen.h.
 { return *m_write_bitmap_ptr; }
References m_write_bitmap_ptr.
Field Documentation
m_active_buffer
int Screen::m_active_buffer private
Definition at line 38 of file Screen.h.
Referenced by Screen(), and swap_buffers().
m_bounds
LG::Rect Screen::m_bounds private
Definition at line 35 of file Screen.h.
Referenced by bounds(), height(), and width().
m_depth
uint32_t Screen::m_depth private
Definition at line 36 of file Screen.h.
Referenced by depth().
m_display_bitmap
LG::PixelBitmap Screen::m_display_bitmap private
Definition at line 41 of file Screen.h.
Referenced by Screen().
m_display_bitmap_ptr
UniquePtr<LG::PixelBitmap> Screen::m_display_bitmap_ptr { nullptr } private
Definition at line 44 of file Screen.h.
Referenced by display_bitmap(), Screen(), and swap_buffers().
m_screen_fd
int Screen::m_screen_fd private
Definition at line 34 of file Screen.h.
Referenced by Screen(), and swap_buffers().
m_write_bitmap
LG::PixelBitmap Screen::m_write_bitmap private
Definition at line 40 of file Screen.h.
Referenced by Screen().
m_write_bitmap_ptr
UniquePtr<LG::PixelBitmap> Screen::m_write_bitmap_ptr { nullptr } private
Definition at line 43 of file Screen.h.
Referenced by Screen(), swap_buffers(), and write_bitmap().
The documentation for this class was generated from the following files:
servers/window_server/Screen.h
servers/window_server/Screen.cpp