oneOS: UI::Context Class Reference
UI::Context Class Reference
#include <Context.h>
Public Member Functions
Context (LG::PixelBitmap &bitmap)
Context (View &view)
Public Member Functions inherited from LG::Context
Context (PixelBitmap &)
~Context ()
void add_clip (const Rect &rect)
void reset_clip ()
void set (const Point< int > &start, const PixelBitmap &bitmap)
void draw (const Point< int > &start, const PixelBitmap &bitmap)
void draw (const Point< int > &start, const GlyphBitmap &bitmap)
void fill (const Rect &rect)
void add_ellipse (const Rect &rect)
void set_draw_offset (const Point< int > &offset)
void set_fill_color (const Color &clr)
const Color & fill_color () const
Detailed Description
Definition at line 15 of file Context.h.
Constructor & Destructor Documentation
Context() [1/2]
UI::Context::Context (LG::PixelBitmap & bitmap) inline
Definition at line 17 of file Context.h.
         : LG::Context(bitmap)
     {
     }
Context() [2/2]
UI::Context::Context (View & view) inline
Definition at line 22 of file Context.h.
         : Context(view.window()->bitmap())
     {
         auto frame = view.frame_in_window();
         add_clip(frame);
         set_draw_offset(frame.origin());
     }
References LG::Context::add_clip(), UI::View::frame_in_window(), and LG::Context::set_draw_offset().
The documentation for this class was generated from the following file:
libs/libui/Context.h