oneOS: LG::Rect Class Reference
LG::Rect Class Reference
#include <Rect.h>
Public Member Functions
Rect ()=default
Rect (int x, int y, size_t width, size_t height)
~Rect ()
size_t width () const
size_t height () const
size_t square () const
int min_x () const
int mid_x () const
int max_x () const
int min_y () const
int mid_y () const
int max_y () const
bool empty () const
void set_x (int new_x)
void set_y (int new_y)
void set_width (int new_w)
void set_height (int new_h)
bool contains (int x, int y) const
bool contains (const Point< int > &p) const
void offset_by (int x, int y)
void offset_by (const Point< int > &p)
Point< int > & origin ()
const Point< int > & origin () const
void unite (const Rect &other)
LG::Rect union_of (const Rect &other) const
void intersect (const Rect &other)
bool intersects (const Rect &other) const
LG::Rect intersection (const Rect &other) const
void encode (EncodedMessage &buf) const override
void decode (const char *buf, size_t &offset) override
bool operator== (const Rect &r) const
bool operator!= (const Rect &r) const
Private Attributes
Point< int > m_origin
size_t m_width { 0 }
size_t m_height { 0 }
Detailed Description
Definition at line 20 of file Rect.h.
Constructor & Destructor Documentation
Rect() [1/2]
LG::Rect::Rect () default
Rect() [2/2]
LG::Rect::Rect (int x, int y, size_t width, size_t height)
Definition at line 13 of file Rect.cpp.
     : m_origin(x, y)
     , m_width(width)
     , m_height(height)
 {
 }
~Rect()
LG::Rect::~Rect () inline
Definition at line 25 of file Rect.h.
 { }
Member Function Documentation
contains() [1/2]
bool LG::Rect::contains (const Point< int > & p) const inline
Definition at line 44 of file Rect.h.
 { return contains(p.x(), p.y()); }
References contains(), and p.
Referenced by contains().
contains() [2/2]
bool LG::Rect::contains (int x, int y) const inline
Definition at line 43 of file Rect.h.
 { return min_x() <= x && x <= max_x() && min_y() <= y && y <= max_y(); }
References max_x(), max_y(), min_x(), and min_y().
Referenced by WindowManager::receive_mouse_event(), and UI::View::receive_mouse_move_event().
decode()
void LG::Rect::decode (const char * buf, size_t & offset) override virtual
Reimplemented from Decodable< Rect >.
Definition at line 100 of file Rect.cpp.
 {
     Encoder::decode(buf, offset, m_origin);
     Encoder::decode(buf, offset, m_width);
     Encoder::decode(buf, offset, m_height);
 }
References buf, Encoder::decode(), m_height, m_origin, and m_width.
empty()
bool LG::Rect::empty () const inline
Definition at line 36 of file Rect.h.
 { return !width() || !height(); }
References height(), and width().
Referenced by LG::Context::draw(), and LG::Context::set().
encode()
void LG::Rect::encode (EncodedMessage & buf) const override virtual
Reimplemented from Encodable< Rect >.
Definition at line 93 of file Rect.cpp.
 {
     Encoder::append(buf, m_origin);
     Encoder::append(buf, m_width);
     Encoder::append(buf, m_height);
 }
References Encoder::append(), buf, m_height, m_origin, and m_width.
height()
size_t LG::Rect::height () const inline
Definition at line 28 of file Rect.h.
 { return m_height; }
References m_height.
Referenced by LG::Context::add_ellipse(), WindowFrame::draw(), empty(), LG::PixelBitmap::height(), Screen::height(), Window::make_frame(), Window::make_frameless(), max_y(), mid_y(), UI::Connection::new_window(), TerminalView::recalc_dimensions(), WindowManager::setup_dock(), and square().
intersect()
void LG::Rect::intersect (const Rect & other)
Definition at line 46 of file Rect.cpp.
 {
     // (a, b) - top left corner
     // (c, d) - bottom right corner
     int a = max(min_x(), other.min_x());
     int b = max(min_y(), other.min_y());
     int c = min(max_x(), other.max_x());
     int d = min(max_y(), other.max_y());
     if (a > c || b > d) {
         set_width(0);
         set_height(0);
         return;
     }
     set_x(a);
     set_y(b);
     set_width(c - a + 1);
     set_height(d - b + 1);
 }
References max(), max_x(), max_y(), min(), min_x(), min_y(), set_height(), set_width(), set_x(), and set_y().
Referenced by LG::Context::add_clip(), LG::Context::draw(), LG::Context::set(), and UI::View::set_needs_display().
intersection()
LG::Rect LG::Rect::intersection (const Rect & other) const
Definition at line 78 of file Rect.cpp.
 {
     // (a, b) - top left corner
     // (c, d) - bottom right corner
     int a = max(min_x(), other.min_x());
     int b = max(min_y(), other.min_y());
     int c = min(max_x(), other.max_x());
     int d = min(max_y(), other.max_y());
     if (a > c || b > d) {
         return LG::Rect(0, 0, 0, 0);
     }
     return LG::Rect(a, b, c - a + 1, d - b + 1);
 }
References max(), max_x(), max_y(), min(), min_x(), and min_y().
intersects()
bool LG::Rect::intersects (const Rect & other) const
Definition at line 67 of file Rect.cpp.
 {
     // (a, b) - top left corner
     // (c, d) - bottom right corner
     int a = max(min_x(), other.min_x());
     int b = max(min_y(), other.min_y());
     int c = min(max_x(), other.max_x());
     int d = min(max_y(), other.max_y());
     return c >= a && d >= b;
 }
References max(), max_x(), max_y(), min(), min_x(), and min_y().
Referenced by UI::View::receive_display_event().
max_x()
int LG::Rect::max_x () const inline
Definition at line 32 of file Rect.h.
 { return m_origin.x() + width() - 1; }
References m_origin, width(), and LG::Point< T >::x().
Referenced by contains(), LG::Context::draw(), intersect(), intersection(), intersects(), LG::Context::set(), union_of(), and unite().
max_y()
int LG::Rect::max_y () const inline
Definition at line 35 of file Rect.h.
 { return m_origin.y() + height() - 1; }
References height(), m_origin, and LG::Point< T >::y().
Referenced by contains(), LG::Context::draw(), intersect(), intersection(), intersects(), LG::Context::set(), WindowManager::setup_dock(), union_of(), and unite().
mid_x()
int LG::Rect::mid_x () const inline
Definition at line 31 of file Rect.h.
 { return m_origin.x() + width() / 2; }
References m_origin, width(), and LG::Point< T >::x().
Referenced by LG::Context::add_ellipse().
mid_y()
int LG::Rect::mid_y () const inline
Definition at line 34 of file Rect.h.
 { return m_origin.y() + height() / 2; }
References height(), m_origin, and LG::Point< T >::y().
Referenced by LG::Context::add_ellipse().
min_x()
int LG::Rect::min_x () const inline
Definition at line 30 of file Rect.h.
 { return m_origin.x(); }
References m_origin, and LG::Point< T >::x().
Referenced by WindowFrame::bounds(), contains(), LG::Context::draw(), WindowFrame::draw(), intersect(), intersection(), intersects(), Window::make_frame(), Window::make_frameless(), WindowManager::receive_mouse_event(), LG::Context::set(), union_of(), and unite().
min_y()
int LG::Rect::min_y () const inline
Definition at line 33 of file Rect.h.
 { return m_origin.y(); }
References m_origin, and LG::Point< T >::y().
Referenced by WindowFrame::bounds(), contains(), LG::Context::draw(), WindowFrame::draw(), intersect(), intersection(), intersects(), Window::make_frame(), Window::make_frameless(), WindowManager::receive_mouse_event(), LG::Context::set(), union_of(), and unite().
offset_by() [1/2]
void LG::Rect::offset_by (const Point< int > & p) inline
Definition at line 46 of file Rect.h.
 { m_origin.offset_by(p); }
References m_origin, LG::Point< T >::offset_by(), and p.
offset_by() [2/2]
void LG::Rect::offset_by (int x, int y) inline
Definition at line 45 of file Rect.h.
 { m_origin.offset_by(x, y); }
References m_origin, and LG::Point< T >::offset_by().
Referenced by WindowManager::continue_window_move(), LG::Context::fill(), and WServerDecoder::handle().
operator!=()
bool LG::Rect::operator!= (const Rect & r) const inline
Definition at line 65 of file Rect.h.
     {
         return !(*this == r);
     }
operator==()
bool LG::Rect::operator== (const Rect & r) const inline
Definition at line 60 of file Rect.h.
     {
         return m_width == r.m_width && m_height == r.m_height && m_origin == r.m_origin;
     }
References m_height, m_origin, and m_width.
origin() [1/2]
Point<int>& LG::Rect::origin () inline
Definition at line 48 of file Rect.h.
 { return m_origin; }
References m_origin.
Referenced by __attribute__(), UI::View::frame_in_window(), WindowManager::receive_mouse_event(), and WindowManager::update_mouse_position().
origin() [2/2]
const Point<int>& LG::Rect::origin () const inline
Definition at line 49 of file Rect.h.
 { return m_origin; }
References m_origin.
set_height()
void LG::Rect::set_height (int new_h) inline
Definition at line 41 of file Rect.h.
 { m_height = new_h; }
References m_height.
Referenced by LG::PixelBitmap::clear(), intersect(), Button::recalc_dims(), LG::PixelBitmap::resize(), UI::View::set_height(), and unite().
set_width()
void LG::Rect::set_width (int new_w) inline
Definition at line 40 of file Rect.h.
 { m_width = new_w; }
References m_width.
Referenced by LG::PixelBitmap::clear(), intersect(), Button::recalc_dims(), LG::PixelBitmap::resize(), UI::View::set_width(), and unite().
set_x()
void LG::Rect::set_x (int new_x) inline
Definition at line 38 of file Rect.h.
 { m_origin.set_x(new_x); }
References m_origin, and LG::Point< T >::set_x().
Referenced by intersect(), and unite().
set_y()
void LG::Rect::set_y (int new_y) inline
Definition at line 39 of file Rect.h.
 { m_origin.set_y(new_y); }
References m_origin, and LG::Point< T >::set_y().
Referenced by intersect(), WindowManager::setup_dock(), and unite().
square()
size_t LG::Rect::square () const inline
Definition at line 29 of file Rect.h.
 { return width() * height(); }
References height(), and width().
Referenced by Compositor::optimized_invalidate_insert().
union_of()
LG::Rect LG::Rect::union_of (const Rect & other) const
Definition at line 35 of file Rect.cpp.
 {
     // (a, b) - top left corner
     // (c, d) - bottom right corner
     int a = min(min_x(), other.min_x());
     int b = min(min_y(), other.min_y());
     int c = max(max_x(), other.max_x());
     int d = max(max_y(), other.max_y());
     return LG::Rect(a, b, c - a + 1, d - b + 1);
 }
References max(), max_x(), max_y(), min(), min_x(), and min_y().
Referenced by Compositor::optimized_invalidate_insert().
unite()
void LG::Rect::unite (const Rect & other)
Definition at line 20 of file Rect.cpp.
 {
     // (a, b) - top left corner
     // (c, d) - bottom right corner
     int a = min(min_x(), other.min_x());
     int b = min(min_y(), other.min_y());
     int c = max(max_x(), other.max_x());
     int d = max(max_y(), other.max_y());
     set_x(a);
     set_y(b);
     set_width(c - a + 1);
     set_height(d - b + 1);
 }
References max(), max_x(), max_y(), min(), min_x(), min_y(), set_height(), set_width(), set_x(), and set_y().
width()
size_t LG::Rect::width () const inline
Definition at line 27 of file Rect.h.
 { return m_width; }
References m_width.
Referenced by LG::Context::add_ellipse(), WindowFrame::bounds(), UI::Label::display(), WindowFrame::draw(), empty(), Window::make_frame(), Window::make_frameless(), max_x(), mid_x(), UI::Connection::new_window(), TerminalView::recalc_dimensions(), WindowFrame::receive_tap_event(), square(), Screen::width(), and LG::PixelBitmap::width().
Field Documentation
m_height
size_t LG::Rect::m_height { 0 } private
Definition at line 73 of file Rect.h.
Referenced by decode(), encode(), height(), operator==(), and set_height().
m_origin
Point<int> LG::Rect::m_origin private
Definition at line 71 of file Rect.h.
Referenced by decode(), encode(), max_x(), max_y(), mid_x(), mid_y(), min_x(), min_y(), offset_by(), operator==(), origin(), set_x(), and set_y().
m_width
size_t LG::Rect::m_width { 0 } private
Definition at line 72 of file Rect.h.
Referenced by decode(), encode(), operator==(), set_width(), and width().
The documentation for this class was generated from the following files:
libs/libg/Rect.h
libs/libg/Rect.cpp