oneOS: LG::PixelBitmap Class Reference
LG::PixelBitmap Class Reference
#include <PixelBitmap.h>
Public Member Functions
PixelBitmap ()=default
PixelBitmap (size_t width, size_t height, PixelBitmapFormat format=RGB)
PixelBitmap (Color *buffer, size_t width, size_t height, PixelBitmapFormat format=RGB)
PixelBitmap (PixelBitmap &bitmap)
PixelBitmap (PixelBitmap &&moved_bitmap) noexcept
~PixelBitmap ()
void clear ()
PixelBitmap & operator= (PixelBitmap &bitmap)
PixelBitmap & operator= (PixelBitmap &&moved_bitmap) noexcept
size_t width () const
size_t height () const
LG::Rect & bounds ()
const LG::Rect & bounds () const
Color * data () const
Color * line (size_t i)
const Color * line (size_t i) const
Color * operator[] (size_t i)
const Color * operator[] (size_t i) const
void resize (size_t width, size_t height)
void set_format (PixelBitmapFormat format)
PixelBitmapFormat format () const
bool has_alpha_channel () const
Private Attributes
Color * m_data { nullptr }
LG::Rect m_bounds { 0, 0, 0, 0 }
bool m_should_free { false }
PixelBitmapFormat m_format { RGB }
Detailed Description
Definition at line 24 of file PixelBitmap.h.
Constructor & Destructor Documentation
PixelBitmap() [1/5]
LG::PixelBitmap::PixelBitmap () default
PixelBitmap() [2/5]
LG::PixelBitmap::PixelBitmap (size_t width, size_t height, PixelBitmapFormat format = RGB)
Definition at line 22 of file PixelBitmap.cpp.
     : m_bounds(0, 0, width, height)
     , m_data((Color*)malloc(sizeof(Color) * width * height))
     , m_should_free(true)
     , m_format(format)
 {
 }
PixelBitmap() [3/5]
LG::PixelBitmap::PixelBitmap (Color * buffer, size_t width, size_t height, PixelBitmapFormat format = RGB)
Definition at line 14 of file PixelBitmap.cpp.
     : m_data(buffer)
     , m_bounds(0, 0, width, height)
     , m_should_free(false)
     , m_format(format)
 {
 }
PixelBitmap() [4/5]
LG::PixelBitmap::PixelBitmap (PixelBitmap & bitmap)
Definition at line 31 of file PixelBitmap.cpp.
     : m_data(nullptr)
     , m_bounds(bitmap.m_bounds)
     , m_should_free(bitmap.m_should_free)
     , m_format(bitmap.m_format)
 {
     if (m_should_free) {
         size_t len = width() * height() * sizeof(Color);
         m_data = (Color*)malloc(len);
         memcpy((uint8_t*)m_data, (uint8_t*)bitmap.m_data, len);
     } else {
         m_data = bitmap.m_data;
     }
 }
References height(), m_data, m_should_free, malloc(), memcpy(), and width().
PixelBitmap() [5/5]
LG::PixelBitmap::PixelBitmap (PixelBitmap && moved_bitmap) noexcept
Definition at line 46 of file PixelBitmap.cpp.
     : m_data(moved_bitmap.m_data)
     , m_bounds(moved_bitmap.m_bounds)
     , m_should_free(moved_bitmap.m_should_free)
     , m_format(moved_bitmap.m_format)
 {
     moved_bitmap.m_data = nullptr;
     moved_bitmap.bounds().set_width(0);
     moved_bitmap.bounds().set_height(0);
     moved_bitmap.m_should_free = false;
 }
~PixelBitmap()
LG::PixelBitmap::~PixelBitmap () inline
Definition at line 31 of file PixelBitmap.h.
     {
         clear();
     }
References clear().
Member Function Documentation
bounds() [1/2]
LG::Rect& LG::PixelBitmap::bounds () inline
Definition at line 77 of file PixelBitmap.h.
 { return m_bounds; }
References m_bounds.
Referenced by resize(), and WindowManager::update_mouse_position().
bounds() [2/2]
const LG::Rect& LG::PixelBitmap::bounds () const inline
Definition at line 78 of file PixelBitmap.h.
 { return m_bounds; }
References m_bounds.
clear()
void LG::PixelBitmap::clear () inline
Definition at line 36 of file PixelBitmap.h.
     {
         if (m_should_free) {
             delete m_data;
         }
         m_data = nullptr;
         m_bounds.set_width(0);
         m_bounds.set_height(0);
     }
References m_bounds, m_data, m_should_free, LG::Rect::set_height(), and LG::Rect::set_width().
Referenced by operator=(), resize(), and ~PixelBitmap().
data()
Color* LG::PixelBitmap::data () const inline
Definition at line 79 of file PixelBitmap.h.
 { return m_data; }
References m_data.
format()
PixelBitmapFormat LG::PixelBitmap::format () const inline
Definition at line 87 of file PixelBitmap.h.
 { return m_format; }
References m_format.
Referenced by set_format().
has_alpha_channel()
bool LG::PixelBitmap::has_alpha_channel () const inline
Definition at line 88 of file PixelBitmap.h.
 { return m_format == RGBA; }
References m_format, and LG::RGBA.
height()
size_t LG::PixelBitmap::height () const inline
Definition at line 76 of file PixelBitmap.h.
 { return m_bounds.height(); }
References LG::Rect::height(), and m_bounds.
Referenced by operator=(), PixelBitmap(), and resize().
line() [1/2]
Color* LG::PixelBitmap::line (size_t i) inline
Definition at line 80 of file PixelBitmap.h.
 { return m_data + i * width(); }
References m_data, and width().
Referenced by operator[]().
line() [2/2]
const Color* LG::PixelBitmap::line (size_t i) const inline
Definition at line 81 of file PixelBitmap.h.
 { return m_data + i * width(); }
References m_data, and width().
operator=() [1/2]
PixelBitmap& LG::PixelBitmap::operator= (PixelBitmap && moved_bitmap) inline noexcept
Definition at line 62 of file PixelBitmap.h.
     {
         m_data = moved_bitmap.m_data;
         m_bounds = moved_bitmap.bounds();
         m_should_free = moved_bitmap.m_should_free;
         m_format = moved_bitmap.m_format;
         moved_bitmap.m_data = nullptr;
         moved_bitmap.bounds().set_width(0);
         moved_bitmap.bounds().set_height(0);
         moved_bitmap.m_should_free = false;
         return *this;
     }
References m_bounds, m_data, m_format, and m_should_free.
operator=() [2/2]
PixelBitmap& LG::PixelBitmap::operator= (PixelBitmap & bitmap) inline
Definition at line 46 of file PixelBitmap.h.
     {
         clear();
         m_bounds = bitmap.bounds();
         m_should_free = bitmap.m_should_free;
         m_format = bitmap.m_format;
         if (m_should_free) {
             size_t len = width() * height() * sizeof(Color);
             m_data = (Color*)malloc(len);
             memcpy((uint8_t*)m_data, (uint8_t*)bitmap.m_data, len);
         } else {
             m_data = bitmap.m_data;
         }
         return *this;
     }
References clear(), height(), m_bounds, m_data, m_format, m_should_free, malloc(), memcpy(), and width().
operator[]() [1/2]
Color* LG::PixelBitmap::operator[] (size_t i) inline
Definition at line 82 of file PixelBitmap.h.
 { return line(i); }
References line().
operator[]() [2/2]
const Color* LG::PixelBitmap::operator[] (size_t i) const inline
Definition at line 83 of file PixelBitmap.h.
 { return line(i); }
References line().
resize()
void LG::PixelBitmap::resize (size_t width, size_t height)
Definition at line 58 of file PixelBitmap.cpp.
 {
     clear();
     bounds().set_width(width);
     bounds().set_height(height);
     m_data = (Color*)malloc(sizeof(Color) * width * height);
     m_should_free = true;
 }
References bounds(), clear(), height(), m_data, m_should_free, malloc(), LG::Rect::set_height(), LG::Rect::set_width(), and width().
set_format()
void LG::PixelBitmap::set_format (PixelBitmapFormat format) inline
Definition at line 86 of file PixelBitmap.h.
 { m_format = format; }
References format(), and m_format.
Referenced by UI::Window::set_bitmap_format().
width()
size_t LG::PixelBitmap::width () const inline
Definition at line 75 of file PixelBitmap.h.
 { return m_bounds.width(); }
References m_bounds, and LG::Rect::width().
Referenced by line(), operator=(), PixelBitmap(), and resize().
Field Documentation
m_bounds
LG::Rect LG::PixelBitmap::m_bounds { 0, 0, 0, 0 } private
Definition at line 92 of file PixelBitmap.h.
Referenced by bounds(), clear(), height(), operator=(), and width().
m_data
Color* LG::PixelBitmap::m_data { nullptr } private
Definition at line 91 of file PixelBitmap.h.
Referenced by clear(), data(), line(), operator=(), PixelBitmap(), and resize().
m_format
PixelBitmapFormat LG::PixelBitmap::m_format { RGB } private
Definition at line 94 of file PixelBitmap.h.
Referenced by format(), has_alpha_channel(), operator=(), and set_format().
m_should_free
bool LG::PixelBitmap::m_should_free { false } private
Definition at line 93 of file PixelBitmap.h.
Referenced by clear(), operator=(), PixelBitmap(), and resize().
The documentation for this class was generated from the following files:
libs/libg/PixelBitmap.h
libs/libg/PixelBitmap.cpp