oneOS: Button Class Reference
Button Class Reference
#include <Button.h>
Public Member Functions
Button ()=default
~Button ()
void display ()
void set_title (const String &title)
void set_title (String &&title)
const String & title () const
void set_font (const LG::Font &font)
void set_icon (const LG::GlyphBitmap &icon)
void set_title_color (const LG::Color &color)
const LG::Color & title_color () const
const LG::Font & font () const
LG::Rect & bounds ()
const LG::Rect & bounds () const
void display (LG::Context &ctx, LG::Point< int > pt)
Private Member Functions
void recalc_dims ()
size_t text_width ()
size_t text_height ()
Private Attributes
LG::Rect m_bounds {}
String m_title {}
LG::Font m_font { LG::Font::system_font() }
LG::Color m_title_color
LG::GlyphBitmap m_icon
bool m_is_icon_set { false }
Detailed Description
Definition at line 15 of file Button.h.
Constructor & Destructor Documentation
Button()
Button::Button () default
~Button()
Button::~Button () inline
Definition at line 18 of file Button.h.
 { }
Member Function Documentation
bounds() [1/2]
LG::Rect& Button::bounds () inline
Definition at line 33 of file Button.h.
 { return m_bounds; }
References m_bounds.
Referenced by recalc_dims().
bounds() [2/2]
const LG::Rect& Button::bounds () const inline
Definition at line 34 of file Button.h.
 { return m_bounds; }
References m_bounds.
display() [1/2]
void Button::display ()
display() [2/2]
void Button::display (LG::Context & ctx, LG::Point< int > pt)
Definition at line 36 of file Button.cpp.
 {
     if (m_is_icon_set) {
         ctx.draw(pt, m_icon);
         pt.offset_by(m_icon.width() + 4, 0);
     }
     auto& f = font();
     for (int i = 0; i < m_title.size(); i++) {
         ctx.draw(pt, f.glyph_bitmap(m_title[i]));
         pt.offset_by(f.glyph_width(m_title[i]) + 2, 0);
     }
 }
References LG::Context::draw(), font(), m_icon, m_is_icon_set, m_title, LG::Point< T >::offset_by(), Algo::String::size(), and LG::GlyphBitmap::width().
font()
const LG::Font& Button::font () const inline
Definition at line 31 of file Button.h.
 { return m_font; }
References m_font.
Referenced by display(), set_font(), text_height(), and text_width().
recalc_dims()
void Button::recalc_dims () private
Definition at line 11 of file Button.cpp.
 {
     size_t new_width = 0;
     size_t new_height = 0;
     if (m_is_icon_set) {
         new_height = m_icon.height();
         new_width += m_icon.width();
         if (m_title.size()) {
             new_width += 4;
         }
     }
     bounds().set_width(new_width + text_width());
     bounds().set_height(max(new_height, text_height()));
 }
References bounds(), LG::GlyphBitmap::height(), m_icon, m_is_icon_set, m_title, max(), LG::Rect::set_height(), LG::Rect::set_width(), Algo::String::size(), text_height(), text_width(), and LG::GlyphBitmap::width().
Referenced by set_font(), set_icon(), and set_title().
set_font()
void Button::set_font (const LG::Font & font) inline
Definition at line 25 of file Button.h.
 { m_font = font, recalc_dims(); }
References font(), m_font, and recalc_dims().
set_icon()
void Button::set_icon (const LG::GlyphBitmap & icon) inline
Definition at line 26 of file Button.h.
 { m_is_icon_set = true, m_icon = icon, recalc_dims(); }
References m_icon, m_is_icon_set, and recalc_dims().
set_title() [1/2]
void Button::set_title (const String & title) inline
Definition at line 21 of file Button.h.
 { m_title = title, recalc_dims(); }
References m_title, recalc_dims(), and title().
set_title() [2/2]
void Button::set_title (String && title) inline
Definition at line 22 of file Button.h.
 { m_title = move(title), recalc_dims(); }
References m_title, move(), recalc_dims(), and title().
set_title_color()
void Button::set_title_color (const LG::Color & color) inline
Definition at line 28 of file Button.h.
 { m_title_color = color; }
References m_title_color.
text_height()
size_t Button::text_height () inline private
Definition at line 41 of file Button.h.
 { return font().glyph_height(); }
References font(), and LG::Font::glyph_height().
Referenced by recalc_dims().
text_width()
size_t Button::text_width () private
Definition at line 26 of file Button.cpp.
 {
     size_t width = 0;
     auto& f = font();
     for (int i = 0; i < m_title.size(); i++) {
         width += f.glyph_width(m_title[i]) + 2; // FIXME
     }
     return width;
 }
References font(), m_title, and Algo::String::size().
Referenced by recalc_dims().
title()
const String& Button::title () const inline
Definition at line 23 of file Button.h.
 { return m_title; }
References m_title.
Referenced by set_title().
title_color()
const LG::Color& Button::title_color () const inline
Definition at line 29 of file Button.h.
 { return m_title_color; }
References m_title_color.
Field Documentation
m_bounds
LG::Rect Button::m_bounds {} private
Definition at line 43 of file Button.h.
Referenced by bounds().
m_font
LG::Font Button::m_font { LG::Font::system_font() } private
Definition at line 45 of file Button.h.
Referenced by font(), and set_font().
m_icon
LG::GlyphBitmap Button::m_icon private
Definition at line 47 of file Button.h.
Referenced by display(), recalc_dims(), and set_icon().
m_is_icon_set
bool Button::m_is_icon_set { false } private
Definition at line 49 of file Button.h.
Referenced by display(), recalc_dims(), and set_icon().
m_title
String Button::m_title {} private
Definition at line 44 of file Button.h.
Referenced by display(), recalc_dims(), set_title(), text_width(), and title().
m_title_color
LG::Color Button::m_title_color private
Definition at line 46 of file Button.h.
Referenced by set_title_color(), and title_color().
The documentation for this class was generated from the following files:
servers/window_server/Button.h
servers/window_server/Button.cpp