oneOS: MouseLeaveMessage Class Reference
MouseLeaveMessage Class Reference
#include <WSConnection.h>
Public Member Functions
MouseLeaveMessage (message_key_t key, int win_id, uint32_t x, uint32_t y)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
int win_id () const
uint32_t x () const
uint32_t y () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
int m_win_id
uint32_t m_x
uint32_t m_y
Detailed Description
Definition at line 530 of file WSConnection.h.
Constructor & Destructor Documentation
MouseLeaveMessage()
MouseLeaveMessage::MouseLeaveMessage (message_key_t key, int win_id, uint32_t x, uint32_t y) inline
Definition at line 532 of file WSConnection.h.
         : m_key(key)
         , m_win_id(win_id)
         , m_x(x)
         , m_y(y)
     {
     }
Member Function Documentation
decoder_magic()
int MouseLeaveMessage::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 542 of file WSConnection.h.
 { return 737; }
Referenced by encode().
encode()
EncodedMessage MouseLeaveMessage::encode () const inline override virtual
Reimplemented from Message.
Definition at line 546 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_win_id);
         Encoder::append(buffer, m_x);
         Encoder::append(buffer, m_y);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), m_win_id, m_x, and m_y.
id()
int MouseLeaveMessage::id () const inline override virtual
Reimplemented from Message.
Definition at line 539 of file WSConnection.h.
 { return 3; }
key()
int MouseLeaveMessage::key () const inline override virtual
Reimplemented from Message.
Definition at line 541 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode().
reply_id()
int MouseLeaveMessage::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 540 of file WSConnection.h.
 { return -1; }
win_id()
int MouseLeaveMessage::win_id () const inline
Definition at line 543 of file WSConnection.h.
 { return m_win_id; }
References m_win_id.
Referenced by UI::ClientDecoder::handle().
x()
uint32_t MouseLeaveMessage::x () const inline
Definition at line 544 of file WSConnection.h.
 { return m_x; }
References m_x.
Referenced by UI::ClientDecoder::handle().
y()
uint32_t MouseLeaveMessage::y () const inline
Definition at line 545 of file WSConnection.h.
 { return m_y; }
References m_y.
Referenced by UI::ClientDecoder::handle().
Field Documentation
m_key
message_key_t MouseLeaveMessage::m_key private
Definition at line 558 of file WSConnection.h.
Referenced by key().
m_win_id
int MouseLeaveMessage::m_win_id private
Definition at line 559 of file WSConnection.h.
Referenced by encode(), and win_id().
m_x
uint32_t MouseLeaveMessage::m_x private
Definition at line 560 of file WSConnection.h.
Referenced by encode(), and x().
m_y
uint32_t MouseLeaveMessage::m_y private
Definition at line 561 of file WSConnection.h.
Referenced by encode(), and y().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h