oneOS: Algo::Vector< T > Class Template Reference
Algo::Vector< T > Class Template Reference
#include <Vector.h>
Public Types
typedef T * iterator
Public Member Functions
Vector ()
Vector (int capacity)
Vector (const Vector &v)
Vector (Vector &&v)
~Vector ()
Vector & operator= (const Vector &v)
Vector & operator= (Vector &&v)
void push_back (T &&el)
void push_back (const T &el)
const T & at (size_t i) const
T & at (size_t i)
void clear ()
void clear_remain_capacity ()
void resize (size_t new_size)
size_t size () const
const T & operator[] (size_t i) const
T & operator[] (size_t i)
const T & back () const
T & back ()
T * data ()
const T * data () const
Private Member Functions
void ensure_capacity (size_t new_size)
void grow (size_t capacity)
void copy (T *to, T *from, size_t len)
T * end ()
Private Attributes
size_t m_size { 0 }
size_t m_capacity { 16 }
T * m_data { nullptr }
Detailed Description
template<class T>
class Algo::Vector< T >
Definition at line 8 of file Vector.h.
Member Typedef Documentation
iterator
template<class T > typedef T* Algo::Vector< T >::iterator
Definition at line 10 of file Vector.h.
Constructor & Destructor Documentation
Vector() [1/4]
template<class T > Algo::Vector< T >::Vector () inline
Definition at line 12 of file Vector.h.
     {
         grow(m_capacity);
     }
References Algo::Vector< T >::grow(), and Algo::Vector< T >::m_capacity.
Vector() [2/4]
template<class T > Algo::Vector< T >::Vector (int capacity) inline
Definition at line 17 of file Vector.h.
     {
         grow(capacity);
     }
References Algo::Vector< T >::grow().
Vector() [3/4]
template<class T > Algo::Vector< T >::Vector (const Vector< T > & v) inline
Definition at line 22 of file Vector.h.
     {
         grow(v.m_capacity);
         m_size = v.m_size;
         copy(m_data, v.m_data, m_size);
     }
References Algo::Vector< T >::copy(), Algo::Vector< T >::grow(), Algo::Vector< T >::m_capacity, Algo::Vector< T >::m_data, and Algo::Vector< T >::m_size.
Vector() [4/4]
template<class T > Algo::Vector< T >::Vector (Vector< T > && v) inline
Definition at line 29 of file Vector.h.
     {
         m_size = v.m_size;
         m_capacity = v.m_capacity;
         m_data = v.m_data;
         v.m_size = v.m_capacity = 0;
         v.m_data = nullptr;
     }
References Algo::Vector< T >::m_capacity, Algo::Vector< T >::m_data, and Algo::Vector< T >::m_size.
~Vector()
template<class T > Algo::Vector< T >::~Vector () inline
Definition at line 38 of file Vector.h.
     {
         clear();
     }
References Algo::Vector< T >::clear().
Member Function Documentation
at() [1/2]
template<class T > T& Algo::Vector< T >::at (size_t i) inline
Definition at line 82 of file Vector.h.
     {
         return data()[i];
     }
References Algo::Vector< T >::data().
at() [2/2]
template<class T > const T& Algo::Vector< T >::at (size_t i) const inline
Definition at line 77 of file Vector.h.
     {
         return data()[i];
     }
References Algo::Vector< T >::data().
Referenced by Algo::Vector< T >::back(), Algo::Vector< T >::grow(), and Algo::Vector< T >::operator[]().
back() [1/2]
template<class T > T& Algo::Vector< T >::back () inline
Definition at line 116 of file Vector.h.
 { return at(size() - 1); }
References Algo::Vector< T >::at(), and Algo::Vector< T >::size().
back() [2/2]
template<class T > const T& Algo::Vector< T >::back () const inline
Definition at line 115 of file Vector.h.
 { return at(size() - 1); }
References Algo::Vector< T >::at(), and Algo::Vector< T >::size().
clear()
template<class T > void Algo::Vector< T >::clear () inline
Definition at line 87 of file Vector.h.
     {
         clear_remain_capacity();
         if (m_data) {
             free(m_data);
             m_data = nullptr;
         }
     }
References Algo::Vector< T >::clear_remain_capacity(), free(), and Algo::Vector< T >::m_data.
Referenced by Algo::Vector< T >::operator=(), and Algo::Vector< T >::~Vector().
clear_remain_capacity()
template<class T > void Algo::Vector< T >::clear_remain_capacity () inline
Definition at line 96 of file Vector.h.
     {
         for (size_t i = 0; i < m_size; ++i) {
             data()[i].~T();
         }
         m_size = 0;
     }
References Algo::Vector< T >::data(), and Algo::Vector< T >::m_size.
Referenced by Algo::Vector< T >::clear().
copy()
template<class T > void Algo::Vector< T >::copy (T * to, T * from, size_t len) inline private
Definition at line 148 of file Vector.h.
     {
         for (size_t i = 0; i < len; i++) {
             new (to) T(*from);
             to++;
             from++;
         }
     }
Referenced by Algo::Vector< T >::operator=(), and Algo::Vector< T >::Vector().
data() [1/2]
template<class T > T* Algo::Vector< T >::data () inline
Definition at line 118 of file Vector.h.
 { return m_data; }
References Algo::Vector< T >::m_data.
Referenced by Algo::Vector< T >::at(), and Algo::Vector< T >::clear_remain_capacity().
data() [2/2]
template<class T > const T* Algo::Vector< T >::data () const inline
Definition at line 119 of file Vector.h.
 { return m_data; }
References Algo::Vector< T >::m_data.
end()
template<class T > T* Algo::Vector< T >::end () inline private
Definition at line 157 of file Vector.h.
 { return m_data + m_size; }
References Algo::Vector< T >::m_data, and Algo::Vector< T >::m_size.
Referenced by Algo::Vector< T >::push_back().
ensure_capacity()
template<class T > void Algo::Vector< T >::ensure_capacity (size_t new_size) inline private
Definition at line 122 of file Vector.h.
     {
         int capacity = 16;
         while (new_size > capacity) {
             capacity *= 2;
         }
         grow(capacity);
     }
References Algo::Vector< T >::grow().
Referenced by Algo::Vector< T >::push_back(), and Algo::Vector< T >::resize().
grow()
template<class T > void Algo::Vector< T >::grow (size_t capacity) inline private
Definition at line 131 of file Vector.h.
     {
         if (!m_data) {
             m_data = (T*)malloc(capacity * sizeof(T));
         } else {
             auto new_buf = (T*)malloc(capacity * sizeof(T));
             for (size_t i = 0; i < m_size; i++) {
                 new (&new_buf[i]) T(move(at(i)));
                 at(i).~T();
             }
             free(m_data);
             m_data = new_buf;
         }
         m_capacity = capacity;
     }
References Algo::Vector< T >::at(), free(), Algo::Vector< T >::m_capacity, Algo::Vector< T >::m_data, Algo::Vector< T >::m_size, malloc(), and move().
Referenced by Algo::Vector< T >::ensure_capacity(), Algo::Vector< T >::operator=(), and Algo::Vector< T >::Vector().
operator=() [1/2]
template<class T > Vector& Algo::Vector< T >::operator= (const Vector< T > & v) inline
Definition at line 43 of file Vector.h.
     {
         grow(v.m_capacity);
         m_size = v.m_size;
         copy(m_data, v.m_data, m_size);
         return *this;
     }
References Algo::Vector< T >::copy(), Algo::Vector< T >::grow(), Algo::Vector< T >::m_capacity, Algo::Vector< T >::m_data, and Algo::Vector< T >::m_size.
operator=() [2/2]
template<class T > Vector& Algo::Vector< T >::operator= (Vector< T > && v) inline
Definition at line 51 of file Vector.h.
     {
         if (this != &v) {
             clear();
             m_size = v.m_size;
             m_capacity = v.m_capacity;
             m_data = v.m_data;
             v.m_size = 0;
             v.m_capacity = 0;
             v.m_data = nullptr;
         }
         return *this;
     }
References Algo::Vector< T >::clear(), Algo::Vector< T >::m_capacity, Algo::Vector< T >::m_data, and Algo::Vector< T >::m_size.
operator[]() [1/2]
template<class T > T& Algo::Vector< T >::operator[] (size_t i) inline
Definition at line 113 of file Vector.h.
 { return at(i); }
References Algo::Vector< T >::at().
operator[]() [2/2]
template<class T > const T& Algo::Vector< T >::operator[] (size_t i) const inline
Definition at line 112 of file Vector.h.
 { return at(i); }
References Algo::Vector< T >::at().
push_back() [1/2]
template<class T > void Algo::Vector< T >::push_back (const T & el) inline
Definition at line 72 of file Vector.h.
     {
         push_back(T(el));
     }
References Algo::Vector< T >::push_back().
push_back() [2/2]
template<class T > void Algo::Vector< T >::push_back (T && el) inline
Definition at line 65 of file Vector.h.
     {
         ensure_capacity(size() + 1);
         new (end()) T(move(el));
         m_size++;
     }
References Algo::Vector< T >::end(), Algo::Vector< T >::ensure_capacity(), Algo::Vector< T >::m_size, move(), and Algo::Vector< T >::size().
Referenced by WindowFrame::add_control(), Compositor::optimized_invalidate_insert(), ClientConnection< ServerDecoder, ClientDecoder >::pump_messages(), Algo::Vector< T >::push_back(), WindowFrame::set_app_name(), and WindowFrame::WindowFrame().
resize()
template<class T > void Algo::Vector< T >::resize (size_t new_size) inline
Definition at line 104 of file Vector.h.
     {
         ensure_capacity(new_size);
         m_size = new_size;
     }
References Algo::Vector< T >::ensure_capacity(), and Algo::Vector< T >::m_size.
size()
template<class T > size_t Algo::Vector< T >::size () const inline
Definition at line 110 of file Vector.h.
 { return m_size; }
References Algo::Vector< T >::m_size.
Referenced by __attribute__(), Algo::Vector< T >::back(), Compositor::copy_changes_to_second_buffer(), WindowFrame::draw(), Compositor::optimized_invalidate_insert(), LFoundation::EventLoop::pump(), ClientConnection< ServerDecoder, ClientDecoder >::pump_messages(), Algo::Vector< T >::push_back(), WindowFrame::receive_tap_event(), WindowFrame::set_app_name(), and ClientConnection< ServerDecoder, ClientDecoder >::wait_for_answer().
Field Documentation
m_capacity
template<class T > size_t Algo::Vector< T >::m_capacity { 16 } private
Definition at line 160 of file Vector.h.
Referenced by Algo::Vector< T >::grow(), Algo::Vector< T >::operator=(), and Algo::Vector< T >::Vector().
m_data
template<class T > T* Algo::Vector< T >::m_data { nullptr } private
Definition at line 161 of file Vector.h.
Referenced by Algo::Vector< T >::clear(), Algo::Vector< T >::data(), Algo::Vector< T >::end(), Algo::Vector< T >::grow(), Algo::Vector< T >::operator=(), and Algo::Vector< T >::Vector().
m_size
template<class T > size_t Algo::Vector< T >::m_size { 0 } private
Definition at line 159 of file Vector.h.
Referenced by Algo::Vector< T >::clear_remain_capacity(), Algo::Vector< T >::end(), Algo::Vector< T >::grow(), Algo::Vector< T >::operator=(), Algo::Vector< T >::push_back(), Algo::Vector< T >::resize(), Algo::Vector< T >::size(), and Algo::Vector< T >::Vector().
The documentation for this class was generated from the following file:
libs/libcxx/std/Vector.h