oneOS: CursorManager Class Reference
CursorManager Class Reference
#include <CursorManager.h>
Public Member Functions
CursorManager ()
const LG::PixelBitmap & current_cursor () const
const LG::PixelBitmap & std_cursor () const
LG::Point< int > draw_position (int mouse_x, int mouse_y)
Static Public Member Functions
static CursorManager & the ()
Private Attributes
LG::PixelBitmap m_std_cursor
Detailed Description
Definition at line 13 of file CursorManager.h.
Constructor & Destructor Documentation
CursorManager()
CursorManager::CursorManager ()
Definition at line 20 of file CursorManager.cpp.
 {
     s_the = this;
     LG::PNG::PNGLoader loader;
     m_std_cursor = loader.load_from_file("/res/arrow.png");
 }
References LG::PNG::PNGLoader::load_from_file(), m_std_cursor, and s_the.
Member Function Documentation
current_cursor()
const LG::PixelBitmap& CursorManager::current_cursor () const inline
Definition at line 18 of file CursorManager.h.
 { return std_cursor(); }
References std_cursor().
Referenced by __attribute__(), and WindowManager::update_mouse_position().
draw_position()
LG::Point<int> CursorManager::draw_position (int mouse_x, int mouse_y) inline
Definition at line 20 of file CursorManager.h.
 { return { mouse_x - 2, mouse_y - 2 }; }
Referenced by __attribute__(), and WindowManager::update_mouse_position().
std_cursor()
const LG::PixelBitmap& CursorManager::std_cursor () const inline
Definition at line 19 of file CursorManager.h.
 { return m_std_cursor; }
References m_std_cursor.
Referenced by current_cursor().
the()
CursorManager & CursorManager::the () static
Definition at line 15 of file CursorManager.cpp.
 {
     return *s_the;
 }
References s_the.
Field Documentation
m_std_cursor
LG::PixelBitmap CursorManager::m_std_cursor private
Definition at line 23 of file CursorManager.h.
Referenced by CursorManager(), and std_cursor().
The documentation for this class was generated from the following files:
servers/window_server/CursorManager.h
servers/window_server/CursorManager.cpp