oneOS: DockEntity Class Reference
DockEntity Class Reference
#include <DockEntity.h>
Public Member Functions
DockEntity ()=default
DockEntity (int window_id)
int window_id () const
void set_icon (LG::PixelBitmap &&icon)
const LG::PixelBitmap & icon () const
Public Member Functions inherited from Algo::LinkedListNode< DockEntity >
LinkedListNode ()=default
DockEntity * next () const
DockEntity * prev () const
void set_prev (DockEntity *prev)
void set_next (DockEntity *next)
Private Attributes
int m_window_id { 0 }
LG::PixelBitmap m_icon
int m_window_status { 0 }
Detailed Description
Definition at line 5 of file DockEntity.h.
Constructor & Destructor Documentation
DockEntity() [1/2]
DockEntity::DockEntity () default
DockEntity() [2/2]
DockEntity::DockEntity (int window_id) inline
Definition at line 9 of file DockEntity.h.
         : m_window_id(window_id)
     {
     }
Member Function Documentation
icon()
const LG::PixelBitmap& DockEntity::icon () const inline
Definition at line 16 of file DockEntity.h.
 { return m_icon; }
References m_icon.
Referenced by set_icon().
set_icon()
void DockEntity::set_icon (LG::PixelBitmap && icon) inline
Definition at line 15 of file DockEntity.h.
 { m_icon = move(icon); }
References icon(), m_icon, and move().
window_id()
int DockEntity::window_id () const inline
Definition at line 14 of file DockEntity.h.
 { return m_window_id; }
References m_window_id.
Field Documentation
m_icon
LG::PixelBitmap DockEntity::m_icon private
Definition at line 20 of file DockEntity.h.
Referenced by icon(), and set_icon().
m_window_id
int DockEntity::m_window_id { 0 } private
Definition at line 19 of file DockEntity.h.
Referenced by window_id().
m_window_status
int DockEntity::m_window_status { 0 } private
Definition at line 21 of file DockEntity.h.
The documentation for this class was generated from the following file:
userland/dock/DockEntity.h