oneOS: UI::MouseActionEvent Class Reference
UI::MouseActionEvent Class Reference
#include <Event.h>
Public Member Functions
MouseActionEvent (MouseActionType type, uint32_t x, uint32_t y)
~MouseActionEvent ()
MouseActionType type () const
uint32_t x () const
uint32_t y () const
Public Member Functions inherited from UI::Event
Event (int type)
~Event ()
Public Member Functions inherited from LFoundation::Event
Event (int type)
~Event ()
int type ()
Private Attributes
MouseActionType m_type
uint32_t m_x
uint32_t m_y
Additional Inherited Members
Public Types inherited from UI::Event
enum Type {
Invalid = 0x2000 , MouseEvent , MouseActionEvent , MouseLeaveEvent ,
KeyUpEvent , KeyDownEvent , DisplayEvent , WindowCloseRequestEvent ,
NotifyWindowStatusChangedEvent , NotifyWindowIconChangedEvent , Other
}
Public Types inherited from LFoundation::Event
enum Type {
Invalid = 0 , FdWaiterRead , FdWaiterWrite , DeferredInvoke ,
Other
}
Detailed Description
Definition at line 67 of file Event.h.
Constructor & Destructor Documentation
MouseActionEvent()
UI::MouseActionEvent::MouseActionEvent (MouseActionType type, uint32_t x, uint32_t y) inline
Definition at line 69 of file Event.h.
         : Event(Event::Type::MouseActionEvent)
         , m_type(type)
         , m_x(x)
         , m_y(y)
     {
     }
~MouseActionEvent()
UI::MouseActionEvent::~MouseActionEvent () inline
Definition at line 77 of file Event.h.
 { }
Member Function Documentation
type()
MouseActionType UI::MouseActionEvent::type () const inline
Definition at line 79 of file Event.h.
 { return m_type; }
References m_type.
Referenced by token.Token::__str__(), and UI::View::receive_mouse_action_event().
x()
uint32_t UI::MouseActionEvent::x () const inline
Definition at line 80 of file Event.h.
 { return m_x; }
References m_x.
Referenced by UI::Window::receive_event(), and UI::View::receive_mouse_action_event().
y()
uint32_t UI::MouseActionEvent::y () const inline
Definition at line 81 of file Event.h.
 { return m_y; }
References m_y.
Referenced by UI::Window::receive_event(), and UI::View::receive_mouse_action_event().
Field Documentation
m_type
MouseActionType UI::MouseActionEvent::m_type private
Definition at line 84 of file Event.h.
Referenced by type().
m_x
uint32_t UI::MouseActionEvent::m_x private
Definition at line 85 of file Event.h.
Referenced by x().
m_y
uint32_t UI::MouseActionEvent::m_y private
Definition at line 86 of file Event.h.
Referenced by y().
The documentation for this class was generated from the following file:
libs/libui/Event.h