oneOS: WindowServerDecoder Class Reference
WindowServerDecoder Class Reference
#include <WSConnection.h>
Public Member Functions
WindowServerDecoder ()
int magic () const
UniquePtr< Message > decode (const char *buf, size_t size, size_t &decoded_msg_len) override
UniquePtr< Message > handle (const Message &msg) override
virtual UniquePtr< Message > handle (const GreetMessage &msg)
virtual UniquePtr< Message > handle (const CreateWindowMessage &msg)
virtual UniquePtr< Message > handle (const DestroyWindowMessage &msg)
virtual UniquePtr< Message > handle (const SetBufferMessage &msg)
virtual UniquePtr< Message > handle (const SetBarStyleMessage &msg)
virtual UniquePtr< Message > handle (const SetTitleMessage &msg)
virtual UniquePtr< Message > handle (const InvalidateMessage &msg)
virtual UniquePtr< Message > handle (const AskBringToFrontMessage &msg)
Public Member Functions inherited from MessageDecoder
MessageDecoder ()
virtual ~MessageDecoder ()
virtual int magic ()
Detailed Description
Definition at line 338 of file WSConnection.h.
Constructor & Destructor Documentation
WindowServerDecoder()
WindowServerDecoder::WindowServerDecoder () inline
Definition at line 340 of file WSConnection.h.
 {}
Member Function Documentation
decode()
UniquePtr<Message> WindowServerDecoder::decode (const char * buf, size_t size, size_t & decoded_msg_len) inline override virtual
Reimplemented from MessageDecoder.
Definition at line 342 of file WSConnection.h.
     {
         int msg_id, decoder_magic;
         size_t saved_dml = decoded_msg_len;
         Encoder::decode(buf, decoded_msg_len, decoder_magic);
         Encoder::decode(buf, decoded_msg_len, msg_id);
         if (magic() != decoder_magic) {
             decoded_msg_len = saved_dml;
             return nullptr;
         }
         message_key_t secret_key;
         Encoder::decode(buf, decoded_msg_len, secret_key);
         uint32_t var_connection_id;
         int var_type;
         uint32_t var_width;
         uint32_t var_height;
         int var_buffer_id;
         LG::String var_icon_path;
         uint32_t var_window_id;
         uint32_t var_status;
         int var_format;
         uint32_t var_color;
         int var_text_style;
         LG::String var_title;
         LG::Rect var_rect;
         uint32_t var_target_window_id;
         switch(msg_id) {
         case 1:
             return new GreetMessage(secret_key);
         case 2:
             Encoder::decode(buf, decoded_msg_len, var_connection_id);
             return new GreetMessageReply(secret_key, var_connection_id);
         case 3:
             Encoder::decode(buf, decoded_msg_len, var_type);
             Encoder::decode(buf, decoded_msg_len, var_width);
             Encoder::decode(buf, decoded_msg_len, var_height);
             Encoder::decode(buf, decoded_msg_len, var_buffer_id);
             Encoder::decode(buf, decoded_msg_len, var_icon_path);
             return new CreateWindowMessage(secret_key, var_type, var_width, var_height, var_buffer_id, var_icon_path);
         case 4:
             Encoder::decode(buf, decoded_msg_len, var_window_id);
             return new CreateWindowMessageReply(secret_key, var_window_id);
         case 5:
             Encoder::decode(buf, decoded_msg_len, var_window_id);
             return new DestroyWindowMessage(secret_key, var_window_id);
         case 6:
             Encoder::decode(buf, decoded_msg_len, var_status);
             return new DestroyWindowMessageReply(secret_key, var_status);
         case 7:
             Encoder::decode(buf, decoded_msg_len, var_window_id);
             Encoder::decode(buf, decoded_msg_len, var_buffer_id);
             Encoder::decode(buf, decoded_msg_len, var_format);
             return new SetBufferMessage(secret_key, var_window_id, var_buffer_id, var_format);
         case 8:
             Encoder::decode(buf, decoded_msg_len, var_window_id);
             Encoder::decode(buf, decoded_msg_len, var_color);
             Encoder::decode(buf, decoded_msg_len, var_text_style);
             return new SetBarStyleMessage(secret_key, var_window_id, var_color, var_text_style);
         case 9:
             Encoder::decode(buf, decoded_msg_len, var_window_id);
             Encoder::decode(buf, decoded_msg_len, var_title);
             return new SetTitleMessage(secret_key, var_window_id, var_title);
         case 10:
             Encoder::decode(buf, decoded_msg_len, var_window_id);
             Encoder::decode(buf, decoded_msg_len, var_rect);
             return new InvalidateMessage(secret_key, var_window_id, var_rect);
         case 11:
             Encoder::decode(buf, decoded_msg_len, var_window_id);
             Encoder::decode(buf, decoded_msg_len, var_target_window_id);
             return new AskBringToFrontMessage(secret_key, var_window_id, var_target_window_id);
         default:
             decoded_msg_len = saved_dml;
             return nullptr;
         }
     }
References buf, Encoder::decode(), and magic().
handle() [1/9]
virtual UniquePtr<Message> WindowServerDecoder::handle (const AskBringToFrontMessage & msg) inline virtual
Reimplemented in WServerDecoder.
Definition at line 455 of file WSConnection.h.
 { return nullptr; }
handle() [2/9]
virtual UniquePtr<Message> WindowServerDecoder::handle (const CreateWindowMessage & msg) inline virtual
Reimplemented in WServerDecoder.
Definition at line 449 of file WSConnection.h.
 { return nullptr; }
handle() [3/9]
virtual UniquePtr<Message> WindowServerDecoder::handle (const DestroyWindowMessage & msg) inline virtual
Reimplemented in WServerDecoder.
Definition at line 450 of file WSConnection.h.
 { return nullptr; }
handle() [4/9]
virtual UniquePtr<Message> WindowServerDecoder::handle (const GreetMessage & msg) inline virtual
Reimplemented in WServerDecoder.
Definition at line 448 of file WSConnection.h.
 { return nullptr; }
handle() [5/9]
virtual UniquePtr<Message> WindowServerDecoder::handle (const InvalidateMessage & msg) inline virtual
Reimplemented in WServerDecoder.
Definition at line 454 of file WSConnection.h.
 { return nullptr; }
handle() [6/9]
UniquePtr<Message> WindowServerDecoder::handle (const Message & msg) inline override virtual
Reimplemented from MessageDecoder.
Definition at line 420 of file WSConnection.h.
     {
         if (magic() != msg.decoder_magic()) {
             return nullptr;
         }
         switch(msg.id()) {
         case 1:
             return handle(static_cast<const GreetMessage&>(msg));
         case 3:
             return handle(static_cast<const CreateWindowMessage&>(msg));
         case 5:
             return handle(static_cast<const DestroyWindowMessage&>(msg));
         case 7:
             return handle(static_cast<const SetBufferMessage&>(msg));
         case 8:
             return handle(static_cast<const SetBarStyleMessage&>(msg));
         case 9:
             return handle(static_cast<const SetTitleMessage&>(msg));
         case 10:
             return handle(static_cast<const InvalidateMessage&>(msg));
         case 11:
             return handle(static_cast<const AskBringToFrontMessage&>(msg));
         default:
             return nullptr;
         }
     }
References Message::decoder_magic(), Message::id(), and magic().
handle() [7/9]
virtual UniquePtr<Message> WindowServerDecoder::handle (const SetBarStyleMessage & msg) inline virtual
Reimplemented in WServerDecoder.
Definition at line 452 of file WSConnection.h.
 { return nullptr; }
handle() [8/9]
virtual UniquePtr<Message> WindowServerDecoder::handle (const SetBufferMessage & msg) inline virtual
Reimplemented in WServerDecoder.
Definition at line 451 of file WSConnection.h.
 { return nullptr; }
handle() [9/9]
virtual UniquePtr<Message> WindowServerDecoder::handle (const SetTitleMessage & msg) inline virtual
Reimplemented in WServerDecoder.
Definition at line 453 of file WSConnection.h.
 { return nullptr; }
magic()
int WindowServerDecoder::magic () const inline
Definition at line 341 of file WSConnection.h.
 { return 320; }
Referenced by decode(), and handle().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h