oneOS: WindowFrame Class Reference
WindowFrame Class Reference
#include <WindowFrame.h>
Public Member Functions
WindowFrame (Window &window)
WindowFrame (Window &window, Vector< Button * > &&control_panel_buttons, Vector< Button * > &&window_control_buttons)
~WindowFrame ()
void draw (LG::Context &)
constexpr size_t std_top_border_size () const
constexpr size_t std_bottom_border_size () const
constexpr size_t std_left_border_size () const
constexpr size_t std_right_border_size () const
size_t top_border_size () const
size_t bottom_border_size () const
size_t left_border_size () const
size_t right_border_size () const
const LG::Rect bounds () const
void receive_tap_event (const LG::Point< int > &tap)
void set_app_name (const String &title)
void set_app_name (String &&title)
void add_control (const String &title)
Vector< Button * > & window_control_buttons ()
const Vector< Button * > & window_control_buttons () const
Vector< Button * > & control_panel_buttons ()
const Vector< Button * > & control_panel_buttons () const
void handle_control_panel_tap (int button_id)
LG::Color & color ()
const LG::Color & color () const
void set_color (const LG::Color &clr)
void set_visible (bool visible)
bool visible () const
void reload_icon ()
const LG::PixelBitmap & icon () const
Static Public Member Functions
static constexpr int spacing ()
static constexpr int icon_y_offset ()
static constexpr int text_y_offset ()
static constexpr int button_y_offset ()
static constexpr int icon_width ()
Private Member Functions
int draw_text (LG::Context &ctx, LG::Point< int > pt, const char *text, LG::Font &font)
Private Attributes
Window & m_window
Vector< Button * > m_window_control_buttons
Vector< Button * > m_control_panel_buttons
LG::Color m_color { 0x00342d2d }
LG::PixelBitmap m_icon {}
size_t m_top_border_size { std_top_border_size() }
bool m_visible { true }
Detailed Description
Definition at line 18 of file WindowFrame.h.
Constructor & Destructor Documentation
WindowFrame() [1/2]
WindowFrame::WindowFrame (Window & window)
Definition at line 62 of file WindowFrame.cpp.
     : m_window(window)
     , m_window_control_buttons()
     , m_control_panel_buttons()
 {
     auto* close = new Button();
     close->set_icon(LG::GlyphBitmap(s_close_button_glyph_data, 10, 10));
     auto* maximize = new Button();
     maximize->set_icon(LG::GlyphBitmap(s_maximise_button_glyph_data, 10, 10));
     auto* minimize = new Button();
     minimize->set_icon(LG::GlyphBitmap(s_minimise_button_glyph_data, 10, 10));
     m_window_control_buttons.push_back(close);
     m_window_control_buttons.push_back(maximize);
     m_window_control_buttons.push_back(minimize);
 }
References close(), m_window_control_buttons, Algo::Vector< T >::push_back(), s_close_button_glyph_data, s_maximise_button_glyph_data, and s_minimise_button_glyph_data.
WindowFrame() [2/2]
WindowFrame::WindowFrame (Window & window, Vector< Button * > && control_panel_buttons, Vector< Button * > && window_control_buttons)
Definition at line 79 of file WindowFrame.cpp.
     : m_window(window)
     , m_window_control_buttons(move(window_control_buttons))
     , m_control_panel_buttons(move(control_panel_buttons))
 {
 }
~WindowFrame()
WindowFrame::~WindowFrame () inline
Definition at line 22 of file WindowFrame.h.
 { }
Member Function Documentation
add_control()
void WindowFrame::add_control (const String & title)
Definition at line 109 of file WindowFrame.cpp.
 {
     auto* new_control = new Button();
     new_control->set_title(title);
     m_control_panel_buttons.push_back(new_control);
     Compositor::the().invalidate(bounds());
 }
References bounds(), Compositor::invalidate(), m_control_panel_buttons, Algo::Vector< T >::push_back(), and Compositor::the().
bottom_border_size()
size_t WindowFrame::bottom_border_size () const inline
Definition at line 30 of file WindowFrame.h.
 { return std_bottom_border_size(); }
References std_bottom_border_size().
Referenced by draw().
bounds()
const LG::Rect WindowFrame::bounds () const
Definition at line 173 of file WindowFrame.cpp.
 {
     const auto& bounds = m_window.bounds();
     return LG::Rect(bounds.min_x(), bounds.min_y(), bounds.width(), top_border_size());
 }
References Window::bounds(), m_window, LG::Rect::min_x(), LG::Rect::min_y(), top_border_size(), and LG::Rect::width().
Referenced by add_control(), WindowManager::receive_mouse_event(), and set_app_name().
button_y_offset()
static constexpr int WindowFrame::button_y_offset () inline static constexpr
Definition at line 67 of file WindowFrame.h.
 { return 8; }
Referenced by draw(), and receive_tap_event().
color() [1/2]
LG::Color& WindowFrame::color () inline
Definition at line 49 of file WindowFrame.h.
 { return m_color; }
References m_color.
Referenced by draw().
color() [2/2]
const LG::Color& WindowFrame::color () const inline
Definition at line 50 of file WindowFrame.h.
 { return m_color; }
References m_color.
control_panel_buttons() [1/2]
Vector<Button*>& WindowFrame::control_panel_buttons () inline
Definition at line 45 of file WindowFrame.h.
 { return m_control_panel_buttons; }
References m_control_panel_buttons.
control_panel_buttons() [2/2]
const Vector<Button*>& WindowFrame::control_panel_buttons () const inline
Definition at line 46 of file WindowFrame.h.
 { return m_control_panel_buttons; }
References m_control_panel_buttons.
draw()
void WindowFrame::draw (LG::Context & ctx)
Definition at line 117 of file WindowFrame.cpp.
 {
     if (!visible()) {
         return;
     }
     int x = m_window.bounds().min_x();
     int y = m_window.bounds().min_y();
     size_t width = m_window.bounds().width();
     size_t height = m_window.bounds().height();
     int right_x = x + width - right_border_size();
     int bottom_y = y + height - bottom_border_size();
     // Drawing frame
     ctx.set_fill_color(color());
     ctx.fill(LG::Rect(x, y, width, top_border_size()));
     ctx.fill(LG::Rect(x, y, left_border_size(), height));
     ctx.fill(LG::Rect(right_x, y, right_border_size(), height));
     ctx.fill(LG::Rect(x, bottom_y, width, bottom_border_size()));
     // Drawing labels, icons.
     // Drawing positions are calculated using a start of the frame.
     ctx.set_fill_color(LG::Color::White);
     ctx.draw({ x + spacing(), y + icon_y_offset() }, icon());
     constexpr int start_controls_offset = icon_width() + 2 * spacing();
     int start_controls = x + start_controls_offset;
     for (int i = 0; i < m_control_panel_buttons.size(); i++) {
         m_control_panel_buttons[i]->display(ctx, { start_controls, y + text_y_offset() });
         start_controls += spacing() + m_control_panel_buttons[i]->bounds().width();
     }
     int start_buttons = right_x - spacing() - m_window_control_buttons[0]->bounds().width();
     for (int i = 0; i < m_window_control_buttons.size(); i++) {
         m_window_control_buttons[i]->display(ctx, { start_buttons, y + button_y_offset() });
         start_buttons += -spacing() - m_window_control_buttons[i]->bounds().width();
     }
 }
References bottom_border_size(), Window::bounds(), button_y_offset(), color(), LG::Context::draw(), LG::Context::fill(), LG::Rect::height(), icon(), icon_width(), icon_y_offset(), left_border_size(), m_control_panel_buttons, m_window, m_window_control_buttons, LG::Rect::min_x(), LG::Rect::min_y(), right_border_size(), LG::Context::set_fill_color(), Algo::Vector< T >::size(), spacing(), text_y_offset(), top_border_size(), visible(), LG::Color::White, and LG::Rect::width().
Referenced by __attribute__().
draw_text()
int WindowFrame::draw_text (LG::Context & ctx, LG::Point< int > pt, const char * text, LG::Font & font) private
handle_control_panel_tap()
void WindowFrame::handle_control_panel_tap (int button_id)
Definition at line 179 of file WindowFrame.cpp.
 {
     auto& wm = WindowManager::the();
     switch (button_id) {
     case CONTROL_PANEL_CLOSE:
         wm.close_window(m_window);
         break;
     default:
         break;
     }
 }
References CONTROL_PANEL_CLOSE, m_window, and WindowManager::the().
Referenced by receive_tap_event().
icon()
const LG::PixelBitmap& WindowFrame::icon () const inline
Definition at line 62 of file WindowFrame.h.
 { return m_icon; }
References m_icon.
Referenced by draw().
icon_width()
static constexpr int WindowFrame::icon_width () inline static constexpr
Definition at line 68 of file WindowFrame.h.
 { return 12; }
Referenced by draw().
icon_y_offset()
static constexpr int WindowFrame::icon_y_offset () inline static constexpr
Definition at line 65 of file WindowFrame.h.
 { return 7; }
Referenced by draw().
left_border_size()
size_t WindowFrame::left_border_size () const inline
Definition at line 31 of file WindowFrame.h.
 { return std_left_border_size(); }
References std_left_border_size().
Referenced by draw(), Window::make_frame(), and Window::Window().
receive_tap_event()
void WindowFrame::receive_tap_event (const LG::Point< int > & tap)
Definition at line 156 of file WindowFrame.cpp.
 {
     // Calculating buttons' positions
     size_t width = m_window.bounds().width();
     int right_x = width - right_border_size();
     int start_buttons = right_x - spacing() - m_window_control_buttons[0]->bounds().width();
     for (int button_id = 0; button_id < m_window_control_buttons.size(); button_id++) {
         auto button_frame = m_window_control_buttons[button_id]->bounds();
         button_frame.offset_by(start_buttons, button_y_offset());
         if (button_frame.contains(tap)) {
             handle_control_panel_tap(button_id);
             return;
         }
         start_buttons += -spacing() - button_frame.width();
     }
 }
References Window::bounds(), button_y_offset(), handle_control_panel_tap(), m_window, m_window_control_buttons, right_border_size(), Algo::Vector< T >::size(), spacing(), and LG::Rect::width().
Referenced by WindowManager::receive_mouse_event().
reload_icon()
void WindowFrame::reload_icon ()
Definition at line 191 of file WindowFrame.cpp.
 {
     LG::PNG::PNGLoader loader;
     m_icon = loader.load_from_file(m_window.icon_path() + "/12x12.png");
 }
References Window::icon_path(), LG::PNG::PNGLoader::load_from_file(), m_icon, and m_window.
Referenced by Window::set_icon().
right_border_size()
size_t WindowFrame::right_border_size () const inline
Definition at line 32 of file WindowFrame.h.
 { return std_right_border_size(); }
References std_right_border_size().
Referenced by draw(), and receive_tap_event().
set_app_name() [1/2]
void WindowFrame::set_app_name (const String & title)
Definition at line 86 of file WindowFrame.cpp.
 {
     if (m_control_panel_buttons.size() > 0) {
         m_control_panel_buttons[0]->set_title(title);
     } else {
         auto* new_control = new Button();
         new_control->set_title(title);
         m_control_panel_buttons.push_back(new_control);
     }
 }
References m_control_panel_buttons, Algo::Vector< T >::push_back(), and Algo::Vector< T >::size().
set_app_name() [2/2]
void WindowFrame::set_app_name (String && title)
Definition at line 97 of file WindowFrame.cpp.
 {
     if (m_control_panel_buttons.size() > 0) {
         m_control_panel_buttons[0]->set_title(title);
     } else {
         auto* new_control = new Button();
         new_control->set_title(title);
         m_control_panel_buttons.push_back(new_control);
     }
     Compositor::the().invalidate(bounds());
 }
References bounds(), Compositor::invalidate(), m_control_panel_buttons, Algo::Vector< T >::push_back(), Algo::Vector< T >::size(), and Compositor::the().
set_color()
void WindowFrame::set_color (const LG::Color & clr) inline
Definition at line 51 of file WindowFrame.h.
 { m_color = clr; }
References m_color.
set_visible()
void WindowFrame::set_visible (bool visible) inline
Definition at line 53 of file WindowFrame.h.
     {
         m_top_border_size = visible ? std_top_border_size() : 0;
         m_visible = visible;
     }
References m_top_border_size, m_visible, std_top_border_size(), and visible().
Referenced by Window::make_frame(), and Window::make_frameless().
spacing()
static constexpr int WindowFrame::spacing () inline static constexpr
Definition at line 64 of file WindowFrame.h.
 { return 8; }
Referenced by draw(), and receive_tap_event().
std_bottom_border_size()
constexpr size_t WindowFrame::std_bottom_border_size () const inline constexpr
Definition at line 26 of file WindowFrame.h.
 { return 1; }
Referenced by bottom_border_size().
std_left_border_size()
constexpr size_t WindowFrame::std_left_border_size () const inline constexpr
Definition at line 27 of file WindowFrame.h.
 { return 1; }
Referenced by left_border_size().
std_right_border_size()
constexpr size_t WindowFrame::std_right_border_size () const inline constexpr
Definition at line 28 of file WindowFrame.h.
 { return 1; }
Referenced by right_border_size().
std_top_border_size()
constexpr size_t WindowFrame::std_top_border_size () const inline constexpr
Definition at line 25 of file WindowFrame.h.
 { return 26; }
Referenced by set_visible().
text_y_offset()
static constexpr int WindowFrame::text_y_offset () inline static constexpr
Definition at line 66 of file WindowFrame.h.
 { return 9; }
Referenced by draw().
top_border_size()
size_t WindowFrame::top_border_size () const inline
Definition at line 29 of file WindowFrame.h.
 { return m_top_border_size; }
References m_top_border_size.
Referenced by bounds(), draw(), Window::make_frame(), and Window::Window().
visible()
bool WindowFrame::visible () const inline
Definition at line 59 of file WindowFrame.h.
 { return m_visible; }
References m_visible.
Referenced by draw(), and set_visible().
window_control_buttons() [1/2]
Vector<Button*>& WindowFrame::window_control_buttons () inline
Definition at line 42 of file WindowFrame.h.
 { return m_window_control_buttons; }
References m_window_control_buttons.
window_control_buttons() [2/2]
const Vector<Button*>& WindowFrame::window_control_buttons () const inline
Definition at line 43 of file WindowFrame.h.
 { return m_window_control_buttons; }
References m_window_control_buttons.
Field Documentation
m_color
LG::Color WindowFrame::m_color { 0x00342d2d } private
Definition at line 75 of file WindowFrame.h.
Referenced by color(), and set_color().
m_control_panel_buttons
Vector<Button*> WindowFrame::m_control_panel_buttons private
Definition at line 74 of file WindowFrame.h.
Referenced by add_control(), control_panel_buttons(), draw(), and set_app_name().
m_icon
LG::PixelBitmap WindowFrame::m_icon {} private
Definition at line 76 of file WindowFrame.h.
Referenced by icon(), and reload_icon().
m_top_border_size
size_t WindowFrame::m_top_border_size { std_top_border_size() } private
Definition at line 77 of file WindowFrame.h.
Referenced by set_visible(), and top_border_size().
m_visible
bool WindowFrame::m_visible { true } private
Definition at line 78 of file WindowFrame.h.
Referenced by set_visible(), and visible().
m_window
Window& WindowFrame::m_window private
Definition at line 72 of file WindowFrame.h.
Referenced by bounds(), draw(), handle_control_panel_tap(), receive_tap_event(), and reload_icon().
m_window_control_buttons
Vector<Button*> WindowFrame::m_window_control_buttons private
Definition at line 73 of file WindowFrame.h.
Referenced by draw(), receive_tap_event(), window_control_buttons(), and WindowFrame().
The documentation for this class was generated from the following files:
servers/window_server/WindowFrame.h
servers/window_server/WindowFrame.cpp