oneOS: TerminalView Class Reference
TerminalView Class Reference
#include <TerminalView.h>
Public Member Functions
TerminalView (const LG::Rect &, int ptmx)
const LG::Color & font_color () const
const LG::Color & cursor_color () const
const LG::Color & background_color () const
const LG::Font & font () const
int glyph_width () const
int glyph_height () const
LG::Point< int > pos_on_screen () const
int pos_in_data () const
void display (const LG::Rect &rect) override
void receive_keyup_event (UI::KeyUpEvent &) override
void receive_keydown_event (UI::KeyDownEvent &) override
int ptmx () const
constexpr int cursor_width ()
Public Member Functions inherited from UI::View
View (const LG::Rect &)
View (const LG::Rect &, const LG::Color &)
template<class T , class... Args>
T & add_subview (Args &&... args)
void remove_from_superview ()
template<typename Callback >
void foreach_subview (Callback callback) const
View * subview_at (const LG::Point< int > &point) const
View * hit_test (const LG::Point< int > &point)
const LG::Rect & frame () const
const LG::Rect & bounds () const
void set_width (size_t x)
void set_height (size_t x)
LG::Rect frame_in_window ()
Window * window ()
bool has_superview ()
View * superview ()
Vector< View * > & subviews ()
const Vector< View * > & subviews () const
void set_needs_display (const LG::Rect &)
void set_needs_display ()
bool is_hovered () const
void set_focusable (bool val)
bool is_focusable () const
virtual void did_display (const LG::Rect &rect)
virtual void hover_begin (const LG::Point< int > &location)
virtual void hover_end ()
virtual void click_began (const LG::Point< int > &location)
virtual void click_ended ()
virtual void receive_mouse_move_event (MouseEvent &) override
virtual void receive_mouse_action_event (MouseActionEvent &) override
virtual void receive_mouse_leave_event (MouseLeaveEvent &) override
virtual void receive_display_event (DisplayEvent &) override
LG::Color & background_color ()
const LG::Color & background_color () const
virtual void set_background_color (const LG::Color &background_color)
Public Member Functions inherited from UI::Responder
bool send_invalidate_message_to_server (const LG::Rect &rect) const
void send_display_message_to_self (Window &win, const LG::Rect &display_rect)
void receive_event (UniquePtr< LFoundation::Event > event) override
Public Member Functions inherited from LFoundation::EventReceiver
EventReceiver ()
~EventReceiver ()
Private Member Functions
void scroll_line ()
void new_line ()
void increment_counter ()
void decrement_counter ()
void recalc_dimensions (const LG::Rect &)
void put_char (char c)
void push_back_char (char c)
void send_input ()
void will_move_cursor ()
void did_move_cursor ()
Private Attributes
LG::Color m_background_color { 0x292929 }
LG::Color m_font_color { LG::Color::White }
LG::Font * m_font_ptr { LG::Font::load_from_file("/res/LizaRegular8x10.font") }
int m_ptmx { -1 }
String m_input {}
size_t m_max_cols { 0 }
size_t m_max_rows { 0 }
size_t m_col { 0 }
size_t m_row { 0 }
char * m_display_data { nullptr }
Additional Inherited Members
Protected Member Functions inherited from UI::Responder
Responder ()
Protected Attributes inherited from UI::Responder
bool m_display_message_sent { false }
LG::Rect m_prev_display_message {}
Detailed Description
Definition at line 6 of file TerminalView.h.
Constructor & Destructor Documentation
TerminalView()
TerminalView::TerminalView (const LG::Rect & frame, int ptmx)
Definition at line 10 of file TerminalView.cpp.
     : View(frame)
     , m_ptmx(ptmx)
 {
     this_view = this;
     LFoundation::EventLoop::the().add(
         ptmx, [] {
             char text[256];
             int cnt = read(this_view->ptmx(), text, 256);
             for (int i = 0; i < cnt; i++) {
                 this_view->push_back_char(text[i]);
             }
         },
         nullptr);
     recalc_dimensions(frame);
 }
References LFoundation::EventLoop::add(), UI::View::frame(), ptmx(), push_back_char(), read(), recalc_dimensions(), LFoundation::EventLoop::the(), and this_view.
Member Function Documentation
background_color()
const LG::Color& TerminalView::background_color () const inline
Definition at line 12 of file TerminalView.h.
 { return m_background_color; }
References m_background_color.
Referenced by display().
cursor_color()
const LG::Color& TerminalView::cursor_color () const inline
Definition at line 11 of file TerminalView.h.
 { return LG::Color(200, 200, 200, 255); }
Referenced by display().
cursor_width()
constexpr int TerminalView::cursor_width () inline constexpr
Definition at line 27 of file TerminalView.h.
 { return 5; }
Referenced by did_move_cursor(), display(), and will_move_cursor().
decrement_counter()
void TerminalView::decrement_counter () private
Definition at line 94 of file TerminalView.cpp.
 {
     will_move_cursor();
     m_col--;
     if (m_col == 0) {
         m_row--;
     }
     did_move_cursor();
 }
References did_move_cursor(), m_col, m_row, and will_move_cursor().
Referenced by receive_keydown_event().
did_move_cursor()
void TerminalView::did_move_cursor () inline private
Definition at line 46 of file TerminalView.h.
     {
         auto pt = pos_on_screen();
         set_needs_display(LG::Rect(pt.x(), pt.y(), cursor_width() + 2, glyph_height()));
     }
References cursor_width(), glyph_height(), pos_on_screen(), and UI::View::set_needs_display().
Referenced by decrement_counter(), increment_counter(), and new_line().
display()
void TerminalView::display (const LG::Rect & rect) override virtual
Draws the receivers image within the passed-in rectangle.
Parameters
rect The portion of the views bounds that needs to be updated. The first time your view is drawn, this rectangle is typically the entire visible bounds of your view. However, during subsequent drawing operations, the rectangle may specify only part of your view.
Reimplemented from UI::View.
Definition at line 36 of file TerminalView.cpp.
 {
     UI::Context ctx(*this);
     ctx.add_clip(rect);
     ctx.set_fill_color(background_color());
     ctx.fill(bounds());
     auto& f = font();
     ctx.set_fill_color(font_color());
     LG::Point<int> text_start { 0, 0 };
     for (int i = 0; i < m_max_rows; i++) {
         for (int j = 0; j < m_max_cols; j++) {
             int idx = i * m_max_cols + j;
             ctx.draw(text_start, f.glyph_bitmap(m_display_data[idx]));
             text_start.offset_by(glyph_width(), 0);
         }
         text_start.set_x(0);
         text_start.offset_by(0, glyph_height());
     }
     ctx.set_fill_color(cursor_color());
     auto cursor_left_corner = pos_on_screen();
     ctx.fill(LG::Rect(cursor_left_corner.x() + 2, cursor_left_corner.y(), cursor_width(), glyph_height()));
 }
References LG::Context::add_clip(), background_color(), UI::View::bounds(), cursor_color(), cursor_width(), LG::Context::draw(), LG::Context::fill(), font(), font_color(), glyph_height(), glyph_width(), m_display_data, m_max_cols, m_max_rows, pos_on_screen(), and LG::Context::set_fill_color().
font()
const LG::Font& TerminalView::font () const inline
Definition at line 13 of file TerminalView.h.
 { return *m_font_ptr; }
References m_font_ptr.
Referenced by display(), glyph_height(), and glyph_width().
font_color()
const LG::Color& TerminalView::font_color () const inline
Definition at line 10 of file TerminalView.h.
 { return m_font_color; }
References m_font_color.
Referenced by display().
glyph_height()
int TerminalView::glyph_height () const inline
Definition at line 16 of file TerminalView.h.
 { return font().glyph_height(); }
References font(), and LG::Font::glyph_height().
Referenced by did_move_cursor(), display(), pos_on_screen(), put_char(), recalc_dimensions(), and will_move_cursor().
glyph_width()
int TerminalView::glyph_width () const inline
Definition at line 15 of file TerminalView.h.
 { return font().glyph_width('.'); }
References font(), and LG::Font::glyph_width().
Referenced by display(), pos_on_screen(), put_char(), and recalc_dimensions().
increment_counter()
void TerminalView::increment_counter () private
Definition at line 84 of file TerminalView.cpp.
 {
     will_move_cursor();
     m_col++;
     if (m_col == m_max_cols) {
         new_line();
     }
     did_move_cursor();
 }
References did_move_cursor(), m_col, m_max_cols, new_line(), and will_move_cursor().
Referenced by push_back_char().
new_line()
void TerminalView::new_line () private
Definition at line 72 of file TerminalView.cpp.
 {
     will_move_cursor();
     m_col = 0;
     m_row++;
     if (m_row == m_max_rows) {
         scroll_line();
         m_row--;
     }
     did_move_cursor();
 }
References did_move_cursor(), m_col, m_max_rows, m_row, scroll_line(), and will_move_cursor().
Referenced by increment_counter(), and push_back_char().
pos_in_data()
int TerminalView::pos_in_data () const inline
Definition at line 19 of file TerminalView.h.
 { return m_max_cols * m_row + m_col; }
References m_col, m_max_cols, and m_row.
Referenced by put_char().
pos_on_screen()
LG::Point<int> TerminalView::pos_on_screen () const inline
Definition at line 18 of file TerminalView.h.
 { return { m_col * glyph_width(), m_row * glyph_height() }; }
References glyph_height(), glyph_width(), m_col, and m_row.
Referenced by did_move_cursor(), display(), put_char(), and will_move_cursor().
ptmx()
int TerminalView::ptmx () const inline
Definition at line 25 of file TerminalView.h.
 { return m_ptmx; }
References m_ptmx.
Referenced by send_input(), and TerminalView().
push_back_char()
void TerminalView::push_back_char (char c) private
Definition at line 111 of file TerminalView.cpp.
 {
     if (c == '\n') {
         new_line();
         return;
     }
     put_char(c);
     increment_counter();
 }
References increment_counter(), new_line(), and put_char().
Referenced by receive_keydown_event(), and TerminalView().
put_char()
void TerminalView::put_char (char c) private
Definition at line 104 of file TerminalView.cpp.
 {
     auto pt = pos_on_screen();
     set_needs_display(LG::Rect(pt.x(), pt.y(), glyph_width(), glyph_height()));
     m_display_data[pos_in_data()] = c;
 }
References glyph_height(), glyph_width(), m_display_data, pos_in_data(), pos_on_screen(), and UI::View::set_needs_display().
Referenced by push_back_char(), and receive_keydown_event().
recalc_dimensions()
void TerminalView::recalc_dimensions (const LG::Rect & frame) private
Definition at line 27 of file TerminalView.cpp.
 {
     m_max_rows = frame.height() / glyph_height();
     m_max_cols = frame.width() / glyph_width();
     // FIXME: Add copy and resize on window resize.
     m_display_data = (char*)malloc(m_max_rows * m_max_cols);
     memset((uint8_t*)m_display_data, 0, m_max_rows * m_max_cols);
 }
References UI::View::frame(), glyph_height(), glyph_width(), LG::Rect::height(), m_display_data, m_max_cols, m_max_rows, malloc(), memset(), and LG::Rect::width().
Referenced by TerminalView().
receive_keydown_event()
void TerminalView::receive_keydown_event (UI::KeyDownEvent & event) override virtual
Reimplemented from UI::View.
Definition at line 132 of file TerminalView.cpp.
 {
     // FIXME: More symbols and static size of font
     if (event.key() == LFoundation::Keycode::KEY_BACKSPACE) {
         if (m_input.size()) {
             m_input.pop_back();
             decrement_counter();
             put_char(' ');
         }
     } else if (event.key() == LFoundation::Keycode::KEY_RETURN) {
         push_back_char('\n');
         send_input();
     } else if (event.key() < 128) {
         m_input.push_back(char(event.key()));
         push_back_char(char(event.key()));
     }
 }
References decrement_counter(), UI::KeyDownEvent::key(), KEY_BACKSPACE, KEY_RETURN, m_input, Algo::String::pop_back(), Algo::String::push_back(), push_back_char(), put_char(), send_input(), and Algo::String::size().
receive_keyup_event()
void TerminalView::receive_keyup_event (UI::KeyUpEvent &) override virtual
Reimplemented from UI::View.
Definition at line 128 of file TerminalView.cpp.
 {
 }
scroll_line()
void TerminalView::scroll_line () private
Definition at line 63 of file TerminalView.cpp.
 {
     char* data_plus_line = m_display_data + (m_max_cols);
     char* data_end_minus_line = m_display_data + (m_max_rows - 1) * m_max_cols;
     memmove((uint8_t*)m_display_data, (uint8_t*)data_plus_line, (m_max_rows - 1) * m_max_cols);
     memset((uint8_t*)data_end_minus_line, 0, m_max_cols);
     set_needs_display();
 }
References m_display_data, m_max_cols, m_max_rows, memmove(), memset(), and UI::View::set_needs_display().
Referenced by new_line().
send_input()
void TerminalView::send_input () private
Definition at line 121 of file TerminalView.cpp.
 {
     // Send string with /0.
     write(ptmx(), m_input.c_str(), m_input.size() + 1);
     m_input.clear();
 }
References Algo::String::c_str(), Algo::String::clear(), m_input, ptmx(), Algo::String::size(), and write().
Referenced by receive_keydown_event().
will_move_cursor()
void TerminalView::will_move_cursor () inline private
Definition at line 40 of file TerminalView.h.
     {
         auto pt = pos_on_screen();
         set_needs_display(LG::Rect(pt.x(), pt.y(), cursor_width() + 2, glyph_height()));
     }
References cursor_width(), glyph_height(), pos_on_screen(), and UI::View::set_needs_display().
Referenced by decrement_counter(), increment_counter(), and new_line().
Field Documentation
m_background_color
LG::Color TerminalView::m_background_color { 0x292929 } private
Definition at line 52 of file TerminalView.h.
Referenced by background_color().
m_col
size_t TerminalView::m_col { 0 } private
Definition at line 61 of file TerminalView.h.
Referenced by decrement_counter(), increment_counter(), new_line(), pos_in_data(), and pos_on_screen().
m_display_data
char* TerminalView::m_display_data { nullptr } private
Definition at line 63 of file TerminalView.h.
Referenced by display(), put_char(), recalc_dimensions(), and scroll_line().
m_font_color
LG::Color TerminalView::m_font_color { LG::Color::White } private
Definition at line 53 of file TerminalView.h.
Referenced by font_color().
m_font_ptr
LG::Font* TerminalView::m_font_ptr { LG::Font::load_from_file("/res/LizaRegular8x10.font") } private
Definition at line 54 of file TerminalView.h.
Referenced by font().
m_input
String TerminalView::m_input {} private
Definition at line 57 of file TerminalView.h.
Referenced by receive_keydown_event(), and send_input().
m_max_cols
size_t TerminalView::m_max_cols { 0 } private
Definition at line 59 of file TerminalView.h.
Referenced by display(), increment_counter(), pos_in_data(), recalc_dimensions(), and scroll_line().
m_max_rows
size_t TerminalView::m_max_rows { 0 } private
Definition at line 60 of file TerminalView.h.
Referenced by display(), new_line(), recalc_dimensions(), and scroll_line().
m_ptmx
int TerminalView::m_ptmx { -1 } private
Definition at line 56 of file TerminalView.h.
Referenced by ptmx().
m_row
size_t TerminalView::m_row { 0 } private
Definition at line 62 of file TerminalView.h.
Referenced by decrement_counter(), new_line(), pos_in_data(), and pos_on_screen().
The documentation for this class was generated from the following files:
userland/terminal/TerminalView.h
userland/terminal/TerminalView.cpp