oneOS: InvalidateMessage Class Reference
InvalidateMessage Class Reference
#include <WSConnection.h>
Public Member Functions
InvalidateMessage (message_key_t key, uint32_t window_id, LG::Rect rect)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
uint32_t window_id () const
LG::Rect rect () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
uint32_t m_window_id
LG::Rect m_rect
Detailed Description
Definition at line 278 of file WSConnection.h.
Constructor & Destructor Documentation
InvalidateMessage()
InvalidateMessage::InvalidateMessage (message_key_t key, uint32_t window_id, LG::Rect rect) inline
Definition at line 280 of file WSConnection.h.
         : m_key(key)
         , m_window_id(window_id)
         , m_rect(rect)
     {
     }
Member Function Documentation
decoder_magic()
int InvalidateMessage::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 289 of file WSConnection.h.
 { return 320; }
Referenced by encode().
encode()
EncodedMessage InvalidateMessage::encode () const inline override virtual
Reimplemented from Message.
Definition at line 292 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_window_id);
         Encoder::append(buffer, m_rect);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), m_rect, and m_window_id.
id()
int InvalidateMessage::id () const inline override virtual
Reimplemented from Message.
Definition at line 286 of file WSConnection.h.
 { return 10; }
key()
int InvalidateMessage::key () const inline override virtual
Reimplemented from Message.
Definition at line 288 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode().
rect()
LG::Rect InvalidateMessage::rect () const inline
Definition at line 291 of file WSConnection.h.
 { return m_rect; }
References m_rect.
Referenced by WServerDecoder::handle().
reply_id()
int InvalidateMessage::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 287 of file WSConnection.h.
 { return -1; }
window_id()
uint32_t InvalidateMessage::window_id () const inline
Definition at line 290 of file WSConnection.h.
 { return m_window_id; }
References m_window_id.
Referenced by WServerDecoder::handle().
Field Documentation
m_key
message_key_t InvalidateMessage::m_key private
Definition at line 303 of file WSConnection.h.
Referenced by key().
m_rect
LG::Rect InvalidateMessage::m_rect private
Definition at line 305 of file WSConnection.h.
Referenced by encode(), and rect().
m_window_id
uint32_t InvalidateMessage::m_window_id private
Definition at line 304 of file WSConnection.h.
Referenced by encode(), and window_id().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h