oneOS: LG::PNG::DataStreamer Class Reference
LG::PNG::DataStreamer Class Reference
#include <PNGLoader.h>
Public Member Functions
DataStreamer ()=default
DataStreamer (const void *data)
~DataStreamer ()
template<typename T >
void read (T &val)
void read (void *buffer, size_t cnt)
template<typename T >
T at (int index) const
void skip (size_t cnt)
void set (const void *data)
const uint8_t * ptr () const
uint8_t * ptr ()
Private Attributes
uint8_t * m_orig_ptr { nullptr }
uint8_t * m_ptr { nullptr }
Detailed Description
Definition at line 34 of file PNGLoader.h.
Constructor & Destructor Documentation
DataStreamer() [1/2]
LG::PNG::DataStreamer::DataStreamer () default
DataStreamer() [2/2]
LG::PNG::DataStreamer::DataStreamer (const void * data) inline
Definition at line 38 of file PNGLoader.h.
         : m_ptr((uint8_t*)data)
     {
     }
~DataStreamer()
LG::PNG::DataStreamer::~DataStreamer () inline
Definition at line 43 of file PNGLoader.h.
 { }
Member Function Documentation
at()
template<typename T > T LG::PNG::DataStreamer::at (int index) const inline
Definition at line 60 of file PNGLoader.h.
     {
         T val = *((T*)m_orig_ptr + index);
         val = LFoundation::ByteOrder::from_network(val);
         return val;
     }
References LFoundation::ByteOrder::from_network(), and m_orig_ptr.
ptr() [1/2]
uint8_t* LG::PNG::DataStreamer::ptr () inline
Definition at line 70 of file PNGLoader.h.
 { return m_ptr; }
References m_ptr.
ptr() [2/2]
const uint8_t* LG::PNG::DataStreamer::ptr () const inline
Definition at line 69 of file PNGLoader.h.
 { return m_ptr; }
References m_ptr.
Referenced by LG::PNG::PNGLoader::read_IDAT().
read() [1/2]
template<typename T > void LG::PNG::DataStreamer::read (T & val) inline
Definition at line 46 of file PNGLoader.h.
     {
         val = *(T*)m_ptr;
         m_ptr += sizeof(T);
         val = LFoundation::ByteOrder::from_network(val);
     }
References LFoundation::ByteOrder::from_network(), and m_ptr.
Referenced by LG::PNG::PNGLoader::read_chunk(), LG::PNG::PNGLoader::read_IDAT(), and LG::PNG::PNGLoader::read_IHDR().
read() [2/2]
void LG::PNG::DataStreamer::read (void * buffer, size_t cnt) inline
Definition at line 53 of file PNGLoader.h.
     {
         memcpy((uint8_t*)buffer, m_ptr, cnt);
         m_ptr += cnt;
     }
References m_ptr, and memcpy().
set()
void LG::PNG::DataStreamer::set (const void * data) inline
Definition at line 68 of file PNGLoader.h.
 { m_orig_ptr = m_ptr = (uint8_t*)data; }
References m_orig_ptr, and m_ptr.
Referenced by LG::PNG::PNGLoader::load_from_mem().
skip()
void LG::PNG::DataStreamer::skip (size_t cnt) inline
Definition at line 67 of file PNGLoader.h.
 { m_ptr += cnt; }
References m_ptr.
Referenced by LG::PNG::PNGLoader::read_IDAT(), LG::PNG::PNGLoader::read_PHYS(), and LG::PNG::PNGLoader::read_TEXT().
Field Documentation
m_orig_ptr
uint8_t* LG::PNG::DataStreamer::m_orig_ptr { nullptr } private
Definition at line 73 of file PNGLoader.h.
Referenced by at(), and set().
m_ptr
uint8_t* LG::PNG::DataStreamer::m_ptr { nullptr } private
Definition at line 74 of file PNGLoader.h.
Referenced by ptr(), read(), set(), and skip().
The documentation for this class was generated from the following file:
libs/libg/ImageLoaders/PNGLoader.h