oneOS: ServerConnection< ServerDecoder, ClientDecoder > Class Template Reference
ServerConnection< ServerDecoder, ClientDecoder > Class Template Reference
#include <ServerConnection.h>
Public Member Functions
ServerConnection (int sock_fd, ServerDecoder &server_decoder, ClientDecoder &client_decoder)
bool send_message (const Message &msg) const
void pump_messages ()
Private Attributes
int m_connection_fd
ServerDecoder & m_server_decoder
ClientDecoder & m_client_decoder
Detailed Description
template<typename ServerDecoder, typename ClientDecoder>
class ServerConnection< ServerDecoder, ClientDecoder >
Definition at line 8 of file ServerConnection.h.
Constructor & Destructor Documentation
ServerConnection()
template<typename ServerDecoder , typename ClientDecoder > ServerConnection< ServerDecoder, ClientDecoder >::ServerConnection (int sock_fd, ServerDecoder & server_decoder, ClientDecoder & client_decoder) inline
Definition at line 10 of file ServerConnection.h.
         : m_connection_fd(sock_fd)
         , m_server_decoder(server_decoder)
         , m_client_decoder(client_decoder)
     {
     }
Member Function Documentation
pump_messages()
template<typename ServerDecoder , typename ClientDecoder > void ServerConnection< ServerDecoder, ClientDecoder >::pump_messages () inline
Definition at line 24 of file ServerConnection.h.
     {
         Vector<char> buf;
         char tmpbuf[1024];
         int read_cnt;
         while (read_cnt = read(m_connection_fd, tmpbuf, sizeof(tmpbuf))) {
             if (read_cnt <= 0) {
                 Dbg() << getpid() << " :: ServerConnection read error\n";
                 return;
             }
             size_t buf_size = buf.size();
             buf.resize(buf_size + read_cnt);
             memcpy((uint8_t*)&buf.data()[buf_size], (uint8_t*)tmpbuf, read_cnt);
             if (read_cnt < sizeof(tmpbuf)) {
                 break;
             }
         }
         size_t msg_len = 0;
         for (int i = 0; i < read_cnt; i += msg_len) {
             msg_len = 0;
             if (auto response = m_server_decoder.decode((buf.data() + i), read_cnt - i, msg_len)) {
                 if (auto answer = m_server_decoder.handle(*response)) {
                     send_message(*answer);
                 }
             } else if (auto response = m_client_decoder.decode((buf.data() + i), read_cnt - i, msg_len)) {
             } else {
                 ASSERT_NOT_REACHED();
             }
         }
     }
References ASSERT_NOT_REACHED, buf, getpid(), ServerConnection< ServerDecoder, ClientDecoder >::m_client_decoder, ServerConnection< ServerDecoder, ClientDecoder >::m_connection_fd, ServerConnection< ServerDecoder, ClientDecoder >::m_server_decoder, memcpy(), read(), and ServerConnection< ServerDecoder, ClientDecoder >::send_message().
Referenced by Connection::listen().
send_message()
template<typename ServerDecoder , typename ClientDecoder > bool ServerConnection< ServerDecoder, ClientDecoder >::send_message (const Message & msg) const inline
Definition at line 17 of file ServerConnection.h.
     {
         auto encoded_msg = msg.encode();
         int wrote = write(m_connection_fd, encoded_msg.data(), encoded_msg.size());
         return wrote == encoded_msg.size();
     }
References Message::encode(), ServerConnection< ServerDecoder, ClientDecoder >::m_connection_fd, and write().
Referenced by ServerConnection< ServerDecoder, ClientDecoder >::pump_messages(), Connection::receive_event(), and Connection::send_async_message().
Field Documentation
m_client_decoder
template<typename ServerDecoder , typename ClientDecoder > ClientDecoder& ServerConnection< ServerDecoder, ClientDecoder >::m_client_decoder private
Definition at line 62 of file ServerConnection.h.
Referenced by ServerConnection< ServerDecoder, ClientDecoder >::pump_messages().
m_connection_fd
template<typename ServerDecoder , typename ClientDecoder > int ServerConnection< ServerDecoder, ClientDecoder >::m_connection_fd private
Definition at line 60 of file ServerConnection.h.
Referenced by ServerConnection< ServerDecoder, ClientDecoder >::pump_messages(), and ServerConnection< ServerDecoder, ClientDecoder >::send_message().
m_server_decoder
template<typename ServerDecoder , typename ClientDecoder > ServerDecoder& ServerConnection< ServerDecoder, ClientDecoder >::m_server_decoder private
Definition at line 61 of file ServerConnection.h.
Referenced by ServerConnection< ServerDecoder, ClientDecoder >::pump_messages().
The documentation for this class was generated from the following file:
libs/libipc/ServerConnection.h