oneOS: DestroyWindowMessageReply Class Reference
DestroyWindowMessageReply Class Reference
#include <WSConnection.h>
Public Member Functions
DestroyWindowMessageReply (message_key_t key, uint32_t status)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
uint32_t status () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
uint32_t m_status
Detailed Description
Definition at line 154 of file WSConnection.h.
Constructor & Destructor Documentation
DestroyWindowMessageReply()
DestroyWindowMessageReply::DestroyWindowMessageReply (message_key_t key, uint32_t status) inline
Definition at line 156 of file WSConnection.h.
         : m_key(key)
         , m_status(status)
     {
     }
Member Function Documentation
decoder_magic()
int DestroyWindowMessageReply::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 164 of file WSConnection.h.
 { return 320; }
Referenced by encode().
encode()
EncodedMessage DestroyWindowMessageReply::encode () const inline override virtual
Reimplemented from Message.
Definition at line 166 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_status);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), and m_status.
id()
int DestroyWindowMessageReply::id () const inline override virtual
Reimplemented from Message.
Definition at line 161 of file WSConnection.h.
 { return 6; }
key()
int DestroyWindowMessageReply::key () const inline override virtual
Reimplemented from Message.
Definition at line 163 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode().
reply_id()
int DestroyWindowMessageReply::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 162 of file WSConnection.h.
 { return -1; }
status()
uint32_t DestroyWindowMessageReply::status () const inline
Definition at line 165 of file WSConnection.h.
 { return m_status; }
References m_status.
Field Documentation
m_key
message_key_t DestroyWindowMessageReply::m_key private
Definition at line 176 of file WSConnection.h.
Referenced by key().
m_status
uint32_t DestroyWindowMessageReply::m_status private
Definition at line 177 of file WSConnection.h.
Referenced by encode(), and status().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h