oneOS: UI::Connection Class Reference
UI::Connection Class Reference
#include <Connection.h>
Public Member Functions
Connection (int connection_fd)
void greeting ()
int new_window (const Window &window)
void set_buffer (const Window &window)
template<class T >
UniquePtr< T > send_sync_message (const Message &msg)
bool send_async_message (const Message &msg) const
void listen ()
int key () const
Static Public Member Functions
static Connection & the ()
Private Attributes
int m_connection_fd
int m_connection_id
ClientConnection< WindowServerDecoder, ClientDecoder > m_connection_with_server
WindowServerDecoder m_server_decoder
ClientDecoder m_client_decoder
Detailed Description
Definition at line 10 of file Connection.h.
Constructor & Destructor Documentation
Connection()
Connection::Connection (int connection_fd)
Definition at line 25 of file Connection.cpp.
     : m_connection_fd(connection_fd)
     , m_server_decoder()
     , m_client_decoder()
     , m_connection_with_server(m_connection_fd, m_server_decoder, m_client_decoder)
 {
     s_the = this;
     if (m_connection_fd > 0) {
         connect(m_connection_fd, "/win.sock", 9);
     }
     greeting();
     LFoundation::EventLoop::the().add(
         m_connection_fd, [] {
             Connection::the().listen();
         },
         nullptr);
 }
References LFoundation::EventLoop::add(), connect(), greeting(), listen(), m_connection_fd, UI::s_the, LFoundation::EventLoop::the(), and the().
Referenced by the().
Member Function Documentation
greeting()
void Connection::greeting ()
Definition at line 43 of file Connection.cpp.
 {
     auto resp_message = send_sync_message<GreetMessageReply>(GreetMessage(getpid()));
     m_connection_id = resp_message->connection_id();
     m_connection_with_server.set_accepted_key(m_connection_id);
 #ifdef DEBUG_CONNECTION
     Dbg() << "Got greet with server\n";
 #endif
 }
References getpid(), m_connection_id, and m_connection_with_server.
Referenced by Connection().
key()
int UI::Connection::key () const inline
Definition at line 25 of file Connection.h.
 { return m_connection_id; }
References m_connection_id.
Referenced by new_window(), and UI::App::receive_event().
listen()
void UI::Connection::listen () inline
Definition at line 22 of file Connection.h.
 { m_connection_with_server.pump_messages(); }
References m_connection_with_server.
Referenced by Connection().
new_window()
int Connection::new_window (const Window & window)
Definition at line 53 of file Connection.cpp.
 {
     auto message = CreateWindowMessage(key(), window.type(), window.bounds().width(), window.bounds().height(), window.buffer().id(), window.icon_path());
     auto resp_message = send_sync_message<CreateWindowMessageReply>(message);
 #ifdef DEBUG_CONNECTION
     Dbg() << "New window created\n";
 #endif
     return resp_message->window_id();
 }
References UI::Window::bounds(), UI::Window::buffer(), LG::Rect::height(), UI::Window::icon_path(), Sys::SharedBuffer< T >::id(), key(), UI::Window::type(), and LG::Rect::width().
Referenced by UI::Window::Window().
send_async_message()
bool UI::Connection::send_async_message (const Message & msg) const inline
Definition at line 21 of file Connection.h.
 { return m_connection_with_server.send_message(msg); }
References m_connection_with_server.
Referenced by UI::Window::did_format_change(), UI::Window::set_frame_style(), and UI::Window::set_title().
send_sync_message()
template<class T > UniquePtr<T> UI::Connection::send_sync_message (const Message & msg) inline
Definition at line 20 of file Connection.h.
 { return UniquePtr<T>(m_connection_with_server.send_sync(msg)); }
References m_connection_with_server.
Referenced by UI::App::receive_event().
set_buffer()
void UI::Connection::set_buffer (const Window & window)
the()
Connection & Connection::the () static
Definition at line 16 of file Connection.cpp.
 {
     // FIXME: Thread-safe method to be applied
     if (!s_the) {
         new Connection(socket(PF_LOCAL, 0, 0));
     }
     return *s_the;
 }
References Connection(), PF_LOCAL, UI::s_the, and socket().
Referenced by Connection(), UI::Window::did_format_change(), UI::Responder::send_invalidate_message_to_server(), UI::Window::set_frame_style(), UI::Window::set_title(), and UI::Window::Window().
Field Documentation
m_client_decoder
ClientDecoder UI::Connection::m_client_decoder private
Definition at line 32 of file Connection.h.
m_connection_fd
int UI::Connection::m_connection_fd private
Definition at line 28 of file Connection.h.
Referenced by Connection().
m_connection_id
int UI::Connection::m_connection_id private
Definition at line 29 of file Connection.h.
Referenced by greeting(), and key().
m_connection_with_server
ClientConnection<WindowServerDecoder, ClientDecoder> UI::Connection::m_connection_with_server private
Definition at line 30 of file Connection.h.
Referenced by greeting(), listen(), send_async_message(), and send_sync_message().
m_server_decoder
WindowServerDecoder UI::Connection::m_server_decoder private
Definition at line 31 of file Connection.h.
The documentation for this class was generated from the following files:
libs/libui/Connection.h
libs/libui/Connection.cpp