oneOS: GreetMessageReply Class Reference
GreetMessageReply Class Reference
#include <WSConnection.h>
Public Member Functions
GreetMessageReply (message_key_t key, uint32_t connection_id)
int id () const override
int reply_id () const override
int key () const override
int decoder_magic () const override
uint32_t connection_id () const
EncodedMessage encode () const override
Public Member Functions inherited from Message
Message ()
virtual ~Message ()=default
Private Attributes
message_key_t m_key
uint32_t m_connection_id
Detailed Description
Definition at line 34 of file WSConnection.h.
Constructor & Destructor Documentation
GreetMessageReply()
GreetMessageReply::GreetMessageReply (message_key_t key, uint32_t connection_id) inline
Definition at line 36 of file WSConnection.h.
         : m_key(key)
         , m_connection_id(connection_id)
     {
     }
Member Function Documentation
connection_id()
uint32_t GreetMessageReply::connection_id () const inline
Definition at line 45 of file WSConnection.h.
 { return m_connection_id; }
References m_connection_id.
decoder_magic()
int GreetMessageReply::decoder_magic () const inline override virtual
Reimplemented from Message.
Definition at line 44 of file WSConnection.h.
 { return 320; }
Referenced by encode().
encode()
EncodedMessage GreetMessageReply::encode () const inline override virtual
Reimplemented from Message.
Definition at line 46 of file WSConnection.h.
     {
         EncodedMessage buffer;
         Encoder::append(buffer, decoder_magic());
         Encoder::append(buffer, id());
         Encoder::append(buffer, key());
         Encoder::append(buffer, m_connection_id);
         return buffer;
     }
References Encoder::append(), decoder_magic(), key(), and m_connection_id.
id()
int GreetMessageReply::id () const inline override virtual
Reimplemented from Message.
Definition at line 41 of file WSConnection.h.
 { return 2; }
key()
int GreetMessageReply::key () const inline override virtual
Reimplemented from Message.
Definition at line 43 of file WSConnection.h.
 { return m_key; }
References m_key.
Referenced by encode().
reply_id()
int GreetMessageReply::reply_id () const inline override virtual
Reimplemented from Message.
Definition at line 42 of file WSConnection.h.
 { return -1; }
Field Documentation
m_connection_id
uint32_t GreetMessageReply::m_connection_id private
Definition at line 57 of file WSConnection.h.
Referenced by connection_id(), and encode().
m_key
message_key_t GreetMessageReply::m_key private
Definition at line 56 of file WSConnection.h.
Referenced by key().
The documentation for this class was generated from the following file:
servers/window_server/WSConnection.h