oneOS: FastLaunchEntity Class Reference
FastLaunchEntity Class Reference
#include <FastLaunchEntity.h>
Public Member Functions
FastLaunchEntity ()=default
void set_icon (LG::PixelBitmap &&icon)
const LG::PixelBitmap & icon () const
void set_path_to_exec (LG::String &&path)
const LG::String & path_to_exec () const
Public Member Functions inherited from Algo::LinkedListNode< FastLaunchEntity >
LinkedListNode ()=default
FastLaunchEntity * next () const
FastLaunchEntity * prev () const
void set_prev (FastLaunchEntity *prev)
void set_next (FastLaunchEntity *next)
Private Attributes
LG::PixelBitmap m_icon
LG::String m_path_to_exec {}
Detailed Description
Definition at line 6 of file FastLaunchEntity.h.
Constructor & Destructor Documentation
FastLaunchEntity()
FastLaunchEntity::FastLaunchEntity () default
Member Function Documentation
icon()
const LG::PixelBitmap& FastLaunchEntity::icon () const inline
Definition at line 11 of file FastLaunchEntity.h.
 { return m_icon; }
References m_icon.
Referenced by set_icon().
path_to_exec()
const LG::String& FastLaunchEntity::path_to_exec () const inline
Definition at line 14 of file FastLaunchEntity.h.
 { return m_path_to_exec; }
References m_path_to_exec.
Referenced by DockView::launch().
set_icon()
void FastLaunchEntity::set_icon (LG::PixelBitmap && icon) inline
Definition at line 10 of file FastLaunchEntity.h.
 { m_icon = move(icon); }
References icon(), m_icon, and move().
set_path_to_exec()
void FastLaunchEntity::set_path_to_exec (LG::String && path) inline
Definition at line 13 of file FastLaunchEntity.h.
 { m_path_to_exec = move(path); }
References m_path_to_exec, and move().
Field Documentation
m_icon
LG::PixelBitmap FastLaunchEntity::m_icon private
Definition at line 17 of file FastLaunchEntity.h.
Referenced by icon(), and set_icon().
m_path_to_exec
LG::String FastLaunchEntity::m_path_to_exec {} private
Definition at line 18 of file FastLaunchEntity.h.
Referenced by path_to_exec(), and set_path_to_exec().
The documentation for this class was generated from the following file:
userland/dock/FastLaunchEntity.h