oneOS: UI::Label Class Reference
UI::Label Class Reference
#include <Label.h>
Public Member Functions
Label (const LG::Rect &)
const String & text () const
void set_text (const String &text)
void set_text (String &&text)
void set_text_color (const LG::Color &color)
const LG::Color & text_color () const
void set_content_edge_insets (const EdgeInsect &ei)
const EdgeInsect & content_edge_insets () const
const LG::Font & font () const
size_t preferred_width () const
virtual void display (const LG::Rect &rect) override
virtual void hover_begin (const LG::Point< int > &location) override
virtual void hover_end () override
Public Member Functions inherited from UI::View
View (const LG::Rect &)
View (const LG::Rect &, const LG::Color &)
template<class T , class... Args>
T & add_subview (Args &&... args)
void remove_from_superview ()
template<typename Callback >
void foreach_subview (Callback callback) const
View * subview_at (const LG::Point< int > &point) const
View * hit_test (const LG::Point< int > &point)
const LG::Rect & frame () const
const LG::Rect & bounds () const
void set_width (size_t x)
void set_height (size_t x)
LG::Rect frame_in_window ()
Window * window ()
bool has_superview ()
View * superview ()
Vector< View * > & subviews ()
const Vector< View * > & subviews () const
void set_needs_display (const LG::Rect &)
void set_needs_display ()
bool is_hovered () const
void set_focusable (bool val)
bool is_focusable () const
virtual void did_display (const LG::Rect &rect)
virtual void click_began (const LG::Point< int > &location)
virtual void click_ended ()
virtual void receive_mouse_move_event (MouseEvent &) override
virtual void receive_mouse_action_event (MouseActionEvent &) override
virtual void receive_mouse_leave_event (MouseLeaveEvent &) override
virtual void receive_keyup_event (KeyUpEvent &) override
virtual void receive_keydown_event (KeyDownEvent &) override
virtual void receive_display_event (DisplayEvent &) override
LG::Color & background_color ()
const LG::Color & background_color () const
virtual void set_background_color (const LG::Color &background_color)
Public Member Functions inherited from UI::Responder
bool send_invalidate_message_to_server (const LG::Rect &rect) const
void send_display_message_to_self (Window &win, const LG::Rect &display_rect)
void receive_event (UniquePtr< LFoundation::Event > event) override
Public Member Functions inherited from LFoundation::EventReceiver
EventReceiver ()
~EventReceiver ()
Private Member Functions
void recalc_bounds ()
size_t text_height () const
size_t text_width () const
Private Attributes
String m_text {}
LG::Color m_text_color { LG::Color::Black }
LG::Font m_font { LG::Font::system_font() }
EdgeInsect m_content_edge_insets {}
Additional Inherited Members
Protected Member Functions inherited from UI::Responder
Responder ()
Protected Attributes inherited from UI::Responder
bool m_display_message_sent { false }
LG::Rect m_prev_display_message {}
Detailed Description
Definition at line 17 of file Label.h.
Constructor & Destructor Documentation
Label()
UI::Label::Label (const LG::Rect & frame)
Definition at line 17 of file Label.cpp.
     : View(frame)
 {
 }
Member Function Documentation
content_edge_insets()
const EdgeInsect& UI::Label::content_edge_insets () const inline
Definition at line 29 of file Label.h.
 { return m_content_edge_insets; }
References m_content_edge_insets.
Referenced by display(), and recalc_bounds().
display()
void UI::Label::display (const LG::Rect & rect) override virtual
Draws the receiver’s image within the passed-in rectangle.
Parameters
rect The portion of the view’s bounds that needs to be updated. The first time your view is drawn, this rectangle is typically the entire visible bounds of your view. However, during subsequent drawing operations, the rectangle may specify only part of your view.
Reimplemented from UI::View.
Definition at line 22 of file Label.cpp.
 {
     Context ctx(*this);
     auto& f = font();
     const size_t letter_spacing = 2;
     size_t label_width = bounds().width() - content_edge_insets().left() - content_edge_insets().right();
     size_t txt_width = text_width();
     size_t dots_width = font().glyph_width('.') * 3 + letter_spacing * 2;
     bool need_to_stop_rendering_text = (txt_width > label_width);
     size_t width_when_stop_rendering_text = content_edge_insets().left() + label_width - dots_width;
     LG::Point<int> text_start { content_edge_insets().left(), content_edge_insets().top() };
     ctx.set_fill_color(text_color());
     for (int i = 0; i < m_text.size(); i++) {
         size_t glyph_width = f.glyph_width(m_text[i]) + letter_spacing;
         if (need_to_stop_rendering_text && text_start.x() + glyph_width > width_when_stop_rendering_text) {
             for (int j = 0; j < 3; j++) {
                 ctx.draw(text_start, f.glyph_bitmap('.'));
                 text_start.offset_by(f.glyph_width('.') + letter_spacing, 0);
             }
             return;
         }
         ctx.draw(text_start, f.glyph_bitmap(m_text[i]));
         text_start.offset_by(glyph_width, 0);
     }
 }
References UI::View::bounds(), content_edge_insets(), LG::Context::draw(), font(), LG::Font::glyph_width(), UI::EdgeInsect::left(), m_text, UI::EdgeInsect::right(), LG::Context::set_fill_color(), Algo::String::size(), text_color(), text_width(), UI::EdgeInsect::top(), and LG::Rect::width().
font()
const LG::Font& UI::Label::font () const inline
Definition at line 31 of file Label.h.
 { return m_font; }
References m_font.
Referenced by display(), text_height(), and text_width().
hover_begin()
void UI::Label::hover_begin (const LG::Point< int > & location) override virtual
Reimplemented from UI::View.
Definition at line 52 of file Label.cpp.
 {
 }
hover_end()
void UI::Label::hover_end () override virtual
Reimplemented from UI::View.
Definition at line 56 of file Label.cpp.
 {
 }
preferred_width()
size_t UI::Label::preferred_width () const inline
Definition at line 33 of file Label.h.
 { return text_width() + m_content_edge_insets.left() + m_content_edge_insets.right(); }
References UI::EdgeInsect::left(), m_content_edge_insets, UI::EdgeInsect::right(), and text_width().
recalc_bounds()
void UI::Label::recalc_bounds () private
Definition at line 60 of file Label.cpp.
 {
     size_t new_width = text_width() + content_edge_insets().left() + content_edge_insets().right();
     size_t new_height = text_height() + content_edge_insets().top() + content_edge_insets().bottom();
     set_width(new_width);
     set_height(new_height);
 }
References UI::EdgeInsect::bottom(), content_edge_insets(), UI::EdgeInsect::left(), UI::EdgeInsect::right(), UI::View::set_height(), UI::View::set_width(), text_height(), text_width(), and UI::EdgeInsect::top().
set_content_edge_insets()
void UI::Label::set_content_edge_insets (const EdgeInsect & ei) inline
Definition at line 28 of file Label.h.
 { m_content_edge_insets = ei; }
References m_content_edge_insets.
set_text() [1/2]
void UI::Label::set_text (const String & text) inline
Definition at line 22 of file Label.h.
 { m_text = text; }
References m_text, and text().
set_text() [2/2]
void UI::Label::set_text (String && text) inline
Definition at line 23 of file Label.h.
 { m_text = move(text); }
References m_text, move(), and text().
set_text_color()
void UI::Label::set_text_color (const LG::Color & color) inline
Definition at line 25 of file Label.h.
 { m_text_color = color; }
References m_text_color.
Referenced by main().
text()
const String& UI::Label::text () const inline
Definition at line 21 of file Label.h.
 { return m_text; }
References m_text.
Referenced by set_text().
text_color()
const LG::Color& UI::Label::text_color () const inline
Definition at line 26 of file Label.h.
 { return m_text_color; }
References m_text_color.
Referenced by display().
text_height()
size_t UI::Label::text_height () const private
Definition at line 82 of file Label.cpp.
 {
     return font().glyph_height();
 }
References font(), and LG::Font::glyph_height().
Referenced by recalc_bounds().
text_width()
size_t UI::Label::text_width () const private
Definition at line 68 of file Label.cpp.
 {
     if (!m_text.size()) {
         return 0;
     }
     size_t width = 0;
     auto& f = font();
     for (int i = 0; i < m_text.size(); i++) {
         width += f.glyph_width(m_text[i]) + 2; // FIXME
     }
     return width - 2;
 }
References font(), m_text, and Algo::String::size().
Referenced by display(), preferred_width(), and recalc_bounds().
Field Documentation
m_content_edge_insets
EdgeInsect UI::Label::m_content_edge_insets {} private
Definition at line 48 of file Label.h.
Referenced by content_edge_insets(), preferred_width(), and set_content_edge_insets().
m_font
LG::Font UI::Label::m_font { LG::Font::system_font() } private
Definition at line 46 of file Label.h.
Referenced by font().
m_text
String UI::Label::m_text {} private
Definition at line 44 of file Label.h.
Referenced by display(), set_text(), text(), and text_width().
m_text_color
LG::Color UI::Label::m_text_color { LG::Color::Black } private
Definition at line 45 of file Label.h.
Referenced by set_text_color(), and text_color().
The documentation for this class was generated from the following files:
libs/libui/Label.h
libs/libui/Label.cpp