oneOS: include/cmd/cmd.h File Reference
cmd.h File Reference
#include <drivers/x86/display.h>
#include <drivers/x86/keyboard.h>
#include <mem/kmalloc.h>
Data Structures
struct cmd_redirect_desc_t
Macros
#define MAX_CMD_LENGTH 64
Functions
void cmd_install ()
bool cmd_register (char *cmd, void *handler)
Macro Definition Documentation
MAX_CMD_LENGTH
#define MAX_CMD_LENGTH 64
Definition at line 8 of file cmd.h.
Function Documentation
cmd_install()
void cmd_install ()
Definition at line 131 of file cmd.c.
                    {
     clean_screen();
     _cmd_buffer = kmalloc(256);
     _cmd_parsed_buffer = kmalloc(sizeof(void*) * 256);
     _cmd_loop();
 }
References _cmd_buffer, _cmd_loop(), _cmd_parsed_buffer, clean_screen(), and kmalloc().
cmd_register()
bool cmd_register (char * cmd, void * handler)
Definition at line 138 of file cmd.c.
{
     uint8_t len = 0;
     while (cmd[len] != '\0') len++;
     char *cmd_holder = kmalloc(len+1);
     memcpy(cmd_holder, cmd, len+1);
     if (_cmd_redirects_registered == MAX_CMD_LENGTH) {
         return false;
     }
     _cmd_redirects[_cmd_redirects_registered].served_cmd = cmd_holder;
     _cmd_redirects[_cmd_redirects_registered].handler = handler;
     _cmd_redirects_registered++;
     return true;
 }
References _cmd_redirects, _cmd_redirects_registered, cmd, cmd_redirect_desc_t::handler, kmalloc(), MAX_CMD_LENGTH, memcpy(), and cmd_redirect_desc_t::served_cmd.
Referenced by syscmd_init().