oneOS: src/kernel/fs/dentry.c File Reference
dentry.c File Reference
#include <algo/dynamic_array.h>
#include <fs/vfs.h>
#include <log.h>
#include <mem/kmalloc.h>
#include <sys_handler.h>
#include <utils/kassert.h>
#include <utils/mem.h>
#include <platform/x86/system.h>
Macros
#define DENTRY_ALLOC_SIZE (4 * KB) /* Shows the size of list's parts. */
#define DENTRY_SWAP_THRESHOLD_FOR_INODE_CACHE (16 * KB)
Functions
static bool need_to_free_inode_cache ()
static bool free_inode_cache ()
static void dentry_cache_alloc ()
static dentry_t * dentry_cache_find_empty_entry ()
static void dentry_delete_inode (dentry_t *dentry)
static void dentry_flush_inode (dentry_t *dentry)
static void dentry_delete_from_cache (dentry_t *dentry)
static void dentry_prefree (dentry_t *dentry)
static dentry_t * dentry_alloc_new (uint32_t dev_indx, uint32_t inode_indx)
void dentry_set_parent (dentry_t *to, dentry_t *parent)
dentry_t * dentry_get_parent (dentry_t *dentry)
void dentry_flusher ()
dentry_t * dentry_get (uint32_t dev_indx, uint32_t inode_indx)
dentry_t * dentry_duplicate (dentry_t *dentry)
static void dentry_put_impl (dentry_t *dentry)
void dentry_force_put (dentry_t *dentry)
void dentry_put (dentry_t *dentry)
void dentry_put_all_dentries_of_dev (uint32_t dev_indx)
void dentry_set_flag (dentry_t *dentry, uint32_t flag)
bool dentry_test_flag (dentry_t *dentry, uint32_t flag)
void dentry_rem_flag (dentry_t *dentry, uint32_t flag)
void dentry_inode_set_flag (dentry_t *dentry, mode_t mode)
bool dentry_inode_test_flag (dentry_t *dentry, mode_t mode)
void dentry_inode_rem_flag (dentry_t *dentry, mode_t mode)
uint32_t dentry_stat_cached_count ()
Variables
vfs_device_t _vfs_devices [MAX_DEVICES_COUNT]
dynamic_array_t _vfs_fses
uint32_t root_fs_dev_id
static bool can_cache_inodes = 1
static uint32_t stat_cached_dentries = 0
static uint32_t stat_cached_inodes_area_size = 0
static dentry_cache_list_t * dentry_cache
static uint16_t * dentry_cahced
Macro Definition Documentation
DENTRY_ALLOC_SIZE
#define DENTRY_ALLOC_SIZE (4 * KB) /* Shows the size of list's parts. */
Definition at line 20 of file dentry.c.
DENTRY_SWAP_THRESHOLD_FOR_INODE_CACHE
#define DENTRY_SWAP_THRESHOLD_FOR_INODE_CACHE (16 * KB)
Definition at line 21 of file dentry.c.
Function Documentation
dentry_alloc_new()
static dentry_t* dentry_alloc_new (uint32_t dev_indx, uint32_t inode_indx) static
Definition at line 167 of file dentry.c.
 {
     if (inode_indx == 0) {
         return 0;
     }
     dentry_t* dentry = dentry_cache_find_empty_entry();
     /* If inode_indx isn't 0, so we can say that we replace a valid dentry, which
        has area for storing inode allocated. */
     bool already_allocated_inode = (dentry->inode_indx != 0);
     dentry->d_count = 1;
     dentry->flags = 0;
     dentry->dev_indx = dev_indx;
     dentry->dev = &_vfs_devices[dentry->dev_indx];
     dentry->ops = dynamic_array_get(&_vfs_fses, dentry->dev->fs);
     dentry->inode_indx = inode_indx;
     dentry->fsdata = dentry->ops->dentry.get_fsdata(dentry);
     if (!already_allocated_inode) {
         dentry->inode = (inode_t*)kmalloc(INODE_LEN);
         stat_cached_inodes_area_size += INODE_LEN;
     }
     if (dentry->ops->dentry.read_inode(dentry) < 0) {
         log_error("[Dentry] Can't read inode %d %d (dev, ino)", dev_indx, inode_indx);
         return 0;
     }
     stat_cached_dentries++;
     return dentry;
 }
References _vfs_devices, _vfs_fses, dentry::d_count, fs_ops::dentry, dentry_cache_find_empty_entry(), dentry::dev, dentry::dev_indx, dynamic_array_get(), dentry::flags, vfs_device_t::fs, dentry::fsdata, dentry_ops::get_fsdata, dentry::inode, dentry::inode_indx, INODE_LEN, kmalloc(), log_error(), dentry::ops, dentry_ops::read_inode, stat_cached_dentries, and stat_cached_inodes_area_size.
Referenced by dentry_get().
dentry_cache_alloc()
static void dentry_cache_alloc () static
Definition at line 59 of file dentry.c.
 {
     dentry_cache_list_t* list_block = (dentry_cache_list_t*)kmalloc(DENTRY_ALLOC_SIZE);
     memset((uint8_t*)list_block, 0, DENTRY_ALLOC_SIZE);
     list_block->data = (dentry_t*)&list_block[1];
     list_block->len = DENTRY_ALLOC_SIZE - ((uint32_t)&list_block[1] - (uint32_t)&list_block[0]);
     if (dentry_cache == 0) {
         dentry_cache = list_block;
     } else {
         dentry_cache_list_t* last = dentry_cache;
         while (last->next != 0) {
             last = last->next;
         }
         last->next = list_block;
         list_block->prev = last;
     }
 }
References dentry_cache_list::data, DENTRY_ALLOC_SIZE, dentry_cache, kmalloc(), dentry_cache_list::len, memset(), dentry_cache_list::next, and dentry_cache_list::prev.
Referenced by dentry_cache_find_empty_entry().
dentry_cache_find_empty_entry()
static dentry_t* dentry_cache_find_empty_entry () static
In this function, we try to find an entry to fill it with a new dentry. Since we have a valid dentries in the cache, which isn't held by someone, they are also condidates to be replaced. But because we want to have more valid entries in the cache, we will start to look for a complitely free entry.
Definition at line 84 of file dentry.c.
 {
     dentry_cache_list_t* dentry_cache_block = dentry_cache;
     dentry_t* valid_dentry_candidate = 0;
     while (dentry_cache_block) {
         int dentries_in_block = dentry_cache_block->len / sizeof(dentry_t);
         for (int i = 0; i < dentries_in_block; i++) {
             if (dentry_cache_block->data[i].inode_indx == 0) {
                 return &dentry_cache_block->data[i];
             }
             if (dentry_cache_block->data[i].d_count == 0) {
                 valid_dentry_candidate = &dentry_cache_block->data[i];
             }
         }
         dentry_cache_block = dentry_cache_block->next;
     }
     /* If we hasn't found a complitely free entry, let's erase a
        valid dentries in the cache, which isn't held by someone. */
     if (valid_dentry_candidate) {
         return valid_dentry_candidate;
     }
     /* If there is no space, let's allocate a bigger area. */
     dentry_cache_alloc();
     dentry_cache_list_t* last = dentry_cache;
     while (last->next != 0) {
         last = last->next;
     }
     return &last->data[0];
 }
References dentry::d_count, dentry_cache_list::data, dentry_cache, dentry_cache_alloc(), dentry::inode_indx, dentry_cache_list::len, and dentry_cache_list::next.
Referenced by dentry_alloc_new().
dentry_delete_from_cache()
static void dentry_delete_from_cache (dentry_t * dentry) static
dentry_delete_from_cache compeletly deletes dentry from cache. In case when file was deleted and after that a new was created with the same inode_id, dentry can't recognize and could use old inode data. We need delete dentry from cache and free inode.
Definition at line 136 of file dentry.c.
 {
     /* This marks the dentry as deleted. */
     dentry->inode_indx = 0;
     if (dentry->inode) {
         kfree(dentry->inode);
     }
     stat_cached_inodes_area_size -= INODE_LEN;
     if (!need_to_free_inode_cache()) {
         can_cache_inodes = 1;
     }
 }
References can_cache_inodes, dentry::inode, dentry::inode_indx, INODE_LEN, kfree(), need_to_free_inode_cache(), and stat_cached_inodes_area_size.
Referenced by dentry_prefree(), and dentry_put_impl().
dentry_delete_inode()
static void dentry_delete_inode (dentry_t * dentry) inline static
Definition at line 116 of file dentry.c.
 {
     ASSERT(dentry->d_count == 0 && dentry_test_flag(dentry, DENTRY_INODE_TO_BE_DELETED));
     dentry->ops->dentry.free_inode(dentry);
 }
References ASSERT, dentry::d_count, fs_ops::dentry, DENTRY_INODE_TO_BE_DELETED, dentry_test_flag(), dentry_ops::free_inode, and dentry::ops.
Referenced by dentry_put_impl().
dentry_duplicate()
dentry_t* dentry_duplicate (dentry_t * dentry)
Definition at line 260 of file dentry.c.
 {
     dentry->d_count++;
     return dentry;
 }
References dentry::d_count.
Referenced by dentry_get(), proc_copy_of(), vfs_lookup(), vfs_mount(), vfs_open(), and vfs_resolve_path_start_from().
dentry_flush_inode()
static void dentry_flush_inode (dentry_t * dentry) inline static
Definition at line 122 of file dentry.c.
 {
     if (dentry_test_flag(dentry, DENTRY_DIRTY)) {
         dentry->ops->dentry.write_inode(dentry);
         dentry_rem_flag(dentry, DENTRY_DIRTY);
     }
 }
References fs_ops::dentry, DENTRY_DIRTY, dentry_rem_flag(), dentry_test_flag(), dentry::ops, and dentry_ops::write_inode.
Referenced by dentry_flusher(), and dentry_put_impl().
dentry_flusher()
void dentry_flusher ()
Is a thread enrty point. The function flushes all inodes to drive.
Definition at line 215 of file dentry.c.
 {
     for (;;) {
         dentry_cache_list_t* dentry_cache_block = dentry_cache;
         while (dentry_cache_block) {
             int dentries_in_block = dentry_cache_block->len / sizeof(dentry_t);
             for (int i = 0; i < dentries_in_block; i++) {
                 if (dentry_cache_block->data[i].inode_indx != 0) {
                     system_disable_interrupts();
                     dentry_flush_inode(&dentry_cache_block->data[i]);
                     system_enable_interrupts();
                 }
             }
             dentry_cache_block = dentry_cache_block->next;
         }
         ksys1(SYSSLEEP, 2);
     }
 }
References dentry_cache_list::data, dentry_cache, dentry_flush_inode(), dentry::inode_indx, ksys1, dentry_cache_list::len, dentry_cache_list::next, SYSSLEEP, system_disable_interrupts(), and system_enable_interrupts().
Referenced by launching().
dentry_force_put()
void dentry_force_put (dentry_t * dentry)
Definition at line 291 of file dentry.c.
 {
     if (dentry_test_flag(dentry, DENTRY_MOUNTPOINT)) {
         return;
     }
     dentry->d_count = 0;
     dentry_put_impl(dentry);
 }
References dentry::d_count, DENTRY_MOUNTPOINT, dentry_put_impl(), and dentry_test_flag().
Referenced by dentry_put_all_dentries_of_dev().
dentry_get()
dentry_t* dentry_get (uint32_t dev_indx, uint32_t inode_indx)
There are 3 cases for each entry in a cache array: 1) We have a valid dentry which is held by someone. 2) We have a valid dentry which isn'y held by someone and ready to swapped out. 3) We have an unsed entry in the cache array.
Definition at line 240 of file dentry.c.
 {
     /* We try to find the dentry in the cache */
     dentry_cache_list_t* dentry_cache_block = dentry_cache;
     while (dentry_cache_block) {
         int dentries_in_block = dentry_cache_block->len / sizeof(dentry_t);
         for (int i = 0; i < dentries_in_block; i++) {
             if (dentry_cache_block->data[i].dev_indx == dev_indx && dentry_cache_block->data[i].inode_indx == inode_indx) {
                 if (!dentry_cache_block->data[i].d_count)
                     stat_cached_dentries++;
                 return dentry_duplicate(&dentry_cache_block->data[i]);
             }
         }
         dentry_cache_block = dentry_cache_block->next;
     }
     /* It means no dentry in the cache. Let's add it. */
     return dentry_alloc_new(dev_indx, inode_indx);
 }
References dentry::d_count, dentry_cache_list::data, dentry_alloc_new(), dentry_cache, dentry_duplicate(), dentry::dev_indx, dentry::inode_indx, dentry_cache_list::len, dentry_cache_list::next, and stat_cached_dentries.
Referenced by dentry_get_parent(), ext2_create(), ext2_mkdir(), vfs_lookup(), vfs_mount(), and vfs_resolve_path_start_from().
dentry_get_parent()
dentry_t* dentry_get_parent (dentry_t * dentry)
Definition at line 207 of file dentry.c.
 {
     return dentry_get(dentry->parent_dev_indx, dentry->parent_inode_indx);
 }
References dentry_get(), dentry::parent_dev_indx, and dentry::parent_inode_indx.
Referenced by ext2_rm(), ext2_rmdir(), and proc_load().
dentry_inode_rem_flag()
void dentry_inode_rem_flag (dentry_t * dentry, mode_t mode) inline
Definition at line 353 of file dentry.c.
 {
     if (dentry_inode_test_flag(dentry, mode)) {
         dentry_set_flag(dentry, DENTRY_DIRTY);
     }
     dentry->inode->mode &= ~mode;
 }
References DENTRY_DIRTY, dentry_inode_test_flag(), dentry_set_flag(), dentry::inode, inode_t::mode, and mode.
dentry_inode_set_flag()
void dentry_inode_set_flag (dentry_t * dentry, mode_t mode) inline
Definition at line 340 of file dentry.c.
 {
     if (!dentry_inode_test_flag(dentry, mode)) {
         dentry_set_flag(dentry, DENTRY_DIRTY);
     }
     dentry->inode->mode |= mode;
 }
References DENTRY_DIRTY, dentry_inode_test_flag(), dentry_set_flag(), dentry::inode, inode_t::mode, and mode.
dentry_inode_test_flag()
bool dentry_inode_test_flag (dentry_t * dentry, mode_t mode) inline
Definition at line 348 of file dentry.c.
 {
     return (dentry->inode->mode & mode) > 0;
 }
References dentry::inode, inode_t::mode, and mode.
Referenced by dentry_inode_rem_flag(), dentry_inode_set_flag(), proc_chdir(), vfs_getdents(), vfs_lookup(), vfs_mkdir(), vfs_mount(), vfs_open(), vfs_rmdir(), and vfs_unlink().
dentry_prefree()
static void dentry_prefree (dentry_t * dentry) static
dentry_prefree puts the dentry in a state when it can be safely replaced with a new one. Note: the dentry stays valid and can be reused without needless to read all data again.
Definition at line 155 of file dentry.c.
 {
     if (!can_cache_inodes) {
         dentry_delete_from_cache(dentry);
     } else {
         if (need_to_free_inode_cache()) {
             free_inode_cache();
         }
     }
     stat_cached_dentries--;
 }
References can_cache_inodes, dentry_delete_from_cache(), free_inode_cache(), need_to_free_inode_cache(), and stat_cached_dentries.
Referenced by dentry_put_impl().
dentry_put()
void dentry_put (dentry_t * dentry)
Definition at line 301 of file dentry.c.
 {
     ASSERT(dentry->d_count > 0);
     dentry->d_count--;
     if (dentry->d_count == 0) {
         dentry_put_impl(dentry);
     }
 }
References ASSERT, dentry::d_count, and dentry_put_impl().
Referenced by _kbdriver_notification(), _mouse_recieve_notification(), _syscmd_ls(), bga_recieve_notification(), devfs_mount(), ext2_create(), ext2_mkdir(), proc_chdir(), proc_free(), proc_load(), proc_setup_tty(), procfs(), ptmx_install(), pty_slave_create(), read(), rm(), sys_creat(), sys_open(), sys_rmdir(), sys_unlink(), tty_new(), umount(), vfs_close(), vfs_create(), vfs_resolve_path_start_from(), and vfs_umount().
dentry_put_all_dentries_of_dev()
void dentry_put_all_dentries_of_dev (uint32_t dev_indx)
Definition at line 311 of file dentry.c.
 {
     dentry_cache_list_t* dentry_cache_block = dentry_cache;
     while (dentry_cache_block) {
         int dentries_in_block = dentry_cache_block->len / sizeof(dentry_t);
         for (int i = 0; i < dentries_in_block; i++) {
             if (dentry_cache_block->data[i].dev_indx == dev_indx && dentry_cache_block->data[i].inode != 0) {
                 dentry_force_put(&dentry_cache_block->data[i]);
             }
         }
         dentry_cache_block = dentry_cache_block->next;
     }
 }
References dentry_cache_list::data, dentry_cache, dentry_force_put(), dentry::dev_indx, dentry::inode, dentry_cache_list::len, and dentry_cache_list::next.
Referenced by vfs_eject_device().
dentry_put_impl()
static void dentry_put_impl (dentry_t * dentry) inline static
Definition at line 266 of file dentry.c.
 {
     if (dentry_test_flag(dentry, DENTRY_CUSTOM)) {
         dentry->inode_indx = 0;
         if (dentry->ops->dentry.free_inode) {
             dentry->ops->dentry.free_inode(dentry);
         }
         return;
     }
     if (dentry_test_flag(dentry, DENTRY_INODE_TO_BE_DELETED)) {
 #ifdef DENTRY_DEBUG
         log("Inode delete %d", dentry->inode_indx);
 #endif
         dentry_delete_inode(dentry);
         dentry_delete_from_cache(dentry);
         return;
     }
 #ifdef DENTRY_DEBUG
     log("Inode flushed %d", dentry->inode_indx);
 #endif
     dentry_flush_inode(dentry);
     dentry_prefree(dentry);
 }
References fs_ops::dentry, DENTRY_CUSTOM, dentry_delete_from_cache(), dentry_delete_inode(), dentry_flush_inode(), DENTRY_INODE_TO_BE_DELETED, dentry_prefree(), dentry_test_flag(), dentry_ops::free_inode, dentry::inode_indx, log(), and dentry::ops.
Referenced by dentry_force_put(), and dentry_put().
dentry_rem_flag()
void dentry_rem_flag (dentry_t * dentry, uint32_t flag) inline
Definition at line 335 of file dentry.c.
 {
     dentry->flags &= ~flag;
 }
References dentry::flags.
Referenced by dentry_flush_inode(), and vfs_umount().
dentry_set_flag()
void dentry_set_flag (dentry_t * dentry, uint32_t flag) inline
Definition at line 325 of file dentry.c.
 {
     dentry->flags |= flag;
 }
References dentry::flags.
Referenced by _ext2_add_child(), _ext2_allocate_block_for_inode(), _ext2_rm_child(), _ext2_set_block_of_inode(), _ext2_setup_dir(), _ext2_setup_file(), dentry_inode_rem_flag(), dentry_inode_set_flag(), devfs_mkdir(), devfs_register(), ext2_truncate(), ext2_write(), pty_master_alloc(), vfs_mount(), vfs_rmdir(), and vfs_unlink().
dentry_set_parent()
void dentry_set_parent (dentry_t * to, dentry_t * parent)
Definition at line 201 of file dentry.c.
 {
     to->parent_inode_indx = parent->inode_indx;
     to->parent_dev_indx = parent->dev_indx;
 }
References dentry::dev_indx, dentry::inode_indx, dentry::parent_dev_indx, and dentry::parent_inode_indx.
Referenced by vfs_resolve_path_start_from().
dentry_stat_cached_count()
uint32_t dentry_stat_cached_count ()
Definition at line 361 of file dentry.c.
 {
     return stat_cached_dentries;
 }
References stat_cached_dentries.
Referenced by dentries_stat().
dentry_test_flag()
bool dentry_test_flag (dentry_t * dentry, uint32_t flag) inline
Definition at line 330 of file dentry.c.
 {
     return (dentry->flags & flag) > 0;
 }
References dentry::flags.
Referenced by dentry_delete_inode(), dentry_flush_inode(), dentry_force_put(), dentry_put_impl(), vfs_lookup(), vfs_mount(), vfs_open(), vfs_resolve_path_start_from(), vfs_rmdir(), and vfs_umount().
free_inode_cache()
static bool free_inode_cache () inline static
Definition at line 38 of file dentry.c.
 {
     dentry_cache_list_t* dentry_cache_block = dentry_cache;
     dentry_t* valid_dentry_candidate = 0;
     while (dentry_cache_block) {
         int dentries_in_block = dentry_cache_block->len / sizeof(dentry_t);
         for (int i = 0; i < dentries_in_block; i++) {
             if (dentry_cache_block->data[i].d_count == 0) {
                 dentry_cache_block->data[i].inode_indx = 0;
                 stat_cached_inodes_area_size -= INODE_LEN;
                 kfree(dentry_cache_block->data[i].inode);
             }
         }
         dentry_cache_block = dentry_cache_block->next;
     }
     if (need_to_free_inode_cache()) {
         can_cache_inodes = 0;
     }
 }
References can_cache_inodes, dentry::d_count, dentry_cache_list::data, dentry_cache, dentry::inode, dentry::inode_indx, INODE_LEN, kfree(), dentry_cache_list::len, need_to_free_inode_cache(), dentry_cache_list::next, and stat_cached_inodes_area_size.
Referenced by dentry_prefree().
need_to_free_inode_cache()
static bool need_to_free_inode_cache () inline static
Definition at line 33 of file dentry.c.
 {
     return (stat_cached_inodes_area_size > DENTRY_SWAP_THRESHOLD_FOR_INODE_CACHE);
 }
References DENTRY_SWAP_THRESHOLD_FOR_INODE_CACHE, and stat_cached_inodes_area_size.
Referenced by dentry_delete_from_cache(), dentry_prefree(), and free_inode_cache().
Variable Documentation
_vfs_devices
vfs_device_t _vfs_devices[MAX_DEVICES_COUNT] extern
Definition at line 21 of file vfs.c.
Referenced by dentry_alloc_new(), vfs_add_dev(), vfs_add_dev_with_fs(), vfs_choose_fs_of_dev(), and vfs_eject_device().
_vfs_fses
dynamic_array_t _vfs_fses extern
Definition at line 22 of file vfs.c.
Referenced by dentry_alloc_new(), vfs_add_dev_with_fs(), vfs_add_fs(), vfs_choose_fs_of_dev(), vfs_eject_device(), and vfs_install().
can_cache_inodes
bool can_cache_inodes = 1 static
Definition at line 27 of file dentry.c.
Referenced by dentry_delete_from_cache(), dentry_prefree(), and free_inode_cache().
dentry_cache
dentry_cache_list_t* dentry_cache static
Definition at line 30 of file dentry.c.
Referenced by dentry_cache_alloc(), dentry_cache_find_empty_entry(), dentry_flusher(), dentry_get(), dentry_put_all_dentries_of_dev(), and free_inode_cache().
dentry_cahced
uint16_t* dentry_cahced static
Definition at line 31 of file dentry.c.
root_fs_dev_id
uint32_t root_fs_dev_id extern
Definition at line 23 of file vfs.c.
Referenced by vfs_add_dev(), vfs_add_dev_with_fs(), and vfs_resolve_path_start_from().
stat_cached_dentries
uint32_t stat_cached_dentries = 0 static
Definition at line 28 of file dentry.c.
Referenced by dentry_alloc_new(), dentry_get(), dentry_prefree(), and dentry_stat_cached_count().
stat_cached_inodes_area_size
uint32_t stat_cached_inodes_area_size = 0 static
Definition at line 29 of file dentry.c.
Referenced by dentry_alloc_new(), dentry_delete_from_cache(), free_inode_cache(), and need_to_free_inode_cache().