oneOS: src/kernel/fs/devfs/devfs.c File Reference
devfs.c File Reference
#include <algo/dynamic_array.h>
#include <drivers/driver_manager.h>
#include <errno.h>
#include <fs/devfs/devfs.h>
#include <log.h>
#include <mem/kmalloc.h>
#include <tasking/proc.h>
Macros
#define DEVFS_ZONE_SIZE 32 * KB
Functions
static int _devfs_alloc_entry_zone ()
static int _devfs_alloc_name_zone ()
static devfs_inode_t * _devfs_get_entry (uint32_t indx)
static devfs_inode_t * _devfs_new_entry ()
static char * _devfs_new_name (int len)
static devfs_inode_t * _devfs_get_devfs_inode (uint32_t inode_indx)
static int _devfs_add_to_list (devfs_inode_t *parent, devfs_inode_t *new_entry)
static devfs_inode_t * _devfs_alloc_entry (devfs_inode_t *parent)
static int _devfs_set_name (devfs_inode_t *entry, const char *name, uint32_t len)
static int _devfs_setup_root ()
fsdata_t devfs_data (dentry_t *dentry)
int devfs_prepare_fs (vfs_device_t *vdev)
int devfs_read_inode (dentry_t *dentry)
int devfs_write_inode (dentry_t *dentry)
int devfs_free_inode (dentry_t *dentry)
int devfs_getdents (dentry_t *dir, uint8_t *buf, uint32_t *offset, uint32_t len)
int devfs_lookup (dentry_t *dir, const char *name, uint32_t len, uint32_t *res_inode_indx)
int devfs_mkdir_dummy (dentry_t *dir, const char *name, uint32_t len, mode_t mode)
int devfs_rmdir_dummy (dentry_t *dir)
int devfs_open (dentry_t *dentry, file_descriptor_t *fd, uint32_t flags)
int devfs_can_read (dentry_t *dentry, uint32_t start)
int devfs_can_write (dentry_t *dentry, uint32_t start)
int devfs_read (dentry_t *dentry, uint8_t *buf, uint32_t start, uint32_t len)
int devfs_write (dentry_t *dentry, uint8_t *buf, uint32_t start, uint32_t len)
int devfs_ioctl (dentry_t *dentry, uint32_t cmd, uint32_t arg)
proc_zone_t * devfs_mmap (dentry_t *dentry, mmap_params_t *params)
driver_desc_t _devfs_driver_info ()
void devfs_install ()
devfs_inode_t * devfs_mkdir (dentry_t *dir, const char *name, uint32_t len)
devfs_inode_t * devfs_register (dentry_t *dir, const char *name, uint32_t len, mode_t mode, const file_ops_t *handlers)
int devfs_mount ()
Variables
static dynamic_array_t entry_zones
static void * next_space_to_put_entry
static uint32_t free_space_in_last_entry_zone
static dynamic_array_t name_zones
static void * next_space_to_put_name
static uint32_t free_space_in_last_name_zone
static devfs_inode_t * devfs_root
static uint32_t next_inode_index = 2
Macro Definition Documentation
DEVFS_ZONE_SIZE
#define DEVFS_ZONE_SIZE 32 * KB
Definition at line 17 of file devfs.c.
Function Documentation
_devfs_add_to_list()
static int _devfs_add_to_list (devfs_inode_t * parent, devfs_inode_t * new_entry) static
Inode Tools
Definition at line 121 of file devfs.c.
 {
     if (!parent || !new_entry) {
         return -EINVAL;
     }
     if (!parent->last) {
         parent->first = new_entry;
         parent->last = new_entry;
         new_entry->prev = 0;
         new_entry->next = 0;
     } else {
         parent->last->next = new_entry;
         new_entry->prev = parent->last;
         parent->last = new_entry;
         new_entry->next = 0;
     }
     new_entry->parent = parent;
     return 0;
 }
References EINVAL, devfs_inode::first, devfs_inode::last, devfs_inode::next, devfs_inode::parent, and devfs_inode::prev.
Referenced by _devfs_alloc_entry().
_devfs_alloc_entry()
static devfs_inode_t* _devfs_alloc_entry (devfs_inode_t * parent) static
Definition at line 144 of file devfs.c.
 {
     devfs_inode_t* new_entry = _devfs_new_entry();
     if (!new_entry) {
         return 0;
     }
     if (_devfs_add_to_list(parent, new_entry) < 0) {
         /* Bringing back allocation */
         next_space_to_put_entry -= sizeof(devfs_inode_t);
         free_space_in_last_entry_zone += sizeof(devfs_inode_t);
         return 0;
     }
     return new_entry;
 }
References _devfs_add_to_list(), _devfs_new_entry(), free_space_in_last_entry_zone, and next_space_to_put_entry.
Referenced by devfs_mkdir(), and devfs_register().
_devfs_alloc_entry_zone()
static int _devfs_alloc_entry_zone () static
Zones Managment
Definition at line 35 of file devfs.c.
 {
     void* new_zone = kmalloc(DEVFS_ZONE_SIZE);
     if (!new_zone) {
         return ENOMEM;
     }
     dynamic_array_push(&entry_zones, &new_zone);
     next_space_to_put_entry = new_zone;
     free_space_in_last_entry_zone = DEVFS_ZONE_SIZE;
     return 0;
 }
References DEVFS_ZONE_SIZE, dynamic_array_push(), ENOMEM, entry_zones, free_space_in_last_entry_zone, kmalloc(), and next_space_to_put_entry.
Referenced by _devfs_new_entry().
_devfs_alloc_name_zone()
static int _devfs_alloc_name_zone () static
Definition at line 48 of file devfs.c.
 {
     void* new_zone = kmalloc(DEVFS_ZONE_SIZE);
     if (!new_zone) {
         return -ENOMEM;
     }
     dynamic_array_push(&name_zones, &new_zone);
     next_space_to_put_name = new_zone;
     free_space_in_last_name_zone = DEVFS_ZONE_SIZE;
     return 0;
 }
References DEVFS_ZONE_SIZE, dynamic_array_push(), ENOMEM, free_space_in_last_name_zone, kmalloc(), name_zones, and next_space_to_put_name.
Referenced by _devfs_new_name().
_devfs_driver_info()
driver_desc_t _devfs_driver_info ()
Driver install functions.
Definition at line 455 of file devfs.c.
 {
     driver_desc_t fs_desc;
     fs_desc.type = DRIVER_FILE_SYSTEM;
     fs_desc.auto_start = false;
     fs_desc.is_device_driver = false;
     fs_desc.is_device_needed = false;
     fs_desc.is_driver_needed = false;
     fs_desc.functions[DRIVER_NOTIFICATION] = 0;
     fs_desc.functions[DRIVER_FILE_SYSTEM_RECOGNIZE] = 0;
     fs_desc.functions[DRIVER_FILE_SYSTEM_PREPARE_FS] = devfs_prepare_fs;
     fs_desc.functions[DRIVER_FILE_SYSTEM_CAN_READ] = devfs_can_read;
     fs_desc.functions[DRIVER_FILE_SYSTEM_CAN_WRITE] = devfs_can_write;
     fs_desc.functions[DRIVER_FILE_SYSTEM_OPEN] = devfs_open;
     fs_desc.functions[DRIVER_FILE_SYSTEM_READ] = devfs_read;
     fs_desc.functions[DRIVER_FILE_SYSTEM_WRITE] = devfs_write;
     fs_desc.functions[DRIVER_FILE_SYSTEM_TRUNCATE] = 0;
     fs_desc.functions[DRIVER_FILE_SYSTEM_MKDIR] = devfs_mkdir_dummy;
     fs_desc.functions[DRIVER_FILE_SYSTEM_RMDIR] = devfs_rmdir_dummy;
     fs_desc.functions[DRIVER_FILE_SYSTEM_EJECT_DEVICE] = 0;
     fs_desc.functions[DRIVER_FILE_SYSTEM_READ_INODE] = devfs_read_inode;
     fs_desc.functions[DRIVER_FILE_SYSTEM_WRITE_INODE] = devfs_write_inode;
     fs_desc.functions[DRIVER_FILE_SYSTEM_FREE_INODE] = devfs_free_inode;
     fs_desc.functions[DRIVER_FILE_SYSTEM_GET_FSDATA] = devfs_data;
     fs_desc.functions[DRIVER_FILE_SYSTEM_LOOKUP] = devfs_lookup;
     fs_desc.functions[DRIVER_FILE_SYSTEM_GETDENTS] = devfs_getdents;
     fs_desc.functions[DRIVER_FILE_SYSTEM_CREATE] = 0;
     fs_desc.functions[DRIVER_FILE_SYSTEM_UNLINK] = 0;
     fs_desc.functions[DRIVER_FILE_SYSTEM_IOCTL] = devfs_ioctl;
     fs_desc.functions[DRIVER_FILE_SYSTEM_MMAP] = devfs_mmap;
     return fs_desc;
 }
References driver_desc_t::auto_start, devfs_can_read(), devfs_can_write(), devfs_data(), devfs_free_inode(), devfs_getdents(), devfs_ioctl(), devfs_lookup(), devfs_mkdir_dummy(), devfs_mmap(), devfs_open(), devfs_prepare_fs(), devfs_read(), devfs_read_inode(), devfs_rmdir_dummy(), devfs_write(), devfs_write_inode(), DRIVER_FILE_SYSTEM, DRIVER_FILE_SYSTEM_CAN_READ, DRIVER_FILE_SYSTEM_CAN_WRITE, DRIVER_FILE_SYSTEM_CREATE, DRIVER_FILE_SYSTEM_EJECT_DEVICE, DRIVER_FILE_SYSTEM_FREE_INODE, DRIVER_FILE_SYSTEM_GET_FSDATA, DRIVER_FILE_SYSTEM_GETDENTS, DRIVER_FILE_SYSTEM_IOCTL, DRIVER_FILE_SYSTEM_LOOKUP, DRIVER_FILE_SYSTEM_MKDIR, DRIVER_FILE_SYSTEM_MMAP, DRIVER_FILE_SYSTEM_OPEN, DRIVER_FILE_SYSTEM_PREPARE_FS, DRIVER_FILE_SYSTEM_READ, DRIVER_FILE_SYSTEM_READ_INODE, DRIVER_FILE_SYSTEM_RECOGNIZE, DRIVER_FILE_SYSTEM_RMDIR, DRIVER_FILE_SYSTEM_TRUNCATE, DRIVER_FILE_SYSTEM_UNLINK, DRIVER_FILE_SYSTEM_WRITE, DRIVER_FILE_SYSTEM_WRITE_INODE, DRIVER_NOTIFICATION, driver_desc_t::functions, driver_desc_t::is_device_driver, driver_desc_t::is_device_needed, driver_desc_t::is_driver_needed, and driver_desc_t::type.
Referenced by devfs_install().
_devfs_get_devfs_inode()
static devfs_inode_t* _devfs_get_devfs_inode (uint32_t inode_indx) inline static
Definition at line 109 of file devfs.c.
 {
     /*  Since in vfs, we use a rule that 2nd inode is a root inode, so, let's
         follow this rule here. But in our storage elements are indexed from 0,
         so we need put up with this. */
     return _devfs_get_entry(inode_indx - 2);
 }
References _devfs_get_entry().
Referenced by devfs_read_inode(), and devfs_write_inode().
_devfs_get_entry()
static devfs_inode_t* _devfs_get_entry (uint32_t indx) static
Definition at line 61 of file devfs.c.
 {
     uint32_t entries_per_zone = DEVFS_ZONE_SIZE / DEVFS_INODE_LEN;
     uint32_t zones_count = entry_zones.size;
     if (indx >= zones_count * entries_per_zone) {
         return 0;
     }
     uint32_t requested_zone = indx / entries_per_zone;
     uint32_t index_within_zone = indx % entries_per_zone;
     uint32_t* tmp_ptr = dynamic_array_get(&entry_zones, requested_zone);
     devfs_inode_t* res = (devfs_inode_t*)*tmp_ptr;
     if (!res) {
         return 0;
     }
     return &res[index_within_zone];
 }
References DEVFS_INODE_LEN, DEVFS_ZONE_SIZE, dynamic_array_get(), entry_zones, and dynamic_array::size.
Referenced by _devfs_get_devfs_inode().
_devfs_new_entry()
static devfs_inode_t* _devfs_new_entry () static
Memory Allocation
Definition at line 83 of file devfs.c.
 {
     if (free_space_in_last_entry_zone < sizeof(devfs_inode_t)) {
         _devfs_alloc_entry_zone();
     }
     devfs_inode_t* res = (devfs_inode_t*)next_space_to_put_entry;
     res->index = next_inode_index++;
     next_space_to_put_entry += sizeof(devfs_inode_t);
     free_space_in_last_entry_zone -= sizeof(devfs_inode_t);
     return res;
 }
References _devfs_alloc_entry_zone(), free_space_in_last_entry_zone, devfs_inode::index, next_inode_index, and next_space_to_put_entry.
Referenced by _devfs_alloc_entry(), and _devfs_setup_root().
_devfs_new_name()
static char* _devfs_new_name (int len) static
Definition at line 96 of file devfs.c.
 {
     if (free_space_in_last_name_zone < len + 1) {
         _devfs_alloc_name_zone();
     }
     char* res = (char*)next_space_to_put_name;
     next_space_to_put_name += len + 1;
     free_space_in_last_name_zone -= len + 1;
     memset(res, 0, len + 1);
     return res;
 }
References _devfs_alloc_name_zone(), free_space_in_last_name_zone, memset(), and next_space_to_put_name.
Referenced by _devfs_set_name().
_devfs_set_name()
static int _devfs_set_name (devfs_inode_t * entry, const char * name, uint32_t len) static
Definition at line 159 of file devfs.c.
 {
     if (!entry || !name) {
         return -EINVAL;
     }
     if (len > 255) {
         return -2;
     }
     char* name_space = _devfs_new_name(len);
     if (!name_space) {
         return -ENOMEM;
     }
     memcpy((void*)name_space, (void*)name, len);
     entry->name = name_space;
     return 0;
 }
References _devfs_new_name(), EINVAL, ENOMEM, memcpy(), devfs_inode::name, and copy_bin::name.
Referenced by devfs_mkdir(), and devfs_register().
_devfs_setup_root()
static int _devfs_setup_root () static
FS Tools
Definition at line 182 of file devfs.c.
 {
     devfs_root = _devfs_new_entry();
     memset((void*)devfs_root, 0, DEVFS_INODE_LEN);
     devfs_root->index = 2;
     devfs_root->mode = S_IFDIR;
     return 0;
 }
References _devfs_new_entry(), DEVFS_INODE_LEN, devfs_root, devfs_inode::index, memset(), devfs_inode::mode, and S_IFDIR.
Referenced by devfs_prepare_fs().
devfs_can_read()
int devfs_can_read (dentry_t * dentry, uint32_t start)
Definition at line 396 of file devfs.c.
 {
     devfs_inode_t* devfs_inode = (devfs_inode_t*)dentry->inode;
     if (devfs_inode->handlers.can_read) {
         return devfs_inode->handlers.can_read(dentry, start);
     }
     return true;
 }
References file_ops::can_read, devfs_inode::handlers, and dentry::inode.
Referenced by _devfs_driver_info().
devfs_can_write()
int devfs_can_write (dentry_t * dentry, uint32_t start)
Definition at line 405 of file devfs.c.
 {
     devfs_inode_t* devfs_inode = (devfs_inode_t*)dentry->inode;
     if (devfs_inode->handlers.can_write) {
         return devfs_inode->handlers.can_write(dentry, start);
     }
     return true;
 }
References file_ops::can_write, devfs_inode::handlers, and dentry::inode.
Referenced by _devfs_driver_info().
devfs_data()
fsdata_t devfs_data (dentry_t * dentry)
VFS Api
Definition at line 195 of file devfs.c.
 {
     /* Set everything to 0, since devfs isn't supposed to be used by several devices.
        All of mount of devfs will show the same info. */
     fsdata_t fsdata;
     fsdata.sb = 0;
     fsdata.gt = 0;
     return fsdata;
 }
References fsdata_t::gt, and fsdata_t::sb.
Referenced by _devfs_driver_info().
devfs_free_inode()
int devfs_free_inode (dentry_t * dentry)
Definition at line 235 of file devfs.c.
 {
     return 0;
 }
Referenced by _devfs_driver_info().
devfs_getdents()
int devfs_getdents (dentry_t * dir, uint8_t * buf, uint32_t * offset, uint32_t len)
Definition at line 240 of file devfs.c.
 {
     devfs_inode_t* devfs_inode = (devfs_inode_t*)dir->inode;
     /* Currently we leave, dir when offset is the max number. */
     if (*offset == 0xffffffff) {
         return 0;
     }
     int already_read = 0;
     dirent_t tmp;
     tmp.name = 0;
     /* Return . */
     if (*offset == 0) {
         int rec_len = 8 + 1 + 1;
         if (len < rec_len) {
             if (already_read) {
                 return already_read;
             } else {
                 return -EINVAL;
             }
         }
         tmp.inode = devfs_inode->index;
         tmp.rec_len = rec_len;
         tmp.name_len = 1;
         memcpy(buf + already_read, (void*)&tmp, 8);
         memcpy(buf + already_read + 8, ".", 1);
         buf[already_read + rec_len - 1] = '\0';
         already_read += rec_len;
         len -= rec_len;
         *offset = 1;
     }
     /* Return .. */
     if (*offset == 1) {
         int rec_len = 8 + 2 + 1;
         if (len < rec_len) {
             if (already_read) {
                 return already_read;
             } else {
                 return -EINVAL;
             }
         }
         if (devfs_inode->parent) {
             tmp.inode = devfs_inode->parent->index;
         } else {
             tmp.inode = devfs_inode->index;
         }
         tmp.rec_len = rec_len;
         tmp.name_len = 2;
         memcpy(buf + already_read, (void*)&tmp, 8);
         memcpy(buf + already_read + 8, "..", 2);
         buf[already_read + rec_len - 1] = '\0';
         already_read += rec_len;
         len -= rec_len;
         *offset = 2;
     }
     /* Scanining dir from the start */
     if (*offset == 2) {
         if (!devfs_inode->first) {
             return 0;
         }
         *offset = (uint32_t)devfs_inode->first;
     }
     while (*offset != 0xffffffff) {
         devfs_inode_t* child_devfs_inode = (devfs_inode_t*)*offset;
         uint32_t name_len = strlen(child_devfs_inode->name);
         int rec_len = 8 + name_len + 1;
         if (len < rec_len) {
             if (already_read) {
                 return already_read;
             } else {
                 return -EINVAL;
             }
         }
         tmp.inode = child_devfs_inode->index;
         tmp.rec_len = rec_len;
         tmp.name_len = name_len;
         memcpy(buf + already_read, (void*)&tmp, 8);
         memcpy(buf + already_read + 8, child_devfs_inode->name, name_len);
         buf[already_read + rec_len - 1] = '\0';
         already_read += rec_len;
         len -= rec_len;
         if (child_devfs_inode->next) {
             *offset = (uint32_t)child_devfs_inode->next;
         } else {
             *offset = 0xffffffff;
         }
     }
     return already_read;
 }
References buf, EINVAL, devfs_inode::first, devfs_inode::index, dirent::inode, dentry::inode, memcpy(), devfs_inode::name, dirent::name, dirent::name_len, devfs_inode::next, devfs_inode::parent, dirent::rec_len, and strlen().
Referenced by _devfs_driver_info().
devfs_install()
void devfs_install ()
Definition at line 490 of file devfs.c.
 {
     driver_install(_devfs_driver_info());
 }
References _devfs_driver_info(), and driver_install().
Referenced by stage3().
devfs_ioctl()
int devfs_ioctl (dentry_t * dentry, uint32_t cmd, uint32_t arg)
Definition at line 432 of file devfs.c.
 {
     devfs_inode_t* devfs_inode = (devfs_inode_t*)dentry->inode;
     if (devfs_inode->handlers.ioctl) {
         return devfs_inode->handlers.ioctl(dentry, cmd, arg);
     }
     return -EFAULT;
 }
References cmd, EFAULT, devfs_inode::handlers, dentry::inode, and file_ops::ioctl.
Referenced by _devfs_driver_info().
devfs_lookup()
int devfs_lookup (dentry_t * dir, const char * name, uint32_t len, uint32_t * res_inode_indx)
Definition at line 342 of file devfs.c.
 {
     devfs_inode_t* devfs_inode = (devfs_inode_t*)dir->inode;
     if (len == 1) {
         if (name[0] == '.') {
             *res_inode_indx = devfs_inode->index;
             return 0;
         }
     }
     if (len == 2) {
         if (name[0] == '.' && name[1] == '.') {
             *res_inode_indx = devfs_inode->parent->index;
             return 0;
         }
     }
     devfs_inode_t* child = devfs_inode->first;
     while (child) {
         uint32_t child_name_len = strlen(child->name);
         if (len == child_name_len) {
             if (strncmp(name, child->name, len) == 0) {
                 *res_inode_indx = child->index;
                 return 0;
             }
         }
         child = child->next;
     }
     return -ENOENT;
 }
References ENOENT, devfs_inode::first, devfs_inode::index, dentry::inode, devfs_inode::name, copy_bin::name, devfs_inode::next, devfs_inode::parent, strlen(), and strncmp().
Referenced by _devfs_driver_info().
devfs_mkdir()
devfs_inode_t* devfs_mkdir (dentry_t * dir, const char * name, uint32_t len)
Register a device.
Definition at line 499 of file devfs.c.
 {
     devfs_inode_t* devfs_inode = (devfs_inode_t*)dir->inode;
     devfs_inode_t* new_entry = _devfs_alloc_entry(devfs_inode);
     if (!new_entry) {
         return 0;
     }
     dentry_set_flag(dir, DENTRY_DIRTY);
     new_entry->mode = S_IFDIR;
     _devfs_set_name(new_entry, name, len);
     return new_entry;
 }
References _devfs_alloc_entry(), _devfs_set_name(), DENTRY_DIRTY, dentry_set_flag(), dentry::inode, copy_bin::name, and S_IFDIR.
devfs_mkdir_dummy()
int devfs_mkdir_dummy (dentry_t * dir, const char * name, uint32_t len, mode_t mode)
Definition at line 375 of file devfs.c.
 {
     return -1;
 }
Referenced by _devfs_driver_info().
devfs_mmap()
proc_zone_t* devfs_mmap (dentry_t * dentry, mmap_params_t * params)
Definition at line 441 of file devfs.c.
 {
     devfs_inode_t* devfs_inode = (devfs_inode_t*)dentry->inode;
     if (devfs_inode->handlers.mmap) {
         return devfs_inode->handlers.mmap(dentry, params);
     }
     /* If we don't have a custom impl, let's used a std one */
     return (proc_zone_t*)VFS_USE_STD_MMAP;
 }
References devfs_inode::handlers, dentry::inode, file_ops::mmap, and VFS_USE_STD_MMAP.
Referenced by _devfs_driver_info().
devfs_mount()
int devfs_mount ()
Definition at line 531 of file devfs.c.
 {
     dentry_t* mp;
     if (vfs_resolve_path("/dev", &mp) < 0) {
         return -ENOENT;
     }
     int err = vfs_mount(mp, new_virtual_device(DEVICE_STORAGE), 2);
     dentry_put(mp);
     if (!err) {
         dm_send_notification(DM_NOTIFICATION_DEVFS_READY, 0);
     }
     return err;
 }
References dentry_put(), DEVICE_STORAGE, DM_NOTIFICATION_DEVFS_READY, dm_send_notification(), ENOENT, new_virtual_device(), vfs_mount(), and vfs_resolve_path().
Referenced by stage3().
devfs_open()
int devfs_open (dentry_t * dentry, file_descriptor_t * fd, uint32_t flags)
Definition at line 385 of file devfs.c.
 {
     devfs_inode_t* devfs_inode = (devfs_inode_t*)dentry->inode;
     if (devfs_inode->handlers.open) {
         return devfs_inode->handlers.open(dentry, fd, flags);
     }
     /*  The device doesn't have custom open, so returns ENOEXEC in this case
         according to vfs. */
     return -ENOEXEC;
 }
References ENOEXEC, devfs_inode::handlers, dentry::inode, and file_ops::open.
Referenced by _devfs_driver_info().
devfs_prepare_fs()
int devfs_prepare_fs (vfs_device_t * vdev)
Definition at line 205 of file devfs.c.
 {
     dynamic_array_init(&name_zones, sizeof(void*));
     dynamic_array_init(&entry_zones, sizeof(void*));
     _devfs_setup_root();
     return 0;
 }
References _devfs_setup_root(), dynamic_array_init(), entry_zones, and name_zones.
Referenced by _devfs_driver_info().
devfs_read()
int devfs_read (dentry_t * dentry, uint8_t * buf, uint32_t start, uint32_t len)
Definition at line 414 of file devfs.c.
 {
     devfs_inode_t* devfs_inode = (devfs_inode_t*)dentry->inode;
     if (devfs_inode->handlers.read) {
         return devfs_inode->handlers.read(dentry, buf, start, len);
     }
     return -EFAULT;
 }
References buf, EFAULT, devfs_inode::handlers, dentry::inode, and file_ops::read.
Referenced by _devfs_driver_info().
devfs_read_inode()
int devfs_read_inode (dentry_t * dentry)
Definition at line 213 of file devfs.c.
 {
     /*  We currently has a uniqueue structure of inode for devfs. So we need to be
         confident using inode in vfs, since inode and devfs_inode are not similar. */
     devfs_inode_t* devfs_inode = _devfs_get_devfs_inode(dentry->inode_indx);
     if (!devfs_inode) {
         return -EFAULT;
     }
     memcpy((void*)dentry->inode, (void*)devfs_inode, DEVFS_INODE_LEN);
     return 0;
 }
References _devfs_get_devfs_inode(), DEVFS_INODE_LEN, EFAULT, dentry::inode, dentry::inode_indx, and memcpy().
Referenced by _devfs_driver_info().
devfs_register()
devfs_inode_t* devfs_register (dentry_t * dir, const char * name, uint32_t len, mode_t mode, const file_ops_t * handlers)
Definition at line 515 of file devfs.c.
 {
     devfs_inode_t* devfs_inode = (devfs_inode_t*)dir->inode;
     devfs_inode_t* new_entry = _devfs_alloc_entry(devfs_inode);
     if (!new_entry) {
         return 0;
     }
     new_entry->mode = mode;
     _devfs_set_name(new_entry, name, len);
     memcpy((void*)&new_entry->handlers, (void*)handlers, sizeof(*handlers));
     dentry_set_flag(dir, DENTRY_DIRTY);
     return new_entry;
 }
References _devfs_alloc_entry(), _devfs_set_name(), DENTRY_DIRTY, dentry_set_flag(), handlers, dentry::inode, memcpy(), devfs_inode::mode, mode, and copy_bin::name.
devfs_rmdir_dummy()
int devfs_rmdir_dummy (dentry_t * dir)
Definition at line 380 of file devfs.c.
 {
     return -1;
 }
Referenced by _devfs_driver_info().
devfs_write()
int devfs_write (dentry_t * dentry, uint8_t * buf, uint32_t start, uint32_t len)
Definition at line 423 of file devfs.c.
 {
     devfs_inode_t* devfs_inode = (devfs_inode_t*)dentry->inode;
     if (devfs_inode->handlers.write) {
         return devfs_inode->handlers.write(dentry, buf, start, len);
     }
     return -EFAULT;
 }
References buf, EFAULT, devfs_inode::handlers, dentry::inode, and file_ops::write.
Referenced by _devfs_driver_info().
devfs_write_inode()
int devfs_write_inode (dentry_t * dentry)
Definition at line 225 of file devfs.c.
 {
     devfs_inode_t* devfs_inode = _devfs_get_devfs_inode(dentry->inode_indx);
     if (!devfs_inode) {
         return -EFAULT;
     }
     memcpy((void*)devfs_inode, (void*)dentry->inode, DEVFS_INODE_LEN);
     return 0;
 }
References _devfs_get_devfs_inode(), DEVFS_INODE_LEN, EFAULT, dentry::inode, dentry::inode_indx, and memcpy().
Referenced by _devfs_driver_info().
Variable Documentation
devfs_root
devfs_inode_t* devfs_root static
Definition at line 27 of file devfs.c.
Referenced by _devfs_setup_root().
entry_zones
dynamic_array_t entry_zones static
Definition at line 19 of file devfs.c.
Referenced by _devfs_alloc_entry_zone(), _devfs_get_entry(), and devfs_prepare_fs().
free_space_in_last_entry_zone
uint32_t free_space_in_last_entry_zone static
Definition at line 21 of file devfs.c.
Referenced by _devfs_alloc_entry(), _devfs_alloc_entry_zone(), and _devfs_new_entry().
free_space_in_last_name_zone
uint32_t free_space_in_last_name_zone static
Definition at line 25 of file devfs.c.
Referenced by _devfs_alloc_name_zone(), and _devfs_new_name().
name_zones
dynamic_array_t name_zones static
Definition at line 23 of file devfs.c.
Referenced by _devfs_alloc_name_zone(), and devfs_prepare_fs().
next_inode_index
uint32_t next_inode_index = 2 static
Definition at line 29 of file devfs.c.
Referenced by _devfs_new_entry().
next_space_to_put_entry
void* next_space_to_put_entry static
Definition at line 20 of file devfs.c.
Referenced by _devfs_alloc_entry(), _devfs_alloc_entry_zone(), and _devfs_new_entry().
next_space_to_put_name
void* next_space_to_put_name static
Definition at line 24 of file devfs.c.
Referenced by _devfs_alloc_name_zone(), and _devfs_new_name().