oneOS: include/fs/devfs/devfs.h File Reference
devfs.h File Reference
#include <types.h>
#include <fs/vfs.h>
Data Structures
struct devfs_inode
Macros
#define DEVFS_INODE_LEN (sizeof(struct devfs_inode))
Typedefs
typedef struct devfs_inode devfs_inode_t
Functions
void devfs_install ()
int devfs_mount ()
devfs_inode_t * devfs_mkdir (dentry_t *dir, const char *name, uint32_t len)
devfs_inode_t * devfs_register (dentry_t *dir, const char *name, uint32_t len, mode_t mode, const struct file_ops *handlers)
Macro Definition Documentation
DEVFS_INODE_LEN
#define DEVFS_INODE_LEN (sizeof(struct devfs_inode))
Definition at line 8 of file devfs.h.
Typedef Documentation
devfs_inode_t
typedef struct devfs_inode devfs_inode_t
Definition at line 1 of file devfs.h.
Function Documentation
devfs_install()
void devfs_install ()
Definition at line 490 of file devfs.c.
 {
     driver_install(_devfs_driver_info());
 }
References _devfs_driver_info(), and driver_install().
Referenced by stage3().
devfs_mkdir()
devfs_inode_t* devfs_mkdir (dentry_t * dir, const char * name, uint32_t len)
Register a device.
Definition at line 499 of file devfs.c.
 {
     devfs_inode_t* devfs_inode = (devfs_inode_t*)dir->inode;
     devfs_inode_t* new_entry = _devfs_alloc_entry(devfs_inode);
     if (!new_entry) {
         return 0;
     }
     dentry_set_flag(dir, DENTRY_DIRTY);
     new_entry->mode = S_IFDIR;
     _devfs_set_name(new_entry, name, len);
     return new_entry;
 }
References _devfs_alloc_entry(), _devfs_set_name(), DENTRY_DIRTY, dentry_set_flag(), dentry::inode, copy_bin::name, and S_IFDIR.
devfs_mount()
int devfs_mount ()
Definition at line 531 of file devfs.c.
 {
     dentry_t* mp;
     if (vfs_resolve_path("/dev", &mp) < 0) {
         return -ENOENT;
     }
     int err = vfs_mount(mp, new_virtual_device(DEVICE_STORAGE), 2);
     dentry_put(mp);
     if (!err) {
         dm_send_notification(DM_NOTIFICATION_DEVFS_READY, 0);
     }
     return err;
 }
References dentry_put(), DEVICE_STORAGE, DM_NOTIFICATION_DEVFS_READY, dm_send_notification(), ENOENT, new_virtual_device(), vfs_mount(), and vfs_resolve_path().
Referenced by stage3().
devfs_register()
devfs_inode_t* devfs_register (dentry_t * dir, const char * name, uint32_t len, mode_t mode, const struct file_ops * handlers)
Referenced by _kbdriver_notification(), _mouse_recieve_notification(), bga_recieve_notification(), ptmx_install(), pty_slave_create(), and tty_new().