oneOS: include/drivers/driver_manager.h File Reference
driver_manager.h File Reference
#include <types.h>
Data Structures
struct driver_desc_t
struct driver_t
struct device_desc_t
struct device_t
Macros
#define MAX_DRIVERS_COUNT 256
#define MAX_DEVICES_COUNT 64
#define MAX_DRIVER_FUNCTION_COUNT 32
#define DRIVER_NAME_LENGTH 8
#define DM_FUNC_NOTIFY 0x0
#define DM_FUNC_DEVICE_START 0x1
#define DM_FUNC_DRIVER_START 0x1
#define DM_FUNC_DRIVER_EMIT_DRIVER 0x1
#define DM_FUNC_DRIVER_EMIT_DEVICE 0x2
Enumerations
enum DRIVER_MAN_NOTIFICATIONS { DM_NOTIFICATION_DEVFS_READY = 0 , DM_NOTIFICATION_STOP }
enum DRIVERS_TYPE {
DRIVER_STORAGE_DEVICE , DRIVER_VIDEO_DEVICE , DRIVER_SOUND_DEVICE , DRIVER_INPUT_SYSTEMS_DEVICE ,
DRIVER_NETWORK_DEVICE , DRIVER_BUS_CONTROLLER , DRIVER_VIRTUAL_FILE_SYSTEM , DRIVER_FILE_SYSTEM ,
DRIVER_OTHER , DRIVER_BAD_SIGN = 0xff
}
enum DEVICES_TYPE {
DEVICE_STORAGE , DEVICE_VIDEO , DEVICE_SOUND , DEVICE_INPUT_SYSTEMS ,
DEVICE_NETWORK , DEVICE_BAD_SIGN = 0xff
}
enum DRIVER_COMMON { DRIVER_NOTIFICATION = 0x0 }
enum DRIVER_VIDEO_OPERTAION { DRIVER_VIDEO_INIT = 0x1 , DRIVER_VIDEO_SET_RESOLUTION }
enum DRIVER_STORAGE_OPERTAION {
DRIVER_STORAGE_ADD_DEVICE = 0x1 , DRIVER_STORAGE_READ , DRIVER_STORAGE_WRITE , DRIVER_STORAGE_FLUSH ,
DRIVER_STORAGE_CAPACITY
}
enum DRIVER_INPUT_SYSTEMS_OPERTAION { DRIVER_INPUT_SYSTEMS_ADD_DEVICE = 0x1 , DRIVER_INPUT_SYSTEMS_GET_LAST_KEY , DRIVER_INPUT_SYSTEMS_DISCARD_LAST_KEY }
enum DRIVER_BUS_CONTROLLER_OPERTAION { DRIVER_BUS_CONTROLLER_FIND_DEVICE = 0x1 }
enum DRIVER_VIRTUAL_FILE_SYSTEM_OPERTAION { DRIVER_VIRTUAL_FILE_SYSTEM_ADD_DRIVER = 0x1 , DRIVER_VIRTUAL_FILE_SYSTEM_ADD_DEVICE , DRIVER_VIRTUAL_FILE_SYSTEM_EJECT_DEVICE }
enum DRIVER_FILE_SYSTEM_OPERTAION {
DRIVER_FILE_SYSTEM_RECOGNIZE = 0x1 , DRIVER_FILE_SYSTEM_PREPARE_FS , DRIVER_FILE_SYSTEM_EJECT_DEVICE , DRIVER_FILE_SYSTEM_OPEN ,
DRIVER_FILE_SYSTEM_CAN_READ , DRIVER_FILE_SYSTEM_CAN_WRITE , DRIVER_FILE_SYSTEM_READ , DRIVER_FILE_SYSTEM_WRITE ,
DRIVER_FILE_SYSTEM_TRUNCATE , DRIVER_FILE_SYSTEM_MKDIR , DRIVER_FILE_SYSTEM_RMDIR , DRIVER_FILE_SYSTEM_READ_INODE ,
DRIVER_FILE_SYSTEM_WRITE_INODE , DRIVER_FILE_SYSTEM_FREE_INODE , DRIVER_FILE_SYSTEM_GET_FSDATA , DRIVER_FILE_SYSTEM_LOOKUP ,
DRIVER_FILE_SYSTEM_GETDENTS , DRIVER_FILE_SYSTEM_CREATE , DRIVER_FILE_SYSTEM_UNLINK , DRIVER_FILE_SYSTEM_IOCTL ,
DRIVER_FILE_SYSTEM_MMAP
}
Functions
bool driver_manager_init ()
void register_drivers ()
void driver_install (driver_desc_t t_driver_info)
void device_install (device_desc_t t_device_info)
void eject_device (uint8_t dev_id)
void eject_all_devices ()
void drivers_run ()
device_t get_device (uint8_t t_dev_type, uint8_t t_start)
void pass_drivers_to_master_drivers ()
void pass_devices_to_master_drivers ()
device_t * new_virtual_device (uint8_t type)
void dm_send_notification (uint32_t msg, uint32_t param)
Variables
driver_t drivers [256]
device_t devices [64]
Macro Definition Documentation
DM_FUNC_DEVICE_START
#define DM_FUNC_DEVICE_START 0x1
Definition at line 12 of file driver_manager.h.
DM_FUNC_DRIVER_EMIT_DEVICE
#define DM_FUNC_DRIVER_EMIT_DEVICE 0x2
Definition at line 15 of file driver_manager.h.
DM_FUNC_DRIVER_EMIT_DRIVER
#define DM_FUNC_DRIVER_EMIT_DRIVER 0x1
Definition at line 14 of file driver_manager.h.
DM_FUNC_DRIVER_START
#define DM_FUNC_DRIVER_START 0x1
Definition at line 13 of file driver_manager.h.
DM_FUNC_NOTIFY
#define DM_FUNC_NOTIFY 0x0
Definition at line 11 of file driver_manager.h.
DRIVER_NAME_LENGTH
#define DRIVER_NAME_LENGTH 8
Definition at line 9 of file driver_manager.h.
MAX_DEVICES_COUNT
#define MAX_DEVICES_COUNT 64
Definition at line 7 of file driver_manager.h.
MAX_DRIVER_FUNCTION_COUNT
#define MAX_DRIVER_FUNCTION_COUNT 32
Definition at line 8 of file driver_manager.h.
MAX_DRIVERS_COUNT
#define MAX_DRIVERS_COUNT 256
Definition at line 6 of file driver_manager.h.
Enumeration Type Documentation
DEVICES_TYPE
enum DEVICES_TYPE
Enumerator
DEVICE_STORAGE
DEVICE_VIDEO
DEVICE_SOUND
DEVICE_INPUT_SYSTEMS
DEVICE_NETWORK
DEVICE_BAD_SIGN
Definition at line 38 of file driver_manager.h.
                   {
     DEVICE_STORAGE,
     DEVICE_VIDEO,
     DEVICE_SOUND,
     DEVICE_INPUT_SYSTEMS,
     DEVICE_NETWORK,
     DEVICE_BAD_SIGN = 0xff
 };
DRIVER_BUS_CONTROLLER_OPERTAION
enum DRIVER_BUS_CONTROLLER_OPERTAION
Enumerator
DRIVER_BUS_CONTROLLER_FIND_DEVICE
Definition at line 75 of file driver_manager.h.
{
     DRIVER_BUS_CONTROLLER_FIND_DEVICE = 0x1, // function called when a device is found
 };
DRIVER_COMMON
enum DRIVER_COMMON
Enumerator
DRIVER_NOTIFICATION
Definition at line 48 of file driver_manager.h.
                    {
     DRIVER_NOTIFICATION = 0x0,
 };
DRIVER_FILE_SYSTEM_OPERTAION
enum DRIVER_FILE_SYSTEM_OPERTAION
Enumerator
DRIVER_FILE_SYSTEM_RECOGNIZE
DRIVER_FILE_SYSTEM_PREPARE_FS
DRIVER_FILE_SYSTEM_EJECT_DEVICE
DRIVER_FILE_SYSTEM_OPEN
DRIVER_FILE_SYSTEM_CAN_READ
DRIVER_FILE_SYSTEM_CAN_WRITE
DRIVER_FILE_SYSTEM_READ
DRIVER_FILE_SYSTEM_WRITE
DRIVER_FILE_SYSTEM_TRUNCATE
DRIVER_FILE_SYSTEM_MKDIR
DRIVER_FILE_SYSTEM_RMDIR
DRIVER_FILE_SYSTEM_READ_INODE
DRIVER_FILE_SYSTEM_WRITE_INODE
DRIVER_FILE_SYSTEM_FREE_INODE
DRIVER_FILE_SYSTEM_GET_FSDATA
DRIVER_FILE_SYSTEM_LOOKUP
DRIVER_FILE_SYSTEM_GETDENTS
DRIVER_FILE_SYSTEM_CREATE
DRIVER_FILE_SYSTEM_UNLINK
DRIVER_FILE_SYSTEM_IOCTL
DRIVER_FILE_SYSTEM_MMAP
Definition at line 87 of file driver_manager.h.
{
     DRIVER_FILE_SYSTEM_RECOGNIZE = 0x1,
     DRIVER_FILE_SYSTEM_PREPARE_FS,
     DRIVER_FILE_SYSTEM_EJECT_DEVICE,
     DRIVER_FILE_SYSTEM_OPEN,
     DRIVER_FILE_SYSTEM_CAN_READ,
     DRIVER_FILE_SYSTEM_CAN_WRITE,
     DRIVER_FILE_SYSTEM_READ,
     DRIVER_FILE_SYSTEM_WRITE,
     DRIVER_FILE_SYSTEM_TRUNCATE,
     DRIVER_FILE_SYSTEM_MKDIR,
     DRIVER_FILE_SYSTEM_RMDIR,
     DRIVER_FILE_SYSTEM_READ_INODE,
     DRIVER_FILE_SYSTEM_WRITE_INODE,
     DRIVER_FILE_SYSTEM_FREE_INODE,
     DRIVER_FILE_SYSTEM_GET_FSDATA,
     DRIVER_FILE_SYSTEM_LOOKUP,
     DRIVER_FILE_SYSTEM_GETDENTS,
     DRIVER_FILE_SYSTEM_CREATE,
     DRIVER_FILE_SYSTEM_UNLINK,
     DRIVER_FILE_SYSTEM_IOCTL,
     DRIVER_FILE_SYSTEM_MMAP,
 };
DRIVER_INPUT_SYSTEMS_OPERTAION
enum DRIVER_INPUT_SYSTEMS_OPERTAION
Enumerator
DRIVER_INPUT_SYSTEMS_ADD_DEVICE
DRIVER_INPUT_SYSTEMS_GET_LAST_KEY
DRIVER_INPUT_SYSTEMS_DISCARD_LAST_KEY
Definition at line 68 of file driver_manager.h.
{
     DRIVER_INPUT_SYSTEMS_ADD_DEVICE = 0x1, // function called when a device is found
     DRIVER_INPUT_SYSTEMS_GET_LAST_KEY,
     DRIVER_INPUT_SYSTEMS_DISCARD_LAST_KEY
 };
DRIVER_MAN_NOTIFICATIONS
enum DRIVER_MAN_NOTIFICATIONS
Enumerator
DM_NOTIFICATION_DEVFS_READY
DM_NOTIFICATION_STOP
Definition at line 17 of file driver_manager.h.
{
     DM_NOTIFICATION_DEVFS_READY = 0,
     DM_NOTIFICATION_STOP,
 };
DRIVER_STORAGE_OPERTAION
enum DRIVER_STORAGE_OPERTAION
Enumerator
DRIVER_STORAGE_ADD_DEVICE
DRIVER_STORAGE_READ
DRIVER_STORAGE_WRITE
DRIVER_STORAGE_FLUSH
DRIVER_STORAGE_CAPACITY
Definition at line 59 of file driver_manager.h.
{
     DRIVER_STORAGE_ADD_DEVICE = 0x1, // function called when a device is found
     DRIVER_STORAGE_READ,
     DRIVER_STORAGE_WRITE,
     DRIVER_STORAGE_FLUSH,
     DRIVER_STORAGE_CAPACITY,
 };
DRIVER_VIDEO_OPERTAION
enum DRIVER_VIDEO_OPERTAION
Enumerator
DRIVER_VIDEO_INIT
DRIVER_VIDEO_SET_RESOLUTION
Definition at line 53 of file driver_manager.h.
{
     DRIVER_VIDEO_INIT = 0x1, // function called when a device is found
     DRIVER_VIDEO_SET_RESOLUTION,
 };
DRIVER_VIRTUAL_FILE_SYSTEM_OPERTAION
enum DRIVER_VIRTUAL_FILE_SYSTEM_OPERTAION
Enumerator
DRIVER_VIRTUAL_FILE_SYSTEM_ADD_DRIVER
DRIVER_VIRTUAL_FILE_SYSTEM_ADD_DEVICE
DRIVER_VIRTUAL_FILE_SYSTEM_EJECT_DEVICE
Definition at line 80 of file driver_manager.h.
{
     DRIVER_VIRTUAL_FILE_SYSTEM_ADD_DRIVER = 0x1,
     DRIVER_VIRTUAL_FILE_SYSTEM_ADD_DEVICE,
     DRIVER_VIRTUAL_FILE_SYSTEM_EJECT_DEVICE,
 };
DRIVERS_TYPE
enum DRIVERS_TYPE
Enumerator
DRIVER_STORAGE_DEVICE
DRIVER_VIDEO_DEVICE
DRIVER_SOUND_DEVICE
DRIVER_INPUT_SYSTEMS_DEVICE
DRIVER_NETWORK_DEVICE
DRIVER_BUS_CONTROLLER
DRIVER_VIRTUAL_FILE_SYSTEM
DRIVER_FILE_SYSTEM
DRIVER_OTHER
DRIVER_BAD_SIGN
Definition at line 23 of file driver_manager.h.
                   {
     DRIVER_STORAGE_DEVICE,
     DRIVER_VIDEO_DEVICE,
     DRIVER_SOUND_DEVICE,
     DRIVER_INPUT_SYSTEMS_DEVICE,
     DRIVER_NETWORK_DEVICE,
     DRIVER_BUS_CONTROLLER,
     DRIVER_VIRTUAL_FILE_SYSTEM,
     DRIVER_FILE_SYSTEM,
     DRIVER_OTHER,
     DRIVER_BAD_SIGN = 0xff
 };
Function Documentation
device_install()
void device_install (device_desc_t t_device_info)
Definition at line 120 of file driver_manager.c.
 {
     int dev_id = _devices_count++;
     devices[dev_id].id = dev_id;
     devices[dev_id].driver_id = _dm_find_driver_for_device(device_info);
     devices[dev_id].device_desc = device_info;
     devices[dev_id].is_virtual = false;
     if (devices[dev_id].driver_id == -1) {
         devices[dev_id].type = DEVICE_BAD_SIGN;
         _dm_no_driver_for_device(device_info);
     } else {
         devices[dev_id].type = drivers[devices[dev_id].driver_id].desc.type;
         void (*rd)(device_t * nd) = (void*)drivers[devices[dev_id].driver_id].desc.functions[DM_FUNC_DEVICE_START];
         rd(&devices[dev_id]);
     }
 }
References _devices_count, _dm_find_driver_for_device(), _dm_no_driver_for_device(), driver_t::desc, DEVICE_BAD_SIGN, device_t::device_desc, devices, DM_FUNC_DEVICE_START, device_t::driver_id, drivers, driver_desc_t::functions, device_t::id, device_t::is_virtual, driver_desc_t::type, and device_t::type.
Referenced by ide_find_devices(), and pci_find_devices().
dm_send_notification()
void dm_send_notification (uint32_t msg, uint32_t param)
Definition at line 191 of file driver_manager.c.
 {
     for (int i = 0; i < _drivers_count; i++) {
         if (drivers[i].desc.functions[DM_FUNC_NOTIFY]) {
             void (*notify)(uint32_t, uint32_t) = (void*)drivers[i].desc.functions[DM_FUNC_NOTIFY];
             notify(msg, param);
         }
     }
 }
References _drivers_count, driver_t::desc, DM_FUNC_NOTIFY, drivers, and driver_desc_t::functions.
Referenced by devfs_mount().
driver_install()
void driver_install (driver_desc_t t_driver_info)
Definition at line 62 of file driver_manager.c.
 {
     driver_t new_driver;
     new_driver.id = _drivers_count;
     new_driver.desc = driver_info;
     drivers[_drivers_count++] = new_driver;
 }
References _drivers_count, driver_t::desc, drivers, and driver_t::id.
Referenced by ata_install(), bga_install(), devfs_install(), ext2_install(), ide_install(), kbdriver_install(), mouse_install(), pci_install(), procfs_install(), and vfs_install().
driver_manager_init()
bool driver_manager_init ()
Definition at line 56 of file driver_manager.c.
 {
     return true;
 }
Referenced by stage3().
drivers_run()
void drivers_run ()
Definition at line 71 of file driver_manager.c.
 {
     for (int i = 0; i < _drivers_count; i++) {
         drivers[i].is_active = false;
     }
     for (int i = 0; i < _drivers_count; i++) {
         if (drivers[i].desc.auto_start) {
             drivers[i].is_active = true;
             void (*rd)() = (void*)drivers[i].desc.functions[DM_FUNC_DRIVER_START];
             rd();
         }
     }
     pass_drivers_to_master_drivers();
     pass_devices_to_master_drivers();
 }
References _drivers_count, driver_t::desc, DM_FUNC_DRIVER_START, drivers, driver_desc_t::functions, driver_t::is_active, pass_devices_to_master_drivers(), and pass_drivers_to_master_drivers().
Referenced by stage3().
eject_all_devices()
void eject_all_devices ()
Definition at line 162 of file driver_manager.c.
 {
     for (int dev_id = 0; dev_id < _devices_count; dev_id++) {
         eject_device(dev_id);
     }
 }
References _devices_count, and eject_device().
Referenced by _syscmd_shutdown().
eject_device()
void eject_device (uint8_t dev_id)
Definition at line 148 of file driver_manager.c.
 {
     uint8_t used_driver_id = devices[dev_id].driver_id;
     _ask_driver_to_eject_device(used_driver_id, dev_id);
     for (int i = 0; i < _drivers_count; i++) {
         if (drivers[i].desc.is_device_needed) {
             if (drivers[i].desc.type_of_needed_device == devices[dev_id].type) {
                 _ask_driver_to_eject_device(i, dev_id);
             }
         }
     }
 }
References _ask_driver_to_eject_device(), _drivers_count, devices, device_t::driver_id, drivers, and device_t::type.
Referenced by eject_all_devices().
get_device()
device_t get_device (uint8_t t_dev_type, uint8_t t_start)
Definition at line 170 of file driver_manager.c.
 {
     for (int i = start; i < _devices_count; i++) {
         if (devices[i].type == dev_type) {
             return devices[i];
         }
     }
     device_t bad_device;
     bad_device.type = DEVICE_BAD_SIGN;
     return bad_device;
 }
References _devices_count, DEVICE_BAD_SIGN, devices, device_t::type, and type.
new_virtual_device()
device_t* new_virtual_device (uint8_t type)
Definition at line 182 of file driver_manager.c.
 {
     int dev_id = _devices_count++;
     devices[dev_id].id = dev_id;
     devices[dev_id].type = type;
     devices[dev_id].is_virtual = true;
     return &devices[dev_id];
 }
References _devices_count, devices, device_t::id, device_t::is_virtual, device_t::type, and type.
Referenced by devfs_mount(), and procfs().
pass_devices_to_master_drivers()
void pass_devices_to_master_drivers ()
Definition at line 104 of file driver_manager.c.
 {
     for (int i = 0; i < _drivers_count; i++) {
         if (drivers[i].desc.is_device_needed) {
             for (int j = 0; j < _devices_count; j++) {
                 if (drivers[i].desc.type_of_needed_device == devices[j].type) {
                     drivers[i].is_active = true;
                     void (*rd)(device_t * nd) = (void*)drivers[i].desc.functions[DM_FUNC_DRIVER_EMIT_DEVICE];
                     rd(&devices[j]);
                 }
             }
         }
     }
 }
References _devices_count, _drivers_count, driver_t::desc, devices, DM_FUNC_DRIVER_EMIT_DEVICE, drivers, driver_desc_t::functions, driver_t::is_active, and device_t::type.
Referenced by drivers_run().
pass_drivers_to_master_drivers()
void pass_drivers_to_master_drivers ()
Definition at line 88 of file driver_manager.c.
 {
     for (int i = 0; i < _drivers_count; i++) {
         if (drivers[i].desc.is_driver_needed) {
             for (int j = 0; j < _drivers_count; j++) {
                 if (drivers[i].desc.type_of_needed_driver == drivers[j].desc.type) {
                     drivers[i].is_active = true;
                     drivers[j].is_active = true;
                     void (*rd)(driver_t* nd) = (void*)drivers[i].desc.functions[DM_FUNC_DRIVER_EMIT_DRIVER];
                     rd(&drivers[j]);
                 }
             }
         }
     }
 }
References _drivers_count, driver_t::desc, DM_FUNC_DRIVER_EMIT_DRIVER, drivers, driver_desc_t::functions, driver_t::is_active, and driver_desc_t::type.
Referenced by drivers_run().
register_drivers()
void register_drivers ()
Variable Documentation
devices
device_t devices[64] extern
Definition at line 12 of file driver_manager.c.
Referenced by _ask_driver_to_eject_device(), device_install(), eject_device(), get_device(), new_virtual_device(), and pass_devices_to_master_drivers().
drivers
driver_t drivers[256] extern
Definition at line 11 of file driver_manager.c.
Referenced by _ask_driver_to_eject_device(), _dm_find_driver_for_device(), _ext2_get_disk_size(), _ext2_read_from_dev(), _ext2_write_to_dev(), device_install(), dm_send_notification(), driver_install(), drivers_run(), eject_device(), pass_devices_to_master_drivers(), and pass_drivers_to_master_drivers().