oneOS: src/kernel/drivers/driver_manager.c File Reference
driver_manager.c File Reference
#include <drivers/driver_manager.h>
#include <log.h>
Functions
int16_t _driver_for_device (device_desc_t device_info)
void _no_driver_for_device (device_desc_t device_info)
static void _dm_no_driver_for_device (device_desc_t device_info)
static int _dm_find_driver_for_device (device_desc_t device_info)
bool driver_manager_init ()
void driver_install (driver_desc_t driver_info)
void drivers_run ()
void pass_drivers_to_master_drivers ()
void pass_devices_to_master_drivers ()
void device_install (device_desc_t device_info)
void _ask_driver_to_eject_device (uint8_t driver_id, uint8_t dev_id)
void eject_device (uint8_t dev_id)
void eject_all_devices ()
device_t get_device (uint8_t dev_type, uint8_t start)
device_t * new_virtual_device (uint8_t type)
void dm_send_notification (uint32_t msg, uint32_t param)
Variables
static int _drivers_count = 0
static int _devices_count = 0
driver_t drivers [MAX_DRIVERS_COUNT]
device_t devices [MAX_DEVICES_COUNT]
Function Documentation
_ask_driver_to_eject_device()
void _ask_driver_to_eject_device (uint8_t driver_id, uint8_t dev_id)
Definition at line 140 of file driver_manager.c.
 {
     if (drivers[driver_id].desc.type == DRIVER_VIRTUAL_FILE_SYSTEM) {
         void (*ej)(device_t * nd) = (void*)drivers[driver_id].desc.functions[DRIVER_VIRTUAL_FILE_SYSTEM_EJECT_DEVICE];
         ej(&devices[dev_id]);
     }
 }
References driver_t::desc, devices, DRIVER_VIRTUAL_FILE_SYSTEM, DRIVER_VIRTUAL_FILE_SYSTEM_EJECT_DEVICE, drivers, and driver_desc_t::functions.
Referenced by eject_device().
_dm_find_driver_for_device()
static int _dm_find_driver_for_device (device_desc_t device_info) static
Definition at line 22 of file driver_manager.c.
 {
     uint8_t cur_capablity = 0;
     uint8_t best_capablity = 0;
     uint8_t best_capable_driver_id = 0;
     for (int i = 0; i < _drivers_count; i++) {
         if (!drivers[i].desc.is_device_driver) {
             continue;
         }
         cur_capablity = 0;
         if (drivers[i].desc.pci_serve_class == device_info.class_id) {
             cur_capablity |= 0b1000;
         }
         if (drivers[i].desc.pci_serve_subclass == device_info.subclass_id) {
             cur_capablity |= 0b0100;
         }
         if (drivers[i].desc.pci_serve_vendor_id == device_info.vendor_id) {
             cur_capablity |= 0b0010;
         }
         if (drivers[i].desc.pci_serve_device_id == device_info.device_id) {
             cur_capablity |= 0b0001;
         }
         if (cur_capablity > best_capablity) {
             best_capablity = cur_capablity;
             best_capable_driver_id = i;
         }
     }
     if (best_capablity >= 0b1100) {
         return best_capable_driver_id;
     }
     return -1;
 }
References _drivers_count, device_desc_t::class_id, device_desc_t::device_id, drivers, device_desc_t::subclass_id, and device_desc_t::vendor_id.
Referenced by device_install().
_dm_no_driver_for_device()
static void _dm_no_driver_for_device (device_desc_t device_info) static
Definition at line 17 of file driver_manager.c.
 {
     log_warn("No driver for the device: cl/subcl %x %x : ven/dev %x %x", device_info.class_id, device_info.subclass_id, device_info.vendor_id, device_info.device_id);
 }
References device_desc_t::class_id, device_desc_t::device_id, log_warn(), device_desc_t::subclass_id, and device_desc_t::vendor_id.
Referenced by device_install().
_driver_for_device()
int16_t _driver_for_device (device_desc_t device_info)
_no_driver_for_device()
void _no_driver_for_device (device_desc_t device_info)
device_install()
void device_install (device_desc_t device_info)
Definition at line 120 of file driver_manager.c.
 {
     int dev_id = _devices_count++;
     devices[dev_id].id = dev_id;
     devices[dev_id].driver_id = _dm_find_driver_for_device(device_info);
     devices[dev_id].device_desc = device_info;
     devices[dev_id].is_virtual = false;
     if (devices[dev_id].driver_id == -1) {
         devices[dev_id].type = DEVICE_BAD_SIGN;
         _dm_no_driver_for_device(device_info);
     } else {
         devices[dev_id].type = drivers[devices[dev_id].driver_id].desc.type;
         void (*rd)(device_t * nd) = (void*)drivers[devices[dev_id].driver_id].desc.functions[DM_FUNC_DEVICE_START];
         rd(&devices[dev_id]);
     }
 }
References _devices_count, _dm_find_driver_for_device(), _dm_no_driver_for_device(), driver_t::desc, DEVICE_BAD_SIGN, device_t::device_desc, devices, DM_FUNC_DEVICE_START, device_t::driver_id, drivers, driver_desc_t::functions, device_t::id, device_t::is_virtual, driver_desc_t::type, and device_t::type.
Referenced by ide_find_devices(), and pci_find_devices().
dm_send_notification()
void dm_send_notification (uint32_t msg, uint32_t param)
Definition at line 191 of file driver_manager.c.
 {
     for (int i = 0; i < _drivers_count; i++) {
         if (drivers[i].desc.functions[DM_FUNC_NOTIFY]) {
             void (*notify)(uint32_t, uint32_t) = (void*)drivers[i].desc.functions[DM_FUNC_NOTIFY];
             notify(msg, param);
         }
     }
 }
References _drivers_count, driver_t::desc, DM_FUNC_NOTIFY, drivers, and driver_desc_t::functions.
Referenced by devfs_mount().
driver_install()
void driver_install (driver_desc_t driver_info)
Definition at line 62 of file driver_manager.c.
 {
     driver_t new_driver;
     new_driver.id = _drivers_count;
     new_driver.desc = driver_info;
     drivers[_drivers_count++] = new_driver;
 }
References _drivers_count, driver_t::desc, drivers, and driver_t::id.
Referenced by ata_install(), bga_install(), devfs_install(), ext2_install(), ide_install(), kbdriver_install(), mouse_install(), pci_install(), procfs_install(), and vfs_install().
driver_manager_init()
bool driver_manager_init ()
Definition at line 56 of file driver_manager.c.
 {
     return true;
 }
Referenced by stage3().
drivers_run()
void drivers_run ()
Definition at line 71 of file driver_manager.c.
 {
     for (int i = 0; i < _drivers_count; i++) {
         drivers[i].is_active = false;
     }
     for (int i = 0; i < _drivers_count; i++) {
         if (drivers[i].desc.auto_start) {
             drivers[i].is_active = true;
             void (*rd)() = (void*)drivers[i].desc.functions[DM_FUNC_DRIVER_START];
             rd();
         }
     }
     pass_drivers_to_master_drivers();
     pass_devices_to_master_drivers();
 }
References _drivers_count, driver_t::desc, DM_FUNC_DRIVER_START, drivers, driver_desc_t::functions, driver_t::is_active, pass_devices_to_master_drivers(), and pass_drivers_to_master_drivers().
Referenced by stage3().
eject_all_devices()
void eject_all_devices ()
Definition at line 162 of file driver_manager.c.
 {
     for (int dev_id = 0; dev_id < _devices_count; dev_id++) {
         eject_device(dev_id);
     }
 }
References _devices_count, and eject_device().
Referenced by _syscmd_shutdown().
eject_device()
void eject_device (uint8_t dev_id)
Definition at line 148 of file driver_manager.c.
 {
     uint8_t used_driver_id = devices[dev_id].driver_id;
     _ask_driver_to_eject_device(used_driver_id, dev_id);
     for (int i = 0; i < _drivers_count; i++) {
         if (drivers[i].desc.is_device_needed) {
             if (drivers[i].desc.type_of_needed_device == devices[dev_id].type) {
                 _ask_driver_to_eject_device(i, dev_id);
             }
         }
     }
 }
References _ask_driver_to_eject_device(), _drivers_count, devices, device_t::driver_id, drivers, and device_t::type.
Referenced by eject_all_devices().
get_device()
device_t get_device (uint8_t dev_type, uint8_t start)
Definition at line 170 of file driver_manager.c.
 {
     for (int i = start; i < _devices_count; i++) {
         if (devices[i].type == dev_type) {
             return devices[i];
         }
     }
     device_t bad_device;
     bad_device.type = DEVICE_BAD_SIGN;
     return bad_device;
 }
References _devices_count, DEVICE_BAD_SIGN, devices, device_t::type, and type.
new_virtual_device()
device_t* new_virtual_device (uint8_t type)
Definition at line 182 of file driver_manager.c.
 {
     int dev_id = _devices_count++;
     devices[dev_id].id = dev_id;
     devices[dev_id].type = type;
     devices[dev_id].is_virtual = true;
     return &devices[dev_id];
 }
References _devices_count, devices, device_t::id, device_t::is_virtual, device_t::type, and type.
Referenced by devfs_mount(), and procfs().
pass_devices_to_master_drivers()
void pass_devices_to_master_drivers ()
Definition at line 104 of file driver_manager.c.
 {
     for (int i = 0; i < _drivers_count; i++) {
         if (drivers[i].desc.is_device_needed) {
             for (int j = 0; j < _devices_count; j++) {
                 if (drivers[i].desc.type_of_needed_device == devices[j].type) {
                     drivers[i].is_active = true;
                     void (*rd)(device_t * nd) = (void*)drivers[i].desc.functions[DM_FUNC_DRIVER_EMIT_DEVICE];
                     rd(&devices[j]);
                 }
             }
         }
     }
 }
References _devices_count, _drivers_count, driver_t::desc, devices, DM_FUNC_DRIVER_EMIT_DEVICE, drivers, driver_desc_t::functions, driver_t::is_active, and device_t::type.
Referenced by drivers_run().
pass_drivers_to_master_drivers()
void pass_drivers_to_master_drivers ()
Definition at line 88 of file driver_manager.c.
 {
     for (int i = 0; i < _drivers_count; i++) {
         if (drivers[i].desc.is_driver_needed) {
             for (int j = 0; j < _drivers_count; j++) {
                 if (drivers[i].desc.type_of_needed_driver == drivers[j].desc.type) {
                     drivers[i].is_active = true;
                     drivers[j].is_active = true;
                     void (*rd)(driver_t* nd) = (void*)drivers[i].desc.functions[DM_FUNC_DRIVER_EMIT_DRIVER];
                     rd(&drivers[j]);
                 }
             }
         }
     }
 }
References _drivers_count, driver_t::desc, DM_FUNC_DRIVER_EMIT_DRIVER, drivers, driver_desc_t::functions, driver_t::is_active, and driver_desc_t::type.
Referenced by drivers_run().
Variable Documentation
_devices_count
int _devices_count = 0 static
Definition at line 9 of file driver_manager.c.
Referenced by device_install(), eject_all_devices(), get_device(), new_virtual_device(), and pass_devices_to_master_drivers().
_drivers_count
int _drivers_count = 0 static
Definition at line 8 of file driver_manager.c.
Referenced by _dm_find_driver_for_device(), dm_send_notification(), driver_install(), drivers_run(), eject_device(), pass_devices_to_master_drivers(), and pass_drivers_to_master_drivers().
devices
device_t devices[MAX_DEVICES_COUNT]
Definition at line 12 of file driver_manager.c.
Referenced by _ask_driver_to_eject_device(), device_install(), eject_device(), get_device(), new_virtual_device(), and pass_devices_to_master_drivers().
drivers
driver_t drivers[MAX_DRIVERS_COUNT]
Definition at line 11 of file driver_manager.c.
Referenced by _ask_driver_to_eject_device(), _dm_find_driver_for_device(), _ext2_get_disk_size(), _ext2_read_from_dev(), _ext2_write_to_dev(), device_install(), dm_send_notification(), driver_install(), drivers_run(), eject_device(), pass_devices_to_master_drivers(), and pass_drivers_to_master_drivers().