oneOS: src/kernel/algo/dynamic_array.c File Reference
dynamic_array.c File Reference
#include <algo/dynamic_array.h>
#include <log.h>
#include <mem/kmalloc.h>
#include <utils/mem.h>
Functions
static int _dynamic_array_resize (dynamic_array_t *v, uint32_t new_capacity, uint32_t element_size)
static int _dynamic_array_grow (dynamic_array_t *v)
int dynamic_array_init (dynamic_array_t *v, uint32_t element_size)
int dynamic_array_init_of_size (dynamic_array_t *v, uint32_t element_size, uint32_t capacity)
int dynamic_array_free (dynamic_array_t *v)
void * dynamic_array_get (dynamic_array_t *v, int index)
int dynamic_array_push (dynamic_array_t *v, void *element)
int dynamic_array_pop (dynamic_array_t *v)
int dynamic_array_clear (dynamic_array_t *v)
uint32_t dynamic_array_size (dynamic_array_t *v)
Function Documentation
_dynamic_array_grow()
static int _dynamic_array_grow (dynamic_array_t * v) inline static
Definition at line 25 of file dynamic_array.c.
 {
     if (v->capacity) {
         if (_dynamic_array_resize(v, 2 * v->capacity, v->element_size) != 0) {
             return -1;
         }
     } else {
         v->data = kmalloc(v->element_size); /* allocating one entry */
         if (!v->data) {
             return -1;
         }
         v->capacity = 1;
     }
     return 0;
 }
References _dynamic_array_resize(), dynamic_array::capacity, dynamic_array::data, dynamic_array::element_size, and kmalloc().
Referenced by dynamic_array_push().
_dynamic_array_resize()
static int _dynamic_array_resize (dynamic_array_t * v, uint32_t new_capacity, uint32_t element_size) inline static
Definition at line 14 of file dynamic_array.c.
 {
     uint32_t* new_darray_area = krealloc(v->data, new_capacity * element_size);
     if (new_darray_area == 0) {
         return -1;
     }
     v->data = new_darray_area;
     v->capacity = new_capacity;
     return 0;
 }
References dynamic_array::capacity, dynamic_array::data, and krealloc().
Referenced by _dynamic_array_grow().
dynamic_array_clear()
int dynamic_array_clear (dynamic_array_t * v)
Definition at line 102 of file dynamic_array.c.
 {
     v->size = 0;
     return 0;
 }
References dynamic_array::size.
Referenced by tasking_exec().
dynamic_array_free()
int dynamic_array_free (dynamic_array_t * v)
Definition at line 63 of file dynamic_array.c.
 {
     kfree(v->data);
     v->size = 0;
     v->capacity = 0;
     return 0;
 }
References dynamic_array::capacity, dynamic_array::data, kfree(), and dynamic_array::size.
Referenced by proc_free().
dynamic_array_get()
void* dynamic_array_get (dynamic_array_t * v, int index)
Definition at line 71 of file dynamic_array.c.
 {
     if (index >= v->size) {
         log_warn("!!! dynamic array: index out of range");
         return 0;
     }
     return (void*)v->data + index * v->element_size;
 }
References dynamic_array::data, dynamic_array::element_size, log_warn(), and dynamic_array::size.
Referenced by _devfs_get_entry(), _proc_can_add_zone(), dentry_alloc_new(), dynamic_array_push(), proc_copy_of(), proc_find_zone(), proc_new_random_zone(), proc_new_random_zone_backward(), proc_new_zone(), vfs_add_dev_with_fs(), vfs_choose_fs_of_dev(), and vfs_eject_device().
dynamic_array_init()
int dynamic_array_init (dynamic_array_t * v, uint32_t element_size)
Definition at line 41 of file dynamic_array.c.
 {
     v->size = 0;
     v->capacity = 0;
     v->element_size = element_size;
     return 0;
 }
References dynamic_array::capacity, dynamic_array::element_size, and dynamic_array::size.
Referenced by devfs_prepare_fs().
dynamic_array_init_of_size()
int dynamic_array_init_of_size (dynamic_array_t * v, uint32_t element_size, uint32_t capacity)
Definition at line 49 of file dynamic_array.c.
 {
     v->data = kmalloc(capacity * element_size);
     if (!v->data) {
         return -1;
     }
     v->size = 0;
     v->capacity = capacity;
     v->element_size = element_size;
     return 0;
 }
References dynamic_array::capacity, dynamic_array::data, dynamic_array::element_size, kmalloc(), and dynamic_array::size.
Referenced by proc_setup(), and vfs_install().
dynamic_array_pop()
int dynamic_array_pop (dynamic_array_t * v)
Definition at line 93 of file dynamic_array.c.
 {
     if (v->size) {
         v->size--;
         return 0;
     }
     return -1;
 }
References dynamic_array::size.
dynamic_array_push()
int dynamic_array_push (dynamic_array_t * v, void * element)
Definition at line 80 of file dynamic_array.c.
 {
     if (v->size == v->capacity) {
         if (_dynamic_array_grow(v) != 0) {
             return -1;
         }
     }
     v->size++;
     void* place = dynamic_array_get(v, v->size - 1);
     memcpy(place, element, v->element_size);
     return 0;
 }
References _dynamic_array_grow(), dynamic_array::capacity, dynamic_array_get(), dynamic_array::element_size, memcpy(), and dynamic_array::size.
Referenced by _devfs_alloc_entry_zone(), _devfs_alloc_name_zone(), proc_copy_of(), proc_new_zone(), and vfs_add_fs().
dynamic_array_size()
uint32_t dynamic_array_size (dynamic_array_t * v)
Definition at line 108 of file dynamic_array.c.
 {
     return v->size;
 }
References dynamic_array::size.