oneOS: userland/edit/main.c File Reference
main.c File Reference
#include "file.h"
#include "lifetime.h"
#include "menu.h"
#include "mode.h"
#include "viewer.h"
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
Macros
#define STDIN 0
#define STDOUT 1
Functions
void viewing_accept_key (char key)
char get_key ()
void process_input ()
void display_file (char *path)
void init_mode ()
int main (int argc, char **argv)
Variables
uint32_t mode
mode_disc_t mode_disc
Macro Definition Documentation
STDIN
#define STDIN 0
Definition at line 15 of file main.c.
STDOUT
#define STDOUT 1
Definition at line 16 of file main.c.
Function Documentation
display_file()
void display_file (char * path)
Definition at line 65 of file main.c.
 {
     int fd = file_open(path);
 }
References file_open().
Referenced by main().
get_key()
char get_key ()
Definition at line 48 of file main.c.
 {
     char c;
     if (read(STDIN, &c, 1) != 1) {
         crash_app();
     }
     return c;
 }
References crash_app(), read(), and STDIN.
Referenced by process_input().
init_mode()
void init_mode ()
Definition at line 70 of file main.c.
 {
     mode = VIEWING;
     mode_disc.accept_key = viewing_accept_key;
 }
References mode_disc::accept_key, mode, VIEWING, and viewing_accept_key().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 76 of file main.c.
 {
     if (argc < 2) {
         return 0;
     }
     enable_raw_mode();
     init_mode();
     display_file(argv[1]);
     process_input();
     exit_app();
 }
References display_file(), enable_raw_mode(), exit_app(), init_mode(), and process_input().
process_input()
void process_input ()
Definition at line 57 of file main.c.
 {
     for (;;) {
         char key = get_key();
         mode_disc.accept_key(key);
     }
 }
References mode_disc::accept_key, and get_key().
Referenced by main().
viewing_accept_key()
void viewing_accept_key (char key)
Definition at line 21 of file main.c.
 {
     if (key == ':') {
         menu_enter_mode();
         return;
     }
     if (key == 'w') {
         viewer_cursor_up();
         return;
     }
     if (key == 's') {
         viewer_cursor_down();
         return;
     }
     if (key == 'a') {
         viewer_cursor_left();
         return;
     }
     if (key == 'd') {
         viewer_cursor_right();
         return;
     }
     file_paste_char(key, viewer_get_cursor_offset_in_file());
 }
References file_paste_char(), menu_enter_mode(), viewer_cursor_down(), viewer_cursor_left(), viewer_cursor_right(), viewer_cursor_up(), and viewer_get_cursor_offset_in_file().
Referenced by init_mode().
Variable Documentation
mode
uint32_t mode
Definition at line 18 of file main.c.
Referenced by _ext2_setup_dir(), _ext2_setup_file(), creat(), dentry_inode_rem_flag(), dentry_inode_set_flag(), dentry_inode_test_flag(), devfs_register(), ext2_create(), ext2_mkdir(), init_mode(), menu_enter_mode(), sys_creat(), sys_open(), touch(), vfs_create(), and vfs_mkdir().
mode_disc
mode_disc_t mode_disc
Definition at line 19 of file main.c.