oneOS: src/boot/x86/stage2/drivers/elf_lite.c File Reference
elf_lite.c File Reference
#include "elf_lite.h"
#include "display.h"
Functions
int elf_load_header (drive_desc_t *drive_desc, fs_desc_t *fs_desc, char *path)
void elf_read_program_header (drive_desc_t *drive_desc, fs_desc_t *fs_desc, char *path, uint32_t id, elf_program_header_32_t *program_header)
void elf_read_section_header (drive_desc_t *drive_desc, fs_desc_t *fs_desc, char *path, uint32_t id, elf_section_header_32_t *section_header)
int elf_load_kernel (drive_desc_t *drive_desc, fs_desc_t *fs_desc, char *path, uint32_t *kernel_size)
Variables
elf_header_32_t elf_header
Function Documentation
elf_load_header()
int elf_load_header (drive_desc_t * drive_desc, fs_desc_t * fs_desc, char * path)
Definition at line 10 of file elf_lite.c.
{
     int (*read_drive)(drive_desc_t *drive_desc, char *path, uint8_t *buf, uint32_t from, uint32_t len) = fs_desc->read;
     read_drive(drive_desc, path, (uint8_t*)&elf_header, 0, sizeof(elf_header_32_t));
     if (elf_header.e_ident[EI_MAG0] != 0x7F ||
         elf_header.e_ident[EI_MAG1] != 0x45 ||
         elf_header.e_ident[EI_MAG2] != 0x4c ||
         elf_header.e_ident[EI_MAG3] != 0x46) {
         return -1;
     }
     return 0;
 }
References buf, elf_header_32_t::e_ident, EI_MAG0, EI_MAG1, EI_MAG2, EI_MAG3, elf_header, and fs_desc_t::read.
Referenced by elf_load_kernel().
elf_load_kernel()
int elf_load_kernel (drive_desc_t * drive_desc, fs_desc_t * fs_desc, char * path, uint32_t * kernel_size)
Definition at line 34 of file elf_lite.c.
{
     int (*read_drive)(drive_desc_t *drive_desc, char *path, uint8_t *buf, uint32_t from, uint32_t len) = fs_desc->read;
     read_drive(drive_desc, path, (uint8_t*)&elf_header, 0, sizeof(elf_header_32_t));
     if (elf_load_header(drive_desc, fs_desc, path) != 0) {
         return -1;
     }
     // Reading Kernel
     for (uint32_t i = 0; i < elf_header.e_phnum; i++) {
         elf_program_header_32_t program_header;
         elf_read_program_header(drive_desc, fs_desc, path, i, &program_header);
         // Let's load it
         if (program_header.p_type == PT_LOAD) {
             read_drive(drive_desc, path, (uint8_t*)program_header.p_paddr, program_header.p_offset, program_header.p_filesz);
         }
     }
     // Calc Kernel Size
     *kernel_size = 0;
     for (uint32_t i = 0; i < elf_header.e_shnum; i++) {
         elf_section_header_32_t section_header;
         elf_read_section_header(drive_desc, fs_desc, path, i, &section_header);
         if (section_header.sh_type == SHT_NOBITS) {
             *kernel_size += section_header.sh_size;
         }
         if (section_header.sh_type == SHT_PROGBITS) {
             *kernel_size += section_header.sh_size;
         }
     }
     return 0;
 }
References buf, elf_header_32_t::e_phnum, elf_header_32_t::e_shnum, elf_header, elf_load_header(), elf_read_program_header(), elf_read_section_header(), elf_program_header_32_t::p_filesz, elf_program_header_32_t::p_offset, elf_program_header_32_t::p_paddr, elf_program_header_32_t::p_type, PT_LOAD, fs_desc_t::read, elf_section_header_32_t::sh_size, elf_section_header_32_t::sh_type, SHT_NOBITS, and SHT_PROGBITS.
Referenced by stage2().
elf_read_program_header()
void elf_read_program_header (drive_desc_t * drive_desc, fs_desc_t * fs_desc, char * path, uint32_t id, elf_program_header_32_t * program_header)
Definition at line 24 of file elf_lite.c.
{
     int (*read_drive)(drive_desc_t *drive_desc, char *path, uint8_t *buf, uint32_t from, uint32_t len) = fs_desc->read;
     read_drive(drive_desc, path, (uint8_t*)program_header, elf_header.e_phoff + id * elf_header.e_phentsize, sizeof(*program_header));
 }
References buf, elf_header_32_t::e_phentsize, elf_header_32_t::e_phoff, elf_header, and fs_desc_t::read.
Referenced by elf_load_kernel().
elf_read_section_header()
void elf_read_section_header (drive_desc_t * drive_desc, fs_desc_t * fs_desc, char * path, uint32_t id, elf_section_header_32_t * section_header)
Definition at line 29 of file elf_lite.c.
{
     int (*read_drive)(drive_desc_t *drive_desc, char *path, uint8_t *buf, uint32_t from, uint32_t len) = fs_desc->read;
     read_drive(drive_desc, path, (uint8_t*)section_header, elf_header.e_shoff + id * elf_header.e_shentsize, sizeof(*section_header));
 }
References buf, elf_header_32_t::e_shentsize, elf_header_32_t::e_shoff, elf_header, and fs_desc_t::read.
Referenced by elf_load_kernel().
Variable Documentation
elf_header
elf_header_32_t elf_header
Elf lite parese kernel file and load it.
Definition at line 8 of file elf_lite.c.
Referenced by elf_load_header(), elf_load_kernel(), elf_read_program_header(), and elf_read_section_header().