oneOS: src/boot/x86/stage2/drivers/elf_lite.h File Reference
elf_lite.h File Reference
#include "../types.h"
#include "drive_desc.h"
#include "fs_desc.h"
Data Structures
struct elf_header_32_t
struct elf_program_header_32_t
struct elf_section_header_32_t
Enumerations
enum E_IDENT_FIELDS {
EI_MAG0 , EI_MAG1 , EI_MAG2 , EI_MAG3 ,
EI_CLASS , EI_DATA , EI_VERSION , EI_OSABI ,
EI_ABIVERSION , EI_MAG0 , EI_MAG1 , EI_MAG2 ,
EI_MAG3 , EI_CLASS , EI_DATA , EI_VERSION ,
EI_OSABI , EI_ABIVERSION
}
enum E_TYPE_FIELDS {
ET_NONE , ET_REL , ET_EXEC , ET_DYN ,
ET_CORE , ET_NONE , ET_REL , ET_EXEC ,
ET_DYN , ET_CORE
}
enum E_MACHINE_FIELDS {
EM_NONE , EM_386 = 3 , EM_PPC = 20 , EM_PPC64 = 21 ,
EM_X86_64 = 62 , EM_NONE , EM_386 = 3 , EM_PPC = 20 ,
EM_PPC64 = 21 , EM_X86_64 = 62
}
enum P_TYPE_FIELDS {
PT_NULL , PT_LOAD , PT_DYNAMIC , PT_INTERP ,
PT_NOTE , PT_SHLIB , PT_PHDR , PT_TLS ,
PT_LOOS = 0x60000000 , PT_HIOS = 0x6FFFFFFF , PT_LOPROC = 0x70000000 , PT_HIPROC = 0x7FFFFFFF ,
PT_NULL , PT_LOAD , PT_DYNAMIC , PT_INTERP ,
PT_NOTE , PT_SHLIB , PT_PHDR , PT_TLS ,
PT_LOOS = 0x60000000 , PT_HIOS = 0x6FFFFFFF , PT_LOPROC = 0x70000000 , PT_HIPROC = 0x7FFFFFFF
}
enum SH_TYPE_FIELDS {
SHT_NULL , SHT_PROGBITS , SHT_SYMTAB , SHT_STRTAB ,
SHT_RELA , SHT_HASH , SHT_DYNAMIC , SHT_NOTE ,
SHT_NOBITS , SHT_REL , SHT_SHLIB , SHT_DYNSYM ,
SHT_INIT_ARRAY , SHT_FINI_ARRAY , SHT_PREINIT_ARRAY , SHT_GROUP ,
SHT_SYMTAB_SHNDX , SHT_LOOS = 1610612736 , SHT_HIOS = 1879048191 , SHT_LOPROC = 1879048192 ,
SHT_HIPROC = 2147483647 , SHT_LOUSER = 2147483648 , SHT_HIUSER = 4294967295 , SHT_NULL ,
SHT_PROGBITS , SHT_SYMTAB , SHT_STRTAB , SHT_RELA ,
SHT_HASH , SHT_DYNAMIC , SHT_NOTE , SHT_NOBITS ,
SHT_REL , SHT_SHLIB , SHT_DYNSYM , SHT_INIT_ARRAY ,
SHT_FINI_ARRAY , SHT_PREINIT_ARRAY , SHT_GROUP , SHT_SYMTAB_SHNDX ,
SHT_LOOS = 1610612736 , SHT_HIOS = 1879048191 , SHT_LOPROC = 1879048192 , SHT_HIPROC = 2147483647 ,
SHT_LOUSER = 2147483648 , SHT_HIUSER = 4294967295
}
enum SH_FLAGS_FIELDS {
SHF_WRITE = 0x1 , SHF_ALLOC = 0x2 , SHF_EXECINSTR = 0x4 , SHF_MERGE = 0x10 ,
SHF_STRINGS = 0x20 , SHF_INFO_LINK = 0x40 , SHF_LINK_ORDER = 0x80 , SHF_OS_NONCONFORMING = 0x100 ,
SHF_GROUP = 0x200 , SHF_TLS = 0x400 , SHF_COMPRESSED = 0x800 , SHF_MASKOS = 0x0ff00000 ,
SHF_MASKPROC = 0xf0000000 , SHF_WRITE = 0x1 , SHF_ALLOC = 0x2 , SHF_EXECINSTR = 0x4 ,
SHF_MERGE = 0x10 , SHF_STRINGS = 0x20 , SHF_INFO_LINK = 0x40 , SHF_LINK_ORDER = 0x80 ,
SHF_OS_NONCONFORMING = 0x100 , SHF_GROUP = 0x200 , SHF_TLS = 0x400 , SHF_COMPRESSED = 0x800 ,
SHF_MASKOS = 0x0ff00000 , SHF_MASKPROC = 0xf0000000
}
Functions
int elf_load_header (drive_desc_t *drive_desc, fs_desc_t *fs_desc, char *path)
int elf_load_kernel (drive_desc_t *drive_desc, fs_desc_t *fs_desc, char *path, uint32_t *kernel_size)
Enumeration Type Documentation
E_IDENT_FIELDS
enum E_IDENT_FIELDS
Enumerator
EI_MAG0
EI_MAG1
EI_MAG2
EI_MAG3
EI_CLASS
EI_DATA
EI_VERSION
EI_OSABI
EI_ABIVERSION
EI_MAG0
EI_MAG1
EI_MAG2
EI_MAG3
EI_CLASS
EI_DATA
EI_VERSION
EI_OSABI
EI_ABIVERSION
Definition at line 8 of file elf_lite.h.
                     {
     EI_MAG0,
     EI_MAG1,
     EI_MAG2,
     EI_MAG3,
     EI_CLASS,
     EI_DATA,
     EI_VERSION,
     EI_OSABI,
     EI_ABIVERSION,
 };
E_MACHINE_FIELDS
enum E_MACHINE_FIELDS
Enumerator
EM_NONE
EM_386
EM_PPC
EM_PPC64
EM_X86_64
EM_NONE
EM_386
EM_PPC
EM_PPC64
EM_X86_64
Definition at line 28 of file elf_lite.h.
                       {
     EM_NONE,
     EM_386 = 3,
     EM_PPC = 20,
     EM_PPC64 = 21,
     EM_X86_64 = 62,
 };
E_TYPE_FIELDS
enum E_TYPE_FIELDS
Enumerator
ET_NONE
ET_REL
ET_EXEC
ET_DYN
ET_CORE
ET_NONE
ET_REL
ET_EXEC
ET_DYN
ET_CORE
Definition at line 20 of file elf_lite.h.
                    {
     ET_NONE,
     ET_REL,
     ET_EXEC,
     ET_DYN,
     ET_CORE,
 };
P_TYPE_FIELDS
enum P_TYPE_FIELDS
Enumerator
PT_NULL
PT_LOAD
PT_DYNAMIC
PT_INTERP
PT_NOTE
PT_SHLIB
PT_PHDR
PT_TLS
PT_LOOS
PT_HIOS
PT_LOPROC
PT_HIPROC
PT_NULL
PT_LOAD
PT_DYNAMIC
PT_INTERP
PT_NOTE
PT_SHLIB
PT_PHDR
PT_TLS
PT_LOOS
PT_HIOS
PT_LOPROC
PT_HIPROC
Definition at line 54 of file elf_lite.h.
                    {
     PT_NULL,
     PT_LOAD,
     PT_DYNAMIC,
     PT_INTERP,
     PT_NOTE,
     PT_SHLIB,
     PT_PHDR,
     PT_TLS,
     PT_LOOS = 0x60000000,
     PT_HIOS = 0x6FFFFFFF,
     PT_LOPROC = 0x70000000,
     PT_HIPROC = 0x7FFFFFFF,
 };
SH_FLAGS_FIELDS
enum SH_FLAGS_FIELDS
Enumerator
SHF_WRITE
SHF_ALLOC
SHF_EXECINSTR
SHF_MERGE
SHF_STRINGS
SHF_INFO_LINK
SHF_LINK_ORDER
SHF_OS_NONCONFORMING
SHF_GROUP
SHF_TLS
SHF_COMPRESSED
SHF_MASKOS
SHF_MASKPROC
SHF_WRITE
SHF_ALLOC
SHF_EXECINSTR
SHF_MERGE
SHF_STRINGS
SHF_INFO_LINK
SHF_LINK_ORDER
SHF_OS_NONCONFORMING
SHF_GROUP
SHF_TLS
SHF_COMPRESSED
SHF_MASKOS
SHF_MASKPROC
Definition at line 108 of file elf_lite.h.
                      {
     SHF_WRITE = 0x1,
     SHF_ALLOC = 0x2,
     SHF_EXECINSTR = 0x4,
     SHF_MERGE = 0x10,
     SHF_STRINGS = 0x20,
     SHF_INFO_LINK = 0x40,
     SHF_LINK_ORDER = 0x80,
     SHF_OS_NONCONFORMING = 0x100,
     SHF_GROUP = 0x200,
     SHF_TLS = 0x400,
     SHF_COMPRESSED = 0x800,
     SHF_MASKOS = 0x0ff00000,
     SHF_MASKPROC = 0xf0000000
 };
SH_TYPE_FIELDS
enum SH_TYPE_FIELDS
Enumerator
SHT_NULL
SHT_PROGBITS
SHT_SYMTAB
SHT_STRTAB
SHT_RELA
SHT_HASH
SHT_DYNAMIC
SHT_NOTE
SHT_NOBITS
SHT_REL
SHT_SHLIB
SHT_DYNSYM
SHT_INIT_ARRAY
SHT_FINI_ARRAY
SHT_PREINIT_ARRAY
SHT_GROUP
SHT_SYMTAB_SHNDX
SHT_LOOS
SHT_HIOS
SHT_LOPROC
SHT_HIPROC
SHT_LOUSER
SHT_HIUSER
SHT_NULL
SHT_PROGBITS
SHT_SYMTAB
SHT_STRTAB
SHT_RELA
SHT_HASH
SHT_DYNAMIC
SHT_NOTE
SHT_NOBITS
SHT_REL
SHT_SHLIB
SHT_DYNSYM
SHT_INIT_ARRAY
SHT_FINI_ARRAY
SHT_PREINIT_ARRAY
SHT_GROUP
SHT_SYMTAB_SHNDX
SHT_LOOS
SHT_HIOS
SHT_LOPROC
SHT_HIPROC
SHT_LOUSER
SHT_HIUSER
Definition at line 81 of file elf_lite.h.
                     {
     SHT_NULL,
     SHT_PROGBITS,
     SHT_SYMTAB,
     SHT_STRTAB,
     SHT_RELA,
     SHT_HASH,
     SHT_DYNAMIC,
     SHT_NOTE,
     SHT_NOBITS,
     SHT_REL,
     SHT_SHLIB,
     SHT_DYNSYM,
     SHT_INIT_ARRAY,
     SHT_FINI_ARRAY,
     SHT_PREINIT_ARRAY,
     SHT_GROUP,
     SHT_SYMTAB_SHNDX,
     SHT_LOOS = 1610612736,
     SHT_HIOS = 1879048191,
     SHT_LOPROC = 1879048192,
     SHT_HIPROC = 2147483647,
     SHT_LOUSER = 2147483648,
     SHT_HIUSER = 4294967295,
 };
Function Documentation
elf_load_header()
int elf_load_header (drive_desc_t * drive_desc, fs_desc_t * fs_desc, char * path)
Definition at line 10 of file elf_lite.c.
{
     int (*read_drive)(drive_desc_t *drive_desc, char *path, uint8_t *buf, uint32_t from, uint32_t len) = fs_desc->read;
     read_drive(drive_desc, path, (uint8_t*)&elf_header, 0, sizeof(elf_header_32_t));
     if (elf_header.e_ident[EI_MAG0] != 0x7F ||
         elf_header.e_ident[EI_MAG1] != 0x45 ||
         elf_header.e_ident[EI_MAG2] != 0x4c ||
         elf_header.e_ident[EI_MAG3] != 0x46) {
         return -1;
     }
     return 0;
 }
References buf, elf_header_32_t::e_ident, EI_MAG0, EI_MAG1, EI_MAG2, EI_MAG3, elf_header, and fs_desc_t::read.
Referenced by elf_load_kernel().
elf_load_kernel()
int elf_load_kernel (drive_desc_t * drive_desc, fs_desc_t * fs_desc, char * path, uint32_t * kernel_size)
Definition at line 34 of file elf_lite.c.
{
     int (*read_drive)(drive_desc_t *drive_desc, char *path, uint8_t *buf, uint32_t from, uint32_t len) = fs_desc->read;
     read_drive(drive_desc, path, (uint8_t*)&elf_header, 0, sizeof(elf_header_32_t));
     if (elf_load_header(drive_desc, fs_desc, path) != 0) {
         return -1;
     }
     // Reading Kernel
     for (uint32_t i = 0; i < elf_header.e_phnum; i++) {
         elf_program_header_32_t program_header;
         elf_read_program_header(drive_desc, fs_desc, path, i, &program_header);
         // Let's load it
         if (program_header.p_type == PT_LOAD) {
             read_drive(drive_desc, path, (uint8_t*)program_header.p_paddr, program_header.p_offset, program_header.p_filesz);
         }
     }
     // Calc Kernel Size
     *kernel_size = 0;
     for (uint32_t i = 0; i < elf_header.e_shnum; i++) {
         elf_section_header_32_t section_header;
         elf_read_section_header(drive_desc, fs_desc, path, i, &section_header);
         if (section_header.sh_type == SHT_NOBITS) {
             *kernel_size += section_header.sh_size;
         }
         if (section_header.sh_type == SHT_PROGBITS) {
             *kernel_size += section_header.sh_size;
         }
     }
     return 0;
 }
References buf, elf_header_32_t::e_phnum, elf_header_32_t::e_shnum, elf_header, elf_load_header(), elf_read_program_header(), elf_read_section_header(), elf_program_header_32_t::p_filesz, elf_program_header_32_t::p_offset, elf_program_header_32_t::p_paddr, elf_program_header_32_t::p_type, PT_LOAD, fs_desc_t::read, elf_section_header_32_t::sh_size, elf_section_header_32_t::sh_type, SHT_NOBITS, and SHT_PROGBITS.
Referenced by stage2().