oneOS: src/kernel/tasking/elf.c File Reference
elf.c File Reference
#include <errno.h>
#include <fs/vfs.h>
#include <tasking/elf.h>
#include <tasking/tasking.h>
Macros
#define MACHINE_ARCH EM_386
Functions
static int _elf_do_load (proc_t *p, file_descriptor_t *fd)
int elf_load (proc_t *p, file_descriptor_t *fd)
Macro Definition Documentation
MACHINE_ARCH
#define MACHINE_ARCH EM_386
Definition at line 14 of file elf.c.
Function Documentation
_elf_do_load()
static int _elf_do_load (proc_t * p, file_descriptor_t * fd) static
Definition at line 16 of file elf.c.
 {
 }
Referenced by elf_load().
elf_load()
int elf_load (proc_t * p, file_descriptor_t * fd)
Definition at line 20 of file elf.c.
 {
     elf_header_32_t header;
     int err = vfs_read(fd, &header, sizeof(header));
     if (err != sizeof(header)) {
         return err;
     }
     char elf_signature[] = { 0x7F, 0x45, 0x4c, 0x46 };
     if (memcmp(header.e_ident, elf_signature, sizeof(elf_signature)) != 0) {
         return -ENOEXEC;
     }
     // FIXME: Currently we support only 32bit execs
     if (header.e_ident[EI_CLASS] != ELF_CLASS_32) {
         return -EBADMACHO;
     }
     if (header.e_type != ET_EXEC) {
         return -ENOEXEC;
     }
     if (header.e_machine != MACHINE_ARCH) {
         return -EBADARCH;
     }
     return _elf_do_load(p, fd);
 }
References _elf_do_load(), EI_CLASS, ELF_CLASS_32, ENOEXEC, ET_EXEC, fat16_formatter::header(), MACHINE_ARCH, memcmp(), p, and vfs_read().