oneOS: src/boot/x86/stage2/drivers/ext2_lite.h File Reference
ext2_lite.h File Reference
#include "../types.h"
#include "drive_desc.h"
#include "fs_desc.h"
Data Structures
struct superblock_t
struct group_desc_t
struct inode_t
struct dir_entry_t
Macros
#define SUPERBLOCK_START 1024
#define SUPERBLOCK_LEN (sizeof(superblock_t))
#define GROUP_LEN (sizeof(group_desc_t))
#define S_IFSOCK 0xC000
#define S_IFLNK 0xA000
#define S_IFREG 0x8000
#define S_IFBLK 0x6000
#define S_IFDIR 0x4000
#define S_IFCHR 0x2000
#define S_IFIFO 0x1000
#define S_ISUID 0x0800
#define S_ISGID 0x0400
#define S_ISVTX 0x0200
#define S_IRUSR 0x0100
#define S_IWUSR 0x0080
#define S_IXUSR 0x0040
#define S_IRGRP 0x0020
#define S_IWGRP 0x0010
#define S_IXGRP 0x0008
#define S_IROTH 0x0004
#define S_IWOTH 0x0002
#define S_IXOTH 0x0001
#define INODE_LEN (sizeof(inode_t))
#define INODES_RESERVED 11
Functions
int ext2_lite_init (drive_desc_t *drive_desc, fs_desc_t *fs_desc)
int ext2_lite_get_inode (drive_desc_t *drive_desc, char *path, inode_t *file_inode)
int ext2_lite_read (drive_desc_t *drive_desc, char *path, uint8_t *buf, uint32_t from, uint32_t len)
Macro Definition Documentation
GROUP_LEN
#define GROUP_LEN (sizeof(group_desc_t))
Definition at line 55 of file ext2_lite.h.
INODE_LEN
#define INODE_LEN (sizeof(inode_t))
Definition at line 89 of file ext2_lite.h.
INODES_RESERVED
#define INODES_RESERVED 11
Definition at line 90 of file ext2_lite.h.
S_IFBLK
#define S_IFBLK 0x6000
Definition at line 70 of file ext2_lite.h.
S_IFCHR
#define S_IFCHR 0x2000
Definition at line 72 of file ext2_lite.h.
S_IFDIR
#define S_IFDIR 0x4000
Definition at line 71 of file ext2_lite.h.
S_IFIFO
#define S_IFIFO 0x1000
Definition at line 73 of file ext2_lite.h.
S_IFLNK
#define S_IFLNK 0xA000
Definition at line 68 of file ext2_lite.h.
S_IFREG
#define S_IFREG 0x8000
Definition at line 69 of file ext2_lite.h.
S_IFSOCK
#define S_IFSOCK 0xC000
Definition at line 67 of file ext2_lite.h.
S_IRGRP
#define S_IRGRP 0x0020
Definition at line 82 of file ext2_lite.h.
S_IROTH
#define S_IROTH 0x0004
Definition at line 85 of file ext2_lite.h.
S_IRUSR
#define S_IRUSR 0x0100
Definition at line 79 of file ext2_lite.h.
S_ISGID
#define S_ISGID 0x0400
Definition at line 76 of file ext2_lite.h.
S_ISUID
#define S_ISUID 0x0800
Definition at line 75 of file ext2_lite.h.
S_ISVTX
#define S_ISVTX 0x0200
Definition at line 77 of file ext2_lite.h.
S_IWGRP
#define S_IWGRP 0x0010
Definition at line 83 of file ext2_lite.h.
S_IWOTH
#define S_IWOTH 0x0002
Definition at line 86 of file ext2_lite.h.
S_IWUSR
#define S_IWUSR 0x0080
Definition at line 80 of file ext2_lite.h.
S_IXGRP
#define S_IXGRP 0x0008
Definition at line 84 of file ext2_lite.h.
S_IXOTH
#define S_IXOTH 0x0001
Definition at line 87 of file ext2_lite.h.
S_IXUSR
#define S_IXUSR 0x0040
Definition at line 81 of file ext2_lite.h.
SUPERBLOCK_LEN
#define SUPERBLOCK_LEN (sizeof(superblock_t))
Definition at line 9 of file ext2_lite.h.
SUPERBLOCK_START
#define SUPERBLOCK_START 1024
Definition at line 8 of file ext2_lite.h.
Function Documentation
ext2_lite_get_inode()
int ext2_lite_get_inode (drive_desc_t * drive_desc, char * path, inode_t * file_inode)
Definition at line 149 of file ext2_lite.c.
{
     active_drive_desc = drive_desc;
     // printf("AT GET INODE\n");
     inode_t root_inode;
     _ext2_lite_read_inode(2, &root_inode);
     int res = -1;
     if (path[0] == '/') {
         res = ext2_lite_scan_dir(root_inode, &path[1], file_inode);
     } else {
         res = ext2_lite_scan_dir(root_inode, path, file_inode);
     }
     return res;
 }
References _ext2_lite_read_inode(), active_drive_desc, and ext2_lite_scan_dir().
Referenced by ext2_lite_read().
ext2_lite_init()
int ext2_lite_init (drive_desc_t * drive_desc, fs_desc_t * fs_desc)
Definition at line 59 of file ext2_lite.c.
{
     active_drive_desc = drive_desc;
     void (*read)(uint32_t sector, uint8_t* read_to) = drive_desc->read;
     _ext2_lite_read((uint8_t*)&superblock, SUPERBLOCK_START, SUPERBLOCK_LEN);
     printd(superblock.log_block_size); printf("\n");
     if (superblock.magic != 0xEF53) {
         return -1;
     }
     if (superblock.rev_level != 0) {
         return -1;
     }
     // TODO currently support up to 8192 bytes a block.
     if (superblock.log_block_size > 3) {
         return -1;
     }
     // fs_desc->get_file_desc = ext2_lite_read;
     fs_desc->read = ext2_lite_read;
     return 0;
 }
References _ext2_lite_read(), active_drive_desc, ext2_lite_read(), superblock_t::log_block_size, superblock_t::magic, printd(), printf(), read(), drive_desc_t::read, fs_desc_t::read, superblock_t::rev_level, superblock, SUPERBLOCK_LEN, and SUPERBLOCK_START.
Referenced by get_fs_of_disk().
ext2_lite_read()
int ext2_lite_read (drive_desc_t * drive_desc, char * path, uint8_t * buf, uint32_t from, uint32_t len)
Definition at line 224 of file ext2_lite.c.
{
     active_drive_desc = drive_desc;
     inode_t inode;
     ext2_lite_get_inode(drive_desc, path, &inode);
     const uint32_t block_len = _ext2_lite_get_block_len();
     uint32_t start_block_index = from / block_len;
     uint32_t end_block_index = (from + len) / block_len;
     uint32_t read_offset = from % block_len;
     uint32_t write_offset = 0;
     for (uint32_t block_index = start_block_index; block_index <= end_block_index; block_index++) {
         uint32_t data_block_index = _ext2_lite_get_block_of_file(&inode, block_index);
         _ext2_lite_read(tmp_block_buf, _ext2_lite_get_offset_of_block(data_block_index), _ext2_lite_get_block_len());
         for (int i = 0; i < _ext2_lite_min(len, block_len - read_offset); i++) {
             buf[write_offset++] = tmp_block_buf[read_offset + i];
         }
         len -= _ext2_lite_min(len, block_len - read_offset);
         read_offset = 0;
     }
     if (len != 0) {
         return -1;
     }
     return 0;
 }
References _ext2_lite_get_block_len(), _ext2_lite_get_block_of_file(), _ext2_lite_get_offset_of_block(), _ext2_lite_min(), _ext2_lite_read(), active_drive_desc, buf, ext2_lite_get_inode(), and tmp_block_buf.
Referenced by ext2_lite_init().