oneOS: src/kernel/fs/ext2/ext2.c File Reference
ext2.c File Reference
#include <errno.h>
#include <fs/vfs.h>
#include <log.h>
#include <mem/kmalloc.h>
#include <time/time_manager.h>
#include <utils/kassert.h>
Macros
#define MAX_BLOCK_LEN 1024
#define MIN(X, Y) (((X) < (Y)) ? (X) : (Y))
#define SUPERBLOCK _ext2_superblocks[dev->dev->id]
#define GROUP_TABLES _ext2_group_table_info[dev->dev->id].table
#define BLOCK_LEN(sb) (1024 << (sb->log_block_size))
#define TO_EXT_BLOCKS_CNT(sb, x) (x / (2 << (sb->log_block_size)))
#define NORM_FILENAME(x) (x + ((4 - (x & 0b11)) & 0b11))
Functions
driver_desc_t _ext2_driver_info ()
static void _ext2_read_from_dev (vfs_device_t *dev, uint8_t *buf, uint32_t start, uint32_t len)
static void _ext2_write_to_dev (vfs_device_t *dev, uint8_t *buf, uint32_t start, uint32_t len)
static uint32_t _ext2_get_disk_size (vfs_device_t *dev)
static bool _ext2_bitmap_get (uint8_t *bitmap, uint32_t index)
static void _ext2_bitmap_set_bit (uint8_t *bitmap, uint32_t index)
static void _ext2_bitmap_unset_bit (uint8_t *bitmap, uint32_t index)
static uint32_t _ext2_get_group_len (superblock_t *sb)
static int _ext2_get_groups_cnt (vfs_device_t *dev, superblock_t *sb)
static uint32_t _ext2_get_block_offset (superblock_t *sb, uint32_t block_index)
static uint32_t _ext2_get_block_of_inode_lev0 (dentry_t *dentry, uint32_t cur_block, uint32_t inode_block_index)
static uint32_t _ext2_get_block_of_inode_lev1 (dentry_t *dentry, uint32_t cur_block, uint32_t inode_block_index)
static uint32_t _ext2_get_block_of_inode_lev2 (dentry_t *dentry, uint32_t cur_block, uint32_t inode_block_index)
static uint32_t _ext2_get_block_of_inode (dentry_t *dentry, uint32_t inode_block_index)
static int _ext2_set_block_of_inode_lev0 (dentry_t *dentry, uint32_t cur_block, uint32_t inode_block_index, uint32_t val)
static int _ext2_set_block_of_inode_lev1 (dentry_t *dentry, uint32_t cur_block, uint32_t inode_block_index, uint32_t val)
static int _ext2_set_block_of_inode_lev2 (dentry_t *dentry, uint32_t cur_block, uint32_t inode_block_index, uint32_t val)
static int _ext2_set_block_of_inode (dentry_t *dentry, uint32_t inode_block_index, uint32_t val)
static int _ext2_find_free_block_index (vfs_device_t *dev, fsdata_t fsdata, uint32_t *block_index, uint32_t group_index)
static int _ext2_allocate_block_index (vfs_device_t *dev, fsdata_t fsdata, uint32_t *block_index, uint32_t pref_group)
static int _ext2_free_block_index (vfs_device_t *dev, fsdata_t fsdata, uint32_t block_index)
static int _ext2_allocate_block_for_inode (dentry_t *dentry, uint32_t pref_group, uint32_t *block_index)
int ext2_read_inode (dentry_t *dentry)
int ext2_write_inode (dentry_t *dentry)
int ext2_free_inode (dentry_t *dentry)
static int _ext2_find_free_inode_index (vfs_device_t *dev, fsdata_t fsdata, uint32_t *inode_index, uint32_t group_index)
static int _ext2_allocate_inode_index (vfs_device_t *dev, fsdata_t fsdata, uint32_t *inode_index, uint32_t pref_group)
static int _ext2_free_inode_index (vfs_device_t *dev, fsdata_t fsdata, uint32_t inode_index)
static int _ext2_decriment_links_count (dentry_t *dentry)
static int _ext2_lookup_block (vfs_device_t *dev, fsdata_t fsdata, uint32_t block_index, const char *name, uint32_t len, uint32_t *found_inode_index)
static int _ext2_getdirent_block (vfs_device_t *dev, fsdata_t fsdata, uint32_t block_index, uint32_t *offset, dirent_t *dirent)
static int _ext2_get_dir_entries_count_in_block (vfs_device_t *dev, fsdata_t fsdata, uint32_t block_index)
static bool _ext2_is_dir_empty (dentry_t *dir)
static int _ext2_add_first_entry_to_dir_block (vfs_device_t *dev, fsdata_t fsdata, uint32_t block_index, dentry_t *child_dentry, const char *filename, uint32_t len)
static int _ext2_add_to_dir_block (vfs_device_t *dev, fsdata_t fsdata, uint32_t block_index, dentry_t *child_dentry, const char *filename, uint32_t len)
static int _ext2_rm_from_dir_block (vfs_device_t *dev, fsdata_t fsdata, uint32_t block_index, dentry_t *child_dentry)
static int _ext2_add_child (dentry_t *dir, dentry_t *child_dentry, const char *name, int len)
static int _ext2_rm_child (dentry_t *dir, dentry_t *child_dentry)
static int _ext2_setup_dir (dentry_t *dir, dentry_t *parent_dir, mode_t mode)
static int _ext2_setup_file (dentry_t *file, mode_t mode)
bool ext2_recognize_drive (vfs_device_t *dev)
int ext2_prepare_fs (vfs_device_t *dev)
void ext2_save_state (vfs_device_t *dev)
fsdata_t get_fsdata (dentry_t *dentry)
int ext2_read (dentry_t *dentry, uint8_t *buf, uint32_t start, uint32_t len)
int ext2_write (dentry_t *dentry, uint8_t *buf, uint32_t start, uint32_t len)
int ext2_truncate (dentry_t *dentry, uint32_t len)
int ext2_lookup (dentry_t *dir, const char *name, uint32_t len, uint32_t *res_inode_indx)
int ext2_mkdir (dentry_t *dir, const char *name, uint32_t len, mode_t mode)
int ext2_getdirent (dentry_t *dir, uint32_t *offset, dirent_t *res)
int ext2_create (dentry_t *dir, const char *name, uint32_t len, mode_t mode)
int ext2_rm (dentry_t *dentry)
static int _ext2_getdents_block (vfs_device_t *dev, fsdata_t fsdata, uint32_t block_index, uint8_t *buf, uint32_t len, uint32_t inner_offset, uint32_t *scanned_bytes)
bool ext2_can_read (dentry_t *dentry, uint32_t start)
bool ext2_can_write (dentry_t *dentry, uint32_t start)
int ext2_rmdir (dentry_t *dir)
int ext2_getdents (dentry_t *dentry, uint8_t *buf, uint32_t *offset, uint32_t len)
void ext2_install ()
Variables
static superblock_t * _ext2_superblocks [MAX_DEVICES_COUNT]
static groups_info_t _ext2_group_table_info [MAX_DEVICES_COUNT]
Macro Definition Documentation
BLOCK_LEN
#define BLOCK_LEN (sb) (1024 << (sb->log_block_size))
Definition at line 21 of file ext2.c.
GROUP_TABLES
#define GROUP_TABLES _ext2_group_table_info[dev->dev->id].table
Definition at line 20 of file ext2.c.
MAX_BLOCK_LEN
#define MAX_BLOCK_LEN 1024
Definition at line 16 of file ext2.c.
MIN
#define MIN (X, Y) (((X) < (Y)) ? (X) : (Y))
Definition at line 18 of file ext2.c.
NORM_FILENAME
#define NORM_FILENAME (x) (x + ((4 - (x & 0b11)) & 0b11))
Definition at line 23 of file ext2.c.
SUPERBLOCK
#define SUPERBLOCK _ext2_superblocks[dev->dev->id]
Definition at line 19 of file ext2.c.
TO_EXT_BLOCKS_CNT
#define TO_EXT_BLOCKS_CNT (sb, x) (x / (2 << (sb->log_block_size)))
Definition at line 22 of file ext2.c.
Function Documentation
_ext2_add_child()
static int _ext2_add_child (dentry_t * dir, dentry_t * child_dentry, const char * name, int len) static
Definition at line 719 of file ext2.c.
 {
     uint32_t block_index;
     uint32_t blocks_per_dir = TO_EXT_BLOCKS_CNT(dir->fsdata.sb, dir->inode->blocks);
     for (int i = 0; i < blocks_per_dir; i++) {
         if (block_index = _ext2_get_block_of_inode(dir, i)) {
             if (_ext2_add_to_dir_block(dir->dev, dir->fsdata, block_index, child_dentry, name, len) == 0) {
                 goto updated_inode;
             }
         }
     }
     // FIXME: group
     uint32_t new_block_index;
     if (_ext2_allocate_block_for_inode(dir, 0, &new_block_index) == 0) {
         if (_ext2_add_first_entry_to_dir_block(dir->dev, dir->fsdata, new_block_index, child_dentry, name, len) == 0) {
             goto updated_inode;
         }
     }
     return -EFAULT;
 updated_inode:
     child_dentry->inode->links_count++;
     dentry_set_flag(child_dentry, DENTRY_DIRTY);
     return 0;
 }
References _ext2_add_first_entry_to_dir_block(), _ext2_add_to_dir_block(), _ext2_allocate_block_for_inode(), _ext2_get_block_of_inode(), inode_t::blocks, DENTRY_DIRTY, dentry_set_flag(), dentry::dev, EFAULT, dentry::fsdata, dentry::inode, inode_t::links_count, copy_bin::name, fsdata_t::sb, and TO_EXT_BLOCKS_CNT.
Referenced by _ext2_setup_dir(), ext2_create(), and ext2_mkdir().
_ext2_add_first_entry_to_dir_block()
static int _ext2_add_first_entry_to_dir_block (vfs_device_t * dev, fsdata_t fsdata, uint32_t block_index, dentry_t * child_dentry, const char * filename, uint32_t len) static
Definition at line 613 of file ext2.c.
 {
     if (block_index == 0) {
         return -EINVAL;
     }
     uint32_t record_name_len = NORM_FILENAME(len);
     uint32_t min_rec_len = 8 + record_name_len;
     dir_entry_t new_entry;
     uint8_t tmp_buf[DIR_ENTRY_LEN];
     _ext2_read_from_dev(dev, tmp_buf, _ext2_get_block_offset(fsdata.sb, block_index), DIR_ENTRY_LEN);
     dir_entry_t* start_of_entry = (dir_entry_t*)tmp_buf;
     new_entry.inode = child_dentry->inode_indx;
     new_entry.rec_len = BLOCK_LEN(fsdata.sb);
     new_entry.name_len = len;
     memcpy((void*)start_of_entry, (void*)&new_entry, 8);
     memcpy((void*)((uint32_t)start_of_entry + 8), (void*)filename, len);
     memset((void*)((uint32_t)start_of_entry + 8 + len), 0, record_name_len - len);
     _ext2_write_to_dev(dev, tmp_buf, _ext2_get_block_offset(fsdata.sb, block_index), DIR_ENTRY_LEN);
     return 0;
 }
References _ext2_get_block_offset(), _ext2_read_from_dev(), _ext2_write_to_dev(), BLOCK_LEN, DIR_ENTRY_LEN, EINVAL, fat16_formatter::filename, dir_entry_t::inode, dentry::inode_indx, memcpy(), memset(), dir_entry_t::name_len, NORM_FILENAME, dir_entry_t::rec_len, and fsdata_t::sb.
Referenced by _ext2_add_child().
_ext2_add_to_dir_block()
static int _ext2_add_to_dir_block (vfs_device_t * dev, fsdata_t fsdata, uint32_t block_index, dentry_t * child_dentry, const char * filename, uint32_t len) static
Definition at line 636 of file ext2.c.
 {
     if (block_index == 0) {
         return -EINVAL;
     }
     uint32_t record_name_len = NORM_FILENAME(len);
     uint32_t min_rec_len = 8 + record_name_len;
     dir_entry_t new_entry;
     uint8_t tmp_buf[MAX_BLOCK_LEN];
     _ext2_read_from_dev(dev, tmp_buf, _ext2_get_block_offset(fsdata.sb, block_index), BLOCK_LEN(fsdata.sb));
     dir_entry_t* start_of_entry = (dir_entry_t*)tmp_buf;
     dir_entry_t* start_of_new_entry;
     if (start_of_entry->inode == 0) {
         kpanic("Ext2: can't add as first entry with help of that function.");
     }
     for (;;) {
         uint32_t cur_filename_len = NORM_FILENAME(start_of_entry->name_len);
         uint32_t cur_rec_len = 8 + cur_filename_len;
         // We have enough place to put both records
         if (start_of_entry->rec_len >= cur_rec_len + min_rec_len) {
             new_entry.inode = child_dentry->inode_indx;
             new_entry.rec_len = start_of_entry->rec_len - cur_rec_len;
             new_entry.name_len = len;
             start_of_new_entry = (dir_entry_t*)((uint32_t)start_of_entry + cur_rec_len);
             start_of_entry->rec_len = cur_rec_len;
             goto update_res;
         }
         start_of_entry = (dir_entry_t*)((uint32_t)start_of_entry + start_of_entry->rec_len);
         if ((uint32_t)start_of_entry >= (uint32_t)tmp_buf + BLOCK_LEN(fsdata.sb)) {
             return -EFAULT;
         }
     }
 update_res:
     memcpy((void*)start_of_new_entry, (void*)&new_entry, 8);
     memcpy((void*)((uint32_t)start_of_new_entry + 8), (void*)filename, len);
     memset((void*)((uint32_t)start_of_new_entry + 8 + len), 0, record_name_len - len);
     _ext2_write_to_dev(dev, tmp_buf, _ext2_get_block_offset(fsdata.sb, block_index), BLOCK_LEN(fsdata.sb));
     return 0;
 }
References _ext2_get_block_offset(), _ext2_read_from_dev(), _ext2_write_to_dev(), BLOCK_LEN, EFAULT, EINVAL, fat16_formatter::filename, dir_entry_t::inode, dentry::inode_indx, kpanic(), MAX_BLOCK_LEN, memcpy(), memset(), dir_entry_t::name_len, NORM_FILENAME, dir_entry_t::rec_len, and fsdata_t::sb.
Referenced by _ext2_add_child().
_ext2_allocate_block_for_inode()
static int _ext2_allocate_block_for_inode (dentry_t * dentry, uint32_t pref_group, uint32_t * block_index) static
Returns allocated block in @block_index
Definition at line 340 of file ext2.c.
 {
     if (_ext2_allocate_block_index(dentry->dev, dentry->fsdata, block_index, pref_group) == 0) {
         uint32_t blocks_per_inode = TO_EXT_BLOCKS_CNT(dentry->fsdata.sb, dentry->inode->blocks);
         if (_ext2_set_block_of_inode(dentry, blocks_per_inode, *block_index) == 0) {
             dentry->inode->blocks += BLOCK_LEN(dentry->fsdata.sb) / 512;
             dentry_set_flag(dentry, DENTRY_DIRTY);
             return 0;
         }
     }
     return -ENOSPC;
 }
References _ext2_allocate_block_index(), _ext2_set_block_of_inode(), BLOCK_LEN, inode_t::blocks, DENTRY_DIRTY, dentry_set_flag(), dentry::dev, ENOSPC, dentry::fsdata, dentry::inode, fsdata_t::sb, and TO_EXT_BLOCKS_CNT.
Referenced by _ext2_add_child(), and ext2_write().
_ext2_allocate_block_index()
static int _ext2_allocate_block_index (vfs_device_t * dev, fsdata_t fsdata, uint32_t * block_index, uint32_t pref_group) static
Definition at line 308 of file ext2.c.
 {
     // TODO: change group count to real value
     uint32_t groups_cnt = 3;
     for (int i = 0; i < groups_cnt; i++) {
         if (GROUP_TABLES[(pref_group + i) % groups_cnt].free_inodes_count) {
             if (_ext2_find_free_block_index(dev, fsdata, block_index, pref_group) == 0) {
                 return 0;
             }
         }
     }
     return -ENOSPC;
 }
References _ext2_find_free_block_index(), ENOSPC, and GROUP_TABLES.
Referenced by _ext2_allocate_block_for_inode().
_ext2_allocate_inode_index()
static int _ext2_allocate_inode_index (vfs_device_t * dev, fsdata_t fsdata, uint32_t * inode_index, uint32_t pref_group) static
Definition at line 393 of file ext2.c.
 {
     /* TODO: change group count to real value */
     uint32_t groups_cnt = 3;
     for (int i = 0; i < groups_cnt; i++) {
         if (fsdata.gt->table[(pref_group + i) % groups_cnt].free_inodes_count) {
             if (_ext2_find_free_inode_index(dev, fsdata, inode_index, pref_group) == 0) {
                 return 0;
             }
         }
     }
     return -ENOSPC;
 }
References _ext2_find_free_inode_index(), ENOSPC, group_desc_t::free_inodes_count, fsdata_t::gt, and groups_info_t::table.
Referenced by ext2_create(), and ext2_mkdir().
_ext2_bitmap_get()
static bool _ext2_bitmap_get (uint8_t * bitmap, uint32_t index) inline static
UTILS
Definition at line 159 of file ext2.c.
 {
     return (bitmap[index / 8] >> (index % 8)) & 1;
 }
Referenced by _ext2_find_free_block_index(), and _ext2_find_free_inode_index().
_ext2_bitmap_set_bit()
static void _ext2_bitmap_set_bit (uint8_t * bitmap, uint32_t index) inline static
Definition at line 164 of file ext2.c.
 {
     bitmap[index / 8] |= (uint8_t)(1 << (index % 8));
 }
Referenced by _ext2_find_free_block_index(), and _ext2_find_free_inode_index().
_ext2_bitmap_unset_bit()
static void _ext2_bitmap_unset_bit (uint8_t * bitmap, uint32_t index) inline static
Definition at line 169 of file ext2.c.
 {
     bitmap[index / 8] &= ~(1 << (index % 8));
 }
Referenced by _ext2_free_block_index(), and _ext2_free_inode_index().
_ext2_decriment_links_count()
static int _ext2_decriment_links_count (dentry_t * dentry) static
Definition at line 438 of file ext2.c.
 {
     return (--dentry->inode->links_count) == 0;
 }
References dentry::inode, and inode_t::links_count.
_ext2_driver_info()
driver_desc_t _ext2_driver_info ()
INIT FUNCTIONS
Definition at line 1099 of file ext2.c.
 {
     driver_desc_t fs_desc;
     fs_desc.type = DRIVER_FILE_SYSTEM;
     fs_desc.auto_start = false;
     fs_desc.is_device_driver = false;
     fs_desc.is_device_needed = false;
     fs_desc.is_driver_needed = false;
     fs_desc.functions[DRIVER_NOTIFICATION] = 0;
     fs_desc.functions[DRIVER_FILE_SYSTEM_RECOGNIZE] = ext2_recognize_drive;
     fs_desc.functions[DRIVER_FILE_SYSTEM_PREPARE_FS] = ext2_prepare_fs;
     fs_desc.functions[DRIVER_FILE_SYSTEM_CAN_READ] = ext2_can_read;
     fs_desc.functions[DRIVER_FILE_SYSTEM_CAN_WRITE] = ext2_can_write;
     fs_desc.functions[DRIVER_FILE_SYSTEM_READ] = ext2_read;
     fs_desc.functions[DRIVER_FILE_SYSTEM_WRITE] = ext2_write;
     fs_desc.functions[DRIVER_FILE_SYSTEM_OPEN] = 0; /* No custom open, vfs will use its code */
     fs_desc.functions[DRIVER_FILE_SYSTEM_TRUNCATE] = ext2_truncate;
     fs_desc.functions[DRIVER_FILE_SYSTEM_MKDIR] = ext2_mkdir;
     fs_desc.functions[DRIVER_FILE_SYSTEM_RMDIR] = ext2_rmdir;
     fs_desc.functions[DRIVER_FILE_SYSTEM_EJECT_DEVICE] = ext2_save_state;
     fs_desc.functions[DRIVER_FILE_SYSTEM_READ_INODE] = ext2_read_inode;
     fs_desc.functions[DRIVER_FILE_SYSTEM_WRITE_INODE] = ext2_write_inode;
     fs_desc.functions[DRIVER_FILE_SYSTEM_FREE_INODE] = ext2_free_inode;
     fs_desc.functions[DRIVER_FILE_SYSTEM_GET_FSDATA] = get_fsdata;
     fs_desc.functions[DRIVER_FILE_SYSTEM_LOOKUP] = ext2_lookup;
     fs_desc.functions[DRIVER_FILE_SYSTEM_GETDENTS] = ext2_getdents;
     fs_desc.functions[DRIVER_FILE_SYSTEM_CREATE] = ext2_create;
     fs_desc.functions[DRIVER_FILE_SYSTEM_UNLINK] = ext2_rm;
     fs_desc.functions[DRIVER_FILE_SYSTEM_IOCTL] = 0;
     fs_desc.functions[DRIVER_FILE_SYSTEM_MMAP] = 0;
     return fs_desc;
 }
References driver_desc_t::auto_start, DRIVER_FILE_SYSTEM, DRIVER_FILE_SYSTEM_CAN_READ, DRIVER_FILE_SYSTEM_CAN_WRITE, DRIVER_FILE_SYSTEM_CREATE, DRIVER_FILE_SYSTEM_EJECT_DEVICE, DRIVER_FILE_SYSTEM_FREE_INODE, DRIVER_FILE_SYSTEM_GET_FSDATA, DRIVER_FILE_SYSTEM_GETDENTS, DRIVER_FILE_SYSTEM_IOCTL, DRIVER_FILE_SYSTEM_LOOKUP, DRIVER_FILE_SYSTEM_MKDIR, DRIVER_FILE_SYSTEM_MMAP, DRIVER_FILE_SYSTEM_OPEN, DRIVER_FILE_SYSTEM_PREPARE_FS, DRIVER_FILE_SYSTEM_READ, DRIVER_FILE_SYSTEM_READ_INODE, DRIVER_FILE_SYSTEM_RECOGNIZE, DRIVER_FILE_SYSTEM_RMDIR, DRIVER_FILE_SYSTEM_TRUNCATE, DRIVER_FILE_SYSTEM_UNLINK, DRIVER_FILE_SYSTEM_WRITE, DRIVER_FILE_SYSTEM_WRITE_INODE, DRIVER_NOTIFICATION, ext2_can_read(), ext2_can_write(), ext2_create(), ext2_free_inode(), ext2_getdents(), ext2_lookup(), ext2_mkdir(), ext2_prepare_fs(), ext2_read(), ext2_read_inode(), ext2_recognize_drive(), ext2_rm(), ext2_rmdir(), ext2_save_state(), ext2_truncate(), ext2_write(), ext2_write_inode(), driver_desc_t::functions, get_fsdata(), driver_desc_t::is_device_driver, driver_desc_t::is_device_needed, driver_desc_t::is_driver_needed, and driver_desc_t::type.
Referenced by ext2_install().
_ext2_find_free_block_index()
static int _ext2_find_free_block_index (vfs_device_t * dev, fsdata_t fsdata, uint32_t * block_index, uint32_t group_index) static
Definition at line 292 of file ext2.c.
 {
     uint8_t block_bitmap[MAX_BLOCK_LEN];
     _ext2_read_from_dev(dev, block_bitmap, _ext2_get_block_offset(fsdata.sb, fsdata.gt->table[group_index].block_bitmap), BLOCK_LEN(fsdata.sb));
     for (uint32_t off = 0; off < BLOCK_LEN(fsdata.sb); off++) {
         if (!_ext2_bitmap_get(block_bitmap, off)) {
             *block_index = fsdata.sb->blocks_per_group * group_index + off + 1;
             _ext2_bitmap_set_bit(block_bitmap, off);
             _ext2_write_to_dev(dev, block_bitmap, _ext2_get_block_offset(fsdata.sb, fsdata.gt->table[group_index].block_bitmap), BLOCK_LEN(fsdata.sb));
             return 0;
         }
     }
     return -ENOSPC;
 }
References _ext2_bitmap_get(), _ext2_bitmap_set_bit(), _ext2_get_block_offset(), _ext2_read_from_dev(), _ext2_write_to_dev(), group_desc_t::block_bitmap, BLOCK_LEN, superblock_t::blocks_per_group, ENOSPC, fsdata_t::gt, MAX_BLOCK_LEN, fsdata_t::sb, and groups_info_t::table.
Referenced by _ext2_allocate_block_index().
_ext2_find_free_inode_index()
static int _ext2_find_free_inode_index (vfs_device_t * dev, fsdata_t fsdata, uint32_t * inode_index, uint32_t group_index) static
Definition at line 377 of file ext2.c.
 {
     uint8_t inode_bitmap[MAX_BLOCK_LEN];
     _ext2_read_from_dev(dev, inode_bitmap, _ext2_get_block_offset(fsdata.sb, fsdata.gt->table[group_index].inode_bitmap), BLOCK_LEN(fsdata.sb));
     for (uint32_t off = 0; off < BLOCK_LEN(fsdata.sb); off++) {
         if (!_ext2_bitmap_get(inode_bitmap, off)) {
             *inode_index = SUPERBLOCK->inodes_per_group * group_index + off + 1;
             _ext2_bitmap_set_bit(inode_bitmap, off);
             _ext2_write_to_dev(dev, inode_bitmap, _ext2_get_block_offset(fsdata.sb, fsdata.gt->table[group_index].inode_bitmap), BLOCK_LEN(fsdata.sb));
             return 0;
         }
     }
     return -ENOSPC;
 }
References _ext2_bitmap_get(), _ext2_bitmap_set_bit(), _ext2_get_block_offset(), _ext2_read_from_dev(), _ext2_write_to_dev(), BLOCK_LEN, ENOSPC, fsdata_t::gt, group_desc_t::inode_bitmap, MAX_BLOCK_LEN, fsdata_t::sb, SUPERBLOCK, and groups_info_t::table.
Referenced by _ext2_allocate_inode_index().
_ext2_free_block_index()
static int _ext2_free_block_index (vfs_device_t * dev, fsdata_t fsdata, uint32_t block_index) static
Definition at line 322 of file ext2.c.
 {
     block_index--;
     uint32_t block_len = BLOCK_LEN(fsdata.sb);
     uint32_t group_index = block_index / block_len;
     uint32_t off = block_index % block_len;
     uint8_t block_bitmap[MAX_BLOCK_LEN];
     _ext2_read_from_dev(dev, block_bitmap, _ext2_get_block_offset(fsdata.sb, fsdata.gt->table[group_index].block_bitmap), block_len);
     _ext2_bitmap_unset_bit(block_bitmap, off);
     _ext2_write_to_dev(dev, block_bitmap, _ext2_get_block_offset(fsdata.sb, fsdata.gt->table[group_index].block_bitmap), block_len);
     return 0;
 }
References _ext2_bitmap_unset_bit(), _ext2_get_block_offset(), _ext2_read_from_dev(), _ext2_write_to_dev(), group_desc_t::block_bitmap, BLOCK_LEN, fsdata_t::gt, MAX_BLOCK_LEN, fsdata_t::sb, and groups_info_t::table.
Referenced by ext2_free_inode(), and ext2_truncate().
_ext2_free_inode_index()
static int _ext2_free_inode_index (vfs_device_t * dev, fsdata_t fsdata, uint32_t inode_index) static
Definition at line 407 of file ext2.c.
 {
     inode_index--;
     uint32_t block_len = BLOCK_LEN(fsdata.sb);
     uint32_t inodes_per_group = fsdata.sb->inodes_per_group;
     uint32_t group_index = inode_index / inodes_per_group;
     uint32_t off = inode_index % inodes_per_group;
     uint8_t inode_bitmap[MAX_BLOCK_LEN];
     _ext2_read_from_dev(dev, inode_bitmap, _ext2_get_block_offset(fsdata.sb, fsdata.gt->table[group_index].inode_bitmap), block_len);
     _ext2_bitmap_unset_bit(inode_bitmap, off);
     _ext2_write_to_dev(dev, inode_bitmap, _ext2_get_block_offset(fsdata.sb, fsdata.gt->table[group_index].inode_bitmap), block_len);
     return 0;
 }
References _ext2_bitmap_unset_bit(), _ext2_get_block_offset(), _ext2_read_from_dev(), _ext2_write_to_dev(), BLOCK_LEN, fsdata_t::gt, group_desc_t::inode_bitmap, superblock_t::inodes_per_group, MAX_BLOCK_LEN, fsdata_t::sb, and groups_info_t::table.
Referenced by ext2_free_inode().
_ext2_get_block_of_inode()
static uint32_t _ext2_get_block_of_inode (dentry_t * dentry, uint32_t inode_block_index) static
Definition at line 233 of file ext2.c.
 {
     uint32_t block_len = BLOCK_LEN(dentry->fsdata.sb) / 4;
     if (inode_block_index < 12) {
         return dentry->inode->block[inode_block_index];
     } else if (inode_block_index < 12 + block_len) { // single indirect
         return _ext2_get_block_of_inode_lev0(dentry, dentry->inode->block[12], inode_block_index - 12);
     } else if (inode_block_index < 12 + block_len + block_len * block_len) { // double indirect
         return _ext2_get_block_of_inode_lev1(dentry, dentry->inode->block[13], inode_block_index - 12 - block_len);
     } else { // triple indirect
         return _ext2_get_block_of_inode_lev2(dentry, dentry->inode->block[14], inode_block_index - (12 + block_len + block_len * block_len));
     }
 }
References _ext2_get_block_of_inode_lev0(), _ext2_get_block_of_inode_lev1(), _ext2_get_block_of_inode_lev2(), inode_t::block, BLOCK_LEN, dentry::fsdata, dentry::inode, and fsdata_t::sb.
Referenced by _ext2_add_child(), _ext2_is_dir_empty(), _ext2_rm_child(), ext2_free_inode(), ext2_getdents(), ext2_getdirent(), ext2_lookup(), ext2_read(), ext2_truncate(), and ext2_write().
_ext2_get_block_of_inode_lev0()
static uint32_t _ext2_get_block_of_inode_lev0 (dentry_t * dentry, uint32_t cur_block, uint32_t inode_block_index) static
Definition at line 203 of file ext2.c.
 {
     uint32_t offset = inode_block_index;
     uint32_t res;
     _ext2_read_from_dev(dentry->dev, (uint8_t*)&res, _ext2_get_block_offset(dentry->fsdata.sb, cur_block) + offset * 4, 4);
     return res;
 }
References _ext2_get_block_offset(), _ext2_read_from_dev(), dentry::dev, dentry::fsdata, and fsdata_t::sb.
Referenced by _ext2_get_block_of_inode(), and _ext2_get_block_of_inode_lev1().
_ext2_get_block_of_inode_lev1()
static uint32_t _ext2_get_block_of_inode_lev1 (dentry_t * dentry, uint32_t cur_block, uint32_t inode_block_index) static
Definition at line 211 of file ext2.c.
 {
     uint32_t lev_contain = BLOCK_LEN(dentry->fsdata.sb) / 4;
     uint32_t offset = inode_block_index / lev_contain;
     uint32_t offset_inner = inode_block_index % lev_contain;
     uint32_t res;
     _ext2_read_from_dev(dentry->dev, (uint8_t*)&res, _ext2_get_block_offset(dentry->fsdata.sb, cur_block) + offset * 4, 4);
     return res ? _ext2_get_block_of_inode_lev0(dentry, res, offset_inner) : 0;
 }
References _ext2_get_block_of_inode_lev0(), _ext2_get_block_offset(), _ext2_read_from_dev(), BLOCK_LEN, dentry::dev, dentry::fsdata, and fsdata_t::sb.
Referenced by _ext2_get_block_of_inode(), and _ext2_get_block_of_inode_lev2().
_ext2_get_block_of_inode_lev2()
static uint32_t _ext2_get_block_of_inode_lev2 (dentry_t * dentry, uint32_t cur_block, uint32_t inode_block_index) static
Definition at line 221 of file ext2.c.
 {
     uint32_t block_len = BLOCK_LEN(dentry->fsdata.sb) / 4;
     uint32_t lev_contain = block_len * block_len;
     uint32_t offset = inode_block_index / lev_contain;
     uint32_t offset_inner = inode_block_index % lev_contain;
     uint32_t res;
     _ext2_read_from_dev(dentry->dev, (uint8_t*)&res, _ext2_get_block_offset(dentry->fsdata.sb, cur_block) + offset * 4, 4);
     return res ? _ext2_get_block_of_inode_lev1(dentry, res, offset_inner) : 0;
 }
References _ext2_get_block_of_inode_lev1(), _ext2_get_block_offset(), _ext2_read_from_dev(), BLOCK_LEN, dentry::dev, dentry::fsdata, and fsdata_t::sb.
Referenced by _ext2_get_block_of_inode().
_ext2_get_block_offset()
static uint32_t _ext2_get_block_offset (superblock_t * sb, uint32_t block_index) static
BLOCK FUNCTIONS
Definition at line 198 of file ext2.c.
 {
     return SUPERBLOCK_START + (block_index - 1) * BLOCK_LEN(sb);
 }
References BLOCK_LEN, and SUPERBLOCK_START.
Referenced by _ext2_add_first_entry_to_dir_block(), _ext2_add_to_dir_block(), _ext2_find_free_block_index(), _ext2_find_free_inode_index(), _ext2_free_block_index(), _ext2_free_inode_index(), _ext2_get_block_of_inode_lev0(), _ext2_get_block_of_inode_lev1(), _ext2_get_block_of_inode_lev2(), _ext2_get_dir_entries_count_in_block(), _ext2_getdents_block(), _ext2_getdirent_block(), _ext2_lookup_block(), _ext2_rm_from_dir_block(), _ext2_set_block_of_inode_lev0(), _ext2_set_block_of_inode_lev1(), _ext2_set_block_of_inode_lev2(), ext2_prepare_fs(), ext2_read(), ext2_read_inode(), ext2_save_state(), ext2_write(), and ext2_write_inode().
_ext2_get_dir_entries_count_in_block()
static int _ext2_get_dir_entries_count_in_block (vfs_device_t * dev, fsdata_t fsdata, uint32_t block_index) static
Definition at line 516 of file ext2.c.
 {
     ASSERT(block_index != 0);
     const uint32_t block_len = BLOCK_LEN(fsdata.sb);
     uint32_t internal_offset = 0;
     int result = 0;
     uint8_t tmp_buf[MAX_BLOCK_LEN];
     _ext2_read_from_dev(dev, tmp_buf, _ext2_get_block_offset(fsdata.sb, block_index), block_len);
     for (;;) {
         dir_entry_t* start_of_entry = (dir_entry_t*)((uint32_t)tmp_buf + internal_offset);
         internal_offset += start_of_entry->rec_len;
         if (start_of_entry->inode != 0) {
             result++;
         }
         if (internal_offset >= block_len) {
             return result;
         }
     }
     return result;
 }
References _ext2_get_block_offset(), _ext2_read_from_dev(), ASSERT, BLOCK_LEN, dir_entry_t::inode, MAX_BLOCK_LEN, dir_entry_t::rec_len, and fsdata_t::sb.
Referenced by _ext2_is_dir_empty().
_ext2_get_disk_size()
static uint32_t _ext2_get_disk_size (vfs_device_t * dev) static
Definition at line 149 of file ext2.c.
 {
     uint32_t (*get_size)(device_t * d) = drivers[dev->dev->driver_id].desc.functions[DRIVER_STORAGE_CAPACITY];
     return get_size(dev->dev);
 }
References driver_t::desc, vfs_device_t::dev, device_t::driver_id, DRIVER_STORAGE_CAPACITY, drivers, and driver_desc_t::functions.
Referenced by _ext2_get_groups_cnt().
_ext2_get_group_len()
static uint32_t _ext2_get_group_len (superblock_t * sb) inline static
GROUPS FUNCTIONS
Definition at line 178 of file ext2.c.
 {
     return BLOCK_LEN(sb) * BLOCK_LEN(sb) * 8;
 }
References BLOCK_LEN.
Referenced by _ext2_get_groups_cnt().
_ext2_get_groups_cnt()
static int _ext2_get_groups_cnt (vfs_device_t * dev, superblock_t * sb) inline static
Definition at line 183 of file ext2.c.
 {
     uint32_t sz = _ext2_get_disk_size(dev) - SUPERBLOCK_START;
     uint32_t ans = sz / _ext2_get_group_len(sb);
     /* TODO: Work with the last smaller group. */
     // if (sz % get_group_len()) {
     //     ans++;
     // }
     return ans;
 }
References _ext2_get_disk_size(), _ext2_get_group_len(), and SUPERBLOCK_START.
Referenced by ext2_prepare_fs().
_ext2_getdents_block()
static int _ext2_getdents_block (vfs_device_t * dev, fsdata_t fsdata, uint32_t block_index, uint8_t * buf, uint32_t len, uint32_t inner_offset, uint32_t * scanned_bytes) static
_ext2_getdents_block puts dents into @buf from block with index @block_index. @block_index: index block to put from @buf: result buffer @len: len of the buffer @buf @inner_offset: offset of block, shows the start from where to start @scanned_bytes: keeps the result value how many bytes were scanned in this block. return: returns an error (if return < 0) or count of bytes written to @buf.
Definition at line 569 of file ext2.c.
 {
     if (block_index == 0) {
         return -EINVAL;
     }
     const uint32_t block_len = BLOCK_LEN(fsdata.sb);
     int already_read = 0;
     uint8_t tmp_buf[MAX_BLOCK_LEN];
     _ext2_read_from_dev(dev, tmp_buf, _ext2_get_block_offset(fsdata.sb, block_index), block_len);
     for (;;) {
         dir_entry_t* start_of_entry = (dir_entry_t*)((uint32_t)tmp_buf + inner_offset);
         uint32_t record_name_len = NORM_FILENAME(start_of_entry->name_len);
         uint32_t real_rec_len = 8 + record_name_len + 1;
         if (real_rec_len > len) {
             /*  There is no space to put this element in the buffer.
                 If we havn't written anything, that means we can't fit
                 the elem in the buf, so, return an error */
             if (already_read == 0) {
                 return -EINVAL;
             }
             return already_read;
         }
         inner_offset += start_of_entry->rec_len;
         *scanned_bytes += start_of_entry->rec_len;
         if (start_of_entry->inode != 0) {
             // Change it here, to have the correct copied data.
             start_of_entry->rec_len = real_rec_len;
             memcpy(buf + already_read, (uint8_t*)start_of_entry, real_rec_len);
             buf[already_read + real_rec_len - 1] = '\0';
             already_read += real_rec_len;
             len -= real_rec_len;
         }
         if (inner_offset >= block_len) {
             return already_read;
         }
     }
     return already_read;
 }
References _ext2_get_block_offset(), _ext2_read_from_dev(), BLOCK_LEN, buf, EINVAL, dir_entry_t::inode, MAX_BLOCK_LEN, memcpy(), dir_entry_t::name_len, NORM_FILENAME, dir_entry_t::rec_len, and fsdata_t::sb.
Referenced by ext2_getdents().
_ext2_getdirent_block()
static int _ext2_getdirent_block (vfs_device_t * dev, fsdata_t fsdata, uint32_t block_index, uint32_t * offset, dirent_t * dirent) static
Definition at line 483 of file ext2.c.
 {
     if (block_index == 0) {
         return -EINVAL;
     }
     const uint32_t block_len = BLOCK_LEN(fsdata.sb);
     uint32_t internal_offset = *offset % block_len;
     uint8_t tmp_buf[MAX_BLOCK_LEN];
     _ext2_read_from_dev(dev, tmp_buf, _ext2_get_block_offset(fsdata.sb, block_index), block_len);
     for (;;) {
         dir_entry_t* start_of_entry = (dir_entry_t*)((uint32_t)tmp_buf + internal_offset);
         internal_offset += start_of_entry->rec_len;
         *offset += start_of_entry->rec_len;
         if (start_of_entry->inode != 0) {
             int name_len = start_of_entry->name_len;
             if (name_len > 251) {
                 kprintf("[VFS] Full name len is unsupported\n");
                 name_len = 251;
             }
             memcpy(dirent->name, (char*)start_of_entry + 8, name_len);
             dirent->name[name_len] = '\0';
             return 0;
         }
         if (internal_offset >= block_len) {
             return -EFAULT;
         }
     }
     return -EFAULT;
 }
References _ext2_get_block_offset(), _ext2_read_from_dev(), BLOCK_LEN, EFAULT, EINVAL, dir_entry_t::inode, kprintf(), MAX_BLOCK_LEN, memcpy(), dirent::name, dir_entry_t::name_len, dir_entry_t::rec_len, and fsdata_t::sb.
Referenced by ext2_getdirent().
_ext2_is_dir_empty()
static bool _ext2_is_dir_empty (dentry_t * dir) static
Definition at line 541 of file ext2.c.
 {
     const uint32_t block_len = BLOCK_LEN(dir->fsdata.sb);
     uint32_t end_block_index = TO_EXT_BLOCKS_CNT(dir->fsdata.sb, dir->inode->blocks);
     int result = 0;
     for (uint32_t block_index = 0; block_index < end_block_index; block_index++) {
         uint32_t data_block_index = _ext2_get_block_of_inode(dir, block_index);
         result += _ext2_get_dir_entries_count_in_block(dir->dev, dir->fsdata, data_block_index);
         /* 2 here is because don't count . and .. */
         if (result > 2) {
             return false;
         }
     }
     return true;
 }
References _ext2_get_block_of_inode(), _ext2_get_dir_entries_count_in_block(), BLOCK_LEN, inode_t::blocks, dentry::dev, dentry::fsdata, dentry::inode, fsdata_t::sb, and TO_EXT_BLOCKS_CNT.
Referenced by ext2_rmdir().
_ext2_lookup_block()
static int _ext2_lookup_block (vfs_device_t * dev, fsdata_t fsdata, uint32_t block_index, const char * name, uint32_t len, uint32_t * found_inode_index) static
DIR FUNCTIONS
Definition at line 449 of file ext2.c.
 {
     if (block_index == 0) {
         return -EINVAL;
     }
     uint8_t tmp_buf[MAX_BLOCK_LEN];
     _ext2_read_from_dev(dev, tmp_buf, _ext2_get_block_offset(fsdata.sb, block_index), BLOCK_LEN(fsdata.sb));
     dir_entry_t* start_of_entry = (dir_entry_t*)tmp_buf;
     for (;;) {
         if (start_of_entry->inode == 0) {
             return -EFAULT;
         }
         if (start_of_entry->name_len == len) {
             bool is_name_same = true;
             for (int i = 0; i < start_of_entry->name_len; i++) {
                 is_name_same &= (name[i] == *((char*)start_of_entry + 8 + i));
             }
             if (is_name_same) {
                 *found_inode_index = start_of_entry->inode;
                 return 0;
             }
         }
         start_of_entry = (dir_entry_t*)((uint32_t)start_of_entry + start_of_entry->rec_len);
         if ((uint32_t)start_of_entry >= (uint32_t)tmp_buf + BLOCK_LEN(fsdata.sb)) {
             return -EFAULT;
         }
     }
     return -EFAULT;
 }
References _ext2_get_block_offset(), _ext2_read_from_dev(), BLOCK_LEN, EFAULT, EINVAL, dir_entry_t::inode, MAX_BLOCK_LEN, copy_bin::name, dir_entry_t::name_len, dir_entry_t::rec_len, and fsdata_t::sb.
Referenced by ext2_lookup().
_ext2_read_from_dev()
static void _ext2_read_from_dev (vfs_device_t * dev, uint8_t * buf, uint32_t start, uint32_t len) static
DRIVE RELATED FUNCTIONS
Definition at line 108 of file ext2.c.
 {
     void (*read)(device_t * d, uint32_t s, uint8_t * r) = drivers[dev->dev->driver_id].desc.functions[DRIVER_STORAGE_READ];
     int already_read = 0;
     uint32_t sector = start / 512;
     uint32_t start_offset = start % 512;
     uint8_t tmp_buf[512];
     while (len) {
         read(dev->dev, sector, tmp_buf);
         for (int i = 0; i < MIN(512 - start_offset, len); i++) {
             buf[already_read++] = tmp_buf[start_offset + i];
         }
         len -= MIN(512 - start_offset, len);
         sector++;
         start_offset = 0;
     }
 }
References buf, driver_t::desc, vfs_device_t::dev, device_t::driver_id, DRIVER_STORAGE_READ, drivers, driver_desc_t::functions, MIN, and read().
Referenced by _ext2_add_first_entry_to_dir_block(), _ext2_add_to_dir_block(), _ext2_find_free_block_index(), _ext2_find_free_inode_index(), _ext2_free_block_index(), _ext2_free_inode_index(), _ext2_get_block_of_inode_lev0(), _ext2_get_block_of_inode_lev1(), _ext2_get_block_of_inode_lev2(), _ext2_get_dir_entries_count_in_block(), _ext2_getdents_block(), _ext2_getdirent_block(), _ext2_lookup_block(), _ext2_rm_from_dir_block(), _ext2_set_block_of_inode_lev1(), _ext2_set_block_of_inode_lev2(), ext2_prepare_fs(), ext2_read(), ext2_read_inode(), and ext2_recognize_drive().
_ext2_rm_child()
static int _ext2_rm_child (dentry_t * dir, dentry_t * child_dentry) static
Definition at line 748 of file ext2.c.
 {
     uint32_t block_index;
     uint32_t blocks_per_dir = TO_EXT_BLOCKS_CNT(dir->fsdata.sb, dir->inode->blocks);
     for (int i = 0; i < blocks_per_dir; i++) {
         if (block_index = _ext2_get_block_of_inode(dir, i)) {
             if (_ext2_rm_from_dir_block(dir->dev, dir->fsdata, block_index, child_dentry) == 0) {
                 child_dentry->inode->links_count--;
                 dentry_set_flag(child_dentry, DENTRY_DIRTY);
                 return 0;
             }
         }
     }
     return -ENOENT;
 }
References _ext2_get_block_of_inode(), _ext2_rm_from_dir_block(), inode_t::blocks, DENTRY_DIRTY, dentry_set_flag(), dentry::dev, ENOENT, dentry::fsdata, dentry::inode, inode_t::links_count, fsdata_t::sb, and TO_EXT_BLOCKS_CNT.
Referenced by ext2_rm(), and ext2_rmdir().
_ext2_rm_from_dir_block()
static int _ext2_rm_from_dir_block (vfs_device_t * dev, fsdata_t fsdata, uint32_t block_index, dentry_t * child_dentry) static
Definition at line 683 of file ext2.c.
 {
     if (block_index == 0) {
         return -EINVAL;
     }
     uint8_t tmp_buf[MAX_BLOCK_LEN];
     _ext2_read_from_dev(dev, tmp_buf, _ext2_get_block_offset(fsdata.sb, block_index), BLOCK_LEN(fsdata.sb));
     dir_entry_t* start_of_entry = (dir_entry_t*)tmp_buf;
     dir_entry_t* prev_entry = (dir_entry_t*)0;
     for (;;) {
         if (start_of_entry->inode == child_dentry->inode_indx) {
             /* FIXME: just fix that */
             if (!prev_entry) {
                 kpanic("Ext2: can't delete first entry.");
             }
             /* deleting entry */
             start_of_entry->inode = 0;
             prev_entry->rec_len += start_of_entry->rec_len;
             _ext2_write_to_dev(dev, tmp_buf, _ext2_get_block_offset(fsdata.sb, block_index), BLOCK_LEN(fsdata.sb));
             return 0;
         }
         prev_entry = start_of_entry;
         start_of_entry = (dir_entry_t*)((uint32_t)start_of_entry + start_of_entry->rec_len);
         if ((uint32_t)start_of_entry >= (uint32_t)tmp_buf + BLOCK_LEN(fsdata.sb)) {
             return -EFAULT;
         }
     }
 }
References _ext2_get_block_offset(), _ext2_read_from_dev(), _ext2_write_to_dev(), BLOCK_LEN, EFAULT, EINVAL, dir_entry_t::inode, dentry::inode_indx, kpanic(), MAX_BLOCK_LEN, dir_entry_t::rec_len, and fsdata_t::sb.
Referenced by _ext2_rm_child().
_ext2_set_block_of_inode()
int _ext2_set_block_of_inode (dentry_t * dentry, uint32_t inode_block_index, uint32_t val) static
Definition at line 276 of file ext2.c.
 {
     uint32_t block_len = BLOCK_LEN(dentry->fsdata.sb) / 4;
     if (inode_block_index < 12) {
         dentry->inode->block[inode_block_index] = val;
         dentry_set_flag(dentry, DENTRY_DIRTY);
         return 0;
     } else if (inode_block_index < 12 + block_len) { // single indirect
         return _ext2_set_block_of_inode_lev0(dentry, dentry->inode->block[12], inode_block_index - 12, val);
     } else if (inode_block_index < 12 + block_len + block_len * block_len) { // double indirect
         return _ext2_set_block_of_inode_lev1(dentry, dentry->inode->block[13], inode_block_index - 12 - block_len, val);
     } else { // triple indirect
         return _ext2_set_block_of_inode_lev2(dentry, dentry->inode->block[14], inode_block_index - (12 + block_len + block_len * block_len), val);
     }
 }
References _ext2_set_block_of_inode_lev0(), _ext2_set_block_of_inode_lev1(), _ext2_set_block_of_inode_lev2(), inode_t::block, BLOCK_LEN, DENTRY_DIRTY, dentry_set_flag(), dentry::fsdata, dentry::inode, and fsdata_t::sb.
Referenced by _ext2_allocate_block_for_inode().
_ext2_set_block_of_inode_lev0()
static int _ext2_set_block_of_inode_lev0 (dentry_t * dentry, uint32_t cur_block, uint32_t inode_block_index, uint32_t val) static
Definition at line 247 of file ext2.c.
 {
     uint32_t offset = inode_block_index;
     _ext2_write_to_dev(dentry->dev, (uint8_t*)&val, _ext2_get_block_offset(dentry->fsdata.sb, cur_block) + offset * 4, 4);
     return 0;
 }
References _ext2_get_block_offset(), _ext2_write_to_dev(), dentry::dev, dentry::fsdata, and fsdata_t::sb.
Referenced by _ext2_set_block_of_inode(), and _ext2_set_block_of_inode_lev1().
_ext2_set_block_of_inode_lev1()
static int _ext2_set_block_of_inode_lev1 (dentry_t * dentry, uint32_t cur_block, uint32_t inode_block_index, uint32_t val) static
Definition at line 254 of file ext2.c.
 {
     uint32_t lev_contain = BLOCK_LEN(dentry->fsdata.sb) / 4;
     uint32_t offset = inode_block_index / lev_contain;
     uint32_t offset_inner = inode_block_index % lev_contain;
     uint32_t res;
     _ext2_read_from_dev(dentry->dev, (uint8_t*)&res, _ext2_get_block_offset(dentry->fsdata.sb, cur_block) + offset * 4, 4);
     return res ? _ext2_set_block_of_inode_lev0(dentry, res, offset_inner, val) : -1;
 }
References _ext2_get_block_offset(), _ext2_read_from_dev(), _ext2_set_block_of_inode_lev0(), BLOCK_LEN, dentry::dev, dentry::fsdata, and fsdata_t::sb.
Referenced by _ext2_set_block_of_inode(), and _ext2_set_block_of_inode_lev2().
_ext2_set_block_of_inode_lev2()
static int _ext2_set_block_of_inode_lev2 (dentry_t * dentry, uint32_t cur_block, uint32_t inode_block_index, uint32_t val) static
Definition at line 264 of file ext2.c.
 {
     uint32_t block_len = BLOCK_LEN(dentry->fsdata.sb) / 4;
     uint32_t lev_contain = block_len * block_len;
     uint32_t offset = inode_block_index / lev_contain;
     uint32_t offset_inner = inode_block_index % lev_contain;
     uint32_t res;
     _ext2_read_from_dev(dentry->dev, (uint8_t*)&res, _ext2_get_block_offset(dentry->fsdata.sb, cur_block) + offset * 4, 4);
     return res ? _ext2_set_block_of_inode_lev1(dentry, res, offset_inner, val) : -1;
 }
References _ext2_get_block_offset(), _ext2_read_from_dev(), _ext2_set_block_of_inode_lev1(), BLOCK_LEN, dentry::dev, dentry::fsdata, and fsdata_t::sb.
Referenced by _ext2_set_block_of_inode().
_ext2_setup_dir()
static int _ext2_setup_dir (dentry_t * dir, dentry_t * parent_dir, mode_t mode) static
Definition at line 766 of file ext2.c.
 {
     dir->inode->mode = mode;
     dir->inode->uid = 0; // FIXME: uid of real user
     dir->inode->links_count = 0;
     dir->inode->blocks = 0;
     dentry_set_flag(dir, DENTRY_DIRTY);
     if (_ext2_add_child(dir, dir, ".", 1) < 0) {
         return -EFAULT;
     }
     if (_ext2_add_child(dir, parent_dir, "..", 2) < 0) {
         return -EFAULT;
     }
     return 0;
 }
References _ext2_add_child(), inode_t::blocks, DENTRY_DIRTY, dentry_set_flag(), EFAULT, dentry::inode, inode_t::links_count, inode_t::mode, mode, and inode_t::uid.
Referenced by ext2_mkdir().
_ext2_setup_file()
static int _ext2_setup_file (dentry_t * file, mode_t mode) static
FILE FUNCTIONS
Definition at line 786 of file ext2.c.
 {
     file->inode->mode = mode;
     file->inode->uid = 0; // FIXME: uid of real user
     file->inode->links_count = 0;
     file->inode->blocks = 0;
     file->inode->size = 0;
     dentry_set_flag(file, DENTRY_DIRTY);
     return 0;
 }
References inode_t::blocks, DENTRY_DIRTY, dentry_set_flag(), dentry::inode, inode_t::links_count, inode_t::mode, mode, inode_t::size, and inode_t::uid.
Referenced by ext2_create().
_ext2_write_to_dev()
static void _ext2_write_to_dev (vfs_device_t * dev, uint8_t * buf, uint32_t start, uint32_t len) static
Definition at line 127 of file ext2.c.
 {
     void (*read)(device_t * d, uint32_t s, uint8_t * r) = drivers[dev->dev->driver_id].desc.functions[DRIVER_STORAGE_READ];
     void (*write)(device_t * d, uint32_t s, uint8_t * r, uint32_t siz) = drivers[dev->dev->driver_id].desc.functions[DRIVER_STORAGE_WRITE];
     int already_written = 0;
     uint32_t sector = start / 512;
     uint32_t start_offset = start % 512;
     uint8_t tmp_buf[512];
     while (len != 0) {
         if (start_offset != 0 || len < 512) {
             read(dev->dev, sector, tmp_buf);
         }
         for (int i = 0; i < MIN(512 - start_offset, len); i++) {
             tmp_buf[start_offset + i] = buf[already_written++];
         }
         write(dev->dev, sector, tmp_buf, 512);
         len -= MIN(512 - start_offset, len);
         sector++;
         start_offset = 0;
     }
 }
References buf, driver_t::desc, vfs_device_t::dev, device_t::driver_id, DRIVER_STORAGE_READ, DRIVER_STORAGE_WRITE, drivers, driver_desc_t::functions, MIN, read(), and write().
Referenced by _ext2_add_first_entry_to_dir_block(), _ext2_add_to_dir_block(), _ext2_find_free_block_index(), _ext2_find_free_inode_index(), _ext2_free_block_index(), _ext2_free_inode_index(), _ext2_rm_from_dir_block(), _ext2_set_block_of_inode_lev0(), ext2_save_state(), ext2_write(), and ext2_write_inode().
ext2_can_read()
bool ext2_can_read (dentry_t * dentry, uint32_t start)
API FUNTIONS
Definition at line 801 of file ext2.c.
 {
     return true;
 }
Referenced by _ext2_driver_info().
ext2_can_write()
bool ext2_can_write (dentry_t * dentry, uint32_t start)
Definition at line 806 of file ext2.c.
 {
     return true;
 }
Referenced by _ext2_driver_info().
ext2_create()
int ext2_create (dentry_t * dir, const char * name, uint32_t len, mode_t mode)
Definition at line 993 of file ext2.c.
 {
     uint32_t new_file_inode_indx = 0;
     if (_ext2_allocate_inode_index(dir->dev, dir->fsdata, &new_file_inode_indx, 0) < 0) {
         return -ENOSPC;
     }
     dentry_t* new_file = dentry_get(dir->dev_indx, new_file_inode_indx);
     if (_ext2_setup_file(new_file, mode) < 0) {
         dentry_put(new_file);
         return -EFAULT;
     }
     if (_ext2_add_child(dir, new_file, name, len) < 0) {
         dentry_put(new_file);
         return -EFAULT;
     }
     dentry_put(new_file);
     return 0;
 }
References _ext2_add_child(), _ext2_allocate_inode_index(), _ext2_setup_file(), dentry_get(), dentry_put(), dentry::dev, dentry::dev_indx, EFAULT, ENOSPC, dentry::fsdata, mode, and copy_bin::name.
Referenced by _ext2_driver_info().
ext2_free_inode()
int ext2_free_inode (dentry_t * dentry)
Definition at line 423 of file ext2.c.
 {
     ASSERT(dentry->d_count == 0 && dentry->inode->links_count == 0);
     uint32_t block_per_dir = TO_EXT_BLOCKS_CNT(dentry->fsdata.sb, dentry->inode->blocks);
     /* freeing all data blocks */
     for (int block_index = 0; block_index < block_per_dir; block_index++) {
         uint32_t data_block_index = _ext2_get_block_of_inode(dentry, block_index);
         _ext2_free_block_index(dentry->dev, dentry->fsdata, data_block_index);
     }
     _ext2_free_inode_index(dentry->dev, dentry->fsdata, dentry->inode_indx);
     return 0;
 }
References _ext2_free_block_index(), _ext2_free_inode_index(), _ext2_get_block_of_inode(), ASSERT, inode_t::blocks, dentry::d_count, dentry::dev, dentry::fsdata, dentry::inode, dentry::inode_indx, inode_t::links_count, fsdata_t::sb, and TO_EXT_BLOCKS_CNT.
Referenced by _ext2_driver_info().
ext2_getdents()
int ext2_getdents (dentry_t * dentry, uint8_t * buf, uint32_t * offset, uint32_t len)
Definition at line 967 of file ext2.c.
 {
     const uint32_t block_len = BLOCK_LEN(dentry->fsdata.sb);
     uint32_t start_block_index = *offset / block_len;
     uint32_t end_block_index = TO_EXT_BLOCKS_CNT(dentry->fsdata.sb, dentry->inode->blocks);
     uint32_t read_offset = *offset % block_len;
     uint32_t already_read = 0;
     for (uint32_t block_index = start_block_index; block_index < end_block_index; block_index++) {
         uint32_t data_block_index = _ext2_get_block_of_inode(dentry, block_index);
         uint32_t read_from_block = MIN(len, block_len - read_offset);
         int act_read = _ext2_getdents_block(dentry->dev, dentry->fsdata, data_block_index, buf + already_read, read_from_block, read_offset, offset);
         if (act_read < 0) {
             if (already_read == 0) {
                 return act_read;
             }
             return already_read;
         }
         len -= act_read;
         already_read += act_read;
         read_offset = 0;
     }
     return already_read;
 }
References _ext2_get_block_of_inode(), _ext2_getdents_block(), BLOCK_LEN, inode_t::blocks, buf, dentry::dev, dentry::fsdata, dentry::inode, MIN, fsdata_t::sb, and TO_EXT_BLOCKS_CNT.
Referenced by _ext2_driver_info().
ext2_getdirent()
int ext2_getdirent (dentry_t * dir, uint32_t * offset, dirent_t * res)
Definition at line 949 of file ext2.c.
 {
     const uint32_t block_len = BLOCK_LEN(dir->fsdata.sb);
     uint32_t blocks_per_dir = TO_EXT_BLOCKS_CNT(dir->fsdata.sb, dir->inode->blocks);
     if (*offset >= blocks_per_dir * block_len) {
         return -1;
     }
     for (uint32_t block_index = *offset / block_len; block_index < blocks_per_dir; block_index++) {
         uint32_t data_block_index = _ext2_get_block_of_inode(dir, block_index);
         if (_ext2_getdirent_block(dir->dev, dir->fsdata, data_block_index, offset, res) == 0) {
             return 0;
         }
     }
     return 0;
 }
References _ext2_get_block_of_inode(), _ext2_getdirent_block(), BLOCK_LEN, inode_t::blocks, dentry::dev, dentry::fsdata, dentry::inode, fsdata_t::sb, and TO_EXT_BLOCKS_CNT.
ext2_install()
void ext2_install ()
Definition at line 1135 of file ext2.c.
 {
     driver_install(_ext2_driver_info());
 }
References _ext2_driver_info(), and driver_install().
Referenced by stage3().
ext2_lookup()
int ext2_lookup (dentry_t * dir, const char * name, uint32_t len, uint32_t * res_inode_indx)
Definition at line 895 of file ext2.c.
 {
     uint32_t block_per_dir = TO_EXT_BLOCKS_CNT(dir->fsdata.sb, dir->inode->blocks);
     for (int block_index = 0; block_index < block_per_dir; block_index++) {
         uint32_t data_block_index = _ext2_get_block_of_inode(dir, block_index);
         if (_ext2_lookup_block(dir->dev, dir->fsdata, data_block_index, name, len, res_inode_indx) == 0) {
             return 0;
         }
     }
     return -ENOENT;
 }
References _ext2_get_block_of_inode(), _ext2_lookup_block(), inode_t::blocks, dentry::dev, ENOENT, dentry::fsdata, dentry::inode, copy_bin::name, fsdata_t::sb, and TO_EXT_BLOCKS_CNT.
Referenced by _ext2_driver_info().
ext2_mkdir()
int ext2_mkdir (dentry_t * dir, const char * name, uint32_t len, mode_t mode)
Definition at line 907 of file ext2.c.
 {
     uint32_t new_dir_inode_indx = 0;
     if (_ext2_allocate_inode_index(dir->dev, dir->fsdata, &new_dir_inode_indx, 0) < 0) {
         return -ENOSPC;
     }
     dentry_t* new_dir = dentry_get(dir->dev_indx, new_dir_inode_indx);
     if (_ext2_setup_dir(new_dir, dir, mode) < 0) {
         dentry_put(new_dir);
         return -EFAULT;
     }
     if (_ext2_add_child(dir, new_dir, name, len) < 0) {
         dentry_put(new_dir);
         return -EFAULT;
     }
     dentry_put(new_dir);
     return 0;
 }
References _ext2_add_child(), _ext2_allocate_inode_index(), _ext2_setup_dir(), dentry_get(), dentry_put(), dentry::dev, dentry::dev_indx, EFAULT, ENOSPC, dentry::fsdata, mode, and copy_bin::name.
Referenced by _ext2_driver_info().
ext2_prepare_fs()
int ext2_prepare_fs (vfs_device_t * dev)
Definition at line 1051 of file ext2.c.
 {
     superblock_t* superblock = (superblock_t*)kmalloc(SUPERBLOCK_LEN);
     _ext2_read_from_dev(dev, (uint8_t*)superblock, SUPERBLOCK_START, SUPERBLOCK_LEN);
     _ext2_superblocks[dev->dev->id] = superblock;
     // FIXME: for now we consider that we have at max 5 groups
     uint32_t groups_cnt = _ext2_get_groups_cnt(dev, superblock);
     uint32_t group_table_len = groups_cnt * GROUP_LEN;
     group_desc_t* group_table = (group_desc_t*)kmalloc(group_table_len);
     _ext2_read_from_dev(dev, (uint8_t*)group_table, _ext2_get_block_offset(superblock, 2), group_table_len);
     _ext2_group_table_info[dev->dev->id].count = groups_cnt;
     _ext2_group_table_info[dev->dev->id].table = group_table;
     return 0;
 }
References _ext2_get_block_offset(), _ext2_get_groups_cnt(), _ext2_group_table_info, _ext2_read_from_dev(), _ext2_superblocks, groups_info_t::count, vfs_device_t::dev, GROUP_LEN, device_t::id, kmalloc(), superblock, SUPERBLOCK_LEN, SUPERBLOCK_START, and groups_info_t::table.
Referenced by _ext2_driver_info().
ext2_read()
int ext2_read (dentry_t * dentry, uint8_t * buf, uint32_t start, uint32_t len)
Definition at line 811 of file ext2.c.
 {
     const uint32_t block_len = BLOCK_LEN(dentry->fsdata.sb);
     uint32_t blocks_allocated = TO_EXT_BLOCKS_CNT(dentry->fsdata.sb, dentry->inode->blocks);
     uint32_t start_block_index = start / block_len;
     uint32_t end_block_index = MIN((start + len - 1) / block_len, blocks_allocated - 1);
     if (start >= dentry->inode->size) {
         return 0;
     }
     uint32_t have_to_read = MIN(len, dentry->inode->size - start);
     uint32_t read_offset = start % block_len;
     uint32_t already_read = 0;
     for (uint32_t virt_block_index = start_block_index; virt_block_index <= end_block_index; virt_block_index++) {
         uint32_t data_block_index = _ext2_get_block_of_inode(dentry, virt_block_index);
         uint32_t read_from_block = MIN(have_to_read, block_len - read_offset);
         _ext2_read_from_dev(dentry->dev, buf + already_read, _ext2_get_block_offset(dentry->fsdata.sb, data_block_index) + read_offset, read_from_block);
         have_to_read -= read_from_block;
         already_read += read_from_block;
         read_offset = 0;
     }
     return already_read;
 }
References _ext2_get_block_of_inode(), _ext2_get_block_offset(), _ext2_read_from_dev(), BLOCK_LEN, inode_t::blocks, buf, dentry::dev, dentry::fsdata, dentry::inode, MIN, fsdata_t::sb, inode_t::size, and TO_EXT_BLOCKS_CNT.
Referenced by _ext2_driver_info().
ext2_read_inode()
int ext2_read_inode (dentry_t * dentry)
INODE FUNCTIONS
Definition at line 357 of file ext2.c.
 {
     uint32_t inodes_per_group = dentry->fsdata.sb->inodes_per_group;
     uint32_t holder_group = (dentry->inode_indx - 1) / inodes_per_group;
     uint32_t pos_inside_group = (dentry->inode_indx - 1) % inodes_per_group;
     uint32_t inode_start = _ext2_get_block_offset(dentry->fsdata.sb, dentry->fsdata.gt->table[holder_group].inode_table) + (pos_inside_group * INODE_LEN);
     _ext2_read_from_dev(dentry->dev, (uint8_t*)dentry->inode, inode_start, INODE_LEN);
     return 0;
 }
References _ext2_get_block_offset(), _ext2_read_from_dev(), dentry::dev, dentry::fsdata, fsdata_t::gt, dentry::inode, dentry::inode_indx, INODE_LEN, group_desc_t::inode_table, superblock_t::inodes_per_group, fsdata_t::sb, and groups_info_t::table.
Referenced by _ext2_driver_info().
ext2_recognize_drive()
bool ext2_recognize_drive (vfs_device_t * dev)
Definition at line 1032 of file ext2.c.
 {
     superblock_t* superblock = (superblock_t*)kmalloc(SUPERBLOCK_LEN);
     _ext2_read_from_dev(dev, (uint8_t*)superblock, SUPERBLOCK_START, SUPERBLOCK_LEN);
     if (superblock->magic != 0xEF53) {
         kfree(superblock);
         return false;
     }
     if (superblock->rev_level != 0) {
         kfree(superblock);
         return false;
     }
     kfree(superblock);
     return true;
 }
References _ext2_read_from_dev(), kfree(), kmalloc(), superblock_t::magic, superblock_t::rev_level, superblock, SUPERBLOCK_LEN, and SUPERBLOCK_START.
Referenced by _ext2_driver_info().
ext2_rm()
int ext2_rm (dentry_t * dentry)
Definition at line 1015 of file ext2.c.
 {
     dentry_t* parent_dir = dentry_get_parent(dentry);
     if (!parent_dir) {
         return -EPERM;
     }
     if (_ext2_rm_child(parent_dir, dentry) < 0) {
         return -EFAULT;
     }
     log("free from ext2");
     return 0;
 }
References _ext2_rm_child(), dentry_get_parent(), EFAULT, EPERM, and log().
Referenced by _ext2_driver_info().
ext2_rmdir()
int ext2_rmdir (dentry_t * dir)
Definition at line 929 of file ext2.c.
 {
     dentry_t* parent_dir = dentry_get_parent(dir);
     if (!parent_dir) {
         return -EPERM;
     }
     if (_ext2_is_dir_empty(dir)) {
         if (_ext2_rm_child(parent_dir, dir) < 0) {
             return -EFAULT;
         }
         parent_dir->inode->links_count--;
         dir->inode->links_count--;
         return 0;
     }
     return -ENOTEMPTY;
 }
References _ext2_is_dir_empty(), _ext2_rm_child(), dentry_get_parent(), EFAULT, ENOTEMPTY, EPERM, dentry::inode, and inode_t::links_count.
Referenced by _ext2_driver_info().
ext2_save_state()
void ext2_save_state (vfs_device_t * dev)
Definition at line 1069 of file ext2.c.
 {
     if (!_ext2_superblocks[dev->dev->id]) {
         return;
     }
     superblock_t* superblock = _ext2_superblocks[dev->dev->id];
     // FIXME: for now we consider that we have at max 5 groups
     uint32_t group_table_len = _ext2_group_table_info[dev->dev->id].count * GROUP_LEN;
     group_desc_t* group_table = _ext2_group_table_info[dev->dev->id].table;
     _ext2_write_to_dev(dev, (uint8_t*)group_table, _ext2_get_block_offset(superblock, 2), group_table_len);
     kfree(group_table);
     _ext2_write_to_dev(dev, (uint8_t*)superblock, SUPERBLOCK_START, SUPERBLOCK_LEN);
     kfree(superblock);
 }
References _ext2_get_block_offset(), _ext2_group_table_info, _ext2_superblocks, _ext2_write_to_dev(), groups_info_t::count, vfs_device_t::dev, GROUP_LEN, device_t::id, kfree(), superblock, SUPERBLOCK_LEN, SUPERBLOCK_START, and groups_info_t::table.
Referenced by _ext2_driver_info().
ext2_truncate()
int ext2_truncate (dentry_t * dentry, uint32_t len)
Definition at line 872 of file ext2.c.
 {
     if (dentry->inode->size <= len) {
         return 0;
     }
     const uint32_t block_len = BLOCK_LEN(dentry->fsdata.sb);
     const uint32_t last_written_byte = len - 1;
     uint32_t last_written_block_index = last_written_byte / block_len;
     uint32_t start_block_index = last_written_block_index + 1;
     uint32_t blocks_allocated = TO_EXT_BLOCKS_CNT(dentry->fsdata.sb, dentry->inode->blocks);
     for (uint32_t block_index, virt_block_index = start_block_index; virt_block_index < blocks_allocated; virt_block_index++) {
         block_index = _ext2_get_block_of_inode(dentry, virt_block_index);
         _ext2_free_block_index(dentry->dev, dentry->fsdata, block_index);
     }
     dentry->inode->size = len;
     dentry->inode->mtime = (uint32_t)timeman_now();
     dentry_set_flag(dentry, DENTRY_DIRTY);
     return 0;
 }
References _ext2_free_block_index(), _ext2_get_block_of_inode(), BLOCK_LEN, inode_t::blocks, DENTRY_DIRTY, dentry_set_flag(), dentry::dev, dentry::fsdata, dentry::inode, inode_t::mtime, fsdata_t::sb, inode_t::size, timeman_now(), and TO_EXT_BLOCKS_CNT.
Referenced by _ext2_driver_info().
ext2_write()
int ext2_write (dentry_t * dentry, uint8_t * buf, uint32_t start, uint32_t len)
Definition at line 838 of file ext2.c.
 {
     const uint32_t block_len = BLOCK_LEN(dentry->fsdata.sb);
     uint32_t start_block_index = start / block_len;
     uint32_t end_block_index = (start + len) / block_len;
     uint32_t write_offset = start % block_len;
     uint32_t to_write = len;
     uint32_t already_written = 0;
     uint32_t blocks_allocated = TO_EXT_BLOCKS_CNT(dentry->fsdata.sb, dentry->inode->blocks);
     for (uint32_t data_block_index, virt_block_index = start_block_index; virt_block_index <= end_block_index; virt_block_index++) {
         uint32_t write_to_block = MIN(to_write, block_len - write_offset);
         if (blocks_allocated <= virt_block_index) {
             _ext2_allocate_block_for_inode(dentry, 0, &data_block_index);
         } else {
             data_block_index = _ext2_get_block_of_inode(dentry, virt_block_index);
         }
         _ext2_write_to_dev(dentry->dev, buf + already_written, _ext2_get_block_offset(dentry->fsdata.sb, data_block_index) + write_offset, write_to_block);
         to_write -= write_to_block;
         already_written += write_to_block;
         write_offset = 0;
     }
     if (dentry->inode->size < start + len) {
         dentry->inode->size = start + len;
     }
     dentry->inode->mtime = (uint32_t)timeman_now();
     dentry_set_flag(dentry, DENTRY_DIRTY);
     return already_written;
 }
References _ext2_allocate_block_for_inode(), _ext2_get_block_of_inode(), _ext2_get_block_offset(), _ext2_write_to_dev(), BLOCK_LEN, inode_t::blocks, buf, DENTRY_DIRTY, dentry_set_flag(), dentry::dev, dentry::fsdata, dentry::inode, MIN, inode_t::mtime, fsdata_t::sb, inode_t::size, timeman_now(), and TO_EXT_BLOCKS_CNT.
Referenced by _ext2_driver_info().
ext2_write_inode()
int ext2_write_inode (dentry_t * dentry)
Definition at line 367 of file ext2.c.
 {
     uint32_t inodes_per_group = dentry->fsdata.sb->inodes_per_group;
     uint32_t holder_group = (dentry->inode_indx - 1) / inodes_per_group;
     uint32_t pos_inside_group = (dentry->inode_indx - 1) % inodes_per_group;
     uint32_t inode_start = _ext2_get_block_offset(dentry->fsdata.sb, dentry->fsdata.gt->table[holder_group].inode_table) + (pos_inside_group * INODE_LEN);
     _ext2_write_to_dev(dentry->dev, (uint8_t*)dentry->inode, inode_start, INODE_LEN);
     return 0;
 }
References _ext2_get_block_offset(), _ext2_write_to_dev(), dentry::dev, dentry::fsdata, fsdata_t::gt, dentry::inode, dentry::inode_indx, INODE_LEN, group_desc_t::inode_table, superblock_t::inodes_per_group, fsdata_t::sb, and groups_info_t::table.
Referenced by _ext2_driver_info().
get_fsdata()
fsdata_t get_fsdata (dentry_t * dentry)
Definition at line 1087 of file ext2.c.
 {
     fsdata_t fsdata;
     fsdata.sb = _ext2_superblocks[dentry->dev_indx];
     fsdata.gt = &_ext2_group_table_info[dentry->dev_indx];
     return fsdata;
 }
References _ext2_group_table_info, _ext2_superblocks, dentry::dev_indx, fsdata_t::gt, and fsdata_t::sb.
Referenced by _ext2_driver_info().
Variable Documentation
_ext2_group_table_info
groups_info_t _ext2_group_table_info[MAX_DEVICES_COUNT] static
Definition at line 26 of file ext2.c.
Referenced by ext2_prepare_fs(), ext2_save_state(), and get_fsdata().
_ext2_superblocks
superblock_t* _ext2_superblocks[MAX_DEVICES_COUNT] static
Definition at line 25 of file ext2.c.
Referenced by ext2_prepare_fs(), ext2_save_state(), and get_fsdata().