oneOS: include/fs/ext2/ext2.h File Reference
ext2.h File Reference
#include <types.h>
Data Structures
struct superblock_t
struct group_desc_t
struct inode_t
struct dir_entry_t
Macros
#define SUPERBLOCK_START 1024
#define SUPERBLOCK_LEN (sizeof(superblock_t))
#define GROUP_LEN (sizeof(group_desc_t))
#define S_IFSOCK 0xC000
#define S_IFLNK 0xA000
#define S_IFREG 0x8000
#define S_IFBLK 0x6000
#define S_IFDIR 0x4000
#define S_IFCHR 0x2000
#define S_IFIFO 0x1000
#define S_ISUID 0x0800
#define S_ISGID 0x0400
#define S_ISVTX 0x0200
#define S_IRUSR 0x0100
#define S_IWUSR 0x0080
#define S_IXUSR 0x0040
#define S_IRGRP 0x0020
#define S_IWGRP 0x0010
#define S_IXGRP 0x0008
#define S_IROTH 0x0004
#define S_IWOTH 0x0002
#define S_IXOTH 0x0001
#define INODE_LEN (sizeof(inode_t))
#define INODES_RESERVED 11
#define DIR_ENTRY_LEN (sizeof(dir_entry_t))
Typedefs
typedef uint16_t mode_t
Functions
void ext2_install ()
Macro Definition Documentation
DIR_ENTRY_LEN
#define DIR_ENTRY_LEN (sizeof(dir_entry_t))
Definition at line 112 of file ext2.h.
GROUP_LEN
#define GROUP_LEN (sizeof(group_desc_t))
Definition at line 53 of file ext2.h.
INODE_LEN
#define INODE_LEN (sizeof(inode_t))
Definition at line 89 of file ext2.h.
INODES_RESERVED
#define INODES_RESERVED 11
Definition at line 90 of file ext2.h.
S_IFBLK
#define S_IFBLK 0x6000
Definition at line 68 of file ext2.h.
S_IFCHR
#define S_IFCHR 0x2000
Definition at line 70 of file ext2.h.
S_IFDIR
#define S_IFDIR 0x4000
Definition at line 69 of file ext2.h.
S_IFIFO
#define S_IFIFO 0x1000
Definition at line 71 of file ext2.h.
S_IFLNK
#define S_IFLNK 0xA000
Definition at line 66 of file ext2.h.
S_IFREG
#define S_IFREG 0x8000
Definition at line 67 of file ext2.h.
S_IFSOCK
#define S_IFSOCK 0xC000
Definition at line 65 of file ext2.h.
S_IRGRP
#define S_IRGRP 0x0020
Definition at line 80 of file ext2.h.
S_IROTH
#define S_IROTH 0x0004
Definition at line 83 of file ext2.h.
S_IRUSR
#define S_IRUSR 0x0100
Definition at line 77 of file ext2.h.
S_ISGID
#define S_ISGID 0x0400
Definition at line 74 of file ext2.h.
S_ISUID
#define S_ISUID 0x0800
Definition at line 73 of file ext2.h.
S_ISVTX
#define S_ISVTX 0x0200
Definition at line 75 of file ext2.h.
S_IWGRP
#define S_IWGRP 0x0010
Definition at line 81 of file ext2.h.
S_IWOTH
#define S_IWOTH 0x0002
Definition at line 84 of file ext2.h.
S_IWUSR
#define S_IWUSR 0x0080
Definition at line 78 of file ext2.h.
S_IXGRP
#define S_IXGRP 0x0008
Definition at line 82 of file ext2.h.
S_IXOTH
#define S_IXOTH 0x0001
Definition at line 85 of file ext2.h.
S_IXUSR
#define S_IXUSR 0x0040
Definition at line 79 of file ext2.h.
SUPERBLOCK_LEN
#define SUPERBLOCK_LEN (sizeof(superblock_t))
Definition at line 7 of file ext2.h.
SUPERBLOCK_START
#define SUPERBLOCK_START 1024
Definition at line 6 of file ext2.h.
Typedef Documentation
mode_t
typedef uint16_t mode_t
Definition at line 87 of file ext2.h.
Function Documentation
ext2_install()
void ext2_install ()
Definition at line 1135 of file ext2.c.
 {
     driver_install(_ext2_driver_info());
 }
References _ext2_driver_info(), and driver_install().
Referenced by stage3().