oneOS: userland/edit/file.c File Reference
file.c File Reference
#include "file.h"
#include "viewer.h"
#include <unistd.h>
#include <stdlib.h>
#include <fcntl.h>
#include <string.h>
Functions
static int _file_get_size_of_first_line ()
static void _file_find_start (uint32_t old_offset)
static int _file_remaining_size ()
static int _file_is_last_line_in_buf ()
int _file_buf_flush ()
int _file_buf_reload (int offset_in_file)
int file_line_len (int offset)
int file_line_len_backwards (int offset)
int file_open (char *path)
void file_exit ()
int file_paste_char (char c, int offset)
int file_save ()
int file_scroll_up ()
int file_scroll_down ()
Variables
file_view_area_t view_area
Function Documentation
_file_buf_flush()
int _file_buf_flush ()
Definition at line 51 of file file.c.
 {
     /* FIXME: for now we think that we have all file in our buffer */
     lseek(view_area.fd, view_area.offset, SEEK_SET);
     view_area.data_len = write(view_area.fd, view_area.buffer, view_area.data_len);
     return 0;
 }
References file_view_area::buffer, file_view_area::data_len, file_view_area::fd, lseek(), file_view_area::offset, SEEK_SET, view_area, and write().
Referenced by file_save().
_file_buf_reload()
int _file_buf_reload (int offset_in_file)
Definition at line 59 of file file.c.
 {
     /* TODO: Get real file size */
     view_area.buf_len = 4000;
     view_area.buffer = (char*)malloc(view_area.buf_len);
     view_area.start = 0;
     view_area.offset = offset_in_file;
     view_area.was_changed = 0;
     lseek(view_area.fd, view_area.offset, SEEK_SET);
     view_area.data_len = read(view_area.fd, view_area.buffer, view_area.buf_len);
     if (view_area.data_len < 0) {
         return -1;
     }
     return 0;
 }
References file_view_area::buf_len, file_view_area::buffer, file_view_area::data_len, file_view_area::fd, lseek(), malloc(), file_view_area::offset, read(), SEEK_SET, file_view_area::start, view_area, and file_view_area::was_changed.
Referenced by file_open(), file_scroll_down(), and file_scroll_up().
_file_find_start()
static void _file_find_start (uint32_t old_offset) static
Definition at line 28 of file file.c.
 {
     old_offset -= 2;
     while (old_offset > view_area.offset) {
         if (view_area.buffer[old_offset - view_area.offset] == '\n') {
             view_area.start = old_offset - view_area.offset + 1;
             return;
         }
         old_offset--;
     }
     view_area.start = 0;
 }
References file_view_area::buffer, file_view_area::offset, file_view_area::start, and view_area.
Referenced by file_scroll_up().
_file_get_size_of_first_line()
static int _file_get_size_of_first_line () static
Definition at line 16 of file file.c.
 {
     int res = 0;
     for (int i = view_area.start; i < view_area.data_len; i++) {
         res++;
         if (view_area.buffer[i] == '\n') {
             return res;
         }
     }
     return view_area.data_len - view_area.start;
 }
References file_view_area::buffer, file_view_area::data_len, file_view_area::start, and view_area.
Referenced by file_scroll_down().
_file_is_last_line_in_buf()
static int _file_is_last_line_in_buf () inline static
Definition at line 46 of file file.c.
 {
     return 1;
 }
Referenced by file_scroll_down().
_file_remaining_size()
static int _file_remaining_size () inline static
Definition at line 41 of file file.c.
 {
     return view_area.data_len - view_area.start;
 }
References file_view_area::data_len, file_view_area::start, and view_area.
Referenced by file_open(), file_paste_char(), file_scroll_down(), and file_scroll_up().
file_exit()
void file_exit ()
Definition at line 118 of file file.c.
 {
     close(view_area.fd);
 }
References close(), file_view_area::fd, and view_area.
file_line_len()
int file_line_len (int offset)
Definition at line 76 of file file.c.
 {
     int res = 0;
     for (int i = offset; i < view_area.data_len; i++) {
         res++;
         if (view_area.buffer[i] == '\n') {
             return res;
         }
     }
     return view_area.data_len - view_area.start;
 }
References file_view_area::buffer, file_view_area::data_len, file_view_area::start, and view_area.
Referenced by viewer_cursor_down().
file_line_len_backwards()
int file_line_len_backwards (int offset)
Definition at line 88 of file file.c.
 {
     int res = 1;
     for (int i = offset - 1; i >= view_area.offset; i--) {
         if (view_area.buffer[i] == '\n') {
             return res;
         }
         res++;
     }
     return offset;
 }
References file_view_area::buffer, file_view_area::offset, and view_area.
Referenced by viewer_cursor_up().
file_open()
int file_open (char * path)
Definition at line 101 of file file.c.
 {
     int n;
     if ((view_area.fd = open(path, O_RDWR)) < 0) {
         return;
     }
     _file_buf_reload(0);
     if (view_area.data_len < 0) {
         return -1;
     }
     viewer_display(view_area.buffer, view_area.start, _file_remaining_size());
     return view_area.fd;
 }
References _file_buf_reload(), _file_remaining_size(), file_view_area::buffer, file_view_area::data_len, file_view_area::fd, O_RDWR, open(), file_view_area::start, view_area, and viewer_display().
Referenced by display_file().
file_paste_char()
int file_paste_char (char c, int offset)
file_paste_char pastes and flush updates to disk.
Definition at line 126 of file file.c.
 {
     view_area.was_changed = 1;
     view_area.data_len++;
     memmove(view_area.buffer + offset + 1, view_area.buffer + offset, view_area.data_len - offset - 1);
     view_area.buffer[offset] = c;
     viewer_cursor_next();
     viewer_display(view_area.buffer, view_area.start, _file_remaining_size());
 }
References _file_remaining_size(), file_view_area::buffer, file_view_area::data_len, memmove(), file_view_area::start, view_area, viewer_cursor_next(), viewer_display(), and file_view_area::was_changed.
Referenced by viewing_accept_key().
file_save()
int file_save ()
file_paste_char pastes and flush updates to disk.
Definition at line 140 of file file.c.
 {
     if (view_area.was_changed) {
         _file_buf_flush();
     }
 }
References _file_buf_flush(), view_area, and file_view_area::was_changed.
Referenced by menu_run_cmd().
file_scroll_down()
int file_scroll_down ()
Definition at line 173 of file file.c.
 {
     int line_size = _file_get_size_of_first_line();
     view_area.start += line_size;
     if (!_file_is_last_line_in_buf()) {
         _file_buf_reload(view_area.offset + view_area.start);
     }
     viewer_display(view_area.buffer, view_area.start, _file_remaining_size());
     view_area.line++;
 }
References _file_buf_reload(), _file_get_size_of_first_line(), _file_is_last_line_in_buf(), _file_remaining_size(), file_view_area::buffer, file_view_area::line, file_view_area::offset, file_view_area::start, view_area, and viewer_display().
Referenced by viewer_cursor_down().
file_scroll_up()
int file_scroll_up ()
Scroll functions update file buffer, to contain line scrolled to.
Definition at line 150 of file file.c.
 {
     if (view_area.line == 0 || view_area.start == 0) {
         return;
     }
     view_area.line--;
     int old_offset_in_file = view_area.offset + view_area.start;
     int offset_in_file = view_area.offset + view_area.start - SCREEN_X;
     if (offset_in_file < 0) {
         offset_in_file = 0;
     }
     if (offset_in_file >= view_area.offset) {
         view_area.start = offset_in_file - view_area.offset;
         _file_find_start(old_offset_in_file);
         viewer_display(view_area.buffer, view_area.start, _file_remaining_size());
     } else {
         _file_buf_reload(offset_in_file);
         _file_find_start(old_offset_in_file);
         viewer_display(view_area.buffer, view_area.start, _file_remaining_size());
     }
 }
References _file_buf_reload(), _file_find_start(), _file_remaining_size(), file_view_area::buffer, file_view_area::line, file_view_area::offset, SCREEN_X, file_view_area::start, view_area, and viewer_display().
Referenced by viewer_cursor_up().
Variable Documentation
view_area
file_view_area_t view_area
Definition at line 14 of file file.c.
Referenced by _file_buf_flush(), _file_buf_reload(), _file_find_start(), _file_get_size_of_first_line(), _file_remaining_size(), file_exit(), file_line_len(), file_line_len_backwards(), file_open(), file_paste_char(), file_save(), file_scroll_down(), and file_scroll_up().