oneOS: include/drivers/x86/fpu.h File Reference
fpu.h File Reference
#include <types.h>
Data Structures
struct __attribute__
Functions
void fpu_handler ()
void fpu_init ()
void fpu_reset_state (fpu_state_t *new_fpu_state)
void fpu_save (fpu_state_t *fpu_state)
void fpu_restore (fpu_state_t *fpu_state)
Function Documentation
fpu_handler()
void fpu_handler ()
Definition at line 29 of file fpu.c.
 {
     asm volatile("clts");
 }
Referenced by fpu_init().
fpu_init()
void fpu_init ()
Definition at line 34 of file fpu.c.
 {
     fpu_setup();
     asm volatile("fninit");
     asm volatile("fxsave %0"
                  : "=m"(fpu_state));
     set_irq_handler(IRQ7, fpu_handler);
 }
References fpu_handler(), fpu_setup(), fpu_state, IRQ7, and set_irq_handler().
Referenced by stage3().
fpu_reset_state()
void fpu_reset_state (fpu_state_t * new_fpu_state)
Definition at line 43 of file fpu.c.
 {
     memcpy((uint8_t*)new_fpu_state, (uint8_t*)&fpu_state, sizeof(fpu_state_t));
 }
References fpu_state, and memcpy().
Referenced by _thread_setup_kstack(), and tasking_exec().
fpu_restore()
void fpu_restore (fpu_state_t * fpu_state) inline
Definition at line 28 of file fpu.h.
 {
     asm volatile("fxrstor %0"
                  :
                  : "m"(*fpu_state));
 }
Referenced by switchuvm().
fpu_save()
void fpu_save (fpu_state_t * fpu_state) inline
Definition at line 22 of file fpu.h.
 {
     asm volatile("fxsave %0"
                  : "=m"(*fpu_state));
 }
Referenced by switchuvm().