oneOS: src/kernel/platform/x86/gdt.c File Reference
gdt.c File Reference
#include <platform/x86/gdt.h>
#include <platform/x86/tasking/tss.h>
#include <mem/vmm/vmm.h>
#include <mem/kmalloc.h>
Functions
void lgdt (void *p, uint16_t size)
void gdt_setup ()
Variables
struct gdt_entry gdt [GDT_MAX_ENTRIES]
Function Documentation
gdt_setup()
void gdt_setup ()
Definition at line 16 of file gdt.c.
                  {
     gdt[SEG_KCODE] = SEG_PG(SEGF_X|SEGF_R, 0, 0xffffffff, 0);
     gdt[SEG_KDATA] = SEG_PG(SEGF_W, 0, 0xffffffff, 0);
     gdt[SEG_UCODE] = SEG_PG(SEGF_X|SEGF_R, 0, 0xffffffff, DPL_USER);
     gdt[SEG_UDATA] = SEG_PG(SEGF_W, 0, 0xffffffff, DPL_USER);
     lgdt(gdt, sizeof(gdt));
 }
References DPL_USER, gdt, lgdt(), SEG_KCODE, SEG_KDATA, SEG_PG, SEG_UCODE, SEG_UDATA, SEGF_R, SEGF_W, and SEGF_X.
Referenced by stage3().
lgdt()
void lgdt (void * p, uint16_t size)
Definition at line 8 of file gdt.c.
{
     volatile uint16_t pd[3];
     pd[0] = size-1;
     pd[1] = (uint32_t)p;
     pd[2] = (uint32_t)p >> 16;
     asm volatile("lgdt (%0)" : : "r" (pd));
 }
References p.
Referenced by gdt_setup().
Variable Documentation
gdt
struct gdt_entry gdt[GDT_MAX_ENTRIES]
Definition at line 1 of file gdt.c.
Referenced by gdt_setup(), switch_to_user_mode(), and switchuvm().