oneOS: src/kernel/drivers/x86/ide.c File Reference
ide.c File Reference
#include <drivers/x86/ide.h>
Functions
driver_desc_t _ide_driver_info ()
void ide_install ()
void ide_find_devices (device_t *t_device)
Function Documentation
_ide_driver_info()
driver_desc_t _ide_driver_info ()
Definition at line 9 of file ide.c.
{
     driver_desc_t ide_desc;
     ide_desc.type = DRIVER_BUS_CONTROLLER;
     ide_desc.auto_start = false;
     ide_desc.is_device_driver = true;
     ide_desc.is_device_needed = false;
     ide_desc.is_driver_needed = false;
     ide_desc.functions[DRIVER_NOTIFICATION] = 0;
     ide_desc.functions[DRIVER_BUS_CONTROLLER_FIND_DEVICE] = ide_find_devices;
     ide_desc.pci_serve_class = 0x01;
     ide_desc.pci_serve_subclass = 0x01;
     ide_desc.pci_serve_vendor_id = 0x00;
     ide_desc.pci_serve_device_id = 0x00;
     return ide_desc;
 }
References driver_desc_t::auto_start, DRIVER_BUS_CONTROLLER, DRIVER_BUS_CONTROLLER_FIND_DEVICE, DRIVER_NOTIFICATION, driver_desc_t::functions, ide_find_devices(), driver_desc_t::is_device_driver, driver_desc_t::is_device_needed, driver_desc_t::is_driver_needed, driver_desc_t::pci_serve_class, driver_desc_t::pci_serve_device_id, driver_desc_t::pci_serve_subclass, driver_desc_t::pci_serve_vendor_id, and driver_desc_t::type.
Referenced by ide_install().
ide_find_devices()
void ide_find_devices (device_t * t_device)
Definition at line 37 of file ide.c.
{
     const uint8_t DRIVES_COUNT = 2;
     uint32_t ask_ports[] = {0x1F0, 0x1F0};
     bool is_masters[] = {true, false};
     for (uint8_t i = 0; i < DRIVES_COUNT; i++) {
         ata_t new_drive;
         ata_init(&new_drive, ask_ports[i], is_masters[i]);
         if (ata_indentify(&new_drive)) {
             device_desc_t new_device;
             new_device.class_id = 0x01; // mark as storage
             new_device.subclass_id = 0x05; // mark as Ata drive
             new_device.interface_id = 0;
             new_device.revision_id = 0;
             new_device.port_base = ask_ports[i] | (1 << 31);
             new_device.interrupt = IRQ14;
             device_install(new_device);
         }
     }
 }
References ata_indentify(), ata_init(), device_desc_t::class_id, device_install(), device_desc_t::interface_id, device_desc_t::interrupt, IRQ14, device_desc_t::port_base, device_desc_t::revision_id, and device_desc_t::subclass_id.
Referenced by _ide_driver_info().
ide_install()
void ide_install ()
Definition at line 30 of file ide.c.
                    {
     driver_install(_ide_driver_info());
 }
References _ide_driver_info(), and driver_install().
Referenced by stage3().