oneOS: include/drivers/x86/ide.h File Reference
ide.h File Reference
#include <types.h>
#include <drivers/x86/ata.h>
#include <platform/x86/idt.h>
Functions
void ide_install ()
void ide_find_devices (device_t *t_device)
Function Documentation
ide_find_devices()
void ide_find_devices (device_t * t_device)
Definition at line 37 of file ide.c.
{
     const uint8_t DRIVES_COUNT = 2;
     uint32_t ask_ports[] = {0x1F0, 0x1F0};
     bool is_masters[] = {true, false};
     for (uint8_t i = 0; i < DRIVES_COUNT; i++) {
         ata_t new_drive;
         ata_init(&new_drive, ask_ports[i], is_masters[i]);
         if (ata_indentify(&new_drive)) {
             device_desc_t new_device;
             new_device.class_id = 0x01; // mark as storage
             new_device.subclass_id = 0x05; // mark as Ata drive
             new_device.interface_id = 0;
             new_device.revision_id = 0;
             new_device.port_base = ask_ports[i] | (1 << 31);
             new_device.interrupt = IRQ14;
             device_install(new_device);
         }
     }
 }
References ata_indentify(), ata_init(), device_desc_t::class_id, device_install(), device_desc_t::interface_id, device_desc_t::interrupt, IRQ14, device_desc_t::port_base, device_desc_t::revision_id, and device_desc_t::subclass_id.
Referenced by _ide_driver_info().
ide_install()
void ide_install ()
Definition at line 30 of file ide.c.
                    {
     driver_install(_ide_driver_info());
 }
References _ide_driver_info(), and driver_install().
Referenced by stage3().