oneOS: include/platform/x86/idt.h File Reference
idt.h File Reference
#include <platform/x86/pic.h>
#include <platform/x86/port.h>
#include <platform/x86/tasking/trapframe.h>
#include <types.h>
Data Structures
struct idt_entry
Macros
#define INIT_CODE_SEG 0x08
#define INIT_DATA_SEG 0x10
#define IDT_ENTRIES 0x100
#define IRQ_MASTER_OFFSET 32
#define IRQ_SLAVE_OFFSET 40
#define IRQ0 32
#define IRQ1 33
#define IRQ2 34
#define IRQ3 35
#define IRQ4 36
#define IRQ5 37
#define IRQ6 38
#define IRQ7 39
#define IRQ8 40
#define IRQ9 41
#define IRQ10 42
#define IRQ11 43
#define IRQ12 44
#define IRQ13 45
#define IRQ14 46
#define IRQ15 47
Functions
struct idt_entry __attribute__ ((packed))
void idt_element_setup (uint8_t n, void *handler_addr, bool user)
void idt_setup ()
void set_irq_handler (uint8_t interrupt_no, void(*handler)())
void init_irq_handlers ()
void isr0 ()
void isr1 ()
void isr2 ()
void isr3 ()
void isr4 ()
void isr5 ()
void isr6 ()
void isr7 ()
void isr8 ()
void isr9 ()
void isr10 ()
void isr11 ()
void isr12 ()
void isr13 ()
void isr14 ()
void isr15 ()
void isr16 ()
void isr17 ()
void isr18 ()
void isr19 ()
void isr20 ()
void isr21 ()
void isr22 ()
void isr23 ()
void isr24 ()
void isr25 ()
void isr26 ()
void isr27 ()
void isr28 ()
void isr29 ()
void isr30 ()
void isr31 ()
void irq0 ()
void irq1 ()
void irq2 ()
void irq3 ()
void irq4 ()
void irq5 ()
void irq6 ()
void irq7 ()
void irq8 ()
void irq9 ()
void irq10 ()
void irq11 ()
void irq12 ()
void irq13 ()
void irq14 ()
void irq15 ()
void irq_null ()
void irq_empty_handler ()
void syscall ()
Variables
uint16_t offset_lower
uint16_t segment
uint8_t zero
uint8_t type
uint16_t offset_upper
struct idt_entry idt [0x100]
void ** handlers [0x100]
Macro Definition Documentation
IDT_ENTRIES
#define IDT_ENTRIES 0x100
Definition at line 11 of file idt.h.
INIT_CODE_SEG
#define INIT_CODE_SEG 0x08
Definition at line 9 of file idt.h.
INIT_DATA_SEG
#define INIT_DATA_SEG 0x10
Definition at line 10 of file idt.h.
IRQ0
#define IRQ0 32
Definition at line 88 of file idt.h.
IRQ1
#define IRQ1 33
Definition at line 89 of file idt.h.
IRQ10
#define IRQ10 42
Definition at line 98 of file idt.h.
IRQ11
#define IRQ11 43
Definition at line 99 of file idt.h.
IRQ12
#define IRQ12 44
Definition at line 100 of file idt.h.
IRQ13
#define IRQ13 45
Definition at line 101 of file idt.h.
IRQ14
#define IRQ14 46
Definition at line 102 of file idt.h.
IRQ15
#define IRQ15 47
Definition at line 103 of file idt.h.
IRQ2
#define IRQ2 34
Definition at line 90 of file idt.h.
IRQ3
#define IRQ3 35
Definition at line 91 of file idt.h.
IRQ4
#define IRQ4 36
Definition at line 92 of file idt.h.
IRQ5
#define IRQ5 37
Definition at line 93 of file idt.h.
IRQ6
#define IRQ6 38
Definition at line 94 of file idt.h.
IRQ7
#define IRQ7 39
Definition at line 95 of file idt.h.
IRQ8
#define IRQ8 40
Definition at line 96 of file idt.h.
IRQ9
#define IRQ9 41
Definition at line 97 of file idt.h.
IRQ_MASTER_OFFSET
#define IRQ_MASTER_OFFSET 32
Definition at line 13 of file idt.h.
IRQ_SLAVE_OFFSET
#define IRQ_SLAVE_OFFSET 40
Definition at line 14 of file idt.h.
Function Documentation
__attribute__()
struct idt_entry __attribute__ ((packed))
idt_element_setup()
void idt_element_setup (uint8_t n, void * handler_addr, bool user) inline
Definition at line 96 of file idt.c.
{
     idt[n].offset_lower = (uint32_t)handler_addr & 0xffff;
     idt[n].segment = INIT_CODE_SEG;
     idt[n].zero = 0;
     idt[n].type = 0x8E;
     // setting user type
     // now user can call this sw interrupts (syscalls)
     if (is_user) {
         idt[n].type |= (0b1100000);
     }
     idt[n].offset_upper = (uint32_t)handler_addr >> 16;
 }
References idt, INIT_CODE_SEG, idt_entry::offset_lower, idt_entry::offset_upper, idt_entry::segment, idt_entry::type, and idt_entry::zero.
Referenced by idt_setup().
idt_setup()
void idt_setup ()
Definition at line 18 of file idt.c.
                  {
     idt_element_setup(0, (void*)isr0, SYS);
     idt_element_setup(1, (void*)isr1, SYS);
     idt_element_setup(2, (void*)isr2, SYS);
     idt_element_setup(3, (void*)isr3, SYS);
     idt_element_setup(4, (void*)isr4, SYS);
     idt_element_setup(5, (void*)isr5, SYS);
     idt_element_setup(6, (void*)isr6, SYS);
     idt_element_setup(7, (void*)isr7, SYS);
     idt_element_setup(8, (void*)isr8, SYS);
     idt_element_setup(9, (void*)isr9, SYS);
     idt_element_setup(10, (void*)isr10, SYS);
     idt_element_setup(11, (void*)isr11, SYS);
     idt_element_setup(12, (void*)isr12, SYS);
     idt_element_setup(13, (void*)isr13, SYS);
     idt_element_setup(14, (void*)isr14, SYS);
     idt_element_setup(15, (void*)isr15, SYS);
     idt_element_setup(16, (void*)isr16, SYS);
     idt_element_setup(17, (void*)isr17, SYS);
     idt_element_setup(18, (void*)isr18, SYS);
     idt_element_setup(19, (void*)isr19, SYS);
     idt_element_setup(20, (void*)isr20, SYS);
     idt_element_setup(21, (void*)isr21, SYS);
     idt_element_setup(22, (void*)isr22, SYS);
     idt_element_setup(23, (void*)isr23, SYS);
     idt_element_setup(24, (void*)isr24, SYS);
     idt_element_setup(25, (void*)isr25, SYS);
     idt_element_setup(26, (void*)isr26, SYS);
     idt_element_setup(27, (void*)isr27, SYS);
     idt_element_setup(28, (void*)isr28, SYS);
     idt_element_setup(29, (void*)isr29, SYS);
     idt_element_setup(30, (void*)isr30, SYS);
     idt_element_setup(31, (void*)isr31, SYS);
     pic_remap(IRQ_MASTER_OFFSET, IRQ_SLAVE_OFFSET);
     idt_element_setup(32, (void*)irq0, SYS);
     idt_element_setup(33, (void*)irq1, SYS);
     idt_element_setup(34, (void*)irq2, SYS);
     idt_element_setup(35, (void*)irq3, SYS);
     idt_element_setup(36, (void*)irq4, SYS);
     idt_element_setup(37, (void*)irq5, SYS);
     idt_element_setup(38, (void*)irq6, SYS);
     idt_element_setup(39, (void*)irq7, SYS);
     idt_element_setup(40, (void*)irq8, SYS);
     idt_element_setup(41, (void*)irq9, SYS);
     idt_element_setup(42, (void*)irq10, SYS);
     idt_element_setup(43, (void*)irq11, SYS);
     idt_element_setup(44, (void*)irq12, SYS);
     idt_element_setup(45, (void*)irq13, SYS);
     idt_element_setup(46, (void*)irq14, SYS);
     idt_element_setup(47, (void*)irq15, SYS);
     for (int i = 48; i < 256; i++) {
         idt_element_setup(i, (void*)syscall, SYS);
     }
     idt_element_setup(SYSCALL, (void*)syscall, USER);
     init_irq_handlers();
     lidt(idt, sizeof(idt));
     asm volatile("sti");
 }
References idt, idt_element_setup(), init_irq_handlers(), irq0(), irq1(), irq10(), irq11(), irq12(), irq13(), irq14(), irq15(), irq2(), irq3(), irq4(), irq5(), irq6(), irq7(), irq8(), irq9(), IRQ_MASTER_OFFSET, IRQ_SLAVE_OFFSET, isr0(), isr1(), isr10(), isr11(), isr12(), isr13(), isr14(), isr15(), isr16(), isr17(), isr18(), isr19(), isr2(), isr20(), isr21(), isr22(), isr23(), isr24(), isr25(), isr26(), isr27(), isr28(), isr29(), isr3(), isr30(), isr31(), isr4(), isr5(), isr6(), isr7(), isr8(), isr9(), lidt(), pic_remap(), SYS, syscall(), SYSCALL, and USER.
Referenced by stage3().
init_irq_handlers()
void init_irq_handlers () inline
Definition at line 86 of file idt.c.
{
     int i;
     for (i = IRQ_MASTER_OFFSET; i < IRQ_MASTER_OFFSET + 8; i++){
         handlers[i] = (void*)irq_empty_handler;
     }
     for (i = IRQ_SLAVE_OFFSET; i < IRQ_SLAVE_OFFSET + 8; i++){
         handlers[i] = (void*)irq_empty_handler;
     }
 }
References handlers, irq_empty_handler(), IRQ_MASTER_OFFSET, and IRQ_SLAVE_OFFSET.
Referenced by idt_setup().
irq0()
void irq0 ()
Referenced by idt_setup().
irq1()
void irq1 ()
Referenced by idt_setup().
irq10()
void irq10 ()
Referenced by idt_setup().
irq11()
void irq11 ()
Referenced by idt_setup().
irq12()
void irq12 ()
Referenced by idt_setup().
irq13()
void irq13 ()
Referenced by idt_setup().
irq14()
void irq14 ()
Referenced by idt_setup().
irq15()
void irq15 ()
Referenced by idt_setup().
irq2()
void irq2 ()
Referenced by idt_setup().
irq3()
void irq3 ()
Referenced by idt_setup().
irq4()
void irq4 ()
Referenced by idt_setup().
irq5()
void irq5 ()
Referenced by idt_setup().
irq6()
void irq6 ()
Referenced by idt_setup().
irq7()
void irq7 ()
Referenced by idt_setup().
irq8()
void irq8 ()
Referenced by idt_setup().
irq9()
void irq9 ()
Referenced by idt_setup().
irq_empty_handler()
void irq_empty_handler ()
Definition at line 29 of file irq_handler.c.
{
     return;
 }
Referenced by init_irq_handlers().
irq_null()
void irq_null ()
isr0()
void isr0 ()
Referenced by idt_setup().
isr1()
void isr1 ()
Referenced by idt_setup().
isr10()
void isr10 ()
Referenced by idt_setup().
isr11()
void isr11 ()
Referenced by idt_setup().
isr12()
void isr12 ()
Referenced by idt_setup().
isr13()
void isr13 ()
Referenced by idt_setup().
isr14()
void isr14 ()
Referenced by idt_setup().
isr15()
void isr15 ()
Referenced by idt_setup().
isr16()
void isr16 ()
Referenced by idt_setup().
isr17()
void isr17 ()
Referenced by idt_setup().
isr18()
void isr18 ()
Referenced by idt_setup().
isr19()
void isr19 ()
Referenced by idt_setup().
isr2()
void isr2 ()
Referenced by idt_setup().
isr20()
void isr20 ()
Referenced by idt_setup().
isr21()
void isr21 ()
Referenced by idt_setup().
isr22()
void isr22 ()
Referenced by idt_setup().
isr23()
void isr23 ()
Referenced by idt_setup().
isr24()
void isr24 ()
Referenced by idt_setup().
isr25()
void isr25 ()
Referenced by idt_setup().
isr26()
void isr26 ()
Referenced by idt_setup().
isr27()
void isr27 ()
Referenced by idt_setup().
isr28()
void isr28 ()
Referenced by idt_setup().
isr29()
void isr29 ()
Referenced by idt_setup().
isr3()
void isr3 ()
Referenced by idt_setup().
isr30()
void isr30 ()
Referenced by idt_setup().
isr31()
void isr31 ()
Referenced by idt_setup().
isr4()
void isr4 ()
Referenced by idt_setup().
isr5()
void isr5 ()
Referenced by idt_setup().
isr6()
void isr6 ()
Referenced by idt_setup().
isr7()
void isr7 ()
Referenced by idt_setup().
isr8()
void isr8 ()
Referenced by idt_setup().
isr9()
void isr9 ()
Referenced by idt_setup().
set_irq_handler()
void set_irq_handler (uint8_t interrupt_no, void(*)() handler)
Definition at line 82 of file idt.c.
{
     handlers[interrupt_no] = (void*)handler;
 }
References handlers.
Referenced by fpu_init(), kbdriver_run(), mouse_run(), and pit_setup().
syscall()
void syscall ()
Referenced by idt_setup().
Variable Documentation
handlers
void** handlers[0x100] extern
Definition at line 5 of file idt.c.
Referenced by devfs_register(), init_irq_handlers(), irq_redirect(), and set_irq_handler().
idt
struct idt_entry idt[0x100] extern
Definition at line 1 of file idt.c.
Referenced by idt_element_setup(), and idt_setup().
offset_lower
uint16_t offset_lower
Definition at line 0 of file idt.h.
offset_upper
uint16_t offset_upper
Definition at line 4 of file idt.h.
segment
uint16_t segment
Definition at line 1 of file idt.h.
type
uint8_t type
Definition at line 3 of file idt.h.
zero
uint8_t zero
Definition at line 2 of file idt.h.