oneOS: include/platform/x86/vmm/pte.h File Reference
pte.h File Reference
#include <types.h>
Macros
#define page_desc_t uint32_t
#define pte_t uint32_t
#define PAGE_DESC_FRAME_OFFSET 12
Enumerations
enum PAGE_DESC_PAGE_FLAGS {
PAGE_DESC_PRESENT = 0x1 , PAGE_DESC_WRITABLE = 0x2 , PAGE_DESC_USER = 0x4 , PAGE_DESC_WRITETHOUGH = 0x8 ,
PAGE_DESC_NOT_CACHEABLE = 0x10 , PAGE_DESC_ACCESSED = 0x20 , PAGE_DESC_DIRTY = 0x40 , PAGE_DESC_PAT = 0x80 ,
PAGE_DESC_CPU_GLOBAL = 0x100 , PAGE_DESC_LV4_GLOBAL = 0x200 , PAGE_DESC_COPY_ON_WRITE = 0x400 , PAGE_DESC_ZEROING_ON_DEMAND = 0x800 ,
PAGE_DESC_PRESENT = 0 , PAGE_DESC_WRITABLE , PAGE_DESC_USER , PAGE_DESC_WRITETHOUGH ,
PAGE_DESC_NOT_CACHEABLE , PAGE_DESC_ACCESSED , PAGE_DESC_DIRTY , PAGE_DESC_PAT ,
PAGE_DESC_CPU_GLOBAL , PAGE_DESC_LV4_GLOBAL , PAGE_DESC_COPY_ON_WRITE , PAGE_DESC_ZEROING_ON_DEMAND ,
PAGE_DESC_FRAME = 12
}
Functions
void page_desc_set_attrs (uint32_t *pte, uint32_t attrs)
void page_desc_del_attrs (uint32_t *pte, uint32_t attrs)
bool page_desc_has_attrs (uint32_t pte, uint32_t attr)
void page_desc_set_frame (uint32_t *pte, uint32_t frame)
void page_desc_del_frame (uint32_t *pte)
bool page_desc_is_present (uint32_t pte)
bool page_desc_is_writable (uint32_t pte)
bool page_desc_is_user (uint32_t pte)
bool page_desc_is_not_cacheable (uint32_t pte)
bool page_desc_is_cow (uint32_t pte)
uint32_t page_desc_get_frame (uint32_t pte)
uint32_t page_desc_get_settings (uint32_t pte)
uint32_t page_desc_get_settings_ignore_cow (uint32_t pte)
Macro Definition Documentation
PAGE_DESC_FRAME_OFFSET
#define PAGE_DESC_FRAME_OFFSET 12
Definition at line 17 of file pte.h.
page_desc_t
#define page_desc_t uint32_t
Definition at line 14 of file pte.h.
pte_t
#define pte_t uint32_t
Definition at line 15 of file pte.h.
Enumeration Type Documentation
PAGE_DESC_PAGE_FLAGS
enum PAGE_DESC_PAGE_FLAGS
Enumerator
PAGE_DESC_PRESENT
PAGE_DESC_WRITABLE
PAGE_DESC_USER
PAGE_DESC_WRITETHOUGH
PAGE_DESC_NOT_CACHEABLE
PAGE_DESC_ACCESSED
PAGE_DESC_DIRTY
PAGE_DESC_PAT
PAGE_DESC_CPU_GLOBAL
PAGE_DESC_LV4_GLOBAL
PAGE_DESC_COPY_ON_WRITE
PAGE_DESC_ZEROING_ON_DEMAND
PAGE_DESC_PRESENT
PAGE_DESC_WRITABLE
PAGE_DESC_USER
PAGE_DESC_WRITETHOUGH
PAGE_DESC_NOT_CACHEABLE
PAGE_DESC_ACCESSED
PAGE_DESC_DIRTY
PAGE_DESC_PAT
PAGE_DESC_CPU_GLOBAL
PAGE_DESC_LV4_GLOBAL
PAGE_DESC_COPY_ON_WRITE
PAGE_DESC_ZEROING_ON_DEMAND
PAGE_DESC_FRAME
Definition at line 19 of file pte.h.
{
     PAGE_DESC_PRESENT = 0x1,
     PAGE_DESC_WRITABLE = 0x2,
     PAGE_DESC_USER = 0x4,
     PAGE_DESC_WRITETHOUGH = 0x8,
     PAGE_DESC_NOT_CACHEABLE = 0x10,
     PAGE_DESC_ACCESSED = 0x20,
     PAGE_DESC_DIRTY = 0x40,
     PAGE_DESC_PAT = 0x80,
     PAGE_DESC_CPU_GLOBAL = 0x100,
     PAGE_DESC_LV4_GLOBAL = 0x200,
     PAGE_DESC_COPY_ON_WRITE = 0x400,
     PAGE_DESC_ZEROING_ON_DEMAND = 0x800
 };
Function Documentation
page_desc_del_attrs()
void page_desc_del_attrs (uint32_t * pte, uint32_t attrs)
Referenced by _vmm_resolve_zeroing_on_demand(), vmm_free_page(), vmm_test_pspace_vaddr_of_active_ptable(), vmm_tune_page(), and vmm_unmap_page().
page_desc_del_frame()
void page_desc_del_frame (uint32_t * pte)
Referenced by vmm_unmap_page().
page_desc_get_frame()
uint32_t page_desc_get_frame (uint32_t pte)
Referenced by _vmm_convert_vaddr2paddr(), _vmm_copy_page_to_resolve_cow(), _vmm_kernel_convert_vaddr2paddr(), vmm_copy_page(), and vmm_free_page().
page_desc_get_settings()
uint32_t page_desc_get_settings (uint32_t pte)
page_desc_get_settings_ignore_cow()
uint32_t page_desc_get_settings_ignore_cow (uint32_t pte)
Referenced by _vmm_copy_page_to_resolve_cow(), and vmm_copy_page().
page_desc_has_attrs()
bool page_desc_has_attrs (uint32_t pte, uint32_t attr)
Referenced by _vmm_is_zeroing_on_demand().
page_desc_is_cow()
bool page_desc_is_cow (uint32_t pte)
page_desc_is_not_cacheable()
bool page_desc_is_not_cacheable (uint32_t pte)
page_desc_is_present()
bool page_desc_is_present (uint32_t pte)
Referenced by vmm_copy_page(), and vmm_tune_page().
page_desc_is_user()
bool page_desc_is_user (uint32_t pte)
page_desc_is_writable()
bool page_desc_is_writable (uint32_t pte)
page_desc_set_attrs()
void page_desc_set_attrs (uint32_t * pte, uint32_t attrs)
Referenced by _vmm_pspace_gen(), _vmm_pspace_init(), _vmm_resolve_zeroing_on_demand(), vmm_alloc_page(), vmm_map_page(), and vmm_tune_page().
page_desc_set_frame()
void page_desc_set_frame (uint32_t * pte, uint32_t frame)
Referenced by _vmm_pspace_gen(), _vmm_pspace_init(), vmm_alloc_page(), and vmm_map_page().