oneOS: include/platform/x86/vmm/pde.h File Reference
pde.h File Reference
#include <types.h>
Macros
#define table_desc_t uint32_t
#define pde_t uint32_t
#define TABLE_DESC_FRAME_OFFSET 12
Enumerations
enum TABLE_DESC_PAGE_FLAGS {
TABLE_DESC_PRESENT = 0x1 , TABLE_DESC_WRITABLE = 0x2 , TABLE_DESC_USER = 0x4 , TABLE_DESC_PWT = 0x8 ,
TABLE_DESC_PCD = 0x10 , TABLE_DESC_ACCESSED = 0x20 , TABLE_DESC_DIRTY = 0x40 , TABLE_DESC_4MB = 0x80 ,
TABLE_DESC_CPU_GLOBAL = 0x100 , TABLE_DESC_LV4_GLOBAL = 0x200 , TABLE_DESC_COPY_ON_WRITE = 0x400 , TABLE_DESC_ZEROING_ON_DEMAND = 0x800 ,
TABLE_DESC_PRESENT = 0 , TABLE_DESC_WRITABLE , TABLE_DESC_USER , TABLE_DESC_PWT ,
TABLE_DESC_PCD , TABLE_DESC_ACCESSED , TABLE_DESC_DIRTY , TABLE_DESC_4MB ,
TABLE_DESC_CPU_GLOBAL , TABLE_DESC_LV4_GLOBAL , TABLE_DESC_COPY_ON_WRITE , TABLE_DESC_ZEROING_ON_DEMAND ,
TABLE_DESC_FRAME = 12
}
Functions
void table_desc_clear (uint32_t *pde)
void table_desc_set_attrs (uint32_t *pde, uint32_t attrs)
void table_desc_del_attrs (uint32_t *pde, uint32_t attrs)
bool table_desc_has_attrs (uint32_t pde, uint32_t attrs)
void table_desc_set_frame (uint32_t *pde, uint32_t frame)
void table_desc_del_frame (uint32_t *pde)
bool table_desc_is_present (uint32_t pde)
bool table_desc_is_writable (uint32_t pde)
bool table_desc_is_4mb (uint32_t pde)
bool table_desc_is_copy_on_write (uint32_t pde)
uint32_t table_desc_get_frame (uint32_t pde)
Macro Definition Documentation
pde_t
#define pde_t uint32_t
Definition at line 15 of file pde.h.
TABLE_DESC_FRAME_OFFSET
#define TABLE_DESC_FRAME_OFFSET 12
Definition at line 17 of file pde.h.
table_desc_t
#define table_desc_t uint32_t
Definition at line 14 of file pde.h.
Enumeration Type Documentation
TABLE_DESC_PAGE_FLAGS
enum TABLE_DESC_PAGE_FLAGS
Enumerator
TABLE_DESC_PRESENT
TABLE_DESC_WRITABLE
TABLE_DESC_USER
TABLE_DESC_PWT
TABLE_DESC_PCD
TABLE_DESC_ACCESSED
TABLE_DESC_DIRTY
TABLE_DESC_4MB
TABLE_DESC_CPU_GLOBAL
TABLE_DESC_LV4_GLOBAL
TABLE_DESC_COPY_ON_WRITE
TABLE_DESC_ZEROING_ON_DEMAND
TABLE_DESC_PRESENT
TABLE_DESC_WRITABLE
TABLE_DESC_USER
TABLE_DESC_PWT
TABLE_DESC_PCD
TABLE_DESC_ACCESSED
TABLE_DESC_DIRTY
TABLE_DESC_4MB
TABLE_DESC_CPU_GLOBAL
TABLE_DESC_LV4_GLOBAL
TABLE_DESC_COPY_ON_WRITE
TABLE_DESC_ZEROING_ON_DEMAND
TABLE_DESC_FRAME
Definition at line 19 of file pde.h.
{
     TABLE_DESC_PRESENT = 0x1,
     TABLE_DESC_WRITABLE = 0x2,
     TABLE_DESC_USER = 0x4,
     TABLE_DESC_PWT = 0x8,
     TABLE_DESC_PCD = 0x10,
     TABLE_DESC_ACCESSED = 0x20,
     TABLE_DESC_DIRTY = 0x40,
     TABLE_DESC_4MB = 0x80,
     TABLE_DESC_CPU_GLOBAL = 0x100,
     TABLE_DESC_LV4_GLOBAL = 0x200,
     TABLE_DESC_COPY_ON_WRITE = 0x400,
     TABLE_DESC_ZEROING_ON_DEMAND = 0x800
 };
Function Documentation
table_desc_clear()
void table_desc_clear (uint32_t * pde)
Referenced by vmm_allocate_ptable().
table_desc_del_attrs()
void table_desc_del_attrs (uint32_t * pde, uint32_t attrs)
Referenced by _vmm_resolve_zeroing_on_demand(), vmm_new_forked_user_pdir(), and vmm_zero_user_pages().
table_desc_del_frame()
void table_desc_del_frame (uint32_t * pde)
Referenced by _vmm_free_pspace(), and vmm_free_ptable().
table_desc_get_frame()
uint32_t table_desc_get_frame (uint32_t pde)
Referenced by _vmm_free_pspace(), and vmm_free_ptable().
table_desc_has_attrs()
bool table_desc_has_attrs (uint32_t pde, uint32_t attrs)
Referenced by _vmm_free_pspace(), _vmm_is_zeroing_on_demand(), _vmm_resolve_zeroing_on_demand(), vmm_free_ptable(), and vmm_new_forked_user_pdir().
table_desc_is_4mb()
bool table_desc_is_4mb (uint32_t pde)
table_desc_is_copy_on_write()
bool table_desc_is_copy_on_write (uint32_t pde)
Referenced by _vmm_is_copy_on_write().
table_desc_is_present()
bool table_desc_is_present (uint32_t pde)
Referenced by _vmm_pspace_init(), vmm_map_page(), and vmm_unmap_page().
table_desc_is_writable()
bool table_desc_is_writable (uint32_t pde)
table_desc_set_attrs()
void table_desc_set_attrs (uint32_t * pde, uint32_t attrs)
Referenced by _vmm_create_kernel_ptables(), _vmm_pspace_gen(), vmm_allocate_ptable(), vmm_new_forked_user_pdir(), and vmm_zero_user_pages().
table_desc_set_frame()
void table_desc_set_frame (uint32_t * pde, uint32_t frame)
Referenced by _vmm_create_kernel_ptables(), _vmm_pspace_gen(), and vmm_allocate_ptable().