oneOS: include/drivers/x86/ata.h File Reference
ata.h File Reference
#include <types.h>
#include <platform/x86/port.h>
#include <drivers/x86/display.h>
#include <mem/kmalloc.h>
#include <drivers/driver_manager.h>
Data Structures
struct ata_ports_t
struct ata_t
Functions
void ata_add_new_device (device_t *t_new_device)
void ata_install ()
void ata_init (ata_t *ata, uint32_t port, bool is_master)
bool ata_indentify (ata_t *ata)
Variables
ata_t _ata_drives [MAX_DEVICES_COUNT]
Function Documentation
ata_add_new_device()
void ata_add_new_device (device_t * t_new_device)
Definition at line 61 of file ata.c.
 {
     bool is_master = new_device->device_desc.port_base >> 31;
     uint16_t port = new_device->device_desc.port_base & 0xFFF;
     ata_init(&_ata_drives[new_device->id], port, is_master);
     if (ata_indentify(&_ata_drives[new_device->id])) {
         kprintf("Device added to ata driver\n");
     }
 }
References _ata_drives, ata_indentify(), ata_init(), device_t::device_desc, device_t::id, kprintf(), and device_desc_t::port_base.
Referenced by _ata_driver_info().
ata_indentify()
bool ata_indentify (ata_t * ata)
Definition at line 91 of file ata.c.
 {
     port_8bit_out(ata->port.device, ata->is_master ? 0xA0 : 0xB0);
     port_8bit_out(ata->port.sector_count, 0);
     port_8bit_out(ata->port.lba_lo, 0);
     port_8bit_out(ata->port.lba_mid, 0);
     port_8bit_out(ata->port.lba_hi, 0);
     port_8bit_out(ata->port.command, 0xEC);
     // check the acceptance of a command
     uint8_t status = port_8bit_in(ata->port.command);
     if (status == 0x00) {
         kprintf("Cmd isn't accepted");
         return false;
     }
     // waiting for processing
     // while BSY is on
     while ((status & 0x80) == 0x80) {
         status = port_8bit_in(ata->port.command);
     }
     // check if drive isn't ready to transer DRQ
     if ((status & 0x08) != 0x08) {
         kprintf("Doesn't ready to transfer DRQ");
         return false;
     }
     // transfering 256 bytes of data
     for (int i = 0; i < 256; i++) {
         uint16_t data = port_16bit_in(ata->port.data);
         if (i == 1) {
             ata->cylindres = data;
         }
         if (i == 3) {
             ata->heads = data;
         }
         if (i == 6) {
             ata->sectors = data;
         }
         if (i == 49) {
             if ((data >> 8) & 0x1 == 1) {
                 ata->dma = true;
             }
             if ((data >> 9) & 0x1 == 1) {
                 ata->lba = true;
             }
         }
         if (i == 60) {
             ata->capacity = data;
         }
         if (i == 61) {
             ata->capacity |= ((uint32_t)data) << 16;
         }
     }
     return true;
 }
References ata_t::capacity, ata_ports_t::command, ata_t::cylindres, ata_ports_t::data, ata_ports_t::device, ata_t::dma, ata_t::heads, ata_t::is_master, kprintf(), ata_t::lba, ata_ports_t::lba_hi, ata_ports_t::lba_lo, ata_ports_t::lba_mid, ata_t::port, port_16bit_in(), port_8bit_in(), port_8bit_out(), ata_ports_t::sector_count, and ata_t::sectors.
Referenced by ata_add_new_device(), and ide_find_devices().
ata_init()
void ata_init (ata_t * ata, uint32_t port, bool is_master)
Definition at line 77 of file ata.c.
 {
     ata->is_master = is_master;
     ata->port.data = port;
     ata->port.error = port + 0x1;
     ata->port.sector_count = port + 0x2;
     ata->port.lba_lo = port + 0x3;
     ata->port.lba_mid = port + 0x4;
     ata->port.lba_hi = port + 0x5;
     ata->port.device = port + 0x6;
     ata->port.command = port + 0x7;
     ata->port.control = port + 0x206;
 }
References ata_ports_t::command, ata_ports_t::control, ata_ports_t::data, ata_ports_t::device, ata_ports_t::error, ata_t::is_master, ata_ports_t::lba_hi, ata_ports_t::lba_lo, ata_ports_t::lba_mid, ata_t::port, and ata_ports_t::sector_count.
Referenced by ata_add_new_device(), and ide_find_devices().
ata_install()
void ata_install ()
Definition at line 71 of file ata.c.
 {
     // registering driver and passing info to it
     driver_install(_ata_driver_info());
 }
References _ata_driver_info(), and driver_install().
Referenced by stage3().
Variable Documentation
_ata_drives
ata_t _ata_drives[MAX_DEVICES_COUNT] extern
Definition at line 12 of file ata.c.
Referenced by ata_add_new_device(), ata_flush(), ata_get_capacity(), ata_read(), and ata_write().