oneOS: include/drivers/x86/display.h File Reference
display.h File Reference
#include <platform/x86/port.h>
#include <types.h>
#include <utils.h>
#include <utils/mem.h>
#include <platform/x86/memmap.h>
Macros
#define VIDEO_MEMORY (char*)(0xb8000 + BIOS_SETTING_BASE)
#define VIDEO_ADDRESS (char*)(0xb8000 + BIOS_SETTING_BASE)
#define MAX_ROWS 25
#define MAX_COLS 80
#define WHITE_ON_BLACK 0x0f
#define BLACK_ON_WHITE 0xf0
#define RED_ON_BLACK 0x04
#define REG_SCREEN_CTRL 0x3d4
#define REG_SCREEN_DATA 0x3d5
#define TRUE 1
#define FALSE 0
Typedefs
typedef unsigned int u_int
Functions
void print_char (char symbol, unsigned char color, int col, int row)
void ext_print_char (char symbol, unsigned char color, int col, int row, int minus_offset)
void delete_char (unsigned char color, int col, int row, int minus_offset)
void print_string (const char *string, unsigned char color, int col, int row)
void print_hex (uint32_t hex, unsigned char color, int col, int row)
void kprintf (const char *string,...)
void kprinth (uint32_t hex)
void print_dec (uint32_t dec, unsigned char color, int col, int row)
void kprintd (uint32_t dec)
void clean_screen ()
void scroll (unsigned char lines)
char col_in_field (int col)
char row_in_field (int row)
void set_cursor_offset (unsigned short offset)
int get_cursor_offet ()
int get_offset (int col, int row)
Macro Definition Documentation
BLACK_ON_WHITE
#define BLACK_ON_WHITE 0xf0
Definition at line 16 of file display.h.
FALSE
#define FALSE 0
Definition at line 23 of file display.h.
MAX_COLS
#define MAX_COLS 80
Definition at line 13 of file display.h.
MAX_ROWS
#define MAX_ROWS 25
Definition at line 12 of file display.h.
RED_ON_BLACK
#define RED_ON_BLACK 0x04
Definition at line 17 of file display.h.
REG_SCREEN_CTRL
#define REG_SCREEN_CTRL 0x3d4
Definition at line 19 of file display.h.
REG_SCREEN_DATA
#define REG_SCREEN_DATA 0x3d5
Definition at line 20 of file display.h.
TRUE
#define TRUE 1
Definition at line 22 of file display.h.
VIDEO_ADDRESS
#define VIDEO_ADDRESS (char*)(0xb8000 + BIOS_SETTING_BASE)
Definition at line 11 of file display.h.
VIDEO_MEMORY
#define VIDEO_MEMORY (char*)(0xb8000 + BIOS_SETTING_BASE)
Definition at line 10 of file display.h.
WHITE_ON_BLACK
#define WHITE_ON_BLACK 0x0f
Definition at line 15 of file display.h.
Typedef Documentation
u_int
typedef unsigned int u_int
Definition at line 25 of file display.h.
Function Documentation
clean_screen()
void clean_screen ()
Definition at line 82 of file display.c.
                     {
     char* mem = VIDEO_MEMORY;
     for (int i = 0; i < 2 * MAX_COLS * MAX_ROWS; i+=2) {
         mem[i] = ' ';
         mem[i+1] = WHITE_ON_BLACK;
     }
     set_cursor_offset(0);
 }
References MAX_COLS, MAX_ROWS, mem(), set_cursor_offset(), VIDEO_MEMORY, and WHITE_ON_BLACK.
Referenced by _syscmd_shutdown(), _tty_process_esc_seq(), cmd_install(), kpanic_at_test(), stage2(), and stage3().
col_in_field()
char col_in_field (int col)
Definition at line 131 of file display.c.
 { return (0 <= col && col <= MAX_COLS); }
References MAX_COLS.
delete_char()
void delete_char (unsigned char color, int col, int row, int minus_offset)
Definition at line 23 of file display.c.
{
     char* mem = VIDEO_MEMORY;
     unsigned short offset_types[2] = {get_cursor_offet(), get_offset(col, row)};
     unsigned short offset = offset_types[(col_in_field(col) && row_in_field(row))] - minus_offset;
     mem[offset * 2] = ' ';
     mem[offset * 2 + 1] = color;
     set_cursor_offset(offset);
 }
References col_in_field(), get_cursor_offet(), get_offset(), mem(), row_in_field(), set_cursor_offset(), and VIDEO_MEMORY.
Referenced by _cmd_input(), and tty_eat_key().
ext_print_char()
void ext_print_char (char symbol, unsigned char color, int col, int row, int minus_offset)
Definition at line 6 of file display.c.
{
     char* mem = VIDEO_MEMORY;
     unsigned short offset_types[2] = {get_cursor_offet(), get_offset(col, row)};
     unsigned short offset = offset_types[(col_in_field(col) && row_in_field(row))] - minus_offset;
     if (symbol == '\n') {
         offset += MAX_COLS - (offset % MAX_COLS) - 1; // -1 to make it works (offset + 1 further)
     } else {
         mem[offset * 2] = symbol;
         mem[offset * 2 + 1] = color;
     }
     if (offset + 1 >= MAX_COLS * MAX_ROWS) {
         scroll(1); // scroll for 1 line
     } else {
         set_cursor_offset(offset+1);
     }
 }
References col_in_field(), get_cursor_offet(), get_offset(), MAX_COLS, MAX_ROWS, mem(), row_in_field(), scroll(), set_cursor_offset(), and VIDEO_MEMORY.
get_cursor_offet()
int get_cursor_offet ()
Definition at line 119 of file display.c.
{
     port_byte_out(REG_SCREEN_CTRL, 14);
     unsigned short offset = port_byte_in(REG_SCREEN_DATA);
     offset <<= 8;
     port_byte_out(REG_SCREEN_CTRL, 15);
     offset += port_byte_in(REG_SCREEN_DATA);
     return offset;
 }
References port_byte_in(), port_byte_out(), REG_SCREEN_CTRL, and REG_SCREEN_DATA.
get_offset()
int get_offset (int col, int row)
Definition at line 130 of file display.c.
 { return row * MAX_COLS + col; }
References MAX_COLS.
Referenced by _tty_process_esc_seq().
kprintd()
void kprintd (uint32_t dec)
Definition at line 130 of file display.c.
{
     print_dec(dec, WHITE_ON_BLACK, -1, -1);
 }
References print_dec(), and WHITE_ON_BLACK.
Referenced by kpanic_at_test(), kprintf(), read(), and sys_restart_syscall().
kprintf()
void kprintf (const char * string, ...)
Definition at line 100 of file display.c.
{
     char *ptr_to_next_arg = (char*)((uint32_t)&format + sizeof(void*));
     while (*format) {
         if (*format == '%') {
             format++;
             if (*format == 'x') {
                 uint32_t* arg =(uint32_t*)ptr_to_next_arg;
                 ptr_to_next_arg += sizeof(uint32_t);
                 kprinth(*arg);
             } else if (*format == 'd') {
                 uint32_t* arg =(uint32_t*)ptr_to_next_arg;
                 ptr_to_next_arg += sizeof(uint32_t);
                 kprintd(*arg);
             } else if (*format == 's') {
                 char** arg = (char**)ptr_to_next_arg;
                 ptr_to_next_arg += sizeof(char**);
                 print_string(*arg, WHITE_ON_BLACK, -1, -1);
             }
         } else {
             print_char(*format, WHITE_ON_BLACK, -1, -1);
         }
         format++;
     }
     // print_string(string, WHITE_ON_BLACK, -1, -1);
 }
References kprintd(), kprinth(), print_char(), print_string(), and WHITE_ON_BLACK.
Referenced by _cmd_loop_end(), _cmd_loop_start(), _cmd_processor(), _ext2_getdirent_block(), _syscmd_ls(), _syscmd_shutdown(), ata_add_new_device(), ata_indentify(), ata_read(), ata_write(), dentries_stat(), kmalloc(), kpanic_at_test(), pci_find_devices(), pmm_setup(), read(), rm(), signal_restore_thread_after_handling_signal(), and tty_new().
kprinth()
void kprinth (uint32_t hex)
Definition at line 126 of file display.c.
{
     print_hex(hex, WHITE_ON_BLACK, -1, -1);
 }
References print_hex(), and WHITE_ON_BLACK.
Referenced by kprintf(), and pmm_setup().
print_char()
void print_char (char symbol, unsigned char color, int col, int row)
Definition at line 3 of file display.c.
{
     char* mem = VIDEO_MEMORY;
     unsigned short offset_types[2] = {get_cursor_offet(), get_offset(col, row)};
     unsigned short offset = offset_types[(col_in_field(col) && row_in_field(row))];
     if (symbol == '\n') {
         offset += MAX_COLS - (offset % MAX_COLS) - 1; // -1 to make it works (offset + 1 further)
     } else {
         mem[offset * 2] = symbol;
         mem[offset * 2 + 1] = color;
     }
     if (offset + 1 >= MAX_COLS * MAX_ROWS) {
         scroll(1); // scroll for 1 line
     } else {
         set_cursor_offset(offset+1);
     }
 }
References col_in_field(), get_cursor_offet(), get_offset(), MAX_COLS, MAX_ROWS, mem(), row_in_field(), scroll(), set_cursor_offset(), and VIDEO_MEMORY.
Referenced by _tty_echo_key(), and tty_write().
print_dec()
void print_dec (uint32_t dec, unsigned char color, int col, int row)
Definition at line 51 of file display.c.
{
     uint32_t pk = 1000000000;
     bool was_not_zero = 0;
     while (pk > 0) {
         uint32_t pp = dec / pk;
         if (was_not_zero || pp > 0) {
             print_char(pp + '0', color, col, row);
             was_not_zero = 1;
         }
         dec -= pp * pk;
         pk /= 10;
     }
     if (!was_not_zero) {
         print_char('0', color, col, row);
     }
 }
References print_char().
Referenced by kprintd(), and printd().
print_hex()
void print_hex (uint32_t hex, unsigned char color, int col, int row)
Definition at line 28 of file display.c.
{
     uint32_t pk = (uint32_t)0x10000000;
     bool was_not_zero = 0;
     while (pk > 0) {
         uint32_t pp = hex / pk;
         if (was_not_zero || pp > 0) {
             if (pp >= 10) {
                 print_char(pp - 10 + 'A', color, col, row);
             } else {
                 print_char(pp + '0', color, col, row);
             }
             was_not_zero = 1;
         }
         hex -= pp * pk;
         pk /= 16;
     }
     if (was_not_zero) {
         print_char('h', color, col, row);
     } else {
         print_char('0', color, col, row);
     }
 }
References print_char().
Referenced by kprinth(), and printh().
print_string()
void print_string (const char * string, unsigned char color, int col, int row)
Definition at line 20 of file display.c.
{
     int i = 0;
     while (string[i] != 0) {
         print_char(string[i++], color, col, row);
         col = row = -1;
     }
 }
References print_char().
row_in_field()
char row_in_field (int row)
Definition at line 132 of file display.c.
 { return (0 <= row && row <= MAX_ROWS); }
References MAX_ROWS.
scroll()
void scroll (unsigned char lines)
Definition at line 93 of file display.c.
{
     char* mem = VIDEO_MEMORY;
     unsigned int mem_offset = lines * MAX_COLS;
     unsigned int bytes_2_del = 2*(MAX_COLS*MAX_ROWS-mem_offset);
     char* src = (mem + mem_offset*2);
     for (int i = 0; i < bytes_2_del; ++i) {
         *(mem + i) = *(src + i);
     }
     for (int i = bytes_2_del; i < 2 * MAX_COLS * MAX_ROWS; i+=2) {
         mem[i] = ' ';
         mem[i + 1] = WHITE_ON_BLACK;
     }
     set_cursor_offset(bytes_2_del/2);
 }
References MAX_COLS, MAX_ROWS, mem(), set_cursor_offset(), VIDEO_MEMORY, and WHITE_ON_BLACK.
set_cursor_offset()
void set_cursor_offset (unsigned short offset)
Definition at line 112 of file display.c.
{
     port_byte_out(REG_SCREEN_CTRL, 14);
     port_byte_out(REG_SCREEN_DATA, (unsigned char)(offset >> 8));
     port_byte_out(REG_SCREEN_CTRL, 15);
     port_byte_out(REG_SCREEN_DATA, (unsigned char)(offset & 0xff));
 }
References port_byte_out(), REG_SCREEN_CTRL, and REG_SCREEN_DATA.
Referenced by _tty_process_esc_seq().