oneOS: src/kernel/platform/x86/interrupts/irq_handler.c File Reference
irq_handler.c File Reference
#include <platform/x86/irq_handler.h>
#include <tasking/tasking.h>
#include <platform/x86/system.h>
Functions
void irq_redirect (uint8_t int_no)
void irq_handler (trapframe_t *tf)
void irq_empty_handler ()
Function Documentation
irq_empty_handler()
void irq_empty_handler ()
Definition at line 29 of file irq_handler.c.
{
     return;
 }
Referenced by init_irq_handlers().
irq_handler()
void irq_handler (trapframe_t * tf)
Definition at line 10 of file irq_handler.c.
{
     system_disable_interrupts();
     if (tf->int_no >= IRQ_SLAVE_OFFSET) {
         port_byte_out(0xA0, 0x20);
     }
     port_byte_out(0x20, 0x20);
     if (likely(RUNNIG_THREAD)) {
         if (RUNNIG_THREAD->process->is_kthread) {
             RUNNIG_THREAD->tf = tf;
         }
     }
     irq_redirect(tf->int_no);
     /* We are leaving interrupt, and later interrupts will be on,
        when flags are restored */
     system_enable_interrupts_only_counter();
 }
References irq_redirect(), IRQ_SLAVE_OFFSET, likely, port_byte_out(), RUNNIG_THREAD, system_disable_interrupts(), and system_enable_interrupts_only_counter().
irq_redirect()
void irq_redirect (uint8_t int_no)
Definition at line 5 of file irq_handler.c.
{
     void (*func)() = (void*)handlers[int_no];
     func();
 }
References handlers.
Referenced by irq_handler().