oneOS: include/platform/x86/isr_handler.h File Reference
isr_handler.h File Reference
#include <types.h>
#include <platform/x86/idt.h>
#include <drivers/x86/display.h>
Functions
void isr_handler (trapframe_t *tf)
void isr_standart_handler (trapframe_t *tf)
uint32_t rcr2 ()
Function Documentation
isr_handler()
void isr_handler (trapframe_t * tf)
Definition at line 46 of file isr_handler.c.
 {
     system_disable_interrupts();
     proc_t* p = 0;
     if (likely(RUNNIG_THREAD)) {
         p = RUNNIG_THREAD->process;
         if (RUNNIG_THREAD->process->is_kthread) {
             RUNNIG_THREAD->tf = tf;
         }
     }
     /* TODO: A thing to change */
     if (tf->int_no == 14) {
         int res = vmm_page_fault_handler(tf->err, read_cr2());
         if (res == SHOULD_CRASH) {
             log_warn("Crash: pf err %d at %x: %d pid, %x eip\n", tf->err, read_cr2(), p->pid, tf->eip);
             thread_print_backtrace();
             proc_die(p);
             resched();
         }
     } else if (tf->int_no == 6) {
         if (!p) {
             kpanic("invalid opcode in kernel");
         } else {
             log_warn("Crash: invalid opcode in %d tid\n", RUNNIG_THREAD->tid);
             thread_print_backtrace();
             proc_die(p);
             resched();
         }
     } else {
         log_warn("Int w/o handler: %d: %s: %d", tf->int_no, exception_messages[tf->int_no], tf->err);
     }
     /* We are leaving interrupt, and later interrupts will be on,
        when flags are restored */
     system_enable_interrupts_only_counter();
 }
References exception_messages, kpanic(), likely, log_warn(), p, proc_die(), read_cr2(), resched(), RUNNIG_THREAD, SHOULD_CRASH, system_disable_interrupts(), system_enable_interrupts_only_counter(), thread_print_backtrace(), and vmm_page_fault_handler().
isr_standart_handler()
void isr_standart_handler (trapframe_t * tf)
rcr2()
uint32_t rcr2 ()