oneOS: include/utils/kassert.h File Reference
kassert.h File Reference
#include <log.h>
#include <platform/x86/system.h>
#include <types.h>
Macros
#define ASSERT(x)
Functions
void kpanic (char *msg)
Macro Definition Documentation
ASSERT
#define ASSERT (x)
Value:
    if (unlikely(!(x))) {                                      \
        log("kassert at line %d in %s\n", __LINE__, __FILE__); \
        system_stop();                                         \
    }
Definition at line 16 of file kassert.h.
Function Documentation
kpanic()
void kpanic (char * msg)
Definition at line 11 of file kassert.c.
 {
     log_error("Kpanic occured %s", err_msg);
     system_stop();
 }
References log_error(), and system_stop().
Referenced by _ext2_add_to_dir_block(), _ext2_rm_from_dir_block(), _kbdriver_notification(), _mouse_recieve_notification(), _vmm_create_kernel_ptables(), _vmm_pspace_init(), _vmm_split_pspace(), bga_recieve_notification(), isr_handler(), pit_setup(), signal_restore_thread_after_handling_signal(), vmm_load_page(), vmm_page_fault_handler(), vmm_setup(), and vmm_switch_pdir().