oneOS: src/kernel/utils/kassert.c File Reference
kassert.c File Reference
#include <utils/kassert.h>
Functions
void kpanic (char *err_msg)
Function Documentation
kpanic()
void kpanic (char * err_msg)
Definition at line 11 of file kassert.c.
 {
     log_error("Kpanic occured %s", err_msg);
     system_stop();
 }
References log_error(), and system_stop().
Referenced by _ext2_add_to_dir_block(), _ext2_rm_from_dir_block(), _kbdriver_notification(), _mouse_recieve_notification(), _vmm_create_kernel_ptables(), _vmm_pspace_init(), _vmm_split_pspace(), bga_recieve_notification(), isr_handler(), pit_setup(), signal_restore_thread_after_handling_signal(), vmm_load_page(), vmm_page_fault_handler(), vmm_setup(), and vmm_switch_pdir().