oneOS: src/kernel/platform/x86/port.c File Reference
port.c File Reference
#include <platform/x86/port.h>
Functions
uint8_t port_byte_in (uint16_t port)
void port_byte_out (uint16_t port, uint8_t data)
uint16_t port_word_in (uint16_t port)
void port_word_out (uint16_t port, uint16_t data)
uint32_t port_dword_in (uint16_t port)
void port_dword_out (uint16_t port, uint32_t data)
uint8_t port_8bit_in (uint16_t port)
void port_8bit_out (uint16_t port, uint8_t data)
uint16_t port_16bit_in (uint16_t port)
void port_16bit_out (uint16_t port, uint16_t data)
uint32_t port_32bit_in (uint16_t port)
void port_32bit_out (uint16_t port, uint32_t data)
void io_wait ()
Function Documentation
io_wait()
void io_wait ()
Definition at line 63 of file port.c.
                {
     asm volatile("out %%al, $0x80" : : "a"(0)); // writing to "unused" port
 }
Referenced by pic_remap().
port_16bit_in()
uint16_t port_16bit_in (uint16_t port)
Definition at line 43 of file port.c.
{
     uint16_t result_data;
     asm volatile("inw %%dx, %%ax" : "=a"(result_data) : "d"(port));
     return result_data;
 }
Referenced by _bga_read_reg(), ata_indentify(), ata_read(), and indentify_ata_device().
port_16bit_out()
void port_16bit_out (uint16_t port, uint16_t data)
Definition at line 49 of file port.c.
{
     asm volatile("outw %%ax, %%dx" : : "a"(data), "d"(port));
 }
Referenced by _bga_read_reg(), _bga_write_reg(), and ata_write().
port_32bit_in()
uint32_t port_32bit_in (uint16_t port)
Definition at line 53 of file port.c.
{
     uint32_t result_data;
     asm volatile("inl %%dx, %%eax" : "=a"(result_data) : "d"(port));
     return result_data;
 }
port_32bit_out()
void port_32bit_out (uint16_t port, uint32_t data)
Definition at line 59 of file port.c.
{
     asm volatile("outl %%eax, %%dx" : : "a"(data), "d"(port));
 }
port_8bit_in()
uint8_t port_8bit_in (uint16_t port)
Definition at line 33 of file port.c.
{
     uint8_t result_data;
     asm volatile("inb %%dx, %%al" : "=a" (result_data) : "d" (port));
     return result_data;
 }
Referenced by _mouse_wait_in(), _mouse_wait_out(), _mouse_wait_then_read(), ata_flush(), ata_indentify(), ata_read(), ata_write(), cmos_read(), indentify_ata_device(), and mouse_handler().
port_8bit_out()
void port_8bit_out (uint16_t port, uint8_t data)
Definition at line 39 of file port.c.
{
     asm volatile("outb %%al, %%dx" : : "a"(data), "d"(port));
 }
Referenced by _mouse_wait_then_write(), ata_flush(), ata_indentify(), ata_read(), ata_write(), cmos_read(), and indentify_ata_device().
port_byte_in()
uint8_t port_byte_in (uint16_t port)
Definition at line 3 of file port.c.
{
     uint8_t result_data;
     asm volatile("inb %%dx, %%al" : "=a" (result_data) : "d" (port));
     return result_data;
 }
Referenced by _uart_is_free_in(), _uart_is_free_out(), get_cursor_offet(), keyboard_handler(), pic_remap(), and uart_read().
port_byte_out()
void port_byte_out (uint16_t port, uint8_t data)
Definition at line 9 of file port.c.
{
     asm volatile("outb %%al, %%dx" : : "a"(data), "d"(port));
 }
Referenced by _pit_set_frequency(), _uart_setup_impl(), get_cursor_offet(), irq_handler(), pic_remap(), set_cursor_offset(), and uart_write().
port_dword_in()
uint32_t port_dword_in (uint16_t port)
Definition at line 23 of file port.c.
{
     uint32_t result_data;
     asm volatile("inl %%dx, %%eax" : "=a"(result_data) : "d"(port));
     return result_data;
 }
Referenced by pci_read().
port_dword_out()
void port_dword_out (uint16_t port, uint32_t data)
Definition at line 29 of file port.c.
{
     asm volatile("outl %%eax, %%dx" : : "a"(data), "d"(port));
 }
Referenced by pci_read(), and pci_write().
port_word_in()
uint16_t port_word_in (uint16_t port)
Definition at line 13 of file port.c.
{
     uint16_t result_data;
     asm volatile("inw %%dx, %%ax" : "=a"(result_data) : "d"(port));
     return result_data;
 }
port_word_out()
void port_word_out (uint16_t port, uint16_t data)
Definition at line 19 of file port.c.
{
     asm volatile("outw %%ax, %%dx" : : "a"(data), "d"(port));
 }