oneOS: src/kernel/utils/kernel_self_test.c File Reference
kernel_self_test.c File Reference
#include <utils/kernel_self_test.h>
#include <drivers/x86/display.h>
#include <mem/kmalloc.h>
#include <mem/vmm/vmm.h>
Functions
bool _test_kmalloc ()
bool _test_page_fault ()
void kpanic_at_test (char *t_err_msg, uint16_t test_no)
bool kernel_self_test (bool throw_kernel_panic)
Function Documentation
_test_kmalloc()
bool _test_kmalloc ()
Definition at line 9 of file kernel_self_test.c.
                      {
     uint32_t* kek1 = (uint32_t*)kmalloc(sizeof(uint32_t));
     uint32_t* kek2 = (uint32_t*)kmalloc(sizeof(uint32_t));
     *kek1 = 1;
     *kek2 = 2;
     return *kek1 == 1 && *kek2 == 2;
 }
References kmalloc().
Referenced by kernel_self_test().
_test_page_fault()
bool _test_page_fault ()
Definition at line 17 of file kernel_self_test.c.
{
     int* newpage = (int *)0x10000000;
     *newpage = 8;
     return *newpage == 8;
 }
Referenced by kernel_self_test().
kernel_self_test()
bool kernel_self_test (bool throw_kernel_panic)
Definition at line 34 of file kernel_self_test.c.
{
     void* active_test[] = {
         _test_kmalloc,
         _test_page_fault,
         0 // end sign
     };
     uint16_t i = 0;
     while (active_test[i] != 0) {
         bool (*test)() = active_test[i];
         if (!test()) {
             if (throw_kernel_panic) {
                 while (1) {}
                 kpanic_at_test("Kernel-self-test NOT passed", i);
             } else {
                 return false;
             }
         }
         i++;
     }
     return true;
 }
References _test_kmalloc(), _test_page_fault(), and kpanic_at_test().
Referenced by stage3().
kpanic_at_test()
void kpanic_at_test (char * t_err_msg, uint16_t test_no)
Definition at line 23 of file kernel_self_test.c.
{
     clean_screen();
     kprintf("*****\n");
     kprintf("Kernel Panic\n");
     kprintf("*****\n");
     kprintf(t_err_msg);
     kprintf("\nFailed Test: "); kprintd(test_no);
     kprintf("\n*****");
     while (1) {}
 }
References clean_screen(), kprintd(), and kprintf().
Referenced by kernel_self_test().