oneOS: include/drivers/x86/keyboard.h File Reference
keyboard.h File Reference
#include <drivers/x86/display.h>
#include <drivers/driver_manager.h>
#include <platform/x86/idt.h>
Data Structures
struct kbd_packet
Typedefs
typedef uint32_t key_t
typedef struct kbd_packet kbd_packet_t
Enumerations
enum KEYCODE {
KEY_CTRLC = '\003' , KEY_SPACE = ' ' , KEY_0 = '0' , KEY_1 = '1' ,
KEY_2 = '2' , KEY_3 = '3' , KEY_4 = '4' , KEY_5 = '5' ,
KEY_6 = '6' , KEY_7 = '7' , KEY_8 = '8' , KEY_9 = '9' ,
KEY_A = 'a' , KEY_B = 'b' , KEY_C = 'c' , KEY_D = 'd' ,
KEY_E = 'e' , KEY_F = 'f' , KEY_G = 'g' , KEY_H = 'h' ,
KEY_I = 'i' , KEY_J = 'j' , KEY_K = 'k' , KEY_L = 'l' ,
KEY_M = 'm' , KEY_N = 'n' , KEY_O = 'o' , KEY_P = 'p' ,
KEY_Q = 'q' , KEY_R = 'r' , KEY_S = 's' , KEY_T = 't' ,
KEY_U = 'u' , KEY_V = 'v' , KEY_W = 'w' , KEY_X = 'x' ,
KEY_Y = 'y' , KEY_Z = 'z' , KEY_RETURN = '\r' , KEY_ESCAPE = 0x1001 ,
KEY_BACKSPACE = '\b' , KEY_UP = 0x1100 , KEY_DOWN = 0x1101 , KEY_LEFT = 0x1102 ,
KEY_RIGHT = 0x1103 , KEY_F1 = 0x1201 , KEY_F2 = 0x1202 , KEY_F3 = 0x1203 ,
KEY_F4 = 0x1204 , KEY_F5 = 0x1205 , KEY_F6 = 0x1206 , KEY_F7 = 0x1207 ,
KEY_F8 = 0x1208 , KEY_F9 = 0x1209 , KEY_F10 = 0x120a , KEY_F11 = 0x120b ,
KEY_F12 = 0x120b , KEY_F13 = 0x120c , KEY_F14 = 0x120d , KEY_F15 = 0x120e ,
KEY_DOT = '.' , KEY_COMMA = ',' , KEY_COLON = ':' , KEY_SEMICOLON = ';' ,
KEY_SLASH = '/' , KEY_BACKSLASH = '\\' , KEY_PLUS = '+' , KEY_MINUS = '-' ,
KEY_ASTERISK = '*' , KEY_EXCLAMATION = '!' , KEY_QUESTION = '?' , KEY_QUOTEDOUBLE = '\"' ,
KEY_QUOTE = '\'' , KEY_EQUAL = '=' , KEY_HASH = '#' , KEY_PERCENT = '' ,
KEY_AMPERSAND = '&' , KEY_UNDERSCORE = '_' , KEY_LEFTPARENTHESIS = '(' , KEY_RIGHTPARENTHESIS = ')' ,
KEY_LEFTBRACKET = '[' , KEY_RIGHTBRACKET = ']' , KEY_LEFTCURL = '{' , KEY_RIGHTCURL = '}' ,
KEY_DOLLAR = '$' , KEY_POUND = 0 , KEY_EURO = '$' , KEY_LESS = '<' ,
KEY_GREATER = '>' , KEY_BAR = '|' , KEY_GRAVE = '`' , KEY_TILDE = '~' ,
KEY_AT = '@' , KEY_CARRET = '^' , KEY_KP_0 = '0' , KEY_KP_1 = '1' ,
KEY_KP_2 = '2' , KEY_KP_3 = '3' , KEY_KP_4 = '4' , KEY_KP_5 = '5' ,
KEY_KP_6 = '6' , KEY_KP_7 = '7' , KEY_KP_8 = '8' , KEY_KP_9 = '9' ,
KEY_KP_PLUS = '+' , KEY_KP_MINUS = '-' , KEY_KP_DECIMAL = '.' , KEY_KP_DIVIDE = '/' ,
KEY_KP_ASTERISK = '*' , KEY_KP_NUMLOCK = 0x300f , KEY_KP_ENTER = 0x3010 , KEY_TAB = 0x4000 ,
KEY_CAPSLOCK = 0x4001 , KEY_LSHIFT = 0x4002 , KEY_LCTRL = 0x4003 , KEY_LALT = 0x4004 ,
KEY_LWIN = 0x4005 , KEY_RSHIFT = 0x4006 , KEY_RCTRL = 0x4007 , KEY_RALT = 0x4008 ,
KEY_RWIN = 0x4009 , KEY_INSERT = 0x400a , KEY_DELETE = 0x400b , KEY_HOME = 0x400c ,
KEY_END = 0x400d , KEY_PAGEUP = 0x400e , KEY_PAGEDOWN = 0x400f , KEY_SCROLLLOCK = 0x4010 ,
KEY_PAUSE = 0x4011 , KEY_PREV_TRACK = 0x5001 , KEY_NEXT_TRACK = 0x5002 , KEY_MUTE = 0x5003 ,
KEY_CALC = 0x5004 , KEY_PLAY = 0x5005 , KEY_STOP = 0x5006 , KEY_VOL_DOWN = 0x5007 ,
KEY_VOL_UP = 0x5008 , KEY_WWW_HOME = 0x500a , KEY_UNKNOWN , KEY_NUMKEYCODES
}
Functions
void keyboard_handler ()
bool kbdriver_install ()
void kbdriver_run ()
uint32_t kbdriver_get_last_key ()
void kbdriver_discard_last_key ()
Typedef Documentation
kbd_packet_t
typedef struct kbd_packet kbd_packet_t
Definition at line 8 of file keyboard.h.
key_t
typedef uint32_t key_t
Definition at line 8 of file keyboard.h.
Enumeration Type Documentation
KEYCODE
enum KEYCODE
Enumerator
KEY_CTRLC
KEY_SPACE
KEY_0
KEY_1
KEY_2
KEY_3
KEY_4
KEY_5
KEY_6
KEY_7
KEY_8
KEY_9
KEY_A
KEY_B
KEY_C
KEY_D
KEY_E
KEY_F
KEY_G
KEY_H
KEY_I
KEY_J
KEY_K
KEY_L
KEY_M
KEY_N
KEY_O
KEY_P
KEY_Q
KEY_R
KEY_S
KEY_T
KEY_U
KEY_V
KEY_W
KEY_X
KEY_Y
KEY_Z
KEY_RETURN
KEY_ESCAPE
KEY_BACKSPACE
KEY_UP
KEY_DOWN
KEY_LEFT
KEY_RIGHT
KEY_F1
KEY_F2
KEY_F3
KEY_F4
KEY_F5
KEY_F6
KEY_F7
KEY_F8
KEY_F9
KEY_F10
KEY_F11
KEY_F12
KEY_F13
KEY_F14
KEY_F15
KEY_DOT
KEY_COMMA
KEY_COLON
KEY_SEMICOLON
KEY_SLASH
KEY_BACKSLASH
KEY_PLUS
KEY_MINUS
KEY_ASTERISK
KEY_EXCLAMATION
KEY_QUESTION
KEY_QUOTEDOUBLE
KEY_QUOTE
KEY_EQUAL
KEY_HASH
KEY_PERCENT
KEY_AMPERSAND
KEY_UNDERSCORE
KEY_LEFTPARENTHESIS
KEY_RIGHTPARENTHESIS
KEY_LEFTBRACKET
KEY_RIGHTBRACKET
KEY_LEFTCURL
KEY_RIGHTCURL
KEY_DOLLAR
KEY_POUND
KEY_EURO
KEY_LESS
KEY_GREATER
KEY_BAR
KEY_GRAVE
KEY_TILDE
KEY_AT
KEY_CARRET
KEY_KP_0
KEY_KP_1
KEY_KP_2
KEY_KP_3
KEY_KP_4
KEY_KP_5
KEY_KP_6
KEY_KP_7
KEY_KP_8
KEY_KP_9
KEY_KP_PLUS
KEY_KP_MINUS
KEY_KP_DECIMAL
KEY_KP_DIVIDE
KEY_KP_ASTERISK
KEY_KP_NUMLOCK
KEY_KP_ENTER
KEY_TAB
KEY_CAPSLOCK
KEY_LSHIFT
KEY_LCTRL
KEY_LALT
KEY_LWIN
KEY_RSHIFT
KEY_RCTRL
KEY_RALT
KEY_RWIN
KEY_INSERT
KEY_DELETE
KEY_HOME
KEY_END
KEY_PAGEUP
KEY_PAGEDOWN
KEY_SCROLLLOCK
KEY_PAUSE
KEY_PREV_TRACK
KEY_NEXT_TRACK
KEY_MUTE
KEY_CALC
KEY_PLAY
KEY_STOP
KEY_VOL_DOWN
KEY_VOL_UP
KEY_WWW_HOME
KEY_UNKNOWN
KEY_NUMKEYCODES
Definition at line 16 of file keyboard.h.
              {
     // Alphanumeric keys ////////////////
     KEY_CTRLC = '\003',
     KEY_SPACE = ' ',
     KEY_0 = '0',
     KEY_1 = '1',
     KEY_2 = '2',
     KEY_3 = '3',
     KEY_4 = '4',
     KEY_5 = '5',
     KEY_6 = '6',
     KEY_7 = '7',
     KEY_8 = '8',
     KEY_9 = '9',
     KEY_A = 'a',
     KEY_B = 'b',
     KEY_C = 'c',
     KEY_D = 'd',
     KEY_E = 'e',
     KEY_F = 'f',
     KEY_G = 'g',
     KEY_H = 'h',
     KEY_I = 'i',
     KEY_J = 'j',
     KEY_K = 'k',
     KEY_L = 'l',
     KEY_M = 'm',
     KEY_N = 'n',
     KEY_O = 'o',
     KEY_P = 'p',
     KEY_Q = 'q',
     KEY_R = 'r',
     KEY_S = 's',
     KEY_T = 't',
     KEY_U = 'u',
     KEY_V = 'v',
     KEY_W = 'w',
     KEY_X = 'x',
     KEY_Y = 'y',
     KEY_Z = 'z',
     KEY_RETURN = '\r',
     KEY_ESCAPE = 0x1001,
     KEY_BACKSPACE = '\b',
     // Arrow keys ////////////////////////
     KEY_UP = 0x1100,
     KEY_DOWN = 0x1101,
     KEY_LEFT = 0x1102,
     KEY_RIGHT = 0x1103,
     // Function keys /////////////////////
     KEY_F1 = 0x1201,
     KEY_F2 = 0x1202,
     KEY_F3 = 0x1203,
     KEY_F4 = 0x1204,
     KEY_F5 = 0x1205,
     KEY_F6 = 0x1206,
     KEY_F7 = 0x1207,
     KEY_F8 = 0x1208,
     KEY_F9 = 0x1209,
     KEY_F10 = 0x120a,
     KEY_F11 = 0x120b,
     KEY_F12 = 0x120b,
     KEY_F13 = 0x120c,
     KEY_F14 = 0x120d,
     KEY_F15 = 0x120e,
     KEY_DOT = '.',
     KEY_COMMA = ',',
     KEY_COLON = ':',
     KEY_SEMICOLON = ';',
     KEY_SLASH = '/',
     KEY_BACKSLASH = '\\',
     KEY_PLUS = '+',
     KEY_MINUS = '-',
     KEY_ASTERISK = '*',
     KEY_EXCLAMATION = '!',
     KEY_QUESTION = '?',
     KEY_QUOTEDOUBLE = '\"',
     KEY_QUOTE = '\'',
     KEY_EQUAL = '=',
     KEY_HASH = '#',
     KEY_PERCENT = '%',
     KEY_AMPERSAND = '&',
     KEY_UNDERSCORE = '_',
     KEY_LEFTPARENTHESIS = '(',
     KEY_RIGHTPARENTHESIS = ')',
     KEY_LEFTBRACKET = '[',
     KEY_RIGHTBRACKET = ']',
     KEY_LEFTCURL = '{',
     KEY_RIGHTCURL = '}',
     KEY_DOLLAR = '$',
     KEY_POUND = 0,
     KEY_EURO = '$',
     KEY_LESS = '<',
     KEY_GREATER = '>',
     KEY_BAR = '|',
     KEY_GRAVE = '`',
     KEY_TILDE = '~',
     KEY_AT = '@',
     KEY_CARRET = '^',
     // Numeric keypad //////////////////////
     KEY_KP_0 = '0',
     KEY_KP_1 = '1',
     KEY_KP_2 = '2',
     KEY_KP_3 = '3',
     KEY_KP_4 = '4',
     KEY_KP_5 = '5',
     KEY_KP_6 = '6',
     KEY_KP_7 = '7',
     KEY_KP_8 = '8',
     KEY_KP_9 = '9',
     KEY_KP_PLUS = '+',
     KEY_KP_MINUS = '-',
     KEY_KP_DECIMAL = '.',
     KEY_KP_DIVIDE = '/',
     KEY_KP_ASTERISK = '*',
     KEY_KP_NUMLOCK = 0x300f,
     KEY_KP_ENTER = 0x3010,
     KEY_TAB = 0x4000,
     KEY_CAPSLOCK = 0x4001,
     // Modify keys ////////////////////////////
     KEY_LSHIFT = 0x4002,
     KEY_LCTRL = 0x4003,
     KEY_LALT = 0x4004,
     KEY_LWIN = 0x4005,
     KEY_RSHIFT = 0x4006,
     KEY_RCTRL = 0x4007,
     KEY_RALT = 0x4008,
     KEY_RWIN = 0x4009,
     KEY_INSERT = 0x400a,
     KEY_DELETE = 0x400b,
     KEY_HOME = 0x400c,
     KEY_END = 0x400d,
     KEY_PAGEUP = 0x400e,
     KEY_PAGEDOWN = 0x400f,
     KEY_SCROLLLOCK = 0x4010,
     KEY_PAUSE = 0x4011,
     // Multimedia keys ////////////////////////
     KEY_PREV_TRACK = 0x5001,
     KEY_NEXT_TRACK = 0x5002,
     KEY_MUTE = 0x5003,
     KEY_CALC = 0x5004,
     KEY_PLAY = 0x5005,
     KEY_STOP = 0x5006,
     KEY_VOL_DOWN = 0x5007,
     KEY_VOL_UP = 0x5008,
     KEY_WWW_HOME = 0x500a,
     KEY_UNKNOWN,
     KEY_NUMKEYCODES
 };
Function Documentation
kbdriver_discard_last_key()
void kbdriver_discard_last_key ()
Definition at line 441 of file keyboard.c.
 {
     _kbdriver_last_scancode = KEY_UNKNOWN;
 }
References _kbdriver_last_scancode, and KEY_UNKNOWN.
Referenced by _cmd_getkeycode(), and _keyboard_driver_info().
kbdriver_get_last_key()
uint32_t kbdriver_get_last_key ()
Definition at line 432 of file keyboard.c.
 {
     if (_kbdriver_last_scancode == KEY_UNKNOWN) {
         return KEY_UNKNOWN;
     } else {
         return _kbdriver_get_keycode(_kbdriver_last_scancode);
     }
 }
References _kbdriver_get_keycode(), _kbdriver_last_scancode, and KEY_UNKNOWN.
Referenced by _cmd_getkeycode(), and _keyboard_driver_info().
kbdriver_install()
bool kbdriver_install ()
Definition at line 350 of file keyboard.c.
 {
     driver_install(_keyboard_driver_info());
     return true;
 }
References _keyboard_driver_info(), and driver_install().
Referenced by stage3().
kbdriver_run()
void kbdriver_run ()
Definition at line 356 of file keyboard.c.
 {
     set_irq_handler(IRQ1, keyboard_handler);
     kbd_buffer = ringbuffer_create_std();
 }
References IRQ1, kbd_buffer, keyboard_handler(), ringbuffer_create_std(), and set_irq_handler().
Referenced by _keyboard_driver_info().
keyboard_handler()
void keyboard_handler ()
Definition at line 363 of file keyboard.c.
 {
     uint32_t scancode = (uint32_t)port_byte_in(0x60);
     if (scancode == 0xE0) {
         _kbdriver_has_prefix_e0 = true;
         return;
     }
     if (_kbdriver_has_prefix_e0) {
         scancode |= 0x100;
         _kbdriver_has_prefix_e0 = false;
     }
     key_t key;
     kbd_packet_t packet;
     if (scancode & 0x80) {
         scancode -= 0x80;
         key = _kbdriver_get_keycode(scancode);
         packet.key = key | (1 << 31);
         switch (key) {
         case KEY_LCTRL:
         case KEY_RCTRL:
             _kbdriver_ctrl_enabled = false;
             break;
         case KEY_LSHIFT:
         case KEY_RSHIFT:
             _kbdriver_shift_enabled = false;
             break;
         case KEY_CAPSLOCK:
             _kbdriver_caps_enabled ^= 1;
             break;
         case KEY_LALT:
         case KEY_RALT:
             _kbdriver_alt_enabled = false;
             break;
         default:
             key = _kbdriver_apply_modifiers(key);
             packet.key = key | (1 << 31);
         }
     } else {
         _kbdriver_last_scancode = scancode;
         key = _kbdriver_get_keycode(scancode);
         packet.key = key;
         switch (key) {
         case KEY_LCTRL:
         case KEY_RCTRL:
             _kbdriver_ctrl_enabled = true;
             break;
         case KEY_LSHIFT:
         case KEY_RSHIFT:
             _kbdriver_shift_enabled = true;
             break;
         case KEY_CAPSLOCK:
             break;
         case KEY_LALT:
         case KEY_RALT:
             _kbdriver_alt_enabled = true;
             break;
         default:
             key = _kbdriver_apply_modifiers(key);
             packet.key = key;
             /* FIXME: ifdef here to support console mode */
             /* tty_eat_key(key); */
         }
     }
     ringbuffer_write(&kbd_buffer, (uint8_t*)&packet, sizeof(kbd_packet_t));
 }
References _kbdriver_alt_enabled, _kbdriver_apply_modifiers(), _kbdriver_caps_enabled, _kbdriver_ctrl_enabled, _kbdriver_get_keycode(), _kbdriver_has_prefix_e0, _kbdriver_last_scancode, _kbdriver_shift_enabled, kbd_buffer, kbd_packet::key, KEY_CAPSLOCK, KEY_LALT, KEY_LCTRL, KEY_LSHIFT, KEY_RALT, KEY_RCTRL, KEY_RSHIFT, port_byte_in(), and ringbuffer_write().
Referenced by kbdriver_run().