oneOS: src/kernel/drivers/x86/keyboard.c File Reference
keyboard.c File Reference
#include <algo/ringbuffer.h>
#include <drivers/x86/keyboard.h>
#include <fs/devfs/devfs.h>
#include <fs/vfs.h>
#include <io/tty/tty.h>
#include <utils/kassert.h>
Functions
static key_t _kbdriver_get_keycode (uint32_t scancode)
static driver_desc_t _keyboard_driver_info ()
static key_t _kbdriver_apply_modifiers (key_t key)
static bool _kbdriver_can_read (dentry_t *dentry, uint32_t start)
static int _kbdriver_read (dentry_t *dentry, uint8_t *buf, uint32_t start, uint32_t len)
static void _kbdriver_notification (uint32_t msg, uint32_t param)
bool kbdriver_install ()
void kbdriver_run ()
void keyboard_handler ()
uint32_t kbdriver_get_last_key ()
void kbdriver_discard_last_key ()
Variables
static key_t _scancodes []
static key_t _scancodes_upper []
static bool _kbdriver_has_prefix_e0 = false
static bool _kbdriver_shift_enabled = false
static bool _kbdriver_ctrl_enabled = false
static bool _kbdriver_alt_enabled = false
static bool _kbdriver_caps_enabled = false
static uint32_t _kbdriver_last_scancode = KEY_UNKNOWN
static ringbuffer_t kbd_buffer
Function Documentation
_kbdriver_apply_modifiers()
static key_t _kbdriver_apply_modifiers (key_t key) static
Definition at line 255 of file keyboard.c.
 {
     if (_kbdriver_ctrl_enabled) {
         if (key == 'c') {
             key = KEY_CTRLC;
         }
         return key;
     }
     if (_kbdriver_shift_enabled || _kbdriver_caps_enabled) {
         if (key >= 'a' && key <= 'z') {
             key -= 32;
         }
     }
     if (_kbdriver_shift_enabled) {
         switch (key) {
         case KEY_0:
             key = KEY_RIGHTPARENTHESIS;
             break;
         case KEY_1:
             key = KEY_EXCLAMATION;
             break;
         case KEY_2:
             key = KEY_AT;
             break;
         case KEY_3:
             key = KEY_EXCLAMATION;
             break;
         case KEY_4:
             key = KEY_HASH;
             break;
         case KEY_5:
             key = KEY_PERCENT;
             break;
         case KEY_6:
             key = KEY_CARRET;
             break;
         case KEY_7:
             key = KEY_AMPERSAND;
             break;
         case KEY_8:
             key = KEY_ASTERISK;
             break;
         case KEY_9:
             key = KEY_LEFTPARENTHESIS;
             break;
         case KEY_COMMA:
             key = KEY_LESS;
             break;
         case KEY_DOT:
             key = KEY_GREATER;
             break;
         case KEY_SLASH:
             key = KEY_QUESTION;
             break;
         case KEY_SEMICOLON:
             key = KEY_COLON;
             break;
         case KEY_QUOTE:
             key = KEY_QUOTEDOUBLE;
             break;
         case KEY_LEFTBRACKET:
             key = KEY_LEFTCURL;
             break;
         case KEY_RIGHTBRACKET:
             key = KEY_RIGHTCURL;
             break;
         case KEY_GRAVE:
             key = KEY_TILDE;
             break;
         case KEY_MINUS:
             key = KEY_UNDERSCORE;
             break;
         case KEY_EQUAL:
             key = KEY_PLUS;
             break;
         case KEY_BACKSLASH:
             key = KEY_BAR;
             break;
         }
     }
     return key;
 }
References _kbdriver_caps_enabled, _kbdriver_ctrl_enabled, _kbdriver_shift_enabled, KEY_0, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_AMPERSAND, KEY_ASTERISK, KEY_AT, KEY_BACKSLASH, KEY_BAR, KEY_CARRET, KEY_COLON, KEY_COMMA, KEY_CTRLC, KEY_DOT, KEY_EQUAL, KEY_EXCLAMATION, KEY_GRAVE, KEY_GREATER, KEY_HASH, KEY_LEFTBRACKET, KEY_LEFTCURL, KEY_LEFTPARENTHESIS, KEY_LESS, KEY_MINUS, KEY_PERCENT, KEY_PLUS, KEY_QUESTION, KEY_QUOTE, KEY_QUOTEDOUBLE, KEY_RIGHTBRACKET, KEY_RIGHTCURL, KEY_RIGHTPARENTHESIS, KEY_SEMICOLON, KEY_SLASH, KEY_TILDE, and KEY_UNDERSCORE.
Referenced by keyboard_handler().
_kbdriver_can_read()
static bool _kbdriver_can_read (dentry_t * dentry, uint32_t start) static
Definition at line 199 of file keyboard.c.
 {
     return ringbuffer_space_to_read(&kbd_buffer) >= 1;
 }
References kbd_buffer, and ringbuffer_space_to_read().
Referenced by _kbdriver_notification().
_kbdriver_get_keycode()
static key_t _kbdriver_get_keycode (uint32_t scancode) static
Definition at line 181 of file keyboard.c.
 {
     key_t* lookup_table[] = { _scancodes, _scancodes_upper };
     return lookup_table[(scancode >> 8) & 1][scancode & ~((uint32_t)0x100)];
 }
References _scancodes, and _scancodes_upper.
Referenced by kbdriver_get_last_key(), and keyboard_handler().
_kbdriver_notification()
static void _kbdriver_notification (uint32_t msg, uint32_t param) static
Definition at line 214 of file keyboard.c.
 {
     if (msg == DM_NOTIFICATION_DEVFS_READY) {
         dentry_t* mp;
         if (vfs_resolve_path("/dev", &mp) < 0) {
             kpanic("Can't init mouse in /dev");
         }
         file_ops_t fops;
         fops.open = 0;
         fops.can_read = _kbdriver_can_read;
         fops.can_write = 0;
         fops.read = _kbdriver_read;
         fops.write = 0;
         fops.ioctl = 0;
         fops.mmap = 0;
         devfs_inode_t* res = devfs_register(mp, "kbd", 3, 0, &fops);
         dentry_put(mp);
     }
 }
References _kbdriver_can_read(), _kbdriver_read(), file_ops::can_read, file_ops::can_write, dentry_put(), devfs_register(), DM_NOTIFICATION_DEVFS_READY, file_ops::ioctl, kpanic(), file_ops::mmap, file_ops::open, file_ops::read, vfs_resolve_path(), and file_ops::write.
Referenced by _keyboard_driver_info().
_kbdriver_read()
static int _kbdriver_read (dentry_t * dentry, uint8_t * buf, uint32_t start, uint32_t len) static
Definition at line 204 of file keyboard.c.
 {
     uint32_t leno = ringbuffer_space_to_read(&kbd_buffer);
     if (leno > len) {
         leno = len;
     }
     int res = ringbuffer_read(&kbd_buffer, buf, leno);
     return leno;
 }
References buf, kbd_buffer, ringbuffer_read(), and ringbuffer_space_to_read().
Referenced by _kbdriver_notification().
_keyboard_driver_info()
static driver_desc_t _keyboard_driver_info () static
Definition at line 236 of file keyboard.c.
 {
     driver_desc_t kbd_desc;
     kbd_desc.type = DRIVER_INPUT_SYSTEMS_DEVICE;
     kbd_desc.auto_start = true;
     kbd_desc.is_device_driver = false;
     kbd_desc.is_device_needed = false;
     kbd_desc.is_driver_needed = false;
     kbd_desc.functions[DRIVER_NOTIFICATION] = _kbdriver_notification;
     kbd_desc.functions[DRIVER_INPUT_SYSTEMS_ADD_DEVICE] = kbdriver_run;
     kbd_desc.functions[DRIVER_INPUT_SYSTEMS_GET_LAST_KEY] = kbdriver_get_last_key;
     kbd_desc.functions[DRIVER_INPUT_SYSTEMS_DISCARD_LAST_KEY] = kbdriver_discard_last_key;
     kbd_desc.pci_serve_class = 0xff;
     kbd_desc.pci_serve_subclass = 0xff;
     kbd_desc.pci_serve_vendor_id = 0x00;
     kbd_desc.pci_serve_device_id = 0x00;
     return kbd_desc;
 }
References _kbdriver_notification(), driver_desc_t::auto_start, DRIVER_INPUT_SYSTEMS_ADD_DEVICE, DRIVER_INPUT_SYSTEMS_DEVICE, DRIVER_INPUT_SYSTEMS_DISCARD_LAST_KEY, DRIVER_INPUT_SYSTEMS_GET_LAST_KEY, DRIVER_NOTIFICATION, driver_desc_t::functions, driver_desc_t::is_device_driver, driver_desc_t::is_device_needed, driver_desc_t::is_driver_needed, kbdriver_discard_last_key(), kbdriver_get_last_key(), kbdriver_run(), driver_desc_t::pci_serve_class, driver_desc_t::pci_serve_device_id, driver_desc_t::pci_serve_subclass, driver_desc_t::pci_serve_vendor_id, and driver_desc_t::type.
Referenced by kbdriver_install().
kbdriver_discard_last_key()
void kbdriver_discard_last_key ()
Definition at line 441 of file keyboard.c.
 {
     _kbdriver_last_scancode = KEY_UNKNOWN;
 }
References _kbdriver_last_scancode, and KEY_UNKNOWN.
Referenced by _cmd_getkeycode(), and _keyboard_driver_info().
kbdriver_get_last_key()
uint32_t kbdriver_get_last_key ()
Definition at line 432 of file keyboard.c.
 {
     if (_kbdriver_last_scancode == KEY_UNKNOWN) {
         return KEY_UNKNOWN;
     } else {
         return _kbdriver_get_keycode(_kbdriver_last_scancode);
     }
 }
References _kbdriver_get_keycode(), _kbdriver_last_scancode, and KEY_UNKNOWN.
Referenced by _cmd_getkeycode(), and _keyboard_driver_info().
kbdriver_install()
bool kbdriver_install ()
Definition at line 350 of file keyboard.c.
 {
     driver_install(_keyboard_driver_info());
     return true;
 }
References _keyboard_driver_info(), and driver_install().
Referenced by stage3().
kbdriver_run()
void kbdriver_run ()
Definition at line 356 of file keyboard.c.
 {
     set_irq_handler(IRQ1, keyboard_handler);
     kbd_buffer = ringbuffer_create_std();
 }
References IRQ1, kbd_buffer, keyboard_handler(), ringbuffer_create_std(), and set_irq_handler().
Referenced by _keyboard_driver_info().
keyboard_handler()
void keyboard_handler ()
Definition at line 363 of file keyboard.c.
 {
     uint32_t scancode = (uint32_t)port_byte_in(0x60);
     if (scancode == 0xE0) {
         _kbdriver_has_prefix_e0 = true;
         return;
     }
     if (_kbdriver_has_prefix_e0) {
         scancode |= 0x100;
         _kbdriver_has_prefix_e0 = false;
     }
     key_t key;
     kbd_packet_t packet;
     if (scancode & 0x80) {
         scancode -= 0x80;
         key = _kbdriver_get_keycode(scancode);
         packet.key = key | (1 << 31);
         switch (key) {
         case KEY_LCTRL:
         case KEY_RCTRL:
             _kbdriver_ctrl_enabled = false;
             break;
         case KEY_LSHIFT:
         case KEY_RSHIFT:
             _kbdriver_shift_enabled = false;
             break;
         case KEY_CAPSLOCK:
             _kbdriver_caps_enabled ^= 1;
             break;
         case KEY_LALT:
         case KEY_RALT:
             _kbdriver_alt_enabled = false;
             break;
         default:
             key = _kbdriver_apply_modifiers(key);
             packet.key = key | (1 << 31);
         }
     } else {
         _kbdriver_last_scancode = scancode;
         key = _kbdriver_get_keycode(scancode);
         packet.key = key;
         switch (key) {
         case KEY_LCTRL:
         case KEY_RCTRL:
             _kbdriver_ctrl_enabled = true;
             break;
         case KEY_LSHIFT:
         case KEY_RSHIFT:
             _kbdriver_shift_enabled = true;
             break;
         case KEY_CAPSLOCK:
             break;
         case KEY_LALT:
         case KEY_RALT:
             _kbdriver_alt_enabled = true;
             break;
         default:
             key = _kbdriver_apply_modifiers(key);
             packet.key = key;
             /* FIXME: ifdef here to support console mode */
             /* tty_eat_key(key); */
         }
     }
     ringbuffer_write(&kbd_buffer, (uint8_t*)&packet, sizeof(kbd_packet_t));
 }
References _kbdriver_alt_enabled, _kbdriver_apply_modifiers(), _kbdriver_caps_enabled, _kbdriver_ctrl_enabled, _kbdriver_get_keycode(), _kbdriver_has_prefix_e0, _kbdriver_last_scancode, _kbdriver_shift_enabled, kbd_buffer, kbd_packet::key, KEY_CAPSLOCK, KEY_LALT, KEY_LCTRL, KEY_LSHIFT, KEY_RALT, KEY_RCTRL, KEY_RSHIFT, port_byte_in(), and ringbuffer_write().
Referenced by kbdriver_run().
Variable Documentation
_kbdriver_alt_enabled
bool _kbdriver_alt_enabled = false static
Definition at line 190 of file keyboard.c.
Referenced by keyboard_handler().
_kbdriver_caps_enabled
bool _kbdriver_caps_enabled = false static
Definition at line 191 of file keyboard.c.
Referenced by _kbdriver_apply_modifiers(), and keyboard_handler().
_kbdriver_ctrl_enabled
bool _kbdriver_ctrl_enabled = false static
Definition at line 189 of file keyboard.c.
Referenced by _kbdriver_apply_modifiers(), and keyboard_handler().
_kbdriver_has_prefix_e0
bool _kbdriver_has_prefix_e0 = false static
Definition at line 187 of file keyboard.c.
Referenced by keyboard_handler().
_kbdriver_last_scancode
uint32_t _kbdriver_last_scancode = KEY_UNKNOWN static
Definition at line 192 of file keyboard.c.
Referenced by kbdriver_discard_last_key(), kbdriver_get_last_key(), and keyboard_handler().
_kbdriver_shift_enabled
bool _kbdriver_shift_enabled = false static
Definition at line 188 of file keyboard.c.
Referenced by _kbdriver_apply_modifiers(), and keyboard_handler().
_scancodes
key_t _scancodes[] static
Definition at line 8 of file keyboard.c.
Referenced by _kbdriver_get_keycode().
_scancodes_upper
key_t _scancodes_upper[] static
Definition at line 94 of file keyboard.c.
Referenced by _kbdriver_get_keycode().
kbd_buffer
ringbuffer_t kbd_buffer static
Definition at line 197 of file keyboard.c.
Referenced by _kbdriver_can_read(), _kbdriver_read(), kbdriver_run(), and keyboard_handler().