oneOS: src/kernel/tasking/kthread.c File Reference
kthread.c File Reference
#include <errno.h>
#include <fs/vfs.h>
#include <io/tty/tty.h>
#include <mem/kmalloc.h>
#include <tasking/proc.h>
#include <tasking/thread.h>
#include <platform/x86/gdt.h>
#include <platform/x86/tasking/tss.h>
Functions
void trap_return ()
void _tasking_jumper ()
int _thread_setup_kstack (thread_t *thread, uint32_t esp)
int kthread_setup (proc_t *p)
int kthread_setup_regs (proc_t *p, void *entry_point)
void kthread_setup_segment_regs (proc_t *p)
int kthread_free (proc_t *p)
Function Documentation
_tasking_jumper()
void _tasking_jumper ()
used to jump to trapend the jump will start the process
Definition at line 33 of file tasking.c.
 {
     system_enable_interrupts();
     return;
 }
References system_enable_interrupts().
_thread_setup_kstack()
int _thread_setup_kstack (thread_t * thread, uint32_t esp)
Definition at line 22 of file thread.c.
 {
     char* sp = (char*)(esp);
     /* setting trapframe in kernel stack */
     sp -= sizeof(*thread->tf);
     thread->tf = (trapframe_t*)sp;
     /* setting return point in kernel stack */
     sp -= 4;
     *(uint32_t*)sp = (uint32_t)trap_return;
     /* setting context in kernel stack */
     sp -= sizeof(*thread->context);
     thread->context = (context_t*)sp;
     /* setting init data */
     memset((void*)thread->context, 0, sizeof(*thread->context));
     thread->context->eip = (uint32_t)_tasking_jumper;
     memset((void*)thread->tf, 0, sizeof(*thread->tf));
     /* setting fpu */
     thread->fpu_state = kmalloc_aligned(sizeof(fpu_state_t), 16);
     fpu_reset_state(thread->fpu_state);
     return 0;
 }
References _tasking_jumper(), thread::context, fpu_reset_state(), thread::fpu_state, kmalloc_aligned(), memset(), thread::tf, and trap_return().
Referenced by kthread_setup().
kthread_free()
int kthread_free (proc_t * p)
Definition at line 69 of file kthread.c.
 {
     /* proc_free can free kthreads too) */
     proc_free(p);
 }
References p, and proc_free().
kthread_setup()
int kthread_setup (proc_t * p)
KTHREAD FUNCTIONS
Definition at line 22 of file kthread.c.
 {
     p->pid = proc_alloc_pid();
     p->pgid = p->pid;
     p->is_kthread = true;
     /* allocating kernel stack */
     p->main_thread = proc_alloc_thread();
     p->main_thread->tid = p->pid;
     p->main_thread->process = p;
     p->main_thread->kstack = zoner_new_zone(VMM_PAGE_SIZE);
     if (!p->main_thread->kstack.start) {
         return -ENOMEM;
     }
     _thread_setup_kstack(p->main_thread, p->main_thread->kstack.start + VMM_PAGE_SIZE);
     /* setting current work directory */
     p->cwd = 0;
     p->fds = 0;
     /* setting signal handlers to 0 */
     p->main_thread->signals_mask = 0x0; /* All signals are disabled. */
     p->main_thread->pending_signals_mask = 0x0;
     memset((void*)p->main_thread->signal_handlers, 0, sizeof(p->main_thread->signal_handlers));
     return 0;
 }
References _thread_setup_kstack(), ENOMEM, memset(), p, proc_alloc_pid(), proc_alloc_thread(), VMM_PAGE_SIZE, and zoner_new_zone().
Referenced by _tasking_alloc_kernel_thread().
kthread_setup_regs()
int kthread_setup_regs (proc_t * p, void * entry_point)
Definition at line 51 of file kthread.c.
 {
     kthread_setup_segment_regs(p);
     p->main_thread->tf->ebp = (p->main_thread->kstack.start + VMM_PAGE_SIZE);
     p->main_thread->tf->esp = p->main_thread->tf->ebp;
     p->main_thread->tf->eip = (uint32_t)entry_point;
     return 0;
 }
References kthread_setup_segment_regs(), p, and VMM_PAGE_SIZE.
Referenced by _tasking_alloc_kernel_thread().
kthread_setup_segment_regs()
void kthread_setup_segment_regs (proc_t * p)
Definition at line 60 of file kthread.c.
 {
     p->main_thread->tf->cs = (SEG_KCODE << 3);
     p->main_thread->tf->ds = (SEG_KDATA << 3);
     p->main_thread->tf->es = p->main_thread->tf->ds;
     p->main_thread->tf->ss = p->main_thread->tf->ds;
     p->main_thread->tf->eflags = FL_IF;
 }
References FL_IF, p, SEG_KCODE, and SEG_KDATA.
Referenced by kthread_setup_regs().
trap_return()
void trap_return ()