oneOS: libs/libcxx/malloc.h File Reference
malloc.h File Reference
#include <libc/malloc.h>
Typedefs
typedef unsigned long size_t
Functions
void * operator new (size_t size)
void operator delete (void *ptr)
void operator delete (void *ptr, size_t)
void * operator new[] (size_t size)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, size_t)
void * operator new (size_t, void *ptr)
void * operator new[] (size_t, void *ptr)
template<class T , class... Args>
T & create (Args &&... args)
Typedef Documentation
size_t
typedef unsigned long size_t
Definition at line 7 of file malloc.h.
Function Documentation
create()
template<class T , class... Args> T& create (Args &&... args) inline
Definition at line 50 of file malloc.h.
 {
     T* newobject = new T(args...);
     return *newobject;
 }
References __main__::args.
operator delete() [1/2]
void operator delete (void * ptr) inline
Definition at line 14 of file malloc.h.
 {
     return free(ptr);
 }
References free().
operator delete() [2/2]
void operator delete (void * ptr, size_t) inline
Definition at line 19 of file malloc.h.
 {
     return free(ptr);
 }
References free().
operator delete[]() [1/2]
void operator delete[] (void * ptr) inline
Definition at line 29 of file malloc.h.
 {
     return free(ptr);
 }
References free().
operator delete[]() [2/2]
void operator delete[] (void * ptr, size_t) inline
Definition at line 34 of file malloc.h.
 {
     return free(ptr);
 }
References free().
operator new() [1/2]
void* operator new (size_t size) inline
Definition at line 9 of file malloc.h.
 {
     return malloc(size);
 }
References malloc().
operator new() [2/2]
void* operator new (size_t , void * ptr) inline
Definition at line 39 of file malloc.h.
 {
     return ptr;
 }
operator new[]() [1/2]
void* operator new[] (size_t size) inline
Definition at line 24 of file malloc.h.
 {
     return malloc(size);
 }
References malloc().
operator new[]() [2/2]
void* operator new[] (size_t , void * ptr) inline
Definition at line 44 of file malloc.h.
 {
     return ptr;
 }