oneOS: libs/libc/stdio.h File Reference
stdio.h File Reference
#include <sys/types.h>
Data Structures
struct __file
Macros
#define MAX_OPENED_FILES 16
#define STDIO_BUFFER_SIZE 16
Typedefs
typedef struct __file FILE
Functions
int fclose (FILE *stream)
FILE * fopen (const char *filename, const char *mode)
size_t fread (void *ptr, size_t size, size_t nmemb, FILE *stream)
size_t fwrite (const void *ptr, size_t size, size_t nmemb, FILE *stream)
int fseek (FILE *stream, uint32_t offset, int whence)
Variables
FILE opened_files [16]
Macro Definition Documentation
MAX_OPENED_FILES
#define MAX_OPENED_FILES 16
Definition at line 6 of file stdio.h.
STDIO_BUFFER_SIZE
#define STDIO_BUFFER_SIZE 16
Definition at line 7 of file stdio.h.
Typedef Documentation
FILE
typedef struct __file FILE
Definition at line 1 of file stdio.h.
Function Documentation
fclose()
int fclose (FILE * stream)
fopen()
FILE* fopen (const char * filename, const char * mode)
Definition at line 17 of file stdio.c.
 {
     size_t free_slot = _find_free_slot();
     if (free_slot == -1) {
         return 0;
     }
     opened_files[free_slot]._fileno = open(filename, 1);
     return &opened_files[free_slot];
 }
References __file::_fileno, _find_free_slot(), fat16_formatter::filename, open(), and opened_files.
fread()
size_t fread (void * ptr, size_t size, size_t nmemb, FILE * stream)
Definition at line 31 of file stdio.c.
 {
     return read(stream->_fileno, ptr, size);
 }
References __file::_fileno, and read().
fseek()
int fseek (FILE * stream, uint32_t offset, int whence)
Definition at line 27 of file stdio.c.
 {
 }
fwrite()
size_t fwrite (const void * ptr, size_t size, size_t nmemb, FILE * stream)
Variable Documentation
opened_files
FILE opened_files[16]
Definition at line 20 of file stdio.h.
Referenced by _find_free_slot(), and fopen().