oneOS: libs/libc/termios.h File Reference
termios.h File Reference
#include <sys/_structs.h>
#include <sys/types.h>
Data Structures
struct termios
Macros
#define NCCS 32
#define VINTR 0
#define VQUIT 1
#define VERASE 2
#define VKILL 3
#define VEOF 4
#define VTIME 5
#define VMIN 6
#define VSWTC 7
#define VSTART 8
#define VSTOP 9
#define VSUSP 10
#define VEOL 11
#define VREPRINT 12
#define VDISCARD 13
#define VWERASE 14
#define VLNEXT 15
#define VEOL2 16
#define ISIG 0000001
#define ICANON 0000002
#define ECHO 0000010
#define ECHOE 0000020
#define ECHOK 0000040
#define ECHONL 0000100
#define NOFLSH 0000200
#define TOSTOP 0000400
#define IEXTEN 0100000
#define TCOOFF 0
#define TCOON 1
#define TCIOFF 2
#define TCION 3
#define TCIFLUSH 0
#define TCOFLUSH 1
#define TCIOFLUSH 2
#define TCSANOW 0
#define TCSADRAIN 1
#define TCSAFLUSH 2
Typedefs
typedef unsigned char cc_t
typedef unsigned int speed_t
typedef unsigned int tcflag_t
typedef struct termios termios_t
Functions
int tcgetattr (int fd, termios_t *termios_p)
int tcsetattr (int fd, int optional_actions, const termios_t *termios_p)
Macro Definition Documentation
ECHO
#define ECHO 0000010
Definition at line 43 of file termios.h.
ECHOE
#define ECHOE 0000020
Definition at line 44 of file termios.h.
ECHOK
#define ECHOK 0000040
Definition at line 45 of file termios.h.
ECHONL
#define ECHONL 0000100
Definition at line 46 of file termios.h.
ICANON
#define ICANON 0000002
Definition at line 42 of file termios.h.
IEXTEN
#define IEXTEN 0100000
Definition at line 49 of file termios.h.
ISIG
#define ISIG 0000001
Definition at line 41 of file termios.h.
NCCS
#define NCCS 32
Definition at line 11 of file termios.h.
NOFLSH
#define NOFLSH 0000200
Definition at line 47 of file termios.h.
TCIFLUSH
#define TCIFLUSH 0
Definition at line 58 of file termios.h.
TCIOFF
#define TCIOFF 2
Definition at line 54 of file termios.h.
TCIOFLUSH
#define TCIOFLUSH 2
Definition at line 60 of file termios.h.
TCION
#define TCION 3
Definition at line 55 of file termios.h.
TCOFLUSH
#define TCOFLUSH 1
Definition at line 59 of file termios.h.
TCOOFF
#define TCOOFF 0
Definition at line 52 of file termios.h.
TCOON
#define TCOON 1
Definition at line 53 of file termios.h.
TCSADRAIN
#define TCSADRAIN 1
Definition at line 64 of file termios.h.
TCSAFLUSH
#define TCSAFLUSH 2
Definition at line 65 of file termios.h.
TCSANOW
#define TCSANOW 0
Definition at line 63 of file termios.h.
TOSTOP
#define TOSTOP 0000400
Definition at line 48 of file termios.h.
VDISCARD
#define VDISCARD 13
Definition at line 35 of file termios.h.
VEOF
#define VEOF 4
Definition at line 26 of file termios.h.
VEOL
#define VEOL 11
Definition at line 33 of file termios.h.
VEOL2
#define VEOL2 16
Definition at line 38 of file termios.h.
VERASE
#define VERASE 2
Definition at line 24 of file termios.h.
VINTR
#define VINTR 0
Definition at line 22 of file termios.h.
VKILL
#define VKILL 3
Definition at line 25 of file termios.h.
VLNEXT
#define VLNEXT 15
Definition at line 37 of file termios.h.
VMIN
#define VMIN 6
Definition at line 28 of file termios.h.
VQUIT
#define VQUIT 1
Definition at line 23 of file termios.h.
VREPRINT
#define VREPRINT 12
Definition at line 34 of file termios.h.
VSTART
#define VSTART 8
Definition at line 30 of file termios.h.
VSTOP
#define VSTOP 9
Definition at line 31 of file termios.h.
VSUSP
#define VSUSP 10
Definition at line 32 of file termios.h.
VSWTC
#define VSWTC 7
Definition at line 29 of file termios.h.
VTIME
#define VTIME 5
Definition at line 27 of file termios.h.
VWERASE
#define VWERASE 14
Definition at line 36 of file termios.h.
Typedef Documentation
cc_t
typedef unsigned char cc_t
Definition at line 7 of file termios.h.
speed_t
typedef unsigned int speed_t
Definition at line 8 of file termios.h.
tcflag_t
typedef unsigned int tcflag_t
Definition at line 9 of file termios.h.
termios_t
typedef struct termios termios_t
Definition at line 9 of file termios.h.
Function Documentation
tcgetattr()
int tcgetattr (int fd, termios_t * termios_p)
Definition at line 14 of file termios.c.
 {
     ioctl(0, TCGETS, (int)termios_p);
 }
References ioctl(), and TCGETS.
Referenced by enable_raw_mode().
tcsetattr()
int tcsetattr (int fd, int optional_actions, const termios_t * termios_p)
Definition at line 19 of file termios.c.
 {
     if (optional_actions == TCSANOW) {
         return ioctl(0, TCSETS, (int)termios_p);
     }
     if (optional_actions == TCSADRAIN) {
         return ioctl(0, TCSETSW, (int)termios_p);
     }
     if (optional_actions == TCSAFLUSH) {
         return ioctl(0, TCSETSF, (int)termios_p);
     }
     return -1;
 }
References ioctl(), TCSADRAIN, TCSAFLUSH, TCSANOW, TCSETS, TCSETSF, and TCSETSW.
Referenced by enable_raw_mode(), and restore_termios().