oneOS: userland/edit/lifetime.h File Reference
lifetime.h File Reference
#include "viewer.h"
#include <termios.h>
Functions
void enable_raw_mode ()
void restore_termios ()
void exit_app ()
void crash_app ()
Variables
struct termios orig_term
Function Documentation
crash_app()
void crash_app ()
Definition at line 28 of file lifetime.c.
 {
     restore_termios();
     exit(1);
 }
References exit(), and restore_termios().
Referenced by get_key().
enable_raw_mode()
void enable_raw_mode ()
Definition at line 8 of file lifetime.c.
 {
     struct termios raw;
     tcgetattr(STDIN, &raw);
     orig_term = raw;
     raw.c_lflag &= ~(ECHO | ICANON);
     tcsetattr(STDIN, TCSAFLUSH, &raw);
 }
References termios::c_lflag, ECHO, ICANON, orig_term, STDIN, tcgetattr(), TCSAFLUSH, and tcsetattr().
Referenced by main().
exit_app()
void exit_app ()
Definition at line 22 of file lifetime.c.
 {
     restore_termios();
     exit(0);
 }
References exit(), and restore_termios().
Referenced by main(), and menu_run_cmd().
restore_termios()
void restore_termios ()
Definition at line 17 of file lifetime.c.
 {
     tcsetattr(STDIN, TCSAFLUSH, &orig_term);
 }
References orig_term, STDIN, TCSAFLUSH, and tcsetattr().
Referenced by crash_app(), and exit_app().
Variable Documentation
orig_term
struct termios orig_term extern
Definition at line 1 of file lifetime.c.
Referenced by enable_raw_mode(), and restore_termios().