oneOS: src/kernel/io/sockets/local_socket.c File Reference
local_socket.c File Reference
#include <drivers/x86/display.h>
#include <errno.h>
#include <io/sockets/local_socket.h>
#include <log.h>
#include <tasking/proc.h>
#include <tasking/tasking.h>
Functions
int local_socket_create (int type, int protocol, file_descriptor_t *fd)
bool local_socket_can_read (dentry_t *dentry, uint32_t start)
int local_socket_read (dentry_t *dentry, uint8_t *buf, uint32_t start, uint32_t len)
bool local_socket_can_write (dentry_t *dentry, uint32_t start)
int local_socket_write (dentry_t *dentry, uint8_t *buf, uint32_t start, uint32_t len)
int local_socket_bind (file_descriptor_t *sock, char *name, uint32_t len)
int local_socket_connect (file_descriptor_t *sock, char *name, uint32_t len)
Variables
static file_ops_t local_socket_ops
Function Documentation
local_socket_bind()
int local_socket_bind (file_descriptor_t * sock, char * name, uint32_t len)
Definition at line 68 of file local_socket.c.
 {
     proc_t* p = RUNNIG_THREAD->process;
     uint32_t file_mode = S_IFSOCK | S_IRUSR | S_IXUSR | S_IRGRP | S_IXGRP | S_IROTH | S_IXOTH;
     vfs_create(p->cwd, name, len, file_mode);
     dentry_t* bind_dentry;
     int res = vfs_resolve_path_start_from(p->cwd, name, &bind_dentry);
     if (res < 0) {
 #ifdef LOCAL_SOCKET_DEBUG
         log_error("Bind: can't find path to file : %d pid\n", p->pid);
 #endif
         return res;
     }
     res = vfs_open(bind_dentry, &sock->sock_entry->bind_file, O_RDONLY);
     if (res < 0) {
 #ifdef LOCAL_SOCKET_DEBUG
         log_error("Bind: can't open file : %d pid\n", p->pid);
 #endif
         return res;
     }
 #ifdef LOCAL_SOCKET_DEBUG
     log("Bind local socket at %x : %d pid", sock->sock_entry, p->pid);
 #endif
     sock->sock_entry->bind_file.dentry->sock = socket_duplicate(sock->sock_entry);
     return 0;
 }
References socket::bind_file, file_descriptor::dentry, log(), log_error(), copy_bin::name, O_RDONLY, p, RUNNIG_THREAD, S_IFSOCK, S_IRGRP, S_IROTH, S_IRUSR, S_IXGRP, S_IXOTH, S_IXUSR, dentry::sock, file_descriptor::sock_entry, socket_duplicate(), vfs_create(), vfs_open(), and vfs_resolve_path_start_from().
Referenced by sys_bind().
local_socket_can_read()
bool local_socket_can_read (dentry_t * dentry, uint32_t start)
Definition at line 40 of file local_socket.c.
 {
     socket_t* sock_entry = (socket_t*)dentry;
     return ringbuffer_space_to_read_with_custom_start(&sock_entry->buffer, start) != 0;
 }
References socket::buffer, and ringbuffer_space_to_read_with_custom_start().
local_socket_can_write()
bool local_socket_can_write (dentry_t * dentry, uint32_t start)
Definition at line 56 of file local_socket.c.
 {
     return true;
 }
local_socket_connect()
int local_socket_connect (file_descriptor_t * sock, char * name, uint32_t len)
Definition at line 96 of file local_socket.c.
 {
     proc_t* p = RUNNIG_THREAD->process;
     dentry_t* bind_dentry;
     int res = vfs_resolve_path_start_from(p->cwd, name, &bind_dentry);
     if (res < 0) {
 #ifdef LOCAL_SOCKET_DEBUG
         log_error("Connect: can't find path to file : %d pid\n", p->pid);
 #endif
         return res;
     }
     if ((bind_dentry->inode->mode & S_IFSOCK) == 0) {
 #ifdef LOCAL_SOCKET_DEBUG
         log_error("Connect: file not a socket : %d pid\n", p->pid);
 #endif
         return -ENOTSOCK;
     }
     if (!bind_dentry->sock) {
         return -EBADF;
     }
     sock->sock_entry = socket_duplicate(bind_dentry->sock);
     sock->offset = bind_dentry->sock->buffer.end; /* Starting to read from the end */
 #ifdef LOCAL_SOCKET_DEBUG
     log("Connected to local socket at %x : %d pid", bind_dentry->sock, p->pid);
 #endif
     return 0;
 }
References socket::buffer, EBADF, __ringbuffer::end, ENOTSOCK, dentry::inode, log(), log_error(), inode_t::mode, copy_bin::name, file_descriptor::offset, p, RUNNIG_THREAD, S_IFSOCK, dentry::sock, file_descriptor::sock_entry, socket_duplicate(), and vfs_resolve_path_start_from().
Referenced by sys_connect().
local_socket_create()
int local_socket_create (int type, int protocol, file_descriptor_t * fd)
Definition at line 35 of file local_socket.c.
 {
     return socket_create(PF_LOCAL, type, protocol, fd, &local_socket_ops);
 }
References local_socket_ops, PF_LOCAL, socket_create(), and type.
Referenced by sys_socket().
local_socket_read()
int local_socket_read (dentry_t * dentry, uint8_t * buf, uint32_t start, uint32_t len)
Definition at line 46 of file local_socket.c.
 {
     socket_t* sock_entry = (socket_t*)dentry;
     uint32_t read = ringbuffer_read_with_start(&sock_entry->buffer, start, buf, len);
     return read;
 }
References buf, socket::buffer, read(), and ringbuffer_read_with_start().
local_socket_write()
int local_socket_write (dentry_t * dentry, uint8_t * buf, uint32_t start, uint32_t len)
Definition at line 61 of file local_socket.c.
 {
     socket_t* sock_entry = (socket_t*)dentry;
     uint32_t written = ringbuffer_write_ignore_bounds(&sock_entry->buffer, buf, len);
     return 0;
 }
References buf, socket::buffer, and ringbuffer_write_ignore_bounds().
Variable Documentation
local_socket_ops
file_ops_t local_socket_ops static
Initial value:
= {
    .can_read = local_socket_can_read,
    .can_write = local_socket_can_write,
    .read = local_socket_read,
    .write = local_socket_write,
    .open = 0,
    .truncate = 0,
    .create = 0,
    .unlink = 0,
    .getdents = 0,
    .lookup = 0,
    .mkdir = 0,
    .rmdir = 0,
    .ioctl = 0,
    .mmap = 0,
}
Definition at line 18 of file local_socket.c.
Referenced by local_socket_create().