oneOS: include/utils/mem.h File Reference
mem.h File Reference
#include <types.h>
Functions
void memmove (uint8_t *dest, const uint8_t *src, uint32_t nbytes)
void memset (uint8_t *dest, uint8_t fll, uint32_t nbytes)
void memcpy (uint8_t *dest, const uint8_t *src, uint32_t nbytes)
int memcmp (const uint8_t *src1, const uint8_t *src2, uint32_t nbytes)
void memccpy (uint8_t *dest, const uint8_t *src, uint8_t stop, uint32_t nbytes)
char * kmem_bring_to_kernel (const char *data, uint32_t size)
char ** kmem_bring_to_kernel_ptrarr (const char **data, uint32_t size)
Function Documentation
kmem_bring_to_kernel()
char* kmem_bring_to_kernel (const char * data, uint32_t size)
Definition at line 55 of file mem.c.
 {
     char* kdata = kmalloc(size);
     if (kdata) {
         memcpy(kdata, data, size);
     }
     return kdata;
 }
References kmalloc(), and memcpy().
Referenced by kmem_bring_to_kernel_ptrarr(), proc_chdir(), sys_creat(), sys_mkdir(), sys_open(), sys_rmdir(), sys_unlink(), and tasking_exec().
kmem_bring_to_kernel_ptrarr()
char** kmem_bring_to_kernel_ptrarr (const char ** data, uint32_t size)
Definition at line 64 of file mem.c.
 {
     char** res = kmalloc(size * sizeof(char*));
     for (int i = 0; i < size; i++) {
         res[i] = kmem_bring_to_kernel(data[i], strlen(data[i]) + 1);
     }
     return res;
 }
References kmalloc(), kmem_bring_to_kernel(), and strlen().
Referenced by tasking_exec().
memccpy()
void memccpy (uint8_t * dest, const uint8_t * src, uint8_t stop, uint32_t nbytes)
Definition at line 30 of file string.c.
 {
     for (int i = 0; i < nbytes; ++i) {
         if (*(src + i) == stop) {
             return;
         }
         *(dest + i) = *(src + i);
     }
 }
memcmp()
int memcmp (const uint8_t * src1, const uint8_t * src2, uint32_t nbytes)
Definition at line 40 of file string.c.
 {
     for (int i = 0; i < nbytes; ++i) {
         if (*(src1 + i) < *(src2 + i)) {
             return -1;
         }
         if (*(src1 + i) > *(src2 + i)) {
             return 1;
         }
     }
     return 0;
 }
Referenced by _is_cmd_internal(), LG::PNG::PNGLoader::check_header(), elf_load(), LG::Font::load_from_mem(), main(), and LG::PNG::PNGLoader::read_chunk().
memcpy()
void memcpy (uint8_t * dest, const uint8_t * src, uint32_t nbytes)
Definition at line 23 of file string.c.
 {
     for (int i = 0; i < nbytes; ++i) {
         *(dest + i) = *(src + i);
     }
 }
Referenced by _cmd_processor(), _devfs_set_name(), _ext2_add_first_entry_to_dir_block(), _ext2_add_to_dir_block(), _ext2_getdents_block(), _ext2_getdirent_block(), _signal_init_caller(), _vmm_copy_page_to_resolve_cow(), _vmm_resolve_copy_on_write(), cmd_register(), devfs_getdents(), devfs_read_inode(), devfs_register(), devfs_write_inode(), dynamic_array_push(), fpu_reset_state(), krealloc(), main(), Algo::String::operator+=(), Algo::String::operator=(), LG::PixelBitmap::operator=(), LG::PixelBitmap::PixelBitmap(), proc_copy_of(), ClientConnection< ServerDecoder, ClientDecoder >::pump_messages(), ServerConnection< ServerDecoder, ClientDecoder >::pump_messages(), LG::PNG::DataStreamer::read(), realloc(), scroll(), signal_setup_stack_to_handle_signal(), Algo::String::String(), thread_fill_up_stack(), tty_ioctl(), vmm_bring_to_kernel(), vmm_copy_page(), and vmm_copy_to_pdir().
memmove()
void memmove (uint8_t * dest, const uint8_t * src, uint32_t nbytes)
Definition at line 10 of file string.c.
 {
     if (src > dest) {
         for (int i = 0; i < nbytes; ++i) {
             *(dest + i) = *(src + i);
         }
     } else {
         for (int i = nbytes - 1; i >= 0; --i) {
             *(dest + i) = *(src + i);
         }
     }
 }
Referenced by file_paste_char(), and TerminalView::scroll_line().
memset()
void memset (uint8_t * dest, uint8_t fll, uint32_t nbytes)
Definition at line 3 of file string.c.
 {
     for (int i = 0; i < nbytes; ++i) {
         *(dest + i) = fll;
     }
 }
Referenced by _devfs_new_name(), _devfs_setup_root(), _ext2_add_first_entry_to_dir_block(), _ext2_add_to_dir_block(), _init_cpus(), _kmalloc_init_bitmap(), _shared_buffer_init_bitmap(), _thread_setup_kstack(), _vmm_resolve_zeroing_on_demand(), _vmm_split_pspace(), calloc(), dentry_cache_alloc(), fourfiles(), kthread_setup(), proc_setup(), read(), TerminalView::recalc_dimensions(), TerminalView::scroll_line(), thread_fill_up_stack(), thread_setup(), thread_setup_main(), vmm_allocate_ptable(), vmm_load_page(), and zoner_place_bitmap().