oneOS: userland/mmaptest/main.c File Reference
main.c File Reference
#include <syscalls.h>
Macros
#define BUF_SIZE 512
Functions
void cat (int fd)
int main (int argc, char **argv)
Variables
char buf [512]
Macro Definition Documentation
BUF_SIZE
#define BUF_SIZE 512
Definition at line 3 of file main.c.
Function Documentation
cat()
void cat (int fd)
Definition at line 6 of file main.c.
 {
     int n = 0;
     while ((n = read(fd, buf, sizeof(buf))) > 0) {
         if (write(1, buf, n) != n) {
             exit(1);
         }
     }
 }
References buf, exit(), read(), and write().
main()
int main (int argc, char ** argv)
Definition at line 16 of file main.c.
 {
     int fd, i;
     if (argc <= 1) {
         cat(0);
         return 0;
     }
     fd = open(argv[1], 0);
     if (fd < 0) {
         return 1;
     }
     mmap_params_t mp;
     mp.flags = MAP_PRIVATE;
     mp.fd = fd;
     mp.size = 4096;
     mp.prot = PROT_READ;
     char* file = (char*)mmap(&mp);
     if (file) {
         write(1, file, 30);
     }
     if (close(fd) == 0) {
         write(1, "s", 1);
         return 1;
     }
     return 0;
 }
References cat(), close(), mmap_params::fd, mmap_params::flags, MAP_PRIVATE, mmap(), open(), mmap_params::prot, PROT_READ, mmap_params::size, and write().
Variable Documentation
buf
char buf[512]
Definition at line 4 of file main.c.