oneOS: include/drivers/x86/mouse.h File Reference
mouse.h File Reference
#include <types.h>
#include <drivers/x86/ata.h>
#include <platform/x86/idt.h>
Data Structures
struct mouse_packet
Typedefs
typedef struct mouse_packet mouse_packet_t
Functions
bool mouse_install ()
Typedef Documentation
mouse_packet_t
typedef struct mouse_packet mouse_packet_t
Definition at line 1 of file mouse.h.
Function Documentation
mouse_install()
bool mouse_install ()
Definition at line 171 of file mouse.c.
 {
     driver_install(_mouse_driver_info());
     return true;
 }
References _mouse_driver_info(), and driver_install().
Referenced by stage3().