oneOS: src/kernel/drivers/x86/mouse.c File Reference
mouse.c File Reference
#include <algo/ringbuffer.h>
#include <drivers/x86/display.h>
#include <drivers/driver_manager.h>
#include <drivers/x86/mouse.h>
#include <fs/devfs/devfs.h>
#include <log.h>
#include <types.h>
#include <utils/kassert.h>
#include <platform/x86/idt.h>
#include <platform/x86/port.h>
Functions
void mouse_run ()
static bool _mouse_can_read (dentry_t *dentry, uint32_t start)
static int _mouse_read (dentry_t *dentry, uint8_t *buf, uint32_t start, uint32_t len)
static void _mouse_recieve_notification (uint32_t msg, uint32_t param)
static driver_desc_t _mouse_driver_info ()
static void _mouse_wait_in ()
static void _mouse_wait_out ()
static uint8_t _mouse_wait_then_write (uint16_t port, uint8_t data)
static uint8_t _mouse_wait_then_read (uint16_t port)
static void _mouse_send_cmd (uint8_t cmd)
static void _mouse_enable_aux ()
void mouse_handler ()
bool mouse_install ()
Variables
static ringbuffer_t mouse_buffer
Function Documentation
_mouse_can_read()
static bool _mouse_can_read (dentry_t * dentry, uint32_t start) static
Definition at line 18 of file mouse.c.
 {
     return ringbuffer_space_to_read(&mouse_buffer) >= 1;
 }
References mouse_buffer, and ringbuffer_space_to_read().
Referenced by _mouse_recieve_notification().
_mouse_driver_info()
static driver_desc_t _mouse_driver_info () static
Definition at line 55 of file mouse.c.
 {
     driver_desc_t desc;
     desc.type = DRIVER_INPUT_SYSTEMS_DEVICE;
     desc.auto_start = true;
     desc.is_device_driver = false;
     desc.is_device_needed = false;
     desc.is_driver_needed = false;
     desc.functions[DRIVER_NOTIFICATION] = _mouse_recieve_notification;
     desc.functions[DRIVER_INPUT_SYSTEMS_ADD_DEVICE] = mouse_run;
     desc.functions[DRIVER_INPUT_SYSTEMS_GET_LAST_KEY] = 0;
     desc.functions[DRIVER_INPUT_SYSTEMS_DISCARD_LAST_KEY] = 0;
     desc.pci_serve_class = 0xff;
     desc.pci_serve_subclass = 0xff;
     desc.pci_serve_vendor_id = 0x00;
     desc.pci_serve_device_id = 0x00;
     return desc;
 }
References _mouse_recieve_notification(), driver_desc_t::auto_start, DRIVER_INPUT_SYSTEMS_ADD_DEVICE, DRIVER_INPUT_SYSTEMS_DEVICE, DRIVER_INPUT_SYSTEMS_DISCARD_LAST_KEY, DRIVER_INPUT_SYSTEMS_GET_LAST_KEY, DRIVER_NOTIFICATION, driver_desc_t::functions, driver_desc_t::is_device_driver, driver_desc_t::is_device_needed, driver_desc_t::is_driver_needed, mouse_run(), driver_desc_t::pci_serve_class, driver_desc_t::pci_serve_device_id, driver_desc_t::pci_serve_subclass, driver_desc_t::pci_serve_vendor_id, and driver_desc_t::type.
Referenced by mouse_install().
_mouse_enable_aux()
static void _mouse_enable_aux () inline static
Definition at line 103 of file mouse.c.
 {
     _mouse_wait_then_write(0x64, 0x20);
     uint8_t res = _mouse_wait_then_read(0x60);
     res |= 0b10;
     res &= 0b11011111;
     _mouse_wait_then_write(0x64, 0x60);
     _mouse_wait_then_write(0x60, res);
 }
References _mouse_wait_then_read(), and _mouse_wait_then_write().
Referenced by mouse_run().
_mouse_read()
static int _mouse_read (dentry_t * dentry, uint8_t * buf, uint32_t start, uint32_t len) static
Definition at line 23 of file mouse.c.
 {
     uint32_t leno = ringbuffer_space_to_read(&mouse_buffer);
     if (leno > len) {
         leno = len;
     }
     int res = ringbuffer_read(&mouse_buffer, buf, leno);
     return leno;
 }
References buf, mouse_buffer, ringbuffer_read(), and ringbuffer_space_to_read().
Referenced by _mouse_recieve_notification().
_mouse_recieve_notification()
static void _mouse_recieve_notification (uint32_t msg, uint32_t param) static
Definition at line 33 of file mouse.c.
 {
     if (msg == DM_NOTIFICATION_DEVFS_READY) {
         dentry_t* mp;
         if (vfs_resolve_path("/dev", &mp) < 0) {
             kpanic("Can't init mouse in /dev");
         }
         file_ops_t fops;
         fops.open = 0;
         fops.can_read = _mouse_can_read;
         fops.can_write = 0;
         fops.read = _mouse_read;
         fops.write = 0;
         fops.ioctl = 0;
         fops.mmap = 0;
         devfs_inode_t* res = devfs_register(mp, "mouse", 5, 0, &fops);
         dentry_put(mp);
     }
 }
References _mouse_can_read(), _mouse_read(), file_ops::can_read, file_ops::can_write, dentry_put(), devfs_register(), DM_NOTIFICATION_DEVFS_READY, file_ops::ioctl, kpanic(), file_ops::mmap, file_ops::open, file_ops::read, vfs_resolve_path(), and file_ops::write.
Referenced by _mouse_driver_info().
_mouse_send_cmd()
static void _mouse_send_cmd (uint8_t cmd) inline static
Definition at line 96 of file mouse.c.
 {
     _mouse_wait_then_write(0x64, 0xD4);
     _mouse_wait_then_write(0x60, cmd);
     ASSERT(_mouse_wait_then_read(0x60) == 0xfa);
 }
References _mouse_wait_then_read(), _mouse_wait_then_write(), ASSERT, and cmd.
Referenced by mouse_run().
_mouse_wait_in()
static void _mouse_wait_in () inline static
Definition at line 74 of file mouse.c.
 {
     while (port_8bit_in(0x64) & 1 == 0) { }
 }
References port_8bit_in().
Referenced by _mouse_wait_then_read().
_mouse_wait_out()
static void _mouse_wait_out () inline static
Definition at line 79 of file mouse.c.
 {
     while (port_8bit_in(0x64) & 2 == 0) { }
 }
References port_8bit_in().
Referenced by _mouse_wait_then_write().
_mouse_wait_then_read()
static uint8_t _mouse_wait_then_read (uint16_t port) inline static
Definition at line 90 of file mouse.c.
 {
     _mouse_wait_in();
     return port_8bit_in(port);
 }
References _mouse_wait_in(), and port_8bit_in().
Referenced by _mouse_enable_aux(), and _mouse_send_cmd().
_mouse_wait_then_write()
static uint8_t _mouse_wait_then_write (uint16_t port, uint8_t data) inline static
Definition at line 84 of file mouse.c.
 {
     _mouse_wait_out();
     port_8bit_out(port, data);
 }
References _mouse_wait_out(), and port_8bit_out().
Referenced by _mouse_enable_aux(), _mouse_send_cmd(), and mouse_run().
mouse_handler()
void mouse_handler ()
Definition at line 113 of file mouse.c.
 {
     uint8_t status = port_8bit_in(0x64);
     if ((status & 0x1) == 0 || (status & 0x20) != 0x20) {
         return;
     }
     uint8_t resp = port_8bit_in(0x60);
     uint8_t xm = port_8bit_in(0x60);
     uint8_t ym = port_8bit_in(0x60);
     uint8_t y_overflow = (resp >> 7) & 1;
     uint8_t x_overflow = (resp >> 6) & 1;
     uint8_t y_sign = (resp >> 5) & 1;
     uint8_t x_sign = (resp >> 4) & 1;
     mouse_packet_t packet;
     packet.x_offset = xm;
     packet.y_offset = ym;
     packet.button_states = resp & 0b111;
     if (packet.x_offset && x_sign) {
         packet.x_offset -= 0x100;
     }
     if (packet.y_offset && y_sign) {
         packet.y_offset -= 0x100;
     }
     if (x_overflow || y_overflow) {
         packet.x_offset = 0;
         packet.y_offset = 0;
     }
     ringbuffer_write(&mouse_buffer, (uint8_t*)&packet, sizeof(mouse_packet_t));
 #ifdef MOUSE_DRIVER_DEBUG
     if (packet.x_offset < 0) {
         log("-%d ", -packet.x_offset);
     } else {
         log("%d ", packet.x_offset);
     }
     if (packet.y_offset < 0) {
         log("-%d\n", -packet.y_offset);
     } else {
         log("%d\n", packet.y_offset);
     }
 #endif /* MOUSE_DRIVER_DEBUG */
 }
References mouse_packet::button_states, log(), mouse_buffer, port_8bit_in(), ringbuffer_write(), mouse_packet::x_offset, and mouse_packet::y_offset.
Referenced by mouse_run().
mouse_install()
bool mouse_install ()
Definition at line 171 of file mouse.c.
 {
     driver_install(_mouse_driver_info());
     return true;
 }
References _mouse_driver_info(), and driver_install().
Referenced by stage3().
mouse_run()
void mouse_run ()
Definition at line 160 of file mouse.c.
 {
     _mouse_wait_then_write(0x64, 0xa8);
     _mouse_enable_aux();
     _mouse_send_cmd(0xF6);
     _mouse_send_cmd(0xF4);
     set_irq_handler(IRQ12, mouse_handler);
     mouse_buffer = ringbuffer_create_std();
 }
References _mouse_enable_aux(), _mouse_send_cmd(), _mouse_wait_then_write(), IRQ12, mouse_buffer, mouse_handler(), ringbuffer_create_std(), and set_irq_handler().
Referenced by _mouse_driver_info().
Variable Documentation
mouse_buffer
ringbuffer_t mouse_buffer static
Definition at line 14 of file mouse.c.
Referenced by _mouse_can_read(), _mouse_read(), mouse_handler(), and mouse_run().