oneOS: __main__ Namespace Reference
__main__ Namespace Reference
Functions
def run (input_f, output_f)
Variables
parser = argparse.ArgumentParser()
type
str
help
args = parser.parse_args()
Function Documentation
run()
def __main__.run (input_f, output_f)
Definition at line 7 of file __main__.py.
 def run(input_f, output_f):
     code = []
     file = open(input_f, "r")
     for line in file:
         line = line.replace('\n', '')
         if len(line) > 0:
             code.append(line)
     parser = Parser()
     gen = Generator()
     parser.set_code_lines(code)
     gen.generate(output_f, parser.parse())
References open().
Variable Documentation
args
__main__.args = parser.parse_args()
Definition at line 27 of file __main__.py.
Referenced by _cmd_processor(), UI::View.add_subview(), create(), and UI::Window.create_superview().
help
__main__.help
Definition at line 24 of file __main__.py.
parser
__main__.parser = argparse.ArgumentParser()
Definition at line 23 of file __main__.py.
str
__main__.str
Definition at line 24 of file __main__.py.
Referenced by _log_string(), dtos(), htos(), menu_run_cmd(), stoi(), and Algo::String.String().
type
__main__.type
Definition at line 24 of file __main__.py.