oneOS: fat16_formatter Namespace Reference
fat16_formatter Namespace Reference
Functions
def open_file ()
def write_file (dd, withPos=0)
def merge (res, plus, offset)
def test_id ()
def bytes_per_sector ()
def sectors_per_cluster ()
def number_of_fats ()
def root_entires ()
def load_kernel ()
def reserved_sectors ()
def volume_label ()
def system_id ()
def header ()
def fat_size ()
def sectors_per_fat ()
def fat ()
def root_dir ()
def print_gh (el)
def print_g (result)
Variables
filename = format_settings['filename']
dictionary file_descriptor
int pos = 0
def header_e = header()
def fat_e = fat()
def root_dir_e = root_dir()
Function Documentation
bytes_per_sector()
def fat16_formatter.bytes_per_sector ()
Definition at line 41 of file fat16_formatter.py.
 def bytes_per_sector():
     result = bytearray(2)
     result[0] = format_settings['BytesPerSector'] % 256
     result[1] = format_settings['BytesPerSector'] // 256
     return result
Referenced by header().
fat()
def fat16_formatter.fat ()
Definition at line 131 of file fat16_formatter.py.
 def fat():
     fsize = fat_size()
     print(fsize)
     result = bytearray(512 * fsize)
     result[0] = 0xf8
     result[1] = 0xff
     result[2] = 0xff
     result[3] = 0xff
     root_dir_sectors = (format_settings['RootEntires'] * 32) // 512
     load_sectors = format_settings['ReservedSectors']
     data_sectors = file_descriptor['size'] // 512 - root_dir_sectors - load_sectors
     free_data_sectors = data_sectors - fsize * format_settings['NumberOfFATs']
     covered_data_clusters = fsize * 512 // 2 - 2
     data_clusters = (free_data_sectors - format_settings['SectorPerClustor'] + 1) // format_settings['SectorPerClustor'] + 1
     unused_clusters = covered_data_clusters - data_clusters
     print(covered_data_clusters, data_clusters, unused_clusters)
     if unused_clusters < 0:
         print("Error with clusters")
         exit(0)
     for i in range(unused_clusters):
         result[512 * fsize - 2 * unused_clusters + 2 * i] = 0xff
         result[512 * fsize - 2 * unused_clusters + 2 * i + 1] = 0xff
     print_g(result)
     return result
References exit(), fat_size(), and print_g().
fat_size()
def fat16_formatter.fat_size ()
Definition at line 109 of file fat16_formatter.py.
 def fat_size():
     if (format_settings['RootEntires'] * 32) % 512 != 0:
         print("RootEntires error [couldn't fit into sectors]")
         exit(0)
     root_dir_sectors = (format_settings['RootEntires'] * 32) // 512
     load_sectors = format_settings['ReservedSectors']
     data_sectors = file_descriptor['size'] // 512 - root_dir_sectors - load_sectors
     for fat_sectors in range(1, 256):
         free_data_sectors = data_sectors - fat_sectors * format_settings['NumberOfFATs']
         covered_data_sectors = fat_sectors * 512 // 2 - 2
         print(free_data_sectors, covered_data_sectors)
         if free_data_sectors <= format_settings['SectorPerClustor'] * covered_data_sectors:
             return fat_sectors
     return 256
References exit().
Referenced by fat(), and sectors_per_fat().
header()
def fat16_formatter.header ()
Definition at line 93 of file fat16_formatter.py.
 def header():
     result = bytearray(512)
     result = merge(result, test_id(), 0x3)
     result = merge(result, bytes_per_sector(), 0xB)
     result = merge(result, sectors_per_cluster(), 0xD)
     result = merge(result, reserved_sectors(), 0xE)
     result = merge(result, number_of_fats(), 0x10)
     result = merge(result, root_entires(), 0x11)
     result = merge(result, sectors_per_fat(), 0x16)
     result = merge(result, volume_label(), 0x2B)
     result = merge(result, system_id(), 0x36)
     result[511] = 0x00
     result[510] = 0x00
     print_g(result)
     return result
References bytes_per_sector(), merge(), number_of_fats(), print_g(), reserved_sectors(), root_entires(), sectors_per_cluster(), sectors_per_fat(), system_id(), test_id(), and volume_label().
Referenced by elf_load(), LG::Font.load_from_mem(), LG::PNG::PNGLoader.read_chunk(), LG::PNG::PNGLoader.read_IDAT(), LG::PNG::PNGLoader.read_PHYS(), and LG::PNG::PNGLoader.read_TEXT().
load_kernel()
def fat16_formatter.load_kernel ()
Definition at line 63 of file fat16_formatter.py.
 def load_kernel():
     result = bytearray(2)
     result[0] = format_settings['ReservedSectors'] % 256
     result[1] = format_settings['ReservedSectors'] // 256
     return result
merge()
def fat16_formatter.merge (res, plus, offset)
Definition at line 29 of file fat16_formatter.py.
 def merge(res, plus, offset):
     for (id,el) in enumerate(plus):
         res[id + offset] = el
     return res
Referenced by header().
number_of_fats()
def fat16_formatter.number_of_fats ()
Definition at line 52 of file fat16_formatter.py.
 def number_of_fats():
     result = bytearray(1)
     result[0] = format_settings['NumberOfFATs'] % 256
     return result
Referenced by header().
open_file()
def fat16_formatter.open_file ()
Definition at line 14 of file fat16_formatter.py.
 def open_file():
     size = 0
     with open(filename, "rb") as f:
         byte = f.read(1)
         while byte != b"":
             size+=1
             byte = f.read(1)
     file_descriptor['size'] = size
References open().
Referenced by print_g().
print_g()
def fat16_formatter.print_g (result)
Definition at line 166 of file fat16_formatter.py.
 def print_g(result):
     for (id,el) in enumerate(result):
         if id % 16 == 0:
             print()
         print(print_gh(el//16), end="")
         print(print_gh(el%16), end=" ")
References open_file(), and print_gh().
Referenced by fat(), and header().
print_gh()
def fat16_formatter.print_gh (el)
Definition at line 161 of file fat16_formatter.py.
 def print_gh(el):
     if (el >= 10):
         return chr(el - 10 + ord('A'))
     return chr(el + ord('0'))
Referenced by print_g().
reserved_sectors()
def fat16_formatter.reserved_sectors ()
Definition at line 69 of file fat16_formatter.py.
 def reserved_sectors():
     result = bytearray(2)
     result[0] = format_settings['ReservedSectors'] % 256
     result[1] = format_settings['ReservedSectors'] // 256
     return result
Referenced by header().
root_dir()
def fat16_formatter.root_dir ()
Definition at line 157 of file fat16_formatter.py.
 def root_dir():
     result = bytearray(format_settings['RootEntires'] * 32)
     return result
root_entires()
def fat16_formatter.root_entires ()
Definition at line 57 of file fat16_formatter.py.
 def root_entires():
     result = bytearray(2)
     result[0] = format_settings['RootEntires'] % 256
     result[1] = format_settings['RootEntires'] // 256
     return result
Referenced by header().
sectors_per_cluster()
def fat16_formatter.sectors_per_cluster ()
Definition at line 47 of file fat16_formatter.py.
 def sectors_per_cluster():
     result = bytearray(1)
     result[0] = format_settings['SectorPerClustor'] % 256
     return result
Referenced by header().
sectors_per_fat()
def fat16_formatter.sectors_per_fat ()
Definition at line 124 of file fat16_formatter.py.
 def sectors_per_fat():
     fsize = fat_size()
     result = bytearray(2)
     result[0] = fsize % 256
     result[1] = fsize // 256
     return result
References fat_size().
Referenced by header().
system_id()
def fat16_formatter.system_id ()
Definition at line 84 of file fat16_formatter.py.
 def system_id():
     result = bytearray(8)
     for i in range(8):
         result[i] = 0x20
     textCode = 'FAT16'
     for (id,el) in enumerate(textCode):
         result[id] = ord(el)
     return result
Referenced by header().
test_id()
def fat16_formatter.test_id ()
Definition at line 34 of file fat16_formatter.py.
 def test_id():
     result = bytearray(8)
     textCode = 'oneOSToP'
     for (id,el) in enumerate(textCode):
         result[id] = ord(el)
     return result
Referenced by header().
volume_label()
def fat16_formatter.volume_label ()
Definition at line 75 of file fat16_formatter.py.
 def volume_label():
     result = bytearray(11)
     for i in range(11):
         result[i] = 0x20
     textCode = format_settings['VolumeName']
     for (id,el) in enumerate(textCode):
         result[id] = ord(el)
     return result
Referenced by header().
write_file()
def fat16_formatter.write_file (dd, withPos = 0)
Definition at line 24 of file fat16_formatter.py.
 def write_file(dd, withPos = 0):
     with open(filename, "rb+") as f:
         f.seek(withPos, 0)
         f.write(bytes(x for x in dd))
References open().
Variable Documentation
fat_e
def fat16_formatter.fat_e = fat()
Definition at line 192 of file fat16_formatter.py.
file_descriptor
dictionary fat16_formatter.file_descriptor
Initial value:
 =  {
     'name': filename,
     'size': 0, #(bytes)
 }
Definition at line 9 of file fat16_formatter.py.
filename
fat16_formatter.filename = format_settings['filename']
Definition at line 7 of file fat16_formatter.py.
Referenced by _ext2_add_first_entry_to_dir_block(), _ext2_add_to_dir_block(), and fopen().
header_e
def fat16_formatter.header_e = header()
Definition at line 184 of file fat16_formatter.py.
pos
int fat16_formatter.pos = 0
Definition at line 179 of file fat16_formatter.py.
root_dir_e
def fat16_formatter.root_dir_e = root_dir()
Definition at line 200 of file fat16_formatter.py.