oneOS: userland/onesh/main.c File Reference
main.c File Reference
#include <malloc.h>
#include <string.h>
#include <syscalls.h>
#include <pthread.h>
Enumerations
enum internal_cmd_code { CMD_NONE = 0 , CMD_CD }
Functions
uint32_t _is_cmd_internal ()
void _cmd_buffer_clear ()
void _cmd_loop ()
void _cmd_loop_start ()
void _cmd_loop_end ()
void _cmd_input ()
void _cmd_processor ()
char _cmd_is_ascii (uint32_t key)
char _cmd_cmp_command (const char *)
int16_t _cmd_find_cmd_handler ()
uint32_t _cmd_getkeycode ()
int _cmd_do_internal (uint32_t code)
int inter (int no)
int main ()
Variables
char * _cmd_app
char * _cmd_buffer
char ** _cmd_parsed_buffer
static int _cmd_buffer_position = 0
static int _cmd_parsed_buffer_position = 0
static int running_job = 0
Enumeration Type Documentation
internal_cmd_code
enum internal_cmd_code
Enumerator
CMD_NONE
CMD_CD
Definition at line 25 of file main.c.
{
     CMD_NONE = 0,
     CMD_CD,
 };
Function Documentation
_cmd_buffer_clear()
void _cmd_buffer_clear ()
Definition at line 46 of file main.c.
 {
     _cmd_buffer_position = 0;
 }
References _cmd_buffer_position.
Referenced by _cmd_loop_end().
_cmd_cmp_command()
char _cmd_cmp_command (const char * data)
Definition at line 25 of file cmd.c.
{
     uint8_t pos = 0;
     while (data[pos] != '\0') {
         if (data[pos] != _cmd_buffer[pos]) {
             return false;
         }
         pos++;
     }
     return (_cmd_buffer[pos] == ' ' || _cmd_buffer[pos] == '\0');
 }
References _cmd_buffer, and pos.
Referenced by _cmd_find_cmd_handler().
_cmd_do_internal()
int _cmd_do_internal (uint32_t code)
Definition at line 38 of file main.c.
 {
     if (code == CMD_CD) {
         return chdir(_cmd_parsed_buffer[1]);
     }
     return 0;
 }
References _cmd_parsed_buffer, chdir(), and CMD_CD.
Referenced by _cmd_processor().
_cmd_find_cmd_handler()
int16_t _cmd_find_cmd_handler ()
Definition at line 36 of file cmd.c.
{
     for (uint8_t i = 0; i < _cmd_redirects_registered; i++) {
         if (_cmd_cmp_command(_cmd_redirects[i].served_cmd)) {
             return i;
         }
     }
     return -1;
 }
References _cmd_cmp_command(), _cmd_redirects, and _cmd_redirects_registered.
Referenced by _cmd_processor().
_cmd_getkeycode()
uint32_t _cmd_getkeycode ()
Definition at line 122 of file cmd.c.
{
     uint32_t key = KEY_UNKNOWN;
     while (key == KEY_UNKNOWN) {
         key = kbdriver_get_last_key();
     }
     kbdriver_discard_last_key();
     return key;
 }
References kbdriver_discard_last_key(), kbdriver_get_last_key(), and KEY_UNKNOWN.
Referenced by _cmd_input().
_cmd_input()
void _cmd_input ()
Definition at line 61 of file main.c.
 {
     _cmd_buffer_position = read(0, _cmd_buffer, 256);
     _cmd_buffer[_cmd_buffer_position] = '\0';
 }
References _cmd_buffer, _cmd_buffer_position, and read().
Referenced by _cmd_loop().
_cmd_is_ascii()
char _cmd_is_ascii (uint32_t key)
Definition at line 122 of file main.c.
 {
     return 32 <= key && key <= 126;
 }
_cmd_loop()
void _cmd_loop ()
Definition at line 51 of file main.c.
 {
     while (1) {
         _cmd_loop_start();
         _cmd_input();
         _cmd_processor();
         _cmd_loop_end();
     }
 }
References _cmd_input(), _cmd_loop_end(), _cmd_loop_start(), and _cmd_processor().
Referenced by main().
_cmd_loop_end()
void _cmd_loop_end ()
Definition at line 116 of file main.c.
 {
     _cmd_buffer_clear();
     write(1, "\n", 1);
 }
References _cmd_buffer_clear(), and write().
Referenced by _cmd_loop().
_cmd_loop_start()
void _cmd_loop_start ()
Definition at line 111 of file main.c.
 {
     write(1, "> ", 2);
 }
References write().
Referenced by _cmd_loop().
_cmd_processor()
void _cmd_processor ()
Definition at line 67 of file main.c.
 {
     _cmd_parsed_buffer_position = 0;
     char is_prev_space = true;
     for (int i = 0; i < _cmd_buffer_position; i++) {
         if (_cmd_buffer[i] == ' ') {
             if (is_prev_space == false) {
                 /* null terminator when args are sent */
                 _cmd_buffer[i] = '\0';
             }
             is_prev_space = true;
         } else {
             if (is_prev_space) {
                 _cmd_parsed_buffer[_cmd_parsed_buffer_position++] = (char*)((char*)_cmd_buffer + i);
             }
             is_prev_space = false;
         }
     }
     _cmd_buffer[_cmd_buffer_position - 1] = '\0'; // remove \n
     _cmd_buffer[_cmd_buffer_position] = '\0';
     _cmd_parsed_buffer[_cmd_parsed_buffer_position] = 0;
     /* We try to launch an app */
     uint32_t cmd = _is_cmd_internal();
     if (cmd == CMD_NONE) {
         uint32_t namelen = strlen(_cmd_parsed_buffer[0]);
         memcpy(_cmd_app+5, _cmd_buffer, namelen + 1);
         int res = fork();
         if (!res) {
             execve(_cmd_app, _cmd_parsed_buffer, 0);
             exit(-1);
         } else {
             running_job = res;
             wait(res);
         }
     } else {
         _cmd_do_internal(cmd);
     }
 }
References _cmd_app, _cmd_buffer, _cmd_buffer_position, _cmd_do_internal(), _cmd_parsed_buffer, _cmd_parsed_buffer_position, _is_cmd_internal(), cmd, CMD_NONE, execve(), exit(), fork(), memcpy(), running_job, strlen(), and wait().
Referenced by _cmd_loop().
_is_cmd_internal()
uint32_t _is_cmd_internal ()
Definition at line 30 of file main.c.
 {
     if (memcmp(_cmd_buffer, "cd", 3) == 0) {
         return CMD_CD;
     }
     return CMD_NONE;
 }
References _cmd_buffer, CMD_CD, CMD_NONE, and memcmp().
Referenced by _cmd_processor().
inter()
int inter (int no)
Definition at line 127 of file main.c.
 {
     kill(running_job, 9);
     return 0;
 }
References kill(), and running_job.
Referenced by main().
main()
int main ()
Definition at line 133 of file main.c.
 {
     sigaction(3, inter);
     ioctl(0, TIOCSPGRP, getpgid(getpid()));
     ioctl(0, TIOCGPGRP, 0);
     _cmd_app = malloc(256);
     _cmd_buffer = malloc(256);
     _cmd_parsed_buffer = malloc(256 * sizeof(char*));
     memcpy(_cmd_app, "/bin/", 5);
     _cmd_loop();
     // while (1) {
     //     _cmd_buffer_position = read(0, _cmd_buffer, 256);
     //     _cmd_buffer[_cmd_buffer_position] = '\0';
     // }
     return 0;
 }
References _cmd_app, _cmd_buffer, _cmd_loop(), _cmd_parsed_buffer, getpgid(), getpid(), inter(), ioctl(), malloc(), memcpy(), sigaction(), TIOCGPGRP, and TIOCSPGRP.
Variable Documentation
_cmd_app
char* _cmd_app
Definition at line 6 of file main.c.
Referenced by _cmd_processor(), and main().
_cmd_buffer
char* _cmd_buffer
Definition at line 7 of file main.c.
Referenced by _cmd_input(), _cmd_processor(), _is_cmd_internal(), and main().
_cmd_buffer_position
int _cmd_buffer_position = 0 static
Definition at line 9 of file main.c.
Referenced by _cmd_buffer_clear(), _cmd_input(), and _cmd_processor().
_cmd_parsed_buffer
char** _cmd_parsed_buffer
Definition at line 8 of file main.c.
Referenced by _cmd_do_internal(), _cmd_processor(), and main().
_cmd_parsed_buffer_position
int _cmd_parsed_buffer_position = 0 static
Definition at line 10 of file main.c.
Referenced by _cmd_processor().
running_job
int running_job = 0 static
Definition at line 11 of file main.c.
Referenced by _cmd_processor(), and inter().