oneOS: src/kernel/drivers/x86/pci.c File Reference
pci.c File Reference
#include <drivers/x86/pci.h>
Functions
static driver_desc_t _pci_driver_info ()
static uint32_t _pci_do_read_bar (uint8_t bus, uint8_t device, uint8_t function, uint8_t bar_id)
static bar_t _pci_get_bar (uint8_t bus, uint8_t device, uint8_t function, uint8_t bar_id)
void pci_install ()
uint32_t pci_read (uint16_t bus, uint16_t device, uint16_t function, uint32_t offset)
void pci_write (uint8_t bus, uint8_t device, uint8_t function, uint8_t offset, uint32_t data)
char pci_has_device_functions (uint8_t bus, uint8_t device)
void pci_find_devices ()
device_desc_t pci_get_device_desriptor (uint8_t bus, uint8_t device, uint8_t function)
uint32_t pci_read_bar (device_t *dev, int bar_id)
Function Documentation
_pci_do_read_bar()
static uint32_t _pci_do_read_bar (uint8_t bus, uint8_t device, uint8_t function, uint8_t bar_id) static
Definition at line 16 of file pci.c.
 {
     uint32_t header_type = pci_read(bus, device, function, 0x0e) & 0x7f;
     uint8_t max_bars = 6 - (header_type * 4);
     if (bar_id >= max_bars)
         return 0;
     uint32_t bar_val = pci_read(bus, device, function, 0x10 + 4 * bar_id);
     return bar_val;
 }
References pci_read().
Referenced by _pci_get_bar(), and pci_read_bar().
_pci_driver_info()
static driver_desc_t _pci_driver_info () static
Definition at line 3 of file pci.c.
 {
     driver_desc_t pci_desc;
     pci_desc.type = DRIVER_BUS_CONTROLLER;
     pci_desc.auto_start = true;
     pci_desc.is_device_driver = false;
     pci_desc.is_device_needed = false;
     pci_desc.is_driver_needed = false;
     pci_desc.functions[DRIVER_NOTIFICATION] = 0;
     pci_desc.functions[DRIVER_BUS_CONTROLLER_FIND_DEVICE] = pci_find_devices;
     return pci_desc;
 }
References driver_desc_t::auto_start, DRIVER_BUS_CONTROLLER, DRIVER_BUS_CONTROLLER_FIND_DEVICE, DRIVER_NOTIFICATION, driver_desc_t::functions, driver_desc_t::is_device_driver, driver_desc_t::is_device_needed, driver_desc_t::is_driver_needed, pci_find_devices(), and driver_desc_t::type.
Referenced by pci_install().
_pci_get_bar()
static bar_t _pci_get_bar (uint8_t bus, uint8_t device, uint8_t function, uint8_t bar_id) static
Definition at line 27 of file pci.c.
 {
     bar_t result;
     uint32_t bar_val = _pci_do_read_bar(bus, device, function, bar_id);
     result.type = (bar_val & 0x1) ? INPUT_OUTPUT : MEMORY_MAPPED;
     if (result.type == MEMORY_MAPPED) {
     } else {
         result.address = (uint32_t)((bar_val >> 2) << 2);
         result.prefetchable = 0;
     }
     return result;
 }
References _pci_do_read_bar(), bar_t::address, INPUT_OUTPUT, MEMORY_MAPPED, bar_t::prefetchable, and bar_t::type.
Referenced by pci_find_devices().
pci_find_devices()
void pci_find_devices ()
Definition at line 79 of file pci.c.
 {
     kprintf("Pci scanning\n");
     uint8_t bus, device, function;
     for (bus = 0; bus < 8; bus++) {
         for (device = 0; device < 32; device++) {
             uint8_t functions_count = pci_has_device_functions(bus, device) == 0 ? 8 : 1;
             for (function = 0; function < functions_count; function++) {
                 device_desc_t dev = pci_get_device_desriptor(bus, device, function);
                 if (dev.vendor_id == 0x0000 || dev.vendor_id == 0xffff) {
                     continue;
                 }
                 for (uint8_t bar_id = 0; bar_id < 6; bar_id++) {
                     bar_t bar = _pci_get_bar(bus, device, function, bar_id);
                     if (bar.address && (bar.type == INPUT_OUTPUT)) {
                         dev.port_base = (uint32_t)bar.address;
                     }
                 }
                 device_install(dev);
                 kprintf("Vendor %x, devID %x, cl %x scl %x\n", dev.vendor_id, dev.device_id, dev.class_id, dev.subclass_id);
             }
         }
     }
 }
References _pci_get_bar(), bar_t::address, device_desc_t::class_id, device_desc_t::device_id, device_install(), INPUT_OUTPUT, kprintf(), pci_get_device_desriptor(), pci_has_device_functions(), device_desc_t::port_base, device_desc_t::subclass_id, bar_t::type, and device_desc_t::vendor_id.
Referenced by _pci_driver_info().
pci_get_device_desriptor()
device_desc_t pci_get_device_desriptor (uint8_t bus, uint8_t device, uint8_t function)
Definition at line 107 of file pci.c.
 {
     device_desc_t new_device;
     new_device.bus = bus;
     new_device.device = device;
     new_device.function = function;
     new_device.vendor_id = pci_read(bus, device, function, 0x00);
     new_device.device_id = pci_read(bus, device, function, 0x02);
     new_device.class_id = pci_read(bus, device, function, 0x0b);
     new_device.subclass_id = pci_read(bus, device, function, 0x0a);
     new_device.interface_id = pci_read(bus, device, function, 0x09);
     new_device.revision_id = pci_read(bus, device, function, 0x08);
     new_device.interrupt = pci_read(bus, device, function, 0x3c);
     return new_device;
 }
References device_desc_t::bus, device_desc_t::class_id, device_desc_t::device, device_desc_t::device_id, device_desc_t::function, device_desc_t::interface_id, device_desc_t::interrupt, pci_read(), device_desc_t::revision_id, device_desc_t::subclass_id, and device_desc_t::vendor_id.
Referenced by pci_find_devices().
pci_has_device_functions()
char pci_has_device_functions (uint8_t bus, uint8_t device)
Definition at line 74 of file pci.c.
 {
     return pci_read(bus, device, 0, 0x0e) & (1 << 7);
 }
References pci_read().
Referenced by pci_find_devices().
pci_install()
void pci_install ()
Definition at line 43 of file pci.c.
 {
     driver_install(_pci_driver_info());
 }
References _pci_driver_info(), and driver_install().
Referenced by stage3().
pci_read()
uint32_t pci_read (uint16_t bus, uint16_t device, uint16_t function, uint32_t offset)
Definition at line 48 of file pci.c.
 {
     uint32_t id = (0x1 << 31)
         | ((bus & 0xFF) << 16)
         | ((device & 0x1F) << 11)
         | ((function & 0x07) << 8)
         | (offset & 0xFC);
     port_dword_out(0xCF8, id);
     uint32_t tmp = (uint32_t)(port_dword_in(0xCFC) >> (8 * (offset % 4)));
     return tmp;
 }
References port_dword_in(), and port_dword_out().
Referenced by _pci_do_read_bar(), pci_get_device_desriptor(), and pci_has_device_functions().
pci_read_bar()
uint32_t pci_read_bar (device_t * dev, int bar_id)
Definition at line 128 of file pci.c.
 {
     return _pci_do_read_bar(dev->device_desc.bus, dev->device_desc.device, dev->device_desc.function, bar_id);
 }
References _pci_do_read_bar(), device_desc_t::bus, device_desc_t::device, device_t::device_desc, and device_desc_t::function.
Referenced by bga_init().
pci_write()
void pci_write (uint8_t bus, uint8_t device, uint8_t function, uint8_t offset, uint32_t data)
Definition at line 60 of file pci.c.
 {
     uint32_t bus32 = bus;
     uint32_t device32 = device;
     uint16_t function16 = function;
     uint32_t address = (1 << 31)
         | (bus32 << 16)
         | (device32 << 11)
         | (function16 << 8)
         | (offset & 0xFC);
     port_dword_out(0xCF8, address);
     port_dword_out(0xCFC, data);
 }
References port_dword_out().