oneOS: include/drivers/x86/pci.h File Reference
pci.h File Reference
#include <drivers/x86/display.h>
#include <drivers/driver_manager.h>
#include <types.h>
#include <platform/x86/port.h>
Data Structures
struct pcidd_t
struct bar_t
Enumerations
enum bar_type { MEMORY_MAPPED = 0 , INPUT_OUTPUT = 1 }
Functions
void pci_install ()
uint32_t pci_read (uint16_t bus, uint16_t device, uint16_t function, uint32_t offset)
void pci_write (uint8_t bus, uint8_t device, uint8_t function, uint8_t offset, uint32_t data)
char pci_has_device_functions (uint8_t bus, uint8_t device)
void pci_find_devices ()
device_desc_t pci_get_device_desriptor (uint8_t bus, uint8_t device, uint8_t function)
uint32_t pci_read_bar (device_t *dev, int bar_id)
Enumeration Type Documentation
bar_type
enum bar_type
Enumerator
MEMORY_MAPPED
INPUT_OUTPUT
Definition at line 26 of file pci.h.
               {
     MEMORY_MAPPED = 0,
     INPUT_OUTPUT = 1
 };
Function Documentation
pci_find_devices()
void pci_find_devices ()
Definition at line 79 of file pci.c.
 {
     kprintf("Pci scanning\n");
     uint8_t bus, device, function;
     for (bus = 0; bus < 8; bus++) {
         for (device = 0; device < 32; device++) {
             uint8_t functions_count = pci_has_device_functions(bus, device) == 0 ? 8 : 1;
             for (function = 0; function < functions_count; function++) {
                 device_desc_t dev = pci_get_device_desriptor(bus, device, function);
                 if (dev.vendor_id == 0x0000 || dev.vendor_id == 0xffff) {
                     continue;
                 }
                 for (uint8_t bar_id = 0; bar_id < 6; bar_id++) {
                     bar_t bar = _pci_get_bar(bus, device, function, bar_id);
                     if (bar.address && (bar.type == INPUT_OUTPUT)) {
                         dev.port_base = (uint32_t)bar.address;
                     }
                 }
                 device_install(dev);
                 kprintf("Vendor %x, devID %x, cl %x scl %x\n", dev.vendor_id, dev.device_id, dev.class_id, dev.subclass_id);
             }
         }
     }
 }
References _pci_get_bar(), bar_t::address, device_desc_t::class_id, device_desc_t::device_id, device_install(), INPUT_OUTPUT, kprintf(), pci_get_device_desriptor(), pci_has_device_functions(), device_desc_t::port_base, device_desc_t::subclass_id, bar_t::type, and device_desc_t::vendor_id.
Referenced by _pci_driver_info().
pci_get_device_desriptor()
device_desc_t pci_get_device_desriptor (uint8_t bus, uint8_t device, uint8_t function)
Definition at line 107 of file pci.c.
 {
     device_desc_t new_device;
     new_device.bus = bus;
     new_device.device = device;
     new_device.function = function;
     new_device.vendor_id = pci_read(bus, device, function, 0x00);
     new_device.device_id = pci_read(bus, device, function, 0x02);
     new_device.class_id = pci_read(bus, device, function, 0x0b);
     new_device.subclass_id = pci_read(bus, device, function, 0x0a);
     new_device.interface_id = pci_read(bus, device, function, 0x09);
     new_device.revision_id = pci_read(bus, device, function, 0x08);
     new_device.interrupt = pci_read(bus, device, function, 0x3c);
     return new_device;
 }
References device_desc_t::bus, device_desc_t::class_id, device_desc_t::device, device_desc_t::device_id, device_desc_t::function, device_desc_t::interface_id, device_desc_t::interrupt, pci_read(), device_desc_t::revision_id, device_desc_t::subclass_id, and device_desc_t::vendor_id.
Referenced by pci_find_devices().
pci_has_device_functions()
char pci_has_device_functions (uint8_t bus, uint8_t device)
Definition at line 74 of file pci.c.
 {
     return pci_read(bus, device, 0, 0x0e) & (1 << 7);
 }
References pci_read().
Referenced by pci_find_devices().
pci_install()
void pci_install ()
Definition at line 43 of file pci.c.
 {
     driver_install(_pci_driver_info());
 }
References _pci_driver_info(), and driver_install().
Referenced by stage3().
pci_read()
uint32_t pci_read (uint16_t bus, uint16_t device, uint16_t function, uint32_t offset)
Definition at line 48 of file pci.c.
 {
     uint32_t id = (0x1 << 31)
         | ((bus & 0xFF) << 16)
         | ((device & 0x1F) << 11)
         | ((function & 0x07) << 8)
         | (offset & 0xFC);
     port_dword_out(0xCF8, id);
     uint32_t tmp = (uint32_t)(port_dword_in(0xCFC) >> (8 * (offset % 4)));
     return tmp;
 }
References port_dword_in(), and port_dword_out().
Referenced by _pci_do_read_bar(), pci_get_device_desriptor(), and pci_has_device_functions().
pci_read_bar()
uint32_t pci_read_bar (device_t * dev, int bar_id)
Definition at line 128 of file pci.c.
 {
     return _pci_do_read_bar(dev->device_desc.bus, dev->device_desc.device, dev->device_desc.function, bar_id);
 }
References _pci_do_read_bar(), device_desc_t::bus, device_desc_t::device, device_t::device_desc, and device_desc_t::function.
Referenced by bga_init().
pci_write()
void pci_write (uint8_t bus, uint8_t device, uint8_t function, uint8_t offset, uint32_t data)
Definition at line 60 of file pci.c.
 {
     uint32_t bus32 = bus;
     uint32_t device32 = device;
     uint16_t function16 = function;
     uint32_t address = (1 << 31)
         | (bus32 << 16)
         | (device32 << 11)
         | (function16 << 8)
         | (offset & 0xFC);
     port_dword_out(0xCF8, address);
     port_dword_out(0xCFC, data);
 }
References port_dword_out().