oneOS: include/platform/x86/pic.h File Reference
pic.h File Reference
#include <platform/x86/port.h>
Macros
#define MASTER_PIC_CMD 0x0020
#define MASTER_PIC_DATA 0x0021
#define SLAVE_PIC_CMD 0x00A0
#define SLAVE_PIC_DATA 0x00A1
#define ICW4_8086 0x01
Functions
void pic_remap (unsigned int offset1, unsigned int offset2)
Macro Definition Documentation
ICW4_8086
#define ICW4_8086 0x01
Definition at line 10 of file pic.h.
MASTER_PIC_CMD
#define MASTER_PIC_CMD 0x0020
Definition at line 6 of file pic.h.
MASTER_PIC_DATA
#define MASTER_PIC_DATA 0x0021
Definition at line 7 of file pic.h.
SLAVE_PIC_CMD
#define SLAVE_PIC_CMD 0x00A0
Definition at line 8 of file pic.h.
SLAVE_PIC_DATA
#define SLAVE_PIC_DATA 0x00A1
Definition at line 9 of file pic.h.
Function Documentation
pic_remap()
void pic_remap (unsigned int offset1, unsigned int offset2)
Definition at line 3 of file pic.c.
{
     unsigned char m1, m2;
     m1 = port_byte_in(MASTER_PIC_DATA);
     m2 = port_byte_in(SLAVE_PIC_DATA);
     port_byte_out(MASTER_PIC_CMD, 0x11); // start in cascade mode
     io_wait();
     port_byte_out(SLAVE_PIC_CMD, 0x11); // start in cascade mode
     io_wait();
     port_byte_out(MASTER_PIC_DATA, offset1);
     io_wait();
     port_byte_out(SLAVE_PIC_DATA, offset2);
     io_wait();
     port_byte_out(MASTER_PIC_DATA, 0x04); // 0000 0100 - use irq2 in cascade
     io_wait();
     port_byte_out(SLAVE_PIC_DATA, 0x02); // cascade identity
     io_wait();
     port_byte_out(MASTER_PIC_DATA, ICW4_8086);
     io_wait();
     port_byte_out(SLAVE_PIC_DATA, ICW4_8086);
     io_wait();
     port_byte_out(MASTER_PIC_DATA, 0x00);
     port_byte_out(SLAVE_PIC_DATA, 0x00);
 }
References ICW4_8086, io_wait(), MASTER_PIC_CMD, MASTER_PIC_DATA, port_byte_in(), port_byte_out(), SLAVE_PIC_CMD, and SLAVE_PIC_DATA.
Referenced by idt_setup().