oneOS: include/drivers/x86/pit.h File Reference
pit.h File Reference
#include <types.h>
#include <platform/x86/idt.h>
Macros
#define PIT_BASE_FREQ 1193180
#define PIT_TICKS_PER_SECOND 1000
Functions
void pit_setup ()
void pit_handler ()
Macro Definition Documentation
PIT_BASE_FREQ
#define PIT_BASE_FREQ 1193180
Definition at line 15 of file pit.h.
PIT_TICKS_PER_SECOND
#define PIT_TICKS_PER_SECOND 1000
Definition at line 16 of file pit.h.
Function Documentation
pit_handler()
void pit_handler ()
Definition at line 47 of file pit.c.
 {
     timeman_pit_tick();
     if (RUNNIG_THREAD) {
         ticks_to_sched--;
         second--;
         if (second < 0) {
             second = 1000;
             log("----- second -----");
         }
         if (ticks_to_sched < 0) {
             ticks_to_sched = SCHED_INT;
             resched();
         }
     }
 }
References log(), resched(), RUNNIG_THREAD, SCHED_INT, second, ticks_to_sched, and timeman_pit_tick().
Referenced by pit_setup().
pit_setup()
void pit_setup ()
Definition at line 36 of file pit.c.
 {
     RUNNIG_THREAD = 0; // TODO: Remove it from here
     ticks_to_sched = SCHED_INT;
     int res = _pit_set_frequency(PIT_TICKS_PER_SECOND);
     if (res < 0) {
         kpanic("Pit: failed to set freq");
     }
     set_irq_handler(IRQ0, pit_handler);
 }
References _pit_set_frequency(), IRQ0, kpanic(), pit_handler(), PIT_TICKS_PER_SECOND, RUNNIG_THREAD, SCHED_INT, set_irq_handler(), and ticks_to_sched.
Referenced by stage3().