oneOS: src/kernel/drivers/x86/pit.c File Reference
pit.c File Reference
#include <drivers/x86/pit.h>
#include <log.h>
#include <platform/x86/system.h>
#include <tasking/sched.h>
#include <time/time_manager.h>
#include <utils/kassert.h>
Functions
static int _pit_set_frequency (uint16_t freq)
void pit_setup ()
void pit_handler ()
Variables
static int ticks_to_sched = 0
static int second = 1000
Function Documentation
_pit_set_frequency()
static int _pit_set_frequency (uint16_t freq) static
Definition at line 20 of file pit.c.
 {
     system_disable_interrupts();
     uint32_t divisor = PIT_BASE_FREQ / freq;
     if (divisor > 0xffff) {
         return -1;
     }
     uint8_t low = (uint8_t)(divisor & 0xFF);
     uint8_t high = (uint8_t)((divisor >> 8) & 0xFF);
     port_byte_out(0x43, 0x36); // 0b110110
     port_byte_out(0x40, low);
     port_byte_out(0x40, high);
     system_enable_interrupts();
     return 0;
 }
References PIT_BASE_FREQ, port_byte_out(), system_disable_interrupts(), and system_enable_interrupts().
Referenced by pit_setup().
pit_handler()
void pit_handler ()
Definition at line 47 of file pit.c.
 {
     timeman_pit_tick();
     if (RUNNIG_THREAD) {
         ticks_to_sched--;
         second--;
         if (second < 0) {
             second = 1000;
             log("----- second -----");
         }
         if (ticks_to_sched < 0) {
             ticks_to_sched = SCHED_INT;
             resched();
         }
     }
 }
References log(), resched(), RUNNIG_THREAD, SCHED_INT, second, ticks_to_sched, and timeman_pit_tick().
Referenced by pit_setup().
pit_setup()
void pit_setup ()
Definition at line 36 of file pit.c.
 {
     RUNNIG_THREAD = 0; // TODO: Remove it from here
     ticks_to_sched = SCHED_INT;
     int res = _pit_set_frequency(PIT_TICKS_PER_SECOND);
     if (res < 0) {
         kpanic("Pit: failed to set freq");
     }
     set_irq_handler(IRQ0, pit_handler);
 }
References _pit_set_frequency(), IRQ0, kpanic(), pit_handler(), PIT_TICKS_PER_SECOND, RUNNIG_THREAD, SCHED_INT, set_irq_handler(), and ticks_to_sched.
Referenced by stage3().
Variable Documentation
second
int second = 1000 static
Definition at line 17 of file pit.c.
Referenced by pit_handler().
ticks_to_sched
int ticks_to_sched = 0 static
Definition at line 16 of file pit.c.
Referenced by pit_handler(), and pit_setup().