oneOS: include/mem/pmm.h File Reference
pmm.h File Reference
#include <types.h>
#include <platform/x86/memmap.h>
#include <drivers/x86/display.h>
Data Structures
struct memory_map_t
struct mem_desc_t
Macros
#define MEMORY_MAP_REGION 0xA00
#define PMM_BLOCK_SIZE (4096)
#define PMM_BLOCK_SIZE_KB (4)
#define PMM_BLOCKS_PER_BYTE (8)
Functions
void pmm_setup (mem_desc_t *mem_desc)
void * pmm_alloc_block ()
void * pmm_alloc_blocks (uint32_t t_size)
bool pmm_free_block (void *t_block)
bool pmm_free_blocks (void *t_block, uint32_t t_size)
uint32_t pmm_get_ram_size ()
uint32_t pmm_get_max_blocks ()
uint32_t pmm_get_used_blocks ()
uint32_t pmm_get_free_blocks ()
uint32_t pmm_get_block_size ()
Variables
static uint32_t pmm_ram_size
static uint32_t pmm_max_blocks
static uint32_t pmm_used_blocks
static uint8_t * pmm_mat
static uint32_t pmm_mat_size
Macro Definition Documentation
MEMORY_MAP_REGION
#define MEMORY_MAP_REGION 0xA00
Definition at line 8 of file pmm.h.
PMM_BLOCK_SIZE
#define PMM_BLOCK_SIZE (4096)
Definition at line 9 of file pmm.h.
PMM_BLOCK_SIZE_KB
#define PMM_BLOCK_SIZE_KB (4)
Definition at line 10 of file pmm.h.
PMM_BLOCKS_PER_BYTE
#define PMM_BLOCKS_PER_BYTE (8)
Definition at line 11 of file pmm.h.
Function Documentation
pmm_alloc_block()
void* pmm_alloc_block ()
Definition at line 224 of file pmm.c.
{
     uint32_t block_id = _pmm_first_free_block();
     if (block_id == 0) {
         return 0x0;
     }
     _pmm_mat_alloc_block(block_id);
     pmm_used_blocks++;
     return (void*)(block_id * PMM_BLOCK_SIZE);
 }
References _pmm_first_free_block(), _pmm_mat_alloc_block(), PMM_BLOCK_SIZE, and pmm_used_blocks.
Referenced by _vmm_alloc_kernel_block(), _vmm_create_kernel_ptables(), _vmm_pspace_gen(), _vmm_split_pspace(), vmm_allocate_ptable(), and vmm_load_page().
pmm_alloc_blocks()
void* pmm_alloc_blocks (uint32_t t_size)
Definition at line 196 of file pmm.c.
{
     uint32_t block_id = _pmm_first_free_block_n(t_size);
     if (block_id == 0) {
         return 0x0;
     }
     for (uint32_t i = 0; i < t_size; i++) {
         _pmm_mat_alloc_block(block_id + i);
         pmm_used_blocks++;
     }
     return (void*)(block_id * PMM_BLOCK_SIZE);
 }
References _pmm_first_free_block_n(), _pmm_mat_alloc_block(), PMM_BLOCK_SIZE, and pmm_used_blocks.
pmm_free_block()
bool pmm_free_block (void * t_block)
Definition at line 237 of file pmm.c.
{
     if (((uint32_t)t_block & 0xfff) != 0) {
         return false;
     }
     uint32_t block_id = (uint32_t)t_block / PMM_BLOCK_SIZE;
     _pmm_mat_free_block(block_id);
     pmm_used_blocks--;
     return true;
 }
References _pmm_mat_free_block(), PMM_BLOCK_SIZE, and pmm_used_blocks.
Referenced by _vmm_free_pspace(), vmm_free_page(), and vmm_free_ptable().
pmm_free_blocks()
bool pmm_free_blocks (void * t_block, uint32_t t_size)
Definition at line 211 of file pmm.c.
{
     if (((uint32_t)t_block & 0xfff) != 0) {
         return false;
     }
     uint32_t block_id = (uint32_t)t_block / PMM_BLOCK_SIZE;
     for (uint32_t i = 0; i < t_size; i++) {
         _pmm_mat_free_block(block_id + i);
         pmm_used_blocks--;
     }
 }
References _pmm_mat_free_block(), PMM_BLOCK_SIZE, and pmm_used_blocks.
pmm_get_block_size()
uint32_t pmm_get_block_size ()
Definition at line 263 of file pmm.c.
{
     return PMM_BLOCK_SIZE;
 }
References PMM_BLOCK_SIZE.
pmm_get_free_blocks()
uint32_t pmm_get_free_blocks ()
Definition at line 259 of file pmm.c.
{
     return pmm_max_blocks - pmm_used_blocks;
 }
References pmm_max_blocks, and pmm_used_blocks.
pmm_get_max_blocks()
uint32_t pmm_get_max_blocks ()
Definition at line 251 of file pmm.c.
{
     return pmm_max_blocks;
 }
References pmm_max_blocks.
pmm_get_ram_size()
uint32_t pmm_get_ram_size ()
Definition at line 247 of file pmm.c.
{
     return pmm_ram_size;
 }
References pmm_ram_size.
pmm_get_used_blocks()
uint32_t pmm_get_used_blocks ()
Definition at line 255 of file pmm.c.
{
     return pmm_used_blocks;
 }
References pmm_used_blocks.
pmm_setup()
void pmm_setup (mem_desc_t * mem_desc)
Definition at line 168 of file pmm.c.
{
     uint32_t kernel_base_c = _pmm_round_ceil(KERNEL_BASE);
     uint32_t kernel_size = _pmm_round_ceil(mem_desc->kernel_size * 1024);
     _pmm_calc_ram_size(mem_desc);
     _pmm_allocate_mat((void*)(kernel_base_c+kernel_size));
     memory_map_t *memory_map = (memory_map_t *)MEMORY_MAP_REGION;
     for (int i = 0; i < mem_desc->memory_map_size; i++) {
         if (memory_map[i].type == 1) {
             kprinth(memory_map[i].startLo); kprintf(" "); kprinth(memory_map[i].sizeLo); kprintf("\n");
             _pmm_init_region(memory_map[i].startLo, memory_map[i].sizeLo);
         }
     }
     kprinth(pmm_mat_size);
     // while (1) {}
     _pmm_deinit_region(0x0, 0x200000);
     // TODO DEINIT MAT DOES NOT WORK;
     _pmm_deinit_mat(); // mat deinit
     _pmm_deinit_region(0x0, KERNEL_PM_BASE); // kernel stack deinit
     _pmm_deinit_region(KERNEL_PM_BASE, mem_desc->kernel_size * 1024); // kernel deinit
     // TODO seems like mistake is near
 }
References _pmm_allocate_mat(), _pmm_calc_ram_size(), _pmm_deinit_mat(), _pmm_deinit_region(), _pmm_init_region(), _pmm_round_ceil(), KERNEL_BASE, KERNEL_PM_BASE, mem_desc_t::kernel_size, kprintf(), kprinth(), MEMORY_MAP_REGION, mem_desc_t::memory_map_size, pmm_mat_size, and type.
Referenced by stage3().
Variable Documentation
pmm_mat
uint8_t* pmm_mat static
Definition at line 30 of file pmm.h.
Referenced by _pmm_allocate_mat(), _pmm_deinit_mat(), _pmm_deinit_region(), _pmm_first_free_block(), _pmm_first_free_block_n(), _pmm_init_region(), _pmm_mat_alloc_block(), _pmm_mat_free_block(), and _pmm_mat_test_block().
pmm_mat_size
uint32_t pmm_mat_size static
Definition at line 31 of file pmm.h.
Referenced by _pmm_allocate_mat(), _pmm_deinit_mat(), _pmm_first_free_block(), _pmm_first_free_block_n(), and pmm_setup().
pmm_max_blocks
uint32_t pmm_max_blocks static
Definition at line 28 of file pmm.h.
Referenced by _pmm_allocate_mat(), pmm_get_free_blocks(), and pmm_get_max_blocks().
pmm_ram_size
uint32_t pmm_ram_size static
Definition at line 27 of file pmm.h.
Referenced by _pmm_allocate_mat(), _pmm_calc_ram_size(), and pmm_get_ram_size().
pmm_used_blocks
uint32_t pmm_used_blocks static
Definition at line 29 of file pmm.h.
Referenced by _pmm_allocate_mat(), _pmm_deinit_region(), _pmm_init_region(), pmm_alloc_block(), pmm_alloc_blocks(), pmm_free_block(), pmm_free_blocks(), pmm_get_free_blocks(), and pmm_get_used_blocks().