oneOS: src/kernel/mem/pmm.c File Reference
pmm.c File Reference
#include <mem/pmm.h>
#include <platform/x86/memmap.h>
Functions
uint32_t _pmm_round_floor (uint32_t t_value)
uint32_t _pmm_round_ceil (uint32_t t_value)
void _pmm_mat_alloc_block (uint32_t t_block_id)
void _pmm_mat_free_block (uint32_t t_block_id)
bool _pmm_mat_test_block (uint32_t t_block_id)
uint32_t _pmm_first_free_block ()
uint32_t _pmm_first_free_block_n (uint32_t t_size)
void _pmm_init_region (uint32_t t_region_start, uint32_t t_region_length)
void _pmm_deinit_region (uint32_t t_region_start, uint32_t t_region_length)
void _pmm_deinit_mat ()
void _pmm_calc_ram_size (mem_desc_t *mem_desc)
void _pmm_allocate_mat (void *t_mat_base)
void pmm_setup (mem_desc_t *mem_desc)
void * pmm_alloc_blocks (uint32_t t_size)
bool pmm_free_blocks (void *t_block, uint32_t t_size)
void * pmm_alloc_block ()
bool pmm_free_block (void *t_block)
uint32_t pmm_get_ram_size ()
uint32_t pmm_get_max_blocks ()
uint32_t pmm_get_used_blocks ()
uint32_t pmm_get_free_blocks ()
uint32_t pmm_get_block_size ()
Function Documentation
_pmm_allocate_mat()
void _pmm_allocate_mat (void * t_mat_base)
Definition at line 157 of file pmm.c.
{
     pmm_mat = t_mat_base;
     pmm_mat_size = pmm_ram_size / PMM_BLOCK_SIZE / PMM_BLOCKS_PER_BYTE;
     pmm_max_blocks = pmm_ram_size / PMM_BLOCK_SIZE;
     pmm_used_blocks = pmm_max_blocks;
     // mark all block as unavailable
     for (uint32_t i = 0; i < pmm_mat_size; ++i) {
         pmm_mat[i] = 0xff;
     }
 }
References PMM_BLOCK_SIZE, PMM_BLOCKS_PER_BYTE, pmm_mat, pmm_mat_size, pmm_max_blocks, pmm_ram_size, and pmm_used_blocks.
Referenced by pmm_setup().
_pmm_calc_ram_size()
void _pmm_calc_ram_size (mem_desc_t * mem_desc)
Definition at line 145 of file pmm.c.
{
     pmm_ram_size = 0;
     memory_map_t *memory_map = (memory_map_t *)MEMORY_MAP_REGION;
     for (int i = 0; i < mem_desc->memory_map_size; i++) {
         if (memory_map[i].type == 1) {
             pmm_ram_size = memory_map[i].startLo + memory_map[i].sizeLo;
         }
     }
 }
References MEMORY_MAP_REGION, mem_desc_t::memory_map_size, pmm_ram_size, memory_map_t::sizeLo, memory_map_t::startLo, and type.
Referenced by pmm_setup().
_pmm_deinit_mat()
void _pmm_deinit_mat ()
Definition at line 139 of file pmm.c.
{
     _pmm_deinit_region((uint32_t)pmm_mat, pmm_mat_size);
 }
References _pmm_deinit_region(), pmm_mat, and pmm_mat_size.
Referenced by pmm_setup().
_pmm_deinit_region()
void _pmm_deinit_region (uint32_t t_region_start, uint32_t t_region_length)
Definition at line 118 of file pmm.c.
{
     t_region_start = _pmm_round_floor(t_region_start);
     t_region_length = _pmm_round_ceil(t_region_length);
     uint32_t block_id = t_region_start / PMM_BLOCK_SIZE;
     uint32_t blocks_count = t_region_length / PMM_BLOCK_SIZE;
     pmm_used_blocks += blocks_count;
     while (blocks_count) {
         if (blocks_count >= PMM_BLOCKS_PER_BYTE && block_id % PMM_BLOCKS_PER_BYTE == 0) {
             pmm_mat[block_id / PMM_BLOCKS_PER_BYTE] = 0xff;
             blocks_count -= PMM_BLOCKS_PER_BYTE;
             block_id += PMM_BLOCKS_PER_BYTE;
         } else {
             _pmm_mat_alloc_block(block_id);
             blocks_count -= 1;
             block_id += 1;
         }
     }
 }
References _pmm_mat_alloc_block(), _pmm_round_ceil(), _pmm_round_floor(), PMM_BLOCK_SIZE, PMM_BLOCKS_PER_BYTE, pmm_mat, and pmm_used_blocks.
Referenced by _pmm_deinit_mat(), and pmm_setup().
_pmm_first_free_block()
uint32_t _pmm_first_free_block ()
Definition at line 54 of file pmm.c.
{
     uint32_t *mat_big = (uint32_t*)pmm_mat;
     for (uint32_t i = 0; i < pmm_mat_size / 4; i++) {
         if (mat_big[i] != 0xffffffff) {
             for (uint8_t j = 0; j < 32; j++) {
                 uint32_t current_block = i * 32 + j;
                 if (!_pmm_mat_test_block(current_block)) {
                     return current_block;
                 }
             }
         }
     }
     return 0x0;
 }
References _pmm_mat_test_block(), pmm_mat, and pmm_mat_size.
Referenced by _pmm_first_free_block_n(), and pmm_alloc_block().
_pmm_first_free_block_n()
uint32_t _pmm_first_free_block_n (uint32_t t_size)
Definition at line 71 of file pmm.c.
{
     if (t_size == 1) {
         return _pmm_first_free_block();
     }
     uint32_t *mat_big = (uint32_t*)pmm_mat;
     for (uint32_t i = 0; i < pmm_mat_size / 4; i++) {
         if (mat_big[i] != 0xffffffff) {
             for (uint8_t j = 0; j < 32; j++) {
                 uint32_t current_block = i * 32 + j;
                 uint32_t free = 0;
                 for (uint32_t x = 0; x < t_size; x++) {
                     if (!_pmm_mat_test_block(current_block+x)) {
                         free++;
                     }
                 }
                 if (free == t_size) {
                     return current_block;
                 }
             }
         }
     }
     return 0x0;
 }
References _pmm_first_free_block(), _pmm_mat_test_block(), free(), pmm_mat, and pmm_mat_size.
Referenced by pmm_alloc_blocks().
_pmm_init_region()
void _pmm_init_region (uint32_t t_region_start, uint32_t t_region_length)
Definition at line 97 of file pmm.c.
{
     t_region_start = _pmm_round_ceil(t_region_start);
     t_region_length = _pmm_round_floor(t_region_length);
     uint32_t block_id = t_region_start / PMM_BLOCK_SIZE;
     uint32_t blocks_count = t_region_length / PMM_BLOCK_SIZE;
     pmm_used_blocks -= blocks_count;
     while (blocks_count) {
         if (blocks_count >= PMM_BLOCKS_PER_BYTE && block_id % PMM_BLOCKS_PER_BYTE == 0) {
             pmm_mat[block_id / PMM_BLOCKS_PER_BYTE] = 0;
             blocks_count -= PMM_BLOCKS_PER_BYTE;
             block_id += PMM_BLOCKS_PER_BYTE;
         } else {
             _pmm_mat_free_block(block_id);
             blocks_count -= 1;
             block_id += 1;
         }
     }
 }
References _pmm_mat_free_block(), _pmm_round_ceil(), _pmm_round_floor(), PMM_BLOCK_SIZE, PMM_BLOCKS_PER_BYTE, pmm_mat, and pmm_used_blocks.
Referenced by pmm_setup().
_pmm_mat_alloc_block()
void _pmm_mat_alloc_block (uint32_t t_block_id)
Definition at line 36 of file pmm.c.
{
     pmm_mat[t_block_id / PMM_BLOCKS_PER_BYTE] |= (1 << (t_block_id % PMM_BLOCKS_PER_BYTE));
 }
References PMM_BLOCKS_PER_BYTE, and pmm_mat.
Referenced by _pmm_deinit_region(), pmm_alloc_block(), and pmm_alloc_blocks().
_pmm_mat_free_block()
void _pmm_mat_free_block (uint32_t t_block_id)
Definition at line 42 of file pmm.c.
{
     pmm_mat[t_block_id / PMM_BLOCKS_PER_BYTE] &= ~(1 << (t_block_id % PMM_BLOCKS_PER_BYTE));
 }
References PMM_BLOCKS_PER_BYTE, and pmm_mat.
Referenced by _pmm_init_region(), pmm_free_block(), and pmm_free_blocks().
_pmm_mat_test_block()
bool _pmm_mat_test_block (uint32_t t_block_id)
Definition at line 48 of file pmm.c.
{
     return (pmm_mat[t_block_id / PMM_BLOCKS_PER_BYTE] >> (t_block_id % PMM_BLOCKS_PER_BYTE)) & 1;
 }
References PMM_BLOCKS_PER_BYTE, and pmm_mat.
Referenced by _pmm_first_free_block(), and _pmm_first_free_block_n().
_pmm_round_ceil()
uint32_t _pmm_round_ceil (uint32_t t_value)
Definition at line 26 of file pmm.c.
{
     if ((t_value & 0xfff) != 0) {
         t_value += 0x1000;
         t_value &= (0xffffffff - 0xfff);
     }
     return t_value;
 }
Referenced by _pmm_deinit_region(), _pmm_init_region(), and pmm_setup().
_pmm_round_floor()
uint32_t _pmm_round_floor (uint32_t t_value)
Definition at line 20 of file pmm.c.
{
     return (t_value & (0xffffffff - 0xfff));
 }
Referenced by _pmm_deinit_region(), and _pmm_init_region().
pmm_alloc_block()
void* pmm_alloc_block ()
Definition at line 224 of file pmm.c.
{
     uint32_t block_id = _pmm_first_free_block();
     if (block_id == 0) {
         return 0x0;
     }
     _pmm_mat_alloc_block(block_id);
     pmm_used_blocks++;
     return (void*)(block_id * PMM_BLOCK_SIZE);
 }
References _pmm_first_free_block(), _pmm_mat_alloc_block(), PMM_BLOCK_SIZE, and pmm_used_blocks.
Referenced by _vmm_alloc_kernel_block(), _vmm_create_kernel_ptables(), _vmm_pspace_gen(), _vmm_split_pspace(), vmm_allocate_ptable(), and vmm_load_page().
pmm_alloc_blocks()
void* pmm_alloc_blocks (uint32_t t_size)
Definition at line 196 of file pmm.c.
{
     uint32_t block_id = _pmm_first_free_block_n(t_size);
     if (block_id == 0) {
         return 0x0;
     }
     for (uint32_t i = 0; i < t_size; i++) {
         _pmm_mat_alloc_block(block_id + i);
         pmm_used_blocks++;
     }
     return (void*)(block_id * PMM_BLOCK_SIZE);
 }
References _pmm_first_free_block_n(), _pmm_mat_alloc_block(), PMM_BLOCK_SIZE, and pmm_used_blocks.
pmm_free_block()
bool pmm_free_block (void * t_block)
Definition at line 237 of file pmm.c.
{
     if (((uint32_t)t_block & 0xfff) != 0) {
         return false;
     }
     uint32_t block_id = (uint32_t)t_block / PMM_BLOCK_SIZE;
     _pmm_mat_free_block(block_id);
     pmm_used_blocks--;
     return true;
 }
References _pmm_mat_free_block(), PMM_BLOCK_SIZE, and pmm_used_blocks.
Referenced by _vmm_free_pspace(), vmm_free_page(), and vmm_free_ptable().
pmm_free_blocks()
bool pmm_free_blocks (void * t_block, uint32_t t_size)
Definition at line 211 of file pmm.c.
{
     if (((uint32_t)t_block & 0xfff) != 0) {
         return false;
     }
     uint32_t block_id = (uint32_t)t_block / PMM_BLOCK_SIZE;
     for (uint32_t i = 0; i < t_size; i++) {
         _pmm_mat_free_block(block_id + i);
         pmm_used_blocks--;
     }
 }
References _pmm_mat_free_block(), PMM_BLOCK_SIZE, and pmm_used_blocks.
pmm_get_block_size()
uint32_t pmm_get_block_size ()
Definition at line 263 of file pmm.c.
{
     return PMM_BLOCK_SIZE;
 }
References PMM_BLOCK_SIZE.
pmm_get_free_blocks()
uint32_t pmm_get_free_blocks ()
Definition at line 259 of file pmm.c.
{
     return pmm_max_blocks - pmm_used_blocks;
 }
References pmm_max_blocks, and pmm_used_blocks.
pmm_get_max_blocks()
uint32_t pmm_get_max_blocks ()
Definition at line 251 of file pmm.c.
{
     return pmm_max_blocks;
 }
References pmm_max_blocks.
pmm_get_ram_size()
uint32_t pmm_get_ram_size ()
Definition at line 247 of file pmm.c.
{
     return pmm_ram_size;
 }
References pmm_ram_size.
pmm_get_used_blocks()
uint32_t pmm_get_used_blocks ()
Definition at line 255 of file pmm.c.
{
     return pmm_used_blocks;
 }
References pmm_used_blocks.
pmm_setup()
void pmm_setup (mem_desc_t * mem_desc)
Definition at line 168 of file pmm.c.
{
     uint32_t kernel_base_c = _pmm_round_ceil(KERNEL_BASE);
     uint32_t kernel_size = _pmm_round_ceil(mem_desc->kernel_size * 1024);
     _pmm_calc_ram_size(mem_desc);
     _pmm_allocate_mat((void*)(kernel_base_c+kernel_size));
     memory_map_t *memory_map = (memory_map_t *)MEMORY_MAP_REGION;
     for (int i = 0; i < mem_desc->memory_map_size; i++) {
         if (memory_map[i].type == 1) {
             kprinth(memory_map[i].startLo); kprintf(" "); kprinth(memory_map[i].sizeLo); kprintf("\n");
             _pmm_init_region(memory_map[i].startLo, memory_map[i].sizeLo);
         }
     }
     kprinth(pmm_mat_size);
     // while (1) {}
     _pmm_deinit_region(0x0, 0x200000);
     // TODO DEINIT MAT DOES NOT WORK;
     _pmm_deinit_mat(); // mat deinit
     _pmm_deinit_region(0x0, KERNEL_PM_BASE); // kernel stack deinit
     _pmm_deinit_region(KERNEL_PM_BASE, mem_desc->kernel_size * 1024); // kernel deinit
     // TODO seems like mistake is near
 }
References _pmm_allocate_mat(), _pmm_calc_ram_size(), _pmm_deinit_mat(), _pmm_deinit_region(), _pmm_init_region(), _pmm_round_ceil(), KERNEL_BASE, KERNEL_PM_BASE, mem_desc_t::kernel_size, kprintf(), kprinth(), MEMORY_MAP_REGION, mem_desc_t::memory_map_size, pmm_mat_size, and type.
Referenced by stage3().