oneOS: src/kernel/tasking/proc_zoner.c File Reference
proc_zoner.c File Reference
#include <errno.h>
#include <fs/vfs.h>
#include <mem/kmalloc.h>
#include <tasking/proc.h>
Functions
static bool _proc_zones_intersect (uint32_t start1, uint32_t size1, uint32_t start2, uint32_t size2)
static bool _proc_can_add_zone (proc_t *proc, uint32_t start, uint32_t len)
proc_zone_t * proc_new_zone (proc_t *proc, uint32_t start, uint32_t len)
proc_zone_t * proc_new_random_zone (proc_t *proc, uint32_t len)
proc_zone_t * proc_new_random_zone_backward (proc_t *proc, uint32_t len)
proc_zone_t * proc_find_zone (proc_t *proc, uint32_t addr)
Function Documentation
_proc_can_add_zone()
static bool _proc_can_add_zone (proc_t * proc, uint32_t start, uint32_t len) inline static
Definition at line 25 of file proc_zoner.c.
 {
     uint32_t zones_count = proc->zones.size;
     for (uint32_t i = 0; i < zones_count; i++) {
         proc_zone_t* zone = (proc_zone_t*)dynamic_array_get(&proc->zones, i);
         if (_proc_zones_intersect(start, len, zone->start, zone->len)) {
             return false;
         }
     }
     return true;
 }
References _proc_zones_intersect(), dynamic_array_get(), proc_zone::len, dynamic_array::size, proc_zone::start, and proc::zones.
Referenced by proc_new_random_zone(), proc_new_random_zone_backward(), and proc_new_zone().
_proc_zones_intersect()
static bool _proc_zones_intersect (uint32_t start1, uint32_t size1, uint32_t start2, uint32_t size2) inline static
PROC ZONING
Definition at line 18 of file proc_zoner.c.
 {
     uint32_t end1 = start1 + size1 - 1;
     uint32_t end2 = start2 + size2 - 1;
     return (start1 <= start2 && start2 <= end1) || (start1 <= end2 && end2 <= end1) || (start2 <= start1 && start1 <= end2) || (start2 <= end1 && end1 <= end2);
 }
Referenced by _proc_can_add_zone().
proc_find_zone()
proc_zone_t* proc_find_zone (proc_t * proc, uint32_t addr)
Definition at line 127 of file proc_zoner.c.
 {
     uint32_t zones_count = proc->zones.size;
     for (uint32_t i = 0; i < zones_count; i++) {
         proc_zone_t* zone = (proc_zone_t*)dynamic_array_get(&proc->zones, i);
         if (zone->start <= addr && addr < zone->start + zone->len) {
             return zone;
         }
     }
     return 0;
 }
References dynamic_array_get(), proc_zone::len, dynamic_array::size, proc_zone::start, and proc::zones.
Referenced by vmm_page_fault_handler().
proc_new_random_zone()
proc_zone_t* proc_new_random_zone (proc_t * proc, uint32_t len)
Definition at line 62 of file proc_zoner.c.
 {
     if (len % VMM_PAGE_SIZE) {
         len += VMM_PAGE_SIZE - (len % VMM_PAGE_SIZE);
     }
     uint32_t zones_count = proc->zones.size;
     /* Check if we can put it at the beginning */
     proc_zone_t* ret = proc_new_zone(proc, 0, len);
     if (ret) {
         return ret;
     }
     uint32_t min_start = 0xffffffff;
     for (uint32_t i = 0; i < zones_count; i++) {
         proc_zone_t* zone = (proc_zone_t*)dynamic_array_get(&proc->zones, i);
         if (_proc_can_add_zone(proc, zone->start + zone->len, len)) {
             if (min_start > zone->start + zone->len) {
                 min_start = zone->start + zone->len;
             }
         }
     }
     if (min_start == 0xffffffff) {
         return 0;
     }
     return proc_new_zone(proc, min_start, len);
 }
References _proc_can_add_zone(), dynamic_array_get(), proc_zone::len, proc_new_zone(), dynamic_array::size, proc_zone::start, VMM_PAGE_SIZE, and proc::zones.
Referenced by _bga_mmap(), _proc_load_bin(), _vfs_do_mmap(), and sys_mmap().
proc_new_random_zone_backward()
proc_zone_t* proc_new_random_zone_backward (proc_t * proc, uint32_t len)
Definition at line 95 of file proc_zoner.c.
 {
     if (len % VMM_PAGE_SIZE) {
         len += VMM_PAGE_SIZE - (len % VMM_PAGE_SIZE);
     }
     uint32_t zones_count = proc->zones.size;
     /* Check if we can put it at the end */
     proc_zone_t* ret = proc_new_zone(proc, KERNEL_BASE - len, len);
     if (ret) {
         return ret;
     }
     uint32_t max_end = 0;
     for (uint32_t i = 0; i < zones_count; i++) {
         proc_zone_t* zone = (proc_zone_t*)dynamic_array_get(&proc->zones, i);
         if (_proc_can_add_zone(proc, zone->start - len, len)) {
             if (max_end < zone->start) {
                 max_end = zone->start;
             }
         }
     }
     if (max_end == 0) {
         return 0;
     }
     return proc_new_zone(proc, max_end - len, len);
 }
References _proc_can_add_zone(), dynamic_array_get(), KERNEL_BASE, proc_new_zone(), dynamic_array::size, proc_zone::start, VMM_PAGE_SIZE, and proc::zones.
Referenced by _proc_load_bin(), and sys_mmap().
proc_new_zone()
proc_zone_t* proc_new_zone (proc_t * p, uint32_t start, uint32_t len)
PROC ZONER FUNCTIONS
Definition at line 39 of file proc_zoner.c.
 {
     if (len % VMM_PAGE_SIZE) {
         len += VMM_PAGE_SIZE - (len % VMM_PAGE_SIZE);
     }
     proc_zone_t new_zone;
     new_zone.start = start;
     new_zone.len = len;
     new_zone.type = 0;
     new_zone.flags = ZONE_USER;
     if (_proc_can_add_zone(proc, start, len)) {
         if (dynamic_array_push(&proc->zones, &new_zone) != 0) {
             return 0;
         }
         return (proc_zone_t*)dynamic_array_get(&proc->zones, proc->zones.size - 1);
     }
     return 0;
 }
References _proc_can_add_zone(), dynamic_array_get(), dynamic_array_push(), proc_zone::flags, proc_zone::len, dynamic_array::size, proc_zone::start, proc_zone::type, VMM_PAGE_SIZE, ZONE_USER, and proc::zones.
Referenced by proc_new_random_zone(), and proc_new_random_zone_backward().