oneOS: include/fs/procfs/procfs.h File Reference
procfs.h File Reference
#include <types.h>
Functions
void procfs_install ()
Function Documentation
procfs_install()
void procfs_install ()
Definition at line 76 of file procfs.c.
 {
     driver_install(_procfs_driver_info());
 }
References _procfs_driver_info(), and driver_install().
Referenced by stage3().