oneOS: include/tasking/proc.h File Reference
proc.h File Reference
#include <algo/dynamic_array.h>
#include <fs/vfs.h>
#include <io/tty/tty.h>
#include <mem/vmm/vmm.h>
#include <mem/vmm/zoner.h>
#include <platform/x86/idt.h>
#include <types.h>
Data Structures
struct proc_zone
struct proc
Macros
#define MAX_PROCESS_COUNT 1024
#define MAX_OPENED_FILES 16
Typedefs
typedef struct proc_zone proc_zone_t
typedef struct proc proc_t
Enumerations
enum ZONE_FLAGS {
ZONE_WRITABLE = 0x1 , ZONE_READABLE = 0x2 , ZONE_EXECUTABLE = 0x4 , ZONE_NOT_CACHEABLE = 0x8 ,
ZONE_COW = 0x10 , ZONE_USER = 0x20
}
enum ZONE_TYPES {
ZONE_TYPE_CODE = 0x1 , ZONE_TYPE_DATA = 0x2 , ZONE_TYPE_STACK = 0x4 , ZONE_TYPE_MAPPED_FILE_PRIVATLY = 0x8 ,
ZONE_TYPE_MAPPED_FILE_SHAREDLY = 0x10
}
enum PROC_STATUS { PROC_INVALID = 0 , PROC_ALIVE , PROC_DEAD , PROC_DYING }
Functions
uint32_t proc_alloc_pid ()
struct thread * thread_by_pid (uint32_t pid)
int proc_setup (proc_t *p)
int proc_setup_tty (proc_t *p, tty_entry_t *tty)
int proc_fill_up_stack (proc_t *p, int argc, char **argv, char **env)
int proc_free (proc_t *p)
struct thread * proc_alloc_thread ()
struct thread * proc_create_thread (proc_t *p)
void proc_kill_all_threads (proc_t *p)
void proc_kill_all_threads_except (proc_t *p, struct thread *gthread)
int kthread_setup (proc_t *p)
int kthread_setup_regs (proc_t *p, void *entry_point)
void kthread_setup_segment_regs (proc_t *p)
int kthread_free (proc_t *p)
int proc_load (proc_t *p, const char *path)
int proc_copy_of (proc_t *new_proc, struct thread *from_thread)
int proc_die (proc_t *p)
int proc_chdir (proc_t *p, const char *path)
file_descriptor_t * proc_get_free_fd (proc_t *p)
file_descriptor_t * proc_get_fd (proc_t *p, uint32_t index)
int proc_get_fd_id (proc_t *proc, file_descriptor_t *fd)
proc_zone_t * proc_new_zone (proc_t *p, uint32_t start, uint32_t len)
proc_zone_t * proc_new_random_zone (proc_t *p, uint32_t len)
proc_zone_t * proc_new_random_zone_backward (proc_t *p, uint32_t len)
proc_zone_t * proc_find_zone (proc_t *p, uint32_t addr)
Macro Definition Documentation
MAX_OPENED_FILES
#define MAX_OPENED_FILES 16
Definition at line 21 of file proc.h.
MAX_PROCESS_COUNT
#define MAX_PROCESS_COUNT 1024
Definition at line 20 of file proc.h.
Typedef Documentation
proc_t
typedef struct proc proc_t
Definition at line 1 of file proc.h.
proc_zone_t
typedef struct proc_zone proc_zone_t
Definition at line 1 of file proc.h.
Enumeration Type Documentation
PROC_STATUS
enum PROC_STATUS
Enumerator
PROC_INVALID
PROC_ALIVE
PROC_DEAD
PROC_DYING
Definition at line 51 of file proc.h.
                  {
     PROC_INVALID = 0,
     PROC_ALIVE,
     PROC_DEAD,
     PROC_DYING,
 };
ZONE_FLAGS
enum ZONE_FLAGS
Enumerator
ZONE_WRITABLE
ZONE_READABLE
ZONE_EXECUTABLE
ZONE_NOT_CACHEABLE
ZONE_COW
ZONE_USER
Definition at line 24 of file proc.h.
                 {
     ZONE_WRITABLE = 0x1,
     ZONE_READABLE = 0x2,
     ZONE_EXECUTABLE = 0x4,
     ZONE_NOT_CACHEABLE = 0x8,
     ZONE_COW = 0x10,
     ZONE_USER = 0x20,
 };
ZONE_TYPES
enum ZONE_TYPES
Enumerator
ZONE_TYPE_CODE
ZONE_TYPE_DATA
ZONE_TYPE_STACK
ZONE_TYPE_MAPPED_FILE_PRIVATLY
ZONE_TYPE_MAPPED_FILE_SHAREDLY
Definition at line 33 of file proc.h.
                 {
     ZONE_TYPE_CODE = 0x1,
     ZONE_TYPE_DATA = 0x2,
     ZONE_TYPE_STACK = 0x4,
     ZONE_TYPE_MAPPED_FILE_PRIVATLY = 0x8,
     ZONE_TYPE_MAPPED_FILE_SHAREDLY = 0x10,
 };
Function Documentation
kthread_free()
int kthread_free (proc_t * p)
Definition at line 69 of file kthread.c.
 {
     /* proc_free can free kthreads too) */
     proc_free(p);
 }
References p, and proc_free().
kthread_setup()
int kthread_setup (proc_t * p)
KTHREAD FUNCTIONS
Definition at line 22 of file kthread.c.
 {
     p->pid = proc_alloc_pid();
     p->pgid = p->pid;
     p->is_kthread = true;
     /* allocating kernel stack */
     p->main_thread = proc_alloc_thread();
     p->main_thread->tid = p->pid;
     p->main_thread->process = p;
     p->main_thread->kstack = zoner_new_zone(VMM_PAGE_SIZE);
     if (!p->main_thread->kstack.start) {
         return -ENOMEM;
     }
     _thread_setup_kstack(p->main_thread, p->main_thread->kstack.start + VMM_PAGE_SIZE);
     /* setting current work directory */
     p->cwd = 0;
     p->fds = 0;
     /* setting signal handlers to 0 */
     p->main_thread->signals_mask = 0x0; /* All signals are disabled. */
     p->main_thread->pending_signals_mask = 0x0;
     memset((void*)p->main_thread->signal_handlers, 0, sizeof(p->main_thread->signal_handlers));
     return 0;
 }
References _thread_setup_kstack(), ENOMEM, memset(), p, proc_alloc_pid(), proc_alloc_thread(), VMM_PAGE_SIZE, and zoner_new_zone().
Referenced by _tasking_alloc_kernel_thread().
kthread_setup_regs()
int kthread_setup_regs (proc_t * p, void * entry_point)
Definition at line 51 of file kthread.c.
 {
     kthread_setup_segment_regs(p);
     p->main_thread->tf->ebp = (p->main_thread->kstack.start + VMM_PAGE_SIZE);
     p->main_thread->tf->esp = p->main_thread->tf->ebp;
     p->main_thread->tf->eip = (uint32_t)entry_point;
     return 0;
 }
References kthread_setup_segment_regs(), p, and VMM_PAGE_SIZE.
Referenced by _tasking_alloc_kernel_thread().
kthread_setup_segment_regs()
void kthread_setup_segment_regs (proc_t * p)
Definition at line 60 of file kthread.c.
 {
     p->main_thread->tf->cs = (SEG_KCODE << 3);
     p->main_thread->tf->ds = (SEG_KDATA << 3);
     p->main_thread->tf->es = p->main_thread->tf->ds;
     p->main_thread->tf->ss = p->main_thread->tf->ds;
     p->main_thread->tf->eflags = FL_IF;
 }
References FL_IF, p, SEG_KCODE, and SEG_KDATA.
Referenced by kthread_setup_regs().
proc_alloc_pid()
uint32_t proc_alloc_pid ()
PROC FUNCTIONS
Definition at line 56 of file proc.c.
 {
     return proc_next_pid++;
 }
References proc_next_pid.
Referenced by kthread_setup(), proc_setup(), and thread_setup().
proc_alloc_thread()
struct thread* proc_alloc_thread ()
Definition at line 41 of file proc.c.
 {
     return &thread_storage[threads_cnt++];
 }
References thread_storage, and threads_cnt.
Referenced by kthread_setup(), proc_create_thread(), and proc_setup().
proc_chdir()
int proc_chdir (proc_t * p, const char * path)
PROC FD FUNCTIONS
PROC FS FUNCTIONS
Definition at line 313 of file proc.c.
 {
     char* kpath = 0;
     if (!str_validate_len(path, 128)) {
         return -EINVAL;
     }
     kpath = kmem_bring_to_kernel(path, strlen(path) + 1);
     dentry_t* new_cwd;
     int ret = vfs_resolve_path_start_from(p->cwd, kpath, &new_cwd);
     if (ret) {
         return -ENOENT;
     }
     if (!dentry_inode_test_flag(new_cwd, S_IFDIR)) {
         dentry_put(new_cwd);
         return -ENOTDIR;
     }
     /* Put an old one back */
     if (p->cwd) {
         dentry_put(p->cwd);
     }
     p->cwd = new_cwd;
     return 0;
 }
References dentry_inode_test_flag(), dentry_put(), EINVAL, ENOENT, ENOTDIR, kmem_bring_to_kernel(), p, S_IFDIR, str_validate_len(), strlen(), and vfs_resolve_path_start_from().
Referenced by sys_chdir().
proc_copy_of()
int proc_copy_of (proc_t * new_proc, struct thread * from_thread)
Definition at line 122 of file proc.c.
 {
     proc_t* from_proc = from_thread->process;
     memcpy((uint8_t*)new_proc->main_thread->tf, (uint8_t*)from_thread->tf, sizeof(trapframe_t));
     memcpy((uint8_t*)new_proc->main_thread->fpu_state, (uint8_t*)from_thread->fpu_state, sizeof(fpu_state_t));
     new_proc->cwd = dentry_duplicate(from_proc->cwd);
     new_proc->tty = from_proc->tty;
     /* TODO: change the size in advance */
     for (int i = 0; i < from_proc->zones.size; i++) {
         proc_zone_t* zone_to_copy = (proc_zone_t*)dynamic_array_get(&from_proc->zones, i);
         dynamic_array_push(&new_proc->zones, zone_to_copy);
     }
     if (from_proc->fds) {
         for (int i = 0; i < MAX_OPENED_FILES; i++) {
             if (from_proc->fds[i].dentry) {
                 file_descriptor_t* fd = &new_proc->fds[i];
                 if (from_proc->fds[i].type == FD_TYPE_FILE) {
                     vfs_open(from_proc->fds[i].dentry, fd, from_proc->fds[i].flags);
                 }
             }
         }
     }
     return 0;
 }
References proc::cwd, file_descriptor::dentry, dentry_duplicate(), dynamic_array_get(), dynamic_array_push(), FD_TYPE_FILE, proc::fds, file_descriptor::flags, thread::fpu_state, proc::main_thread, MAX_OPENED_FILES, memcpy(), thread::process, dynamic_array::size, thread::tf, proc::tty, file_descriptor::type, vfs_open(), and proc::zones.
Referenced by tasking_fork().
proc_create_thread()
struct thread* proc_create_thread (proc_t * p)
PROC THREAD FUNCTIONS
Definition at line 282 of file proc.c.
 {
     thread_t* thread = proc_alloc_thread();
     thread_setup(p, thread);
     sched_enqueue(thread);
     return thread;
 }
References p, proc_alloc_thread(), sched_enqueue(), and thread_setup().
Referenced by sys_create_thread().
proc_die()
int proc_die (proc_t * p)
Definition at line 267 of file proc.c.
 {
     FOREACH_THREAD(p)
     {
         thread_die(thread);
     }
     END_FOREACH
     p->status = PROC_DYING;
     return 0;
 }
References END_FOREACH, FOREACH_THREAD, p, PROC_DYING, and thread_die().
Referenced by isr_handler(), signal_process(), signal_restore_thread_after_handling_signal(), and tasking_exit().
proc_fill_up_stack()
int proc_fill_up_stack (proc_t * p, int argc, char ** argv, char ** env)
proc_find_zone()
proc_zone_t* proc_find_zone (proc_t * p, uint32_t addr)
Definition at line 127 of file proc_zoner.c.
 {
     uint32_t zones_count = proc->zones.size;
     for (uint32_t i = 0; i < zones_count; i++) {
         proc_zone_t* zone = (proc_zone_t*)dynamic_array_get(&proc->zones, i);
         if (zone->start <= addr && addr < zone->start + zone->len) {
             return zone;
         }
     }
     return 0;
 }
References dynamic_array_get(), proc_zone::len, dynamic_array::size, proc_zone::start, and proc::zones.
Referenced by vmm_page_fault_handler().
proc_free()
int proc_free (proc_t * p)
PROC FREE FUNCTIONS
Definition at line 232 of file proc.c.
 {
     if (p->status == PROC_DEAD || p->status == PROC_INVALID || p->status == PROC_ALIVE || p->pid == 0) {
         return -ESRCH;
     }
     /* closing opend fds */
     if (p->fds) {
         for (int i = 0; i < MAX_OPENED_FILES; i++) {
             if (p->fds[i].dentry) {
                 /* think as an active fd */
                 vfs_close(&p->fds[i]);
             }
         }
         kfree(p->fds);
     }
     if (p->cwd) {
         dentry_put(p->cwd);
     }
     dynamic_array_free(&p->zones);
     /* Key parts deletion. After that line you can't work with this process. */
     proc_kill_all_threads(p);
     p->pid = 0;
     if (!p->is_kthread) {
         vmm_free_pdir(p->pdir);
         p->pdir = 0;
     }
     return 0;
 }
References dentry_put(), dynamic_array_free(), ESRCH, kfree(), MAX_OPENED_FILES, p, PROC_ALIVE, PROC_DEAD, PROC_INVALID, proc_kill_all_threads(), vfs_close(), and vmm_free_pdir().
Referenced by kthread_free(), and tasking_kill_dying().
proc_get_fd()
file_descriptor_t* proc_get_fd (proc_t * p, uint32_t index)
Definition at line 367 of file proc.c.
 {
     ASSERT(p->fds);
     if (index >= MAX_OPENED_FILES) {
         return 0;
     }
     if (!p->fds[index].dentry) {
         return 0;
     }
     return &p->fds[index];
 }
References ASSERT, MAX_OPENED_FILES, and p.
Referenced by should_unblock_select_block(), sys_bind(), sys_close(), sys_connect(), sys_fstat(), sys_getdents(), sys_ioctl(), sys_lseek(), sys_mmap(), sys_read(), sys_select(), and sys_write().
proc_get_fd_id()
int proc_get_fd_id (proc_t * proc, file_descriptor_t * fd)
Definition at line 340 of file proc.c.
 {
     ASSERT(p->fds);
     /* Calculating id with pointers */
     uint32_t start = (uint32_t)p->fds;
     uint32_t fd_ptr = (uint32_t)fd;
     fd_ptr -= start;
     int fd_res = fd_ptr / sizeof(file_descriptor_t);
     if (!(fd_ptr % sizeof(file_descriptor_t))) {
         return fd_res;
     }
     return -1;
 }
References ASSERT, and p.
Referenced by sys_creat(), sys_open(), and sys_socket().
proc_get_free_fd()
file_descriptor_t* proc_get_free_fd (proc_t * p)
Definition at line 354 of file proc.c.
 {
     ASSERT(p->fds);
     for (int i = 0; i < MAX_OPENED_FILES; i++) {
         if (!p->fds[i].dentry) {
             return &p->fds[i];
         }
     }
     return 0;
 }
References ASSERT, MAX_OPENED_FILES, and p.
Referenced by sys_creat(), sys_open(), and sys_socket().
proc_kill_all_threads()
void proc_kill_all_threads (proc_t * p)
Definition at line 290 of file proc.c.
 {
     FOREACH_THREAD(p)
     {
         thread_free(thread);
     }
     END_FOREACH
 }
References END_FOREACH, FOREACH_THREAD, p, and thread_free().
Referenced by proc_free().
proc_kill_all_threads_except()
void proc_kill_all_threads_except (proc_t * p, struct thread * gthread)
Definition at line 299 of file proc.c.
 {
     FOREACH_THREAD(p)
     {
         if (thread->tid != gthread->tid)
             thread_free(thread);
     }
     END_FOREACH
 }
References END_FOREACH, FOREACH_THREAD, p, thread_free(), and thread::tid.
Referenced by tasking_exec().
proc_load()
int proc_load (proc_t * p, const char * path)
Definition at line 193 of file proc.c.
 {
     dentry_t* file;
     file_descriptor_t fd;
     if (vfs_resolve_path_start_from(p->cwd, path, &file) < 0) {
         return -ENOENT;
     }
     if (vfs_open(file, &fd, O_RDONLY) < 0) {
         dentry_put(file);
         return -ENOENT;
     }
     pdirectory_t* old_pdir = p->pdir;
     pdirectory_t* new_pdir = vmm_new_user_pdir();
     vmm_switch_pdir(new_pdir);
     p->pdir = new_pdir;
     int err = _proc_load_bin(p, &fd);
     if (!err) {
         if (!p->cwd) {
             p->cwd = dentry_get_parent(file);
         }
         vmm_free_pdir(old_pdir);
     } else {
         p->pdir = old_pdir;
         vmm_switch_pdir(old_pdir);
         vmm_free_pdir(new_pdir);
     }
     dentry_put(file);
     vfs_close(&fd);
     return err;
 }
References _proc_load_bin(), dentry_get_parent(), dentry_put(), ENOENT, O_RDONLY, p, vfs_close(), vfs_open(), vfs_resolve_path_start_from(), vmm_free_pdir(), vmm_new_user_pdir(), and vmm_switch_pdir().
Referenced by _tasking_do_exec(), and tasking_start_init_proc().
proc_new_random_zone()
proc_zone_t* proc_new_random_zone (proc_t * p, uint32_t len)
Definition at line 62 of file proc_zoner.c.
 {
     if (len % VMM_PAGE_SIZE) {
         len += VMM_PAGE_SIZE - (len % VMM_PAGE_SIZE);
     }
     uint32_t zones_count = proc->zones.size;
     /* Check if we can put it at the beginning */
     proc_zone_t* ret = proc_new_zone(proc, 0, len);
     if (ret) {
         return ret;
     }
     uint32_t min_start = 0xffffffff;
     for (uint32_t i = 0; i < zones_count; i++) {
         proc_zone_t* zone = (proc_zone_t*)dynamic_array_get(&proc->zones, i);
         if (_proc_can_add_zone(proc, zone->start + zone->len, len)) {
             if (min_start > zone->start + zone->len) {
                 min_start = zone->start + zone->len;
             }
         }
     }
     if (min_start == 0xffffffff) {
         return 0;
     }
     return proc_new_zone(proc, min_start, len);
 }
References _proc_can_add_zone(), dynamic_array_get(), proc_zone::len, proc_new_zone(), dynamic_array::size, proc_zone::start, VMM_PAGE_SIZE, and proc::zones.
Referenced by _bga_mmap(), _proc_load_bin(), _vfs_do_mmap(), and sys_mmap().
proc_new_random_zone_backward()
proc_zone_t* proc_new_random_zone_backward (proc_t * p, uint32_t len)
Definition at line 95 of file proc_zoner.c.
 {
     if (len % VMM_PAGE_SIZE) {
         len += VMM_PAGE_SIZE - (len % VMM_PAGE_SIZE);
     }
     uint32_t zones_count = proc->zones.size;
     /* Check if we can put it at the end */
     proc_zone_t* ret = proc_new_zone(proc, KERNEL_BASE - len, len);
     if (ret) {
         return ret;
     }
     uint32_t max_end = 0;
     for (uint32_t i = 0; i < zones_count; i++) {
         proc_zone_t* zone = (proc_zone_t*)dynamic_array_get(&proc->zones, i);
         if (_proc_can_add_zone(proc, zone->start - len, len)) {
             if (max_end < zone->start) {
                 max_end = zone->start;
             }
         }
     }
     if (max_end == 0) {
         return 0;
     }
     return proc_new_zone(proc, max_end - len, len);
 }
References _proc_can_add_zone(), dynamic_array_get(), KERNEL_BASE, proc_new_zone(), dynamic_array::size, proc_zone::start, VMM_PAGE_SIZE, and proc::zones.
Referenced by _proc_load_bin(), and sys_mmap().
proc_new_zone()
proc_zone_t* proc_new_zone (proc_t * p, uint32_t start, uint32_t len)
PROC ZONER FUNCTIONS
Definition at line 39 of file proc_zoner.c.
 {
     if (len % VMM_PAGE_SIZE) {
         len += VMM_PAGE_SIZE - (len % VMM_PAGE_SIZE);
     }
     proc_zone_t new_zone;
     new_zone.start = start;
     new_zone.len = len;
     new_zone.type = 0;
     new_zone.flags = ZONE_USER;
     if (_proc_can_add_zone(proc, start, len)) {
         if (dynamic_array_push(&proc->zones, &new_zone) != 0) {
             return 0;
         }
         return (proc_zone_t*)dynamic_array_get(&proc->zones, proc->zones.size - 1);
     }
     return 0;
 }
References _proc_can_add_zone(), dynamic_array_get(), dynamic_array_push(), proc_zone::flags, proc_zone::len, dynamic_array::size, proc_zone::start, proc_zone::type, VMM_PAGE_SIZE, ZONE_USER, and proc::zones.
Referenced by proc_new_random_zone(), and proc_new_random_zone_backward().
proc_setup()
int proc_setup (proc_t * p)
INIT FUNCTIONS
Definition at line 65 of file proc.c.
 {
     p->pid = proc_alloc_pid();
     p->pgid = p->pid;
     p->is_kthread = false;
     p->main_thread = proc_alloc_thread();
     int res = thread_setup_main(p, p->main_thread);
     if (res != 0) {
         return res;
     }
     /* setting current work directory */
     p->cwd = 0;
     /* allocating space for open files */
     p->fds = kmalloc(MAX_OPENED_FILES * sizeof(file_descriptor_t));
     if (!p->fds) {
         return -ENOMEM;
     }
     memset((void*)p->fds, 0, MAX_OPENED_FILES * sizeof(file_descriptor_t));
     /* setting up zones */
     if (dynamic_array_init_of_size(&p->zones, sizeof(proc_zone_t), 8) != 0) {
         return -ENOMEM;
     }
     p->status = PROC_ALIVE;
     p->prio = DEFAULT_PRIO;
     return 0;
 }
References DEFAULT_PRIO, dynamic_array_init_of_size(), ENOMEM, kmalloc(), MAX_OPENED_FILES, memset(), p, PROC_ALIVE, proc_alloc_pid(), proc_alloc_thread(), and thread_setup_main().
Referenced by _tasking_alloc_proc().
proc_setup_tty()
int proc_setup_tty (proc_t * p, tty_entry_t * tty)
Definition at line 98 of file proc.c.
 {
     file_descriptor_t* fd0 = &p->fds[0];
     file_descriptor_t* fd1 = &p->fds[1];
     p->tty = tty;
     char* path_to_tty = "/dev/tty ";
     path_to_tty[8] = tty->id + '0';
     dentry_t* tty_dentry;
     if (vfs_resolve_path(path_to_tty, &tty_dentry) < 0) {
         return -ENOENT;
     }
     int err = vfs_open(tty_dentry, fd0, O_RDWR);
     if (err) {
         return err;
     }
     err = vfs_open(tty_dentry, fd1, O_RDWR);
     if (err) {
         return err;
     }
     dentry_put(tty_dentry);
     return 0;
 }
References dentry_put(), ENOENT, tty_entry::id, O_RDWR, p, vfs_open(), and vfs_resolve_path().
Referenced by tasking_start_init_proc().
thread_by_pid()
struct thread* thread_by_pid (uint32_t pid)
Definition at line 46 of file proc.c.
 {
     for (int i = 0; i < threads_cnt; i++) {
         if (thread_storage[i].tid == pid) {
             return &thread_storage[i];
         }
     }
     return 0;
 }
References thread_storage, and threads_cnt.
Referenced by sys_kill().