oneOS: src/kernel/platform/x86/vmm/pte.c File Reference
pte.c File Reference
#include <platform/x86/vmm/pte.h>
#include <mem/vmm/vmm.h>
Functions
void page_desc_set_attrs (page_desc_t *pte, uint32_t attrs)
void page_desc_del_attrs (page_desc_t *pte, uint32_t attrs)
bool page_desc_has_attrs (page_desc_t pte, uint32_t attrs)
void page_desc_set_frame (page_desc_t *pte, uint32_t frame)
void page_desc_del_frame (page_desc_t *pte)
bool page_desc_is_present (page_desc_t pte)
bool page_desc_is_writable (page_desc_t pte)
bool page_desc_is_user (page_desc_t pte)
bool page_desc_is_not_cacheable (page_desc_t pte)
bool page_desc_is_cow (page_desc_t pte)
uint32_t page_desc_get_frame (page_desc_t pte)
uint32_t page_desc_get_settings (page_desc_t pte)
uint32_t page_desc_get_settings_ignore_cow (page_desc_t pte)
Function Documentation
page_desc_del_attrs()
void page_desc_del_attrs (page_desc_t * pte, uint32_t attrs)
Definition at line 17 of file pte.c.
 {
     *pte &= ~(attrs);
 }
page_desc_del_frame()
void page_desc_del_frame (page_desc_t * pte)
Definition at line 33 of file pte.c.
 {
     *pte &= ((1 << (PAGE_DESC_FRAME_OFFSET)) - 1);
 }
References PAGE_DESC_FRAME_OFFSET.
Referenced by page_desc_set_frame().
page_desc_get_frame()
uint32_t page_desc_get_frame (page_desc_t pte)
Definition at line 63 of file pte.c.
 {
     return ((pte >> PAGE_DESC_FRAME_OFFSET) << PAGE_DESC_FRAME_OFFSET);
 }
References PAGE_DESC_FRAME_OFFSET.
page_desc_get_settings()
uint32_t page_desc_get_settings (page_desc_t pte)
Definition at line 68 of file pte.c.
 {
     uint32_t res = PAGE_READABLE;
     if (page_desc_is_writable(pte)) {
         res |= PAGE_WRITABLE;
     }
     if (page_desc_is_user(pte)) {
         res |= PAGE_USER;
     }
     if (page_desc_is_not_cacheable(pte)) {
         res |= PAGE_NOT_CACHEABLE;
     }
     if (page_desc_is_cow(pte)) {
         res |= PAGE_COW;
     }
     return res;
 }
References PAGE_COW, page_desc_is_cow(), page_desc_is_not_cacheable(), page_desc_is_user(), page_desc_is_writable(), PAGE_NOT_CACHEABLE, PAGE_READABLE, PAGE_USER, and PAGE_WRITABLE.
page_desc_get_settings_ignore_cow()
uint32_t page_desc_get_settings_ignore_cow (page_desc_t pte)
Definition at line 86 of file pte.c.
 {
     uint32_t res = PAGE_READABLE;
     if (page_desc_is_writable(pte)) {
         res |= PAGE_WRITABLE;
     }
     if (page_desc_is_user(pte)) {
         res |= PAGE_USER;
     }
     if (page_desc_is_not_cacheable(pte)) {
         res |= PAGE_NOT_CACHEABLE;
     }
     return res;
 }
References page_desc_is_not_cacheable(), page_desc_is_user(), page_desc_is_writable(), PAGE_NOT_CACHEABLE, PAGE_READABLE, PAGE_USER, and PAGE_WRITABLE.
page_desc_has_attrs()
bool page_desc_has_attrs (page_desc_t pte, uint32_t attrs)
Definition at line 22 of file pte.c.
 {
     return ((pte & attrs) > 0);
 }
page_desc_is_cow()
bool page_desc_is_cow (page_desc_t pte)
Definition at line 58 of file pte.c.
 {
     return ((pte & PAGE_DESC_COPY_ON_WRITE) > 0);
 }
References PAGE_DESC_COPY_ON_WRITE.
Referenced by page_desc_get_settings().
page_desc_is_not_cacheable()
bool page_desc_is_not_cacheable (page_desc_t pte)
Definition at line 53 of file pte.c.
 {
     return ((pte & PAGE_DESC_NOT_CACHEABLE) > 0);
 }
References PAGE_DESC_NOT_CACHEABLE.
Referenced by page_desc_get_settings(), and page_desc_get_settings_ignore_cow().
page_desc_is_present()
bool page_desc_is_present (page_desc_t pte)
Definition at line 38 of file pte.c.
 {
     return ((pte & PAGE_DESC_PRESENT) > 0);
 }
References PAGE_DESC_PRESENT.
page_desc_is_user()
bool page_desc_is_user (page_desc_t pte)
Definition at line 48 of file pte.c.
 {
     return ((pte & PAGE_DESC_USER) > 0);
 }
References PAGE_DESC_USER.
Referenced by page_desc_get_settings(), and page_desc_get_settings_ignore_cow().
page_desc_is_writable()
bool page_desc_is_writable (page_desc_t pte)
Definition at line 43 of file pte.c.
 {
     return ((pte & PAGE_DESC_WRITABLE) > 0);
 }
References PAGE_DESC_WRITABLE.
Referenced by page_desc_get_settings(), and page_desc_get_settings_ignore_cow().
page_desc_set_attrs()
void page_desc_set_attrs (page_desc_t * pte, uint32_t attrs)
Definition at line 12 of file pte.c.
 {
     *pte |= attrs;
 }
page_desc_set_frame()
void page_desc_set_frame (page_desc_t * pte, uint32_t frame)
Definition at line 27 of file pte.c.
 {
     page_desc_del_frame(pte);
     *pte |= (frame << PAGE_DESC_FRAME_OFFSET);
 }
References page_desc_del_frame(), and PAGE_DESC_FRAME_OFFSET.