oneOS: include/io/tty/ptmx.h File Reference
ptmx.h File Reference
Functions
int ptmx_install ()
Function Documentation
ptmx_install()
int ptmx_install ()
Definition at line 37 of file ptmx.c.
 {
     dentry_t* mp;
     if (vfs_resolve_path("/dev", &mp) < 0) {
         return -1;
     }
     file_ops_t fops;
     fops.open = ptmx_open;
     fops.can_read = ptmx_can_read;
     fops.can_write = ptmx_can_write;
     fops.read = ptmx_read;
     fops.write = ptmx_write;
     fops.ioctl = 0;
     devfs_inode_t* res = devfs_register(mp, "ptmx", 4, 0, &fops);
     dentry_put(mp);
     return 0;
 }
References file_ops::can_read, file_ops::can_write, dentry_put(), devfs_register(), file_ops::ioctl, file_ops::open, ptmx_can_read(), ptmx_can_write(), ptmx_open(), ptmx_read(), ptmx_write(), file_ops::read, vfs_resolve_path(), and file_ops::write.
Referenced by stage3().