oneOS: src/kernel/io/tty/ptmx.c File Reference
ptmx.c File Reference
#include <fs/devfs/devfs.h>
#include <io/tty/ptmx.h>
#include <io/tty/pty_master.h>
#include <log.h>
Functions
bool ptmx_can_read (dentry_t *dentry, uint32_t start)
bool ptmx_can_write (dentry_t *dentry, uint32_t start)
int ptmx_read (dentry_t *dentry, uint8_t *buf, uint32_t start, uint32_t len)
int ptmx_write (dentry_t *dentry, uint8_t *buf, uint32_t start, uint32_t len)
int ptmx_open (dentry_t *dentry, struct file_descriptor *fd, uint32_t flags)
int ptmx_install ()
Function Documentation
ptmx_can_read()
bool ptmx_can_read (dentry_t * dentry, uint32_t start)
Definition at line 8 of file ptmx.c.
 {
     return true;
 }
Referenced by ptmx_install().
ptmx_can_write()
bool ptmx_can_write (dentry_t * dentry, uint32_t start)
Definition at line 13 of file ptmx.c.
 {
     return true;
 }
Referenced by ptmx_install().
ptmx_install()
int ptmx_install ()
Definition at line 37 of file ptmx.c.
 {
     dentry_t* mp;
     if (vfs_resolve_path("/dev", &mp) < 0) {
         return -1;
     }
     file_ops_t fops;
     fops.open = ptmx_open;
     fops.can_read = ptmx_can_read;
     fops.can_write = ptmx_can_write;
     fops.read = ptmx_read;
     fops.write = ptmx_write;
     fops.ioctl = 0;
     devfs_inode_t* res = devfs_register(mp, "ptmx", 4, 0, &fops);
     dentry_put(mp);
     return 0;
 }
References file_ops::can_read, file_ops::can_write, dentry_put(), devfs_register(), file_ops::ioctl, file_ops::open, ptmx_can_read(), ptmx_can_write(), ptmx_open(), ptmx_read(), ptmx_write(), file_ops::read, vfs_resolve_path(), and file_ops::write.
Referenced by stage3().
ptmx_open()
int ptmx_open (dentry_t * dentry, struct file_descriptor * fd, uint32_t flags)
Definition at line 28 of file ptmx.c.
 {
 #ifdef PTY_DEBUG
     log("Opening ptmx");
 #endif
     pty_master_alloc(fd);
     return 0;
 }
References log(), and pty_master_alloc().
Referenced by ptmx_install().
ptmx_read()
int ptmx_read (dentry_t * dentry, uint8_t * buf, uint32_t start, uint32_t len)
Definition at line 18 of file ptmx.c.
 {
     return 0;
 }
Referenced by ptmx_install().
ptmx_write()
int ptmx_write (dentry_t * dentry, uint8_t * buf, uint32_t start, uint32_t len)
Definition at line 23 of file ptmx.c.
 {
     return 0;
 }
Referenced by ptmx_install().