oneOS: include/io/tty/pty_slave.h File Reference
pty_slave.h File Reference
Data Structures
struct pty_slave_entry
Macros
#define PTYS_COUNT 4
Typedefs
typedef struct pty_slave_entry pty_slave_entry_t
Functions
int pty_slave_create (int id, struct pty_master_entry *ptm)
Variables
pty_slave_entry_t pty_slaves [4]
Macro Definition Documentation
PTYS_COUNT
#define PTYS_COUNT 4
Definition at line 5 of file pty_slave.h.
Typedef Documentation
pty_slave_entry_t
typedef struct pty_slave_entry pty_slave_entry_t
Definition at line 1 of file pty_slave.h.
Function Documentation
pty_slave_create()
int pty_slave_create (int id, struct pty_master_entry * ptm)
Definition at line 58 of file pty_slave.c.
 {
     ASSERT(0 < id && id < 10 && id <= PTYS_COUNT);
     dentry_t* mp;
     if (vfs_resolve_path("/dev", &mp) < 0) {
         return 0;
     }
     char* name = "pts ";
     name[3] = id + '0';
     file_ops_t fops;
     fops.open = 0;
     fops.can_read = pty_slave_can_read;
     fops.can_write = pty_slave_can_write;
     fops.read = pty_slave_read;
     fops.write = pty_slave_write;
     fops.ioctl = pty_slave_ioctl;
     devfs_inode_t* res = devfs_register(mp, name, 4, 0, &fops);
     pty_slaves[id].inode_indx = res->index;
     pty_slaves[id].ptm = ptm;
     pty_slaves[id].buffer = ringbuffer_create_std();
     ASSERT(pty_slaves[id].buffer.zone.start);
     ptm->pts = &pty_slaves[id];
     dentry_put(mp);
     return 0;
 }
References ASSERT, pty_slave_entry::buffer, file_ops::can_read, file_ops::can_write, dentry_put(), devfs_register(), devfs_inode::index, pty_slave_entry::inode_indx, file_ops::ioctl, copy_bin::name, file_ops::open, pty_slave_entry::ptm, pty_master_entry::pts, pty_slave_can_read(), pty_slave_can_write(), pty_slave_ioctl(), pty_slave_read(), pty_slave_write(), pty_slaves, PTYS_COUNT, file_ops::read, ringbuffer_create_std(), vfs_resolve_path(), and file_ops::write.
Referenced by pty_master_alloc().
Variable Documentation
pty_slaves
pty_slave_entry_t pty_slaves[4] extern
Definition at line 7 of file pty_slave.c.
Referenced by _pts_get(), and pty_slave_create().