oneOS: include/io/tty/pty_master.h File Reference
pty_master.h File Reference
#include <fs/vfs.h>
Data Structures
struct pty_master_entry
Macros
#define PTYS_COUNT 4
Typedefs
typedef struct pty_master_entry pty_master_entry_t
Functions
int pty_master_alloc (file_descriptor_t *fd)
Variables
pty_master_entry_t pty_masters [4]
Macro Definition Documentation
PTYS_COUNT
#define PTYS_COUNT 4
Definition at line 7 of file pty_master.h.
Typedef Documentation
pty_master_entry_t
typedef struct pty_master_entry pty_master_entry_t
Definition at line 1 of file pty_master.h.
Function Documentation
pty_master_alloc()
int pty_master_alloc (file_descriptor_t * fd)
Definition at line 98 of file pty_master.c.
 {
     pty_master_entry_t* ptm = 0;
     for (int i = 0; i < PTYS_COUNT; i++) {
         if (pty_masters[i].dentry.inode_indx == 0) {
             /* According to dentry.c when inode_indx==0, dentry is free */
             ptm = &pty_masters[i];
             ptm->dentry.inode_indx = i + 1;
             break;
         }
     }
     if (!ptm) {
         return -EBUSY;
     }
     /*
        DENTRY_CUSTOM is set for the dentry, since it's not a cache of
        a file (or a dir). We also set a required function for this
        type of dentries free_inode, which is called when dentry is
        freed.
        DENTRY_PRIVATE shows that dentry and fd, shouldn't be copied
        when a new process is forked.
     */
     ptm->dentry.d_count = 1;
     ptm->dentry.flags = 0;
     dentry_set_flag(&ptm->dentry, DENTRY_PRIVATE);
     dentry_set_flag(&ptm->dentry, DENTRY_CUSTOM);
     ptm->dentry.ops = &pty_master_ops;
     fd->dentry = &ptm->dentry;
     fd->ops = &pty_master_ops.file;
     fd->mapped_times = 0;
     fd->flags = 0;
     fd->offset = 0;
     fd->type = FD_TYPE_FILE;
     pty_slave_create(ptm->dentry.inode_indx, ptm);
     ptm->buffer = ringbuffer_create_std();
     return 0;
 }
References pty_master_entry::buffer, dentry::d_count, file_descriptor::dentry, pty_master_entry::dentry, DENTRY_CUSTOM, DENTRY_PRIVATE, dentry_set_flag(), EBUSY, FD_TYPE_FILE, fs_ops::file, dentry::flags, file_descriptor::flags, dentry::inode_indx, file_descriptor::mapped_times, file_descriptor::offset, dentry::ops, file_descriptor::ops, pty_master_ops, pty_masters, pty_slave_create(), PTYS_COUNT, ringbuffer_create_std(), and file_descriptor::type.
Referenced by ptmx_open().
Variable Documentation
pty_masters
pty_master_entry_t pty_masters[4] extern
Since pty masters are virtual files and don't present on real hd, we use an array of dentries. This dentries won't be present in the list of dentries (dentry.c), so other threads con't access it.
Definition at line 13 of file pty_master.c.
Referenced by _ptm_get(), and pty_master_alloc().