oneOS: libs/libfoundation/puff.h File Reference
puff.h File Reference
Macros
#define NIL ((unsigned char*)0) /* for no output option */
Functions
int puff (unsigned char *dest, unsigned long *destlen, const unsigned char *source, unsigned long *sourcelen)
Macro Definition Documentation
NIL
#define NIL ((unsigned char*)0) /* for no output option */
Definition at line 34 of file puff.h.
Function Documentation
puff()
int puff (unsigned char * dest, unsigned long * destlen, const unsigned char * source, unsigned long * sourcelen)
Definition at line 793 of file puff.c.
 {
     struct state s;             /* input/output state */
     int last, type;             /* block information */
     int err;                    /* return value */
     /* initialize output state */
     s.out = dest;
     s.outlen = *destlen;                /* ignored if dest is NIL */
     s.outcnt = 0;
     /* initialize input state */
     s.in = source;
     s.inlen = *sourcelen;
     s.incnt = 0;
     s.bitbuf = 0;
     s.bitcnt = 0;
     /* return if bits() or decode() tries to read past available input */
     if (setjmp(s.env) != 0)             /* if came back here via longjmp() */
         err = 2;                        /* then skip do-loop, return error */
     else {
         /* process blocks until last block or error */
         do {
             last = bits(&s, 1);         /* one if last block */
             type = bits(&s, 2);         /* block type 0..3 */
             err = type == 0 ?
                     stored(&s) :
                     (type == 1 ?
                         fixed(&s) :
                         (type == 2 ?
                             dynamic(&s) :
                             -1));       /* type == 3, invalid */
             if (err != 0)
                 break;                  /* return with error */
         } while (!last);
     }
     /* update the lengths and return */
     if (err <= 0) {
         *destlen = s.outcnt;
         *sourcelen = s.incnt;
     }
     return err;
 }
References state::bitbuf, state::bitcnt, bits(), dynamic(), state::env, fixed(), state::in, state::incnt, state::inlen, state::out, state::outcnt, state::outlen, setjmp(), stored(), and type.
Referenced by LG::PNG::PNGLoader::read_IDAT().