oneOS: src/kernel/algo/ringbuffer.c File Reference
ringbuffer.c File Reference
#include <algo/ringbuffer.h>
#include <mem/vmm/vmm.h>
Macros
#define BUFFER_STD_SIZE (16 * KB)
Functions
ringbuffer_t ringbuffer_create (uint32_t size)
ringbuffer_t ringbuffer_create_std ()
void ringbuffer_free (ringbuffer_t *buf)
uint32_t ringbuffer_space_to_read (ringbuffer_t *buf)
uint32_t ringbuffer_space_to_read_with_custom_start (ringbuffer_t *buf, uint32_t start)
uint32_t ringbuffer_space_to_write (ringbuffer_t *buf)
uint32_t ringbuffer_read (ringbuffer_t *buf, uint8_t *holder, uint32_t siz)
uint32_t ringbuffer_read_with_start (ringbuffer_t *buf, uint32_t start, uint8_t *holder, uint32_t siz)
uint32_t ringbuffer_read_one (ringbuffer_t *buf, uint8_t *data)
uint32_t ringbuffer_write (ringbuffer_t *buf, const uint8_t *holder, uint32_t siz)
uint32_t ringbuffer_write_ignore_bounds (ringbuffer_t *buf, const uint8_t *holder, uint32_t siz)
uint32_t ringbuffer_write_one (ringbuffer_t *buf, uint8_t data)
void ringbuffer_clear (ringbuffer_t *buf)
Macro Definition Documentation
BUFFER_STD_SIZE
#define BUFFER_STD_SIZE (16 * KB)
Definition at line 4 of file ringbuffer.c.
Function Documentation
ringbuffer_clear()
void ringbuffer_clear (ringbuffer_t * buf)
Definition at line 155 of file ringbuffer.c.
 {
     buf->start = 0;
     buf->end = 0;
 }
References buf.
Referenced by _tty_flush_input().
ringbuffer_create()
ringbuffer_t ringbuffer_create (uint32_t size)
Definition at line 6 of file ringbuffer.c.
 {
     ringbuffer_t buf;
     buf.zone = zoner_new_zone(size);
     if (!buf.zone.start) {
         return buf;
     }
     buf.start = 0;
     buf.end = 0;
     return buf;
 }
References buf, and zoner_new_zone().
ringbuffer_create_std()
ringbuffer_t ringbuffer_create_std ()
Definition at line 18 of file ringbuffer.c.
 {
     ringbuffer_t buf;
     buf.zone = zoner_new_zone(BUFFER_STD_SIZE);
     if (!buf.zone.start) {
         return buf;
     }
     buf.start = 0;
     buf.end = 0;
     return buf;
 }
References buf, BUFFER_STD_SIZE, and zoner_new_zone().
Referenced by _socket_create(), kbdriver_run(), mouse_run(), pty_master_alloc(), pty_slave_create(), and tty_new().
ringbuffer_free()
void ringbuffer_free (ringbuffer_t * buf)
Definition at line 30 of file ringbuffer.c.
 {
     zoner_free_zone(buf->zone);
     buf->start = 0;
     buf->end = 0;
 }
References buf, and zoner_free_zone().
Referenced by socket_put().
ringbuffer_read()
uint32_t ringbuffer_read (ringbuffer_t * buf, uint8_t * holder, uint32_t siz)
Definition at line 65 of file ringbuffer.c.
 {
     uint32_t i = 0;
     if (buf->start > buf->end) {
         for (; i < siz && buf->start < buf->zone.len; i++, buf->start++) {
             holder[i] = buf->zone.ptr[buf->start];
         }
         if (buf->start == buf->zone.len) {
             buf->start = 0;
         }
     }
     for (; i < siz && buf->start < buf->end; i++, buf->start++) {
         holder[i] = buf->zone.ptr[buf->start];
     }
     return i;
 }
References buf.
Referenced by _kbdriver_read(), _mouse_read(), pty_master_read(), pty_slave_read(), and tty_read().
ringbuffer_read_one()
uint32_t ringbuffer_read_one (ringbuffer_t * buf, uint8_t * data)
Definition at line 100 of file ringbuffer.c.
 {
     if (buf->start != buf->end) {
         *data = buf->zone.ptr[buf->start];
         buf->start++;
         if (buf->start == buf->zone.len) {
             buf->start = 0;
         }
         return 1;
     }
     return 0;
 }
References buf.
ringbuffer_read_with_start()
uint32_t ringbuffer_read_with_start (ringbuffer_t * buf, uint32_t start, uint8_t * holder, uint32_t siz)
Definition at line 82 of file ringbuffer.c.
 {
     uint32_t i = 0;
     start %= buf->zone.len;
     if (start > buf->end) {
         for (; i < siz && start < buf->zone.len; i++, start++) {
             holder[i] = buf->zone.ptr[start];
         }
         if (start == buf->zone.len) {
             start = 0;
         }
     }
     for (; i < siz && start < buf->end; i++, start++) {
         holder[i] = buf->zone.ptr[start];
     }
     return i;
 }
References buf.
Referenced by local_socket_read().
ringbuffer_space_to_read()
uint32_t ringbuffer_space_to_read (ringbuffer_t * buf)
Definition at line 37 of file ringbuffer.c.
 {
     if (buf->start <= buf->end) {
         return buf->end - buf->start;
     } else {
         return buf->zone.len - buf->start + buf->end;
     }
 }
References buf.
Referenced by _kbdriver_can_read(), _kbdriver_read(), _mouse_can_read(), _mouse_read(), pty_master_can_read(), pty_master_read(), pty_slave_can_read(), pty_slave_read(), tty_can_read(), tty_eat_key(), and tty_read().
ringbuffer_space_to_read_with_custom_start()
uint32_t ringbuffer_space_to_read_with_custom_start (ringbuffer_t * buf, uint32_t start)
Definition at line 46 of file ringbuffer.c.
 {
     start %= buf->zone.len;
     if (start <= buf->end) {
         return buf->end - start;
     } else {
         return buf->zone.len - start + buf->end;
     }
 }
References buf.
Referenced by local_socket_can_read().
ringbuffer_space_to_write()
uint32_t ringbuffer_space_to_write (ringbuffer_t * buf)
Definition at line 56 of file ringbuffer.c.
 {
     if (buf->start > buf->end) {
         return buf->start - buf->end;
     } else {
         return buf->zone.len - buf->end + buf->start;
     }
 }
References buf.
Referenced by pty_master_can_write(), and pty_slave_can_write().
ringbuffer_write()
uint32_t ringbuffer_write (ringbuffer_t * buf, const uint8_t * holder, uint32_t siz)
Definition at line 113 of file ringbuffer.c.
 {
     uint32_t i = 0;
     if (buf->end >= buf->start) {
         for (; i < siz && buf->end < buf->zone.len; i++, buf->end++) {
             buf->zone.ptr[buf->end] = holder[i];
         }
         if (buf->end == buf->zone.len) {
             buf->end = 0;
         }
     }
     for (; i < siz && buf->end < buf->start; i++, buf->end++) {
         buf->zone.ptr[buf->end] = holder[i];
     }
     return i;
 }
References buf.
Referenced by keyboard_handler(), mouse_handler(), pty_master_write(), and pty_slave_write().
ringbuffer_write_ignore_bounds()
uint32_t ringbuffer_write_ignore_bounds (ringbuffer_t * buf, const uint8_t * holder, uint32_t siz)
Definition at line 130 of file ringbuffer.c.
 {
     uint32_t i = 0;
     for (; i < siz; i++) {
         buf->zone.ptr[buf->end++] = holder[i];
         if (buf->end == buf->zone.len) {
             buf->end = 0;
         }
     }
     return i;
 }
References buf.
Referenced by local_socket_write().
ringbuffer_write_one()
uint32_t ringbuffer_write_one (ringbuffer_t * buf, uint8_t data)
Definition at line 142 of file ringbuffer.c.
 {
     if (buf->end + 1 != buf->start) {
         buf->zone.ptr[buf->end] = data;
         buf->end++;
         if (buf->end == buf->zone.len) {
             buf->end = 0;
         }
         return 1;
     }
     return 0;
 }
References buf.
Referenced by tty_eat_key().