oneOS: src/kernel/drivers/x86/rtc.c File Reference
rtc.c File Reference
#include <drivers/x86/rtc.h>
#include <platform/x86/port.h>
Macros
#define BCD_TO_BIN(v) ((((v) & 0xF0) >> 1) + (((v) & 0xF0) >> 3) + ((v) & 0xf))
Functions
static uint8_t cmos_read (uint8_t port)
static void cmos_wait_while_updating ()
void rtc_load_time (uint8_t *secs, uint8_t *mins, uint8_t *hrs, uint8_t *day, uint8_t *month, uint32_t *year)
Macro Definition Documentation
BCD_TO_BIN
#define BCD_TO_BIN (v) ((((v) & 0xF0) >> 1) + (((v) & 0xF0) >> 3) + ((v) & 0xf))
Definition at line 4 of file rtc.c.
Function Documentation
cmos_read()
static uint8_t cmos_read (uint8_t port) inline static
Definition at line 6 of file rtc.c.
 {
     port_8bit_out(0x70, port);
     return port_8bit_in(0x71);
 }
References port_8bit_in(), and port_8bit_out().
Referenced by cmos_wait_while_updating(), and rtc_load_time().
cmos_wait_while_updating()
static void cmos_wait_while_updating () inline static
Definition at line 12 of file rtc.c.
{
       while ((cmos_read(0x0A) & 0x80));
 }
References cmos_read().
Referenced by rtc_load_time().
rtc_load_time()
void rtc_load_time (uint8_t * secs, uint8_t * mins, uint8_t * hrs, uint8_t * day, uint8_t * month, uint32_t * year)
Definition at line 16 of file rtc.c.
 {
     cmos_wait_while_updating();
     uint8_t status_reg_b = cmos_read(0x0b);
     *secs = cmos_read(0x00);
     *mins = cmos_read(0x02);
     *hrs = cmos_read(0x04);
     *day = cmos_read(0x07);
     *month = cmos_read(0x08);
     *year = cmos_read(0x09);
     if (!(status_reg_b & 0b100)) {
         *secs = BCD_TO_BIN(*secs);
         *mins = BCD_TO_BIN(*mins);
         *hrs = BCD_TO_BIN(*hrs);
         *day = BCD_TO_BIN(*day);
         *month = BCD_TO_BIN(*month);
         *year = BCD_TO_BIN(*year);
     }
     *year += 2000;
     if (((*hrs) >> 8) & 1) {
         *hrs = ((*hrs & 0x7F) + 12) % 24;
     }
 }
References BCD_TO_BIN, cmos_read(), and cmos_wait_while_updating().
Referenced by timeman_setup().