oneOS: include/tasking/sched.h File Reference
sched.h File Reference
#include <mem/vmm/vmm.h>
#include <tasking/tasking.h>
#include <types.h>
#include <platform/x86/idt.h>
Data Structures
struct runqueue
Macros
#define MAX_PRIO 0
#define MIN_PRIO 10
#define PRIOS_COUNT (MIN_PRIO - MAX_PRIO + 1)
#define DEFAULT_PRIO 6
#define SCHED_INT 10
Typedefs
typedef struct runqueue runqueue_t
Functions
void scheduler_init ()
void resched_dont_save_context ()
void resched ()
void sched ()
void sched_enqueue (thread_t *thread)
void sched_dequeue (thread_t *thread)
Macro Definition Documentation
DEFAULT_PRIO
#define DEFAULT_PRIO 6
Definition at line 21 of file sched.h.
MAX_PRIO
#define MAX_PRIO 0
Definition at line 18 of file sched.h.
MIN_PRIO
#define MIN_PRIO 10
Definition at line 19 of file sched.h.
PRIOS_COUNT
#define PRIOS_COUNT (MIN_PRIO - MAX_PRIO + 1)
Definition at line 20 of file sched.h.
SCHED_INT
#define SCHED_INT 10
Definition at line 22 of file sched.h.
Typedef Documentation
runqueue_t
typedef struct runqueue runqueue_t
Definition at line 1 of file sched.h.
Function Documentation
resched()
void resched ()
Definition at line 116 of file sched.c.
 {
     if (RUNNIG_THREAD) {
         if (RUNNIG_THREAD->status == THREAD_RUNNING) {
             _sched_add_to_end_of_runqueue(RUNNIG_THREAD);
         }
         switch_contexts(&RUNNIG_THREAD->context, THIS_CPU->scheduler);
     } else {
         switch_to_context(THIS_CPU->scheduler);
     }
 }
References _sched_add_to_end_of_runqueue(), RUNNIG_THREAD, switch_contexts(), switch_to_context(), THIS_CPU, and THREAD_RUNNING.
Referenced by init_join_blocker(), init_read_blocker(), init_select_blocker(), init_sleep_blocker(), init_write_blocker(), isr_handler(), pit_handler(), stage3(), sys_sched_yield(), tasking_exit(), and tasking_fork().
resched_dont_save_context()
void resched_dont_save_context ()
Definition at line 108 of file sched.c.
 {
     if (RUNNIG_THREAD && RUNNIG_THREAD->status == THREAD_RUNNING) {
         _sched_add_to_end_of_runqueue(RUNNIG_THREAD);
     }
     switch_to_context(THIS_CPU->scheduler);
 }
References _sched_add_to_end_of_runqueue(), RUNNIG_THREAD, switch_to_context(), THIS_CPU, and THREAD_RUNNING.
Referenced by signal_restore_thread_after_handling_signal().
sched()
void sched ()
Definition at line 173 of file sched.c.
 {
     for (;;) {
         while (!_master_buf[_buf_read_prio].head) {
             if (_buf_read_prio >= MIN_PRIO) {
                 tasking_kill_dying();
                 sched_unblock_threads();
                 _sched_swap_buffers();
             } else {
                 _buf_read_prio++;
             }
         }
         thread_t* thread = _master_buf[_buf_read_prio].head;
         _master_buf[_buf_read_prio].head = thread->sched_next;
         if (_master_buf[_buf_read_prio].tail == thread) {
             _master_buf[_buf_read_prio].tail = 0;
         }
         thread->sched_next = thread->sched_prev = 0;
 #ifdef SCHED_DEBUG
         log("next to run %d %x\n", thread->tid, thread->tf->eip);
 #endif
 #ifdef SCHED_SHOW_STAT
         log("[STAT] procs in buffer: %d", _debug_count_of_proc_in_buf(_master_buf));
 #endif
         ASSERT(thread->status == THREAD_RUNNING);
         switchuvm(thread);
         switch_contexts(&THIS_CPU->scheduler, thread->context);
     }
 }
References _buf_read_prio, _master_buf, _sched_swap_buffers(), ASSERT, thread::context, runqueue::head, log(), MIN_PRIO, thread::sched_next, thread::sched_prev, sched_unblock_threads(), thread::status, switch_contexts(), switchuvm(), runqueue::tail, tasking_kill_dying(), thread::tf, THIS_CPU, THREAD_RUNNING, and thread::tid.
Referenced by _init_cpus().
sched_dequeue()
void sched_dequeue (thread_t * thread)
Definition at line 141 of file sched.c.
 {
 #ifdef SCHED_DEBUG
     log("dequeue task %d\n", thread->tid);
 #endif
     if (_slave_buf[thread->process->prio].tail == thread) {
         _slave_buf[thread->process->prio].tail = thread->sched_prev;
     }
     if (_slave_buf[thread->process->prio].head == thread) {
         _slave_buf[thread->process->prio].head = thread->sched_next;
     }
     if (_master_buf[thread->process->prio].tail == thread) {
         _master_buf[thread->process->prio].tail = thread->sched_prev;
     }
     if (_master_buf[thread->process->prio].head == thread) {
         _master_buf[thread->process->prio].head = thread->sched_next;
     }
     if (thread->sched_prev) {
         thread->sched_prev->sched_next = thread->sched_next;
     }
     if (thread->sched_next) {
         thread->sched_next->sched_prev = thread->sched_prev;
     }
     thread->sched_next = thread->sched_prev = 0;
 }
References _master_buf, _slave_buf, runqueue::head, log(), proc::prio, thread::process, thread::sched_next, thread::sched_prev, runqueue::tail, and thread::tid.
Referenced by init_join_blocker(), init_read_blocker(), init_select_blocker(), init_sleep_blocker(), init_write_blocker(), signal_restore_thread_after_handling_signal(), and thread_die().
sched_enqueue()
void sched_enqueue (thread_t * thread)
Definition at line 128 of file sched.c.
 {
     thread->status = THREAD_RUNNING;
 #ifdef SCHED_DEBUG
     log("enqueue task %d\n", thread->tid);
 #endif
     if (thread->process->prio > MIN_PRIO) {
         thread->process->prio = MIN_PRIO;
     }
     _sched_add_to_start_of_runqueue(thread);
 }
References _sched_add_to_start_of_runqueue(), log(), MIN_PRIO, proc::prio, thread::process, thread::status, THREAD_RUNNING, and thread::tid.
Referenced by proc_create_thread(), sched_unblock_threads(), signal_dispatch_pending(), tasking_create_kernel_thread(), tasking_fork(), and tasking_start_init_proc().
scheduler_init()
void scheduler_init ()
Definition at line 80 of file sched.c.
 {
     _master_buf = buf1;
     _slave_buf = buf2;
     _buf_read_prio = 0;
     for (int i = 0; i < CPU_CNT; i++) {
         _init_cpus(&cpus[i]);
     }
 }
References _buf_read_prio, _init_cpus(), _master_buf, _slave_buf, buf1, buf2, CPU_CNT, and cpus.
Referenced by stage3().