oneOS: src/kernel/tasking/sched.c File Reference
sched.c File Reference
#include <algo/dynamic_array.h>
#include <log.h>
#include <mem/kmalloc.h>
#include <tasking/sched.h>
#include <tasking/tasking.h>
#include <utils/kassert.h>
#include <platform/x86/registers.h>
Functions
void switch_contexts (context_t **old, context_t *new)
void switch_to_context (context_t *new)
static void _init_cpus (cpu_t *cpu)
static void _sched_swap_buffers ()
static thread_t * _master_buf_back ()
static void _sched_save_running_proc ()
static void _debug_print_runqueue (runqueue_t *it)
static void _sched_add_to_start_of_runqueue (thread_t *thread)
static void _sched_add_to_end_of_runqueue (thread_t *thread)
void scheduler_init ()
void sched_unblock_threads ()
void resched_dont_save_context ()
void resched ()
void sched_enqueue (thread_t *thread)
void sched_dequeue (thread_t *thread)
void sched ()
Variables
runqueue_t buf1 [PRIOS_COUNT]
runqueue_t buf2 [PRIOS_COUNT]
static int _buf_read_prio
static runqueue_t * _master_buf
static runqueue_t * _slave_buf
thread_t thread_storage [512]
int threads_cnt
Function Documentation
_debug_print_runqueue()
static void _debug_print_runqueue (runqueue_t * it) static
Definition at line 204 of file sched.c.
 {
     for (int i = 0; i < PRIOS_COUNT; i++) {
         log(" Prio %d", i);
         thread_t* tmp = it[i].head;
         while (tmp) {
             log("   %d ->", tmp->tid);
             tmp = tmp->sched_next;
         }
     }
 }
References runqueue::head, log(), PRIOS_COUNT, thread::sched_next, and thread::tid.
_init_cpus()
static void _init_cpus (cpu_t * cpu) static
Definition at line 39 of file sched.c.
 {
     cpu->kstack = kmalloc(VMM_PAGE_SIZE);
     char* sp = cpu->kstack + VMM_PAGE_SIZE;
     sp -= sizeof(*cpu->scheduler);
     cpu->scheduler = (context_t*)sp;
     memset((void*)cpu->scheduler, 0, sizeof(*cpu->scheduler));
     cpu->scheduler->eip = (uint32_t)sched;
     cpu->running_thread = 0;
 }
References kmalloc(), memset(), sched(), and VMM_PAGE_SIZE.
Referenced by scheduler_init().
_master_buf_back()
static thread_t* _master_buf_back () inline static
_sched_add_to_end_of_runqueue()
static void _sched_add_to_end_of_runqueue (thread_t * thread) inline static
Definition at line 69 of file sched.c.
 {
     thread->sched_prev = _slave_buf[thread->process->prio].tail;
     if (thread->sched_prev) {
         thread->sched_prev->sched_next = thread;
     } else {
         _slave_buf[thread->process->prio].head = thread;
     }
     _slave_buf[thread->process->prio].tail = thread;
 }
References _slave_buf, runqueue::head, proc::prio, thread::process, thread::sched_next, thread::sched_prev, and runqueue::tail.
Referenced by resched(), and resched_dont_save_context().
_sched_add_to_start_of_runqueue()
static void _sched_add_to_start_of_runqueue (thread_t * thread) inline static
Definition at line 58 of file sched.c.
 {
     thread->sched_next = _slave_buf[thread->process->prio].head;
     if (thread->sched_next) {
         thread->sched_next->sched_prev = thread;
     } else {
         _slave_buf[thread->process->prio].tail = thread;
     }
     _slave_buf[thread->process->prio].head = thread;
 }
References _slave_buf, runqueue::head, proc::prio, thread::process, thread::sched_next, thread::sched_prev, and runqueue::tail.
Referenced by sched_enqueue().
_sched_save_running_proc()
static void _sched_save_running_proc () inline static
_sched_swap_buffers()
static void _sched_swap_buffers () inline static
Definition at line 50 of file sched.c.
 {
     runqueue_t* tmp = _master_buf;
     _master_buf = _slave_buf;
     _slave_buf = tmp;
     _buf_read_prio = 0;
 }
References _buf_read_prio, _master_buf, and _slave_buf.
Referenced by sched().
resched()
void resched ()
Definition at line 116 of file sched.c.
 {
     if (RUNNIG_THREAD) {
         if (RUNNIG_THREAD->status == THREAD_RUNNING) {
             _sched_add_to_end_of_runqueue(RUNNIG_THREAD);
         }
         switch_contexts(&RUNNIG_THREAD->context, THIS_CPU->scheduler);
     } else {
         switch_to_context(THIS_CPU->scheduler);
     }
 }
References _sched_add_to_end_of_runqueue(), RUNNIG_THREAD, switch_contexts(), switch_to_context(), THIS_CPU, and THREAD_RUNNING.
Referenced by init_join_blocker(), init_read_blocker(), init_select_blocker(), init_sleep_blocker(), init_write_blocker(), isr_handler(), pit_handler(), stage3(), sys_sched_yield(), tasking_exit(), and tasking_fork().
resched_dont_save_context()
void resched_dont_save_context ()
Definition at line 108 of file sched.c.
 {
     if (RUNNIG_THREAD && RUNNIG_THREAD->status == THREAD_RUNNING) {
         _sched_add_to_end_of_runqueue(RUNNIG_THREAD);
     }
     switch_to_context(THIS_CPU->scheduler);
 }
References _sched_add_to_end_of_runqueue(), RUNNIG_THREAD, switch_to_context(), THIS_CPU, and THREAD_RUNNING.
Referenced by signal_restore_thread_after_handling_signal().
sched()
void sched ()
Definition at line 173 of file sched.c.
 {
     for (;;) {
         while (!_master_buf[_buf_read_prio].head) {
             if (_buf_read_prio >= MIN_PRIO) {
                 tasking_kill_dying();
                 sched_unblock_threads();
                 _sched_swap_buffers();
             } else {
                 _buf_read_prio++;
             }
         }
         thread_t* thread = _master_buf[_buf_read_prio].head;
         _master_buf[_buf_read_prio].head = thread->sched_next;
         if (_master_buf[_buf_read_prio].tail == thread) {
             _master_buf[_buf_read_prio].tail = 0;
         }
         thread->sched_next = thread->sched_prev = 0;
 #ifdef SCHED_DEBUG
         log("next to run %d %x\n", thread->tid, thread->tf->eip);
 #endif
 #ifdef SCHED_SHOW_STAT
         log("[STAT] procs in buffer: %d", _debug_count_of_proc_in_buf(_master_buf));
 #endif
         ASSERT(thread->status == THREAD_RUNNING);
         switchuvm(thread);
         switch_contexts(&THIS_CPU->scheduler, thread->context);
     }
 }
References _buf_read_prio, _master_buf, _sched_swap_buffers(), ASSERT, thread::context, runqueue::head, log(), MIN_PRIO, thread::sched_next, thread::sched_prev, sched_unblock_threads(), thread::status, switch_contexts(), switchuvm(), runqueue::tail, tasking_kill_dying(), thread::tf, THIS_CPU, THREAD_RUNNING, and thread::tid.
Referenced by _init_cpus().
sched_dequeue()
void sched_dequeue (thread_t * thread)
Definition at line 141 of file sched.c.
 {
 #ifdef SCHED_DEBUG
     log("dequeue task %d\n", thread->tid);
 #endif
     if (_slave_buf[thread->process->prio].tail == thread) {
         _slave_buf[thread->process->prio].tail = thread->sched_prev;
     }
     if (_slave_buf[thread->process->prio].head == thread) {
         _slave_buf[thread->process->prio].head = thread->sched_next;
     }
     if (_master_buf[thread->process->prio].tail == thread) {
         _master_buf[thread->process->prio].tail = thread->sched_prev;
     }
     if (_master_buf[thread->process->prio].head == thread) {
         _master_buf[thread->process->prio].head = thread->sched_next;
     }
     if (thread->sched_prev) {
         thread->sched_prev->sched_next = thread->sched_next;
     }
     if (thread->sched_next) {
         thread->sched_next->sched_prev = thread->sched_prev;
     }
     thread->sched_next = thread->sched_prev = 0;
 }
References _master_buf, _slave_buf, runqueue::head, log(), proc::prio, thread::process, thread::sched_next, thread::sched_prev, runqueue::tail, and thread::tid.
Referenced by init_join_blocker(), init_read_blocker(), init_select_blocker(), init_sleep_blocker(), init_write_blocker(), signal_restore_thread_after_handling_signal(), and thread_die().
sched_enqueue()
void sched_enqueue (thread_t * thread)
Definition at line 128 of file sched.c.
 {
     thread->status = THREAD_RUNNING;
 #ifdef SCHED_DEBUG
     log("enqueue task %d\n", thread->tid);
 #endif
     if (thread->process->prio > MIN_PRIO) {
         thread->process->prio = MIN_PRIO;
     }
     _sched_add_to_start_of_runqueue(thread);
 }
References _sched_add_to_start_of_runqueue(), log(), MIN_PRIO, proc::prio, thread::process, thread::status, THREAD_RUNNING, and thread::tid.
Referenced by proc_create_thread(), sched_unblock_threads(), signal_dispatch_pending(), tasking_create_kernel_thread(), tasking_fork(), and tasking_start_init_proc().
sched_unblock_threads()
void sched_unblock_threads ()
Definition at line 93 of file sched.c.
 {
     thread_t* thread;
     for (int i = 0; i < threads_cnt; i++) {
         thread = &thread_storage[i];
         if (thread->status == THREAD_BLOCKED && thread->blocker.reason != BLOCKER_INVALID) {
             if (thread->blocker.should_unblock(thread)) {
                 thread->status = THREAD_RUNNING;
                 thread->blocker.reason = BLOCKER_INVALID;
                 sched_enqueue(thread);
             }
         }
     }
 }
References thread::blocker, BLOCKER_INVALID, blocker::reason, sched_enqueue(), blocker::should_unblock, thread::status, THREAD_BLOCKED, THREAD_RUNNING, thread_storage, and threads_cnt.
Referenced by sched().
scheduler_init()
void scheduler_init ()
Definition at line 80 of file sched.c.
 {
     _master_buf = buf1;
     _slave_buf = buf2;
     _buf_read_prio = 0;
     for (int i = 0; i < CPU_CNT; i++) {
         _init_cpus(&cpus[i]);
     }
 }
References _buf_read_prio, _init_cpus(), _master_buf, _slave_buf, buf1, buf2, CPU_CNT, and cpus.
Referenced by stage3().
switch_contexts()
void switch_contexts (context_t ** old, context_t * new)
Referenced by resched(), and sched().
switch_to_context()
void switch_to_context (context_t * new)
Referenced by resched(), and resched_dont_save_context().
Variable Documentation
_buf_read_prio
int _buf_read_prio static
Definition at line 23 of file sched.c.
Referenced by _sched_swap_buffers(), sched(), and scheduler_init().
_master_buf
runqueue_t* _master_buf static
Definition at line 24 of file sched.c.
Referenced by _sched_swap_buffers(), sched(), sched_dequeue(), and scheduler_init().
_slave_buf
runqueue_t* _slave_buf static
Definition at line 25 of file sched.c.
Referenced by _sched_add_to_end_of_runqueue(), _sched_add_to_start_of_runqueue(), _sched_swap_buffers(), sched_dequeue(), and scheduler_init().
buf1
runqueue_t buf1[PRIOS_COUNT]
Definition at line 20 of file sched.c.
Referenced by scheduler_init().
buf2
runqueue_t buf2[PRIOS_COUNT]
Definition at line 21 of file sched.c.
Referenced by scheduler_init().
thread_storage
thread_t thread_storage[512] extern
Definition at line 25 of file proc.c.
Referenced by sched_unblock_threads().
threads_cnt
int threads_cnt extern
Definition at line 26 of file proc.c.
Referenced by sched_unblock_threads().