oneOS: servers/window_server/main.cpp File Reference
main.cpp File Reference
#include "Compositor.h"
#include "Connection.h"
#include "CursorManager.h"
#include "Devices.h"
#include "ResourceManager.h"
#include "Screen.h"
#include "WindowManager.h"
#include <libfoundation/EventLoop.h>
#include <malloc.h>
#include <pthread.h>
#include <syscalls.h>
Functions
void start_dock ()
int main ()
Function Documentation
main()
int main ()
Definition at line 29 of file main.cpp.
 {
     start_dock();
     auto* event_loop = new LFoundation::EventLoop();
     new Screen();
     new Connection(socket(PF_LOCAL, 0, 0));
     new CursorManager();
     new ResourceManager();
     new Compositor();
     new WindowManager();
     new Devices();
     event_loop->run();
     return 0;
 }
References PF_LOCAL, socket(), and start_dock().
start_dock()
void start_dock ()
Definition at line 21 of file main.cpp.
 {
     if (fork()) {
         execve("/bin/dock", 0, 0);
         ASSERT_NOT_REACHED();
     }
 }
References ASSERT_NOT_REACHED, execve(), and fork().
Referenced by main().