oneOS: src/kernel/io/shared_buffer/shared_buffer.c File Reference
shared_buffer.c File Reference
#include <algo/bitmap.h>
#include <errno.h>
#include <io/shared_buffer/shared_buffer.h>
#include <log.h>
#include <mem/vmm/vmm.h>
#include <mem/vmm/zoner.h>
Data Structures
struct shared_buffer_header
Macros
#define SHBUF_SPACE_SIZE (128 * MB)
#define SHBUF_BLOCK_SIZE (4 * KB)
#define SHBUF_MAX_BUFFERS 128
Typedefs
typedef struct shared_buffer_header shared_buffer_header_t
Functions
static uint32_t _shared_buffer_to_vaddr (int start)
static int _shared_buffer_to_index (uint32_t vaddr)
static int _shared_buffer_alloc_id ()
static void _shared_buffer_init_bitmap ()
int shared_buffer_init ()
int shared_buffer_create (uint8_t **res_buffer, size_t size)
int shared_buffer_get (int id, uint8_t **res_buffer)
int shared_buffer_free (int id)
Variables
uint8_t * buffers [128]
static zone_t _shared_buffer_zone
static uint32_t _shared_buffer_bitmap_len = 0
static uint8_t * _shared_buffer_bitmap
static bitmap_t bitmap
Macro Definition Documentation
SHBUF_BLOCK_SIZE
#define SHBUF_BLOCK_SIZE (4 * KB)
Definition at line 19 of file shared_buffer.c.
SHBUF_MAX_BUFFERS
#define SHBUF_MAX_BUFFERS 128
Definition at line 20 of file shared_buffer.c.
SHBUF_SPACE_SIZE
#define SHBUF_SPACE_SIZE (128 * MB)
Definition at line 18 of file shared_buffer.c.
Typedef Documentation
shared_buffer_header_t
typedef struct shared_buffer_header shared_buffer_header_t
Definition at line 22 of file shared_buffer.c.
Function Documentation
_shared_buffer_alloc_id()
static int _shared_buffer_alloc_id () inline static
Definition at line 45 of file shared_buffer.c.
 {
     for (int i = 0; i < SHBUF_MAX_BUFFERS; i++) {
         if (!buffers[i]) {
             return i;
         }
     }
     return -1;
 }
References buffers, and SHBUF_MAX_BUFFERS.
Referenced by shared_buffer_create().
_shared_buffer_init_bitmap()
static void _shared_buffer_init_bitmap () static
Definition at line 55 of file shared_buffer.c.
 {
     _shared_buffer_bitmap = _shared_buffer_zone.ptr;
     _shared_buffer_bitmap_len = (SHBUF_SPACE_SIZE / SHBUF_BLOCK_SIZE / 8);
     bitmap = bitmap_wrap(_shared_buffer_bitmap, _shared_buffer_bitmap_len);
     memset(_shared_buffer_bitmap, 0, _shared_buffer_bitmap_len);
     /* Setting bitmap as a busy region. */
     int blocks_needed = (_shared_buffer_bitmap_len + SHBUF_BLOCK_SIZE - 1) / SHBUF_BLOCK_SIZE;
     bitmap_set_range(bitmap, _shared_buffer_to_index((uint32_t)_shared_buffer_bitmap), blocks_needed);
 }
References _shared_buffer_bitmap, _shared_buffer_bitmap_len, _shared_buffer_to_index(), _shared_buffer_zone, bitmap_set_range(), bitmap_wrap(), memset(), __zone::ptr, SHBUF_BLOCK_SIZE, and SHBUF_SPACE_SIZE.
Referenced by shared_buffer_init().
_shared_buffer_to_index()
static int _shared_buffer_to_index (uint32_t vaddr) inline static
Definition at line 40 of file shared_buffer.c.
 {
     return (vaddr - (uint32_t)_shared_buffer_zone.start) / SHBUF_BLOCK_SIZE;
 }
References _shared_buffer_zone, SHBUF_BLOCK_SIZE, and __zone::start.
Referenced by _shared_buffer_init_bitmap(), and shared_buffer_free().
_shared_buffer_to_vaddr()
static uint32_t _shared_buffer_to_vaddr (int start) inline static
Definition at line 34 of file shared_buffer.c.
 {
     uint32_t vaddr = (uint32_t)_shared_buffer_zone.start + start * SHBUF_BLOCK_SIZE;
     return (uint32_t)_shared_buffer_zone.start + start * SHBUF_BLOCK_SIZE;
 }
References _shared_buffer_zone, SHBUF_BLOCK_SIZE, and __zone::start.
Referenced by shared_buffer_create().
shared_buffer_create()
int shared_buffer_create (uint8_t ** res_buffer, size_t size)
Definition at line 74 of file shared_buffer.c.
 {
     int buf_id = _shared_buffer_alloc_id();
     if (buf_id < 0) {
         return -ENOMEM;
     }
     size_t act_size = size + sizeof(shared_buffer_header_t);
     int blocks_needed = (act_size + SHBUF_BLOCK_SIZE - 1) / SHBUF_BLOCK_SIZE;
     int start = bitmap_find_space(bitmap, blocks_needed);
     if (start < 0) {
         return -ENOMEM;
     }
     shared_buffer_header_t* space = (shared_buffer_header_t*)_shared_buffer_to_vaddr(start);
     space->len = act_size;
     bitmap_set_range(bitmap, start, blocks_needed);
     vmm_tune_pages((uint32_t)space, act_size, PAGE_WRITABLE | PAGE_EXECUTABLE | PAGE_READABLE | PAGE_USER);
     *res_buffer = (uint8_t*)&space[1];
     buffers[buf_id] = (uint8_t*)&space[1];
 #ifdef SHARED_BUFFER_DEBUG
     log("Buffer created at %x %d", buffers[buf_id], buf_id);
 #endif
     return buf_id;
 }
References _shared_buffer_alloc_id(), _shared_buffer_to_vaddr(), bitmap_find_space(), bitmap_set_range(), buffers, ENOMEM, shared_buffer_header::len, log(), PAGE_EXECUTABLE, PAGE_READABLE, PAGE_USER, PAGE_WRITABLE, SHBUF_BLOCK_SIZE, SYS_SHBUF_CREATE, syscall(), and vmm_tune_pages().
Referenced by Sys::SharedBuffer< T >::create(), Sys::SharedBuffer< T >::SharedBuffer(), and sys_shbuf_create().
shared_buffer_free()
int shared_buffer_free (int id)
Definition at line 117 of file shared_buffer.c.
 {
     if (unlikely(id < 0 || SHBUF_MAX_BUFFERS <= id)) {
         return -EINVAL;
     }
     if (unlikely(buffers[id] == 0)) {
         return -EINVAL;
     }
     shared_buffer_header_t* sptr = (shared_buffer_header_t*)buffers[id];
     size_t blocks_to_delete = (sptr[-1].len + SHBUF_BLOCK_SIZE - 1) / SHBUF_BLOCK_SIZE;
     bitmap_unset_range(bitmap, _shared_buffer_to_index((uint32_t)&sptr[-1]), blocks_to_delete);
     buffers[id] = 0;
     return 0;
 }
References _shared_buffer_to_index(), bitmap_unset_range(), buffers, EINVAL, shared_buffer_header::len, SHBUF_BLOCK_SIZE, SHBUF_MAX_BUFFERS, SYS_SHBUF_FREE, syscall(), and unlikely.
Referenced by Sys::SharedBuffer< T >::free(), and sys_shbuf_free().
shared_buffer_get()
int shared_buffer_get (int id, uint8_t ** res_buffer)
Definition at line 102 of file shared_buffer.c.
 {
     if (unlikely(id < 0 || SHBUF_MAX_BUFFERS <= id)) {
         return -EINVAL;
     }
     if (unlikely(buffers[id] == 0)) {
         return -EINVAL;
     }
 #ifdef SHARED_BUFFER_DEBUG
     log("Buffer opened at %x %d", buffers[id], id);
 #endif
     *res_buffer = buffers[id];
     return 0;
 }
References buffers, EINVAL, log(), SHBUF_MAX_BUFFERS, SYS_SHBUF_GET, syscall(), and unlikely.
Referenced by Sys::SharedBuffer< T >::open(), Sys::SharedBuffer< T >::SharedBuffer(), and sys_shbuf_get().
shared_buffer_init()
int shared_buffer_init ()
Definition at line 68 of file shared_buffer.c.
 {
     _shared_buffer_zone = zoner_new_zone(SHBUF_SPACE_SIZE);
     _shared_buffer_init_bitmap();
 }
References _shared_buffer_init_bitmap(), _shared_buffer_zone, SHBUF_SPACE_SIZE, and zoner_new_zone().
Referenced by stage3().
Variable Documentation
_shared_buffer_bitmap
uint8_t* _shared_buffer_bitmap static
Definition at line 31 of file shared_buffer.c.
Referenced by _shared_buffer_init_bitmap().
_shared_buffer_bitmap_len
uint32_t _shared_buffer_bitmap_len = 0 static
Definition at line 30 of file shared_buffer.c.
Referenced by _shared_buffer_init_bitmap().
_shared_buffer_zone
zone_t _shared_buffer_zone static
Definition at line 29 of file shared_buffer.c.
Referenced by _shared_buffer_init_bitmap(), _shared_buffer_to_index(), _shared_buffer_to_vaddr(), and shared_buffer_init().
bitmap
bitmap_t bitmap static
Definition at line 32 of file shared_buffer.c.
Referenced by bitmap_wrap(), LG::PNG::PNGLoader::load_from_file(), and LG::PNG::PNGLoader::load_from_mem().
buffers
uint8_t* buffers[128]
Definition at line 22 of file shared_buffer.c.
Referenced by _shared_buffer_alloc_id(), shared_buffer_create(), shared_buffer_free(), and shared_buffer_get().