oneOS: include/io/shared_buffer/shared_buffer.h File Reference
shared_buffer.h File Reference
#include <types.h>
Functions
int shared_buffer_init ()
int shared_buffer_create (uint8_t **buffer, size_t size)
int shared_buffer_get (int id, uint8_t **buffer)
int shared_buffer_free (int id)
Function Documentation
shared_buffer_create()
int shared_buffer_create (uint8_t ** buffer, size_t size)
Definition at line 169 of file syscalls.c.
 {
     return syscall(SYS_SHBUF_CREATE, (int)buffer, (int)size, 0, 0, 0);
 }
References SYS_SHBUF_CREATE, and syscall().
Referenced by Sys::SharedBuffer< T >::create(), Sys::SharedBuffer< T >::SharedBuffer(), and sys_shbuf_create().
shared_buffer_free()
int shared_buffer_free (int id)
Definition at line 179 of file syscalls.c.
 {
     return syscall(SYS_SHBUF_FREE, (int)id, 0, 0, 0, 0);
 }
References SYS_SHBUF_FREE, and syscall().
Referenced by Sys::SharedBuffer< T >::free(), and sys_shbuf_free().
shared_buffer_get()
int shared_buffer_get (int id, uint8_t ** buffer)
Definition at line 174 of file syscalls.c.
 {
     return syscall(SYS_SHBUF_GET, id, (int)buffer, 0, 0, 0);
 }
References SYS_SHBUF_GET, and syscall().
Referenced by Sys::SharedBuffer< T >::open(), Sys::SharedBuffer< T >::SharedBuffer(), and sys_shbuf_get().
shared_buffer_init()
int shared_buffer_init ()
Definition at line 68 of file shared_buffer.c.
 {
     _shared_buffer_zone = zoner_new_zone(SHBUF_SPACE_SIZE);
     _shared_buffer_init_bitmap();
 }
References _shared_buffer_init_bitmap(), _shared_buffer_zone, SHBUF_SPACE_SIZE, and zoner_new_zone().
Referenced by stage3().