oneOS: include/io/sockets/socket.h File Reference
socket.h File Reference
#include <fs/vfs.h>
#include <syscall_structs.h>
#include <types.h>
Macros
#define MAX_SOCKET_COUNT 16
Functions
int socket_create (int domain, int type, int protocol, file_descriptor_t *fd, file_ops_t *ops)
socket_t * socket_duplicate (socket_t *sock)
int socket_put (socket_t *sock)
Macro Definition Documentation
MAX_SOCKET_COUNT
#define MAX_SOCKET_COUNT 16
Definition at line 16 of file socket.h.
Function Documentation
socket_create()
int socket_create (int domain, int type, int protocol, file_descriptor_t * fd, file_ops_t * ops)
Definition at line 25 of file socket.c.
 {
     fd->type = FD_TYPE_SOCKET;
     fd->sock_entry = _socket_create(domain, type, protocol);
     fd->ops = ops;
     if (!fd->sock_entry) {
         return -1;
     }
     return 0;
 }
References _socket_create(), FD_TYPE_SOCKET, file_descriptor::ops, file_descriptor::sock_entry, file_descriptor::type, and type.
Referenced by local_socket_create().
socket_duplicate()
socket_t* socket_duplicate (socket_t * sock)
Definition at line 36 of file socket.c.
 {
     sock->d_count++;
     return sock;
 }
References socket::d_count.
Referenced by local_socket_bind(), and local_socket_connect().
socket_put()
int socket_put (socket_t * sock)
Definition at line 42 of file socket.c.
 {
     sock->d_count--;
     ASSERT(sock->d_count > 0);
     if (sock->d_count == 0) {
         ringbuffer_free(&sock->buffer);
     }
     return 0;
 }
References ASSERT, socket::buffer, socket::d_count, and ringbuffer_free().
Referenced by vfs_close().