oneOS: src/kernel/io/sockets/socket.c File Reference
socket.c File Reference
#include <io/sockets/socket.h>
#include <utils/kassert.h>
Functions
static socket_t * _socket_create (int domain, int type, int protocol)
int socket_create (int domain, int type, int protocol, file_descriptor_t *fd, file_ops_t *ops)
socket_t * socket_duplicate (socket_t *sock)
int socket_put (socket_t *sock)
Variables
socket_t socket_list [MAX_SOCKET_COUNT]
static int next_socket = 0
Function Documentation
_socket_create()
static socket_t* _socket_create (int domain, int type, int protocol) static
Definition at line 15 of file socket.c.
 {
     socket_list[next_socket].domain = domain;
     socket_list[next_socket].type = type;
     socket_list[next_socket].protocol = protocol;
     socket_list[next_socket].buffer = ringbuffer_create_std();
     socket_list[next_socket].d_count = 1;
     return &socket_list[next_socket++];
 }
References socket::buffer, socket::d_count, socket::domain, next_socket, socket::protocol, ringbuffer_create_std(), socket_list, socket::type, and type.
Referenced by socket_create().
socket_create()
int socket_create (int domain, int type, int protocol, file_descriptor_t * fd, file_ops_t * ops)
Definition at line 25 of file socket.c.
 {
     fd->type = FD_TYPE_SOCKET;
     fd->sock_entry = _socket_create(domain, type, protocol);
     fd->ops = ops;
     if (!fd->sock_entry) {
         return -1;
     }
     return 0;
 }
References _socket_create(), FD_TYPE_SOCKET, file_descriptor::ops, file_descriptor::sock_entry, file_descriptor::type, and type.
Referenced by local_socket_create().
socket_duplicate()
socket_t* socket_duplicate (socket_t * sock)
Definition at line 36 of file socket.c.
 {
     sock->d_count++;
     return sock;
 }
References socket::d_count.
Referenced by local_socket_bind(), and local_socket_connect().
socket_put()
int socket_put (socket_t * sock)
Definition at line 42 of file socket.c.
 {
     sock->d_count--;
     ASSERT(sock->d_count > 0);
     if (sock->d_count == 0) {
         ringbuffer_free(&sock->buffer);
     }
     return 0;
 }
References ASSERT, socket::buffer, socket::d_count, and ringbuffer_free().
Referenced by vfs_close().
Variable Documentation
next_socket
int next_socket = 0 static
Definition at line 13 of file socket.c.
Referenced by _socket_create().
socket_list
socket_t socket_list[MAX_SOCKET_COUNT]
Definition at line 12 of file socket.c.
Referenced by _socket_create().