oneOS: src/boot/x86/stage2/mem/vmm.h File Reference
vmm.h File Reference
#include <types.h>
#include <mem/pmm.h>
#include <mem/vmm/pte.h>
#include <mem/vmm/pde.h>
Data Structures
struct ptable_t
struct pdirectory
Macros
#define VMM_PTE_COUNT (1024)
#define VMM_PDE_COUNT (1024)
#define VMM_PAGE_SIZE (4096)
Typedefs
typedef struct pdirectory pdirectory_t
Enumerations
enum VMM_ERR_CODES {
VMM_ERR_PDIR , VMM_ERR_PTABLE , VMM_ERR_NO_SPACE , VMM_ERR_BAD_ADDR ,
VMM_ERR_PDIR , VMM_ERR_NO_SPACE , VMM_ERR_BAD_ADDR , VMM_ERR_PDIR ,
VMM_ERR_NO_SPACE , VMM_ERR_BAD_ADDR
}
Functions
int vmm_setup ()
table_desc_t * vmm_pdirectory_lookup (pdirectory_t *t_pdir, uint32_t t_addr)
page_desc_t * vmm_ptable_lookup (ptable_t *t_ptable, uint32_t t_addr)
int vmm_allocate_ptable (uint32_t vaddr)
int vmm_map_page (uint32_t vaddr, uint32_t paddr, bool owner)
int vmm_map_pages (uint32_t vaddr, uint32_t paddr, uint32_t n_pages, bool owner)
int vmm_copy_page (uint32_t vaddr, ptable_t *src_ptable)
pdirectory_t * vmm_new_user_pdir ()
pdirectory_t * vmm_new_forked_user_pdir ()
void vmm_copy_program_data (pdirectory_t *dir, uint8_t *data, uint32_t data_size)
void * vmm_bring_to_kernel (uint8_t *src, uint32_t length)
void vmm_copy_to_pdir (pdirectory_t *pdir, uint8_t *src, uint32_t dest_vaddr, uint32_t length)
void vmm_zero_user_pages (pdirectory_t *pdir)
pdirectory_t * vmm_get_active_pdir ()
int vmm_load_page (uint32_t vaddr)
int vmm_alloc_page (page_desc_t *page)
int vmm_free_page (page_desc_t *page)
void vmm_page_fault_handler (uint8_t info, uint32_t vaddr)
int vmm_switch_pdir (pdirectory_t *pdir)
void vmm_enable_paging ()
void vmm_disable_paging ()
Macro Definition Documentation
VMM_PAGE_SIZE
#define VMM_PAGE_SIZE (4096)
Definition at line 11 of file vmm.h.
VMM_PDE_COUNT
#define VMM_PDE_COUNT (1024)
Definition at line 10 of file vmm.h.
VMM_PTE_COUNT
#define VMM_PTE_COUNT (1024)
Definition at line 9 of file vmm.h.
Typedef Documentation
pdirectory_t
typedef struct pdirectory pdirectory_t
Enumeration Type Documentation
VMM_ERR_CODES
enum VMM_ERR_CODES
Enumerator
VMM_ERR_PDIR
VMM_ERR_PTABLE
VMM_ERR_NO_SPACE
VMM_ERR_BAD_ADDR
VMM_ERR_PDIR
VMM_ERR_NO_SPACE
VMM_ERR_BAD_ADDR
VMM_ERR_PDIR
VMM_ERR_NO_SPACE
VMM_ERR_BAD_ADDR
Definition at line 13 of file vmm.h.
                    {
     VMM_ERR_PDIR,
     VMM_ERR_NO_SPACE,
     VMM_ERR_BAD_ADDR,
 };
Function Documentation
vmm_alloc_page()
int vmm_alloc_page (page_desc_t * page)
Definition at line 821 of file vmm.c.
 {
     void* new_block = kmalloc_page_aligned();
     if (!new_block) {
         return -VMM_ERR_BAD_ADDR;
     }
     page_desc_set_attrs(page, PAGE_DESC_PRESENT);
     page_desc_set_frame(page, FRAME((uint32_t)new_block));
     return 0;
 }
vmm_allocate_ptable()
int vmm_allocate_ptable (uint32_t vaddr)
The function is supposed to create new ptable (not kernel) and rebuild pspace to match to the new setup
Definition at line 342 of file vmm.c.
 {
     if (_vmm_active_pdir == 0) {
         return -VMM_ERR_PDIR;
     }
     uint32_t ptable_paddr = (uint32_t)pmm_alloc_block();
     if (!ptable_paddr) {
         log_error(" vmm_allocate_ptable: No free space in pmm");
         return -VMM_ERR_NO_SPACE;
     }
     uint32_t ptable_vaddr = (uint32_t)_vmm_pspace_get_vaddr_of_active_ptable(vaddr);
     table_desc_t* ptable_desc = vmm_pdirectory_lookup(_vmm_active_pdir, vaddr);
     table_desc_clear(ptable_desc);
     table_desc_set_attrs(ptable_desc, TABLE_DESC_PRESENT | TABLE_DESC_WRITABLE | TABLE_DESC_USER);
     table_desc_set_frame(ptable_desc, FRAME(ptable_paddr));
     int ret = vmm_map_page(ptable_vaddr, ptable_paddr, PAGE_READABLE | PAGE_WRITABLE | PAGE_EXECUTABLE | PAGE_CHOOSE_OWNER(vaddr));
     if (ret == 0) {
         memset((void*)ptable_vaddr, 0, VMM_PAGE_SIZE);
     }
     return ret;
 }
Referenced by _vmm_resolve_copy_on_write(), and vmm_map_page().
vmm_bring_to_kernel()
void* vmm_bring_to_kernel (uint8_t * src, uint32_t length)
Definition at line 684 of file vmm.c.
 {
     if ((uint32_t)src >= KERNEL_BASE) {
         return src;
     }
     uint8_t* kaddr = kmalloc(length);
     memcpy(kaddr, src, length);
     return (void*)kaddr;
 }
Referenced by vmm_copy_to_pdir().
vmm_copy_page()
int vmm_copy_page (uint32_t vaddr, ptable_t * src_ptable)
vmm_copy_program_data()
void vmm_copy_program_data (pdirectory_t * dir, uint8_t * data, uint32_t data_size)
vmm_copy_to_pdir()
void vmm_copy_to_pdir (pdirectory_t * pdir, uint8_t * src, uint32_t dest_vaddr, uint32_t length)
Definition at line 694 of file vmm.c.
 {
     pdirectory_t* prev_pdir = vmm_get_active_pdir();
     uint8_t* ksrc;
     if ((uint32_t)src < KERNEL_BASE) {
         /* Means that it's in user space, so it should be copied here. */
         ksrc = vmm_bring_to_kernel(src, length);
     } else {
         ksrc = src;
     }
     vmm_switch_pdir(pdir);
     _vmm_ensure_cow_for_range(dest_vaddr, length);
     uint8_t* dest = (uint8_t*)dest_vaddr;
     memcpy(dest, ksrc, length);
     if ((uint32_t)src < KERNEL_BASE) {
         kfree(ksrc);
     }
     vmm_switch_pdir(prev_pdir);
 }
vmm_disable_paging()
void vmm_disable_paging ()
Definition at line 918 of file vmm.c.
 {
     system_disable_paging();
 }
vmm_enable_paging()
void vmm_enable_paging ()
Definition at line 913 of file vmm.c.
 {
     system_enable_paging();
 }
vmm_free_page()
int vmm_free_page (page_desc_t * page)
Definition at line 833 of file vmm.c.
 {
     uint32_t frame = page_desc_get_frame(*page);
     pmm_free_block((void*)(frame * VMM_PAGE_SIZE));
     page_desc_del_attrs(page, PAGE_DESC_PRESENT);
     return 0;
 }
vmm_get_active_pdir()
pdirectory_t* vmm_get_active_pdir ()
Definition at line 727 of file vmm.c.
 {
     return _vmm_active_pdir;
 }
Referenced by vmm_copy_to_pdir(), vmm_free_pdir(), vmm_map_page(), and vmm_page_fault_handler().
vmm_load_page()
int vmm_load_page (uint32_t vaddr)
vmm_map_page()
int vmm_map_page (uint32_t vaddr, uint32_t paddr, bool owner)
vmm_map_pages()
int vmm_map_pages (uint32_t vaddr, uint32_t paddr, uint32_t n_pages, bool owner)
vmm_new_forked_user_pdir()
pdirectory_t* vmm_new_forked_user_pdir ()
The function created a new user's pdir from the active pdir. After copying the task we need to flush tlb. To do that we have to to reload cr3 tlb entries.
Definition at line 628 of file vmm.c.
 {
     pdirectory_t* new_pdir = (pdirectory_t*)kmalloc_page_aligned();
     // coping all tables
     for (int i = 0; i < 1024; i++) {
         new_pdir->entities[i] = _vmm_active_pdir->entities[i];
     }
     new_pdir->entities[VMM_OFFSET_IN_DIRECTORY(pspace_zone.start)] = _vmm_pspace_gen();
     for (int i = 0; i < VMM_KERNEL_TABLES_START; i++) {
         table_desc_t* act_ptable_desc = &_vmm_active_pdir->entities[i];
         if (table_desc_has_attrs(*act_ptable_desc, TABLE_DESC_PRESENT)) {
             // COW: blocking current pdir
             table_desc_del_attrs(act_ptable_desc, TABLE_DESC_WRITABLE);
             table_desc_set_attrs(act_ptable_desc, TABLE_DESC_COPY_ON_WRITE);
             // COW: blocking new pdir
             table_desc_t* new_ptable_desc = &new_pdir->entities[i];
             table_desc_del_attrs(new_ptable_desc, TABLE_DESC_WRITABLE);
             table_desc_set_attrs(new_ptable_desc, TABLE_DESC_COPY_ON_WRITE);
         }
     }
     system_flush_whole_tlb();
     return new_pdir;
 }
vmm_new_user_pdir()
pdirectory_t* vmm_new_user_pdir ()
USER PDIR FUNCTIONS The function is supposed to create all new user's pdir.
Definition at line 605 of file vmm.c.
 {
     pdirectory_t* pdir = (pdirectory_t*)kmalloc_page_aligned();
     for (int i = VMM_USER_TABLES_START; i < VMM_KERNEL_TABLES_START; i++) {
         pdir->entities[i] = 0;
     }
     for (int i = VMM_KERNEL_TABLES_START; i < 1024; i++) {
         if (!IS_INDIVIDUAL_PER_DIR(i)) {
             pdir->entities[i] = _vmm_kernel_pdir->entities[i];
         }
     }
     pdir->entities[VMM_OFFSET_IN_DIRECTORY(pspace_zone.start)] = _vmm_pspace_gen();
     return pdir;
 }
vmm_page_fault_handler()
void vmm_page_fault_handler (uint8_t info, uint32_t vaddr)
Definition at line 841 of file vmm.c.
 {
     if ((info & 0b11) == 0b11) {
         bool visited = false;
         if (_vmm_is_copy_on_write(vaddr)) {
             _vmm_resolve_copy_on_write(vaddr);
             visited = true;
         }
         if (_vmm_is_zeroing_on_demand(vaddr)) {
             _vmm_resolve_zeroing_on_demand(vaddr);
             visited = true;
         }
         if (!visited) {
             log_error("Write to not writable page");
             return SHOULD_CRASH;
         }
     } else {
         if ((info & 1) == 0) {
             if (PAGE_CHOOSE_OWNER(vaddr) == PAGE_USER && vmm_get_active_pdir() != vmm_get_kernel_pdir()) {
                 proc_t* holder_proc = tasking_get_proc_by_pdir(vmm_get_active_pdir());
                 if (!holder_proc) {
                     kpanic("No proc with the pdir\n");
                 }
                 proc_zone_t* zone = proc_find_zone(holder_proc, vaddr);
                 if (!zone) {
                     return SHOULD_CRASH;
                 }
 #ifdef VMM_DEBUG
                 log("Mmap page %x for %d pid: %x", vaddr, RUNNIG_THREAD->process->pid, zone->flags);
 #endif
                 vmm_load_page(vaddr, zone->flags);
                 if (zone->type == ZONE_TYPE_MAPPED_FILE_PRIVATLY) {
                     zone->fd->offset = PAGE_START(vaddr) - zone->start;
                     vfs_read(zone->fd, (uint8_t*)PAGE_START(vaddr), VMM_PAGE_SIZE);
                 }
             } else {
                 /* FIXME: Now we have a standard zone for kernel, but it's better to do the same thing as for user's pages */
                 vmm_load_page(vaddr, PAGE_READABLE | PAGE_WRITABLE | PAGE_EXECUTABLE);
             }
         } else {
             proc_zone_t* zone = proc_find_zone(RUNNIG_THREAD->process, vaddr);
             log_error("PF: info %d vaddr %x pdir %x pid %d", info, vaddr, vmm_get_active_pdir(), RUNNIG_THREAD->process->pid);
             return SHOULD_CRASH;
         }
     }
     return OK;
 }
vmm_pdirectory_lookup()
table_desc_t* vmm_pdirectory_lookup (pdirectory_t * t_pdir, uint32_t t_addr)
Definition at line 322 of file vmm.c.
 {
     if (pdir) {
         return &pdir->entities[VMM_OFFSET_IN_DIRECTORY(vaddr)];
     }
     return 0;
 }
Referenced by _vmm_create_kernel_ptables(), _vmm_is_copy_on_write(), _vmm_is_zeroing_on_demand(), _vmm_pspace_init(), _vmm_resolve_copy_on_write(), _vmm_resolve_zeroing_on_demand(), vmm_allocate_ptable(), vmm_map_page(), and vmm_unmap_page().
vmm_ptable_lookup()
page_desc_t* vmm_ptable_lookup (ptable_t * t_ptable, uint32_t t_addr)
Definition at line 330 of file vmm.c.
 {
     if (ptable) {
         return &ptable->entities[VMM_OFFSET_IN_TABLE(vaddr)];
     }
     return 0;
 }
Referenced by _vmm_convert_vaddr2paddr(), _vmm_copy_page_to_resolve_cow(), _vmm_is_zeroing_on_demand(), _vmm_kernel_convert_vaddr2paddr(), _vmm_pspace_init(), _vmm_resolve_copy_on_write(), _vmm_resolve_zeroing_on_demand(), vmm_copy_page(), vmm_map_page(), vmm_test_pspace_vaddr_of_active_ptable(), vmm_tune_page(), and vmm_unmap_page().
vmm_setup()
int vmm_setup ()
PUBLIC FUNCTIONS
Definition at line 288 of file vmm.c.
 {
     zoner_init(0xc0400000);
     _vmm_split_pspace();
     _vmm_create_kernel_ptables();
     _vmm_pspace_init();
     _vmm_init_switch_to_kernel_pdir();
     _vmm_map_kernel();
     zoner_place_bitmap();
     kmalloc_init();
     if (_vmm_self_test() < 0) {
         kpanic("VMM SELF TEST Not passed");
     }
     return 0;
 }
vmm_switch_pdir()
int vmm_switch_pdir (pdirectory_t * pdir)
CPU BASED FUNCTIONS
Definition at line 896 of file vmm.c.
 {
     if (((uint32_t)pdir & (VMM_PAGE_SIZE - 1)) != 0) {
         kpanic("vmm_switch_pdir: wrong pdir");
     }
     system_disable_interrupts();
     if (_vmm_active_pdir == pdir) {
         system_enable_interrupts();
         return 0;
     }
     _vmm_active_pdir = pdir;
     system_set_pdir((uint32_t)_vmm_convert_vaddr2paddr((uint32_t)pdir));
     system_enable_interrupts();
     return 0;
 }
Referenced by vmm_copy_to_pdir(), and vmm_free_pdir().
vmm_zero_user_pages()
void vmm_zero_user_pages (pdirectory_t * pdir)
Definition at line 718 of file vmm.c.
 {
     for (int i = 0; i < VMM_KERNEL_TABLES_START; i++) {
         table_desc_t* ptable_desc = &pdir->entities[i];
         table_desc_del_attrs(ptable_desc, TABLE_DESC_WRITABLE);
         table_desc_set_attrs(ptable_desc, TABLE_DESC_ZEROING_ON_DEMAND);
     }
 }