oneOS: libs/libcxx/std/Memory.h File Reference
Memory.h File Reference
#include <sys/types.h>
Functions
void fast_copy (uint32_t *dest, const uint32_t *src, size_t count)
void fast_set (uint32_t *dest, uint32_t val, size_t count)
Function Documentation
fast_copy()
void fast_copy (uint32_t * dest, const uint32_t * src, size_t count) inline
Definition at line 5 of file Memory.h.
 {
     asm volatile(
         "rep movsl\n"
         : "=S"(src), "=D"(dest), "=c"(count)
         : "S"(src), "D"(dest), "c"(count)
         : "memory");
 }
Referenced by Compositor::copy_changes_to_second_buffer(), and LG::Context::set().
fast_set()
void fast_set (uint32_t * dest, uint32_t val, size_t count) inline
Definition at line 14 of file Memory.h.
 {
     asm volatile(
         "rep stosl\n"
         : "=D"(dest), "=c"(count)
         : "D"(dest), "c"(count), "a"(val)
         : "memory");
 }
Referenced by LG::Context::fill().