oneOS: libs/libc/stdio.c File Reference
stdio.c File Reference
#include <stdio.h>
#include <syscalls.h>
Functions
size_t _find_free_slot ()
FILE * fopen (const char *filename, const char *mode)
int fseek (FILE *stream, uint32_t offset, int whence)
size_t fread (void *ptr, size_t size, size_t nmemb, FILE *stream)
Function Documentation
_find_free_slot()
size_t _find_free_slot ()
Definition at line 6 of file stdio.c.
 {
     for (size_t i = 0; i < MAX_OPENED_FILES; i++) {
         if (opened_files[i]._fileno == -1) {
             return i;
         }
     }
     return -1;
 }
References MAX_OPENED_FILES, and opened_files.
Referenced by fopen().
fopen()
FILE* fopen (const char * filename, const char * mode)
Definition at line 17 of file stdio.c.
 {
     size_t free_slot = _find_free_slot();
     if (free_slot == -1) {
         return 0;
     }
     opened_files[free_slot]._fileno = open(filename, 1);
     return &opened_files[free_slot];
 }
References __file::_fileno, _find_free_slot(), fat16_formatter::filename, open(), and opened_files.
fread()
size_t fread (void * ptr, size_t size, size_t nmemb, FILE * stream)
Definition at line 31 of file stdio.c.
 {
     return read(stream->_fileno, ptr, size);
 }
References __file::_fileno, and read().
fseek()
int fseek (FILE * stream, uint32_t offset, int whence)
Definition at line 27 of file stdio.c.
 {
 }