oneOS: dentry_ops Struct Reference
dentry_ops Struct Reference
#include <vfs.h>
Data Fields
int(* read_inode)(dentry_t *dentry)
int(* write_inode)(dentry_t *dentry)
int(* free_inode)(dentry_t *dentry)
fsdata_t(* get_fsdata)(dentry_t *dentry)
Detailed Description
Definition at line 101 of file vfs.h.
Field Documentation
free_inode
int(* dentry_ops::free_inode) (dentry_t *dentry)
Definition at line 104 of file vfs.h.
Referenced by dentry_delete_inode(), dentry_put_impl(), and vfs_add_fs().
get_fsdata
fsdata_t(* dentry_ops::get_fsdata) (dentry_t *dentry)
Definition at line 105 of file vfs.h.
Referenced by dentry_alloc_new(), and vfs_add_fs().
read_inode
int(* dentry_ops::read_inode) (dentry_t *dentry)
Definition at line 102 of file vfs.h.
Referenced by dentry_alloc_new(), and vfs_add_fs().
write_inode
int(* dentry_ops::write_inode) (dentry_t *dentry)
Definition at line 103 of file vfs.h.
Referenced by dentry_flush_inode(), and vfs_add_fs().
The documentation for this struct was generated from the following file:
include/fs/vfs.h