oneOS: file_ops Struct Reference
file_ops Struct Reference
#include <vfs.h>
Data Fields
bool(* can_read)(dentry_t *, uint32_t start)
bool(* can_write)(dentry_t *, uint32_t start)
int(* read)(dentry_t *, uint8_t *, uint32_t, uint32_t)
int(* write)(dentry_t *, uint8_t *, uint32_t, uint32_t)
int(* open)(dentry_t *dentry, struct file_descriptor *fd, uint32_t flags)
int(* truncate)(dentry_t *, uint32_t)
int(* create)(dentry_t *dentry, const char *name, uint32_t len, mode_t mode)
int(* unlink)(dentry_t *dentry)
int(* getdents)(dentry_t *dir, uint8_t *buf, uint32_t *offset, uint32_t len)
int(* lookup)(dentry_t *dentry, const char *name, uint32_t len, uint32_t *res_inode_indx)
int(* mkdir)(dentry_t *dir, const char *name, uint32_t len, mode_t mode)
int(* rmdir)(dentry_t *dir)
int(* ioctl)(dentry_t *dentry, uint32_t cmd, uint32_t arg)
struct proc_zone *(* mmap)(dentry_t *dentry, mmap_params_t *params)
Detailed Description
Definition at line 83 of file vfs.h.
Field Documentation
can_read
bool(* file_ops::can_read) (dentry_t *, uint32_t start)
Definition at line 84 of file vfs.h.
Referenced by _kbdriver_notification(), _mouse_recieve_notification(), bga_recieve_notification(), devfs_can_read(), ptmx_install(), pty_slave_create(), should_unblock_read_block(), should_unblock_select_block(), sys_select(), tty_new(), vfs_add_fs(), and vfs_can_read().
can_write
bool(* file_ops::can_write) (dentry_t *, uint32_t start)
Definition at line 85 of file vfs.h.
Referenced by _kbdriver_notification(), _mouse_recieve_notification(), bga_recieve_notification(), devfs_can_write(), ptmx_install(), pty_slave_create(), should_unblock_select_block(), should_unblock_write_block(), sys_select(), tty_new(), vfs_add_fs(), and vfs_can_write().
create
int(* file_ops::create) (dentry_t *dentry, const char *name, uint32_t len, mode_t mode)
Definition at line 90 of file vfs.h.
Referenced by vfs_add_fs(), and vfs_create().
getdents
int(* file_ops::getdents) (dentry_t *dir, uint8_t *buf, uint32_t *offset, uint32_t len)
Definition at line 92 of file vfs.h.
Referenced by vfs_add_fs(), and vfs_getdents().
ioctl
int(* file_ops::ioctl) (dentry_t *dentry, uint32_t cmd, uint32_t arg)
Definition at line 96 of file vfs.h.
Referenced by _kbdriver_notification(), _mouse_recieve_notification(), bga_recieve_notification(), devfs_ioctl(), ptmx_install(), pty_slave_create(), sys_ioctl(), tty_new(), and vfs_add_fs().
lookup
int(* file_ops::lookup) (dentry_t *dentry, const char *name, uint32_t len, uint32_t *res_inode_indx)
Definition at line 93 of file vfs.h.
Referenced by lexer.Lexer::read_operation(), lexer.Lexer::read_word(), vfs_add_fs(), and vfs_lookup().
mkdir
int(* file_ops::mkdir) (dentry_t *dir, const char *name, uint32_t len, mode_t mode)
Definition at line 94 of file vfs.h.
Referenced by vfs_add_fs(), and vfs_mkdir().
mmap
struct proc_zone*(* file_ops::mmap) (dentry_t *dentry, mmap_params_t *params)
Definition at line 96 of file vfs.h.
Referenced by _kbdriver_notification(), _mouse_recieve_notification(), bga_recieve_notification(), devfs_mmap(), vfs_add_fs(), and vfs_mmap().
open
int(* file_ops::open) (dentry_t *dentry, struct file_descriptor *fd, uint32_t flags)
Definition at line 88 of file vfs.h.
Referenced by _kbdriver_notification(), _mouse_recieve_notification(), devfs_open(), ptmx_install(), pty_slave_create(), tty_new(), vfs_add_fs(), and vfs_open().
read
int(* file_ops::read) (dentry_t *, uint8_t *, uint32_t, uint32_t)
Definition at line 86 of file vfs.h.
Referenced by _kbdriver_notification(), _mouse_recieve_notification(), _proc_load_bin(), bga_recieve_notification(), devfs_read(), ptmx_install(), pty_slave_create(), tty_new(), vfs_add_fs(), and vfs_read().
rmdir
int(* file_ops::rmdir) (dentry_t *dir)
Definition at line 95 of file vfs.h.
Referenced by vfs_add_fs(), and vfs_rmdir().
truncate
int(* file_ops::truncate) (dentry_t *, uint32_t)
Definition at line 89 of file vfs.h.
Referenced by vfs_add_fs(), and vfs_write().
unlink
int(* file_ops::unlink) (dentry_t *dentry)
Definition at line 91 of file vfs.h.
Referenced by vfs_add_fs(), and vfs_unlink().
write
int(* file_ops::write) (dentry_t *, uint8_t *, uint32_t, uint32_t)
Definition at line 87 of file vfs.h.
Referenced by _kbdriver_notification(), _mouse_recieve_notification(), bga_recieve_notification(), devfs_write(), ptmx_install(), pty_slave_create(), tty_new(), vfs_add_fs(), and vfs_write().
The documentation for this struct was generated from the following file:
include/fs/vfs.h