oneOS: include/platform/x86/tasking/switchvm.h File Reference
switchvm.h File Reference
#include <tasking/tasking.h>
#include <types.h>
Functions
void switchuvm (thread_t *thread)
Function Documentation
switchuvm()
void switchuvm (thread_t * thread)
Definition at line 8 of file switchvm.c.
 {
     system_disable_interrupts();
     if (RUNNIG_THREAD) {
         fpu_save(RUNNIG_THREAD->fpu_state);
     }
     gdt[SEG_TSS] = SEG_BG(SEGTSS_TYPE, &tss, sizeof(tss) - 1, 0);
     uint32_t esp0 = ((uint32_t)thread->tf + sizeof(trapframe_t));
     tss.esp0 = esp0;
     tss.ss0 = (SEG_KDATA << 3);
     // tss.iomap_offset = 0xffff;
     RUNNIG_THREAD = thread;
     fpu_restore(thread->fpu_state);
     ltr(SEG_TSS << 3);
     vmm_switch_pdir(thread->process->pdir);
     system_enable_interrupts();
 }
References fpu_restore(), fpu_save(), thread::fpu_state, gdt, ltr(), proc::pdir, thread::process, RUNNIG_THREAD, SEG_BG, SEG_KDATA, SEG_TSS, SEGTSS_TYPE, system_disable_interrupts(), system_enable_interrupts(), thread::tf, tss, and vmm_switch_pdir().
Referenced by sched().