oneOS: src/kernel/interrupts/sys_handler.c File Reference
sys_handler.c File Reference
#include <errno.h>
#include <io/shared_buffer/shared_buffer.h>
#include <io/sockets/local_socket.h>
#include <log.h>
#include <mem/kmalloc.h>
#include <sys_handler.h>
#include <tasking/sched.h>
#include <tasking/tasking.h>
#include <platform/x86/system.h>
Macros
#define param1 (tf->ebx)
#define param2 (tf->ecx)
#define param3 (tf->edx)
#define param4 (tf->esi)
#define param5 (tf->edi)
#define return_with_val(val)
Functions
static void set_return (trapframe_t *tf, uint32_t val)
int ksyscall_impl (int sys_id, int a, int b, int c, int d)
void sys_handler (trapframe_t *tf)
void sys_restart_syscall (trapframe_t *tf)
void sys_open (trapframe_t *tf)
void sys_close (trapframe_t *tf)
void sys_read (trapframe_t *tf)
void sys_write (trapframe_t *tf)
void sys_lseek (trapframe_t *tf)
void sys_unlink (trapframe_t *tf)
void sys_creat (trapframe_t *tf)
void sys_fstat (trapframe_t *tf)
void sys_mkdir (trapframe_t *tf)
void sys_rmdir (trapframe_t *tf)
void sys_chdir (trapframe_t *tf)
void sys_getdents (trapframe_t *tf)
void sys_select (trapframe_t *tf)
void sys_exit (trapframe_t *tf)
void sys_fork (trapframe_t *tf)
void sys_waitpid (trapframe_t *tf)
void sys_exec (trapframe_t *tf)
void sys_sigaction (trapframe_t *tf)
void sys_sigreturn (trapframe_t *tf)
void sys_raise (trapframe_t *tf)
void sys_getpid (trapframe_t *tf)
void sys_kill (trapframe_t *tf)
void sys_setpgid (trapframe_t *tf)
void sys_getpgid (trapframe_t *tf)
void sys_create_thread (trapframe_t *tf)
void sys_sleep (trapframe_t *tf)
void sys_mmap (trapframe_t *tf)
void sys_munmap (trapframe_t *tf)
void sys_socket (trapframe_t *tf)
void sys_bind (trapframe_t *tf)
void sys_connect (trapframe_t *tf)
void sys_ioctl (trapframe_t *tf)
void sys_shbuf_create (trapframe_t *tf)
void sys_shbuf_get (trapframe_t *tf)
void sys_shbuf_free (trapframe_t *tf)
void sys_sched_yield (trapframe_t *tf)
void sys_none (trapframe_t *tf)
Variables
static const void * syscalls []
Macro Definition Documentation
param1
#define param1 (tf->ebx)
Definition at line 19 of file sys_handler.c.
param2
#define param2 (tf->ecx)
Definition at line 20 of file sys_handler.c.
param3
#define param3 (tf->edx)
Definition at line 21 of file sys_handler.c.
param4
#define param4 (tf->esi)
Definition at line 22 of file sys_handler.c.
param5
#define param5 (tf->edi)
Definition at line 23 of file sys_handler.c.
return_with_val
#define return_with_val (val)
Value:
    (tf->eax = val);         \
    return
Definition at line 28 of file sys_handler.c.
Function Documentation
ksyscall_impl()
int ksyscall_impl (int sys_id, int a, int b, int c, int d)
Definition at line 78 of file sys_handler.c.
 {
     system_disable_interrupts();
     trapframe_t tf;
     tf.eax = sys_id;
     tf.ebx = a;
     tf.ecx = b;
     tf.edx = c;
     sys_handler(&tf);
     /* This hack has to be here, when a context switching happens
        during a syscall (e.g. when block occurs). The hack will start
        interrupts again after it has become a running thread. */
     system_enable_interrupts();
     return tf.eax;
 }
References sys_handler(), system_disable_interrupts(), and system_enable_interrupts().
set_return()
static void set_return (trapframe_t * tf, uint32_t val) inline static
Definition at line 73 of file sys_handler.c.
 {
     tf->eax = val;
 }
Referenced by sys_exec(), sys_sigaction(), and sys_waitpid().
sys_bind()
void sys_bind (trapframe_t * tf)
Definition at line 577 of file sys_handler.c.
 {
     proc_t* p = RUNNIG_THREAD->process;
     int sockfd = param1;
     char* name = (char*)param2;
     uint32_t len = (uint32_t)param3;
     file_descriptor_t* sfd = proc_get_fd(p, sockfd);
     if (sfd->type != FD_TYPE_SOCKET || !sfd->sock_entry) {
         return_with_val(-EBADF);
     }
     if (sfd->sock_entry->domain == PF_LOCAL) {
         return_with_val(local_socket_bind(sfd, name, len));
     }
     return_with_val(0);
 }
References socket::domain, EBADF, FD_TYPE_SOCKET, local_socket_bind(), copy_bin::name, p, param1, param2, param3, PF_LOCAL, proc_get_fd(), return_with_val, RUNNIG_THREAD, file_descriptor::sock_entry, and file_descriptor::type.
sys_chdir()
void sys_chdir (trapframe_t * tf)
Definition at line 322 of file sys_handler.c.
 {
     /* proc lock */
     const char* path = (char*)param1;
     return_with_val(proc_chdir(RUNNIG_THREAD->process, path));
 }
References param1, proc_chdir(), return_with_val, and RUNNIG_THREAD.
sys_close()
void sys_close (trapframe_t * tf)
Definition at line 143 of file sys_handler.c.
 {
     file_descriptor_t* fd = proc_get_fd(RUNNIG_THREAD->process, param1);
     if (!fd) {
         return_with_val(-EBADF);
     }
     return_with_val(vfs_close(fd));
 }
References EBADF, param1, proc_get_fd(), return_with_val, RUNNIG_THREAD, and vfs_close().
sys_connect()
void sys_connect (trapframe_t * tf)
Definition at line 596 of file sys_handler.c.
 {
     proc_t* p = RUNNIG_THREAD->process;
     int sockfd = param1;
     char* name = (char*)param2;
     uint32_t len = (uint32_t)param3;
     file_descriptor_t* sfd = proc_get_fd(p, sockfd);
     if (sfd->type != FD_TYPE_SOCKET || !sfd->sock_entry) {
         return_with_val(-EBADF);
     }
     if (sfd->sock_entry->domain == PF_LOCAL) {
         return_with_val(local_socket_connect(sfd, name, len));
     }
     return_with_val(-EFAULT);
 }
References socket::domain, EBADF, EFAULT, FD_TYPE_SOCKET, local_socket_connect(), copy_bin::name, p, param1, param2, param3, PF_LOCAL, proc_get_fd(), return_with_val, RUNNIG_THREAD, file_descriptor::sock_entry, and file_descriptor::type.
sys_creat()
void sys_creat (trapframe_t * tf)
Definition at line 233 of file sys_handler.c.
 {
     proc_t* p = RUNNIG_THREAD->process;
     const char* path = (char*)param1;
     mode_t mode = param2;
     char* kpath = 0;
     if (!str_validate_len(path, 128)) {
         return_with_val(-EINVAL);
     }
     int name_len = strlen(path);
     kpath = kmem_bring_to_kernel(path, name_len + 1);
     int err = vfs_create(p->cwd, kpath, name_len, mode);
     if (err) {
         return_with_val(err);
     }
     /* Opening file */
     file_descriptor_t* fd = proc_get_free_fd(p);
     dentry_t* file;
     if (vfs_resolve_path_start_from(p->cwd, kpath, &file) < 0) {
         return_with_val(-1);
     }
     err = vfs_open(file, fd, O_WRONLY);
     dentry_put(file);
     if (err) {
         return_with_val(err);
     }
     return_with_val(proc_get_fd_id(p, fd));
 }
References dentry_put(), EINVAL, kmem_bring_to_kernel(), mode, O_WRONLY, p, param1, param2, proc_get_fd_id(), proc_get_free_fd(), return_with_val, RUNNIG_THREAD, str_validate_len(), strlen(), vfs_create(), vfs_open(), and vfs_resolve_path_start_from().
sys_create_thread()
void sys_create_thread (trapframe_t * tf)
Definition at line 463 of file sys_handler.c.
 {
     proc_t* p = RUNNIG_THREAD->process;
     thread_t* thread = proc_create_thread(p);
     if (!thread) {
         return_with_val(-EFAULT);
     }
     thread_create_params_t* params = (thread_create_params_t*)param1;
     thread_set_eip(thread, params->entry_point);
     uint32_t esp = params->stack_start + params->stack_size;
     thread_set_stack(thread, esp, esp);
     return_with_val(thread->tid);
 }
References EFAULT, thread_create_params::entry_point, p, param1, proc_create_thread(), return_with_val, RUNNIG_THREAD, thread_create_params::stack_size, thread_create_params::stack_start, thread_set_eip(), thread_set_stack(), and thread::tid.
sys_exec()
void sys_exec (trapframe_t * tf)
Definition at line 405 of file sys_handler.c.
 {
     set_return(tf, tasking_exec((char*)param1, (const char**)param2, (const char**)param3));
 }
References param1, param2, param3, set_return(), and tasking_exec().
sys_exit()
void sys_exit (trapframe_t * tf)
TASKING SYSCALLS
Definition at line 389 of file sys_handler.c.
 {
     tasking_exit((int)param1);
 }
References param1, and tasking_exit().
sys_fork()
void sys_fork (trapframe_t * tf)
Definition at line 394 of file sys_handler.c.
 {
     tasking_fork(tf);
 }
References tasking_fork().
sys_fstat()
void sys_fstat (trapframe_t * tf)
Definition at line 264 of file sys_handler.c.
 {
     file_descriptor_t* fd = proc_get_fd(RUNNIG_THREAD->process, (int)param1);
     fstat_t* stat = (fstat_t*)param2;
     if (!fd) {
         return_with_val(-EBADF);
     }
     if (!stat) {
         return_with_val(-EINVAL);
     }
     stat->size = fd->dentry->inode->size;
     return_with_val(0);
 }
References file_descriptor::dentry, EBADF, EINVAL, dentry::inode, param1, param2, proc_get_fd(), return_with_val, RUNNIG_THREAD, inode_t::size, and fstat::size.
sys_getdents()
void sys_getdents (trapframe_t * tf)
Definition at line 329 of file sys_handler.c.
 {
     proc_t* p = RUNNIG_THREAD->process;
     file_descriptor_t* fd = (file_descriptor_t*)proc_get_fd(p, (uint32_t)param1);
     int read = vfs_getdents(fd, (uint8_t*)param2, param3);
     return_with_val(read);
 }
References p, param1, param2, param3, proc_get_fd(), read(), return_with_val, RUNNIG_THREAD, and vfs_getdents().
sys_getpgid()
void sys_getpgid (trapframe_t * tf)
Definition at line 451 of file sys_handler.c.
 {
     uint32_t pid = param1;
     proc_t* p = tasking_get_proc(pid);
     if (!p) {
         return_with_val(-ESRCH);
     }
     return_with_val(p->pgid);
 }
References ESRCH, p, param1, return_with_val, and tasking_get_proc().
sys_getpid()
void sys_getpid (trapframe_t * tf)
Definition at line 426 of file sys_handler.c.
 {
     return_with_val(RUNNIG_THREAD->tid);
 }
References return_with_val, and RUNNIG_THREAD.
sys_handler()
void sys_handler (trapframe_t * tf)
Definition at line 94 of file sys_handler.c.
 {
     system_disable_interrupts();
     void (*callee)(trapframe_t*) = (void*)syscalls[tf->eax];
     callee(tf);
     system_enable_interrupts_only_counter();
 }
References syscalls, system_disable_interrupts(), and system_enable_interrupts_only_counter().
Referenced by ksyscall_impl().
sys_ioctl()
void sys_ioctl (trapframe_t * tf)
Definition at line 615 of file sys_handler.c.
 {
     proc_t* p = RUNNIG_THREAD->process;
     file_descriptor_t* fd = proc_get_fd(p, param1);
     if (!fd) {
         return_with_val(-EBADF);
     }
     if (fd->dentry->ops->file.ioctl) {
         return_with_val(fd->dentry->ops->file.ioctl(fd->dentry, param2, param3));
     } else {
         return_with_val(-EACCES);
     }
 }
References file_descriptor::dentry, EACCES, EBADF, fs_ops::file, file_ops::ioctl, dentry::ops, p, param1, param2, param3, proc_get_fd(), return_with_val, and RUNNIG_THREAD.
sys_kill()
void sys_kill (trapframe_t * tf)
Definition at line 431 of file sys_handler.c.
 {
     thread_t* thread = thread_by_pid(param1);
     return_with_val(tasking_kill(thread, param2));
 }
References param1, param2, return_with_val, tasking_kill(), and thread_by_pid().
sys_lseek()
void sys_lseek (trapframe_t * tf)
Definition at line 180 of file sys_handler.c.
 {
     file_descriptor_t* fd = proc_get_fd(RUNNIG_THREAD->process, (int)param1);
     if (!fd) {
         return_with_val(-EBADF);
     }
     int whence = param3;
     switch (whence) {
     case SEEK_SET:
         fd->offset = param2;
         break;
     case SEEK_CUR:
         fd->offset += param2;
         break;
     case SEEK_END:
         fd->offset = fd->dentry->inode->size - param2;
         break;
     default:
         return_with_val(-EINVAL);
     }
     if (fd->offset >= fd->dentry->inode->size) {
         return_with_val(-EOVERFLOW);
     }
     return_with_val(0);
 }
References file_descriptor::dentry, EBADF, EINVAL, EOVERFLOW, dentry::inode, file_descriptor::offset, param1, param2, param3, proc_get_fd(), return_with_val, RUNNIG_THREAD, SEEK_CUR, SEEK_END, SEEK_SET, and inode_t::size.
sys_mkdir()
void sys_mkdir (trapframe_t * tf)
Definition at line 278 of file sys_handler.c.
 {
     proc_t* p = RUNNIG_THREAD->process;
     const char* path = (char*)param1;
     char* kpath = 0;
     if (!str_validate_len(path, 128)) {
         return_with_val(-EINVAL);
     }
     int name_len = strlen(path);
     kpath = kmem_bring_to_kernel(path, name_len + 1);
     // dentry_t* dir;
     // if (vfs_resolve_path_start_from(p->cwd, &dir) < 0) {
     //     return_with_val(-ENOENT);
     // }
     mode_t dir_mode = S_IFDIR | S_IRUSR | S_IWUSR | S_IXUSR | S_IRGRP | S_IXGRP | S_IROTH | S_IXOTH;
     int res = vfs_mkdir(p->cwd, kpath, name_len, dir_mode);
     kfree(kpath);
     return_with_val(res);
 }
References EINVAL, kfree(), kmem_bring_to_kernel(), p, param1, return_with_val, RUNNIG_THREAD, S_IFDIR, S_IRGRP, S_IROTH, S_IRUSR, S_IWUSR, S_IXGRP, S_IXOTH, S_IXUSR, str_validate_len(), strlen(), and vfs_mkdir().
sys_mmap()
void sys_mmap (trapframe_t * tf)
MEMORY SYSCALLS
Definition at line 493 of file sys_handler.c.
 {
     proc_t* p = RUNNIG_THREAD->process;
     mmap_params_t* params = (mmap_params_t*)param1;
     bool map_shared = ((params->flags & MAP_SHARED) > 0);
     bool map_anonymous = ((params->flags & MAP_ANONYMOUS) > 0);
     bool map_private = ((params->flags & MAP_PRIVATE) > 0);
     bool map_stack = ((params->flags & MAP_STACK) > 0);
     bool map_fixed = ((params->flags & MAP_FIXED) > 0);
     bool map_exec = ((params->prot & PROT_EXEC) > 0);
     bool map_read = ((params->prot & PROT_READ) > 0);
     bool map_write = ((params->prot & PROT_WRITE) > 0);
     proc_zone_t* zone;
     if (map_private && map_shared) {
         return_with_val(-EINVAL);
     }
     if (!map_private && !map_shared) {
         return_with_val(-EINVAL);
     }
     if (map_stack) {
         zone = proc_new_random_zone_backward(p, params->size);
     } else if (map_anonymous) {
         zone = proc_new_random_zone(p, params->size);
     } else {
         file_descriptor_t* fd = proc_get_fd(p, params->fd);
         /* TODO: Check for read access to the file */
         if (!fd) {
             return_with_val(-EBADFD);
         }
         zone = vfs_mmap(fd, params);
     }
     if (!zone) {
         return_with_val(-ENOMEM);
     }
     if (map_read) {
         zone->flags |= ZONE_READABLE;
     }
     if (map_write) {
         zone->flags |= ZONE_WRITABLE;
     }
     if (map_exec) {
         zone->flags |= ZONE_EXECUTABLE;
     }
     return_with_val(zone->start);
 }
References EBADFD, EINVAL, ENOMEM, mmap_params::fd, mmap_params::flags, proc_zone::flags, MAP_ANONYMOUS, MAP_FIXED, MAP_PRIVATE, MAP_SHARED, MAP_STACK, p, param1, proc_get_fd(), proc_new_random_zone(), proc_new_random_zone_backward(), mmap_params::prot, PROT_EXEC, PROT_READ, PROT_WRITE, return_with_val, RUNNIG_THREAD, mmap_params::size, proc_zone::start, vfs_mmap(), ZONE_EXECUTABLE, ZONE_READABLE, and ZONE_WRITABLE.
sys_munmap()
void sys_munmap (trapframe_t * tf)
Definition at line 547 of file sys_handler.c.
 {
 }
sys_none()
void sys_none (trapframe_t * tf)
Definition at line 660 of file sys_handler.c.
 { }
sys_open()
void sys_open (trapframe_t * tf)
FS SYSCALLS
Definition at line 111 of file sys_handler.c.
 {
     proc_t* p = RUNNIG_THREAD->process;
     file_descriptor_t* fd = proc_get_free_fd(p);
     const char* path = (char*)param1;
     char* kpath = 0;
     if (!str_validate_len(path, 128)) {
         return_with_val(-EINVAL);
     }
     int name_len = strlen(path);
     kpath = kmem_bring_to_kernel(path, name_len + 1);
     uint32_t flags = param2;
     mode_t mode = S_IFREG | S_IRWXU | S_IRWXG | S_IRWXO;
     dentry_t* file;
     if (flags & O_CREATE) {
         vfs_create(p->cwd, kpath, name_len, mode);
     }
     if (vfs_resolve_path_start_from(p->cwd, kpath, &file) < 0) {
         return_with_val(-ENOENT);
     }
     int res = vfs_open(file, fd, param2);
     dentry_put(file);
     if (!res) {
         return_with_val(proc_get_fd_id(p, fd));
     } else {
         return_with_val(res);
     }
 }
References dentry_put(), EINVAL, ENOENT, kmem_bring_to_kernel(), mode, O_CREATE, p, param1, param2, proc_get_fd_id(), proc_get_free_fd(), return_with_val, RUNNIG_THREAD, S_IFREG, S_IRWXG, S_IRWXO, S_IRWXU, str_validate_len(), strlen(), vfs_create(), vfs_open(), and vfs_resolve_path_start_from().
sys_raise()
void sys_raise (trapframe_t * tf)
Definition at line 420 of file sys_handler.c.
 {
     signal_set_pending(RUNNIG_THREAD, (int)param1);
     signal_dispatch_pending(RUNNIG_THREAD);
 }
References param1, RUNNIG_THREAD, signal_dispatch_pending(), and signal_set_pending().
sys_read()
void sys_read (trapframe_t * tf)
Definition at line 153 of file sys_handler.c.
 {
     file_descriptor_t* fd = proc_get_fd(RUNNIG_THREAD->process, (int)param1);
     if (!fd) {
         return_with_val(-EBADF);
     }
     init_read_blocker(RUNNIG_THREAD, fd);
     int res = vfs_read(fd, (uint8_t*)param2, (uint32_t)param3);
     return_with_val(res);
 }
References EBADF, init_read_blocker(), param1, param2, param3, proc_get_fd(), return_with_val, RUNNIG_THREAD, and vfs_read().
sys_restart_syscall()
void sys_restart_syscall (trapframe_t * tf)
Definition at line 102 of file sys_handler.c.
 {
     kprintd(tf->ebx);
 }
References kprintd().
sys_rmdir()
void sys_rmdir (trapframe_t * tf)
Definition at line 300 of file sys_handler.c.
 {
     proc_t* p = RUNNIG_THREAD->process;
     const char* path = (char*)param1;
     char* kpath = 0;
     if (!str_validate_len(path, 128)) {
         return_with_val(-EINVAL);
     }
     int name_len = strlen(path);
     kpath = kmem_bring_to_kernel(path, name_len + 1);
     dentry_t* dir;
     if (vfs_resolve_path_start_from(p->cwd, kpath, &dir) < 0) {
         return_with_val(-ENOENT);
     }
     int res = vfs_rmdir(dir);
     dentry_put(dir);
     kfree(kpath);
     return_with_val(res);
 }
References dentry_put(), EINVAL, ENOENT, kfree(), kmem_bring_to_kernel(), p, param1, return_with_val, RUNNIG_THREAD, str_validate_len(), strlen(), vfs_resolve_path_start_from(), and vfs_rmdir().
sys_sched_yield()
void sys_sched_yield (trapframe_t * tf)
Scheduler
Definition at line 655 of file sys_handler.c.
 {
     resched();
 }
References resched().
sys_select()
void sys_select (trapframe_t * tf)
Definition at line 337 of file sys_handler.c.
 {
     proc_t* p = RUNNIG_THREAD->process;
     file_descriptor_t* fd;
     int nfds = param1;
     fd_set_t* readfds = (fd_set_t*)param2;
     fd_set_t* writefds = (fd_set_t*)param3;
     fd_set_t* exceptfds = (fd_set_t*)param4;
     timeval_t* timeout = (timeval_t*)param5;
     if (nfds < 0 || nfds > FD_SETSIZE) {
         return_with_val(-EINVAL);
     }
     for (int i = 0; i < nfds; i++) {
         if (FD_ISSET(i, readfds) || FD_ISSET(i, writefds) || FD_ISSET(i, exceptfds)) {
             if (!proc_get_fd(p, i)) {
                 return_with_val(-EBADF);
             }
         }
     }
     init_select_blocker(RUNNIG_THREAD, nfds, readfds, writefds, exceptfds, timeout);
     if (readfds)
         FD_ZERO(readfds);
     if (writefds)
         FD_ZERO(writefds);
     if (exceptfds)
         FD_ZERO(exceptfds);
     for (int i = 0; i < nfds; i++) {
         fd = proc_get_fd(p, i);
         if (readfds && FD_ISSET(i, &(RUNNIG_THREAD->readfds))) {
             if (fd->ops->can_read && fd->ops->can_read(fd->dentry, fd->offset)) {
                 FD_SET(i, readfds);
             }
         }
         if (writefds && FD_ISSET(i, &(RUNNIG_THREAD->writefds))) {
             if (fd->ops->can_write && fd->ops->can_write(fd->dentry, fd->offset)) {
                 FD_SET(i, writefds);
             }
         }
     }
     return_with_val(0);
 }
References file_ops::can_read, file_ops::can_write, file_descriptor::dentry, EBADF, EINVAL, FD_ISSET, FD_SET, FD_SETSIZE, FD_ZERO, init_select_blocker(), file_descriptor::offset, file_descriptor::ops, p, param1, param2, param3, param4, param5, proc_get_fd(), return_with_val, and RUNNIG_THREAD.
sys_setpgid()
void sys_setpgid (trapframe_t * tf)
Definition at line 437 of file sys_handler.c.
 {
     uint32_t pid = param1;
     uint32_t pgid = param2;
     proc_t* p = tasking_get_proc(pid);
     if (!p) {
         return_with_val(-ESRCH);
     }
     p->pgid = pgid;
     return_with_val(0);
 }
References ESRCH, p, param1, param2, return_with_val, and tasking_get_proc().
sys_shbuf_create()
void sys_shbuf_create (trapframe_t * tf)
Definition at line 631 of file sys_handler.c.
 {
     uint8_t** buffer = (uint8_t**)param1;
     size_t size = param2;
     return_with_val(shared_buffer_create(buffer, size));
 }
References param1, param2, return_with_val, and shared_buffer_create().
sys_shbuf_free()
void sys_shbuf_free (trapframe_t * tf)
Definition at line 645 of file sys_handler.c.
 {
     int id = param1;
     return_with_val(shared_buffer_free(id));
 }
References param1, return_with_val, and shared_buffer_free().
sys_shbuf_get()
void sys_shbuf_get (trapframe_t * tf)
Definition at line 638 of file sys_handler.c.
 {
     int id = param1;
     uint8_t** buffer = (uint8_t**)param2;
     return_with_val(shared_buffer_get(id, buffer));
 }
References param1, param2, return_with_val, and shared_buffer_get().
sys_sigaction()
void sys_sigaction (trapframe_t * tf)
Definition at line 410 of file sys_handler.c.
 {
     set_return(tf, signal_set_handler(RUNNIG_THREAD, (int)param1, (void*)param2));
 }
References param1, param2, RUNNIG_THREAD, set_return(), and signal_set_handler().
sys_sigreturn()
void sys_sigreturn (trapframe_t * tf)
Definition at line 415 of file sys_handler.c.
 {
     signal_restore_thread_after_handling_signal(RUNNIG_THREAD);
 }
References RUNNIG_THREAD, and signal_restore_thread_after_handling_signal().
sys_sleep()
void sys_sleep (trapframe_t * tf)
Definition at line 479 of file sys_handler.c.
 {
     thread_t* p = RUNNIG_THREAD;
     time_t time = param1;
     init_sleep_blocker(RUNNIG_THREAD, time);
     return_with_val(0);
 }
References init_sleep_blocker(), p, param1, return_with_val, and RUNNIG_THREAD.
sys_socket()
void sys_socket (trapframe_t * tf)
IO SYSCALLS
Definition at line 555 of file sys_handler.c.
 {
     proc_t* p = RUNNIG_THREAD->process;
     int domain = param1;
     int type = param2;
     int protocol = param3;
     file_descriptor_t* fd = proc_get_free_fd(p);
     if (!fd) {
         return_with_val(-1);
     }
     if (domain == PF_LOCAL) {
         int res = local_socket_create(type, protocol, fd);
         if (!res) {
             return_with_val(proc_get_fd_id(p, fd));
         } else {
             return_with_val(res);
         }
     }
 }
References local_socket_create(), p, param1, param2, param3, PF_LOCAL, proc_get_fd_id(), proc_get_free_fd(), return_with_val, RUNNIG_THREAD, and type.
sys_unlink()
void sys_unlink (trapframe_t * tf)
Definition at line 210 of file sys_handler.c.
 {
     proc_t* p = RUNNIG_THREAD->process;
     const char* path = (char*)param1;
     char* kpath = 0;
     if (!str_validate_len(path, 128)) {
         return_with_val(-EINVAL);
     }
     int name_len = strlen(path);
     kpath = kmem_bring_to_kernel(path, name_len + 1);
     dentry_t* file;
     if (vfs_resolve_path_start_from(p->cwd, kpath, &file) < 0) {
         return_with_val(-ENOENT);
     }
     int ret = vfs_unlink(file);
     dentry_put(file);
     kfree(kpath);
     return_with_val(ret);
 }
References dentry_put(), EINVAL, ENOENT, kfree(), kmem_bring_to_kernel(), p, param1, return_with_val, RUNNIG_THREAD, str_validate_len(), strlen(), vfs_resolve_path_start_from(), and vfs_unlink().
sys_waitpid()
void sys_waitpid (trapframe_t * tf)
Definition at line 399 of file sys_handler.c.
 {
     int ret = tasking_waitpid(param1);
     set_return(tf, ret);
 }
References param1, set_return(), and tasking_waitpid().
sys_write()
void sys_write (trapframe_t * tf)
Definition at line 167 of file sys_handler.c.
 {
     file_descriptor_t* fd = proc_get_fd(RUNNIG_THREAD->process, (int)param1);
     if (!fd) {
         return_with_val(-EBADF);
     }
     init_write_blocker(RUNNIG_THREAD, fd);
     int res = vfs_write(fd, (uint8_t*)param2, (uint32_t)param3);
     return_with_val(res);
 }
References EBADF, init_write_blocker(), param1, param2, param3, proc_get_fd(), return_with_val, RUNNIG_THREAD, and vfs_write().
Variable Documentation
syscalls
const void* syscalls[] static
Definition at line 32 of file sys_handler.c.
Referenced by sys_handler().