oneOS: libs/libc/syscalls.c File Reference
syscalls.c File Reference
#include <sys/time.h>
#include <syscalls.h>
Functions
static int syscall (sysid_t sysid, int p1, int p2, int p3, int p4, int p5)
int read (int fd, char *buf, size_t count)
int write (int fd, const void *buf, size_t count)
void exit (int ret_code)
int fork ()
int wait (int pid)
int execve (const char *path, char **argv, char **env)
int chdir (char *path)
int mkdir (char *path)
int rmdir (char *path)
int unlink (char *path)
int creat (char *path, uint32_t mode)
int open (const char *pathname, int flags)
int close (int fd)
int sigaction (int signo, void *callback)
int raise (int signo)
int kill (pid_t pid, int signo)
int mmap (mmap_params_t *params)
int socket (int domain, int type, int protocol)
int bind (int sockfd, const char *name, int len)
int connect (int sockfd, const char *name, int len)
int getdents (int fd, char *buf, int len)
int ioctl (int fd, uint32_t cmd, uint32_t arg)
int lseek (int fd, uint32_t off, int whence)
int select (int nfds, fd_set_t *readfds, fd_set_t *writefds, fd_set_t *exceptfds, timeval_t *timeout)
int fstat (int nfds, fstat_t *stat)
pid_t getpid ()
int setpgid (pid_t pid, pid_t pgid)
pid_t getpgid (pid_t pid)
int system_pthread_create (thread_create_params_t *params)
int shared_buffer_create (uint8_t **buffer, size_t size)
int shared_buffer_get (int id, uint8_t **buffer)
int shared_buffer_free (int id)
void sched_yield ()
Variables
int errno
Function Documentation
bind()
int bind (int sockfd, const char * name, int len)
Definition at line 114 of file syscalls.c.
 {
     return syscall(SYSBIND, (int)sockfd, (int)name, (int)len, 0, 0);
 }
References copy_bin::name, SYSBIND, and syscall().
Referenced by Connection::Connection(), and main().
chdir()
int chdir (char * path)
Definition at line 54 of file syscalls.c.
 {
     return syscall(SYSCHDIR, (int)path, 0, 0, 0, 0);
 }
References syscall(), and SYSCHDIR.
Referenced by _cmd_do_internal(), and dirfile().
close()
int close (int fd)
Definition at line 84 of file syscalls.c.
 {
     return syscall(SYSCLOSE, (int)fd, 0, 0, 0, 0);
 }
References syscall(), and SYSCLOSE.
Referenced by dirfile(), file_exit(), fourfiles(), generator.Generator::generate(), main(), setup_shell(), and WindowFrame::WindowFrame().
connect()
int connect (int sockfd, const char * name, int len)
Definition at line 119 of file syscalls.c.
 {
     return syscall(SYSCONNECT, (int)sockfd, (int)name, (int)len, 0, 0);
 }
References copy_bin::name, syscall(), and SYSCONNECT.
Referenced by UI::Connection::Connection().
creat()
int creat (char * path, uint32_t mode)
Definition at line 74 of file syscalls.c.
 {
     return syscall(SYSCREAT, (int)path, (int)mode, 0, 0, 0);
 }
References mode, syscall(), and SYSCREAT.
Referenced by main().
execve()
int execve (const char * path, char ** argv, char ** env)
Definition at line 49 of file syscalls.c.
 {
     return syscall(SYSEXEC, (int)path, (int)argv, (int)env, 0, 0);
 }
References syscall(), and SYSEXEC.
Referenced by _cmd_processor(), DockView::launch(), main(), setup_shell(), and start_dock().
exit()
void exit (int ret_code)
Definition at line 34 of file syscalls.c.
 {
     syscall(SYSEXIT, ret_code, 0, 0, 0, 0);
 }
References syscall(), and SYSEXIT.
Referenced by _cmd_processor(), connection.Connection::add_function(), connection.Connection::add_message(), cat(), crash_app(), dirfile(), exit_app(), exitwait(), fat16_formatter::fat(), fat16_formatter::fat_size(), fourfiles(), mem(), parser.Parser::must_next(), and lexer.Lexer::read_number().
fork()
int fork ()
Definition at line 39 of file syscalls.c.
 {
     return syscall(SYSFORK, 0, 0, 0, 0, 0);
 }
References syscall(), and SYSFORK.
Referenced by _cmd_processor(), exitwait(), fourfiles(), DockView::launch(), main(), mem(), setup_shell(), and start_dock().
fstat()
int fstat (int nfds, fstat_t * stat)
Definition at line 144 of file syscalls.c.
 {
     return syscall(SYSFSTAT, (int)nfds, (int)stat, 0, 0, 0);
 }
References syscall(), and SYSFSTAT.
Referenced by LG::PNG::PNGLoader::load_from_file(), and LG::Font::load_from_file().
getdents()
int getdents (int fd, char * buf, int len)
Definition at line 124 of file syscalls.c.
 {
     return syscall(SYSGETDENTS, (int)fd, (int)buf, (int)len, 0, 0);
 }
References buf, syscall(), and SYSGETDENTS.
Referenced by main().
getpgid()
pid_t getpgid (pid_t pid)
Definition at line 159 of file syscalls.c.
 {
     return syscall(SYSGETPGID, (int)pid, 0, 0, 0, 0);
 }
References syscall(), and SYSGETPGID.
Referenced by main().
getpid()
pid_t getpid ()
Definition at line 149 of file syscalls.c.
 {
     return syscall(SYSGETPID, 0, 0, 0, 0, 0);
 }
References syscall(), and SYSGETPID.
Referenced by UI::Connection::greeting(), main(), mem(), ClientConnection< ServerDecoder, ClientDecoder >::pump_messages(), and ServerConnection< ServerDecoder, ClientDecoder >::pump_messages().
ioctl()
int ioctl (int fd, uint32_t cmd, uint32_t arg)
Definition at line 129 of file syscalls.c.
 {
     return syscall(SYSIOCTL, (int)fd, (int)cmd, (int)arg, 0, 0);
 }
References cmd, syscall(), and SYSIOCTL.
Referenced by main(), Screen::swap_buffers(), tcgetattr(), tcgetpgrp(), tcsetattr(), and tcsetpgrp().
kill()
int kill (pid_t pid, int signo)
Definition at line 99 of file syscalls.c.
 {
     return syscall(SYSKILL, (int)pid, (int)signo, 0, 0, 0);
 }
References syscall(), and SYSKILL.
Referenced by inter(), and mem().
lseek()
int lseek (int fd, uint32_t off, int whence)
Definition at line 134 of file syscalls.c.
 {
     return syscall(SYSLSEEK, (int)fd, (int)off, (int)whence, 0, 0);
 }
References syscall(), and SYSLSEEK.
Referenced by _file_buf_flush(), and _file_buf_reload().
mkdir()
int mkdir (char * path)
Definition at line 59 of file syscalls.c.
 {
     return syscall(SYSMKDIR, (int)path, 0, 0, 0, 0);
 }
References syscall(), and SYSMKDIR.
Referenced by main().
mmap()
int mmap (mmap_params_t * params)
Definition at line 104 of file syscalls.c.
 {
     return syscall(SYSMMAP, (int)params, 0, 0, 0, 0);
 }
References syscall(), and SYSMMAP.
Referenced by _alloc_new_block(), LG::PNG::PNGLoader::load_from_file(), LG::Font::load_from_file(), main(), pthread_create(), and Screen::Screen().
open()
int open (const char * pathname, int flags)
Definition at line 79 of file syscalls.c.
 {
     return syscall(SYSOPEN, (int)pathname, flags, 0, 0, 0);
 }
References syscall(), and SYSOPEN.
Referenced by Devices::Devices(), dirfile(), file_open(), fopen(), fourfiles(), generator.Generator::generate(), LG::PNG::PNGLoader::load_from_file(), LG::Font::load_from_file(), main(), copy_bin::open_app(), copy_bin::open_file(), fat16_formatter::open_file(), opendir(), __main__::run(), Screen::Screen(), setup_shell(), copy_bin::write_file(), and fat16_formatter::write_file().
raise()
int raise (int signo)
Definition at line 94 of file syscalls.c.
 {
     return syscall(SYSRAISE, (int)signo, 0, 0, 0, 0);
 }
References syscall(), and SYSRAISE.
read()
int read (int fd, char * buf, size_t count)
Definition at line 24 of file syscalls.c.
 {
     return syscall(SYSREAD, (int)fd, (int)buf, (int)count, 0, 0);
 }
References buf, syscall(), and SYSREAD.
Referenced by _cmd_input(), _ext2_lite_read(), _ext2_read_from_dev(), _ext2_write_to_dev(), _file_buf_reload(), cat(), ext2_lite_init(), fourfiles(), fread(), get_key(), local_socket_read(), main(), Devices::pump_keyboard(), ClientConnection< ServerDecoder, ClientDecoder >::pump_messages(), ServerConnection< ServerDecoder, ClientDecoder >::pump_messages(), Devices::pump_mouse(), sys_getdents(), TerminalView::TerminalView(), and vfs_read().
rmdir()
int rmdir (char * path)
Definition at line 64 of file syscalls.c.
 {
     return syscall(SYSRMDIR, (int)path, 0, 0, 0, 0);
 }
References syscall(), and SYSRMDIR.
Referenced by main().
sched_yield()
void sched_yield ()
Definition at line 184 of file syscalls.c.
 {
     syscall(SYSSCHEDYIELD, 0, 0, 0, 0, 0);
 }
References syscall(), and SYSSCHEDYIELD.
Referenced by LFoundation::EventLoop::pump().
select()
int select (int nfds, fd_set_t * readfds, fd_set_t * writefds, fd_set_t * exceptfds, timeval_t * timeout)
Definition at line 139 of file syscalls.c.
 {
     return syscall(SYSSELECT, (int)nfds, (int)readfds, (int)writefds, (int)exceptfds, (int)timeout);
 }
References syscall(), and SYSSELECT.
Referenced by LFoundation::EventLoop::check_fds().
setpgid()
int setpgid (pid_t pid, pid_t pgid)
Definition at line 154 of file syscalls.c.
 {
     return syscall(SYSSETPGID, (int)pid, (int)pgid, 0, 0, 0);
 }
References syscall(), and SYSSETPGID.
shared_buffer_create()
int shared_buffer_create (uint8_t ** buffer, size_t size)
Definition at line 169 of file syscalls.c.
 {
     return syscall(SYS_SHBUF_CREATE, (int)buffer, (int)size, 0, 0, 0);
 }
shared_buffer_free()
int shared_buffer_free (int id)
Definition at line 179 of file syscalls.c.
 {
     return syscall(SYS_SHBUF_FREE, (int)id, 0, 0, 0, 0);
 }
shared_buffer_get()
int shared_buffer_get (int id, uint8_t ** buffer)
Definition at line 174 of file syscalls.c.
 {
     return syscall(SYS_SHBUF_GET, id, (int)buffer, 0, 0, 0);
 }
sigaction()
int sigaction (int signo, void * callback)
Definition at line 89 of file syscalls.c.
 {
     return syscall(SYSSIGACTION, (int)signo, (int)callback, 0, 0, 0);
 }
References syscall(), and SYSSIGACTION.
Referenced by main().
socket()
int socket (int domain, int type, int protocol)
Definition at line 109 of file syscalls.c.
 {
     return syscall(SYSSOCKET, (int)domain, (int)type, (int)protocol, 0, 0);
 }
References syscall(), SYSSOCKET, and type.
Referenced by main(), and UI::Connection::the().
syscall()
static int syscall (sysid_t sysid, int p1, int p2, int p3, int p4, int p5) inline static
Definition at line 14 of file syscalls.c.
 {
     int ret;
     asm volatile("push %%ebx;movl %2,%%ebx;int $0x80;pop %%ebx"
                  : "=a"(ret)
                  : "0"(sysid), "r"((int)(p1)), "c"((int)(p2)), "d"((int)(p3)), "S"((int)(p4)), "D"((int)(p5))
                  : "memory");
     return ret;
 }
Referenced by bind(), chdir(), close(), connect(), creat(), execve(), exit(), fork(), fstat(), getdents(), getpgid(), getpid(), ioctl(), kill(), lseek(), mkdir(), mmap(), open(), raise(), read(), rmdir(), sched_yield(), select(), setpgid(), shared_buffer_create(), shared_buffer_free(), shared_buffer_get(), sigaction(), socket(), system_pthread_create(), unlink(), wait(), and write().
system_pthread_create()
int system_pthread_create (thread_create_params_t * params)
Definition at line 164 of file syscalls.c.
 {
     return syscall(SYSPTHREADCREATE, (int)params, 0, 0, 0, 0);
 }
References syscall(), and SYSPTHREADCREATE.
Referenced by pthread_create().
unlink()
int unlink (char * path)
Definition at line 69 of file syscalls.c.
 {
     return syscall(SYSUNLINK, (int)path, 0, 0, 0, 0);
 }
References syscall(), and SYSUNLINK.
Referenced by dirfile(), fourfiles(), and main().
wait()
int wait (int pid)
Definition at line 44 of file syscalls.c.
 {
     return syscall(SYSWAITPID, pid, 0, 0, 0, 0);
 }
References syscall(), and SYSWAITPID.
Referenced by _cmd_processor(), exitwait(), fourfiles(), and mem().
write()
int write (int fd, const void * buf, size_t count)
Definition at line 29 of file syscalls.c.
 {
     return syscall(SYSWRITE, (int)fd, (int)buf, (int)count, 0, 0);
 }
References buf, syscall(), and SYSWRITE.
Referenced by _cmd_loop_end(), _cmd_loop_start(), _ext2_write_to_dev(), _file_buf_flush(), _log_dec(), _viewer_display_one(), _viewer_new_line(), _viewer_set_cursor(), _viewer_set_cursor_to_start(), acceptsig(), cat(), dirfile(), exitwait(), fourfiles(), LG::Font::load_from_mem(), main(), mem(), menu_accept_key(), menu_enter_mode(), generator.Generator::out(), print_dec(), print_int(), TerminalView::send_input(), ClientConnection< ServerDecoder, ClientDecoder >::send_message(), ServerConnection< ServerDecoder, ClientDecoder >::send_message(), viewer_clear_screen(), viewer_display(), and viewer_enter_menu_mode().
Variable Documentation
errno
int errno
Definition at line 12 of file syscalls.c.
Referenced by closedir(), and opendir().