oneOS: include/cmd/system_commands.h File Reference
system_commands.h File Reference
#include <cmd/cmd.h>
Functions
void syscmd_init ()
Function Documentation
syscmd_init()
void syscmd_init ()
Definition at line 217 of file system_commands.c.
 {
     cmd_register("mkdir", _syscmd_mkdir);
     cmd_register("ls", _syscmd_ls);
     cmd_register("shutdown", _syscmd_shutdown);
     cmd_register("umode", umode);
     cmd_register("cat", read);
     cmd_register("procfs", procfs);
     cmd_register("devadd", devadd);
     cmd_register("umount", umount);
     cmd_register("touch", touch);
     cmd_register("rm", rm);
     cmd_register("write", write);
     cmd_register("dentries", dentries_stat);
 }
References _syscmd_ls(), _syscmd_mkdir(), _syscmd_shutdown(), cmd_register(), dentries_stat(), devadd(), procfs(), read(), rm(), touch(), umode(), umount(), and write().
Referenced by stage3().