oneOS: include/platform/x86/system.h File Reference
system.h File Reference
#include <platform/x86/registers.h>
#include <types.h>
Functions
void system_disable_interrupts ()
void system_enable_interrupts ()
void system_enable_interrupts_only_counter ()
static void system_set_pdir (uint32_t pdir)
static void system_flush_tlb_entry (uint32_t vaddr)
static void system_flush_whole_tlb ()
static void system_enable_write_protect ()
static void system_disable_write_protect ()
static void system_enable_paging ()
static void system_disable_paging ()
static void system_stop ()
Function Documentation
system_disable_interrupts()
void system_disable_interrupts ()
INTS
Definition at line 15 of file system.c.
 {
     depth_counter++;
     asm volatile("cli");
 }
References depth_counter.
Referenced by _pit_set_frequency(), _vmm_init_switch_to_kernel_pdir(), dentry_flusher(), irq_handler(), isr_handler(), ksyscall_impl(), signal_setup_stack_to_handle_signal(), stage3(), switchuvm(), sys_handler(), and vmm_switch_pdir().
system_disable_paging()
static void system_disable_paging () inline static
Definition at line 66 of file system.h.
 {
     asm volatile("mov %cr0, %eax");
     asm volatile("and $0x7FFFFFFF, %eax");
     asm volatile("mov %eax, %cr0");
 }
Referenced by vmm_disable_paging().
system_disable_write_protect()
static void system_disable_write_protect () inline static
Definition at line 52 of file system.h.
 {
     asm volatile("mov %cr0, %eax");
     asm volatile("and $0xFFFEFFFF, %eax");
     asm volatile("mov %eax, %cr0");
 }
system_enable_interrupts()
void system_enable_interrupts ()
Definition at line 21 of file system.c.
 {
     depth_counter--;
     if (depth_counter == 0) {
         asm volatile("sti");
     }
 }
References depth_counter.
Referenced by _pit_set_frequency(), _tasking_jumper(), _vmm_init_switch_to_kernel_pdir(), dentry_flusher(), ksyscall_impl(), signal_setup_stack_to_handle_signal(), switchuvm(), and vmm_switch_pdir().
system_enable_interrupts_only_counter()
void system_enable_interrupts_only_counter ()
Definition at line 29 of file system.c.
 {
     depth_counter--;
 }
References depth_counter.
Referenced by irq_handler(), isr_handler(), and sys_handler().
system_enable_paging()
static void system_enable_paging () inline static
Definition at line 59 of file system.h.
 {
     asm volatile("mov %cr0, %eax");
     asm volatile("or $0x80000000, %eax");
     asm volatile("mov %eax, %cr0");
 }
Referenced by vmm_enable_paging().
system_enable_write_protect()
static void system_enable_write_protect () inline static
Definition at line 45 of file system.h.
 {
     asm volatile("mov %cr0, %eax");
     asm volatile("or $0x10000, %eax");
     asm volatile("mov %eax, %cr0");
 }
system_flush_tlb_entry()
static void system_flush_tlb_entry (uint32_t vaddr) inline static
Definition at line 34 of file system.h.
 {
     asm volatile("invlpg (%0)" ::"r"(vaddr)
                  : "memory");
 }
Referenced by vmm_map_page(), vmm_tune_page(), and vmm_unmap_page().
system_flush_whole_tlb()
static void system_flush_whole_tlb () inline static
Definition at line 40 of file system.h.
 {
     system_set_pdir(read_cr3());
 }
References read_cr3(), and system_set_pdir().
Referenced by vmm_new_forked_user_pdir().
system_set_pdir()
static void system_set_pdir (uint32_t pdir) inline static
PAGING
Definition at line 27 of file system.h.
 {
     asm volatile("mov %%eax, %%cr3"
                  :
                  : "a"(pdir));
 }
Referenced by _vmm_init_switch_to_kernel_pdir(), system_flush_whole_tlb(), and vmm_switch_pdir().
system_stop()
static void system_stop () inline static
Definition at line 73 of file system.h.
 {
     asm volatile("cli\n");
     asm volatile("hlt\n");
 }
Referenced by kpanic().