oneOS: src/kernel/platform/x86/system.c File Reference
system.c File Reference
#include <platform/x86/system.h>
Functions
void system_disable_interrupts ()
void system_enable_interrupts ()
void system_enable_interrupts_only_counter ()
Variables
static int depth_counter = 0
Function Documentation
system_disable_interrupts()
void system_disable_interrupts ()
INTS
Definition at line 15 of file system.c.
 {
     depth_counter++;
     asm volatile("cli");
 }
References depth_counter.
Referenced by _pit_set_frequency(), _vmm_init_switch_to_kernel_pdir(), dentry_flusher(), irq_handler(), isr_handler(), ksyscall_impl(), signal_setup_stack_to_handle_signal(), stage3(), switchuvm(), sys_handler(), and vmm_switch_pdir().
system_enable_interrupts()
void system_enable_interrupts ()
Definition at line 21 of file system.c.
 {
     depth_counter--;
     if (depth_counter == 0) {
         asm volatile("sti");
     }
 }
References depth_counter.
Referenced by _pit_set_frequency(), _tasking_jumper(), _vmm_init_switch_to_kernel_pdir(), dentry_flusher(), ksyscall_impl(), signal_setup_stack_to_handle_signal(), switchuvm(), and vmm_switch_pdir().
system_enable_interrupts_only_counter()
void system_enable_interrupts_only_counter ()
Definition at line 29 of file system.c.
 {
     depth_counter--;
 }
References depth_counter.
Referenced by irq_handler(), isr_handler(), and sys_handler().
Variable Documentation
depth_counter
int depth_counter = 0 static
Definition at line 13 of file system.c.
Referenced by system_disable_interrupts(), system_enable_interrupts(), and system_enable_interrupts_only_counter().