oneOS: include/tasking/tasking.h File Reference
tasking.h File Reference
#include <fs/vfs.h>
#include <mem/vmm/vmm.h>
#include <mem/vmm/zoner.h>
#include <tasking/proc.h>
#include <tasking/thread.h>
#include <types.h>
#include <platform/x86/idt.h>
Data Structures
struct __attribute__
Macros
#define CPU_CNT 1
#define THIS_CPU (&cpus[0])
#define RUNNIG_THREAD cpus[0].running_thread
#define MAX_PROCESS_COUNT 1024
#define MAX_DYING_PROCESS_COUNT 8
#define MAX_OPENED_FILES 16
#define SIGNALS_CNT 32
Functions
proc_t * tasking_get_proc (uint32_t pid)
proc_t * tasking_get_proc_by_pdir (pdirectory_t *pdir)
void switchuvm (thread_t *p)
void tasking_start_init_proc ()
int tasking_create_kernel_thread (void *entry_point)
void tasking_init ()
void tasking_kill_dying ()
void tasking_fork (trapframe_t *tf)
int tasking_exec (const char *path, const char **argv, const char **env)
void tasking_exit (int exit_code)
int tasking_waitpid (int pid)
int tasking_kill (thread_t *thread, int signo)
void signal_init ()
int signal_set_handler (thread_t *thread, int signo, void *handler)
int signal_set_allow (thread_t *thread, int signo)
int signal_set_private (thread_t *thread, int signo)
int signal_set_pending (thread_t *thread, int signo)
int signal_rem_pending (thread_t *thread, int signo)
int signal_restore_thread_after_handling_signal (thread_t *thread)
int signal_dispatch_pending (thread_t *thread)
Variables
cpu_t cpus [1]
proc_t proc [1024]
uint32_t nxt_proc
uint32_t ended_proc
Macro Definition Documentation
CPU_CNT
#define CPU_CNT 1
Definition at line 20 of file tasking.h.
MAX_DYING_PROCESS_COUNT
#define MAX_DYING_PROCESS_COUNT 8
Definition at line 24 of file tasking.h.
MAX_OPENED_FILES
#define MAX_OPENED_FILES 16
Definition at line 25 of file tasking.h.
MAX_PROCESS_COUNT
#define MAX_PROCESS_COUNT 1024
Definition at line 23 of file tasking.h.
RUNNIG_THREAD
#define RUNNIG_THREAD cpus[0].running_thread
Definition at line 22 of file tasking.h.
SIGNALS_CNT
#define SIGNALS_CNT 32
Definition at line 26 of file tasking.h.
THIS_CPU
#define THIS_CPU (&cpus[0])
Definition at line 21 of file tasking.h.
Function Documentation
signal_dispatch_pending()
int signal_dispatch_pending (thread_t * thread)
Definition at line 257 of file signal.c.
 {
     uint32_t candidate_signals = thread->pending_signals_mask & thread->signals_mask;
     if (!candidate_signals) {
         return -EACCES;
     }
     uint32_t signo = 1;
     for (; signo < 32; signo++) {
         if (candidate_signals & (1 << signo)) {
             break;
         }
     }
     signal_rem_pending(thread, signo);
     int ret = signal_process(thread, signo);
     if (ret < 0) {
         return ret;
     }
     if (ret == UNBLOCK) {
         if (thread->status == THREAD_BLOCKED) {
             if (!thread->blocker.should_unblock_for_signal) {
                 return -1;
             }
             thread->status = THREAD_RUNNING;
             sched_enqueue(thread);
         }
     }
     return 0;
 }
References thread::blocker, EACCES, thread::pending_signals_mask, sched_enqueue(), blocker::should_unblock_for_signal, signal_process(), signal_rem_pending(), thread::signals_mask, thread::status, THREAD_BLOCKED, THREAD_RUNNING, and UNBLOCK.
Referenced by sys_raise(), tasking_kill(), and tty_eat_key().
signal_init()
void signal_init ()
SIGNALS
Definition at line 45 of file signal.c.
 {
     _signal_init_caller();
 }
References _signal_init_caller().
Referenced by tasking_init().
signal_rem_pending()
int signal_rem_pending (thread_t * thread, int signo)
Definition at line 113 of file signal.c.
 {
     if (signo < 0 || signo >= SIGNALS_CNT) {
         return -EINVAL;
     }
     thread->pending_signals_mask &= ~((uint32_t)(1 << signo));
     return 0;
 }
References EINVAL, thread::pending_signals_mask, and SIGNALS_CNT.
Referenced by signal_dispatch_pending().
signal_restore_thread_after_handling_signal()
int signal_restore_thread_after_handling_signal (thread_t * thread)
Definition at line 181 of file signal.c.
 {
     int ret = thread->tf->ebx;
     thread->tf->esp += 12; /* cleaning 3 last pushes */
     uint32_t magic = signal_pop_from_user_stack(thread);
     thread->tf->edi = signal_pop_from_user_stack(thread);
     thread->tf->esi = signal_pop_from_user_stack(thread);
     thread->tf->ebp = signal_pop_from_user_stack(thread);
     uint32_t old_esp = signal_pop_from_user_stack(thread);
     thread->tf->edx = signal_pop_from_user_stack(thread);
     thread->tf->ecx = signal_pop_from_user_stack(thread);
     thread->tf->ebx = signal_pop_from_user_stack(thread);
     thread->tf->eax = signal_pop_from_user_stack(thread);
     thread->tf->eip = signal_pop_from_user_stack(thread);
     thread->tf->eflags = signal_pop_from_user_stack(thread);
     if (magic == MAGIC_STATE_NEW_STACK) {
         uint32_t checksum = signal_pop_from_user_stack(thread);
         context_t* old_ctx = (context_t*)signal_pop_from_user_stack(thread);
         trapframe_t* old_tf = (trapframe_t*)signal_pop_from_user_stack(thread);
         uint32_t calced_checksum = ((uint32_t)old_tf ^ (uint32_t)old_ctx);
         if (checksum != calced_checksum) {
             kprintf("Killed %d: wrong signal checksum\n", thread->process->pid);
             proc_die(thread->process);
             resched_dont_save_context();
         }
         thread->tf = old_tf;
         thread->context = old_ctx;
     }
     if (old_esp != thread->tf->esp) {
         kpanic("ESPs are diff after signal");
     }
     /* If our thread was blocked, that means that it already has a context in stack, we need not ot overwrite it */
     if (thread->blocker.reason != BLOCKER_INVALID) {
         thread->status = THREAD_BLOCKED;
         sched_dequeue(thread);
         resched_dont_save_context();
     }
     /* Since we already have a context in stack, we need not ot overwrite it */
     if (magic == MAGIC_STATE_NEW_STACK) {
         resched_dont_save_context();
     }
     return ret;
 }
References thread::blocker, BLOCKER_INVALID, thread::context, kpanic(), kprintf(), MAGIC_STATE_NEW_STACK, proc::pid, proc_die(), thread::process, blocker::reason, resched_dont_save_context(), sched_dequeue(), signal_pop_from_user_stack(), thread::status, thread::tf, and THREAD_BLOCKED.
Referenced by sys_sigreturn().
signal_set_allow()
int signal_set_allow (thread_t * thread, int signo)
Makes signal allow to be called
Definition at line 83 of file signal.c.
 {
     if (signo < 0 || signo >= SIGNALS_CNT) {
         return -EINVAL;
     }
     thread->signals_mask |= (1 << signo);
     return 0;
 }
References EINVAL, SIGNALS_CNT, and thread::signals_mask.
signal_set_handler()
int signal_set_handler (thread_t * thread, int signo, void * handler)
HELPER FUNCTIONS
Definition at line 71 of file signal.c.
 {
     if (signo < 0 || signo >= SIGNALS_CNT) {
         return -EINVAL;
     }
     thread->signal_handlers[signo] = handler;
     return 0;
 }
References EINVAL, thread::signal_handlers, and SIGNALS_CNT.
Referenced by sys_sigaction().
signal_set_pending()
int signal_set_pending (thread_t * thread, int signo)
Definition at line 104 of file signal.c.
 {
     if (signo < 0 || signo >= SIGNALS_CNT) {
         return -EINVAL;
     }
     thread->pending_signals_mask |= (1 << signo);
     return 0;
 }
References EINVAL, thread::pending_signals_mask, and SIGNALS_CNT.
Referenced by sys_raise(), tasking_kill(), and tty_eat_key().
signal_set_private()
int signal_set_private (thread_t * thread, int signo)
Makes signal private. It can't be called.
Definition at line 95 of file signal.c.
 {
     if (signo < 0 || signo >= SIGNALS_CNT) {
         return -EINVAL;
     }
     thread->signals_mask &= ~((uint32_t)(1 << signo));
     return 0;
 }
References EINVAL, SIGNALS_CNT, and thread::signals_mask.
switchuvm()
void switchuvm (thread_t * p)
CPU FUNCTIONS
Definition at line 8 of file switchvm.c.
 {
     system_disable_interrupts();
     if (RUNNIG_THREAD) {
         fpu_save(RUNNIG_THREAD->fpu_state);
     }
     gdt[SEG_TSS] = SEG_BG(SEGTSS_TYPE, &tss, sizeof(tss) - 1, 0);
     uint32_t esp0 = ((uint32_t)thread->tf + sizeof(trapframe_t));
     tss.esp0 = esp0;
     tss.ss0 = (SEG_KDATA << 3);
     // tss.iomap_offset = 0xffff;
     RUNNIG_THREAD = thread;
     fpu_restore(thread->fpu_state);
     ltr(SEG_TSS << 3);
     vmm_switch_pdir(thread->process->pdir);
     system_enable_interrupts();
 }
tasking_create_kernel_thread()
int tasking_create_kernel_thread (void * entry_point)
Definition at line 118 of file tasking.c.
 {
     proc_t* p = _tasking_alloc_kernel_thread(entry_point);
     p->pdir = vmm_get_kernel_pdir();
     p->main_thread->status = THREAD_RUNNING;
     sched_enqueue(p->main_thread);
     return 0;
 }
References _tasking_alloc_kernel_thread(), p, sched_enqueue(), THREAD_RUNNING, and vmm_get_kernel_pdir().
Referenced by launching(), and stage3().
tasking_exec()
int tasking_exec (const char * path, const char ** argv, const char ** env)
Definition at line 185 of file tasking.c.
 {
     thread_t* thread = RUNNIG_THREAD;
     proc_t* p = RUNNIG_THREAD->process;
     char* kpath = 0;
     int kargc = 0;
     char** kargv = 0;
     char** kenv = 0;
     if (!str_validate_len(path, 128)) {
         return -EINVAL;
     }
     kpath = kmem_bring_to_kernel(path, strlen(path) + 1);
     if (argv) {
         if (!ptrarr_validate_len(argv, 128)) {
             return -EINVAL;
         }
         kargc = ptrarr_len(argv);
         /* Validating arguments size */
         uint32_t data_len = 0;
         for (int argi = 0; argi < kargc; argi++) {
             if (!str_validate_len(argv[argi], 128)) {
                 return -EINVAL;
             }
             data_len += strlen(argv[argi]) + 1;
             if (data_len > 128) {
                 return -EINVAL;
             }
         }
         kargv = kmem_bring_to_kernel_ptrarr(argv, kargc);
     }
     /* Cleaning proc */
     dynamic_array_clear(&p->zones);
     proc_kill_all_threads_except(p, thread);
     p->main_thread = thread;
     p->pid = thread->tid;
     fpu_reset_state(p->main_thread->fpu_state);
     int ret = _tasking_do_exec(p, kpath, kargc, kargv, 0);
 #ifdef TASKING_DEBUG
     if (!ret) {
         log("Exec %s : pid %d", kpath, p->pid);
     }
 #endif
     kfree(kpath);
     for (int argi = 0; argi < kargc; argi++) {
         kfree(kargv[argi]);
     }
     kfree(kargv);
     return ret;
 }
References _tasking_do_exec(), dynamic_array_clear(), EINVAL, fpu_reset_state(), kfree(), kmem_bring_to_kernel(), kmem_bring_to_kernel_ptrarr(), log(), p, proc_kill_all_threads_except(), ptrarr_len(), ptrarr_validate_len(), RUNNIG_THREAD, str_validate_len(), strlen(), and thread::tid.
Referenced by sys_exec().
tasking_exit()
void tasking_exit (int exit_code)
Definition at line 256 of file tasking.c.
 {
     proc_t* p = RUNNIG_THREAD->process;
     p->main_thread->exit_code = exit_code;
     proc_die(p);
     resched();
 }
References p, proc_die(), resched(), and RUNNIG_THREAD.
Referenced by sys_exit().
tasking_fork()
void tasking_fork (trapframe_t * tf)
SYSCALL IMPLEMENTATION
Definition at line 153 of file tasking.c.
 {
     proc_t* new_proc = _tasking_alloc_proc();
     new_proc->pdir = vmm_new_forked_user_pdir();
     /* copying data from proc to new proc */
     proc_copy_of(new_proc, RUNNIG_THREAD);
     /* setting output */
     set_syscall_result(new_proc->main_thread->tf, 0);
     set_syscall_result(RUNNIG_THREAD->tf, new_proc->pid);
     new_proc->main_thread->status = THREAD_RUNNING;
 #ifdef TASKING_DEBUG
     log("Fork %d to pid %d", RUNNIG_THREAD->tid, new_proc->pid);
 #endif
     sched_enqueue(new_proc->main_thread);
     resched();
 }
References _tasking_alloc_proc(), log(), proc::main_thread, proc::pdir, proc::pid, proc_copy_of(), resched(), RUNNIG_THREAD, sched_enqueue(), set_syscall_result(), thread::status, thread::tf, THREAD_RUNNING, and vmm_new_forked_user_pdir().
Referenced by sys_fork().
tasking_get_proc()
proc_t* tasking_get_proc (uint32_t pid)
Definition at line 55 of file tasking.c.
 {
     proc_t* p;
     for (int i = 0; i < nxt_proc; i++) {
         p = &proc[i];
         if (p->pid == pid) {
             return p;
         }
     }
     return 0;
 }
References nxt_proc, and p.
Referenced by sys_getpgid(), sys_setpgid(), and tty_eat_key().
tasking_get_proc_by_pdir()
proc_t* tasking_get_proc_by_pdir (pdirectory_t * pdir)
Definition at line 67 of file tasking.c.
 {
     proc_t* p;
     for (int i = 0; i < nxt_proc; i++) {
         p = &proc[i];
         if (p->status == PROC_DEAD || p->status == PROC_DYING || p->status == PROC_INVALID) {
             continue;
         }
         if (p->pdir == pdir) {
             return p;
         }
     }
     return 0;
 }
References nxt_proc, p, PROC_DEAD, PROC_DYING, and PROC_INVALID.
Referenced by vmm_page_fault_handler().
tasking_init()
void tasking_init ()
TASKING RELATED FUNCTIONS
Definition at line 131 of file tasking.c.
 {
     nxt_proc = 0;
     signal_init();
 }
References nxt_proc, and signal_init().
Referenced by stage3().
tasking_kill()
int tasking_kill (thread_t * thread, int signo)
Definition at line 264 of file tasking.c.
 {
     signal_set_pending(thread, signo);
     signal_dispatch_pending(thread);
     return 0;
 }
References signal_dispatch_pending(), and signal_set_pending().
Referenced by sys_kill().
tasking_kill_dying()
void tasking_kill_dying ()
Definition at line 137 of file tasking.c.
 {
     proc_t* p;
     for (int i = 0; i < nxt_proc; i++) {
         p = &proc[i];
         if (p->status == PROC_DYING) {
             proc_free(p);
             p->status = PROC_DEAD;
         }
     }
 }
References nxt_proc, p, PROC_DEAD, PROC_DYING, and proc_free().
Referenced by sched().
tasking_start_init_proc()
void tasking_start_init_proc ()
TASK LOADING FUNCTIONS
Start init proccess All others processes will fork
Definition at line 102 of file tasking.c.
 {
     proc_t* p = _tasking_alloc_proc();
     proc_setup_tty(p, tty_new());
     /* creating new pdir */
     p->pdir = vmm_new_user_pdir();
     if (proc_load(p, "/boot/init") < 0) {
         log_error("Failed to load init proc");
         while (1) { }
     }
     sched_enqueue(p->main_thread);
 }
References _tasking_alloc_proc(), log_error(), p, proc_load(), proc_setup_tty(), sched_enqueue(), tty_new(), and vmm_new_user_pdir().
Referenced by launching(), and umode().
tasking_waitpid()
int tasking_waitpid (int pid)
Definition at line 244 of file tasking.c.
 {
     thread_t* thread = RUNNIG_THREAD;
     thread_t* joinee_thread = tasking_get_thread(pid);
     if (!joinee_thread) {
         return -ESRCH;
     }
     thread->joinee = joinee_thread;
     init_join_blocker(thread);
     return 0;
 }
References ESRCH, init_join_blocker(), thread::joinee, RUNNIG_THREAD, and tasking_get_thread().
Referenced by sys_waitpid(), and umode().
Variable Documentation
cpus
cpu_t cpus[1] extern
Definition at line 25 of file tasking.c.
Referenced by scheduler_init().
ended_proc
uint32_t ended_proc extern
nxt_proc
uint32_t nxt_proc extern
Definition at line 27 of file tasking.c.
Referenced by _tasking_alloc_kernel_thread(), _tasking_alloc_proc(), tasking_get_proc(), tasking_get_proc_by_pdir(), tasking_init(), and tasking_kill_dying().
proc
proc_t proc[1024] extern
Definition at line 26 of file tasking.c.