oneOS: libs/libc/termios.c File Reference
termios.c File Reference
#include <termios.h>
#include <syscalls.h>
Functions
int tcgetpgrp (int fd)
int tcsetpgrp (int fd, pid_t pgid)
int tcgetattr (int fd, termios_t *termios_p)
int tcsetattr (int fd, int optional_actions, const termios_t *termios_p)
Function Documentation
tcgetattr()
int tcgetattr (int fd, termios_t * termios_p)
Definition at line 14 of file termios.c.
 {
     ioctl(0, TCGETS, (int)termios_p);
 }
References ioctl(), and TCGETS.
Referenced by enable_raw_mode().
tcgetpgrp()
int tcgetpgrp (int fd)
Definition at line 4 of file termios.c.
 {
     return ioctl(fd, TIOCGPGRP, 0);
 }
References ioctl(), and TIOCGPGRP.
tcsetattr()
int tcsetattr (int fd, int optional_actions, const termios_t * termios_p)
Definition at line 19 of file termios.c.
 {
     if (optional_actions == TCSANOW) {
         return ioctl(0, TCSETS, (int)termios_p);
     }
     if (optional_actions == TCSADRAIN) {
         return ioctl(0, TCSETSW, (int)termios_p);
     }
     if (optional_actions == TCSAFLUSH) {
         return ioctl(0, TCSETSF, (int)termios_p);
     }
     return -1;
 }
References ioctl(), TCSADRAIN, TCSAFLUSH, TCSANOW, TCSETS, TCSETSF, and TCSETSW.
Referenced by enable_raw_mode(), and restore_termios().
tcsetpgrp()
int tcsetpgrp (int fd, pid_t pgid)
Definition at line 9 of file termios.c.
 {
     return ioctl(fd, TIOCSPGRP, pgid);
 }
References ioctl(), and TIOCSPGRP.