oneOS: userland/test/main.c File Reference
main.c File Reference
#include <syscalls.h>
Functions
int acceptsig (int signo)
int main ()
Function Documentation
acceptsig()
int acceptsig (int signo)
Definition at line 3 of file main.c.
 {
     write(1, "oneOS\n", 6);
     return 2;
 }
References write().
Referenced by main().
main()
int main ()
Definition at line 9 of file main.c.
 {
     sigaction(3, acceptsig);
     raise(3);
     char buf[256];
     char* arg[] = {
         "b",
         "a",
         "e",
     };
     arg[2] = (char*)0;
     int sock_fd = socket(PF_LOCAL, 0, 0);
     bind(sock_fd, "ke4.sock", 8);
     int res = fork();
     if (res == 0) {
         execve("/bin/echo", arg, 0);
         return -1;
     }
     while (1) {
         read(sock_fd, buf, 4);
         write(1, buf, 4);
     }
     return 0;
 }
References acceptsig(), bind(), buf, execve(), fork(), PF_LOCAL, read(), sigaction(), socket(), and write().