oneOS: include/tasking/thread.h File Reference
thread.h File Reference
#include <drivers/x86/fpu.h>
#include <fs/vfs.h>
#include <tasking/signal.h>
#include <time/time_manager.h>
#include <types.h>
#include <platform/x86/idt.h>
Data Structures
struct __attribute__
struct blocker
struct thread
Typedefs
typedef struct blocker blocker_t
typedef struct thread thread_t
Enumerations
enum THREAD_STATUS {
THREAD_INVALID = 0 , THREAD_RUNNING , THREAD_DEAD , THREAD_STOPPED ,
THREAD_BLOCKED , THREAD_DYING
}
enum BLOCKER_REASON {
BLOCKER_INVALID , BLOCKER_JOIN , BLOCKER_READ , BLOCKER_WRITE ,
BLOCKER_SLEEP , BLOCKER_SELECT
}
Functions
int thread_setup_main (struct proc *p, thread_t *thread)
int thread_setup (struct proc *p, thread_t *thread)
int thread_setup_kstack (thread_t *thread)
void thread_set_stack (thread_t *thread, uint32_t ebp, uint32_t esp)
void thread_set_eip (thread_t *thread, uint32_t eip)
int thread_fill_up_stack (thread_t *thread, int argc, char **argv, char **env)
int thread_free (thread_t *thread)
int thread_die (thread_t *thread)
int init_join_blocker (thread_t *p)
int init_read_blocker (thread_t *p, file_descriptor_t *bfd)
int init_write_blocker (thread_t *thread, file_descriptor_t *bfd)
int init_sleep_blocker (thread_t *thread, uint32_t time)
int init_select_blocker (thread_t *thread, int nfds, fd_set_t *readfds, fd_set_t *writefds, fd_set_t *exceptfds, timeval_t *timeout)
int thread_dump_frame (thread_t *thread)
int thread_print_backtrace ()
Typedef Documentation
blocker_t
typedef struct blocker blocker_t
Definition at line 1 of file thread.h.
thread_t
typedef struct thread thread_t
Definition at line 1 of file thread.h.
Enumeration Type Documentation
BLOCKER_REASON
enum BLOCKER_REASON
Enumerator
BLOCKER_INVALID
BLOCKER_JOIN
BLOCKER_READ
BLOCKER_WRITE
BLOCKER_SLEEP
BLOCKER_SELECT
Definition at line 44 of file thread.h.
                     {
     BLOCKER_INVALID,
     BLOCKER_JOIN,
     BLOCKER_READ,
     BLOCKER_WRITE,
     BLOCKER_SLEEP,
     BLOCKER_SELECT,
 };
THREAD_STATUS
enum THREAD_STATUS
Enumerator
THREAD_INVALID
THREAD_RUNNING
THREAD_DEAD
THREAD_STOPPED
THREAD_BLOCKED
THREAD_DYING
Definition at line 27 of file thread.h.
                    {
     THREAD_INVALID = 0,
     THREAD_RUNNING,
     THREAD_DEAD,
     THREAD_STOPPED,
     THREAD_BLOCKED,
     THREAD_DYING,
 };
Function Documentation
init_join_blocker()
int init_join_blocker (thread_t * p)
BLOCKER FUNCTIONS
Definition at line 23 of file blocker.c.
 {
     thread->status = THREAD_BLOCKED;
     thread->blocker.reason = BLOCKER_JOIN;
     thread->blocker.should_unblock = should_unblock_join_block;
     thread->blocker.should_unblock_for_signal = true;
     sched_dequeue(thread);
     resched();
     return 0;
 }
References thread::blocker, BLOCKER_JOIN, blocker::reason, resched(), sched_dequeue(), blocker::should_unblock, blocker::should_unblock_for_signal, should_unblock_join_block(), thread::status, and THREAD_BLOCKED.
Referenced by tasking_waitpid().
init_read_blocker()
int init_read_blocker (thread_t * p, file_descriptor_t * bfd)
Definition at line 39 of file blocker.c.
 {
     thread->blocker_fd = bfd;
     if (should_unblock_read_block(thread)) {
         return 0;
     }
     thread->status = THREAD_BLOCKED;
     thread->blocker.reason = BLOCKER_READ;
     thread->blocker.should_unblock = should_unblock_read_block;
     thread->blocker.should_unblock_for_signal = true;
     sched_dequeue(thread);
     resched();
     return 0;
 }
References thread::blocker, thread::blocker_fd, BLOCKER_READ, blocker::reason, resched(), sched_dequeue(), blocker::should_unblock, blocker::should_unblock_for_signal, should_unblock_read_block(), thread::status, and THREAD_BLOCKED.
Referenced by sys_read().
init_select_blocker()
int init_select_blocker (thread_t * thread, int nfds, fd_set_t * readfds, fd_set_t * writefds, fd_set_t * exceptfds, timeval_t * timeout)
Definition at line 127 of file blocker.c.
 {
     FD_ZERO(&(thread->readfds));
     FD_ZERO(&(thread->writefds));
     FD_ZERO(&(thread->exceptfds));
     thread->unblock_time = 0;
     if (readfds) {
         thread->readfds = *readfds;
     }
     if (writefds) {
         thread->writefds = *writefds;
     }
     if (exceptfds) {
         thread->exceptfds = *exceptfds;
     }
     if (timeout) {
         thread->unblock_time = timeman_now() + timeout->tv_sec;
     }
     thread->nfds = nfds;
     if (should_unblock_select_block(thread)) {
         return 0;
     }
     thread->status = THREAD_BLOCKED;
     thread->blocker.reason = BLOCKER_SELECT;
     thread->blocker.should_unblock = should_unblock_select_block;
     thread->blocker.should_unblock_for_signal = true;
     sched_dequeue(thread);
     resched();
     return 0;
 }
References thread::blocker, BLOCKER_SELECT, thread::exceptfds, FD_ZERO, thread::nfds, thread::readfds, blocker::reason, resched(), sched_dequeue(), blocker::should_unblock, blocker::should_unblock_for_signal, should_unblock_select_block(), thread::status, THREAD_BLOCKED, timeman_now(), timeval::tv_sec, thread::unblock_time, and thread::writefds.
Referenced by sys_select().
init_sleep_blocker()
int init_sleep_blocker (thread_t * thread, uint32_t time)
Definition at line 83 of file blocker.c.
 {
     thread->unblock_time = timeman_now() + time;
     if (should_unblock_sleep_block(thread)) {
         return 0;
     }
     thread->status = THREAD_BLOCKED;
     thread->blocker.reason = BLOCKER_SLEEP;
     thread->blocker.should_unblock = should_unblock_sleep_block;
     thread->blocker.should_unblock_for_signal = true;
     sched_dequeue(thread);
     resched();
     return 0;
 }
References thread::blocker, BLOCKER_SLEEP, blocker::reason, resched(), sched_dequeue(), blocker::should_unblock, blocker::should_unblock_for_signal, should_unblock_sleep_block(), thread::status, THREAD_BLOCKED, timeman_now(), and thread::unblock_time.
Referenced by sys_sleep().
init_write_blocker()
int init_write_blocker (thread_t * thread, file_descriptor_t * bfd)
Definition at line 61 of file blocker.c.
 {
     thread->blocker_fd = bfd;
     if (should_unblock_write_block(thread)) {
         return 0;
     }
     thread->status = THREAD_BLOCKED;
     thread->blocker.reason = BLOCKER_WRITE;
     thread->blocker.should_unblock = should_unblock_write_block;
     thread->blocker.should_unblock_for_signal = true;
     sched_dequeue(thread);
     resched();
     return 0;
 }
References thread::blocker, thread::blocker_fd, BLOCKER_WRITE, blocker::reason, resched(), sched_dequeue(), blocker::should_unblock, blocker::should_unblock_for_signal, should_unblock_write_block(), thread::status, and THREAD_BLOCKED.
Referenced by sys_write().
thread_die()
int thread_die (thread_t * thread)
Definition at line 200 of file thread.c.
 {
     thread->status = THREAD_DYING;
     sched_dequeue(thread);
     return 0;
 }
References sched_dequeue(), thread::status, and THREAD_DYING.
Referenced by proc_die().
thread_dump_frame()
int thread_dump_frame (thread_t * thread)
DEBUG FUNCTIONS
Definition at line 211 of file thread.c.
 {
     for (uint32_t i = thread->tf->esp; i < thread->tf->ebp; i++) {
         uint8_t byte = *(uint8_t*)i;
         uint32_t b32 = (uint32_t)byte;
         log("%x - %x\n", i, b32);
     }
 }
References log(), and thread::tf.
thread_fill_up_stack()
int thread_fill_up_stack (thread_t * thread, int argc, char ** argv, char ** env)
Definition at line 139 of file thread.c.
 {
     /* TODO: Add env */
     uint32_t argv_data_size = 0;
     for (int i = 0; i < argc; i++) {
         argv_data_size += strlen(argv[i]) + 1;
     }
     if (argv_data_size % 4) {
         argv_data_size += 4 - (argv_data_size % 4);
     }
     uint32_t size_in_stack = argv_data_size + (argc + 1) * sizeof(char*) + sizeof(argc) + sizeof(char*);
     int* tmp_buf = (int*)kmalloc(size_in_stack);
     if (!tmp_buf) {
         return -EAGAIN;
     }
     memset((void*)tmp_buf, 0, size_in_stack);
     char* tmp_buf_ptr = ((char*)tmp_buf) + size_in_stack;
     char* tmp_buf_data_ptr = tmp_buf_ptr - argv_data_size;
     uint32_t* tmp_buf_array_ptr = (uint32_t*)((char*)tmp_buf_data_ptr - (argc + 1) * sizeof(char*));
     int* tmp_buf_argv_ptr = (int*)((char*)tmp_buf_array_ptr - sizeof(char*));
     int* tmp_buf_argc_ptr = (int*)((char*)tmp_buf_argv_ptr - sizeof(int));
     uint32_t data_esp = get_stack_pointer(thread->tf) - argv_data_size;
     uint32_t array_esp = data_esp - (argc + 1) * sizeof(char*);
     uint32_t argv_esp = array_esp - 4;
     uint32_t argc_esp = argv_esp - 4;
     for (int i = argc - 1; i >= 0; i--) {
         uint32_t len = strlen(argv[i]);
         tmp_buf_ptr -= len + 1;
         thread->tf->esp -= len + 1;
         memcpy(tmp_buf_ptr, argv[i], len);
         tmp_buf_ptr[len] = 0;
         tmp_buf_array_ptr[i] = get_stack_pointer(thread->tf);
     }
     tmp_buf_array_ptr[argc] = 0;
     *tmp_buf_argv_ptr = array_esp;
     *tmp_buf_argc_ptr = argc;
     set_stack_pointer(thread->tf, argc_esp);
     vmm_copy_to_pdir(thread->process->pdir, (uint8_t*)tmp_buf, get_stack_pointer(thread->tf), size_in_stack);
     kfree(tmp_buf);
     return 0;
 }
References EAGAIN, get_stack_pointer(), kfree(), kmalloc(), memcpy(), memset(), proc::pdir, thread::process, set_stack_pointer(), strlen(), thread::tf, and vmm_copy_to_pdir().
Referenced by _tasking_do_exec().
thread_free()
int thread_free (thread_t * thread)
Definition at line 192 of file thread.c.
 {
     thread->status = THREAD_DEAD;
     // Don't dequeue here, since thread_die has been already run.
     zoner_free_zone(thread->kstack);
     return 0;
 }
References thread::kstack, thread::status, THREAD_DEAD, and zoner_free_zone().
Referenced by proc_kill_all_threads(), and proc_kill_all_threads_except().
thread_print_backtrace()
int thread_print_backtrace ()
Definition at line 220 of file thread.c.
 {
     int id = 1;
     log("# %d : %x", id++, get_instruction_pointer(RUNNIG_THREAD->tf));
     if (get_instruction_pointer(RUNNIG_THREAD->tf) <= 0xa) { // for now it's ok)
         return 0;
     }
     uint32_t* stack = (uint32_t*)get_stack_pointer(RUNNIG_THREAD->tf);
     for (; (uint32_t)stack > 0 && (uint32_t)stack <= 0xc0000000; stack = (uint32_t*)*stack) {
         log("# %d : %x", id++, stack[1]);
         if (stack[1] <= 0xa) { // for now it's ok)
             break;
         }
     }
     return 0;
 }
References get_instruction_pointer(), get_stack_pointer(), log(), and RUNNIG_THREAD.
Referenced by isr_handler().
thread_set_eip()
void thread_set_eip (thread_t * thread, uint32_t eip)
Definition at line 65 of file thread.c.
 {
     thread->tf->eip = eip;
 }
References thread::tf.
Referenced by _proc_load_bin(), and sys_create_thread().
thread_set_stack()
void thread_set_stack (thread_t * thread, uint32_t ebp, uint32_t esp)
Definition at line 59 of file thread.c.
 {
     thread->tf->ebp = ebp;
     thread->tf->esp = esp;
 }
References thread::tf.
Referenced by _proc_load_bin(), and sys_create_thread().
thread_setup()
int thread_setup (struct proc * p, thread_t * thread)
Definition at line 91 of file thread.c.
 {
     /* allocating kernel stack */
     thread->kstack = zoner_new_zone(VMM_PAGE_SIZE);
     if (!thread->kstack.start) {
         return -ENOMEM;
     }
     thread->process = p;
     thread->tid = proc_alloc_pid();
     /* setting signal handlers to 0 */
     thread->signals_mask = 0xffffffff; /* for now all signals are legal */
     thread->pending_signals_mask = 0;
     memset((void*)thread->signal_handlers, 0, sizeof(thread->signal_handlers));
     _thread_setup_kstack(thread, thread->kstack.start + VMM_PAGE_SIZE);
     _thread_setup_segment_regs(thread);
     return 0;
 }
References _thread_setup_kstack(), _thread_setup_segment_regs(), ENOMEM, thread::kstack, memset(), p, thread::pending_signals_mask, proc_alloc_pid(), thread::process, thread::signal_handlers, thread::signals_mask, __zone::start, thread::tid, VMM_PAGE_SIZE, and zoner_new_zone().
Referenced by proc_create_thread().
thread_setup_kstack()
int thread_setup_kstack (thread_t * thread)
thread_setup_main()
int thread_setup_main (struct proc * p, thread_t * thread)
THREAD FUNCTIONS
Definition at line 70 of file thread.c.
 {
     /* allocating kernel stack */
     thread->kstack = zoner_new_zone(VMM_PAGE_SIZE);
     if (!thread->kstack.start) {
         return -ENOMEM;
     }
     thread->process = p;
     thread->tid = p->pid;
     /* setting signal handlers to 0 */
     thread->signals_mask = 0xffffffff; /* for now all signals are legal */
     thread->pending_signals_mask = 0;
     memset((void*)thread->signal_handlers, 0, sizeof(thread->signal_handlers));
     _thread_setup_kstack(thread, thread->kstack.start + VMM_PAGE_SIZE);
     _thread_setup_segment_regs(thread);
     return 0;
 }
References _thread_setup_kstack(), _thread_setup_segment_regs(), ENOMEM, thread::kstack, memset(), p, thread::pending_signals_mask, thread::process, thread::signal_handlers, thread::signals_mask, __zone::start, thread::tid, VMM_PAGE_SIZE, and zoner_new_zone().
Referenced by proc_setup().