oneOS: include/time/time_manager.h File Reference
time_manager.h File Reference
#include <types.h>
Data Structures
struct timeval
Typedefs
typedef unsigned int time_t
typedef struct timeval timeval_t
Functions
bool timeman_is_leap_year (uint32_t year)
uint32_t timeman_days_in_years_since_epoch (uint32_t year)
uint32_t timeman_days_in_months_since_soy (uint8_t month, uint32_t year)
time_t timeman_to_seconds_since_epoch (uint8_t secs, uint8_t mins, uint8_t hrs, uint8_t day, uint8_t month, uint32_t year)
int timeman_setup ()
void timeman_pit_tick ()
time_t timeman_now ()
time_t timeman_seconds_since_boot ()
time_t timeman_get_ticks_from_last_second ()
Typedef Documentation
time_t
typedef unsigned int time_t
Definition at line 15 of file time_manager.h.
timeval_t
typedef struct timeval timeval_t
Definition at line 15 of file time_manager.h.
Function Documentation
timeman_days_in_months_since_soy()
uint32_t timeman_days_in_months_since_soy (uint8_t month, uint32_t year)
soy - start of the year
Definition at line 49 of file time_manager.c.
 {
     uint32_t days = pref_sum_of_days_in_mounts[month];
     if (timeman_is_leap_year(year) && month >= 2) {
         days++;
     }
     return days;
 }
References pref_sum_of_days_in_mounts, and timeman_is_leap_year().
Referenced by timeman_to_seconds_since_epoch().
timeman_days_in_years_since_epoch()
uint32_t timeman_days_in_years_since_epoch (uint32_t year)
Definition at line 34 of file time_manager.c.
 {
     uint32_t days = 0;
     for (uint32_t y = 1970; y <= year; y++) {
         days += 365;
         if (timeman_is_leap_year(y)) {
             days++;
         }
     }
     return days;
 }
References timeman_is_leap_year().
Referenced by timeman_to_seconds_since_epoch().
timeman_get_ticks_from_last_second()
time_t timeman_get_ticks_from_last_second ()
Definition at line 97 of file time_manager.c.
 {
     return ticks;
 }
References ticks.
Referenced by tty_write().
timeman_is_leap_year()
bool timeman_is_leap_year (uint32_t year)
Definition at line 29 of file time_manager.c.
 {
     return (year % 4 == 0) && (year % 100 != 0) || (year % 400 == 0);
 }
Referenced by timeman_days_in_months_since_soy(), and timeman_days_in_years_since_epoch().
timeman_now()
time_t timeman_now ()
Definition at line 87 of file time_manager.c.
 {
     return time_since_epoch;
 }
References time_since_epoch.
Referenced by ext2_truncate(), ext2_write(), init_select_blocker(), init_sleep_blocker(), should_unblock_select_block(), should_unblock_sleep_block(), and tty_write().
timeman_pit_tick()
void timeman_pit_tick ()
Definition at line 78 of file time_manager.c.
 {
     if (++ticks >= PIT_TICKS_PER_SECOND) {
         time_since_boot++;
         time_since_epoch++;
         ticks = 0;
     }
 }
References PIT_TICKS_PER_SECOND, ticks, time_since_boot, and time_since_epoch.
Referenced by pit_handler().
timeman_seconds_since_boot()
time_t timeman_seconds_since_boot ()
Definition at line 92 of file time_manager.c.
 {
     return time_since_boot;
 }
References time_since_boot.
timeman_setup()
int timeman_setup ()
Definition at line 64 of file time_manager.c.
 {
     uint8_t secs, mins, hrs, day, month;
     uint32_t year;
     rtc_load_time(&secs, &mins, &hrs, &day, &month, &year);
 #ifdef TIME_MANAGER_DEBUG
     log("Loaded date: %ds %dm %dh %dd %dm %dy", (uint32_t)secs, (uint32_t)mins, (uint32_t)hrs, (uint32_t)day, (uint32_t)month, (uint32_t)year);
 #endif
     time_since_epoch = timeman_to_seconds_since_epoch(secs, mins, hrs, day, month, year);
 }
References log(), rtc_load_time(), time_since_epoch, and timeman_to_seconds_since_epoch().
Referenced by stage3().
timeman_to_seconds_since_epoch()
time_t timeman_to_seconds_since_epoch (uint8_t secs, uint8_t mins, uint8_t hrs, uint8_t day, uint8_t month, uint32_t year)
Definition at line 58 of file time_manager.c.
 {
     time_t res = timeman_days_in_years_since_epoch(year - 1) * 86400 + timeman_days_in_months_since_soy(month - 1, year) * 86400 + (day - 1) * 86400 + hrs * 3600 + mins * 60 + secs;
     return res;
 }
References timeman_days_in_months_since_soy(), and timeman_days_in_years_since_epoch().
Referenced by timeman_setup().