oneOS: include/platform/x86/tasking/trapframe.h File Reference
trapframe.h File Reference
#include <types.h>
Data Structures
struct __attribute__
Functions
static uint32_t get_stack_pointer (trapframe_t *tf)
static uint32_t set_stack_pointer (trapframe_t *tf, uint32_t sp)
static uint32_t get_instruction_pointer (trapframe_t *tf)
static uint32_t set_instruction_pointer (trapframe_t *tf, uint32_t ip)
static uint32_t get_syscall_result (trapframe_t *tf)
static uint32_t set_syscall_result (trapframe_t *tf, uint32_t val)
Function Documentation
get_instruction_pointer()
static uint32_t get_instruction_pointer (trapframe_t * tf) inline static
Definition at line 51 of file trapframe.h.
 {
     return tf->eip;
 }
Referenced by thread_print_backtrace().
get_stack_pointer()
static uint32_t get_stack_pointer (trapframe_t * tf) inline static
Definition at line 41 of file trapframe.h.
 {
     return tf->esp;
 }
Referenced by thread_fill_up_stack(), and thread_print_backtrace().
get_syscall_result()
static uint32_t get_syscall_result (trapframe_t * tf) inline static
Definition at line 61 of file trapframe.h.
 {
     return tf->eax;
 }
set_instruction_pointer()
static uint32_t set_instruction_pointer (trapframe_t * tf, uint32_t ip) inline static
Definition at line 56 of file trapframe.h.
 {
     tf->eip = ip;
 }
set_stack_pointer()
static uint32_t set_stack_pointer (trapframe_t * tf, uint32_t sp) inline static
Definition at line 46 of file trapframe.h.
 {
     tf->esp = sp;
 }
Referenced by thread_fill_up_stack().
set_syscall_result()
static uint32_t set_syscall_result (trapframe_t * tf, uint32_t val) inline static
Definition at line 66 of file trapframe.h.
 {
     tf->eax = val;
 }
Referenced by tasking_fork().