oneOS: src/kernel/platform/x86/tasking/tss.c File Reference
tss.c File Reference
#include <platform/x86/tasking/tss.h>
#include <platform/x86/gdt.h>
#include <mem/vmm/vmm.h>
#include <mem/kmalloc.h>
Functions
void ltr (uint16_t seg)
void jump_usermode ()
void switch_to_user_mode ()
void user_mode_function ()
Variables
tss_t tss
char * kernel_stack
Function Documentation
jump_usermode()
void jump_usermode ()
Referenced by switch_to_user_mode().
ltr()
void ltr (uint16_t seg)
Definition at line 8 of file tss.c.
{
     asm volatile("ltr %0" : : "r"(seg));
 }
Referenced by switch_to_user_mode(), and switchuvm().
switch_to_user_mode()
void switch_to_user_mode ()
Definition at line 19 of file tss.c.
{
     kernel_stack = (char*)kmalloc(VMM_PAGE_SIZE);
     gdt[SEG_TSS] = SEG_BG(SEGTSS_TYPE, &tss, sizeof(tss)-1, 0);
     tss.esp0 = (uint32_t)(kernel_stack + VMM_PAGE_SIZE - 1);
     tss.ss0 = (SEG_KDATA << 3);
     // tss.iomap_offset = 0xffff;
     ltr(SEG_TSS << 3);
     jump_usermode();
 }
References gdt, jump_usermode(), kernel_stack, kmalloc(), ltr(), SEG_BG, SEG_KDATA, SEG_TSS, SEGTSS_TYPE, tss, and VMM_PAGE_SIZE.
user_mode_function()
void user_mode_function ()
Definition at line 29 of file tss.c.
{
     while (1) {}
 }
Variable Documentation
kernel_stack
char* kernel_stack
Definition at line 14 of file tss.c.
Referenced by switch_to_user_mode().
tss
tss_t tss
Definition at line 6 of file tss.c.
Referenced by switch_to_user_mode(), and switchuvm().