oneOS: src/kernel/io/tty/tty.c File Reference
tty.c File Reference
#include <drivers/x86/display.h>
#include <drivers/x86/keyboard.h>
#include <drivers/x86/pit.h>
#include <errno.h>
#include <fs/devfs/devfs.h>
#include <fs/vfs.h>
#include <io/tty/tty.h>
#include <log.h>
#include <mem/kmalloc.h>
#include <syscall_structs.h>
#include <tasking/signal.h>
#include <tasking/tasking.h>
#include <utils.h>
Functions
static tty_entry_t * _tty_get (dentry_t *dentry)
static void _tty_flush_input (tty_entry_t *tty)
static tty_entry_t * _tty_active ()
bool tty_can_read (dentry_t *dentry, uint32_t start)
bool tty_can_write (dentry_t *dentry, uint32_t start)
int tty_read (dentry_t *dentry, uint8_t *buf, uint32_t start, uint32_t len)
int _tty_process_esc_seq (uint8_t *buf)
int tty_write (dentry_t *dentry, uint8_t *buf, uint32_t start, uint32_t len)
int tty_ioctl (dentry_t *dentry, uint32_t cmd, uint32_t arg)
static void _tty_setup_termios (tty_entry_t *tty)
tty_entry_t * tty_new ()
static void _tty_echo_key (tty_entry_t *tty, key_t key)
void tty_eat_key (key_t key)
Variables
static int next_tty = 0
static tty_entry_t * active_tty = 0
tty_entry_t ttys [TTY_MAX_COUNT]
Function Documentation
_tty_active()
static tty_entry_t* _tty_active () inline static
Definition at line 37 of file tty.c.
 {
     return active_tty;
 }
References active_tty.
Referenced by tty_eat_key().
_tty_echo_key()
static void _tty_echo_key (tty_entry_t * tty, key_t key) static
Definition at line 202 of file tty.c.
 {
     if (tty->termios.c_lflag & ECHO) {
         print_char(key, WHITE_ON_BLACK, -1, -1);
     }
 }
References termios::c_lflag, ECHO, print_char(), tty_entry::termios, and WHITE_ON_BLACK.
Referenced by tty_eat_key().
_tty_flush_input()
static void _tty_flush_input (tty_entry_t * tty) inline static
Definition at line 31 of file tty.c.
 {
     tty->lines_avail = 0;
     ringbuffer_clear(&tty->buffer);
 }
References tty_entry::buffer, tty_entry::lines_avail, and ringbuffer_clear().
Referenced by tty_ioctl().
_tty_get()
static tty_entry_t* _tty_get (dentry_t * dentry) static
Definition at line 21 of file tty.c.
 {
     for (int i = 0; i < TTY_MAX_COUNT; i++) {
         if (dentry->inode_indx == ttys[i].inode_indx) {
             return &ttys[i];
         }
     }
     return 0;
 }
References dentry::inode_indx, tty_entry::inode_indx, TTY_MAX_COUNT, and ttys.
Referenced by tty_can_read(), tty_ioctl(), and tty_read().
_tty_process_esc_seq()
int _tty_process_esc_seq (uint8_t * buf)
Definition at line 70 of file tty.c.
 {
     if (buf[0] != '\x1b') {
         return 0;
     }
     int argv[4] = { 0, 0, 0, 0 };
     int id = 1;
     int argc = 0;
     if (buf[id] == '[') {
         id++;
         for (;;) {
             int len = 0;
             while ('0' <= buf[id + len] && buf[id + len] <= '9') {
                 len++;
             }
             argv[argc++] = stoi(&buf[id], len);
             id += len;
             if (buf[id] != ';') {
                 break;
             }
             id++;
         }
     }
     char cmd = buf[id];
     id++;
     switch (cmd) {
     case 'J':
         if (argv[0] == 2) {
             clean_screen();
         }
         return id;
     case 'H':
         if (argc == 0) {
             set_cursor_offset(get_offset(0, 0));
         }
         if (argc == 2) {
             set_cursor_offset(get_offset(argv[1] - 1, argv[0] - 1));
         }
         return id;
     }
 }
References buf, clean_screen(), cmd, get_offset(), set_cursor_offset(), and stoi().
Referenced by tty_write().
_tty_setup_termios()
static void _tty_setup_termios (tty_entry_t * tty) static
Definition at line 164 of file tty.c.
 {
     tty->termios.c_lflag |= ECHO | ICANON;
 }
References termios::c_lflag, ECHO, ICANON, and tty_entry::termios.
Referenced by tty_new().
tty_can_read()
bool tty_can_read (dentry_t * dentry, uint32_t start)
Definition at line 42 of file tty.c.
 {
     tty_entry_t* tty = _tty_get(dentry);
     if (tty->termios.c_lflag & ICANON) {
         return tty->lines_avail > 0;
     }
     return ringbuffer_space_to_read(&tty->buffer) >= 1;
 }
References _tty_get(), tty_entry::buffer, termios::c_lflag, ICANON, tty_entry::lines_avail, ringbuffer_space_to_read(), and tty_entry::termios.
Referenced by tty_new().
tty_can_write()
bool tty_can_write (dentry_t * dentry, uint32_t start)
Definition at line 51 of file tty.c.
 {
     return true;
 }
Referenced by tty_new().
tty_eat_key()
void tty_eat_key (key_t key)
Definition at line 209 of file tty.c.
 {
     tty_entry_t* tty = _tty_active();
     if (key == KEY_CTRLC) {
         proc_t* p = tasking_get_proc(tty->pgid);
         if (p) {
             signal_set_pending(p->main_thread, SIGINT);
             signal_dispatch_pending(p->main_thread);
         }
         return;
     }
     if (key == KEY_RETURN) {
         _tty_echo_key(tty, '\n');
         ringbuffer_write_one(&tty->buffer, '\n');
         tty->lines_avail++;
     } else if (key == KEY_BACKSPACE) {
         if (ringbuffer_space_to_read(&tty->buffer) > 0) {
             delete_char(WHITE_ON_BLACK, -1, -1, 1);
             tty->buffer.end--;
         }
     } else {
         ringbuffer_write_one(&tty->buffer, (char)key);
         _tty_echo_key(tty, key);
     }
 }
References _tty_active(), _tty_echo_key(), tty_entry::buffer, delete_char(), __ringbuffer::end, KEY_BACKSPACE, KEY_CTRLC, KEY_RETURN, tty_entry::lines_avail, p, tty_entry::pgid, ringbuffer_space_to_read(), ringbuffer_write_one(), SIGINT, signal_dispatch_pending(), signal_set_pending(), tasking_get_proc(), and WHITE_ON_BLACK.
tty_ioctl()
int tty_ioctl (dentry_t * dentry, uint32_t cmd, uint32_t arg)
Definition at line 138 of file tty.c.
 {
     tty_entry_t* tty = _tty_get(dentry);
     switch (cmd) {
     case TIOCGPGRP:
         return tty->pgid;
     case TIOCSPGRP:
         tty->pgid = arg;
         return 0;
     case TCGETS:
         memcpy((void*)arg, (void*)&tty->termios, sizeof(termios_t));
         return 0;
     case TCSETS:
     case TCSETSW:
     case TCSETSF:
         memcpy((void*)&tty->termios, (void*)arg, sizeof(termios_t));
         if (cmd == TCSETSF) {
             _tty_flush_input(tty);
         }
         return 0;
     }
     return -EINVAL;
 }
References _tty_flush_input(), _tty_get(), cmd, EINVAL, memcpy(), tty_entry::pgid, TCGETS, TCSETS, TCSETSF, TCSETSW, tty_entry::termios, TIOCGPGRP, and TIOCSPGRP.
Referenced by tty_new().
tty_new()
tty_entry_t* tty_new ()
Definition at line 169 of file tty.c.
 {
     dentry_t* mp;
     if (vfs_resolve_path("/dev", &mp) < 0) {
         return 0;
     }
     char* name = "tty ";
     name[3] = next_tty + '0';
     file_ops_t fops;
     fops.open = 0;
     fops.can_read = tty_can_read;
     fops.can_write = tty_can_write;
     fops.read = tty_read;
     fops.write = tty_write;
     fops.ioctl = tty_ioctl;
     devfs_inode_t* res = devfs_register(mp, name, 4, 0, &fops);
     ttys[next_tty].id = next_tty;
     ttys[next_tty].inode_indx = res->index;
     ttys[next_tty].buffer = ringbuffer_create_std();
     ttys[next_tty].lines_avail = 0;
     _tty_setup_termios(&ttys[next_tty]);
     if (!ttys[next_tty].buffer.zone.start) {
         kprintf("Error: tty buffer allocation");
         while (1) { }
     }
     active_tty = &ttys[next_tty];
     next_tty++;
     dentry_put(mp);
     return &ttys[next_tty - 1];
 }
References _tty_setup_termios(), active_tty, tty_entry::buffer, file_ops::can_read, file_ops::can_write, dentry_put(), devfs_register(), tty_entry::id, devfs_inode::index, tty_entry::inode_indx, file_ops::ioctl, kprintf(), tty_entry::lines_avail, copy_bin::name, next_tty, file_ops::open, file_ops::read, ringbuffer_create_std(), tty_can_read(), tty_can_write(), tty_ioctl(), tty_read(), tty_write(), ttys, vfs_resolve_path(), and file_ops::write.
Referenced by tasking_start_init_proc().
tty_read()
int tty_read (dentry_t * dentry, uint8_t * buf, uint32_t start, uint32_t len)
Definition at line 56 of file tty.c.
 {
     tty_entry_t* tty = _tty_get(dentry);
     uint32_t leno = ringbuffer_space_to_read(&tty->buffer);
     if (leno > len) {
         leno = len;
     }
     int res = ringbuffer_read(&tty->buffer, buf, leno);
     if (tty->termios.c_lflag & ICANON && res == leno) {
         tty->lines_avail--;
     }
     return leno;
 }
References _tty_get(), buf, tty_entry::buffer, termios::c_lflag, ICANON, tty_entry::lines_avail, ringbuffer_read(), ringbuffer_space_to_read(), and tty_entry::termios.
Referenced by tty_new().
tty_write()
int tty_write (dentry_t * dentry, uint8_t * buf, uint32_t start, uint32_t len)
Definition at line 114 of file tty.c.
 {
 #ifdef TTY_DEBUG_TIME
     time_t cur_time = timeman_now();
     int secs = cur_time % 60;
     cur_time /= 60;
     int mins = cur_time % 60;
     cur_time /= 60;
     int hrs = cur_time % 24;
     time_t ticks = timeman_get_ticks_from_last_second();
     log_not_formatted("[%d:%d:%d.%d] ", hrs, mins, secs, ticks);
 #endif
     for (int i = 0; i < len; i++) {
         if (buf[i] == '\x1b') {
             i += _tty_process_esc_seq(&buf[i]);
         } else {
             log_char(buf[i]);
             print_char(buf[i], WHITE_ON_BLACK, -1, -1);
         }
     }
     return len;
 }
References _tty_process_esc_seq(), buf, log_char(), log_not_formatted(), print_char(), ticks, timeman_get_ticks_from_last_second(), timeman_now(), and WHITE_ON_BLACK.
Referenced by tty_new().
Variable Documentation
active_tty
tty_entry_t* active_tty = 0 static
Definition at line 18 of file tty.c.
Referenced by _tty_active(), and tty_new().
next_tty
int next_tty = 0 static
Definition at line 17 of file tty.c.
Referenced by tty_new().
ttys
tty_entry_t ttys[TTY_MAX_COUNT]
Definition at line 19 of file tty.c.
Referenced by _tty_get(), and tty_new().