oneOS: include/io/tty/tty.h File Reference
tty.h File Reference
#include <algo/ringbuffer.h>
#include <drivers/x86/keyboard.h>
#include <types.h>
Data Structures
struct termios
struct tty_entry
Macros
#define TTY_MAX_COUNT 8
#define TTY_BUFFER_SIZE 1024
#define NCCS 32
#define VINTR 0
#define VQUIT 1
#define VERASE 2
#define VKILL 3
#define VEOF 4
#define VTIME 5
#define VMIN 6
#define VSWTC 7
#define VSTART 8
#define VSTOP 9
#define VSUSP 10
#define VEOL 11
#define VREPRINT 12
#define VDISCARD 13
#define VWERASE 14
#define VLNEXT 15
#define VEOL2 16
#define ISIG 0000001
#define ICANON 0000002
#define ECHO 0000010
#define ECHOE 0000020
#define ECHOK 0000040
#define ECHONL 0000100
#define NOFLSH 0000200
#define TOSTOP 0000400
#define IEXTEN 0100000
#define TCOOFF 0
#define TCOON 1
#define TCIOFF 2
#define TCION 3
#define TCIFLUSH 0
#define TCOFLUSH 1
#define TCIOFLUSH 2
#define TCSANOW 0
#define TCSADRAIN 1
#define TCSAFLUSH 2
Typedefs
typedef unsigned char cc_t
typedef unsigned int speed_t
typedef unsigned int tcflag_t
typedef struct termios termios_t
typedef struct tty_entry tty_entry_t
Functions
tty_entry_t * tty_new ()
void tty_eat_key (key_t key)
Variables
tty_entry_t ttys [8]
Macro Definition Documentation
ECHO
#define ECHO 0000010
Definition at line 47 of file tty.h.
ECHOE
#define ECHOE 0000020
Definition at line 48 of file tty.h.
ECHOK
#define ECHOK 0000040
Definition at line 49 of file tty.h.
ECHONL
#define ECHONL 0000100
Definition at line 50 of file tty.h.
ICANON
#define ICANON 0000002
Definition at line 46 of file tty.h.
IEXTEN
#define IEXTEN 0100000
Definition at line 53 of file tty.h.
ISIG
#define ISIG 0000001
Definition at line 45 of file tty.h.
NCCS
#define NCCS 32
Definition at line 15 of file tty.h.
NOFLSH
#define NOFLSH 0000200
Definition at line 51 of file tty.h.
TCIFLUSH
#define TCIFLUSH 0
Definition at line 62 of file tty.h.
TCIOFF
#define TCIOFF 2
Definition at line 58 of file tty.h.
TCIOFLUSH
#define TCIOFLUSH 2
Definition at line 64 of file tty.h.
TCION
#define TCION 3
Definition at line 59 of file tty.h.
TCOFLUSH
#define TCOFLUSH 1
Definition at line 63 of file tty.h.
TCOOFF
#define TCOOFF 0
Definition at line 56 of file tty.h.
TCOON
#define TCOON 1
Definition at line 57 of file tty.h.
TCSADRAIN
#define TCSADRAIN 1
Definition at line 68 of file tty.h.
TCSAFLUSH
#define TCSAFLUSH 2
Definition at line 69 of file tty.h.
TCSANOW
#define TCSANOW 0
Definition at line 67 of file tty.h.
TOSTOP
#define TOSTOP 0000400
Definition at line 52 of file tty.h.
TTY_BUFFER_SIZE
#define TTY_BUFFER_SIZE 1024
Definition at line 9 of file tty.h.
TTY_MAX_COUNT
#define TTY_MAX_COUNT 8
Definition at line 8 of file tty.h.
VDISCARD
#define VDISCARD 13
Definition at line 39 of file tty.h.
VEOF
#define VEOF 4
Definition at line 30 of file tty.h.
VEOL
#define VEOL 11
Definition at line 37 of file tty.h.
VEOL2
#define VEOL2 16
Definition at line 42 of file tty.h.
VERASE
#define VERASE 2
Definition at line 28 of file tty.h.
VINTR
#define VINTR 0
Definition at line 26 of file tty.h.
VKILL
#define VKILL 3
Definition at line 29 of file tty.h.
VLNEXT
#define VLNEXT 15
Definition at line 41 of file tty.h.
VMIN
#define VMIN 6
Definition at line 32 of file tty.h.
VQUIT
#define VQUIT 1
Definition at line 27 of file tty.h.
VREPRINT
#define VREPRINT 12
Definition at line 38 of file tty.h.
VSTART
#define VSTART 8
Definition at line 34 of file tty.h.
VSTOP
#define VSTOP 9
Definition at line 35 of file tty.h.
VSUSP
#define VSUSP 10
Definition at line 36 of file tty.h.
VSWTC
#define VSWTC 7
Definition at line 33 of file tty.h.
VTIME
#define VTIME 5
Definition at line 31 of file tty.h.
VWERASE
#define VWERASE 14
Definition at line 40 of file tty.h.
Typedef Documentation
cc_t
typedef unsigned char cc_t
Definition at line 11 of file tty.h.
speed_t
typedef unsigned int speed_t
Definition at line 12 of file tty.h.
tcflag_t
typedef unsigned int tcflag_t
Definition at line 13 of file tty.h.
termios_t
typedef struct termios termios_t
Definition at line 13 of file tty.h.
tty_entry_t
typedef struct tty_entry tty_entry_t
Definition at line 13 of file tty.h.
Function Documentation
tty_eat_key()
void tty_eat_key (key_t key)
Definition at line 209 of file tty.c.
 {
     tty_entry_t* tty = _tty_active();
     if (key == KEY_CTRLC) {
         proc_t* p = tasking_get_proc(tty->pgid);
         if (p) {
             signal_set_pending(p->main_thread, SIGINT);
             signal_dispatch_pending(p->main_thread);
         }
         return;
     }
     if (key == KEY_RETURN) {
         _tty_echo_key(tty, '\n');
         ringbuffer_write_one(&tty->buffer, '\n');
         tty->lines_avail++;
     } else if (key == KEY_BACKSPACE) {
         if (ringbuffer_space_to_read(&tty->buffer) > 0) {
             delete_char(WHITE_ON_BLACK, -1, -1, 1);
             tty->buffer.end--;
         }
     } else {
         ringbuffer_write_one(&tty->buffer, (char)key);
         _tty_echo_key(tty, key);
     }
 }
References _tty_active(), _tty_echo_key(), tty_entry::buffer, delete_char(), __ringbuffer::end, KEY_BACKSPACE, KEY_CTRLC, KEY_RETURN, tty_entry::lines_avail, p, tty_entry::pgid, ringbuffer_space_to_read(), ringbuffer_write_one(), SIGINT, signal_dispatch_pending(), signal_set_pending(), tasking_get_proc(), and WHITE_ON_BLACK.
tty_new()
tty_entry_t* tty_new ()
Definition at line 169 of file tty.c.
 {
     dentry_t* mp;
     if (vfs_resolve_path("/dev", &mp) < 0) {
         return 0;
     }
     char* name = "tty ";
     name[3] = next_tty + '0';
     file_ops_t fops;
     fops.open = 0;
     fops.can_read = tty_can_read;
     fops.can_write = tty_can_write;
     fops.read = tty_read;
     fops.write = tty_write;
     fops.ioctl = tty_ioctl;
     devfs_inode_t* res = devfs_register(mp, name, 4, 0, &fops);
     ttys[next_tty].id = next_tty;
     ttys[next_tty].inode_indx = res->index;
     ttys[next_tty].buffer = ringbuffer_create_std();
     ttys[next_tty].lines_avail = 0;
     _tty_setup_termios(&ttys[next_tty]);
     if (!ttys[next_tty].buffer.zone.start) {
         kprintf("Error: tty buffer allocation");
         while (1) { }
     }
     active_tty = &ttys[next_tty];
     next_tty++;
     dentry_put(mp);
     return &ttys[next_tty - 1];
 }
References _tty_setup_termios(), active_tty, tty_entry::buffer, file_ops::can_read, file_ops::can_write, dentry_put(), devfs_register(), tty_entry::id, devfs_inode::index, tty_entry::inode_indx, file_ops::ioctl, kprintf(), tty_entry::lines_avail, copy_bin::name, next_tty, file_ops::open, file_ops::read, ringbuffer_create_std(), tty_can_read(), tty_can_write(), tty_ioctl(), tty_read(), tty_write(), ttys, vfs_resolve_path(), and file_ops::write.
Referenced by tasking_start_init_proc().
Variable Documentation
ttys
tty_entry_t ttys[8] extern
Definition at line 19 of file tty.c.
Referenced by _tty_get(), and tty_new().