oneOS: src/kernel/drivers/x86/uart.c File Reference
uart.c File Reference
#include <drivers/x86/uart.h>
#include <platform/x86/port.h>
Functions
static int _uart_setup_impl (int port)
void uart_setup ()
static bool _uart_is_free_in (int port)
static bool _uart_is_free_out (int port)
int uart_write (int port, uint8_t data)
int uart_read (int port, uint8_t *data)
Function Documentation
_uart_is_free_in()
static bool _uart_is_free_in (int port) static
Definition at line 29 of file uart.c.
{
    return port_byte_in(port + 5) & 0x01;
 }
References port_byte_in().
_uart_is_free_out()
static bool _uart_is_free_out (int port) static
Definition at line 33 of file uart.c.
{
    return port_byte_in(port + 5) & 0x20;
 }
References port_byte_in().
Referenced by uart_read(), and uart_write().
_uart_setup_impl()
static int _uart_setup_impl (int port) static
Definition at line 12 of file uart.c.
 {
     port_byte_out(port + 1, 0x00);
     port_byte_out(port + 3, 0x80);
     port_byte_out(port + 0, 0x03);
     port_byte_out(port + 1, 0x00);
     port_byte_out(port + 3, 0x03);
     port_byte_out(port + 2, 0xC7);
     port_byte_out(port + 4, 0x0B);
     return 0;
 }
References port_byte_out().
Referenced by uart_setup().
uart_read()
int uart_read (int port, uint8_t * data)
Definition at line 45 of file uart.c.
 {
     while (!_uart_is_free_out(port));
     *data = port_byte_in(port);
     return 0;
 }
References _uart_is_free_out(), and port_byte_in().
uart_setup()
void uart_setup ()
Definition at line 24 of file uart.c.
 {
     _uart_setup_impl(COM1);
 }
References _uart_setup_impl(), and COM1.
Referenced by logger_setup().
uart_write()
int uart_write (int port, uint8_t data)
Definition at line 38 of file uart.c.
 {
     while (!_uart_is_free_out(port));
     port_byte_out(port, data);
     return 0;
 }
References _uart_is_free_out(), and port_byte_out().
Referenced by _log_dec(), _log_hex(), _log_string(), log(), log_char(), log_error(), log_not_formatted(), and log_warn().