oneOS: include/drivers/x86/uart.h File Reference
uart.h File Reference
#include <types.h>
Macros
#define COM1 0x3F8
#define COM2 0x2F8
#define COM3 0x3E8
#define COM4 0x2E8
Functions
void uart_setup ()
int uart_write (int port, uint8_t data)
int uart_read (int port, uint8_t *data)
Macro Definition Documentation
COM1
#define COM1 0x3F8
Definition at line 14 of file uart.h.
COM2
#define COM2 0x2F8
Definition at line 15 of file uart.h.
COM3
#define COM3 0x3E8
Definition at line 16 of file uart.h.
COM4
#define COM4 0x2E8
Definition at line 17 of file uart.h.
Function Documentation
uart_read()
int uart_read (int port, uint8_t * data)
Definition at line 45 of file uart.c.
 {
     while (!_uart_is_free_out(port));
     *data = port_byte_in(port);
     return 0;
 }
References _uart_is_free_out(), and port_byte_in().
uart_setup()
void uart_setup ()
Definition at line 24 of file uart.c.
 {
     _uart_setup_impl(COM1);
 }
References _uart_setup_impl(), and COM1.
Referenced by logger_setup().
uart_write()
int uart_write (int port, uint8_t data)
Definition at line 38 of file uart.c.
 {
     while (!_uart_is_free_out(port));
     port_byte_out(port, data);
     return 0;
 }
References _uart_is_free_out(), and port_byte_out().
Referenced by _log_dec(), _log_hex(), _log_string(), log(), log_char(), log_error(), log_not_formatted(), and log_warn().