oneOS: include/utils.h File Reference
utils.h File Reference
#include <types.h>
Functions
int stoi (char *str, int len)
void htos (uint32_t hex, char str[])
void dtos (uint32_t dec, char str[])
void reverse (char s[])
uint32_t strlen (const char *s)
int strcmp (const char *a, const char *b)
int strncmp (const char *a, const char *b, uint32_t num)
bool str_validate_len (const char *c, uint32_t len)
uint32_t ptrarr_len (const char **s)
bool ptrarr_validate_len (const char **s, uint32_t len)
Function Documentation
dtos()
void dtos (uint32_t dec, char str[])
Definition at line 39 of file utils.c.
 {
     int i = 0;
     if (dec == 0) {
         str[0] = '0';
         i = 1;
     }
     while (dec != 0) {
         int num = dec % 10;
         dec /= 10;
         str[i++] = num + '0';
     }
     str[i] = '\0';
     reverse(str);
 }
References reverse(), and __main__::str.
htos()
void htos (uint32_t hex, char str[])
Definition at line 19 of file utils.c.
 {
     int i = 0;
     if (hex == 0) {
         str[0] = '0';
         i = 1;
     }
     while (hex != 0) {
         int num = hex % 16;
         hex /= 16;
         if (num < 10) {
             str[i++] = num + '0';
         } else {
             str[i++] = num + 'a' - 10;
         }
     }
     str[i] = '\0';
     reverse(str);
 }
References reverse(), and __main__::str.
ptrarr_len()
uint32_t ptrarr_len (const char ** s)
Ptr array utils
Definition at line 122 of file utils.c.
 {
     uint32_t len = 0;
     while (s[len] != 0) {
         ++len;
     }
     return len;
 }
Referenced by tasking_exec().
ptrarr_validate_len()
bool ptrarr_validate_len (const char ** s, uint32_t len)
Definition at line 131 of file utils.c.
 {
     for (int i = 0; i < len + 1; i++) {
         if (s[i] == 0) {
             return true;
         }
     }
     return false;
 }
Referenced by tasking_exec().
reverse()
void reverse (char s[])
Definition at line 55 of file utils.c.
 {
     int c, i, j;
     for (i = 0, j = strlen(s) - 1; i < j; i++, j--) {
         c = s[i];
         s[i] = s[j];
         s[j] = c;
     }
 }
References strlen().
Referenced by dtos(), and htos().
stoi()
int stoi (char * str, int len)
Definition at line 3 of file utils.c.
 {
     if (len > 9) {
         return 0;
     }
     int res = 0;
     int mult = 1;
     char *end = str + len - 1;
     while (end >= str) {
         res += (*end - '0') * mult;
         mult *= 10;
         end--;
     }
     return res;
 }
References __main__::str.
Referenced by _tty_process_esc_seq().
str_validate_len()
bool str_validate_len (const char * c, uint32_t len)
Definition at line 108 of file utils.c.
 {
     for (int i = 0; i < len + 1; i++) {
         if (s[i] == 0) {
             return true;
         }
     }
     return false;
 }
Referenced by proc_chdir(), sys_creat(), sys_mkdir(), sys_open(), sys_rmdir(), sys_unlink(), and tasking_exec().
strcmp()
int strcmp (const char * a, const char * b)
Definition at line 73 of file utils.c.
 {
     while (*a == *b && *a != 0 && *b != 0) {
         a++;
         b++;
     }
     if (a < b) {
         return -1;
     } else if (a > b) {
         return 1;
     }
     return 0;
 }
strlen()
uint32_t strlen (const char * s)
Definition at line 53 of file string.c.
 {
     uint32_t i = 0;
     while (s[i] != '\0')
         ++i;
     return i;
 }
Referenced by _cmd_processor(), _syscmd_mkdir(), devfs_getdents(), devfs_lookup(), kmem_bring_to_kernel_ptrarr(), proc_chdir(), Algo::String::String(), sys_creat(), sys_mkdir(), sys_open(), sys_rmdir(), sys_unlink(), tasking_exec(), thread_fill_up_stack(), touch(), and write().
strncmp()
int strncmp (const char * a, const char * b, uint32_t num)
Definition at line 89 of file utils.c.
 {
     while (*a == *b && *a != 0 && *b != 0 && num) {
         a++;
         b++;
         num--;
     }
     if (!num) {
         return 0;
     } else if (a < b) {
         return -1;
     } else if (a > b) {
         return 1;
     }
     return 0;
 }
Referenced by devfs_lookup().