oneOS: src/kernel/fs/vfs.c File Reference
vfs.c File Reference
#include <algo/dynamic_array.h>
#include <errno.h>
#include <fs/vfs.h>
#include <io/sockets/socket.h>
#include <log.h>
#include <mem/kmalloc.h>
#include <syscall_structs.h>
#include <tasking/tasking.h>
#include <utils/mem.h>
Functions
driver_desc_t _vfs_driver_info ()
void vfs_install ()
int vfs_choose_fs_of_dev (vfs_device_t *vfs_dev)
int vfs_add_dev (device_t *dev)
int vfs_add_dev_with_fs (device_t *dev, int fs_id)
void vfs_eject_device (device_t *dev)
void vfs_add_fs (driver_t *new_driver)
int vfs_open (dentry_t *file, file_descriptor_t *fd, uint32_t flags)
int vfs_close (file_descriptor_t *fd)
int vfs_create (dentry_t *dir, const char *name, uint32_t len, mode_t mode)
int vfs_unlink (dentry_t *file)
int vfs_lookup (dentry_t *dir, const char *name, uint32_t len, dentry_t **result)
bool vfs_can_read (file_descriptor_t *fd)
bool vfs_can_write (file_descriptor_t *fd)
int vfs_read (file_descriptor_t *fd, uint8_t *buf, uint32_t len)
int vfs_write (file_descriptor_t *fd, uint8_t *buf, uint32_t len)
int vfs_mkdir (dentry_t *dir, const char *name, uint32_t len, mode_t mode)
int vfs_rmdir (dentry_t *dir)
int vfs_getdents (file_descriptor_t *dir_fd, uint8_t *buf, uint32_t len)
int vfs_resolve_path_start_from (dentry_t *dentry, const char *path, dentry_t **result)
int vfs_resolve_path (const char *path, dentry_t **result)
int vfs_mount (dentry_t *mountpoint, device_t *dev, uint32_t fs_indx)
int vfs_umount (dentry_t *mounted_dentry)
static proc_zone_t * _vfs_do_mmap (file_descriptor_t *fd, mmap_params_t *params)
proc_zone_t * vfs_mmap (file_descriptor_t *fd, mmap_params_t *params)
Variables
vfs_device_t _vfs_devices [MAX_DEVICES_COUNT]
dynamic_array_t _vfs_fses
int32_t root_fs_dev_id = -1
Function Documentation
_vfs_do_mmap()
static proc_zone_t* _vfs_do_mmap (file_descriptor_t * fd, mmap_params_t * params) static
Definition at line 481 of file vfs.c.
 {
     bool map_shared = ((params->flags & MAP_SHARED) > 0);
     bool map_private = ((params->flags & MAP_PRIVATE) > 0);
     proc_zone_t* zone;
     if (map_private) {
         zone = proc_new_random_zone(RUNNIG_THREAD->process, params->size);
         zone->type = ZONE_TYPE_MAPPED_FILE_PRIVATLY;
         zone->fd = fd;
         zone->offset = params->offset;
     } else {
         /* TODO */
         return 0;
     }
     return zone;
 }
References proc_zone::fd, mmap_params::flags, MAP_PRIVATE, MAP_SHARED, mmap_params::offset, proc_zone::offset, proc_new_random_zone(), RUNNIG_THREAD, mmap_params::size, proc_zone::type, and ZONE_TYPE_MAPPED_FILE_PRIVATLY.
Referenced by vfs_mmap().
_vfs_driver_info()
driver_desc_t _vfs_driver_info ()
Definition at line 25 of file vfs.c.
 {
     driver_desc_t vfs_desc;
     vfs_desc.type = DRIVER_VIRTUAL_FILE_SYSTEM;
     vfs_desc.is_device_driver = false;
     vfs_desc.is_device_needed = true;
     vfs_desc.is_driver_needed = true;
     vfs_desc.type_of_needed_device = DEVICE_STORAGE;
     vfs_desc.type_of_needed_driver = DRIVER_FILE_SYSTEM;
     vfs_desc.functions[DRIVER_NOTIFICATION] = 0;
     vfs_desc.functions[DRIVER_VIRTUAL_FILE_SYSTEM_ADD_DEVICE] = vfs_add_dev;
     vfs_desc.functions[DRIVER_VIRTUAL_FILE_SYSTEM_ADD_DRIVER] = vfs_add_fs;
     vfs_desc.functions[DRIVER_VIRTUAL_FILE_SYSTEM_EJECT_DEVICE] = vfs_eject_device;
     return vfs_desc;
 }
References DEVICE_STORAGE, DRIVER_FILE_SYSTEM, DRIVER_NOTIFICATION, DRIVER_VIRTUAL_FILE_SYSTEM, DRIVER_VIRTUAL_FILE_SYSTEM_ADD_DEVICE, DRIVER_VIRTUAL_FILE_SYSTEM_ADD_DRIVER, DRIVER_VIRTUAL_FILE_SYSTEM_EJECT_DEVICE, driver_desc_t::functions, driver_desc_t::is_device_driver, driver_desc_t::is_device_needed, driver_desc_t::is_driver_needed, driver_desc_t::type, driver_desc_t::type_of_needed_device, driver_desc_t::type_of_needed_driver, vfs_add_dev(), vfs_add_fs(), and vfs_eject_device().
Referenced by vfs_install().
vfs_add_dev()
int vfs_add_dev (device_t * dev)
Definition at line 72 of file vfs.c.
 {
     if (dev->type != DEVICE_STORAGE) {
         return -EPERM;
     }
     if (root_fs_dev_id == -1) {
         root_fs_dev_id = dev->id;
     }
     _vfs_devices[dev->id].dev = dev;
     if (!dev->is_virtual) {
         if (vfs_choose_fs_of_dev(&_vfs_devices[dev->id]) < 0) {
             return -ENOENT;
         }
     }
     return 0;
 }
References _vfs_devices, vfs_device_t::dev, DEVICE_STORAGE, ENOENT, EPERM, device_t::id, device_t::is_virtual, root_fs_dev_id, device_t::type, and vfs_choose_fs_of_dev().
Referenced by _vfs_driver_info().
vfs_add_dev_with_fs()
int vfs_add_dev_with_fs (device_t * dev, int fs_id)
Definition at line 91 of file vfs.c.
 {
     if (dev->type != DEVICE_STORAGE) {
         return -EPERM;
     }
     if (root_fs_dev_id == -1) {
         root_fs_dev_id = dev->id;
     }
     _vfs_devices[dev->id].dev = dev;
     _vfs_devices[dev->id].fs = fs_id;
     fs_ops_t* fs = dynamic_array_get(&_vfs_fses, fs_id);
     if (fs->prepare_fs) {
         int (*prepare_fs)(vfs_device_t * nd) = fs->prepare_fs;
         return prepare_fs(&_vfs_devices[dev->id]);
     }
     return 0;
 }
References _vfs_devices, _vfs_fses, vfs_device_t::dev, DEVICE_STORAGE, dynamic_array_get(), EPERM, vfs_device_t::fs, device_t::id, fs_ops::prepare_fs, root_fs_dev_id, and device_t::type.
Referenced by vfs_mount().
vfs_add_fs()
void vfs_add_fs (driver_t * new_driver)
Definition at line 128 of file vfs.c.
 {
     if (new_driver->desc.type != DRIVER_FILE_SYSTEM) {
         return;
     }
     fs_ops_t new_fs;
     new_fs.recognize = new_driver->desc.functions[DRIVER_FILE_SYSTEM_RECOGNIZE];
     new_fs.prepare_fs = new_driver->desc.functions[DRIVER_FILE_SYSTEM_PREPARE_FS];
     new_fs.eject_device = new_driver->desc.functions[DRIVER_FILE_SYSTEM_EJECT_DEVICE];
     new_fs.file.mkdir = new_driver->desc.functions[DRIVER_FILE_SYSTEM_MKDIR];
     new_fs.file.rmdir = new_driver->desc.functions[DRIVER_FILE_SYSTEM_RMDIR];
     new_fs.file.getdents = new_driver->desc.functions[DRIVER_FILE_SYSTEM_GETDENTS];
     new_fs.file.lookup = new_driver->desc.functions[DRIVER_FILE_SYSTEM_LOOKUP];
     new_fs.file.open = new_driver->desc.functions[DRIVER_FILE_SYSTEM_OPEN];
     new_fs.file.can_read = new_driver->desc.functions[DRIVER_FILE_SYSTEM_CAN_READ];
     new_fs.file.can_write = new_driver->desc.functions[DRIVER_FILE_SYSTEM_CAN_WRITE];
     new_fs.file.read = new_driver->desc.functions[DRIVER_FILE_SYSTEM_READ];
     new_fs.file.write = new_driver->desc.functions[DRIVER_FILE_SYSTEM_WRITE];
     new_fs.file.truncate = new_driver->desc.functions[DRIVER_FILE_SYSTEM_TRUNCATE];
     new_fs.file.create = new_driver->desc.functions[DRIVER_FILE_SYSTEM_CREATE];
     new_fs.file.unlink = new_driver->desc.functions[DRIVER_FILE_SYSTEM_UNLINK];
     new_fs.file.ioctl = new_driver->desc.functions[DRIVER_FILE_SYSTEM_IOCTL];
     new_fs.file.mmap = new_driver->desc.functions[DRIVER_FILE_SYSTEM_MMAP];
     new_fs.dentry.write_inode = new_driver->desc.functions[DRIVER_FILE_SYSTEM_WRITE_INODE];
     new_fs.dentry.read_inode = new_driver->desc.functions[DRIVER_FILE_SYSTEM_READ_INODE];
     new_fs.dentry.free_inode = new_driver->desc.functions[DRIVER_FILE_SYSTEM_FREE_INODE];
     new_fs.dentry.get_fsdata = new_driver->desc.functions[DRIVER_FILE_SYSTEM_GET_FSDATA];
     dynamic_array_push(&_vfs_fses, &new_fs);
 }
References _vfs_fses, file_ops::can_read, file_ops::can_write, file_ops::create, fs_ops::dentry, driver_t::desc, DRIVER_FILE_SYSTEM, DRIVER_FILE_SYSTEM_CAN_READ, DRIVER_FILE_SYSTEM_CAN_WRITE, DRIVER_FILE_SYSTEM_CREATE, DRIVER_FILE_SYSTEM_EJECT_DEVICE, DRIVER_FILE_SYSTEM_FREE_INODE, DRIVER_FILE_SYSTEM_GET_FSDATA, DRIVER_FILE_SYSTEM_GETDENTS, DRIVER_FILE_SYSTEM_IOCTL, DRIVER_FILE_SYSTEM_LOOKUP, DRIVER_FILE_SYSTEM_MKDIR, DRIVER_FILE_SYSTEM_MMAP, DRIVER_FILE_SYSTEM_OPEN, DRIVER_FILE_SYSTEM_PREPARE_FS, DRIVER_FILE_SYSTEM_READ, DRIVER_FILE_SYSTEM_READ_INODE, DRIVER_FILE_SYSTEM_RECOGNIZE, DRIVER_FILE_SYSTEM_RMDIR, DRIVER_FILE_SYSTEM_TRUNCATE, DRIVER_FILE_SYSTEM_UNLINK, DRIVER_FILE_SYSTEM_WRITE, DRIVER_FILE_SYSTEM_WRITE_INODE, dynamic_array_push(), fs_ops::eject_device, fs_ops::file, dentry_ops::free_inode, driver_desc_t::functions, dentry_ops::get_fsdata, file_ops::getdents, file_ops::ioctl, file_ops::lookup, file_ops::mkdir, file_ops::mmap, file_ops::open, fs_ops::prepare_fs, file_ops::read, dentry_ops::read_inode, fs_ops::recognize, file_ops::rmdir, file_ops::truncate, driver_desc_t::type, file_ops::unlink, file_ops::write, and dentry_ops::write_inode.
Referenced by _vfs_driver_info().
vfs_can_read()
bool vfs_can_read (file_descriptor_t * fd)
Definition at line 283 of file vfs.c.
 {
     if (!fd->ops->can_read) {
         return true;
     }
     return fd->ops->can_read(fd->dentry, fd->offset);
 }
References file_ops::can_read, file_descriptor::dentry, file_descriptor::offset, and file_descriptor::ops.
vfs_can_write()
bool vfs_can_write (file_descriptor_t * fd)
Definition at line 291 of file vfs.c.
 {
     if (!fd->ops->can_write) {
         return true;
     }
     return fd->ops->can_write(fd->dentry, fd->offset);
 }
References file_ops::can_write, file_descriptor::dentry, file_descriptor::offset, and file_descriptor::ops.
vfs_choose_fs_of_dev()
int vfs_choose_fs_of_dev (vfs_device_t * vfs_dev)
Definition at line 50 of file vfs.c.
 {
     int fs_cnt = _vfs_fses.size;
     for (int i = 0; i < fs_cnt; i++) {
         fs_ops_t* fs = dynamic_array_get(&_vfs_fses, (int)i);
         if (!fs->recognize) {
             continue;
         }
         bool (*is_capable)(vfs_device_t * nd) = fs->recognize;
         if (is_capable(vfs_dev)) {
             vfs_dev->fs = i;
             if (fs->prepare_fs) {
                 int (*prepare_fs)(vfs_device_t * nd) = fs->prepare_fs;
                 return prepare_fs(&_vfs_devices[vfs_dev->dev->id]);
             }
             return 0;
         }
     }
     return -ENOENT;
 }
References _vfs_devices, _vfs_fses, vfs_device_t::dev, dynamic_array_get(), ENOENT, vfs_device_t::fs, device_t::id, fs_ops::prepare_fs, fs_ops::recognize, and dynamic_array::size.
Referenced by vfs_add_dev().
vfs_close()
int vfs_close (file_descriptor_t * fd)
Definition at line 199 of file vfs.c.
 {
     if (!fd) {
         return -EFAULT;
     }
     if (fd->mapped_times) {
         return -EIO;
     }
     if (fd->type == FD_TYPE_FILE) {
         dentry_put(fd->dentry);
     } else {
         socket_put(fd->sock_entry);
     }
     fd->dentry = 0;
     fd->offset = 0;
     fd->ops = 0;
     return 0;
 }
References file_descriptor::dentry, dentry_put(), EFAULT, EIO, FD_TYPE_FILE, file_descriptor::mapped_times, file_descriptor::offset, file_descriptor::ops, file_descriptor::sock_entry, socket_put(), and file_descriptor::type.
Referenced by _syscmd_ls(), proc_free(), proc_load(), read(), sys_close(), and write().
vfs_create()
int vfs_create (dentry_t * dir, const char * name, uint32_t len, mode_t mode)
Definition at line 220 of file vfs.c.
 {
     /* Check if there is a file with the same name */
     dentry_t* tmp;
     if (vfs_lookup(dir, name, len, &tmp) == 0) {
         dentry_put(tmp);
         return -EEXIST;
     }
     return dir->ops->file.create(dir, name, len, mode);
 }
References file_ops::create, dentry_put(), EEXIST, fs_ops::file, mode, copy_bin::name, dentry::ops, and vfs_lookup().
Referenced by local_socket_bind(), sys_creat(), sys_open(), and touch().
vfs_eject_device()
void vfs_eject_device (device_t * dev)
Definition at line 114 of file vfs.c.
 {
 #ifdef VFS_DEBUG
     log("Ejecting\n");
 #endif
     int fs_id = _vfs_devices[dev->id].fs;
     fs_ops_t* fs = dynamic_array_get(&_vfs_fses, (int)fs_id);
     if (fs->eject_device) {
         bool (*eject)(vfs_device_t * nd) = fs->eject_device;
         eject(&_vfs_devices[dev->id]);
     }
     dentry_put_all_dentries_of_dev(dev->id);
 }
References _vfs_devices, _vfs_fses, dentry_put_all_dentries_of_dev(), dynamic_array_get(), fs_ops::eject_device, vfs_device_t::fs, device_t::id, and log().
Referenced by _vfs_driver_info().
vfs_getdents()
int vfs_getdents (file_descriptor_t * dir_fd, uint8_t * buf, uint32_t len)
Definition at line 349 of file vfs.c.
 {
     if (!dentry_inode_test_flag(dir_fd->dentry, S_IFDIR)) {
         return -ENOTDIR;
     }
     int res = dir_fd->ops->getdents(dir_fd->dentry, buf, &dir_fd->offset, len);
     return res;
 }
References buf, file_descriptor::dentry, dentry_inode_test_flag(), ENOTDIR, file_ops::getdents, file_descriptor::offset, file_descriptor::ops, and S_IFDIR.
Referenced by sys_getdents().
vfs_install()
void vfs_install ()
Init of vfs
Definition at line 44 of file vfs.c.
 {
     driver_install(_vfs_driver_info());
     dynamic_array_init_of_size(&_vfs_fses, sizeof(fs_ops_t), 16);
 }
References _vfs_driver_info(), _vfs_fses, driver_install(), and dynamic_array_init_of_size().
Referenced by stage3().
vfs_lookup()
int vfs_lookup (dentry_t * dir, const char * name, uint32_t len, dentry_t ** result)
Definition at line 249 of file vfs.c.
 {
     if (!dentry_inode_test_flag(dir, S_IFDIR)) {
         return -ENOTDIR;
     }
     if (len == 1) {
         if (name[0] == '.') {
             *result = dentry_duplicate(dir);
             return 0;
         }
     }
     /* If dir is a mount point, vfs should find it's parent by itself */
     if (dentry_test_flag(dir, DENTRY_MOUNTED)) {
 #ifdef VFS_DEBUG
         log("[VFS] Lookup for mounted's parents %d %d : %d %d", dir->dev_indx, dir->inode_indx, dir->parent_dev_indx, dir->parent_inode_indx);
 #endif
         if (len == 2) {
             if (name[0] == '.' && name[1] == '.') {
                 *result = dentry_get(dir->parent_dev_indx, dir->parent_inode_indx);
                 return 0;
             }
         }
     }
     uint32_t next_inode;
     if (dir->ops->file.lookup(dir, name, len, &next_inode) == 0) {
         *result = dentry_get(dir->dev_indx, next_inode);
         return 0;
     }
     return -ENOENT;
 }
References dentry_duplicate(), dentry_get(), dentry_inode_test_flag(), DENTRY_MOUNTED, dentry_test_flag(), dentry::dev_indx, ENOENT, ENOTDIR, fs_ops::file, dentry::inode_indx, log(), file_ops::lookup, copy_bin::name, dentry::ops, dentry::parent_dev_indx, dentry::parent_inode_indx, and S_IFDIR.
Referenced by vfs_create(), and vfs_resolve_path_start_from().
vfs_mkdir()
int vfs_mkdir (dentry_t * dir, const char * name, uint32_t len, mode_t mode)
Definition at line 324 of file vfs.c.
 {
     if (!dentry_inode_test_flag(dir, S_IFDIR)) {
         return -ENOTDIR;
     }
     return dir->ops->file.mkdir(dir, name, len, mode | S_IFDIR);
 }
References dentry_inode_test_flag(), ENOTDIR, fs_ops::file, file_ops::mkdir, mode, copy_bin::name, dentry::ops, and S_IFDIR.
Referenced by _syscmd_mkdir(), and sys_mkdir().
vfs_mmap()
proc_zone_t* vfs_mmap (file_descriptor_t * fd, mmap_params_t * params)
Definition at line 501 of file vfs.c.
 {
     fd->mapped_times++;
     /* Check if we have a custom mmap for a dentry */
     if (fd->dentry->ops->file.mmap) {
         proc_zone_t* res = fd->dentry->ops->file.mmap(fd->dentry, params);
         if ((uint32_t)res != VFS_USE_STD_MMAP) {
             return res;
         }
     }
     return _vfs_do_mmap(fd, params);
 }
References _vfs_do_mmap(), file_descriptor::dentry, fs_ops::file, file_descriptor::mapped_times, file_ops::mmap, dentry::ops, and VFS_USE_STD_MMAP.
Referenced by sys_mmap().
vfs_mount()
int vfs_mount (dentry_t * mountpoint, device_t * dev, uint32_t fs_indx)
Definition at line 418 of file vfs.c.
 {
     if (dentry_test_flag(mountpoint, DENTRY_MOUNTPOINT)) {
 #ifdef VFS_DEBUG
         log("[VFS] Already a mount point\n");
 #endif
         return -EBUSY;
     }
     if (!dentry_inode_test_flag(mountpoint, S_IFDIR)) {
 #ifdef VFS_DEBUG
         log("[VFS] Not a dir\n");
 #endif
         return -ENOTDIR;
     }
     vfs_add_dev_with_fs(dev, fs_indx);
     mountpoint = dentry_duplicate(mountpoint); /* We keep mounts in mem until to umount. */
     dentry_set_flag(mountpoint, DENTRY_MOUNTPOINT);
     dentry_t* mounted_dentry = dentry_get(dev->id, 2); /* Not going to put it, to keep mounts in mem until to umount */
     dentry_set_flag(mounted_dentry, DENTRY_MOUNTED);
     mountpoint->mounted_dentry = mounted_dentry;
     mounted_dentry->mountpoint = mountpoint;
     return 0;
 }
References dentry_duplicate(), dentry_get(), dentry_inode_test_flag(), DENTRY_MOUNTED, DENTRY_MOUNTPOINT, dentry_set_flag(), dentry_test_flag(), EBUSY, ENOTDIR, device_t::id, log(), dentry::mounted_dentry, dentry::mountpoint, S_IFDIR, and vfs_add_dev_with_fs().
Referenced by devfs_mount(), and procfs().
vfs_open()
int vfs_open (dentry_t * file, file_descriptor_t * fd, uint32_t flags)
Definition at line 163 of file vfs.c.
 {
     if (!file) {
         return -EFAULT;
     }
     if (!fd) {
         return -EFAULT;
     }
     if (dentry_test_flag(file, DENTRY_PRIVATE)) {
         return -EPERM;
     }
     if (dentry_inode_test_flag(file, S_IFDIR) && !(flags & O_DIRECTORY)) {
         return -EISDIR;
     }
     /* If it has custom open, let's use it */
     if (file->ops->file.open) {
         int res = file->ops->file.open(file, fd, flags);
         /* Devfs can't find the right one and returns ENOEXEC in this case. */
         if (res != -ENOEXEC) {
             return res;
         }
     }
     fd->flags = flags;
     fd->type = FD_TYPE_FILE;
     fd->dentry = dentry_duplicate(file);
     fd->offset = 0;
     fd->mapped_times = 0;
     fd->ops = &file->ops->file;
     return 0;
 }
References file_descriptor::dentry, dentry_duplicate(), dentry_inode_test_flag(), DENTRY_PRIVATE, dentry_test_flag(), EFAULT, EISDIR, ENOEXEC, EPERM, FD_TYPE_FILE, fs_ops::file, file_descriptor::flags, file_descriptor::mapped_times, O_DIRECTORY, file_descriptor::offset, file_ops::open, dentry::ops, file_descriptor::ops, S_IFDIR, and file_descriptor::type.
Referenced by _syscmd_ls(), local_socket_bind(), proc_copy_of(), proc_load(), proc_setup_tty(), read(), sys_creat(), sys_open(), and write().
vfs_read()
int vfs_read (file_descriptor_t * fd, uint8_t * buf, uint32_t len)
Definition at line 299 of file vfs.c.
 {
     int read = fd->ops->read(fd->dentry, buf, fd->offset, len);
     if (read > 0) {
         fd->offset += read;
     }
     return read;
 }
References buf, file_descriptor::dentry, file_descriptor::offset, file_descriptor::ops, read(), and file_ops::read.
Referenced by elf_load(), read(), sys_read(), and vmm_page_fault_handler().
vfs_resolve_path()
int vfs_resolve_path (const char * path, dentry_t ** result)
Definition at line 413 of file vfs.c.
 {
     return vfs_resolve_path_start_from((dentry_t*)0, path, result);
 }
References vfs_resolve_path_start_from().
Referenced by _kbdriver_notification(), _mouse_recieve_notification(), _syscmd_ls(), _syscmd_mkdir(), bga_recieve_notification(), devfs_mount(), proc_setup_tty(), procfs(), ptmx_install(), pty_slave_create(), read(), rm(), touch(), tty_new(), umount(), and write().
vfs_resolve_path_start_from()
int vfs_resolve_path_start_from (dentry_t * dentry, const char * path, dentry_t ** result)
Definition at line 358 of file vfs.c.
 {
     if (!path) {
         return -EFAULT;
     }
     dentry_t* cur_dent;
     if (!dentry || path[0] == '/') {
         cur_dent = dentry_get(root_fs_dev_id, 2);
         while (*path == '/')
             path++;
     } else {
         cur_dent = dentry_duplicate(dentry);
     }
     while (*path != '\0') {
         while (*path == '/')
             path++;
         const char* name = path;
         int len = 0;
         while (*path != '\0' && *path != '/')
             path++, len++;
         if (len == 0) {
             break;
         }
         dentry_t* parent_dent = cur_dent;
         if (vfs_lookup(cur_dent, name, len, &cur_dent) < 0) {
             return -ENOENT;
         }
         dentry_t* lookuped_dent = cur_dent;
         while (dentry_test_flag(cur_dent, DENTRY_MOUNTPOINT)) {
             cur_dent = cur_dent->mounted_dentry;
         }
         if (dentry_test_flag(lookuped_dent, DENTRY_MOUNTPOINT)) {
             dentry_put(lookuped_dent);
             cur_dent = dentry_duplicate(cur_dent);
         }
         if (cur_dent != parent_dent) {
             dentry_set_parent(cur_dent, parent_dent);
         }
         dentry_put(parent_dent);
     }
     *result = dentry_duplicate(cur_dent);
     dentry_put(cur_dent);
     return 0;
 }
References dentry_duplicate(), dentry_get(), DENTRY_MOUNTPOINT, dentry_put(), dentry_set_parent(), dentry_test_flag(), EFAULT, ENOENT, dentry::mounted_dentry, copy_bin::name, root_fs_dev_id, and vfs_lookup().
Referenced by local_socket_bind(), local_socket_connect(), proc_chdir(), proc_load(), sys_creat(), sys_open(), sys_rmdir(), sys_unlink(), and vfs_resolve_path().
vfs_rmdir()
int vfs_rmdir (dentry_t * dir)
Definition at line 332 of file vfs.c.
 {
     if (!dentry_inode_test_flag(dir, S_IFDIR)) {
         return -ENOTDIR;
     }
     if (dentry_test_flag(dir, DENTRY_MOUNTPOINT) || dentry_test_flag(dir, DENTRY_MOUNTED) || dir->d_count != 1) {
         return -EBUSY;
     }
     int err = dir->ops->file.rmdir(dir);
     if (!err) {
         log("Rmdir: will be deleted %d", dir->inode_indx);
         dentry_set_flag(dir, DENTRY_INODE_TO_BE_DELETED);
     }
     return err;
 }
References dentry::d_count, dentry_inode_test_flag(), DENTRY_INODE_TO_BE_DELETED, DENTRY_MOUNTED, DENTRY_MOUNTPOINT, dentry_set_flag(), dentry_test_flag(), EBUSY, ENOTDIR, fs_ops::file, dentry::inode_indx, log(), dentry::ops, file_ops::rmdir, and S_IFDIR.
Referenced by sys_rmdir().
vfs_umount()
int vfs_umount (dentry_t * mounted_dentry)
Definition at line 447 of file vfs.c.
 {
     if (!dentry_test_flag(mounted_dentry, DENTRY_MOUNTED)) {
 #ifdef VFS_DEBUG
         log_warn("[VFS] Not mounted\n");
 #endif
         return -EPERM;
     }
     dentry_t* mountpoint = mounted_dentry->mountpoint;
     if (!dentry_test_flag(mountpoint, DENTRY_MOUNTPOINT)) {
 #ifdef VFS_DEBUG
         log_warn("[VFS] Not a mountpoint\n");
 #endif
         return -EPERM;
     }
     dentry_rem_flag(mounted_dentry, DENTRY_MOUNTED);
     dentry_rem_flag(mountpoint, DENTRY_MOUNTPOINT);
     mounted_dentry->mountpoint = 0;
     mountpoint->mounted_dentry = 0;
     dentry_put(mounted_dentry);
     dentry_put(mountpoint);
     if (dentry_test_flag(mountpoint, DENTRY_MOUNTED)) {
         vfs_umount(mountpoint);
     }
     return 0;
 }
References DENTRY_MOUNTED, DENTRY_MOUNTPOINT, dentry_put(), dentry_rem_flag(), dentry_test_flag(), EPERM, log_warn(), dentry::mounted_dentry, dentry::mountpoint, and vfs_umount().
Referenced by umount(), and vfs_umount().
vfs_unlink()
int vfs_unlink (dentry_t * file)
Definition at line 232 of file vfs.c.
 {
     if (dentry_inode_test_flag(file, S_IFDIR)) {
         return -EPERM;
     }
     if (file->inode->links_count == 1) {
         /* According to docs, we don't delete inode while it's opened somewhere. */
         dentry_set_flag(file, DENTRY_INODE_TO_BE_DELETED);
 #ifdef VFS_DEBUG
         log("[VFS] unlink: the file will be deleted");
 #endif
     }
     return file->ops->file.unlink(file);
 }
References dentry_inode_test_flag(), DENTRY_INODE_TO_BE_DELETED, dentry_set_flag(), EPERM, fs_ops::file, dentry::inode, inode_t::links_count, log(), dentry::ops, S_IFDIR, and file_ops::unlink.
Referenced by rm(), and sys_unlink().
vfs_write()
int vfs_write (file_descriptor_t * fd, uint8_t * buf, uint32_t len)
Definition at line 308 of file vfs.c.
 {
     int written = fd->ops->write(fd->dentry, buf, fd->offset, len);
     if (written > 0) {
         fd->offset += written;
     }
     if (fd->flags & O_TRUNC) {
         if (fd->ops->truncate) {
             fd->ops->truncate(fd->dentry, fd->offset);
         }
     }
     return written;
 }
References buf, file_descriptor::dentry, file_descriptor::flags, O_TRUNC, file_descriptor::offset, file_descriptor::ops, file_ops::truncate, and file_ops::write.
Referenced by sys_write().
Variable Documentation
_vfs_devices
vfs_device_t _vfs_devices[MAX_DEVICES_COUNT]
Definition at line 21 of file vfs.c.
Referenced by dentry_alloc_new(), vfs_add_dev(), vfs_add_dev_with_fs(), vfs_choose_fs_of_dev(), and vfs_eject_device().
_vfs_fses
dynamic_array_t _vfs_fses
Definition at line 22 of file vfs.c.
Referenced by dentry_alloc_new(), vfs_add_dev_with_fs(), vfs_add_fs(), vfs_choose_fs_of_dev(), vfs_eject_device(), and vfs_install().
root_fs_dev_id
int32_t root_fs_dev_id = -1
Definition at line 23 of file vfs.c.
Referenced by vfs_add_dev(), vfs_add_dev_with_fs(), and vfs_resolve_path_start_from().