oneOS: userland/edit/viewer.h File Reference
viewer.h File Reference
Macros
#define STDIN 0
#define STDOUT 1
#define SCREEN_X 80
#define SCREEN_Y 24
Functions
void viewer_clear_screen ()
void viewer_display (char *buf, int start, int len)
void viewer_enter_menu_mode ()
void viewer_cursor_left ()
void viewer_cursor_right ()
void viewer_cursor_up ()
void viewer_cursor_down ()
void viewer_cursor_next ()
int viewer_get_cursor_offset_in_file ()
Macro Definition Documentation
SCREEN_X
#define SCREEN_X 80
Definition at line 6 of file viewer.h.
SCREEN_Y
#define SCREEN_Y 24
Definition at line 7 of file viewer.h.
STDIN
#define STDIN 0
Definition at line 4 of file viewer.h.
STDOUT
#define STDOUT 1
Definition at line 5 of file viewer.h.
Function Documentation
viewer_clear_screen()
void viewer_clear_screen ()
Definition at line 20 of file viewer.c.
 {
     out_x = out_y = 0;
     write(STDOUT, "\x1b[2J", 4);
     write(STDOUT, "\x1b[H", 3);
 }
References out_x, out_y, STDOUT, and write().
Referenced by viewer_display().
viewer_cursor_down()
void viewer_cursor_down ()
Definition at line 176 of file viewer.c.
 {
     if (cursor_y == SCREEN_Y - 1) {
         file_scroll_down();
     } else {
         working_with_offset += file_line_len(working_with_offset);
         cursor_y++;
         if (cursor_x >= file_line_len(working_with_offset)) {
             cursor_x = file_line_len(working_with_offset) - 1;
         }
         working_with_offset += cursor_x;
         _viewer_set_cursor(cursor_x, cursor_y);
     }
 }
References _viewer_set_cursor(), cursor_x, cursor_y, file_line_len(), file_scroll_down(), SCREEN_Y, and working_with_offset.
Referenced by viewing_accept_key().
viewer_cursor_left()
void viewer_cursor_left ()
Definition at line 139 of file viewer.c.
 {
     if (cursor_x) {
         cursor_x--;
         working_with_offset--;
         _viewer_set_cursor(cursor_x, cursor_y);
     }
 }
References _viewer_set_cursor(), cursor_x, cursor_y, and working_with_offset.
Referenced by viewing_accept_key().
viewer_cursor_next()
void viewer_cursor_next ()
Definition at line 191 of file viewer.c.
 {
     cursor_x++;
     if (cursor_x == SCREEN_X) {
         cursor_y++;
         cursor_x = 0;
     }
 }
References cursor_x, cursor_y, and SCREEN_X.
Referenced by file_paste_char().
viewer_cursor_right()
void viewer_cursor_right ()
Definition at line 148 of file viewer.c.
 {
     if (displaying_buffer) {
         if (displaying_buffer[working_with_offset] != '\n') {
             cursor_x++;
             working_with_offset++;
             _viewer_set_cursor(cursor_x, cursor_y);
         }
     }
 }
References _viewer_set_cursor(), cursor_x, cursor_y, displaying_buffer, and working_with_offset.
Referenced by viewing_accept_key().
viewer_cursor_up()
void viewer_cursor_up ()
Definition at line 159 of file viewer.c.
 {
     if (!cursor_y) {
         file_scroll_up();
     } else {
         working_with_offset -= file_line_len_backwards(working_with_offset);
         cursor_y--;
         int new_line_len = file_line_len_backwards(working_with_offset) - 1;
         if (cursor_x >= new_line_len) {
             cursor_x = (new_line_len) % SCREEN_X;
         }
         working_with_offset -= (new_line_len);
         working_with_offset += cursor_x;
         _viewer_set_cursor(cursor_x, cursor_y);
     }
 }
References _viewer_set_cursor(), cursor_x, cursor_y, file_line_len_backwards(), file_scroll_up(), SCREEN_X, and working_with_offset.
Referenced by viewing_accept_key().
viewer_display()
void viewer_display (char * buf, int start, int len)
Definition at line 114 of file viewer.c.
 {
     displaying_buffer = buf;
     int last_cx = 0;
     viewer_clear_screen();
     for (int i = start; i < start + len; i++) {
         if (out_x <= cursor_x && out_y == cursor_y) {
             working_with_offset = i;
             last_cx = out_x;
         }
         if (!_viewer_display_one(buf[i])) {
             goto out;
         }
     }
     while (out_y < SCREEN_Y - 1) {
         out_y++;
         write(STDOUT, "\n~", 2);
     }
 out:
     cursor_x = last_cx;
     _viewer_set_cursor(cursor_x, cursor_y);
 }
References _viewer_display_one(), _viewer_set_cursor(), buf, cursor_x, cursor_y, displaying_buffer, out_x, out_y, SCREEN_Y, STDOUT, viewer_clear_screen(), working_with_offset, and write().
Referenced by file_open(), file_paste_char(), file_scroll_down(), and file_scroll_up().
viewer_enter_menu_mode()
void viewer_enter_menu_mode ()
Definition at line 206 of file viewer.c.
 {
     write(STDOUT, "\x1b[25;1H", 7);
 }
References STDOUT, and write().
Referenced by menu_enter_mode().
viewer_get_cursor_offset_in_file()
int viewer_get_cursor_offset_in_file ()
Definition at line 200 of file viewer.c.
 {
     return working_with_offset;
 }
References working_with_offset.
Referenced by viewing_accept_key().