oneOS: userland/edit/viewer.c File Reference
viewer.c File Reference
#include "viewer.h"
#include "file.h"
#include <unistd.h>
#include <stdlib.h>
Functions
static int _viewer_get_offset (int cx, int cy)
void viewer_clear_screen ()
void _viewer_set_cursor (int col, int row)
void _viewer_set_cursor_to_start ()
void _viewer_new_line ()
char _viewer_has_space_to_print (char c)
char _viewer_display_one (char c)
static void _log_dec (uint32_t dec)
void viewer_display (char *buf, int start, int len)
void viewer_cursor_left ()
void viewer_cursor_right ()
void viewer_cursor_up ()
void viewer_cursor_down ()
void viewer_cursor_next ()
int viewer_get_cursor_offset_in_file ()
void viewer_enter_menu_mode ()
void viewer_leave_menu_mode ()
Variables
int out_x
int out_y
int cursor_x
int cursor_y
char * displaying_buffer
int working_with_offset
Function Documentation
_log_dec()
static void _log_dec (uint32_t dec) static
Definition at line 95 of file viewer.c.
 {
     uint32_t pk = 1000000000;
     char was_not_zero = 0;
     while (pk > 0) {
         uint32_t pp = dec / pk;
         if (was_not_zero || pp > 0) {
             char ccp = pp + '0';
             write(1, &ccp, 1);
             was_not_zero = 1;
         }
         dec -= pp * pk;
         pk /= 10;
     }
     if (!was_not_zero) {
         write(1, "0", 1);
     }
 }
References write().
_viewer_display_one()
char _viewer_display_one (char c)
Definition at line 75 of file viewer.c.
 {
     if (_viewer_has_space_to_print(c)) {
         if (c == '\n') {
             out_x = 0;
             out_y++;
             _viewer_new_line();
         } else {
             write(STDOUT, &c, 1);
             out_x++;
             if (out_x == SCREEN_X) {
                 out_x = 0;
                 out_y++;
             }
         }
         return 1;
     }
     return 0;
 }
References _viewer_has_space_to_print(), _viewer_new_line(), out_x, out_y, SCREEN_X, STDOUT, and write().
Referenced by viewer_display().
_viewer_get_offset()
static int _viewer_get_offset (int cx, int cy) static
Definition at line 15 of file viewer.c.
 {
     return cy * SCREEN_X + cx;
 }
References SCREEN_X.
_viewer_has_space_to_print()
char _viewer_has_space_to_print (char c)
Definition at line 61 of file viewer.c.
 {
     if (c == '\n') {
         if (out_y == SCREEN_Y - 1) {
             return 0;
         }
     } else {
         if (out_x == SCREEN_X - 1 && out_y == SCREEN_Y - 1) {
             return 0;
         }
     }
     return 1;
 }
References out_x, out_y, SCREEN_X, and SCREEN_Y.
Referenced by _viewer_display_one().
_viewer_new_line()
void _viewer_new_line ()
Definition at line 56 of file viewer.c.
 {
     write(STDOUT, "\n", 1);
 }
References STDOUT, and write().
Referenced by _viewer_display_one().
_viewer_set_cursor()
void _viewer_set_cursor (int col, int row)
Definition at line 27 of file viewer.c.
 {
     char buf[8];
     buf[0] = '\x1b';
     buf[1] = '[';
     int id = 2;
     col++, row++;
     if (row < 10) {
         buf[id++] = row + '0';
     } else {
         buf[id++] = (row / 10) + '0';
         buf[id++] = (row % 10) + '0';
     }
     buf[id++] = ';';
     if (col < 10) {
         buf[id++] = col + '0';
     } else {
         buf[id++] = (col / 10) + '0';
         buf[id++] = (col % 10) + '0';
     }
     buf[id++] = 'H';
     write(STDOUT, buf, id);
 }
References buf, STDOUT, and write().
Referenced by viewer_cursor_down(), viewer_cursor_left(), viewer_cursor_right(), viewer_cursor_up(), and viewer_display().
_viewer_set_cursor_to_start()
void _viewer_set_cursor_to_start ()
Definition at line 51 of file viewer.c.
 {
     write(STDOUT, "\x1b[H", 3);
 }
References STDOUT, and write().
Referenced by viewer_leave_menu_mode().
viewer_clear_screen()
void viewer_clear_screen ()
Definition at line 20 of file viewer.c.
 {
     out_x = out_y = 0;
     write(STDOUT, "\x1b[2J", 4);
     write(STDOUT, "\x1b[H", 3);
 }
References out_x, out_y, STDOUT, and write().
Referenced by viewer_display().
viewer_cursor_down()
void viewer_cursor_down ()
Definition at line 176 of file viewer.c.
 {
     if (cursor_y == SCREEN_Y - 1) {
         file_scroll_down();
     } else {
         working_with_offset += file_line_len(working_with_offset);
         cursor_y++;
         if (cursor_x >= file_line_len(working_with_offset)) {
             cursor_x = file_line_len(working_with_offset) - 1;
         }
         working_with_offset += cursor_x;
         _viewer_set_cursor(cursor_x, cursor_y);
     }
 }
References _viewer_set_cursor(), cursor_x, cursor_y, file_line_len(), file_scroll_down(), SCREEN_Y, and working_with_offset.
Referenced by viewing_accept_key().
viewer_cursor_left()
void viewer_cursor_left ()
Definition at line 139 of file viewer.c.
 {
     if (cursor_x) {
         cursor_x--;
         working_with_offset--;
         _viewer_set_cursor(cursor_x, cursor_y);
     }
 }
References _viewer_set_cursor(), cursor_x, cursor_y, and working_with_offset.
Referenced by viewing_accept_key().
viewer_cursor_next()
void viewer_cursor_next ()
Definition at line 191 of file viewer.c.
 {
     cursor_x++;
     if (cursor_x == SCREEN_X) {
         cursor_y++;
         cursor_x = 0;
     }
 }
References cursor_x, cursor_y, and SCREEN_X.
Referenced by file_paste_char().
viewer_cursor_right()
void viewer_cursor_right ()
Definition at line 148 of file viewer.c.
 {
     if (displaying_buffer) {
         if (displaying_buffer[working_with_offset] != '\n') {
             cursor_x++;
             working_with_offset++;
             _viewer_set_cursor(cursor_x, cursor_y);
         }
     }
 }
References _viewer_set_cursor(), cursor_x, cursor_y, displaying_buffer, and working_with_offset.
Referenced by viewing_accept_key().
viewer_cursor_up()
void viewer_cursor_up ()
Definition at line 159 of file viewer.c.
 {
     if (!cursor_y) {
         file_scroll_up();
     } else {
         working_with_offset -= file_line_len_backwards(working_with_offset);
         cursor_y--;
         int new_line_len = file_line_len_backwards(working_with_offset) - 1;
         if (cursor_x >= new_line_len) {
             cursor_x = (new_line_len) % SCREEN_X;
         }
         working_with_offset -= (new_line_len);
         working_with_offset += cursor_x;
         _viewer_set_cursor(cursor_x, cursor_y);
     }
 }
References _viewer_set_cursor(), cursor_x, cursor_y, file_line_len_backwards(), file_scroll_up(), SCREEN_X, and working_with_offset.
Referenced by viewing_accept_key().
viewer_display()
void viewer_display (char * buf, int start, int len)
Definition at line 114 of file viewer.c.
 {
     displaying_buffer = buf;
     int last_cx = 0;
     viewer_clear_screen();
     for (int i = start; i < start + len; i++) {
         if (out_x <= cursor_x && out_y == cursor_y) {
             working_with_offset = i;
             last_cx = out_x;
         }
         if (!_viewer_display_one(buf[i])) {
             goto out;
         }
     }
     while (out_y < SCREEN_Y - 1) {
         out_y++;
         write(STDOUT, "\n~", 2);
     }
 out:
     cursor_x = last_cx;
     _viewer_set_cursor(cursor_x, cursor_y);
 }
References _viewer_display_one(), _viewer_set_cursor(), buf, cursor_x, cursor_y, displaying_buffer, out_x, out_y, SCREEN_Y, STDOUT, viewer_clear_screen(), working_with_offset, and write().
Referenced by file_open(), file_paste_char(), file_scroll_down(), and file_scroll_up().
viewer_enter_menu_mode()
void viewer_enter_menu_mode ()
Definition at line 206 of file viewer.c.
 {
     write(STDOUT, "\x1b[25;1H", 7);
 }
References STDOUT, and write().
Referenced by menu_enter_mode().
viewer_get_cursor_offset_in_file()
int viewer_get_cursor_offset_in_file ()
Definition at line 200 of file viewer.c.
 {
     return working_with_offset;
 }
References working_with_offset.
Referenced by viewing_accept_key().
viewer_leave_menu_mode()
void viewer_leave_menu_mode ()
Definition at line 211 of file viewer.c.
 {
     /* FIXME: Restore cursor to prev position */
     _viewer_set_cursor_to_start();
 }
References _viewer_set_cursor_to_start().
Variable Documentation
cursor_x
int cursor_x
Definition at line 11 of file viewer.c.
Referenced by viewer_cursor_down(), viewer_cursor_left(), viewer_cursor_next(), viewer_cursor_right(), viewer_cursor_up(), and viewer_display().
cursor_y
int cursor_y
Definition at line 11 of file viewer.c.
Referenced by viewer_cursor_down(), viewer_cursor_left(), viewer_cursor_next(), viewer_cursor_right(), viewer_cursor_up(), and viewer_display().
displaying_buffer
char* displaying_buffer
Definition at line 12 of file viewer.c.
Referenced by viewer_cursor_right(), and viewer_display().
out_x
int out_x
Definition at line 10 of file viewer.c.
Referenced by _viewer_display_one(), _viewer_has_space_to_print(), viewer_clear_screen(), and viewer_display().
out_y
int out_y
Definition at line 10 of file viewer.c.
Referenced by _viewer_display_one(), _viewer_has_space_to_print(), viewer_clear_screen(), and viewer_display().
working_with_offset
int working_with_offset
Definition at line 13 of file viewer.c.
Referenced by viewer_cursor_down(), viewer_cursor_left(), viewer_cursor_right(), viewer_cursor_up(), viewer_display(), and viewer_get_cursor_offset_in_file().