oneOS: src/kernel/mem/vmm/vmm.c File Reference
vmm.c File Reference
#include <errno.h>
#include <log.h>
#include <mem/kmalloc.h>
#include <mem/vmm/vmm.h>
#include <mem/vmm/zoner.h>
#include <platform/x86/memmap.h>
#include <platform/x86/system.h>
#include <tasking/tasking.h>
#include <utils/kassert.h>
Macros
#define pdir_t pdirectory_t
#define VMM_OFFSET_IN_DIRECTORY(a) (((a) >> 22) & 0x3ff)
#define VMM_OFFSET_IN_TABLE(a) (((a) >> 12) & 0x3ff)
#define VMM_OFFSET_IN_PAGE(a) ((a)&0xfff)
#define FRAME(addr) (addr / VMM_PAGE_SIZE)
#define PAGE_START(vaddr) ((vaddr >> 12) << 12)
#define VMM_KERNEL_TABLES_START 768
#define VMM_USER_TABLES_START 0
#define IS_INDIVIDUAL_PER_DIR(index) (index < VMM_KERNEL_TABLES_START || (index == VMM_OFFSET_IN_DIRECTORY(pspace_zone.start)))
#define vmm_kernel_pdir_phys2virt(paddr) ((void*)((uint32_t)paddr + KERNEL_BASE - KERNEL_PM_BASE))
Functions
static void * _vmm_pspace_get_vaddr_of_active_pdir ()
static void * _vmm_pspace_get_nth_active_ptable (uint32_t n)
static void * _vmm_pspace_get_vaddr_of_active_ptable (uint32_t vaddr)
static bool _vmm_split_pspace ()
static void _vmm_pspace_init ()
static table_desc_t _vmm_pspace_gen ()
static void * _vmm_kernel_convert_vaddr2paddr (uint32_t vaddr)
static void * _vmm_convert_vaddr2paddr (uint32_t vaddr)
static void * _vmm_alloc_kernel_block ()
static bool _vmm_init_switch_to_kernel_pdir ()
static void _vmm_map_init_kernel_pages (uint32_t paddr, uint32_t vaddr)
static bool _vmm_create_kernel_ptables ()
static bool _vmm_map_kernel ()
static uint32_t _vmm_round_ceil_to_page (uint32_t value)
static uint32_t _vmm_round_floor_to_page (uint32_t value)
static bool _vmm_is_copy_on_write (uint32_t vaddr)
static int _vmm_resolve_copy_on_write (uint32_t vaddr)
static void _vmm_ensure_cow_for_page (uint32_t vaddr)
static void _vmm_ensure_cow_for_range (uint32_t vaddr, uint32_t length)
static int _vmm_copy_page_to_resolve_cow (uint32_t vaddr, ptable_t *src_ptable)
static bool _vmm_is_zeroing_on_demand (uint32_t vaddr)
static void _vmm_resolve_zeroing_on_demand (uint32_t vaddr)
static int _vmm_self_test ()
static void _vmm_free_pspace (pdirectory_t *pdir)
int vmm_setup ()
table_desc_t * vmm_pdirectory_lookup (pdirectory_t *pdir, uint32_t vaddr)
page_desc_t * vmm_ptable_lookup (ptable_t *ptable, uint32_t vaddr)
int vmm_allocate_ptable (uint32_t vaddr)
static int vmm_free_ptable (uint32_t ptable_indx)
int vmm_map_page (uint32_t vaddr, uint32_t paddr, uint32_t settings)
int vmm_unmap_page (uint32_t vaddr)
int vmm_map_pages (uint32_t vaddr, uint32_t paddr, uint32_t n_pages, uint32_t settings)
pdirectory_t * vmm_new_user_pdir ()
pdirectory_t * vmm_new_forked_user_pdir ()
int vmm_free_pdir (pdirectory_t *pdir)
void * vmm_bring_to_kernel (uint8_t *src, uint32_t length)
void vmm_copy_to_pdir (pdirectory_t *pdir, uint8_t *src, uint32_t dest_vaddr, uint32_t length)
void vmm_zero_user_pages (pdirectory_t *pdir)
pdirectory_t * vmm_get_active_pdir ()
pdirectory_t * vmm_get_kernel_pdir ()
int vmm_tune_page (uint32_t vaddr, uint32_t settings)
int vmm_tune_pages (uint32_t vaddr, uint32_t length, uint32_t settings)
int vmm_load_page (uint32_t vaddr, uint32_t settings)
int vmm_copy_page (uint32_t to_vaddr, uint32_t src_vaddr, ptable_t *src_ptable)
int vmm_alloc_page (page_desc_t *page)
int vmm_free_page (page_desc_t *page)
int vmm_page_fault_handler (uint8_t info, uint32_t vaddr)
int vmm_switch_pdir (pdirectory_t *pdir)
void vmm_enable_paging ()
void vmm_disable_paging ()
static bool vmm_test_pspace_vaddr_of_active_ptable ()
Variables
static pdirectory_t * _vmm_kernel_pdir
static pdirectory_t * _vmm_active_pdir
static zone_t pspace_zone
static uint32_t kernel_ptables_start_paddr
Macro Definition Documentation
FRAME
#define FRAME (addr) (addr / VMM_PAGE_SIZE)
Definition at line 25 of file vmm.c.
IS_INDIVIDUAL_PER_DIR
#define IS_INDIVIDUAL_PER_DIR (index) (index < VMM_KERNEL_TABLES_START || (index == VMM_OFFSET_IN_DIRECTORY(pspace_zone.start)))
Definition at line 30 of file vmm.c.
PAGE_START
#define PAGE_START (vaddr) ((vaddr >> 12) << 12)
Definition at line 26 of file vmm.c.
pdir_t
#define pdir_t pdirectory_t
Definition at line 21 of file vmm.c.
vmm_kernel_pdir_phys2virt
#define vmm_kernel_pdir_phys2virt (paddr) ((void*)((uint32_t)paddr + KERNEL_BASE - KERNEL_PM_BASE))
Definition at line 37 of file vmm.c.
VMM_KERNEL_TABLES_START
#define VMM_KERNEL_TABLES_START 768
Definition at line 28 of file vmm.c.
VMM_OFFSET_IN_DIRECTORY
#define VMM_OFFSET_IN_DIRECTORY (a) (((a) >> 22) & 0x3ff)
Definition at line 22 of file vmm.c.
VMM_OFFSET_IN_PAGE
#define VMM_OFFSET_IN_PAGE (a) ((a)&0xfff)
Definition at line 24 of file vmm.c.
VMM_OFFSET_IN_TABLE
#define VMM_OFFSET_IN_TABLE (a) (((a) >> 12) & 0x3ff)
Definition at line 23 of file vmm.c.
VMM_USER_TABLES_START
#define VMM_USER_TABLES_START 0
Definition at line 29 of file vmm.c.
Function Documentation
_vmm_alloc_kernel_block()
static void * _vmm_alloc_kernel_block () inline static
VM INITIALIZATION FUNCTIONS
Definition at line 209 of file vmm.c.
 {
     return vmm_kernel_pdir_phys2virt(pmm_alloc_block());
 }
References pmm_alloc_block(), and vmm_kernel_pdir_phys2virt.
Referenced by _vmm_split_pspace().
_vmm_convert_vaddr2paddr()
static void * _vmm_convert_vaddr2paddr (uint32_t vaddr) static
The function is used to traslate a virtual address into physical
Definition at line 198 of file vmm.c.
 {
     ptable_t* ptable_vaddr = (ptable_t*)_vmm_pspace_get_vaddr_of_active_ptable(vaddr);
     page_desc_t* page_desc = vmm_ptable_lookup(ptable_vaddr, vaddr);
     return (void*)((page_desc_get_frame(*page_desc)) | (vaddr & 0xfff));
 }
References _vmm_pspace_get_vaddr_of_active_ptable(), page_desc_get_frame(), page_desc_t, and vmm_ptable_lookup().
Referenced by _vmm_self_test(), and vmm_switch_pdir().
_vmm_copy_page_to_resolve_cow()
static int _vmm_copy_page_to_resolve_cow (uint32_t vaddr, ptable_t * src_ptable) static
The function is supposed to copy a page from @src_ptable to active ptable. The page which is copied has address @vaddr. ONLY TO RESOLVE COW!
Definition at line 537 of file vmm.c.
 {
     page_desc_t* old_page_desc = vmm_ptable_lookup(src_ptable, vaddr);
     /* Based on an old page */
     vmm_load_page(vaddr, page_desc_get_settings_ignore_cow(*old_page_desc));
     /* Mapping the old page to do a copy */
     zone_t tmp_zone = zoner_new_zone(VMM_PAGE_SIZE);
     uint32_t old_page_vaddr = (uint32_t)tmp_zone.start;
     uint32_t old_page_paddr = page_desc_get_frame(*old_page_desc);
     vmm_map_page(old_page_vaddr, old_page_paddr, PAGE_READABLE | PAGE_WRITABLE | PAGE_EXECUTABLE);
     /*  We don't need to check if there is a problem with cow, since this is a special copy function
         to resolve cow. So, we know that pages were created recently. Checking cow here would cause an
         ub, since table has not been setup correctly yet. */
     memcpy((uint8_t*)vaddr, (uint8_t*)old_page_vaddr, VMM_PAGE_SIZE);
     /* Freeing */
     vmm_unmap_page(old_page_vaddr);
     zoner_free_zone(tmp_zone);
     return 0;
 }
References memcpy(), page_desc_get_frame(), page_desc_get_settings_ignore_cow(), page_desc_t, PAGE_EXECUTABLE, PAGE_READABLE, PAGE_WRITABLE, __zone::start, vmm_load_page(), vmm_map_page(), VMM_PAGE_SIZE, vmm_ptable_lookup(), vmm_unmap_page(), zoner_free_zone(), and zoner_new_zone().
Referenced by _vmm_resolve_copy_on_write().
_vmm_create_kernel_ptables()
static bool _vmm_create_kernel_ptables () static
The function is supposed to create all kernel tables and map necessary data into _vmm_kernel_pdir. Used only in the first stage of VM init
VMM_OFFSET_IN_DIRECTORY(pspace_zone.start) shows number of table where pspace starts. Since pspace is right after kernel, let's protect them and not give user access to the whole ptable (and since ptable is not user, all pages inside it are not user too).
Definition at line 246 of file vmm.c.
 {
     uint32_t table_coverage = VMM_PAGE_SIZE * 1024;
     uint32_t kernel_ptabels_vaddr = VMM_KERNEL_TABLES_START * table_coverage;
     for (int i = VMM_KERNEL_TABLES_START; i < 1024; i++, kernel_ptabels_vaddr += table_coverage) {
         // updating table descriptor of kernel's pdir
         table_desc_t* ptable_desc = vmm_pdirectory_lookup(_vmm_kernel_pdir, kernel_ptabels_vaddr);
         uint32_t paddr = (uint32_t)pmm_alloc_block();
         if (!paddr) {
             kpanic("PADDR_5546 : BUG\n");
         }
         table_desc_set_attrs(ptable_desc, TABLE_DESC_PRESENT | TABLE_DESC_WRITABLE);
         if (i > VMM_OFFSET_IN_DIRECTORY(pspace_zone.start)) {
             table_desc_set_attrs(ptable_desc, TABLE_DESC_USER);
         }
         table_desc_set_frame(ptable_desc, FRAME(paddr));
     }
     _vmm_map_init_kernel_pages(0x00100000, 0xc0000000);
     _vmm_map_init_kernel_pages(0x00000000, 0xffc00000);
     return true;
 }
References _vmm_kernel_pdir, _vmm_map_init_kernel_pages(), FRAME, kpanic(), pmm_alloc_block(), pspace_zone, __zone::start, TABLE_DESC_PRESENT, table_desc_set_attrs(), table_desc_set_frame(), table_desc_t, TABLE_DESC_USER, TABLE_DESC_WRITABLE, VMM_KERNEL_TABLES_START, VMM_OFFSET_IN_DIRECTORY, VMM_PAGE_SIZE, and vmm_pdirectory_lookup().
Referenced by vmm_setup().
_vmm_ensure_cow_for_page()
static void _vmm_ensure_cow_for_page (uint32_t vaddr) static
Definition at line 517 of file vmm.c.
 {
     if (_vmm_is_copy_on_write(vaddr)) {
         _vmm_resolve_copy_on_write(vaddr);
     }
 }
References _vmm_is_copy_on_write(), and _vmm_resolve_copy_on_write().
Referenced by _vmm_ensure_cow_for_range(), and vmm_copy_page().
_vmm_ensure_cow_for_range()
static void _vmm_ensure_cow_for_range (uint32_t vaddr, uint32_t length) static
Definition at line 524 of file vmm.c.
 {
     uint32_t page_addr = PAGE_START(vaddr);
     while (page_addr < vaddr + length) {
         _vmm_ensure_cow_for_page(page_addr);
         page_addr += VMM_PAGE_SIZE;
     }
 }
References _vmm_ensure_cow_for_page(), PAGE_START, and VMM_PAGE_SIZE.
Referenced by vmm_copy_to_pdir().
_vmm_free_pspace()
static void _vmm_free_pspace (pdirectory_t * pdir) static
Definition at line 174 of file vmm.c.
 {
     table_desc_t* ptable_desc = &pdir->entities[VMM_OFFSET_IN_DIRECTORY(pspace_zone.start)];
     if (!table_desc_has_attrs(*ptable_desc, TABLE_DESC_PRESENT)) {
         return;
     }
     pmm_free_block((void*)table_desc_get_frame(*ptable_desc));
     table_desc_del_frame(ptable_desc);
 }
References pdirectory::entities, pmm_free_block(), pspace_zone, __zone::start, table_desc_del_frame(), table_desc_get_frame(), table_desc_has_attrs(), TABLE_DESC_PRESENT, table_desc_t, and VMM_OFFSET_IN_DIRECTORY.
Referenced by vmm_free_pdir().
_vmm_init_switch_to_kernel_pdir()
static bool _vmm_init_switch_to_kernel_pdir () static
The function is used to update active pdir Used only in the first stage of VM init
Definition at line 218 of file vmm.c.
 {
     _vmm_active_pdir = _vmm_kernel_pdir;
     system_disable_interrupts();
     /* Should have :Memory here? */
     system_set_pdir((uint32_t)_vmm_kernel_convert_vaddr2paddr((uint32_t)_vmm_active_pdir));
     system_enable_interrupts();
     return true;
 }
References _vmm_active_pdir, _vmm_kernel_convert_vaddr2paddr(), _vmm_kernel_pdir, system_disable_interrupts(), system_enable_interrupts(), and system_set_pdir().
Referenced by vmm_setup().
_vmm_is_copy_on_write()
static bool _vmm_is_copy_on_write (uint32_t vaddr) static
COPY ON WRITE FUNCTIONS
Definition at line 481 of file vmm.c.
 {
     table_desc_t* ptable_desc = vmm_pdirectory_lookup(_vmm_active_pdir, vaddr);
     return table_desc_is_copy_on_write(*ptable_desc);
 }
References _vmm_active_pdir, table_desc_is_copy_on_write(), table_desc_t, and vmm_pdirectory_lookup().
Referenced by _vmm_ensure_cow_for_page(), and vmm_page_fault_handler().
_vmm_is_zeroing_on_demand()
static bool _vmm_is_zeroing_on_demand (uint32_t vaddr) static
ZEROING ON DEMAND FUNCTIONS
Definition at line 565 of file vmm.c.
 {
     table_desc_t* ptable_desc = vmm_pdirectory_lookup(_vmm_active_pdir, vaddr);
     if (table_desc_has_attrs(*ptable_desc, TABLE_DESC_ZEROING_ON_DEMAND)) {
         return true;
     }
     ptable_t* ptable = _vmm_pspace_get_vaddr_of_active_ptable(vaddr);
     table_desc_t* ppage_desc = vmm_ptable_lookup(ptable, vaddr);
     return page_desc_has_attrs(*ppage_desc, PAGE_DESC_ZEROING_ON_DEMAND);
 }
References _vmm_active_pdir, _vmm_pspace_get_vaddr_of_active_ptable(), page_desc_has_attrs(), PAGE_DESC_ZEROING_ON_DEMAND, table_desc_has_attrs(), table_desc_t, TABLE_DESC_ZEROING_ON_DEMAND, vmm_pdirectory_lookup(), and vmm_ptable_lookup().
Referenced by vmm_page_fault_handler().
_vmm_kernel_convert_vaddr2paddr()
static void * _vmm_kernel_convert_vaddr2paddr (uint32_t vaddr) static
The function is used to traslate a virtual address into physical Used only in the first stage of VM init
Definition at line 188 of file vmm.c.
 {
     ptable_t* ptable_vaddr = (ptable_t*)(kernel_ptables_start_paddr + (VMM_OFFSET_IN_DIRECTORY(vaddr) - VMM_KERNEL_TABLES_START) * VMM_PAGE_SIZE);
     page_desc_t* page_desc = vmm_ptable_lookup(ptable_vaddr, vaddr);
     return (void*)((page_desc_get_frame(*page_desc)) | (vaddr & 0xfff));
 }
References kernel_ptables_start_paddr, page_desc_get_frame(), page_desc_t, VMM_KERNEL_TABLES_START, VMM_OFFSET_IN_DIRECTORY, VMM_PAGE_SIZE, and vmm_ptable_lookup().
Referenced by _vmm_init_switch_to_kernel_pdir().
_vmm_map_init_kernel_pages()
static void _vmm_map_init_kernel_pages (uint32_t paddr, uint32_t vaddr) static
The function is used to map kernel pages Used only in the first stage of VM init
Definition at line 232 of file vmm.c.
 {
     ptable_t* ptable_paddr = (ptable_t*)(kernel_ptables_start_paddr + (VMM_OFFSET_IN_DIRECTORY(vaddr) - VMM_KERNEL_TABLES_START) * VMM_PAGE_SIZE);
     for (uint32_t phyz = paddr, virt = vaddr, i = 0; i < 1024; phyz += VMM_PAGE_SIZE, virt += VMM_PAGE_SIZE, i++) {
         pte_t new_page = (FRAME(phyz) << 12) | 3;
         ptable_paddr->entities[i] = new_page;
     }
 }
References ptable_t::entities, FRAME, kernel_ptables_start_paddr, pte_t, VMM_KERNEL_TABLES_START, VMM_OFFSET_IN_DIRECTORY, and VMM_PAGE_SIZE.
Referenced by _vmm_create_kernel_ptables().
_vmm_map_kernel()
static bool _vmm_map_kernel () static
The function is supposed to map secondary data for kernel's pdir. Used only in the first stage of VM init
Definition at line 282 of file vmm.c.
 {
     vmm_map_pages(0x00000000, 0x00000000, 1024, PAGE_READABLE | PAGE_WRITABLE | PAGE_EXECUTABLE);
     return true;
 }
References PAGE_EXECUTABLE, PAGE_READABLE, PAGE_WRITABLE, and vmm_map_pages().
Referenced by vmm_setup().
_vmm_pspace_gen()
static table_desc_t _vmm_pspace_gen () static
The function is used to generate new pspace. The function returns the table of itself.
Definition at line 144 of file vmm.c.
 {
     ptable_t* cur_ptable = (ptable_t*)_vmm_pspace_get_nth_active_ptable(VMM_OFFSET_IN_DIRECTORY(pspace_zone.start));
     uint32_t ptable_paddr = (uint32_t)pmm_alloc_block();
     zone_t tmp_zone = zoner_new_zone(VMM_PAGE_SIZE);
     ptable_t* new_ptable = (ptable_t*)tmp_zone.start;
     vmm_map_page((uint32_t)new_ptable, ptable_paddr, PAGE_READABLE | PAGE_WRITABLE | PAGE_EXECUTABLE);
     for (int i = 0; i < 1024; i++) {
         // coping all pages
         new_ptable->entities[i] = cur_ptable->entities[i];
     }
     page_desc_t pspace_page = 0;
     page_desc_set_attrs(&pspace_page, PAGE_DESC_PRESENT | PAGE_DESC_WRITABLE);
     page_desc_set_frame(&pspace_page, FRAME(ptable_paddr));
     new_ptable->entities[VMM_OFFSET_IN_DIRECTORY(pspace_zone.start)] = pspace_page;
     table_desc_t pspace_table = 0;
     table_desc_set_attrs(&pspace_table, TABLE_DESC_PRESENT | TABLE_DESC_WRITABLE);
     table_desc_set_frame(&pspace_table, FRAME(ptable_paddr));
     vmm_unmap_page((uint32_t)new_ptable);
     zoner_free_zone(tmp_zone);
     return pspace_table;
 }
References _vmm_pspace_get_nth_active_ptable(), ptable_t::entities, FRAME, PAGE_DESC_PRESENT, page_desc_set_attrs(), page_desc_set_frame(), page_desc_t, PAGE_DESC_WRITABLE, PAGE_EXECUTABLE, PAGE_READABLE, PAGE_WRITABLE, pmm_alloc_block(), pspace_zone, __zone::start, TABLE_DESC_PRESENT, table_desc_set_attrs(), table_desc_set_frame(), table_desc_t, TABLE_DESC_WRITABLE, vmm_map_page(), VMM_OFFSET_IN_DIRECTORY, VMM_PAGE_SIZE, vmm_unmap_page(), zoner_free_zone(), and zoner_new_zone().
Referenced by vmm_new_forked_user_pdir(), and vmm_new_user_pdir().
_vmm_pspace_get_nth_active_ptable()
static void * _vmm_pspace_get_nth_active_ptable (uint32_t n) inline static
Definition at line 90 of file vmm.c.
 {
     return (void*)(pspace_zone.start + n * VMM_PAGE_SIZE);
 }
References pspace_zone, __zone::start, and VMM_PAGE_SIZE.
Referenced by _vmm_pspace_gen(), and _vmm_pspace_get_vaddr_of_active_ptable().
_vmm_pspace_get_vaddr_of_active_pdir()
static void * _vmm_pspace_get_vaddr_of_active_pdir () inline static
PRIVATE FUNCTIONS
PSPACE FUNCTIONS
Pspace is a space with all current tables mapped there. The space starts from @pspace_zone.start and length is 4mb The function is supposed to setup pspace_zone.start Every virtual space has its own user's ptables in the area. The kernel's patables are the same.
Definition at line 85 of file vmm.c.
 {
     return (void*)_vmm_active_pdir;
 }
References _vmm_active_pdir.
_vmm_pspace_get_vaddr_of_active_ptable()
static void * _vmm_pspace_get_vaddr_of_active_ptable (uint32_t vaddr) inline static
Definition at line 95 of file vmm.c.
 {
     return (void*)_vmm_pspace_get_nth_active_ptable(VMM_OFFSET_IN_DIRECTORY(vaddr));
 }
References _vmm_pspace_get_nth_active_ptable(), and VMM_OFFSET_IN_DIRECTORY.
Referenced by _vmm_convert_vaddr2paddr(), _vmm_is_zeroing_on_demand(), _vmm_resolve_copy_on_write(), _vmm_resolve_zeroing_on_demand(), vmm_allocate_ptable(), vmm_copy_page(), vmm_map_page(), vmm_test_pspace_vaddr_of_active_ptable(), vmm_tune_page(), and vmm_unmap_page().
_vmm_pspace_init()
static void _vmm_pspace_init () static
The function is used to init pspace Used only in the first stage of VM init
Definition at line 121 of file vmm.c.
 {
     uint32_t kernel_ptabels_vaddr = pspace_zone.start + VMM_KERNEL_TABLES_START * VMM_PAGE_SIZE; // map what
     uint32_t kernel_ptabels_paddr = kernel_ptables_start_paddr; // map to
     for (int i = VMM_KERNEL_TABLES_START; i < 1024; i++) {
         table_desc_t* ptable_desc = vmm_pdirectory_lookup(_vmm_active_pdir, kernel_ptabels_vaddr);
         if (!table_desc_is_present(*ptable_desc)) {
             // must present
             kpanic("PSPACE_6335 : BUG\n");
         }
         ptable_t* ptable_vaddr = (ptable_t*)(kernel_ptables_start_paddr + (VMM_OFFSET_IN_DIRECTORY(kernel_ptabels_vaddr) - VMM_KERNEL_TABLES_START) * VMM_PAGE_SIZE);
         page_desc_t* page = vmm_ptable_lookup(ptable_vaddr, kernel_ptabels_vaddr);
         page_desc_set_attrs(page, PAGE_DESC_PRESENT | PAGE_DESC_WRITABLE);
         page_desc_set_frame(page, FRAME(kernel_ptabels_paddr));
         kernel_ptabels_vaddr += VMM_PAGE_SIZE;
         kernel_ptabels_paddr += VMM_PAGE_SIZE;
     }
 }
References _vmm_active_pdir, FRAME, kernel_ptables_start_paddr, kpanic(), PAGE_DESC_PRESENT, page_desc_set_attrs(), page_desc_set_frame(), page_desc_t, PAGE_DESC_WRITABLE, pspace_zone, __zone::start, table_desc_is_present(), table_desc_t, VMM_KERNEL_TABLES_START, VMM_OFFSET_IN_DIRECTORY, VMM_PAGE_SIZE, vmm_pdirectory_lookup(), and vmm_ptable_lookup().
Referenced by vmm_setup().
_vmm_resolve_copy_on_write()
static int _vmm_resolve_copy_on_write (uint32_t vaddr) static
Definition at line 488 of file vmm.c.
 {
     table_desc_t* ptable_desc = vmm_pdirectory_lookup(_vmm_active_pdir, vaddr);
     /* copying old ptable to kernel */
     ptable_t* src_ptable = kmalloc_page_aligned();
     ptable_t* root_ptable = _vmm_pspace_get_vaddr_of_active_ptable(vaddr);
     memcpy((uint8_t*)src_ptable, (uint8_t*)root_ptable, VMM_PAGE_SIZE);
     /* setting up new ptable */
     int res = vmm_allocate_ptable(vaddr);
     if (res != 0) {
         return res;
     }
     ptable_t* new_ptable = _vmm_pspace_get_vaddr_of_active_ptable(vaddr);
     /* FIXME: Currently we do that for all pages in the table. */
     for (int i = 0; i < 1024; i++) {
         uint32_t page_vaddr = ((vaddr >> 22) << 22) + (i * VMM_PAGE_SIZE);
         page_desc_t* page_desc = vmm_ptable_lookup(src_ptable, page_vaddr);
         if ((uint32_t)*page_desc != 0) {
             _vmm_copy_page_to_resolve_cow(page_vaddr, src_ptable);
         }
     }
     kfree_aligned(src_ptable);
 }
References _vmm_active_pdir, _vmm_copy_page_to_resolve_cow(), _vmm_pspace_get_vaddr_of_active_ptable(), kfree_aligned(), kmalloc_page_aligned(), memcpy(), page_desc_t, table_desc_t, vmm_allocate_ptable(), VMM_PAGE_SIZE, vmm_pdirectory_lookup(), and vmm_ptable_lookup().
Referenced by _vmm_ensure_cow_for_page(), and vmm_page_fault_handler().
_vmm_resolve_zeroing_on_demand()
static void _vmm_resolve_zeroing_on_demand (uint32_t vaddr) static
Definition at line 576 of file vmm.c.
 {
     table_desc_t* ptable_desc = vmm_pdirectory_lookup(_vmm_active_pdir, vaddr);
     ptable_t* ptable = _vmm_pspace_get_vaddr_of_active_ptable(vaddr);
     if (table_desc_has_attrs(*ptable_desc, TABLE_DESC_ZEROING_ON_DEMAND)) {
         for (int i = 0; i < 1024; i++) {
             page_desc_set_attrs(&ptable->entities[i], PAGE_DESC_ZEROING_ON_DEMAND);
             page_desc_del_attrs(&ptable->entities[i], PAGE_DESC_WRITABLE);
         }
         table_desc_del_attrs(ptable_desc, TABLE_DESC_ZEROING_ON_DEMAND);
     }
     table_desc_t* ppage_desc = vmm_ptable_lookup(ptable, vaddr);
     uint8_t* dest = (uint8_t*)_vmm_round_floor_to_page(vaddr);
     memset(dest, 0, VMM_PAGE_SIZE);
     page_desc_del_attrs(ppage_desc, PAGE_DESC_ZEROING_ON_DEMAND);
     page_desc_set_attrs(ppage_desc, PAGE_DESC_WRITABLE);
 }
References _vmm_active_pdir, _vmm_pspace_get_vaddr_of_active_ptable(), _vmm_round_floor_to_page(), ptable_t::entities, memset(), page_desc_del_attrs(), page_desc_set_attrs(), PAGE_DESC_WRITABLE, PAGE_DESC_ZEROING_ON_DEMAND, table_desc_del_attrs(), table_desc_has_attrs(), table_desc_t, TABLE_DESC_ZEROING_ON_DEMAND, VMM_PAGE_SIZE, vmm_pdirectory_lookup(), and vmm_ptable_lookup().
Referenced by vmm_page_fault_handler().
_vmm_round_ceil_to_page()
static uint32_t _vmm_round_ceil_to_page (uint32_t value) inline static
VM TOOLS
Definition at line 308 of file vmm.c.
 {
     if ((value & (VMM_PAGE_SIZE - 1)) != 0) {
         value += VMM_PAGE_SIZE;
         value &= (0xffffffff - (VMM_PAGE_SIZE - 1));
     }
     return value;
 }
References VMM_PAGE_SIZE.
_vmm_round_floor_to_page()
static uint32_t _vmm_round_floor_to_page (uint32_t value) inline static
Definition at line 317 of file vmm.c.
 {
     return (value & (0xffffffff - (VMM_PAGE_SIZE - 1)));
 }
References VMM_PAGE_SIZE.
Referenced by _vmm_resolve_zeroing_on_demand(), and vmm_load_page().
_vmm_self_test()
static int _vmm_self_test () static
VM SELF TEST FUNCTIONS
Definition at line 927 of file vmm.c.
 {
     vmm_map_pages(0x00f0000, 0x8f000000, 1, PAGE_READABLE | PAGE_WRITABLE | PAGE_EXECUTABLE);
     bool correct = true;
     correct &= ((uint32_t)_vmm_convert_vaddr2paddr(KERNEL_BASE) == KERNEL_PM_BASE);
     correct &= ((uint32_t)_vmm_convert_vaddr2paddr(0xffc00000) == 0x0);
     correct &= ((uint32_t)_vmm_convert_vaddr2paddr(0x100) == 0x100);
     correct &= ((uint32_t)_vmm_convert_vaddr2paddr(0x8f000000) == 0x00f0000);
     if (correct) {
         return 0;
     }
     return 1;
 }
References _vmm_convert_vaddr2paddr(), KERNEL_BASE, KERNEL_PM_BASE, PAGE_EXECUTABLE, PAGE_READABLE, PAGE_WRITABLE, and vmm_map_pages().
Referenced by vmm_setup().
_vmm_split_pspace()
static bool _vmm_split_pspace () static
Definition at line 100 of file vmm.c.
 {
     pspace_zone = zoner_new_zone(4 * MB);
     if (VMM_OFFSET_IN_TABLE(pspace_zone.start) != 0) {
         kpanic("WRONG PSPACE START ADDR");
     }
     // FIXME: remove constant basing on kernel len.
     kernel_ptables_start_paddr = 0x220000;
     while ((uint32_t)pmm_alloc_block() < (kernel_ptables_start_paddr - 2 * VMM_PAGE_SIZE)) {
     }
     _vmm_kernel_pdir = (pdir_t*)_vmm_alloc_kernel_block();
     _vmm_active_pdir = (pdir_t*)_vmm_kernel_pdir;
     memset((void*)_vmm_active_pdir, 0, sizeof(*_vmm_active_pdir)); // TODO problem for now
 }
References _vmm_active_pdir, _vmm_alloc_kernel_block(), _vmm_kernel_pdir, kernel_ptables_start_paddr, kpanic(), MB, memset(), pdir_t, pmm_alloc_block(), pspace_zone, __zone::start, VMM_OFFSET_IN_TABLE, VMM_PAGE_SIZE, and zoner_new_zone().
Referenced by vmm_setup().
vmm_alloc_page()
int vmm_alloc_page (page_desc_t * page)
Definition at line 821 of file vmm.c.
 {
     void* new_block = kmalloc_page_aligned();
     if (!new_block) {
         return -VMM_ERR_BAD_ADDR;
     }
     page_desc_set_attrs(page, PAGE_DESC_PRESENT);
     page_desc_set_frame(page, FRAME((uint32_t)new_block));
     return 0;
 }
References FRAME, kmalloc_page_aligned(), PAGE_DESC_PRESENT, page_desc_set_attrs(), page_desc_set_frame(), and VMM_ERR_BAD_ADDR.
vmm_allocate_ptable()
int vmm_allocate_ptable (uint32_t vaddr)
The function is supposed to create new ptable (not kernel) and rebuild pspace to match to the new setup
Definition at line 342 of file vmm.c.
 {
     if (_vmm_active_pdir == 0) {
         return -VMM_ERR_PDIR;
     }
     uint32_t ptable_paddr = (uint32_t)pmm_alloc_block();
     if (!ptable_paddr) {
         log_error(" vmm_allocate_ptable: No free space in pmm");
         return -VMM_ERR_NO_SPACE;
     }
     uint32_t ptable_vaddr = (uint32_t)_vmm_pspace_get_vaddr_of_active_ptable(vaddr);
     table_desc_t* ptable_desc = vmm_pdirectory_lookup(_vmm_active_pdir, vaddr);
     table_desc_clear(ptable_desc);
     table_desc_set_attrs(ptable_desc, TABLE_DESC_PRESENT | TABLE_DESC_WRITABLE | TABLE_DESC_USER);
     table_desc_set_frame(ptable_desc, FRAME(ptable_paddr));
     int ret = vmm_map_page(ptable_vaddr, ptable_paddr, PAGE_READABLE | PAGE_WRITABLE | PAGE_EXECUTABLE | PAGE_CHOOSE_OWNER(vaddr));
     if (ret == 0) {
         memset((void*)ptable_vaddr, 0, VMM_PAGE_SIZE);
     }
     return ret;
 }
References _vmm_active_pdir, _vmm_pspace_get_vaddr_of_active_ptable(), FRAME, log_error(), memset(), PAGE_CHOOSE_OWNER, PAGE_EXECUTABLE, PAGE_READABLE, PAGE_WRITABLE, pmm_alloc_block(), table_desc_clear(), TABLE_DESC_PRESENT, table_desc_set_attrs(), table_desc_set_frame(), table_desc_t, TABLE_DESC_USER, TABLE_DESC_WRITABLE, VMM_ERR_NO_SPACE, VMM_ERR_PDIR, vmm_map_page(), VMM_PAGE_SIZE, and vmm_pdirectory_lookup().
Referenced by _vmm_resolve_copy_on_write(), and vmm_map_page().
vmm_bring_to_kernel()
void* vmm_bring_to_kernel (uint8_t * src, uint32_t length)
Definition at line 684 of file vmm.c.
 {
     if ((uint32_t)src >= KERNEL_BASE) {
         return src;
     }
     uint8_t* kaddr = kmalloc(length);
     memcpy(kaddr, src, length);
     return (void*)kaddr;
 }
References KERNEL_BASE, kmalloc(), and memcpy().
Referenced by vmm_copy_to_pdir().
vmm_copy_page()
int vmm_copy_page (uint32_t to_vaddr, uint32_t src_vaddr, ptable_t * src_ptable)
The function is supposed to copy a page from @src_ptable to active ptable. The page which is copied has address @vaddr. ONLY TO RESOLVE COW!
Definition at line 792 of file vmm.c.
 {
     page_desc_t* old_page_desc = vmm_ptable_lookup(src_ptable, src_vaddr);
     /* Based on an old page */
     ptable_t* cur_ptable = (ptable_t*)_vmm_pspace_get_vaddr_of_active_ptable(to_vaddr);
     page_desc_t* cur_page = vmm_ptable_lookup(cur_ptable, to_vaddr);
     if (!page_desc_is_present(*cur_page)) {
         vmm_load_page(to_vaddr, page_desc_get_settings_ignore_cow(*old_page_desc));
     } else {
         _vmm_ensure_cow_for_page(to_vaddr);
     }
     /* Mapping the old page to do a copy */
     zone_t tmp_zone = zoner_new_zone(VMM_PAGE_SIZE);
     uint32_t old_page_vaddr = (uint32_t)tmp_zone.start;
     uint32_t old_page_paddr = page_desc_get_frame(*old_page_desc);
     vmm_map_page(old_page_vaddr, old_page_paddr, PAGE_READABLE | PAGE_WRITABLE | PAGE_EXECUTABLE);
     memcpy((uint8_t*)to_vaddr, (uint8_t*)old_page_vaddr, VMM_PAGE_SIZE);
     /* Freeing */
     vmm_unmap_page(old_page_vaddr);
     zoner_free_zone(tmp_zone);
     return 0;
 }
References _vmm_ensure_cow_for_page(), _vmm_pspace_get_vaddr_of_active_ptable(), memcpy(), page_desc_get_frame(), page_desc_get_settings_ignore_cow(), page_desc_is_present(), page_desc_t, PAGE_EXECUTABLE, PAGE_READABLE, PAGE_WRITABLE, __zone::start, vmm_load_page(), vmm_map_page(), VMM_PAGE_SIZE, vmm_ptable_lookup(), vmm_unmap_page(), zoner_free_zone(), and zoner_new_zone().
vmm_copy_to_pdir()
void vmm_copy_to_pdir (pdirectory_t * pdir, uint8_t * src, uint32_t dest_vaddr, uint32_t length)
Definition at line 694 of file vmm.c.
 {
     pdirectory_t* prev_pdir = vmm_get_active_pdir();
     uint8_t* ksrc;
     if ((uint32_t)src < KERNEL_BASE) {
         /* Means that it's in user space, so it should be copied here. */
         ksrc = vmm_bring_to_kernel(src, length);
     } else {
         ksrc = src;
     }
     vmm_switch_pdir(pdir);
     _vmm_ensure_cow_for_range(dest_vaddr, length);
     uint8_t* dest = (uint8_t*)dest_vaddr;
     memcpy(dest, ksrc, length);
     if ((uint32_t)src < KERNEL_BASE) {
         kfree(ksrc);
     }
     vmm_switch_pdir(prev_pdir);
 }
References _vmm_ensure_cow_for_range(), KERNEL_BASE, kfree(), memcpy(), vmm_bring_to_kernel(), vmm_get_active_pdir(), and vmm_switch_pdir().
Referenced by _proc_load_bin(), and thread_fill_up_stack().
vmm_disable_paging()
void vmm_disable_paging ()
Definition at line 918 of file vmm.c.
 {
     system_disable_paging();
 }
References system_disable_paging().
vmm_enable_paging()
void vmm_enable_paging ()
Definition at line 913 of file vmm.c.
 {
     system_enable_paging();
 }
References system_enable_paging().
vmm_free_page()
int vmm_free_page (page_desc_t * page)
Definition at line 833 of file vmm.c.
 {
     uint32_t frame = page_desc_get_frame(*page);
     pmm_free_block((void*)(frame * VMM_PAGE_SIZE));
     page_desc_del_attrs(page, PAGE_DESC_PRESENT);
     return 0;
 }
References page_desc_del_attrs(), page_desc_get_frame(), PAGE_DESC_PRESENT, pmm_free_block(), and VMM_PAGE_SIZE.
vmm_free_pdir()
int vmm_free_pdir (pdirectory_t * pdir)
Definition at line 657 of file vmm.c.
 {
     if (!pdir) {
         return -EINVAL;
     }
     if (pdir == _vmm_kernel_pdir) {
         return -EACCES;
     }
     pdirectory_t* cur_pdir = vmm_get_active_pdir();
     vmm_switch_pdir(pdir);
     for (int i = 0; i < VMM_KERNEL_TABLES_START; i++) {
         vmm_free_ptable(i);
     }
     if (cur_pdir == pdir) {
         vmm_switch_pdir(_vmm_kernel_pdir);
     } else {
         vmm_switch_pdir(cur_pdir);
     }
     _vmm_free_pspace(pdir);
     kfree_aligned(pdir);
     return 0;
 }
References _vmm_free_pspace(), _vmm_kernel_pdir, EACCES, EINVAL, kfree_aligned(), vmm_free_ptable(), vmm_get_active_pdir(), VMM_KERNEL_TABLES_START, and vmm_switch_pdir().
Referenced by proc_free(), and proc_load().
vmm_free_ptable()
static int vmm_free_ptable (uint32_t ptable_indx) static
Definition at line 367 of file vmm.c.
 {
     if (_vmm_active_pdir == 0) {
         return -VMM_ERR_PDIR;
     }
     table_desc_t* ptable_desc = &_vmm_active_pdir->entities[ptable_indx];
     if (!table_desc_has_attrs(*ptable_desc, TABLE_DESC_PRESENT)) {
         return -EFAULT;
     }
     if (table_desc_has_attrs(*ptable_desc, TABLE_DESC_COPY_ON_WRITE)) {
         return -EFAULT;
     }
     pmm_free_block((void*)table_desc_get_frame(*ptable_desc));
     table_desc_del_frame(ptable_desc);
     return 0;
 }
References _vmm_active_pdir, EFAULT, pdirectory::entities, pmm_free_block(), TABLE_DESC_COPY_ON_WRITE, table_desc_del_frame(), table_desc_get_frame(), table_desc_has_attrs(), TABLE_DESC_PRESENT, table_desc_t, and VMM_ERR_PDIR.
Referenced by vmm_free_pdir().
vmm_get_active_pdir()
pdirectory_t* vmm_get_active_pdir ()
Definition at line 727 of file vmm.c.
 {
     return _vmm_active_pdir;
 }
References _vmm_active_pdir.
Referenced by signal_setup_stack_to_handle_signal(), vmm_copy_to_pdir(), vmm_free_pdir(), vmm_map_page(), and vmm_page_fault_handler().
vmm_get_kernel_pdir()
pdirectory_t* vmm_get_kernel_pdir ()
Definition at line 732 of file vmm.c.
 {
     return _vmm_kernel_pdir;
 }
References _vmm_kernel_pdir.
Referenced by tasking_create_kernel_thread(), and vmm_page_fault_handler().
vmm_load_page()
int vmm_load_page (uint32_t vaddr, uint32_t settings)
Definition at line 775 of file vmm.c.
 {
     uint32_t paddr = (uint32_t)pmm_alloc_block();
     if (!paddr) {
         /* TODO: Swap pages to make it able to allocate. */
         kpanic("NO PHYSICAL SPACE");
     }
     int res = vmm_map_page(vaddr, paddr, settings);
     uint8_t* dest = (uint8_t*)_vmm_round_floor_to_page(vaddr);
     memset(dest, 0, VMM_PAGE_SIZE);
     return res;
 }
References _vmm_round_floor_to_page(), kpanic(), memset(), pmm_alloc_block(), vmm_map_page(), and VMM_PAGE_SIZE.
Referenced by _signal_init_caller(), _vmm_copy_page_to_resolve_cow(), vmm_copy_page(), vmm_page_fault_handler(), and vmm_tune_page().
vmm_map_page()
int vmm_map_page (uint32_t vaddr, uint32_t paddr, uint32_t settings)
The function is supposed to map vaddr to paddr
Definition at line 393 of file vmm.c.
 {
     if (!_vmm_active_pdir) {
         return -VMM_ERR_PDIR;
     }
     bool is_writable = ((settings & PAGE_WRITABLE) > 0);
     bool is_readable = ((settings & PAGE_READABLE) > 0);
     bool is_executable = ((settings & PAGE_EXECUTABLE) > 0);
     bool is_not_cacheable = ((settings & PAGE_NOT_CACHEABLE) > 0);
     bool is_cow = ((settings & PAGE_COW) > 0);
     bool is_user = ((settings & PAGE_USER) > 0);
     table_desc_t* ptable_desc = vmm_pdirectory_lookup(_vmm_active_pdir, vaddr);
     if (!table_desc_is_present(*ptable_desc)) {
         vmm_allocate_ptable(vaddr);
     }
     ptable_t* ptable = (ptable_t*)_vmm_pspace_get_vaddr_of_active_ptable(vaddr);
     page_desc_t* page = vmm_ptable_lookup(ptable, vaddr);
     page_desc_set_attrs(page, PAGE_DESC_PRESENT);
     page_desc_set_frame(page, FRAME(paddr));
     if (is_writable) {
         page_desc_set_attrs(page, PAGE_DESC_WRITABLE);
     }
     if (is_user) {
         page_desc_set_attrs(page, PAGE_DESC_USER);
     }
     if (is_not_cacheable) {
         page_desc_set_attrs(page, PAGE_DESC_NOT_CACHEABLE);
     }
 #ifdef VMM_DEBUG
     log("Page mapped %x in pdir: %x", vaddr, vmm_get_active_pdir());
 #endif
     system_flush_tlb_entry(vaddr);
     return 0;
 }
References _vmm_active_pdir, _vmm_pspace_get_vaddr_of_active_ptable(), FRAME, log(), PAGE_COW, PAGE_DESC_NOT_CACHEABLE, PAGE_DESC_PRESENT, page_desc_set_attrs(), page_desc_set_frame(), page_desc_t, PAGE_DESC_USER, PAGE_DESC_WRITABLE, PAGE_EXECUTABLE, PAGE_NOT_CACHEABLE, PAGE_READABLE, PAGE_USER, PAGE_WRITABLE, system_flush_tlb_entry(), table_desc_is_present(), table_desc_t, vmm_allocate_ptable(), VMM_ERR_PDIR, vmm_get_active_pdir(), vmm_pdirectory_lookup(), and vmm_ptable_lookup().
Referenced by _bga_mmap(), _vmm_copy_page_to_resolve_cow(), _vmm_pspace_gen(), vmm_allocate_ptable(), vmm_copy_page(), vmm_load_page(), and vmm_map_pages().
vmm_map_pages()
int vmm_map_pages (uint32_t vaddr, uint32_t paddr, uint32_t n_pages, uint32_t settings)
The function is supposed to map a sequence of vaddrs to paddrs
Definition at line 461 of file vmm.c.
 {
     if ((paddr & 0xfff) || (vaddr & 0xfff)) {
         return -VMM_ERR_BAD_ADDR;
     }
     int status = 0;
     for (; n_pages; paddr += VMM_PAGE_SIZE, vaddr += VMM_PAGE_SIZE, n_pages--) {
         if (status = vmm_map_page(vaddr, paddr, settings) < 0) {
             return status;
         }
     }
     return 0;
 }
References VMM_ERR_BAD_ADDR, vmm_map_page(), and VMM_PAGE_SIZE.
Referenced by _vmm_map_kernel(), and _vmm_self_test().
vmm_new_forked_user_pdir()
pdirectory_t* vmm_new_forked_user_pdir ()
The function created a new user's pdir from the active pdir. After copying the task we need to flush tlb. To do that we have to to reload cr3 tlb entries.
Definition at line 628 of file vmm.c.
 {
     pdirectory_t* new_pdir = (pdirectory_t*)kmalloc_page_aligned();
     // coping all tables
     for (int i = 0; i < 1024; i++) {
         new_pdir->entities[i] = _vmm_active_pdir->entities[i];
     }
     new_pdir->entities[VMM_OFFSET_IN_DIRECTORY(pspace_zone.start)] = _vmm_pspace_gen();
     for (int i = 0; i < VMM_KERNEL_TABLES_START; i++) {
         table_desc_t* act_ptable_desc = &_vmm_active_pdir->entities[i];
         if (table_desc_has_attrs(*act_ptable_desc, TABLE_DESC_PRESENT)) {
             // COW: blocking current pdir
             table_desc_del_attrs(act_ptable_desc, TABLE_DESC_WRITABLE);
             table_desc_set_attrs(act_ptable_desc, TABLE_DESC_COPY_ON_WRITE);
             // COW: blocking new pdir
             table_desc_t* new_ptable_desc = &new_pdir->entities[i];
             table_desc_del_attrs(new_ptable_desc, TABLE_DESC_WRITABLE);
             table_desc_set_attrs(new_ptable_desc, TABLE_DESC_COPY_ON_WRITE);
         }
     }
     system_flush_whole_tlb();
     return new_pdir;
 }
References _vmm_active_pdir, _vmm_pspace_gen(), pdirectory::entities, kmalloc_page_aligned(), pspace_zone, __zone::start, system_flush_whole_tlb(), TABLE_DESC_COPY_ON_WRITE, table_desc_del_attrs(), table_desc_has_attrs(), TABLE_DESC_PRESENT, table_desc_set_attrs(), table_desc_t, TABLE_DESC_WRITABLE, VMM_KERNEL_TABLES_START, and VMM_OFFSET_IN_DIRECTORY.
Referenced by tasking_fork().
vmm_new_user_pdir()
pdirectory_t* vmm_new_user_pdir ()
USER PDIR FUNCTIONS The function is supposed to create all new user's pdir.
Definition at line 605 of file vmm.c.
 {
     pdirectory_t* pdir = (pdirectory_t*)kmalloc_page_aligned();
     for (int i = VMM_USER_TABLES_START; i < VMM_KERNEL_TABLES_START; i++) {
         pdir->entities[i] = 0;
     }
     for (int i = VMM_KERNEL_TABLES_START; i < 1024; i++) {
         if (!IS_INDIVIDUAL_PER_DIR(i)) {
             pdir->entities[i] = _vmm_kernel_pdir->entities[i];
         }
     }
     pdir->entities[VMM_OFFSET_IN_DIRECTORY(pspace_zone.start)] = _vmm_pspace_gen();
     return pdir;
 }
References _vmm_kernel_pdir, _vmm_pspace_gen(), pdirectory::entities, IS_INDIVIDUAL_PER_DIR, kmalloc_page_aligned(), pspace_zone, __zone::start, VMM_KERNEL_TABLES_START, VMM_OFFSET_IN_DIRECTORY, and VMM_USER_TABLES_START.
Referenced by proc_load(), and tasking_start_init_proc().
vmm_page_fault_handler()
int vmm_page_fault_handler (uint8_t info, uint32_t vaddr)
Definition at line 841 of file vmm.c.
 {
     if ((info & 0b11) == 0b11) {
         bool visited = false;
         if (_vmm_is_copy_on_write(vaddr)) {
             _vmm_resolve_copy_on_write(vaddr);
             visited = true;
         }
         if (_vmm_is_zeroing_on_demand(vaddr)) {
             _vmm_resolve_zeroing_on_demand(vaddr);
             visited = true;
         }
         if (!visited) {
             log_error("Write to not writable page");
             return SHOULD_CRASH;
         }
     } else {
         if ((info & 1) == 0) {
             if (PAGE_CHOOSE_OWNER(vaddr) == PAGE_USER && vmm_get_active_pdir() != vmm_get_kernel_pdir()) {
                 proc_t* holder_proc = tasking_get_proc_by_pdir(vmm_get_active_pdir());
                 if (!holder_proc) {
                     kpanic("No proc with the pdir\n");
                 }
                 proc_zone_t* zone = proc_find_zone(holder_proc, vaddr);
                 if (!zone) {
                     return SHOULD_CRASH;
                 }
 #ifdef VMM_DEBUG
                 log("Mmap page %x for %d pid: %x", vaddr, RUNNIG_THREAD->process->pid, zone->flags);
 #endif
                 vmm_load_page(vaddr, zone->flags);
                 if (zone->type == ZONE_TYPE_MAPPED_FILE_PRIVATLY) {
                     zone->fd->offset = PAGE_START(vaddr) - zone->start;
                     vfs_read(zone->fd, (uint8_t*)PAGE_START(vaddr), VMM_PAGE_SIZE);
                 }
             } else {
                 /* FIXME: Now we have a standard zone for kernel, but it's better to do the same thing as for user's pages */
                 vmm_load_page(vaddr, PAGE_READABLE | PAGE_WRITABLE | PAGE_EXECUTABLE);
             }
         } else {
             proc_zone_t* zone = proc_find_zone(RUNNIG_THREAD->process, vaddr);
             log_error("PF: info %d vaddr %x pdir %x pid %d", info, vaddr, vmm_get_active_pdir(), RUNNIG_THREAD->process->pid);
             return SHOULD_CRASH;
         }
     }
     return OK;
 }
References _vmm_is_copy_on_write(), _vmm_is_zeroing_on_demand(), _vmm_resolve_copy_on_write(), _vmm_resolve_zeroing_on_demand(), proc_zone::fd, proc_zone::flags, kpanic(), log(), log_error(), file_descriptor::offset, OK, PAGE_CHOOSE_OWNER, PAGE_EXECUTABLE, PAGE_READABLE, PAGE_START, PAGE_USER, PAGE_WRITABLE, proc_find_zone(), RUNNIG_THREAD, SHOULD_CRASH, proc_zone::start, tasking_get_proc_by_pdir(), proc_zone::type, vfs_read(), vmm_get_active_pdir(), vmm_get_kernel_pdir(), vmm_load_page(), VMM_PAGE_SIZE, and ZONE_TYPE_MAPPED_FILE_PRIVATLY.
Referenced by isr_handler().
vmm_pdirectory_lookup()
table_desc_t* vmm_pdirectory_lookup (pdirectory_t * pdir, uint32_t vaddr)
Definition at line 322 of file vmm.c.
 {
     if (pdir) {
         return &pdir->entities[VMM_OFFSET_IN_DIRECTORY(vaddr)];
     }
     return 0;
 }
References pdirectory::entities, and VMM_OFFSET_IN_DIRECTORY.
Referenced by _vmm_create_kernel_ptables(), _vmm_is_copy_on_write(), _vmm_is_zeroing_on_demand(), _vmm_pspace_init(), _vmm_resolve_copy_on_write(), _vmm_resolve_zeroing_on_demand(), vmm_allocate_ptable(), vmm_map_page(), and vmm_unmap_page().
vmm_ptable_lookup()
page_desc_t* vmm_ptable_lookup (ptable_t * ptable, uint32_t vaddr)
Definition at line 330 of file vmm.c.
 {
     if (ptable) {
         return &ptable->entities[VMM_OFFSET_IN_TABLE(vaddr)];
     }
     return 0;
 }
References ptable_t::entities, and VMM_OFFSET_IN_TABLE.
Referenced by _vmm_convert_vaddr2paddr(), _vmm_copy_page_to_resolve_cow(), _vmm_is_zeroing_on_demand(), _vmm_kernel_convert_vaddr2paddr(), _vmm_pspace_init(), _vmm_resolve_copy_on_write(), _vmm_resolve_zeroing_on_demand(), vmm_copy_page(), vmm_map_page(), vmm_test_pspace_vaddr_of_active_ptable(), vmm_tune_page(), and vmm_unmap_page().
vmm_setup()
int vmm_setup ()
PUBLIC FUNCTIONS
Definition at line 288 of file vmm.c.
 {
     zoner_init(0xc0400000);
     _vmm_split_pspace();
     _vmm_create_kernel_ptables();
     _vmm_pspace_init();
     _vmm_init_switch_to_kernel_pdir();
     _vmm_map_kernel();
     zoner_place_bitmap();
     kmalloc_init();
     if (_vmm_self_test() < 0) {
         kpanic("VMM SELF TEST Not passed");
     }
     return 0;
 }
References _vmm_create_kernel_ptables(), _vmm_init_switch_to_kernel_pdir(), _vmm_map_kernel(), _vmm_pspace_init(), _vmm_self_test(), _vmm_split_pspace(), kmalloc_init(), kpanic(), zoner_init(), and zoner_place_bitmap().
Referenced by stage3().
vmm_switch_pdir()
int vmm_switch_pdir (pdirectory_t * pdir)
CPU BASED FUNCTIONS
Definition at line 896 of file vmm.c.
 {
     if (((uint32_t)pdir & (VMM_PAGE_SIZE - 1)) != 0) {
         kpanic("vmm_switch_pdir: wrong pdir");
     }
     system_disable_interrupts();
     if (_vmm_active_pdir == pdir) {
         system_enable_interrupts();
         return 0;
     }
     _vmm_active_pdir = pdir;
     system_set_pdir((uint32_t)_vmm_convert_vaddr2paddr((uint32_t)pdir));
     system_enable_interrupts();
     return 0;
 }
References _vmm_active_pdir, _vmm_convert_vaddr2paddr(), kpanic(), system_disable_interrupts(), system_enable_interrupts(), system_set_pdir(), and VMM_PAGE_SIZE.
Referenced by proc_load(), signal_setup_stack_to_handle_signal(), switchuvm(), vmm_copy_to_pdir(), and vmm_free_pdir().
vmm_test_pspace_vaddr_of_active_ptable()
static bool vmm_test_pspace_vaddr_of_active_ptable () static
Definition at line 941 of file vmm.c.
 {
     uint32_t vaddr = 0xc0000000;
     ptable_t* pt = _vmm_pspace_get_vaddr_of_active_ptable(vaddr);
     page_desc_t* ppage = vmm_ptable_lookup(pt, vaddr);
     page_desc_del_attrs(ppage, PAGE_DESC_PRESENT);
     uint32_t* kek1 = (uint32_t*)vaddr;
     *kek1 = 1;
     // should cause PF
     while (1) {
     }
     return true;
 }
References _vmm_pspace_get_vaddr_of_active_ptable(), page_desc_del_attrs(), PAGE_DESC_PRESENT, page_desc_t, and vmm_ptable_lookup().
vmm_tune_page()
int vmm_tune_page (uint32_t vaddr, uint32_t settings)
PF HANDLER FUNCTIONS
Definition at line 741 of file vmm.c.
 {
     bool is_writable = ((settings & PAGE_WRITABLE) > 0);
     bool is_readable = ((settings & PAGE_READABLE) > 0);
     bool is_executable = ((settings & PAGE_EXECUTABLE) > 0);
     bool is_not_cacheable = ((settings & PAGE_NOT_CACHEABLE) > 0);
     bool is_cow = ((settings & PAGE_COW) > 0);
     bool is_user = ((settings & PAGE_USER) > 0);
     ptable_t* ptable = (ptable_t*)_vmm_pspace_get_vaddr_of_active_ptable(vaddr);
     page_desc_t* page = vmm_ptable_lookup(ptable, vaddr);
     if (page_desc_is_present(*page)) {
         is_user ? page_desc_set_attrs(page, PAGE_DESC_USER) : page_desc_del_attrs(page, PAGE_DESC_USER);
         is_writable ? page_desc_set_attrs(page, PAGE_DESC_WRITABLE) : page_desc_del_attrs(page, PAGE_DESC_WRITABLE);
         is_not_cacheable ? page_desc_set_attrs(page, PAGE_DESC_NOT_CACHEABLE) : page_desc_del_attrs(page, PAGE_DESC_NOT_CACHEABLE);
     } else {
         vmm_load_page(vaddr, settings);
     }
     system_flush_tlb_entry(vaddr);
     return 0;
 }
References _vmm_pspace_get_vaddr_of_active_ptable(), PAGE_COW, page_desc_del_attrs(), page_desc_is_present(), PAGE_DESC_NOT_CACHEABLE, page_desc_set_attrs(), page_desc_t, PAGE_DESC_USER, PAGE_DESC_WRITABLE, PAGE_EXECUTABLE, PAGE_NOT_CACHEABLE, PAGE_READABLE, PAGE_USER, PAGE_WRITABLE, system_flush_tlb_entry(), vmm_load_page(), and vmm_ptable_lookup().
Referenced by _signal_init_caller(), and vmm_tune_pages().
vmm_tune_pages()
int vmm_tune_pages (uint32_t vaddr, uint32_t length, uint32_t settings)
Definition at line 765 of file vmm.c.
 {
     uint32_t page_addr = PAGE_START(vaddr);
     while (page_addr < vaddr + length) {
         vmm_tune_page(page_addr, settings);
         page_addr += VMM_PAGE_SIZE;
     }
     return 0;
 }
References PAGE_START, VMM_PAGE_SIZE, and vmm_tune_page().
Referenced by shared_buffer_create().
vmm_unmap_page()
int vmm_unmap_page (uint32_t vaddr)
Definition at line 437 of file vmm.c.
 {
     if (!_vmm_active_pdir) {
         return -VMM_ERR_PDIR;
     }
     table_desc_t* ptable_desc = vmm_pdirectory_lookup(_vmm_active_pdir, vaddr);
     if (!table_desc_is_present(*ptable_desc)) {
         return -VMM_ERR_PTABLE;
     }
     ptable_t* ptable = (ptable_t*)_vmm_pspace_get_vaddr_of_active_ptable(vaddr);
     page_desc_t* page = vmm_ptable_lookup(ptable, vaddr);
     page_desc_del_attrs(page, PAGE_DESC_PRESENT);
     page_desc_del_attrs(page, PAGE_DESC_WRITABLE);
     page_desc_del_frame(page);
     system_flush_tlb_entry(vaddr);
     return 0;
 }
References _vmm_active_pdir, _vmm_pspace_get_vaddr_of_active_ptable(), page_desc_del_attrs(), page_desc_del_frame(), PAGE_DESC_PRESENT, page_desc_t, PAGE_DESC_WRITABLE, system_flush_tlb_entry(), table_desc_is_present(), table_desc_t, VMM_ERR_PDIR, VMM_ERR_PTABLE, vmm_pdirectory_lookup(), and vmm_ptable_lookup().
Referenced by _vmm_copy_page_to_resolve_cow(), _vmm_pspace_gen(), and vmm_copy_page().
vmm_zero_user_pages()
void vmm_zero_user_pages (pdirectory_t * pdir)
Definition at line 718 of file vmm.c.
 {
     for (int i = 0; i < VMM_KERNEL_TABLES_START; i++) {
         table_desc_t* ptable_desc = &pdir->entities[i];
         table_desc_del_attrs(ptable_desc, TABLE_DESC_WRITABLE);
         table_desc_set_attrs(ptable_desc, TABLE_DESC_ZEROING_ON_DEMAND);
     }
 }
References pdirectory::entities, table_desc_del_attrs(), table_desc_set_attrs(), table_desc_t, TABLE_DESC_WRITABLE, TABLE_DESC_ZEROING_ON_DEMAND, and VMM_KERNEL_TABLES_START.
Variable Documentation
_vmm_active_pdir
pdirectory_t* _vmm_active_pdir static
Definition at line 33 of file vmm.c.
Referenced by _vmm_init_switch_to_kernel_pdir(), _vmm_is_copy_on_write(), _vmm_is_zeroing_on_demand(), _vmm_pspace_get_vaddr_of_active_pdir(), _vmm_pspace_init(), _vmm_resolve_copy_on_write(), _vmm_resolve_zeroing_on_demand(), _vmm_split_pspace(), vmm_allocate_ptable(), vmm_free_ptable(), vmm_get_active_pdir(), vmm_map_page(), vmm_new_forked_user_pdir(), vmm_switch_pdir(), and vmm_unmap_page().
_vmm_kernel_pdir
pdirectory_t* _vmm_kernel_pdir static
Definition at line 32 of file vmm.c.
Referenced by _vmm_create_kernel_ptables(), _vmm_init_switch_to_kernel_pdir(), _vmm_split_pspace(), vmm_free_pdir(), vmm_get_kernel_pdir(), and vmm_new_user_pdir().
kernel_ptables_start_paddr
uint32_t kernel_ptables_start_paddr static
Definition at line 35 of file vmm.c.
Referenced by _vmm_kernel_convert_vaddr2paddr(), _vmm_map_init_kernel_pages(), _vmm_pspace_init(), and _vmm_split_pspace().
pspace_zone
zone_t pspace_zone static
Definition at line 34 of file vmm.c.
Referenced by _vmm_create_kernel_ptables(), _vmm_free_pspace(), _vmm_pspace_gen(), _vmm_pspace_get_nth_active_ptable(), _vmm_pspace_init(), _vmm_split_pspace(), vmm_new_forked_user_pdir(), and vmm_new_user_pdir().