oneOS: include/mem/vmm/zoner.h File Reference
zoner.h File Reference
#include <types.h>
Data Structures
struct __zone
Typedefs
typedef struct __zone zone_t
Functions
void zoner_init (uint32_t start_vaddr)
void zoner_place_bitmap ()
zone_t zoner_new_zone (uint32_t size)
int zoner_free_zone (zone_t zone)
Typedef Documentation
zone_t
typedef struct __zone zone_t
Definition at line 1 of file zoner.h.
Function Documentation
zoner_free_zone()
int zoner_free_zone (zone_t zone)
Returns new zone vaddr start. Note, the function does NOT map this vaddr, it's on your own.
Definition at line 102 of file zoner.c.
 {
     /* Checking if it was allocated with bitmap */
     if (zone.start < _zoner_next_vaddr) {
         return -EPERM;
     }
     int start = ZONER_TO_BITMAP_INDEX(zone.start);
     uint32_t blocks = zone.len / VMM_PAGE_SIZE;
     return bitmap_unset_range(bitmap, start, blocks);
 }
References _zoner_next_vaddr, bitmap_unset_range(), EPERM, __zone::len, __zone::start, VMM_PAGE_SIZE, and ZONER_TO_BITMAP_INDEX.
Referenced by _vmm_copy_page_to_resolve_cow(), _vmm_pspace_gen(), ringbuffer_free(), thread_free(), and vmm_copy_page().
zoner_init()
void zoner_init (uint32_t start_vaddr)
Definition at line 58 of file zoner.c.
 {
     _zoner_next_vaddr = start_vaddr;
 }
References _zoner_next_vaddr.
Referenced by vmm_setup().
zoner_new_zone()
zone_t zoner_new_zone (uint32_t size)
Returns new zone vaddr start. Note, the function does NOT map this vaddr, it's on your own.
Definition at line 67 of file zoner.c.
 {
     if (size % VMM_PAGE_SIZE) {
         size += VMM_PAGE_SIZE - (size % VMM_PAGE_SIZE);
     }
     zone_t zone;
     if (!_zoner_bitmap_set) {
         zone.start = _zoner_new_vzone(size);
     } else {
         uint32_t blocks = size / VMM_PAGE_SIZE;
         int start = bitmap_find_space(bitmap, blocks);
         if (start < 0) {
             zone.start = 0;
             zone.len = 0;
             return zone;
         }
         if (bitmap_set_range(bitmap, start, blocks) < 0) {
             zone.start = 0;
         } else {
             zone.start = ZONER_FROM_BITMAP_INDEX(start);
         }
     }
     zone.len = size;
     return zone;
 }
References _zoner_bitmap_set, _zoner_new_vzone(), bitmap_find_space(), bitmap_set_range(), __zone::len, __zone::start, VMM_PAGE_SIZE, and ZONER_FROM_BITMAP_INDEX.
Referenced by _signal_init_caller(), _vmm_copy_page_to_resolve_cow(), _vmm_pspace_gen(), _vmm_split_pspace(), kmalloc_init(), kthread_setup(), ringbuffer_create(), ringbuffer_create_std(), shared_buffer_init(), thread_setup(), thread_setup_main(), and vmm_copy_page().
zoner_place_bitmap()
void zoner_place_bitmap ()
zoner_place_bitmap places bitmap at _zoner_start_vaddr.
Definition at line 49 of file zoner.c.
 {
     _zoner_bitmap = (uint8_t*)_zoner_new_vzone(ZONER_BITMAP_SIZE);
     bitmap = bitmap_wrap(_zoner_bitmap, ZONER_BITMAP_SIZE * 8);
     memset(_zoner_bitmap, 0, ZONER_BITMAP_SIZE * 8);
     _zoner_bitmap_set = true;
     bitmap_set_range(bitmap, 0, ZONER_TO_BITMAP_INDEX(_zoner_next_vaddr));
 }
References _zoner_bitmap, _zoner_bitmap_set, _zoner_new_vzone(), _zoner_next_vaddr, bitmap_set_range(), bitmap_wrap(), memset(), ZONER_BITMAP_SIZE, and ZONER_TO_BITMAP_INDEX.
Referenced by vmm_setup().